- sharding/README.md
Changing _--datadir=~/Desktop/datadir_ to the standard path _--datadir=/path/to/your/datadir_
> update READMEs datadir path to /path/to/your/datadir

- sharding/blocks.go
- sharding/genesis.json
- sharding/transactions.go
- sharding/transactions_test.go
- sharding/vm.go
Work in progress. Do not merge.
Feature status:
TODOs before submit:
> WIP: Modifying Block & Transaction Protocol Primitives for Sharding

- sharding/collation.go
- sharding/collation_test.go
> Collation and CollationHeader types

- sharding/client.go
> Change from ioutil to bufio scanner

- cmd/geth/main.go
- cmd/geth/shardingcmd.go
- cmd/utils/flags.go
Add cli entry point for sharding-collator, and refactor shardingClient to validatorClient and collatorClient
> add cli entrypoint for sharding-collator

- README.md
> Changing main readme to reflect changes

- sharding/collation.go
Updating collation fields to align with phase 1 spec
reference: https://ethresear.ch/t/sharding-phase-1-spec/1407
> Align collation header fields with phase 1 spec

- sharding/config.go
update shard count to 1 to match phase 1 spec
> changed shard count to 1

- sharding/collator/collator.go
- sharding/collator/collator_test.go
- sharding/config.go
- sharding/config_test.go
Updated sharding config with the latest minimal sharding protocol spec.
I'd like to keep this PR open, until the minimal sharding spec is more finalized.
> Align sharding config with minimal sharding protocol

- sharding/collation_test.go
Removed outdated tests that were causing Travis failures. This addresses #104 through a few simple fixes.
Resolves #104
> Fixing #104 By Removing Outdated Tests

- cmd/geth/usage.go
- cmd/utils/flags.go
Before:
```
geth --help 
...
MISC OPTIONS:
--deposit   To become a notary with your sharding client, 100 ETH will be deposited from user's account into SMC
--help, -h  show help
```
After:
```
geth --help
...
SHARDING OPTIONS:
--deposit  To become a notary with your sharding client, 1000 ETH will be deposited from user's account into SMC
...
```
> Add sharding flags option to usage.

- sharding/client/client.go
- sharding/notary/notary.go
- sharding/notary/notary_client.go
- sharding/notary/notary_test.go
> Only deposit when --deposit is present 

- sharding/notary/notary.go
- sharding/notary/notary_test.go
> Only deposit as notary if not already deposited

- sharding/README.md
Looks like a section that got revised a few times and had an extra word left in.
> Just an awkward typo

- cmd/geth/shardingcmd.go
- cmd/geth/usage.go
- sharding/node/node.go
- sharding/node/utils.go
Changes:
- fix logging of SMC address 
- actor flag in sharding help group
- ensure rpcClient is not nil before calling close
> Quick fixes

- README.md
- sharding/CONTRIBUTING.md
- sharding/READINGS.md
Hi all,
Many have been asking to get involved in contributing to Prysmatic Labs and our contribution guidelines have not been as friendly toward sharding beginners. In this PR I am adding a comprehensive contributions doc that details the roles of both core contributors and part-time contributors. I am also creating a READINGS.md doc that includes necessary resources for developers to catch up on Ethereum protocol development, sharding research, and Go.
> Editing Our Contribution Guidelines and Required Readings

- sharding/node/utils.go
Fixed address logging from `Str()` to `Hex()`
> Sharding/node: Address Logging To Hex

- sharding/CONTRIBUTING.md
- sharding/READINGS.md
Made the following changes to our markdown:
1. We need to squash commits before merge
2. Added the awesome Go Ethereum book from today
> Update Contributing and Reading List Markdowns

- beacon-chain/BUILD.bazel
- beacon-chain/LICENSE.md
- beacon-chain/README.md
- beacon-chain/config.go
- beacon-chain/types/BUILD.bazel
- beacon-chain/types/block.go
- beacon-chain/types/state.go
Addresses #248 and enforces bazel visibility rules
> Move beacon-chain to geth-sharding repo

- sharding/node/BUILD.bazel
- sharding/node/backend_test.go
- sharding/simulator/service_test.go
Hi all,
This adds tests for fetching and registering a service in a node backend and adds a quick fix for 100% simulator coverage.
> Test for Node Fetch and Register Service, 100% Simulator Coverage

- LICENSE.md
This PR updates our project license to GPLv3
> Update License to GPLv3

- .clabot
Adding the core team members and CLA contributors.
> Adding CLABot File

- README.md
- client/CONTRIBUTING.md
Some small fixes in docs. Not sure about the gitter ones, currently the `prysmaticlabs/prysm` room gives 404.
> Update readme and contributing links

- .travis.yml
- README.md
- WORKSPACE
- beacon-chain/BUILD.bazel
- client/BUILD.bazel
> Add Docker Container Images for beacon-chain and client

- client/proposer/service.go
- client/simulator/BUILD.bazel
- client/simulator/service.go
- client/syncer/service.go
- client/syncer/service_test.go
- shared/p2p/service.go
- shared/p2p/service_test.go
> Add Feed Subscribe() Convenience Method

- beacon-chain/powchain/BUILD.bazel
- beacon-chain/powchain/service.go
- beacon-chain/powchain/service_test.go
This is a partial fix for #325. I think they'll be easier to consume if the PR's smaller.
> Merge PoWChain Goroutines Together

- .gometalinter.json
- beacon-chain/node/node.go
- beacon-chain/sync/service.go
- client/proposer/proposer.go
- client/proposer/service.go
- client/simulator/service.go
- client/types/collation.go
- client/types/shard.go
- contracts/deployVRC/deployVRC.go
- shared/debug/debug.go
- shared/p2p/options.go
- shared/p2p/service.go
Add a security linter and resolve outstanding issues.
https://github.com/securego/gosec
> Add Security Linter: gosec

- beacon-chain/blockchain/core_test.go
Wrote a simple method to facilitate creating blocks in `core_test.go`
> Quick Test Helper for Creating Blocks

- beacon-chain/simulator/service.go
- client/attester/service.go
- client/mainchain/smc_client_test.go
- client/observer/service.go
- client/simulator/service.go
- client/syncer/handlers_test.go
- client/syncer/service.go
- client/txpool/service.go
- client/types/collation.go
Went through all mentions of `struct` and made sure they're initializations were defined explicitly. I'd like someone to make sure I got them all.
Resolves #342
> Change all struct initializations to be explicit (#342)

- README.md
https://github.com/prysmaticlabs/prysm#step-2-running-a-beacon-node need websocket
>  fix command mistake and enable geth websocket server for beacon node

- beacon-chain/sync/service_test.go
- beacon-chain/types/block.go
- beacon-chain/types/state.go
- beacon-chain/utils/shuffle.go
- client/beacon/service.go
- coverage.sh
> Use Blake2b Sum512 Instead of 256

- beacon-chain/rpc/service_test.go
`TestLatestCrystallizedState` can fail if it reaches the end of the test before executing [stream.Send](https://github.com/rawfalafel/geth-sharding/blob/59febac3930e0ccd0d3a2e128822a49dabec4fd9/beacon-chain/rpc/service.go#L161). This changeset ensures that the service goroutine finishes completely.
> Address race condition in rpc/service_test

- beacon-chain/BUILD.bazel
- client/BUILD.bazel
- coverage.sh
Updated docker rules to use manual tag. `bazel build //...` in mac worked fine after 👍
> Updated Docker Rules

- beacon-chain/blockchain/core.go
- beacon-chain/blockchain/service.go
- beacon-chain/casper/sharding.go
- beacon-chain/casper/sharding_test.go
- beacon-chain/casper/validator.go
- beacon-chain/params/config.go
- beacon-chain/rpc/service.go
- beacon-chain/types/state_test.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1/services.proto
- validator/beacon/service.go
- validator/beacon/service_test.go
This replaces all mentions of height with slot throughout the whole app since height is of the old spec.
#442
> Replace height with slot client wide

- beacon-chain/blockchain/core.go
- beacon-chain/blockchain/core_test.go
- beacon-chain/blockchain/service_test.go
- beacon-chain/casper/sharding_test.go
- beacon-chain/casper/validator.go
- beacon-chain/types/state.go
- beacon-chain/types/state_test.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/messages.proto
This is for #469, let me know if there is anything missing.
> Change IndicesForSlots to ShardsAndCommitteesForSlots

- .travis.yml
Hopefully, this can answer the question "does this work on Mac" without any negative side effects (slow travis, new test timeouts, etc). 
Also, hopefully it works :)
> Add MacOS to travis CI

- beacon-chain/powchain/service.go
- beacon-chain/powchain/service_test.go
Specifically when matching with the validator registration contract.
> Allow users to use 0x prefix for their pubkey

- beacon-chain/node/p2p_config.go
- shared/debug/debug.go
- shared/p2p/discovery.go
- shared/p2p/options.go
- shared/p2p/p2p.go
- shared/p2p/peer.go
- shared/p2p/register_topic_example_test.go
- shared/p2p/service_test.go
- validator/node/node.go
- validator/node/p2p_config.go
Part of #497
---
Cleaned up some TODOs so that they are in the proper format.
> format and cleanup some TODOs

- docs/READINGS.md
> V's Sharding Talk from IC3-ETH bootcamp

- beacon-chain/sync/service.go
- shared/database/inmemory.go
- validator/beacon/service_test.go
- validator/node/node.go
- validator/proposer/service.go
- validator/types/collation_test.go
This is part of #540.
---
This PR exists to clean-up and add an issue/PR number to every TODO created by @rauljordan in our repo.
> Finished TODO Cleanup

- validator/types/collation.go
> Clean-Up Todos

- beacon-chain/sync/initial-sync/service.go
- shared/database/database.go
Part of #497
---
Resolve final TODOs to unblock #497 and #540
> More todos

- beacon-chain/blockchain/core.go
- beacon-chain/blockchain/core_test.go
- beacon-chain/blockchain/service_test.go
- beacon-chain/rpc/service.go
- beacon-chain/rpc/service_test.go
- beacon-chain/types/block.go
- beacon-chain/types/block_test.go
Remaining work of https://github.com/prysmaticlabs/prysm/issues/495
> Initialize ActiveStateHash and CrystallizedStateHash for Genesis BeaconBlock

- .travis-bazelrc
- .travis.yml
- scripts/coverage.sh
> Enable Remote Caching & Use Host GO Version

- beacon-chain/utils/shuffle.go
This resolves https://github.com/prysmaticlabs/prysm/issues/610
---
The only part we had missing was hashing the seed every iteration of the loop over the validator count. This PR fixes that.
> Fix Shuffling Algorithm

- README.md
This PR updates a few README items to be aligned with the latest release.
> Edit Readme Instructions

- .travis.yml
Moving to buildkite soon where this will be easier to implement
> Disable remote caching for now

- .buildkite-bazelrc
This should fix some delays in builds
> Increase local resources for Bazel to match agent 

- docs/READINGS.md
Added a few useful eWASM learning material into our reading markdown
> eWASM Readings Shared by Lane

- beacon-chain/casper/validator.go
- beacon-chain/rpc/service.go
- beacon-chain/sync/initial-sync/service_test.go
- genesis.json
Still getting this issue when trying to run the validator:
```
[2018-10-12 12:55:18] FATAL beacon: could not fetch genesis time and latest canonical state from beacon node: rpc error: code = Unknown desc = could not get assignments for public keys: can't find slot number for validator with public key 414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141414141
```
> [WIP] Partial fix for the validator code

- beacon-chain/casper/validator.go
- beacon-chain/casper/validator_test.go
- beacon-chain/types/active_state.go
- beacon-chain/types/block.go
- beacon-chain/types/crystallized_state.go
- shared/bitutil/bit.go
- shared/bitutil/bit_test.go
- shared/testutil/checkbit.go
Resolves  #571 
---
Added check for length to CheckBit method and updated the code where it is used
> Add check for validity to CheckBit method

- beacon-chain/types/active_state.go
- beacon-chain/types/active_state_test.go
- beacon-chain/types/block.go
> Fix getSignedParentHashes

- beacon-chain/casper/incentives.go
- beacon-chain/casper/incentives_test.go
- beacon-chain/casper/sharding.go
- beacon-chain/casper/sharding_test.go
- beacon-chain/casper/validator.go
- beacon-chain/casper/validator_test.go
- beacon-chain/params/config.go
- beacon-chain/types/crystallized_state.go
- beacon-chain/types/crystallized_state_test.go
- beacon-chain/utils/shuffle.go
- beacon-chain/utils/shuffle_test.go
This changeset converts remaining config values to `uint64` for consistency. Note that the balance delta may be negative, but the balance itself is always non-negative.
> Convert remaining int config values to uint64

- beacon-chain/types/block.go
- beacon-chain/types/block_test.go
> Fix parent attestation check

- beacon-chain/blockchain/service_test.go
- beacon-chain/casper/validator.go
- beacon-chain/db/block.go
- beacon-chain/powchain/service_test.go
- beacon-chain/rpc/service.go
- beacon-chain/sync/service.go
- beacon-chain/types/active_state.go
- beacon-chain/types/block.go
- validator/beacon/service.go
- validator/types/shard.go
- validator/types/shard_test.go
Fixed up error strings to be consistent across the code base.
> Align Error String Consistency

- README.md
Part of #654
---
To provide instructions for running Prysm from Windows.
Added a section heading and a few paragraphs of instructions to readme.MD
> Update readme file to include section on running under windows

- README.md
- beacon-chain/README.md
- beacon-chain/params/config.go
- contracts/README.md
- docs/DEMO_INFORMATION.md
- docs/MAINCHAIN.md
- docs/READINGS.md
- docs/VALIDATOR_REGISTRATION.md
- k8s/README.md
- proto/README.md
- shared/bls/bls.go
- shared/legacyutil/convert_transaction.go
- shared/p2p/p2p.go
- validator/README.md
- validator/attester/service.go
- validator/main.go
- validator/node/node.go
- validator/proposer/service.go
> Update Ethereum 2.0 to Ethereum Serentity

- beacon-chain/blockchain/service.go
- beacon-chain/blockchain/service_test.go
> Always Pass An Item Through Channel When Processing Blocks

- WORKSPACE
> Batch renovate updates

- beacon-chain/blockchain/service.go
- beacon-chain/blockchain/service_test.go
- contracts/sharding-manager-contract/sharding_manager_test.go
- shared/keystore/keystore.go
I will be turning up the linter on buildkite to catch these issues.
> Fix error message lint issues

- tools/bootnode/BUILD.bazel
This pushes a docker image for the bootnode tool.
> Add Bootnode Docker Target

- WORKSPACE
Updates dependencies from renovate
> Bulk Update

- CONTRIBUTING.md
simple typo!
[Resolves] #956
---
Just a simple typo...left off the "r" in for.
> Typo in CONTRIBUTING.MD

- beacon-chain/sync/sync-querier/service.go
- shared/service_registry.go
Also added a bit of additional logging so the problem might be more apparent in the future
> Fix service registry breakage

- beacon-chain/types/block.go
> Add TODO for Ancestor Hashes Check

- beacon-chain/main.go
- beacon-chain/node/p2p_config.go
- shared/cmd/flags.go
- shared/p2p/BUILD.bazel
- shared/p2p/options.go
- shared/p2p/options_test.go
- shared/p2p/service.go
- validator/node/p2p_config.go
It was random, but needs to be configurable for test network
> Added flag for p2p port

- WORKSPACE
- beacon-chain/chaintest/backend/simulated_backend_test.go
- beacon-chain/core/state/state_transition_test.go
- beacon-chain/core/validators/committees_test.go
- beacon-chain/simulator/service_test.go
- beacon-chain/utils/shuffle.go
- beacon-chain/utils/shuffle_test.go
- shared/params/config.go
This PR updates our current shuffle function to align with spec 
Reference: https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#shuffle
> Update Shuffle Function

- beacon-chain/chaintest/backend/simulated_backend.go
- beacon-chain/core/state/state_transition.go
- beacon-chain/core/state/state_transition_test.go
- beacon-chain/core/validators/validator.go
- beacon-chain/core/validators/validator_test.go
- shared/params/config.go
Imlemented the following helper functions to retrieve total validator balances:
- `is_active_validator`
- `get_active_validator_indices`
- `get_active_validators`
- `get_total_balance`
-  updated config value MAX_DEPOSIT
> Helper Functions to Retrieve Total Validator Balances

- contracts/validator-registration-contract/SafeMath.sol
- contracts/validator-registration-contract/validator_registration.sol
Added SafeMath.sol to Validator Registration contract to prevent uint256 underflow/overflow
[Part of| #1144
---
> Add SafeMath.sol to Validator Registration contract

- scripts/update-go-pbs.sh
Resolves #1191 
---
I created a bash script that builds all `proto` files and copies them to their appropriate locations.
> Add script to generate pb.go files

- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/epoch/epoch_processing_test.go
This PR implements logic to update penalized exit balances, at the end of the epoch processing, we port over the current penalized exit balances onto next epoch
As seen in spec:
```
Let e = state.slot // EPOCH_LENGTH. Set state.latest_penalized_exit_balances[(e+1) % LATEST_PENALIZED_EXIT_LENGTH] = state.latest_penalized_exit_balances[e % LATEST_PENALIZED_EXIT_LENGTH]
```
> Implement Logic to Update Penalized Exit Balances

- CONTRIBUTING.md
- shared/p2p/BUILD.bazel
- shared/p2p/service_test.go
Resolves #543  
---
I have created what I understand is a roundtrip with a broadcast call and 2 hosts subscribed to the topic. I still consider this a WIP tasks, I want you to check if this is what we were expecting and if it is maybe I can clean this a little bit and add a timeout in the end too.
> add unit test for test broadcast

- .gometalinter.json
- .travis.yml
- beacon-chain/blockchain/fork_choice_test.go
- beacon-chain/chaintest/backend/helpers.go
- beacon-chain/chaintest/backend/simulated_backend.go
- beacon-chain/sync/initial-sync/service.go
- shared/ssz/decode_test.go
Resolves  #1355 , and also fixes other linter errors related to goimports.
> Fix travis and Other Linter Errors

- beacon-chain/core/blocks/block_operations.go
Fixes https://github.com/prysmaticlabs/prysm/issues/1376
> Update ProcessValidatorExits spec definition in comment

- shared/ssz/decode.go
- shared/ssz/decode_test.go
Resolves #1383 
Now we will check both cases when input is too short or too long.
> More Strict Input Length Check when Decoding Struct

- contracts/deposit-contract/deployContract/BUILD.bazel
This was accidentally removed in #1343
> Restore deployVRC docker image 

- beacon-chain/powchain/service.go
- beacon-chain/powchain/service_test.go
Before:
[2019-02-05 08:59:31]  INFO powchain: Validator registered in VRC with public key and index merkle tree index=4294967304 publicKey=[231 90 238 1 160 195 142 206 189 86 240 119 213 150 160 191 46 95 186 189 233 151 139 16 52 146 156 51 82 73 183 218 26 78 142 115 202 45 65 16 120 4 134 10 67 68 188 239]
After:
[2019-02-05 09:01:29]  INFO powchain: Validator registered in deposit contract merkleTreeIndex=4294967304 publicKey=0xe75aee01a0c38ecebd56f077d596a0bf2e5fbabde9978b1034929c335249b7da1a4e8e73ca2d41107804860a4344bcef
> Use a better message for notifying of a new deposit

- shared/params/config.go
This simplifies how our demo config is declared, instead of re declaring each element in the struct , we simply use the default config and modify what is required.
> Simplify Config

- validator/BUILD.bazel
> Temporarily disable static linking for validator docker image 

- shared/keystore/BUILD.bazel
- shared/keystore/key_test.go
- shared/keystore/keystore_test.go
> Restore testutil usage removed in #1607

- WORKSPACE
I knew this day would come when we started using github tags, but I never imagined it would be on this scale.
#1704
> Add gx/ to several deleted tags

- WORKSPACE
> Remove all tag based imports

- beacon-chain/rpc/validator_server.go
This log was happening for every RPC call to get assignments and didn't provide much meaningful information at info level
> Change this log to debug because its very verbose

- beacon-chain/BUILD.bazel
It was causing SEG FAULT errors
> Set static to off for cgo built beacon-chain

- beacon-chain/core/state/metrics.go
Self-explanatory: adds instrumentation metric for tracking the last processed slot number
> Add slot metric

- beacon-chain/core/state/metrics.go
> Use promauto to automatically register metrics

- renovate.json
And only run between 00:00 and 02:00 daily (to reduce email spam)
> Set renovate limits to unlimited

- beacon-chain/core/state/metrics.go
subtract  params.BeaconConfig().GenesisEpoch for logging
> Fix Finalize and Justified Slot Stats

- beacon-chain/blockchain/service.go
- beacon-chain/chaintest/backend/simulated_backend.go
- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block.go
- beacon-chain/core/blocks/block_test.go
- beacon-chain/core/state/BUILD.bazel
- beacon-chain/core/state/transition.go
- beacon-chain/rpc/attester_server.go
- beacon-chain/rpc/proposer_server.go
Added spans for processing slots in `state` and `block` package, this is getting called by chain service
> Add Spans for Processing Slots

- shared/params/config.go
> Set Eth1FollowDistance to 16 pow blocks for demo config

- beacon-chain/sync/regular_sync.go
- beacon-chain/sync/regular_sync_test.go
- shared/p2p/BUILD.bazel
- shared/p2p/service.go
- shared/p2p/service_test.go
> Recover from a panic in p2p

- beacon-chain/blockchain/service.go
- beacon-chain/blockchain/service_test.go
- validator/client/service.go
The problem is that some race condition occurs where the initial state isn't sent while validators are waiting.
> Fix wait for activation

- beacon-chain/sync/regular_sync.go
- beacon-chain/sync/regular_sync_test.go
> Fix Panic in Message Recovery

- beacon-chain/sync/initial-sync/service.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/common/messages.pb.go
- proto/faucet/faucet.pb.go
- proto/sharding/p2p/v1/messages.pb.go
- proto/testing/test.pb.go
- shared/hashutil/hash_test.go
- tools/cluster-pk-manager/server/watchtower.go
This PR, cleans up how we send and respond to batched requests , so that there are reduced debug logs
> Clean Up Batched Request

- validator/client/BUILD.bazel
- validator/client/validator_propose.go
- validator/client/validator_propose_test.go
This time with a proper test!
Edit: also print any invalid block in the error log
> Fix validator pending attestations call

- beacon-chain/core/blocks/block.go
- beacon-chain/core/epoch/epoch_processing.go
Nothing functional related, just better comments, logging, and variable names. Minor changes:
- Rename `prevBlockRoot` -> `parentRoot`
- Add comments for finalization scenarios 
- Better logging for validator rejection
> Misc updates for epoch processing

- beacon-chain/core/attestations/BUILD.bazel
- beacon-chain/core/attestations/attestation.go
- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/BUILD.bazel
- beacon-chain/core/state/transition.go
- beacon-chain/core/state/transition_test.go
- beacon-chain/db/block.go
- beacon-chain/node/node.go
- beacon-chain/powchain/service_test.go
- beacon-chain/rpc/attester_server.go
- proto/cluster/services.pb.go
- shared/bls/bls.go
- shared/bls/bls_test.go
- shared/keystore/deposit_input_test.go
- validator/client/BUILD.bazel
- validator/client/validator_attest.go
- validator/client/validator_attest_test.go
Reverts prysmaticlabs/prysm#1908
> Revert "Create and Verify Signatures for Attestations"

- validator/client/validator_propose.go
- validator/client/validator_propose_test.go
> Do not propose a block when compute state root fails

- beacon-chain/db/block.go
- beacon-chain/db/block_test.go
- beacon-chain/db/schema.go
- beacon-chain/db/state.go
- beacon-chain/db/state_test.go
Part of #1951 
Implemented DB wrappers for saving and retrieving justified and finalized blocks and state.
> DB wrappers for justified and finalized objects

- beacon-chain/db/block.go
This adds state to the current cache in the db in update chain head
> Fix UpdateChainHead

- beacon-chain/attestation/service_test.go
- beacon-chain/core/epoch/epoch_operations_test.go
- beacon-chain/core/helpers/committee_test.go
- beacon-chain/core/validators/validator_test.go
- beacon-chain/db/block.go
- shared/bitutil/BUILD.bazel
- shared/bitutil/bit.go
- shared/bitutil/bit_test.go
- validator/client/validator_attest.go
- validator/client/validator_attest_test.go
> Fix Errors with Attestation to Current Chainhead

- scripts/update-go-pbs.sh
This is a temporary solution until https://github.com/gogo/protobuf/issues/554 is solved
> Run goimports in update-go-pbs.sh

- shared/iputils/external_ip.go
Remove unnecessary logging of IP
> Remove debug log

- beacon-chain/blockchain/block_processing.go
- beacon-chain/blockchain/fork_choice.go
- beacon-chain/blockchain/stategenerator/state_generator.go
- beacon-chain/db/BUILD.bazel
- beacon-chain/db/state.go
> Fixes The PR

- beacon-chain/powchain/service.go
- beacon-chain/sync/initial-sync/service.go
- beacon-chain/sync/regular_sync.go
- shared/messagehandler/messagehandler.go
> Print stack trace on panic recovery

- beacon-chain/sync/regular_sync.go
- beacon-chain/sync/regular_sync_test.go
As title describes. The wrong pb was being asserted for type conversion.
> Fix incoming attestation processing to use the proper message type

- beacon-chain/rpc/proposer_server_test.go
> Add regression test for #1994

- beacon-chain/sync/regular_sync.go
> Add some more tracing data with regular sync

- beacon-chain/attestation/service.go
- validator/client/runner.go
Fix an incident where epoch number was incorrectly computed for log
> Fix epoch numbers for logs

- beacon-chain/core/helpers/committee.go
To get current epoch committee count we passed in **current shuffling epoch** which should have been **current epoch**
> Fix current epoch committee count

- beacon-chain/db/state_metrics.go
Added the following stats to track:
1. when did validator active
2. when did validator exit
3. when did validator got slashed
4. the total # of active validators of current epoch
> Add Validator Stats

- beacon-chain/db/state_metrics.go
Change validator balance label back
> Change validator balance label

- WORKSPACE
```
git remote prune origin
git fetch
git branch -r | grep origin/renovate | sed -e 's/origin\///' | xargs -L1 git pull origin
```
> Renovate big update

- beacon-chain/rpc/beacon_server.go
- beacon-chain/rpc/beacon_server_test.go
This PR limited the pending deposits allowed in beacon block, which is capped at `MaxDeposits` amount. We are handling this restriction on the RPC layer
> Limit Deposits Allowed in Block

- beacon-chain/powchain/service.go
- beacon-chain/rpc/beacon_server.go
Removes all references to chainstart delay flag.
> Remove References to Deleted Flag

- beacon-chain/blockchain/stategenerator/BUILD.bazel
- beacon-chain/blockchain/stategenerator/state_generator.go
- beacon-chain/blockchain/stategenerator/state_generator_test.go
This fixes panics in stategen by using the latest block from the state
> Fixes Panics in Stategen

- beacon-chain/attestation/service_test.go
- beacon-chain/blockchain/block_processing_test.go
- beacon-chain/blockchain/fork_choice.go
- beacon-chain/blockchain/fork_choice_test.go
- beacon-chain/blockchain/service.go
- beacon-chain/blockchain/service_test.go
- beacon-chain/blockchain/stategenerator/state_generator_test.go
- beacon-chain/db/block.go
- beacon-chain/db/block_test.go
- beacon-chain/db/state.go
- beacon-chain/db/state_test.go
- beacon-chain/rpc/attester_server_test.go
- beacon-chain/rpc/beacon_server_test.go
- beacon-chain/rpc/proposer_server.go
- beacon-chain/rpc/proposer_server_test.go
- beacon-chain/rpc/validator_server_test.go
- beacon-chain/sync/initial-sync/service.go
- beacon-chain/sync/initial-sync/service_test.go
- beacon-chain/sync/receive_block_test.go
- beacon-chain/sync/regular_sync_test.go
- beacon-chain/sync/simulated_sync_test.go
> Pass ctx to saveState

- beacon-chain/db/state.go
To help us understand read/write delays
> Add more spans to state db

- beacon-chain/rpc/attester_server.go
- beacon-chain/rpc/attester_server_test.go
> Look up justified state from database rather than state block roots

- beacon-chain/db/pending_deposits.go
> Update the pending deposits metrics on pruning

- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/helpers/committee.go
- beacon-chain/core/helpers/committee_test.go
> Post Chainstart Fix

- validator/client/validator_attest.go
- validator/client/validator_attest_test.go
Contributes to the problem in #2165, but is not the root cause.
> Remove redundant assignments request in validator attesting routine

- shared/p2p/service.go
This was commented out accidentally.
> Do bootstrap p2p

- beacon-chain/blockchain/block_processing_test.go
- beacon-chain/blockchain/fork_choice.go
- beacon-chain/blockchain/fork_choice_test.go
- beacon-chain/blockchain/stategenerator/state_generator.go
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/db/block.go
- beacon-chain/db/block_test.go
- beacon-chain/rpc/attester_server.go
- beacon-chain/sync/initial-sync/service_test.go
- beacon-chain/sync/regular_sync.go
- shared/prometheus/service.go
> Add a span to block-by-slot

- beacon-chain/attestation/vote_metrics.go
I swapped genesis slot with genesis epoch.. 🤦‍♂️
> Fix last vote metrics overflow

- beacon-chain/blockchain/stategenerator/BUILD.bazel
- beacon-chain/blockchain/stategenerator/state_generator_test.go
- beacon-chain/db/BUILD.bazel
- beacon-chain/db/state.go
- beacon-chain/db/state_test.go
- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/service_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
This is an optimization that we may not want when debugging the state of failed validators.
> Historical pruning by flag only

- beacon-chain/cache/committee.go
- beacon-chain/core/helpers/committee.go
- beacon-chain/core/helpers/committee_test.go
- beacon-chain/db/state.go
Building off #2228 (uses committee cache for attestation participants), this PR uses committee cache for computing assignment.
todo:
> Use Committee Cache for Assignment

- beacon-chain/cache/committee.go
- beacon-chain/core/helpers/committee.go
Fixed a few comments on committee cache, I didn't have a chance to clean up before merging #2228. The is purely cosmetic there's no functionality changes
> Fix comments for committee cache

- beacon-chain/blockchain/block_processing.go
- beacon-chain/blockchain/fork_choice.go
- beacon-chain/blockchain/service.go
- beacon-chain/rpc/proposer_server.go
- beacon-chain/rpc/proposer_server_test.go
- beacon-chain/rpc/service_test.go
- beacon-chain/sync/regular_sync_test.go
This is part of #2268
Check whether the attestation is voting on the canonical blocks, if not, don't include them in the proposed block.
> Proposer Server Filters Attestation by Canonical

- beacon-chain/rpc/proposer_server_test.go
Improving test from #2271 
The PR tests the returned pending attestations from proposer server are explicitly equal to the expected attestations. We currently only verify the return length
> Test Pending Attestations Explicitly 

- k8s/beacon-chain/cluster-manager.yaml
- tools/cluster-pk-manager/server/db.go
- tools/cluster-pk-manager/server/watchtower.go
> Fix recycling of cluster private keys

- beacon-chain/blockchain/block_processing.go
Feedback from #2291.
We should handle the case where the database returns an error or a nil object.
> Handle error

- k8s/beacon-chain/contract-address.yaml
- tools/contract-addr/BUILD.bazel
- tools/contract-addr/main.go
- validator/client/validator_propose.go
See it in action: https://beta.prylabs.net/contract
> Provide contract address via http

- beacon-chain/blockchain/fork_choice.go
- beacon-chain/core/blocks/validity_conditions.go
- beacon-chain/core/state/transition.go
- beacon-chain/node/node.go
- beacon-chain/operations/BUILD.bazel
- beacon-chain/operations/service.go
- beacon-chain/operations/service_test.go
- beacon-chain/powchain/log_processing.go
- beacon-chain/rpc/beacon_server.go
- beacon-chain/rpc/service.go
- beacon-chain/rpc/service_test.go
- beacon-chain/sync/initial-sync/service.go
- beacon-chain/sync/initial-sync/sync_blocks.go
- beacon-chain/sync/receive_block.go
- beacon-chain/sync/receive_block_test.go
- beacon-chain/sync/regular_sync.go
- beacon-chain/sync/regular_sync_test.go
Fixed logging across repo to use `WithField(s)`
> Use Withfields for Logging

- beacon-chain/sync/regular_sync_test.go
- validator/client/service_test.go
- validator/client/validator_test.go
> Clean Up Validator Client Test Set Up

- beacon-chain/blockchain/block_processing.go
- beacon-chain/blockchain/block_processing_test.go
- beacon-chain/rpc/validator_server.go
This fixes our assignments bug, where we couldn't retrieve the validator index despite the validator being activated. Resolves #2165
> Fix Assingments Bug

- shared/slotutil/slotticker.go
- shared/slotutil/slotticker_test.go
This also had some bizzare test behavior!
> Remove unused method: CurrentSlot

- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/p2p/v1/types.proto
- proto/beacon/rpc/v1/services.pb.go
- proto/sharding/p2p/v1/messages.pb.go
> Add WithdrawableEpoch to Valdiator

- k8s/beacon-chain/contract-address.yaml
Another win for istio that we didn't have to add CORS logic to our code 👏
> Allow CORS from anywhere for deposit contract http endpoint

- validator/client/validator.go
- validator/client/validator_attest.go
- validator/client/validator_metrics.go
This PR made minor cosmetic improvements to the validator log
Update:
1. Update balance logs
2. Use `WithField`
> Minor Cosmetic Updates to Validator Logging

- beacon-chain/sync/metrics.go
- beacon-chain/sync/receive_block.go
Add logging for blocks from a forked chain
> Add Logging for Forked Blocks

- shared/params/config.go
Update `demoConfig` to use 3.2ETH
> Update to 3.2ETH

- beacon-chain/attestation/service.go
- beacon-chain/attestation/service_test.go
- beacon-chain/blockchain/BUILD.bazel
- beacon-chain/blockchain/fork_choice.go
- beacon-chain/blockchain/fork_choice_reorg_test.go
- beacon-chain/blockchain/fork_choice_test.go
- beacon-chain/blockchain/service.go
- beacon-chain/sync/receive_block.go
- shared/p2p/negotiation.go
Only re-org if the new chain head isn't a direct child of the old head
> Fix Fork Choice Reorg Conditions 

- k8s/beacon-chain/cluster-manager.yaml
> Set cluster manager to deposit 3.2 eth

- beacon-chain/core/helpers/randao.go
- beacon-chain/core/helpers/randao_test.go
---
changed the godoc to comply with variable name change in spec
to comply with 0.6 spec
changes in:
- beacon-chain/core/helpers/randao.go
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_active_index_root
> Update active index root helpers

- beacon-chain/node/node.go
- beacon-chain/rpc/service.go
- beacon-chain/rpc/service_test.go
- beacon-chain/sync/service.go
> Reverts RPC Disabling

- beacon-chain/core/epoch/BUILD.bazel
- beacon-chain/core/epoch/epoch_processing.go
- shared/params/config.go
This fixes validator ejection for our current cluster, the ejection balance from config wasn't correctly set.
I also added metrics so we can monitor the # of ejected validators
> Fix Validator Ejection for Testnet

- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/validators/validator.go
> Continue Processing Invalid Deposits

- beacon-chain/attestation/service.go
- beacon-chain/blockchain/fork_choice.go
- beacon-chain/core/state/BUILD.bazel
- beacon-chain/core/state/transition.go
- beacon-chain/rpc/beacon_server.go
- beacon-chain/rpc/proposer_server.go
- beacon-chain/sync/receive_block.go
- beacon-chain/sync/regular_sync.go
- shared/bytesutil/bytes.go
- shared/bytesutil/bytes_test.go
This fixes #2410
Truncates attestation and block root hashes
> Add and Use Truncate Hash Library

- beacon-chain/blockchain/fork_choice.go
- beacon-chain/core/state/transition.go
- beacon-chain/sync/initial-sync/sync_blocks.go
Checked the logs and fixed more logging typos and cosmetic touchups
> Beacon Node Logging Touchups 

- beacon-chain/blockchain/fork_choice.go
- beacon-chain/powchain/BUILD.bazel
- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/log_processing_test.go
- beacon-chain/rpc/proposer_server.go
- beacon-chain/sync/querier.go
- validator/client/BUILD.bazel
- validator/client/validator.go
- validator/client/validator_attest.go
- validator/client/validator_metrics.go
No tracking issue, this just adds minor cosmetic improvements to logs across the repo.
> Various Logging Improvements

- tools/faucet/server.go
If a request for funding comes in and they have already been funded, return an error.
> Faucet: Add simple funded too recently error

- beacon-chain/blockchain/fork_choice.go
- beacon-chain/blockchain/fork_choice_test.go
Added fork choice tie breaker (and test), it's favoring the block with lexicographically higher root.
> Add Forkchoice Tie Breaker

- beacon-chain/node/node.go
- beacon-chain/rpc/service.go
- beacon-chain/rpc/service_test.go
- beacon-chain/sync/service.go
Reverts prysmaticlabs/prysm#2435
> Revert "Reverts RPC Disabling"

- beacon-chain/rpc/validator_server.go
- beacon-chain/sync/initial-sync/service.go
- beacon-chain/sync/initial-sync/sync_blocks.go
> Only Perform Initial Sync With a Single Peer

- beacon-chain/core/helpers/BUILD.bazel
- k8s/beacon-chain/ssz-server.yaml
- k8s/beacon-chain/testnet-site.yaml
- tools/ssz-server/BUILD.bazel
- tools/ssz-server/main.go
Part of https://github.com/prysmaticlabs/prysm-testnet-site/issues/37
This is a temporary API at https://alpha.prylabs.net/ssz/decodeDepositData to provide a solution to decode the deposit data for the testnet site.
> SSZ web api for decoding input data

- README.md
This updates our main README file for a testnet announcement and includes updated information on how to participate and install Prysm.
> Update Prysm README

- beacon-chain/db/deposits.go
- beacon-chain/rpc/validator_server.go
> Fix Status Nil Pointer Error

- beacon-chain/rpc/validator_server.go
- beacon-chain/rpc/validator_server_test.go
- validator/client/validator.go
> Fix Status Update Progression in RPC Server

- k8s/beacon-chain/testnet-site.yaml
Follow up to #2493. This adds much needed routing to prylabs.net
> Add path for prylabs.net/ssz

- WORKSPACE
Reverts prysmaticlabs/prysm#2505
> Revert "Renovate Updates in Batch"

- beacon-chain/sync/regular_sync.go
- beacon-chain/sync/regular_sync_test.go
This fixes batched block response to not include finalized block
> Batched Response Excludes Finalized Block

- shared/p2p/service.go
This was causing a rather noticeable delay in broadcasting
> Only marshal broadcast debug message when actually logging debug

- beacon-chain/sync/initial-sync/sync_blocks.go
- beacon-chain/sync/initial-sync/sync_state.go
- shared/p2p/connection_manager.go
- shared/p2p/interfaces.go
- shared/p2p/service.go
> Fix lint issues

- k8s/monitoring/alertmanager-templates.config.yaml
- k8s/monitoring/alertmanager.config.yaml
- k8s/monitoring/alertmanager.deploy.yaml
- k8s/monitoring/alertmanager.service.yaml
- k8s/monitoring/alerts.yaml
- k8s/monitoring/discord-webhook.encrypted_sercret.yaml
This is the service for prometheus to talk to and send alerts. We also have a discord webhook handler because prometheus doesn't support discord.
> Add alert manager config

- beacon-chain/attestation/BUILD.bazel
- beacon-chain/attestation/service.go
- beacon-chain/attestation/service_test.go
> Change Logging of Failed Attestations

- beacon-chain/blockchain/service.go
- beacon-chain/main.go
- beacon-chain/node/node.go
- beacon-chain/usage.go
- shared/cmd/flags.go
> Add Check for Goroutines Count

- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/transition.go
---
includes:
ProcessBlockHeader
to comply with 0.6 spec
small change
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#randao
> Update Process randao

- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/transition_test.go
- beacon-chain/core/validators/validator.go
Part of #2307 
---
This PR updates block processing voluntary exits as of the v0.6 specification, as well as the `initiate_validator_exit` helper function.
> Update Block Processing Voluntary Exits

- shared/params/config.go
Increase slots per epoch from 8 to 16 for new test net launch
> Increase SlotsToEpoch 8 to 16

- beacon-chain/core/state/BUILD.bazel
- beacon-chain/core/state/transition.go
- shared/featureconfig/config.go
No tracking issue - there is a prom gauge that is creating a new row every single epoch
> Remove Expensive Participation Rate Prometheus Gauge

- beacon-chain/rpc/proposer_server.go
Reverts prysmaticlabs/prysm#2635
> Revert "Remove Canonical Attestation Filter"

- WORKSPACE
All except #2659 which has some breaking changes.
> Renovate updates

- .well-known/security.txt
This adds a standard for how to contact prysmatic labs with security issues.
If you know of a critical security issue, please send an encrypted message to security@prysmaticlabs.com with the encryption specified in the security.txt. 
https://tools.ietf.org/html/draft-foudil-securitytxt-05
> Add security file

- beacon-chain/core/epoch/BUILD.bazel
- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/epoch/epoch_processing_test.go
Process registry was previously reverted. This PR adds back the process registry function. It also touched up on comments and variable names for better readability
> Add Process Registry for Epoch Processing

- WORKSPACE
- beacon-chain/main.go
- validator/main.go
> fix joonix log after https://github.com/joonix/log/pull/13

- beacon-chain/attestation/service_test.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/helpers/committee_test.go
This PR fixes all the outdated tests for core processing functions. Everything under `core`
> Fixed Outdated Tests Core Processing

- WORKSPACE
- beacon-chain/main.go
- beacon-chain/node/p2p_config.go
- k8s/beacon-chain/beacon-chain.deploy.yaml
- shared/cmd/flags.go
- shared/p2p/BUILD.bazel
- shared/p2p/options.go
- shared/p2p/options_test.go
- shared/p2p/service.go
- validator/main.go
This may be useful for local development or other constrained deployments which would not want to peer with external peers.
> Add flag to whitelist certain connections

- shared/trieutil/sparse_merkle_test.go
No tracking issue for this. Just cleaning up some test data.
> Use generalized examples in test

- beacon-chain/blockchain/block_processing_test.go
- beacon-chain/core/epoch/BUILD.bazel
- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/helpers/rewards_penalties.go
- beacon-chain/core/helpers/slot_epoch.go
This PR wraps up rest of the changes for #2790. Good to see we are aligned before proceeding to test vectors
> Minor Updates to 0.7

- beacon-chain/rpc/validator_server_test.go
- shared/params/config.go
> Update config.go to fix BLS issue

- tools/kubesec.bzl
> Update kubesec.bzl to new starlark attr.label API

- shared/bls/BUILD.bazel
- shared/bls/bls.go
- shared/bls/bls_test.go
> Add Functions for Compressed and Uncompressed HashG2 With Domain

- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/helpers/committee.go
- beacon-chain/core/helpers/committee_test.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/sharding/p2p/v1/messages.pb.go
> Attesting Indices Fix

- beacon-chain/core/helpers/block.go
- beacon-chain/core/helpers/block_test.go
This round found a case of false positives!
> Mutation testing fixes for beacon-chain/core/helpers/blocks.go

- beacon-chain/blockchain/BUILD.bazel
- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/helpers/block.go
- beacon-chain/core/helpers/committee_test.go
- beacon-chain/core/helpers/randao_test.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/sharding/p2p/v1/messages.pb.go
- shared/params/config.go
https://github.com/ethereum/eth2.0-specs/pull/1257
> Change Base Reward Factor

- .bazelrc
- WORKSPACE
> Fix builds with bazel 0.27.1

- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/transition.go
Fixed a misspell `volundary` -> `voluntary`
> Fix Volundary -> Voluntary

- beacon-chain/core/helpers/validators.go
- beacon-chain/core/helpers/validators_test.go
- shared/bls/bls.go
- shared/bytesutil/bytes.go
- shared/bytesutil/bytes_test.go
- shared/keystore/BUILD.bazel
- shared/keystore/deposit_input.go
- shared/keystore/deposit_input_test.go
- shared/params/BUILD.bazel
- shared/params/config.go
> Update BLS Domain

- README.md
Several adjustments to language used and presentation.
> Formatting and structure changes

- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/state_test.go
- shared/params/config.go
- shared/params/config_test.go
> Update zero hash to sha256().digest()

- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/state_test.go
- shared/params/config.go
- shared/params/config_test.go
Reverts prysmaticlabs/prysm#2932
> Revert "Update zero hash to sha256().digest()"

- WORKSPACE
- beacon-chain/core/helpers/committee.go
- beacon-chain/core/helpers/committee_test.go
Wrong implementation, now fixed.
> Fix compress validator

- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/helpers/committee_test.go
- beacon-chain/core/helpers/validators_test.go
- beacon-chain/core/state/state.go
- beacon-chain/core/state/state_test.go
- beacon-chain/core/state/transition_test.go
- beacon-chain/rpc/attester_server_test.go
- beacon-chain/rpc/proposer_server_test.go
- beacon-chain/rpc/validator_server_test.go
- contracts/deposit-contract/deployContract/deployContract.go
- shared/params/config.go
> fix breakages from #2957

- WORKSPACE
This PR updates renovate updates in batch
> Mega Renovate Updates

- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/epoch/epoch_processing_test.go
[Part of] #2969
---
https://github.com/ethereum/eth2.0-specs/pull/1286
> Overflow slashing calculation fix

- beacon-chain/BUILD.bazel
- beacon-chain/gateway/server/BUILD.bazel
- contracts/deposit-contract/deployContract/BUILD.bazel
- k8s/geth/prober/BUILD.bazel
- scripts/workspace_status.sh
- tools/bootnode/BUILD.bazel
- tools/cluster-pk-manager/client/BUILD.bazel
- tools/cluster-pk-manager/server/BUILD.bazel
- tools/contract-addr/BUILD.bazel
- tools/eth1exporter/BUILD.bazel
- tools/faucet/BUILD.bazel
- tools/relaynode/BUILD.bazel
- tools/ssz-server/BUILD.bazel
- validator/BUILD.bazel
Minor changes to docker image deployment. We want to deploy a tagged image and latest, rather than just latest.
> Docker: use container bundles to upload multiple image tags

- beacon-chain/rpc/beacon_chain_server.go
- beacon-chain/rpc/beacon_chain_server_test.go
Part of #3045 
This PR implements the `ListBlocks ` functionality of the `BeaconChainService`.
> Implement ListBlocks RPC function 

- beacon-chain/db/BUILD.bazel
- beacon-chain/db/deposits.go
- beacon-chain/db/deposits_test.go
Increasing coverage and confidence in these methods.
> Add tests for db deposits

- beacon-chain/blockchain/service.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/state/spectest/genesis_validity.yaml.go
- beacon-chain/core/state/spectest/genesis_validity_minimal_test.go
> Fix spelling of genesis

- shared/hashutil/BUILD.bazel
- shared/hashutil/hash.go
- shared/keystore/BUILD.bazel
- shared/keystore/keystore.go
Switch to as per @rauljordan 's recommendation, it's a lot faster than `/crypto/sha256`
> Switch over to sha256-simd

- WORKSPACE
- contracts/deposit-contract/sendDepositTx/BUILD.bazel
- contracts/deposit-contract/sendDepositTx/sendDeposits.go
This removes a statistical package that was never used, and added an unneeded dependency.
> Remove Statistical Package

- beacon-chain/sync/querier.go
- beacon-chain/sync/service.go
> Fix Sync Service Status

- beacon-chain/rpc/beacon_chain_server.go
- beacon-chain/rpc/beacon_chain_server_test.go
- return empty list instead of error when block not found
- block by root without input page token works
> Fix ListBlock RPC bugs

- beacon-chain/blockchain/block_processing.go
- beacon-chain/blockchain/service.go
- beacon-chain/core/blocks/block.go
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/helpers/committee.go
- beacon-chain/core/state/state.go
- beacon-chain/core/validators/validator.go
- beacon-chain/db/block.go
- beacon-chain/operations/service.go
- beacon-chain/powchain/deposit.go
- beacon-chain/powchain/service.go
- beacon-chain/rpc/attester_server.go
- beacon-chain/rpc/proposer_server.go
- beacon-chain/rpc/validator_server.go
- beacon-chain/sync/regular_sync.go
- proto/beacon/p2p/v1/messages.proto
- proto/beacon/rpc/v1/services.proto
- shared/sliceutil/BUILD.bazel
- shared/sliceutil/slice_generic.go
This is to finish #3123. Fixed the errors that didnt get wrapped properly
> Finish error wrapping

- WORKSPACE
```
git remote prune origin
git fetch
git branch -r | grep origin/renovate | sed -e 's/origin\///' | xargs -L1 git pull origin
```
> Renovate updates in batch

- WORKSPACE
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
Resolves #2993
---
This PR incorporates the newest SSZ updates which include comprehensive caching, bug fixes, and thread-safety.
> Update SSZ Dependency to Latest Version

- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/log_processing_test.go
- beacon-chain/powchain/service.go
Resolves #3169
sequentially through their merkle index.
> Request Missing Logs

- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/messages.proto
Part of #3147. 
This adds new messages to support p2p rpc.
> Add new p2p messages for RPC

- beacon-chain/p2p/BUILD.bazel
- beacon-chain/p2p/broadcaster.go
- beacon-chain/p2p/broadcaster_test.go
- beacon-chain/p2p/interfaces.go
- beacon-chain/p2p/service.go
- beacon-chain/p2p/testing/BUILD.bazel
- beacon-chain/p2p/testing/p2p.go
Part of #3147.
Not much to describe, this calls through the PubSub publish method. :smile:
> Add p2p broadcast implementation

- beacon-chain/db/kv/BUILD.bazel
- beacon-chain/db/kv/attestations.go
- beacon-chain/db/kv/blocks.go
- beacon-chain/db/kv/state.go
- beacon-chain/db/kv/validators.go
> Add Spans to DB Refactor Methods

- beacon-chain/db/filters/filter.go
No tracking issue for this PR.
> Add Better Godocs to Filter Methods

- beacon-chain/node/node.go
If I do it again, someone take away my keyboard.
> Revert fork version bug (again)

- tools/bootnode/BUILD.bazel
- tools/bootnode/bootnode.go
- tools/bootnode/bootnode_test.go
> Change log to node's URL

- beacon-chain/main.go
- beacon-chain/node/node.go
- beacon-chain/p2p/broadcaster_test.go
- beacon-chain/p2p/config.go
- beacon-chain/p2p/encoder/network_encoding.go
- beacon-chain/p2p/service.go
- beacon-chain/usage.go
- shared/cmd/flags.go
> Add Flag for SSZ Encoding

- beacon-chain/blockchain/chain_info.go
- beacon-chain/blockchain/chain_info_test.go
This PR exposes a getter for retrieving genesis time in block chain service
> Add getter for GenesisTime

- beacon-chain/deprecated-sync/initial-sync/service_test.go
- beacon-chain/deprecated-sync/regular_sync_test.go
- beacon-chain/node/node.go
- beacon-chain/rpc/service.go
Stops Panics in RPC server, by correctly assigning the cache
> Deposit Cache Fix

- beacon-chain/p2p/BUILD.bazel
- beacon-chain/p2p/service.go
- beacon-chain/p2p/service_test.go
- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/rpc.go
- beacon-chain/sync/rpc_goodbye.go
- beacon-chain/sync/rpc_goodbye_test.go
- beacon-chain/sync/rpc_test.go
> Implement GoodBye RPC Handler

- beacon-chain/blockchain/BUILD.bazel
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/log.go
- beacon-chain/blockchain/receive_block.go
- beacon-chain/blockchain/service.go
* Removed excessive state transition logging
* Move logging into its own self contained file
> Fix transition logging

- beacon-chain/blockchain/receive_attestation_test.go
- beacon-chain/blockchain/receive_block.go
- beacon-chain/blockchain/receive_block_test.go
- beacon-chain/blockchain/service_test.go
Previously we were saving incoming block as head. This fixes it to saving head block as head
> Fix save the correct head

- beacon-chain/sync/initial-sync/service.go
This prevents the node from reporting "healthy" and serving traffic to RPC.
> Return status error while syncing

- shared/params/config.go
Cleaned up beacon chain config, removed old shard chain related fields
> Clean up beacon chain config

- beacon-chain/blockchain/forkchoice/process_attestation.go
This was blocking attestation handling
> Remove unnecessary lock when handling attestation

- beacon-chain/blockchain/forkchoice/service.go
- shared/prometheus/service.go
Forgot to remove the lock from store struct in #3399
> Remove lock from store struct

- beacon-chain/sync/subscriber_beacon_blocks.go
- shared/prometheus/service.go
It would be really helpful to see the block slot which doesn't have parent stored in DB
> Log the slot of the block w/o parent

- beacon-chain/cache/depositcache/pending_deposits.go
- beacon-chain/core/state/transition.go
- beacon-chain/db/kv/state.go
- beacon-chain/rpc/BUILD.bazel
- beacon-chain/rpc/attester_server.go
- beacon-chain/rpc/proposer_server.go
This is helpful for some tracing / debugging at runtime.
> Tracing: Add additional attributes

- INTEROP.md
- beacon-chain/core/state/BUILD.bazel
- shared/bls/bls.go
- tools/genesis-state-gen/BUILD.bazel
- tools/genesis-state-gen/main.go
- tools/genesis-state-gen/main_test.go
This is part of #3116 and #3398 
---
We need to get Prysm ready for interop.
This PR implements a tool which deterministically generates `genesis.yaml`, `genesis.json`, or `genesis.ssz` file and adds basic interop guidelines/setup for Prysm.
_The tool panics when generating a large number of validators, marking as WIP in the meantime_
> Genesis State Generator + Interop Docs

- beacon-chain/blockchain/service.go
- beacon-chain/flags/flags.go
- beacon-chain/main.go
- beacon-chain/node/node.go
- beacon-chain/usage.go
This PR allows us to load a generated genesis state in ssz format
Ex: ` bazel run //beacon-chain -- --load-genesis-state ~/terence/genesis.ssz`
> Load ssz formatted genesis state

- beacon-chain/blockchain/forkchoice/metrics.go
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/process_block_test.go
- beacon-chain/blockchain/metrics.go
- beacon-chain/blockchain/receive_block.go
- shared/bytesutil/bytes.go
This PR aligns metrics to: https://github.com/ethereum/eth2.0-metrics/pull/9
> Align metrics to interop

- README.md
Updated how-prysm-works link in README.md
> Updated how-prysm-works link in README.md

- tools/enr-calculator/main.go
> Add outfile support for ENR calculation

- beacon-chain/node/node.go
> Accept a filepath for bootnode ENR address

- beacon-chain/blockchain/forkchoice/doc.go
> Add Fork Choice Package Docs

- beacon-chain/node/node.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
- shared/params/config.go
- validator/node/node.go
Also removed polling value for sync. It was unused.
> demo-config flag

- beacon-chain/node/node.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/eth/v1alpha1/attestation.pb.go
- proto/eth/v1alpha1/beacon_block.pb.go
- proto/eth/v1alpha1/beacon_chain.pb.go
- proto/eth/v1alpha1/node.pb.go
- proto/eth/v1alpha1/slasher.pb.go
- proto/eth/v1alpha1/validator.pb.go
- proto/sharding/p2p/v1/messages.pb.go
> Fix Demo Config 

- beacon-chain/p2p/handshake.go
- beacon-chain/p2p/interfaces.go
- beacon-chain/p2p/service.go
- beacon-chain/p2p/testing/p2p.go
- beacon-chain/sync/rpc_hello.go
- beacon-chain/sync/rpc_hello_test.go
- beacon-chain/sync/service.go
This PR helps maintain the list of statuses / hellos we have received from peers.
> Clean hello tracker on peer disconnection

- beacon-chain/p2p/testing/p2p.go
- beacon-chain/rpc/service.go
- beacon-chain/sync/rpc_hello_test.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/eth/v1alpha1/archive.pb.go
- proto/eth/v1alpha1/attestation.pb.go
- proto/eth/v1alpha1/beacon_block.pb.go
- proto/eth/v1alpha1/beacon_chain.pb.go
- proto/eth/v1alpha1/node.pb.go
- proto/eth/v1alpha1/slasher.pb.go
- proto/eth/v1alpha1/validator.pb.go
- proto/sharding/p2p/v1/messages.pb.go
This initializes the state feed and adds in the channel to listen for chainstart, allowing the validator to work normally.
> Fix Validator Client

- shared/prometheus/service.go
> Log a warning on unhealthy healthz

- beacon-chain/p2p/service.go
In the event that a bootnode server restarts, the prysm client may prune the bootnode server from its local table. Occasionally pinging the server may re-insert the connection and allow for discovery to continue.
> Infrequently ping bootnode

- beacon-chain/p2p/BUILD.bazel
- beacon-chain/p2p/service.go
- tools/bootnode-query/BUILD.bazel
- tools/bootnode-query/README.md
- tools/bootnode-query/main.go
Adds previously deleted tool back into the repo tools
> Restore bootnode query tool for kaddht and fix bootstrapping

- beacon-chain/core/state/interop/write_block_to_disk.go
- beacon-chain/core/state/transition.go
- beacon-chain/rpc/BUILD.bazel
- beacon-chain/rpc/proposer_server.go
- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/subscriber_beacon_blocks.go
Attempting to capture failed blocks on disk
> Write failed blocks to disk

- shared/trieutil/BUILD.bazel
- shared/trieutil/merkle_trie.go
- shared/trieutil/merkle_trie_test.go
Building off #3571, this PR implements merkle tree + test
Reference: https://github.com/ethereum/eth2.0-specs/blob/50209ea806820f83ceff3f21e1578191db0a71e5/specs/light_client/merkle_proofs.md#generalized-merkle-tree-index
> Merkle tree implementation

- WORKSPACE
- beacon-chain/operations/service.go
- beacon-chain/sync/rpc_beacon_blocks_by_root.go
No tracking issue here.
---
This was causing stack overflows in ssz.
> Update ssz and do not try to send a nil block in RPC

- beacon-chain/blockchain/forkchoice/process_attestation.go
- beacon-chain/blockchain/testing/mock.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/eth/v1alpha1/archive.pb.go
- proto/eth/v1alpha1/attestation.pb.go
- proto/eth/v1alpha1/beacon_block.pb.go
- proto/eth/v1alpha1/beacon_chain.pb.go
- proto/eth/v1alpha1/node.pb.go
- proto/eth/v1alpha1/slasher.pb.go
- proto/eth/v1alpha1/validator.pb.go
- proto/sharding/p2p/v1/messages.pb.go
> Improved Validator Votes Logging

- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/state/transition.go
Otherwise state transitions will be incorrect in the case of invalid deposits.
> All deposits must be verified

- validator/BUILD.bazel
- validator/main.go
The deposit amount is part of the block signature.
> Use demo config for accounts create

- beacon-chain/p2p/BUILD.bazel
- beacon-chain/p2p/broadcaster.go
- beacon-chain/rpc/BUILD.bazel
- beacon-chain/rpc/service.go
- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/metrics.go
- beacon-chain/sync/subscriber.go
- shared/traceutil/BUILD.bazel
- shared/traceutil/errors.go
- validator/client/BUILD.bazel
- validator/client/runner.go
- validator/client/service.go
> Add error spans, interceptors

- WORKSPACE
> Update WORKSPACE SSZ Dependency

- beacon-chain/sync/metrics.go
- beacon-chain/sync/rpc.go
- beacon-chain/sync/subscriber.go
For monitoring pubsub processing issues
> Add metrics for p2p message failures

- beacon-chain/blockchain/receive_attestation.go
- beacon-chain/blockchain/receive_attestation_test.go
- beacon-chain/blockchain/receive_block.go
- beacon-chain/blockchain/receive_block_test.go
- beacon-chain/blockchain/service.go
Previously we were saving head for every block and every attestation. This fix it by saving head only if it's diff than prev saved head
> Save head if diff than prev saved head

- WORKSPACE
Reverts protobuf update, which was causing issues building the node.
> Revert Protobuf Update

- beacon-chain/blockchain/forkchoice/process_attestation.go
> Remove attestation that fails to verify from queue

- beacon-chain/p2p/dial_relay_node.go
- beacon-chain/p2p/discovery.go
- beacon-chain/p2p/options.go
- beacon-chain/p2p/service.go
- beacon-chain/p2p/utils.go
- shared/featureconfig/flags.go
This adds provided host addresses to our address factory and adds it as a fallback IP in the case of discoveryV5 .
> Support Provided Host Addresses

- beacon-chain/main.go
- validator/main.go
It was in the wrong format and was causing issues.
> Remove fluentd timestamp

- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block_test.go
- beacon-chain/core/blocks/eth1_data_test.go
- beacon-chain/core/epoch/participation_test.go
- beacon-chain/core/helpers/block_test.go
It's generally a good practice to put test code in different package to express ourselves to the API footprint in the beginning.
> Test code in different packages

- beacon-chain/p2p/discovery.go
- shared/featureconfig/flags.go
This changes it to a debug log as discv5 sometimes returns us invalid peers from its table
> Change MultiAddr Conversion Error to Debug

- validator/client/validator_attest.go
- validator/client/validator_propose.go
Prints the pubkeys as hex when attesting/proposing.
> Print Pubkeys as Hex

- validator/client/runner.go
This is a minor tidy-up of the logging code.  It renames "public_key" to "pubKey" as uses the same format as the rest of the validator logging.  It also logs a warning at the fall-through part of the switch statement rather than silently doing nothing.
> Tidy up logging

- beacon-chain/blockchain/receive_attestation.go
Fixes logs for receiving attestations in chainservice
> Minor Log Fix

- shared/bytesutil/bytes_test.go
- shared/featureconfig/config_test.go
- shared/hashutil/merkleRoot_test.go
- shared/interop/generate_genesis_state_test.go
- shared/interop/generate_keys_test.go
- shared/iputils/external_ip_test.go
- shared/mathutil/math_helper_test.go
- shared/messagehandler/messagehandler_test.go
- shared/pagination/pagination_test.go
- shared/params/config_test.go
- shared/sliceutil/slice_test.go
- shared/trieutil/merkle_trie_test.go
A lot of test code under `shared` share the package as main code. This PR fixes that
> Moved /shared/ test code in different package

- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/helpers/block.go
- beacon-chain/core/helpers/block_test.go
- beacon-chain/core/state/BUILD.bazel
- beacon-chain/core/state/stateutils/BUILD.bazel
- shared/testutil/BUILD.bazel
- shared/testutil/block.go
- shared/testutil/block_test.go
Originally #3674, was reverted without anyone noticing.
> Revert Removal of Block Generation Util

- beacon-chain/blockchain/forkchoice/BUILD.bazel
- beacon-chain/blockchain/forkchoice/process_attestation.go
- beacon-chain/blockchain/forkchoice/process_attestation_test.go
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/process_block_test.go
- beacon-chain/core/helpers/BUILD.bazel
- beacon-chain/core/helpers/slot_epoch.go
This logic was duplicated a few times so this common abstraction makes the code more reusable.
> Abstract verifySlot to helper package

- WORKSPACE
> Use New SSZ In Workspace

- beacon-chain/core/state/transition.go
- beacon-chain/p2p/handshake.go
- beacon-chain/rpc/BUILD.bazel
- beacon-chain/rpc/service.go
- beacon-chain/sync/initial-sync/round_robin.go
- shared/params/config.go
- shared/traceutil/BUILD.bazel
- shared/traceutil/recovery_interceptor_option.go
First time prysmatic labs is all in the same timezone and the testnet died while we were asleep.
Changes:
- Update fork version for testnet restart
- Add a round robin hotfix for scenario when too many slots from finality
- Add a better panic handler to understand panics in gRPC requests
> Testnet restart and hotfixes

- WORKSPACE
- beacon-chain/blockchain/BUILD.bazel
- beacon-chain/blockchain/receive_block.go
- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/pending_blocks_queue.go
Also use random peer to request parent block
> Annotate errors / spans in block processing queue

- WORKSPACE
- beacon-chain/BUILD.bazel
- proto/beacon/rpc/v1/BUILD.bazel
- proto/beacon/rpc/v1/services.proto
Generating swagger.json is broken and we aren't using it at the moment
> Some fixes for bazel v1

- renovate.json
This should result in a single PR each week.
> Change renovate to group dependencies

- beacon-chain/core/helpers/BUILD.bazel
- beacon-chain/core/helpers/attestation.go
- beacon-chain/core/helpers/attestation_aggregation_bench_test.go
- beacon-chain/core/helpers/attestation_test.go
Part of #3744
Adds a method to aggregate a list of attestations.
> Aggregation helper improvements

- beacon-chain/core/epoch/precompute/BUILD.bazel
- beacon-chain/core/epoch/precompute/type.go
This PR defines the pre-computed types that are needed to optimize `process_epoch`. Goal is to pre-compute values for these types and use them through out `process_epoch`
> Type for process epoch optimization

- slasher/rpc/server.go
[Part of] #3133
---
add todo to unimplemented slashed server methods
> slasher todo

- beacon-chain/core/epoch/precompute/BUILD.bazel
- beacon-chain/core/epoch/precompute/slashing.go
- beacon-chain/core/epoch/precompute/slashing_test.go
This PR implements the necessary methods to precompute slashing used for epoch processing. By having total epoch balances precomputed, it drastically increases run time performance
> Process slashing with precompute

- beacon-chain/core/epoch/spectest/BUILD.bazel
- beacon-chain/core/epoch/spectest/justification_and_finalization_test.go
- beacon-chain/core/epoch/spectest/slashings_test.go
Now we have the optimized version of `process_slashing` and `process_justification_finalization`, this PR adds in the spec tests for those optimized versions
> Add spec tests for process_slashing and process_justification_finalization

- .bazelrc
prevent bazel rebuild when moving from IDE to terminal
> prevent bazel rebuild

- validator/README.md
Updated why-combining-sharding-and-casper link in validator/README.md
> Updated why-combining-sharding-and-casper link in validator/README.md

- beacon-chain/gateway/BUILD.bazel
- beacon-chain/gateway/gateway.go
- beacon-chain/sync/initial-sync/round_robin.go
- proto/eth/v1alpha1/BUILD.bazel
Run this PR with `--grpc-gateway-port=7000` then access methods as defined at https://api.prylabs.net
> Gateway registers gRPC gateway handlers

- TESTNET.md
In case anyone wants to try multi-client testnet early!
> Add testnet markdown instructions for interop

- TESTNET.md
> Minor edit

- beacon-chain/db/BUILD.bazel
- tools/interop/export-genesis/BUILD.bazel
- tools/interop/export-genesis/main.go
> Add a tool to extract genesis.ssz from existing database

- beacon-chain/sync/rpc.go
This might be helpful when debugging failed RPC requests over p2p.
> Add peer to span and log in sync rpc handlers

- beacon-chain/blockchain/forkchoice/BUILD.bazel
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/process_block_test.go
- beacon-chain/db/kv/checkpoint_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
Part of prevention for #3841. 
Adding feature flag until issues can be resolved safely.
> Add feature flag for state pruning

- beacon-chain/blockchain/forkchoice/BUILD.bazel
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/sync/initial-sync/round_robin.go
This PR adds tracing and annotation for descendent error during process block
> Add tracing and annotation  for descendent error

- beacon-chain/cache/shuffled_indices.go
- beacon-chain/cache/shuffled_indices_test.go
- beacon-chain/core/helpers/BUILD.bazel
- beacon-chain/core/helpers/committee_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
```
--enable-shuffled-index-cache
```
> Add feature flag to enable shuffled index cache

- beacon-chain/core/epoch/epoch_processing.go
- beacon-chain/core/epoch/precompute/reward_penalty.go
Part of #3865 
This PR updates attestation inclusion reward calculation and It's simple
> Update Inclusion Reward

- beacon-chain/core/helpers/BUILD.bazel
- validator/client/BUILD.bazel
- validator/client/runner.go
- validator/client/validator.go
> Set committee assignment deadline to 1 epoch

- shared/traceutil/recovery_interceptor_option.go
> Safer panic handler

- WORKSPACE
This updates our ethereum-api commit hash to the latest one.
> Update Eth-API To The Latest Version

- WORKSPACE
Follow-up to #3929, this PR integrates the latest changes from commit https://github.com/prysmaticlabs/go-ssz/commit/58b2f86b0f02f06e634db06dee0c838ad41849f8
> Update Latest Master SSZ

- beacon-chain/node/node.go
- shared/version/version.go
Resolves #3817 
---
**Was not able to connect to grpc port using docker
> Fix grpc port for docker

- beacon-chain/core/blocks/spectest/block_processing_minimal_test.go
- beacon-chain/core/blocks/spectest/block_processing_test.go
- beacon-chain/core/state/spectest/slot_processing_minimal_test.go
- beacon-chain/rpc/proposer_server_test.go
- proto/ssz_proto_library.bzl
- shared/params/config.go
Two issues:
- Slot time was set to 6
- Base reward was being overridden with the old value of 5.
> Fix minimal config

- beacon-chain/rpc/proposer/server.go
- shared/mathutil/math_helper.go
- shared/mathutil/math_helper_test.go
This can be an x10 increase in performance for computing these common values
> Use a data table for common power of 2 roots

- WORKSPACE
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/helpers/attestation_test.go
- beacon-chain/core/state/transition_test.go
- beacon-chain/operations/attestation_test.go
- beacon-chain/powchain/deposit_test.go
- beacon-chain/rpc/validator/server_test.go
- beacon-chain/sync/validate_proposer_slashing_test.go
- beacon-chain/sync/validate_voluntary_exit_test.go
- shared/bls/BUILD.bazel
- shared/bls/bls.go
- shared/bls/bls_benchmark_test.go
- shared/bls/bls_test.go
- shared/bls/spectest/BUILD.bazel
- shared/bls/spectest/aggregate_pubkeys_test.go
- shared/bls/spectest/msg_hash_compressed_test.go
- shared/bls/spectest/msg_hash_uncompressed_test.go
- shared/bls/spectest/priv_to_pub_test.go
- shared/keystore/BUILD.bazel
- shared/keystore/key.go
- shared/keystore/key_test.go
- shared/mathutil/math_helper_test.go
- tools/cluster-pk-manager/client/BUILD.bazel
- validator/BUILD.bazel
Reverts prysmaticlabs/prysm#3752
> Revert "Change BLS Library to Herumi"

- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/log_processing_test.go
- endtoend/endtoend_test.go
- endtoend/evaluators/finality.go
- endtoend/evaluators/validator.go
> Optimize Processing Of Past Logs

- WORKSPACE
- beacon-chain/BUILD.bazel
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/helpers/attestation_test.go
- beacon-chain/core/state/transition_test.go
- beacon-chain/gateway/server/BUILD.bazel
- beacon-chain/operations/attestation_test.go
- beacon-chain/powchain/deposit_test.go
- beacon-chain/rpc/validator/server_test.go
- beacon-chain/sync/validate_proposer_slashing_test.go
- beacon-chain/sync/validate_voluntary_exit_test.go
- shared/bls/BUILD.bazel
- shared/bls/bls.go
- shared/bls/bls_benchmark_test.go
- shared/bls/bls_test.go
- shared/bls/spectest/BUILD.bazel
- shared/bls/spectest/aggregate_pubkeys_test.go
- shared/bls/spectest/msg_hash_compressed_test.go
- shared/bls/spectest/msg_hash_uncompressed_test.go
- shared/bls/spectest/priv_to_pub_test.go
- shared/keystore/BUILD.bazel
- shared/keystore/key.go
- shared/keystore/key_test.go
- shared/mathutil/math_helper_test.go
- tools/cluster-pk-manager/client/BUILD.bazel
- tools/cluster-pk-manager/server/BUILD.bazel
- tools/faucet/BUILD.bazel
- validator/BUILD.bazel
> Reverts the Revert which reverted the Revert (#4011)"

- WORKSPACE
https://github.com/prysmaticlabs/ethereumapis/pull/40 was merged and the branch deleted, 9747dd9834b24a8affe4e3b23b0d10efcb32f6a9 no longer exists.
> Fix deleted branch from ethereumapis

- beacon-chain/sync/initial-sync/round_robin.go
- beacon-chain/sync/rpc_beacon_blocks_by_range.go
- proto/beacon/db/attestation_container.pb.go
- proto/beacon/db/finalized_block_root_container.pb.go
> Set Step Value to 1 in case of a Low Count

- WORKSPACE
This might resolve some zlib  fetch issue.
> Update protobuf to v3.10.1 and rules_docker to v0.12.1

- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/service.go
- proto/beacon/db/attestation_container.pb.go
- proto/beacon/db/finalized_block_root_container.pb.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/eth/v1alpha1/archive.pb.go
- proto/eth/v1alpha1/attestation.pb.go
- proto/eth/v1alpha1/beacon_block.pb.go
- proto/eth/v1alpha1/beacon_chain.pb.go
- proto/eth/v1alpha1/node.pb.go
- proto/eth/v1alpha1/slasher.pb.go
- proto/eth/v1alpha1/validator.pb.go
- proto/sharding/p2p/v1/messages.pb.go
Reverts prysmaticlabs/prysm#4086
Saw a few issues regarding locking for a large amount of time. Looked like a multiple dead locks blocked access to check points. 
https://jaeger.prylabs.network/trace/c3abadc814f07226d7d46d5b670511f3
https://jaeger.prylabs.network/trace/788e686f596523f4807d450775dd2ff9?uiFind=57bff5b80a5a337c
> Revert "Add Lock When Accessing Checkpoints"

- beacon-chain/sync/pending_blocks_queue.go
- beacon-chain/sync/pending_blocks_queue_test.go
Reverts prysmaticlabs/prysm#4066
> Revert "Update Pending Queue"

- beacon-chain/blockchain/forkchoice/benchmark_test.go
- beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
- beacon-chain/blockchain/forkchoice/process_attestation.go
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/process_block_test.go
- beacon-chain/blockchain/forkchoice/service.go
- beacon-chain/blockchain/forkchoice/service_test.go
- beacon-chain/db/db.go
- beacon-chain/db/kv/validators.go
- beacon-chain/db/kv/validators_test.go
- beacon-chain/sync/pending_blocks_queue.go
- beacon-chain/sync/pending_blocks_queue_test.go
- proto/beacon/db/attestation_container.pb.go
- proto/beacon/db/finalized_block_root_container.pb.go
- proto/beacon/p2p/v1/messages.pb.go
- proto/beacon/p2p/v1/types.pb.go
- proto/beacon/rpc/v1/services.pb.go
- proto/beacon/rpc/v1_gateway/services.pb.go
- proto/eth/v1alpha1/archive.pb.go
- proto/eth/v1alpha1/attestation.pb.go
- proto/eth/v1alpha1/beacon_block.pb.go
- proto/eth/v1alpha1/beacon_chain.pb.go
- proto/eth/v1alpha1/node.pb.go
- proto/eth/v1alpha1/slasher.pb.go
- proto/eth/v1alpha1/validator.pb.go
- proto/sharding/p2p/v1/messages.pb.go
- validator/internal/aggregator_service_mock.go
- validator/internal/attester_service_mock.go
- validator/internal/proposer_service_mock.go
- validator/internal/validator_service_mock.go
> Use Latest Vote Map

- beacon-chain/blockchain/forkchoice/process_attestation.go
- beacon-chain/blockchain/forkchoice/process_attestation_test.go
Part of #4098 
This PR adds in the additional checks to prevent accepting future beacon block
> Fork choice beacon block checks

- README.md
We are running 0.9.0 at the moment.
> Update README.md to reflect spec version

- tools/faucet/BUILD.bazel
- tools/faucet/main.go
- tools/faucet/server.go
- Adjustable min score
- More verification
- More logging
> Faucet improvements

- beacon-chain/blockchain/chain_info.go
Update chain head state to return nil instead of error if nil in db
> Chain head state return nil instead of err

- tools/faucet/server.go
> Faucet: Use client IP in captcha requests

- beacon-chain/sync/validate_beacon_attestation.go
Check the cache first and exit early if there is a bit
> Move recently seen roots

- proto/beacon/db/attestation_container_helper.go
- proto/beacon/db/attestation_container_helper_test.go
This was causing a panic in attestation insertion into DB :scream:
> prevent OR on bitlists of different length

- beacon-chain/interop-cold-start/service.go
- validator/client/validator_propose_test.go
- validator/flags/flags.go
-[x] Fixes the order so that head block root can be saved.
> Fix Saving of Genesis State Order

- contracts/deposit-contract/sendDepositTx/sendDeposits.go
> Fix Deposit Sender Utility

- shared/cmd/flags.go
- slasher/db/schema.go
This PR changes the default jaeger endpoint so jaeger works without any changes.
> Change jaeger default endpoint

- beacon-chain/operations/attestations/kv/aggregated_test.go
> Fix flaky TestKV_Aggregated_CanSaveRetrieve

- beacon-chain/cache/feature_flag_test.go
- beacon-chain/db/iface/interface.go
- beacon-chain/db/kafka/passthrough.go
- beacon-chain/rpc/validator/server.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
Fixes #4274 
Deprecated unused flags from #4264
> Deprecate active count and committee cache flags

- beacon-chain/core/helpers/committee_test.go
- shared/stateutil/attestations.go
- shared/stateutil/validators.go
- tools/faucet/server.go
> Fix Goerli Faucet

- beacon-chain/core/blocks/BUILD.bazel
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_fuzz_test.go
- beacon-chain/core/helpers/attestation.go
Also removed some unused errors.
> Add a few fuzz tests to core logic

- beacon-chain/rpc/aggregator/server.go
For aggregator, head state is used to calculate committee indices of the requested slot. Which only needs to be calculated at epoch boundary slot.
We naively advance slots up to requested slots which was unnecessary.
Ex:
head slot is 100, req slot is 150, epoch start of 150 is 128. Advance 100 to 128.
head slot is 100, req slot is 127,  epoch start of 127 is 64. Do nothing
> Optimize aggregator process slots

- beacon-chain/rpc/service.go
To give us a better understanding of how performance over time is changing.
See more: https://github.com/grpc-ecosystem/go-grpc-prometheus#histograms
> Add prometheus gRPC time histograms

- beacon-chain/db/BUILD.bazel
- beacon-chain/db/alias.go
- beacon-chain/db/db.go
- beacon-chain/db/db_kafka_wrapped.go
Build with `--define=kafka_enabled=false` to exclude kafka dependencies.
> Config to exclude kafka dep at build time

- beacon-chain/core/epoch/precompute/reward_penalty.go
> Comment typo

- validator/accounts/account.go
- validator/main.go
> Minor fixes to create keys errors

- beacon-chain/blockchain/forkchoice/BUILD.bazel
- beacon-chain/blockchain/forkchoice/process_attestation.go
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/process_block_test.go
- shared/params/config.go
This caused run time instability due to missing shift time tolerance, will have to think about this more
> Revert "Explicit use of GENESIS_SLOT in fork choice"

- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/subscriber.go
- shared/messagehandler/messagehandler.go
This handles any panics that occur when validation occurs for gossipsub messages
> Handle Pubsub Panics

- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/service.go
This fixes our deposit log processing issues that were coming up with a local setup
> Fix Deposit Log Processing

- beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
- beacon-chain/blockchain/forkchoice/service.go
- beacon-chain/blockchain/forkchoice/tree_test.go
This was panicking in run time.
Thanks @terencechain for fixing test.
> Return an error on nil head state in fork choice

- beacon-chain/blockchain/service_test.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/state/state.go
- beacon-chain/core/state/state_test.go
- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/log_processing_test.go
- beacon-chain/powchain/service.go
- beacon-chain/rpc/validator/assignments_test.go
- beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
- beacon-chain/sync/rpc_status_test.go
- shared/interop/generate_genesis_state.go
- shared/interop/generate_genesis_state_test.go
- shared/testutil/deposits.go
Revert #4372 and #4373.
Issue #4370 was a misunderstanding, the actual bug is something else.
> Revert 4372 and 4373

- beacon-chain/rpc/beacon/attestations.go
Fixed bad go imports from #4390
> Fixed goimports

- shared/params/spectest/BUILD.bazel
- shared/params/spectest/config.go
- shared/stateutil/state_root.go
Also use custom state ssz for spec test.
> SSZ: temporarily disable roots cache until cache issues can be resolved

- beacon-chain/sync/rpc_status_test.go
> Unskip RPC Hello Test

- beacon-chain/blockchain/forkchoice/BUILD.bazel
- beacon-chain/blockchain/forkchoice/metrics.go
- beacon-chain/core/epoch/precompute/attestation.go
We have been saying that i'd be nice to have metrics for total and target balances from validators. This PR added them metrics
> total and target balances metrics

- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/process_block_test.go
- beacon-chain/rpc/validator/assignments.go
- beacon-chain/rpc/validator/assignments_test.go
- shared/featureconfig/flags.go
Save justified state before saving justified check point
> Save justified checkpoint state

- beacon-chain/powchain/BUILD.bazel
- beacon-chain/powchain/block_reader_test.go
- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/log_processing_test.go
- beacon-chain/powchain/service.go
- beacon-chain/powchain/service_test.go
- beacon-chain/powchain/testing/BUILD.bazel
- beacon-chain/powchain/testing/mock.go
No logs can be processed with #4392
> Revert #4392

- shared/params/config.go
Quick fix for incorrect YAML tag after #4453
> Fix bad update in #4453

- beacon-chain/sync/subscriber.go
Seeing some deadlines at 10s for blocks.
> Use a longer deadline for processing pubsub messages

- beacon-chain/db/kv/kv.go
Resolves #4482 
---
This PR adds more resource allocation to boltdb to prevent sync getting stuck due to the db resource constraints. Works and is able to sync with the testnet.
> Allocate More Resources to BoltDB

- beacon-chain/sync/initial-sync/round_robin.go
Initial sync's `bestFinalized()` has been superseded with an upgrade version in `p2p/peers`; this removed the unused function.
> Remove unused function

- beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
- beacon-chain/blockchain/forkchoice/process_block.go
- beacon-chain/blockchain/forkchoice/service_test.go
- beacon-chain/blockchain/service.go
- beacon-chain/cache/committee.go
- beacon-chain/cache/feature_flag_test.go
- beacon-chain/core/blocks/block_operations_test.go
- beacon-chain/core/blocks/spectest/block_processing_test.go
- beacon-chain/core/epoch/epoch_processing_test.go
- beacon-chain/core/helpers/BUILD.bazel
- beacon-chain/core/helpers/committee.go
- beacon-chain/core/helpers/committee_test.go
- beacon-chain/core/helpers/validators.go
- beacon-chain/core/helpers/validators_test.go
- beacon-chain/core/state/benchmarks/BUILD.bazel
- beacon-chain/core/state/benchmarks/benchmarks_test.go
- beacon-chain/rpc/beacon/assignments_test.go
- beacon-chain/rpc/beacon/validators_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
- shared/testutil/spectest.go
Reverts prysmaticlabs/prysm#4502 mistakenly merged - new cache hasnt been in prod and requires more testing
> Revert "Deprecate new cache feature flag"

- README.md
This is a super minor documentation fix follow up for #4562
> Removes trailing backslash, refs #4562

- README.md
Removes old gitbook links and replaces them with new doc portal
> Updated doc portal links

- beacon-chain/powchain/log_processing.go
When the flag was released and made default , we also removed this part of the code. This adds it back.
> Save Deposit Data at Every Interval

- tools/faucet/main.go
- tools/faucet/server.go
> Fix Faucet

- beacon-chain/operations/attestations/prepare_forkchoice.go
> Fork choice: Ensure lengths are the same before checking overlap

- beacon-chain/blockchain/forkchoice/process_attestation.go
- beacon-chain/blockchain/forkchoice/process_block.go
- Don't update votes
- Don't update block tree cache
> Disable more fork choice options with flag on

- beacon-chain/blockchain/chain_info.go
- beacon-chain/blockchain/chain_info_test.go
- beacon-chain/blockchain/service_test.go
- beacon-chain/sync/pending_blocks_queue.go
Copy is cheap(ish) now. Verified with a 1 minute profile at HEAD and did not see the Copy method in the flame at all.
> Copy head state to ensure it is never mutated

- beacon-chain/sync/subscriber_beacon_blocks.go
> Pubsub: Ignore block already in database

- shared/stateutil/state_root.go
> SSZ state cache: Only use cached value when flag is on

- beacon-chain/sync/pending_attestations_queue.go
Add more fields to logging `Requesting block for pending attestation....`
> Better log for `Requesting block for pending attestation...`

- beacon-chain/state/types.go
Also only copy the merkle layers if not nil
> Beacon State: Ensure all fields are dirty on initialization

- beacon-chain/rpc/validator/attester.go
- beacon-chain/rpc/validator/server.go
This should make the call more efficient too.
> RPC: Use the proper db access level, use head root from head fetcher

- beacon-chain/db/kv/attestations.go
- beacon-chain/db/kv/blocks.go
This changes all bolt batch calls to an update call.
> Remove All Batch DB Calls

- shared/featureconfig/flags.go
#4774 didn't add the flag to `BeaconChainFlags` list
> Add `forkchoiceAggregateAttestations` to flag list

- beacon-chain/blockchain/chain_info.go
- beacon-chain/blockchain/service.go
- beacon-chain/blockchain/testing/mock.go
- beacon-chain/state/setters.go
- beacon-chain/sync/initial-sync/service.go
Reverts prysmaticlabs/prysm#4789 as it breaks `initial-sync-cache-state`
> Revert "Update Slices More Efficiently"

- beacon-chain/sync/rpc_goodbye.go
> Prevent panic on wrong interface conversion

- beacon-chain/p2p/peers/status.go
This was causing a panic for some reason
> Add nil check to peers status

- shared/featureconfig/config.go
- shared/featureconfig/flags.go
- shared/memorypool/BUILD.bazel
- shared/memorypool/memorypool.go
This flag makes #4811 optional since it may be causing state root issues.
> Add mempool feature flag

- beacon-chain/blockchain/process_attestation_helpers.go
- beacon-chain/blockchain/process_block_helpers.go
Check the current head state first before fetching from db for block processing/attestation procesing
> Check HeadState First

- beacon-chain/operations/attestations/kv/aggregated.go
No need to iterate over the entire list!
> Improve attestation cache check from O(n) to O(1) access time

- beacon-chain/sync/pending_attestations_queue.go
Fixes Panics in queue in #4829
> Fix Pending Attestation Queue Panic

- beacon-chain/db/kv/backup.go
This is a bit slower, but results in a much smaller backup file.
> Create backups without freelist. 

- beacon-chain/blockchain/process_attestation_helpers.go
- beacon-chain/blockchain/process_block_helpers.go
Reverts prysmaticlabs/prysm#4830
> Revert "Check HeadState First"

- beacon-chain/cache/attestation_data.go
- beacon-chain/cache/feature_flag_test.go
- beacon-chain/core/state/benchmarks_test.go
- beacon-chain/rpc/validator/BUILD.bazel
- beacon-chain/rpc/validator/attester_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
This has been in prod for several months without issue.
> Enable attestation cache flag by default, deprecate feature flag

- third_party/README.md
> Update README for Patching Ethereum APIs

- beacon-chain/main.go
> Only set gc percent if the flag is set

- beacon-chain/sync/validate_aggregate_proof.go
Cosmetic tidy-up for span information.
> Fix double period in span name

- beacon-chain/db/kv/state.go
> Add a clarifying comment from #4909

- beacon-chain/blockchain/head.go
- beacon-chain/blockchain/process_block.go
- beacon-chain/blockchain/process_block_helpers.go
- beacon-chain/blockchain/process_block_test.go
- beacon-chain/blockchain/receive_block.go
- beacon-chain/blockchain/service.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
This feature adds a significant increase to sync speed!
> Release --initial-sync-cache-state 

- beacon-chain/blockchain/process_block.go
Duplicated code block. See line 206 above.
> Removed duplicated SaveAttestations

- validator/BUILD.bazel
> Use correct image name for validator debug image

- WORKSPACE
- validator/keymanager/BUILD.bazel
- validator/keymanager/wallet.go
This updates the eth2 wallet keymanager for the spec changes in v0.10.x.
> Update eth2 wallet keymanager (v0.10.1)

- beacon-chain/state/stategen/BUILD.bazel
- beacon-chain/state/stategen/log.go
> Add log file for stategen pkg

- beacon-chain/state/stategen/BUILD.bazel
- beacon-chain/state/stategen/errors.go
> Add error definitions for state gen pkg

- beacon-chain/blockchain/receive_attestation.go
- beacon-chain/blockchain/service.go
Resolves #5015 
---
Fixes race condition by synchronising order of execution.
> Fixes race condition at genesis

- WORKSPACE
- tools/cross-toolchain/configs/clang/bazel_2.1.1/config/BUILD
- tools/cross-toolchain/configs/gcc/bazel_2.1.1/config/BUILD
- tools/cross-toolchain/configs/versions.bzl
- tools/cross-toolchain/install_osxcross.sh
- tools/cross-toolchain/rbe_toolchains_config.bzl
> Cross-compile OSX: Remove dropbox link, add sha256 check

- .bazelrc
- .buildkite-bazelrc
- WORKSPACE
- bazel.sh
- beacon-chain/core/helpers/BUILD.bazel
- proto/slashing/BUILD.bazel
- third_party/kafka/BUILD.bazel
Also adds a release config flag for stamping
> Run buildifer, remove duplicated WORKSPACE entries

- beacon-chain/rpc/validator/assignments.go
Part of #4836 
---
Currently our duties response only reports either active or unknown status. This PR is a simple change to report the real status of the validator.
> Report Validator Status in Duties

- WORKSPACE
> Add sha256 to external dependency librdkafka

- beacon-chain/state/stategen/BUILD.bazel
- beacon-chain/state/stategen/hot.go
- beacon-chain/state/stategen/hot_test.go
- beacon-chain/state/stategen/replay.go
- beacon-chain/state/stategen/service.go
Added functionality to load hot state by root, this is part of new getter for retrieving via the new state mgmt service. Added tests to go along with the implementations
> Load hot state by root

- slasher/node/BUILD.bazel
- slasher/node/node.go
This adds the prometheus metrics collector for the slasher.
> Add Prometheus Service for Slasher

- shared/featureconfig/config.go
- validator/node/BUILD.bazel
- validator/node/node.go
It follows our previous PR, #5026 and also adds in the config changes for the validator.
> Add Config Change for Validator

- beacon-chain/state/stategen/BUILD.bazel
- beacon-chain/state/stategen/cold.go
- beacon-chain/state/stategen/cold_test.go
- beacon-chain/state/stategen/service.go
- slasher/beaconclient/receivers_test.go
- slasher/beaconclient/service.go
- slasher/detection/attestations/spanner.go
This PR adds one method to retrieve archived point and one method to recover archived point. The recovery method is designed for users that may toggle feature flag between new state service and the old one. Also added tests to go with archived point retrieval and archived point recovery
> Archived point retrieval and recovery

- slasher/beaconclient/receivers.go
[Resolves] #5091
continue on error from rpc
> Fix slasher rpc disconnect on error

- beacon-chain/operations/attestations/service.go
- beacon-chain/rpc/beacon/committees_test.go
- beacon-chain/state/stategen/BUILD.bazel
- beacon-chain/state/stategen/setter.go
- beacon-chain/state/stategen/setter_test.go
This PR adds `SaveState` which is the entry point to save state via new state mgmt service. Also added comprehensive tests to go with it
> New state setter

- slasher/README.md
This PR updates the slasher README to include instruction to run it and information about it's purpose.
> Update README for Slasher

- beacon-chain/core/epoch/precompute/reward_penalty.go
- beacon-chain/core/epoch/precompute/reward_penalty_test.go
Fixes https://github.com/prysmaticlabs/prysm/issues/5105
Found by fuzz testing!
> Fix reward and penality zero epoch bug

- slasher/beaconclient/receivers.go
Very minor fixes for slasher, in case the stream gives us something nil.
Also cleans up the logs a bit.
> Minor slasher fixes

- WORKSPACE
Includes https://github.com/prysmaticlabs/go-bitfield/pull/28
> Update go-bitfield 

- beacon-chain/core/state/BUILD.bazel
- beacon-chain/core/state/benchmarks_test.go
> Add Improvements to State Benchmarks

- slasher/detection/detect.go
- slasher/detection/detect_test.go
- slasher/detection/listeners.go
- slasher/detection/service.go
- slasher/node/BUILD.bazel
- slasher/node/node.go
- slasher/rpc/BUILD.bazel
- slasher/rpc/server.go
- slasher/rpc/service.go
- slasher/rpc/service_test.go
[Part of] #5189
reintroduce slasher grpc server
> Setup Slasher RPC server

- beacon-chain/blockchain/service.go
- beacon-chain/cache/BUILD.bazel
- beacon-chain/cache/skip_slot_cache.go
- beacon-chain/core/state/benchmarks_test.go
- beacon-chain/core/state/transition.go
- beacon-chain/interop-cold-start/service.go
- beacon-chain/rpc/validator/proposer_test.go
- beacon-chain/state/BUILD.bazel
- beacon-chain/state/state_trie.go
- beacon-chain/state/types_test.go
- shared/testutil/block.go
> Add span to HTR and skip slot cache

- beacon-chain/p2p/discovery.go
- beacon-chain/p2p/options.go
> Add ipv6 multiaddr support

- beacon-chain/blockchain/head.go
- beacon-chain/blockchain/process_block.go
- beacon-chain/blockchain/process_block_helpers.go
- beacon-chain/state/state_trie.go
Reverts prysmaticlabs/prysm#5221
> Revert "Add Fast Copy of Trie"

- endtoend/minimal_e2e_test.go
This will allow us to run longer running e2e tests on master.
> Add configurable e2e epochs

- .bazelrc
- .gitignore
- WORKSPACE
- shared/debug/BUILD.bazel
- shared/debug/cgo_symbolizer.go
This was very helpful when analyzing callgrind profiles.
> Debug: add cgo symbolizer

- shared/params/config.go
Tidy-up for comments with bad info.
> Fix incorrect domain type comments

- beacon-chain/blockchain/init_sync_process_block.go
- beacon-chain/blockchain/process_block.go
- beacon-chain/blockchain/process_block_helpers.go
- beacon-chain/sync/initial-sync-old/round_robin.go
- beacon-chain/sync/initial-sync-old/round_robin_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
> Invert init-sync-batch-save-blocks flag for v0.11

- BUILD.bazel
- beacon-chain/flags/config.go
- beacon-chain/p2p/config.go
- beacon-chain/powchain/service.go
- beacon-chain/sync/initial-sync/fsm_test.go
- contracts/deposit-contract/testutils.go
- nogo_config.json
- shared/featureconfig/config.go
- tools/analyzers/maligned/BUILD.bazel
- tools/analyzers/maligned/analyzer.go
- tools/analyzers/maligned/maligned.go
- validator/client/fake_validator_test.go
This adds another compile time static analysis check to enforce proper struct field ordering to reduce space.
> Add maligned struct static check

- slasher/beaconclient/receivers.go
- slasher/db/kv/block_header.go
- slasher/db/kv/block_header_test.go
- slasher/db/kv/schema.go
- slasher/detection/detect.go
- slasher/detection/detect_test.go
- slasher/detection/proposals/BUILD.bazel
- slasher/detection/proposals/detector.go
- slasher/detection/proposals/detector_test.go
[Part of] #5116
---
Spec changed to consider only same slot proposer as a slashing offence
this pr consider slot as the unique identifier per validator id
> Update to slash by slot instead of epoch

- proto/slashing/slashing.pb.go
- proto/slashing/slashing.proto
Removes unused protos from the slasher, such as min max span protos and slashing response.
> Remove unused slashing protos

- .buildkite-bazelrc
This uploads build results from buildkite (or local).
Example: https://builds.prylabs.net/invocation/511d0273-d91f-44ac-924b-403706ced520#
> Add buildbuddy BES

- beacon-chain/p2p/info.go
> Print Out ENRs For P2P Handler

- .buildkite-bazelrc
- validator/client/runner.go
I think these extra goroutines might be causing issues with the logging in #4702.
> Use less goroutines in validator runner

- beacon-chain/state/stategen/service.go
This PR sets the new state mgmt service constructor to use param config `SlotsPerArchivedPoint`
> Use param config `SlotsPerArchivedPoint`

- tools/cluster-pk-manager/server/main.go
- tools/faucet/server.go
Part of #5362, we are now offering more eth via our faucet for v0.11
> Amend Faucet to Offer 32.5 ETH for v0.11

- beacon-chain/cache/depositcache/deposits_cache.go
- beacon-chain/powchain/log_processing.go
- beacon-chain/rpc/validator/server.go
- beacon-chain/rpc/validator/server_test.go
- beacon-chain/rpc/validator/status.go
- beacon-chain/rpc/validator/status_test.go
- validator/client/runner.go
- validator/client/validator.go
- validator/client/validator_test.go
Reverts prysmaticlabs/prysm#5300
> Revert "Validator client improvements"

- beacon-chain/p2p/options.go
> Use MultiAddress Builder

- beacon-chain/p2p/service.go
- beacon-chain/p2p/subnets.go
- beacon-chain/sync/rpc_metadata_test.go
- proto/beacon/p2p/v1/messages.proto
> Networking Fixes

- beacon-chain/blockchain/process_block_helpers.go
- beacon-chain/blockchain/process_block_test.go
> Fix overflow in currentSlot

- beacon-chain/p2p/service.go
We shift these errors to debug instead to stop it from spamming our logs
> Less Scary Connection Logs

- shared/featureconfig/config.go
[Resolves] #5514
---
change the config value of `Broadcastslashing` when flag `--broadcat-slashings` is set
> Fix broadcast slashing flag

- beacon-chain/core/epoch/precompute/reward_penalty.go
- beacon-chain/core/epoch/precompute/reward_penalty_test.go
- prysm.sh
~~⚠️ Consensus breaking, do not merge to master ⚠️~~
Retarget to `v0.12` branch
This PR fixes #5593
Change list:
* Reward functions to take correct target and head sum instead of all source sum
* Prevent overflow for reward numerator
> Reward and penalty fixes

- beacon-chain/core/epoch/precompute/reward_penalty_test.go
Fixed a broken test `TestAttestationDeltaPrecompute` reported by @protolambda. Thanks!
Reference: https://github.com/prysmaticlabs/prysm/pull/5595#discussion_r414140982
> Fix TestAttestationDeltaPrecompute

- WORKSPACE
- beacon-chain/rpc/beacon/assignments.go
- beacon-chain/rpc/beacon/assignments_test.go
- beacon-chain/rpc/beacon/validators.go
- beacon-chain/rpc/beacon/validators_test.go
Feature
prysmaticlabs/ethereumapis#137
We need this to improve API usage in https://github.com/gobitfly/eth2-beaconchain-explorer
prysmaticlabs/ethereumapis#137
Required for https://github.com/gobitfly/eth2-beaconchain-explorer/pull/83
> Update EthereumAPIs to prysmaticlabs/ethereumapis#137

- prysm.sh
Feature
As title describes. Gives user faster feedback when attempting to use armv7l to run prysm.
N/A
> Update prysm.sh to fail fast on armv7l

- prysm.bat
Feature
Adds prysm.bat that runs under windows without extra dependencies (e.g. Docker / git bash / WSL)
Fixes #5624
Lacks GPG checks on dist file downloads, but otherwise has feature parity with prysm.sh
> added prysm.bat for native windows support (#5624)

- beacon-chain/sync/rpc_beacon_blocks_by_range.go
Exit early after we finish responding to a request from a 
peer if we have nothing left.
N.A.
> Exit Early from Responding

- beacon-chain/state/getters.go
Bugfix.
Fix the code bug or mistake
Fixes #5642
None
> Missing defer before unlock

- validator/client/service.go
- validator/client/validator.go
> Feature
Change list:
* Add `DomainSelectionProof` and `DomainAggregateAndProof` to validator domain cache
* Increase NumCounters and MaxCost to 192 since the new keys
> Add more domains to domain cache

- beacon-chain/blockchain/metrics.go
- beacon-chain/blockchain/receive_block.go
> Feature
Add sent block time metric to monitor proposer <-> BN operation
> Add sent block time metric

- WORKSPACE
Bug fix
Apline images did not work previously.
Fixes #5768 
> Use alpine base image including libstdc++

- beacon-chain/rpc/validator/proposer.go
- beacon-chain/sync/initial-sync/blocks_fetcher.go
- beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
- beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
> Run `go fmt` in prysm

- beacon-chain/blockchain/head.go
- beacon-chain/blockchain/metrics.go
> Add metric for reorg count

- shared/featureconfig/config.go
removes left-over flag (old init sync was removed in #5761 )
> Removes deprecated flag from config

- beacon-chain/sync/rpc_status.go
Revert Change
This reverts one of the added status conditions due to the fact that it 
causing non-trivial peering issues. 
This is documented in #5827
> Revert Change Added in #5811

- WORKSPACE
> Update spec tests to v0.11.2

- slasher/detection/detect.go
Optimization
Since the slasher is performing several hundred attestation operations a second, small improvements like this matter a lot. Before we would use `IntersectionUint64` which is a very expensive function on every duplicate attestation received. This changes the function to check if it qualifies as a slashable vote first, before performing the more expensive operation.
> Move cheaper operations earlier into detection code path

- beacon-chain/blockchain/head.go
- beacon-chain/blockchain/process_block.go
- beacon-chain/blockchain/process_block_helpers.go
Reverts prysmaticlabs/prysm#5764
> Revert "Use A Single State in Sync"

- beacon-chain/core/blocks/block_operations.go
- beacon-chain/core/blocks/block_operations_test.go
Bug fix
This PR adds additional validation to ensure that a block has the proper slot before processing the block header.
Part of #5844 
> Ensure proper block slot for process block header

- beacon-chain/sync/rpc_status.go
Code Cleanup
Change an error log to debug and disconnect on an 
incorrect fork digest when sending a status request. 
Follows on from #5852 
N.A
> More Handshake Cleanup

- validator/accounts/account.go
This PR suggests users to paste the raw deposit transaction data into step 3 of prylabs.net/participate for easier participation.
Fixes #5729
> Add Suggestion to Paste in Deposit Data into Prylabs/Participate

- slasher/beaconclient/BUILD.bazel
- slasher/beaconclient/receivers.go
This PR adds more verbosity to our logs in the slasher for new blocks.
> More Verbose Logs for Incoming Blocks

- beacon-chain/operations/slashings/service.go
Bug Fix
It adds in slashing metrics so that we get the accurate amount of pending slashings
in our operations pool.
N.A
> Fix Slashing Metrics

- WORKSPACE
- beacon-chain/core/state/interop_regression_test.go
- beacon-chain/core/state/state.go
- beacon-chain/operations/slashings/service_attester_test.go
- beacon-chain/rpc/validator/proposer_test.go
- beacon-chain/state/stateutil/blocks.go
- proto/testing/ssz_static_test.go
- shared/params/config.go
Spec update 
Part of #5935 , this PR mirrors https://github.com/ethereum/eth2.0-specs/pull/1794 from the spec. 
MaxAttesterSlashings: 1 -> 2 (mainnet and minimal)
> Increase MaxAttesterSlashings config to 2 for v0.12

- shared/featureconfig/config.go
Merge issue fix 
This PR fixes a merge issue on branch v0.12.
> Fix merge build issue on v0.12

- WORKSPACE
Change Spec tests to v0.12 from v0.11.3
> Update Spec Tests 

- validator/db/manage.go
- validator/flags/flags.go
> Runs `go fmt` and updates validator files

- shared/params/config.go
> Bug fix
Explicitly set the next fork version to genesis fork version.
N/A
> shared/params: fix next fork version for witti

- beacon-chain/powchain/service.go
Bug Fix
Fixes a genesis bug that came up in witti.
N.A
> Add Block Time when Initializing Service

- beacon-chain/state/references_test.go
- beacon-chain/state/setters.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
Invert state ref copy flag instead or release it
> Invert state ref copy flag

- .github/ISSUE_TEMPLATE/feature_flag.md
- shared/featureconfig/README.md
There is a lack of clarity around what, when, why, and how exactly we should use feature flags. I've written a short README.md about this and proposed a tracking issue template for contributors to use to help them stay on top of their in progress issues. I recommend that all new feature flags follow this pattern going forward.
> Add documentation and issue template for feature flags

- slasher/beaconclient/historical_data_retrieval.go
- slasher/detection/listeners.go
- slasher/detection/listeners_test.go
- slasher/detection/service.go
Bug fixes and log improvements
This PR is a few essential fixes for the slasher, preventing an unpreventable error loop in historical detection.
> Small fixes for slasher 

- beacon-chain/blockchain/info.go
- beacon-chain/core/blocks/block_operations.go
- beacon-chain/rpc/beacon/committees_test.go
- beacon-chain/rpc/validator/assignments_test.go
- beacon-chain/rpc/validator/status_test.go
- beacon-chain/sync/rpc_beacon_blocks_by_range.go
- beacon-chain/sync/rpc_status_test.go
- shared/cmd/helpers.go
Other/Cleanup
- removes redundant type conversions
Too small and quick to fix to warrant a separate issue.
- discovered when working on #6038, where updating return type, caused number of redundant type conversions.
> Removes redundant type conversions

- beacon-chain/blockchain/init_sync_process_block_test.go
- beacon-chain/blockchain/service_test.go
- beacon-chain/forkchoice/interfaces.go
- beacon-chain/main.go
- beacon-chain/p2p/encoder/ssz.go
- beacon-chain/p2p/service_test.go
- beacon-chain/p2p/testing/p2p.go
- beacon-chain/rpc/beacon/validators_stream.go
- beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go
- shared/bls/spectest/aggregate_test.go
- shared/bls/spectest/aggregate_verify_test.go
- shared/bls/spectest/fast_aggregate_verify_test.go
- shared/bls/spectest/sign_test.go
- shared/bls/spectest/verify_test.go
- slasher/db/kv/proposer_slashings_test.go
- slasher/detection/attestations/spanner.go
- slasher/main.go
- tools/bootnode-query/main.go
- tools/bootnode/bootnode.go
- tools/deployContract/deployContract.go
- tools/drainContracts/drainContracts.go
- tools/faucet/main.go
- tools/faucet/server.go
- tools/interop/convert-keys/main.go
- tools/pcli/main.go
- tools/relaynode/relaynode.go
- tools/sendDepositTx/sendDeposits.go
- tools/unencrypted-keys-gen/main.go
- tools/unencrypted-keys-gen/main_test.go
- validator/main.go
Part of sunday funday code clean up
This PR Ran the automatic `cleanup` feature from goland
> Ran code cleanup from goland

- validator/db/manage_test.go
- validator/flags/flags.go
> Fixes go fmt issues

- beacon-chain/powchain/service_test.go
No tracking, just some broken tests due to a bad merge in v0.12
> Fix Broken Powchain Tests v0.12

- beacon-chain/blockchain/process_block_helpers.go
Adds https://github.com/ethereum/eth2.0-specs/pull/1864/files and https://github.com/ethereum/eth2.0-specs/pull/1867 to Prysm for v0.12.1
Part of #5935 and v0.12.1
> Pseudocode Fixes for v0.12.1

- WORKSPACE
Update to v0.12.1
Updates spec tests to v0.12.1 .
N.A
> Update Spec Tests

- beacon-chain/blockchain/process_attestation.go
- beacon-chain/sync/pending_attestations_queue_test.go
- beacon-chain/sync/subscriber.go
Part of #5935, this PR resolves some outstanding comments for v0.12
> Resolve Final Outstanding Comments for v0.12

- beacon-chain/flags/base.go
- beacon-chain/sync/subscriber.go
Other
After #6186 resolved some PR feedback, it was clear that the subscribeDynamic method was no longer necessary.
> Remove subscribeDynamic which was not dynamic anymore

- beacon-chain/sync/rpc_beacon_blocks_by_range.go
- shared/featureconfig/config.go
> Ivan's v0.12 Feedback

- tools/unencrypted-keys-gen/BUILD.bazel
- tools/unencrypted-keys-gen/main.go
Feature
This is helpful for testing, debugging.
N/A
> Add --random flag for unencrypted keygen

- beacon-chain/blockchain/process_block_helpers.go
With Justified Checkpoints being a `zero hash` instead of the genesis block root, this 
causes issues when processing blocks around genesis. 
We handle for the case of when checkpoints are zero hashes instead genesis roots in `blockchain` this allows us to determine justified checkpoints correctly.
Fixes #6247 
> Fix Genesis Justified Checkpoints

- beacon-chain/blockchain/process_block_helpers.go
- beacon-chain/blockchain/process_block_test.go
Minor clean up for #6249 
* Added a helper method
* Added a test to the helper method
Tested run time with and without new state mgmt
> Minor clean up to 6249

- go.sum
Other
- Updates `go.sum` after `go mod tidy` run
- It is probably a good idea to have this added as pre-merge check (just as we have with `go fmt`), otherwise we will have similar PRs from time to time.
> Updates go.sum

- beacon-chain/db/kv/kv.go
- beacon-chain/node/node.go
Bug fix 
This fixes a pathing issue on windows when placing the beacon-chain database.
> Fix windows DB path error and make errors more concise

- beacon-chain/rpc/service.go
- beacon-chain/rpc/service_test.go
- validator/client/service.go
This PR amends the scary insecure grpc connection warning and recommends users a way to generate certs by reading our docs portal.
Fixes #6145 and fixes #791
> Clarify Insecure gRPC Connection Logs

- shared/featureconfig/config.go
Feature
Helpful for debugging which development flags are being enabled.
N/A
No logic changes.
> Add a debug log statement when enabling dev flags

- beacon-chain/rpc/validator/proposer.go
- beacon-chain/rpc/validator/proposer_test.go
Reverts prysmaticlabs/prysm#6309
As reported by @nisdas , the previous implement logic was incorrect and it would revert data back 1024 blocks
```go
canonicalEth1Height := big.NewInt(0)
if latestEth1Height.Uint64() >= params.BeaconConfig().Eth1FollowDistance {
canonicalEth1Height =
big.NewInt(0).Sub(latestEth1Height, big.NewInt(int64(params.BeaconConfig().Eth1FollowDistance)))
}
```
> Revert "Fetch deposit data only up to canonical Eth1 height when proposing"

- beacon-chain/state/field_trie.go
- beacon-chain/state/setters.go
- beacon-chain/state/state_trie.go
- beacon-chain/state/stateutil/BUILD.bazel
- beacon-chain/state/types.go
Bug fix
This PR fixes some data race around field references that could be causing some memory leak issues where state references are kept in memory much longer than are necessary.
No issue filed.
These are cherry picked files from #6298.
> Fix race condition issues in beacon state

- beacon-chain/state/state_trie.go
- beacon-chain/state/state_trie_test.go
- shared/featureconfig/config.go
- shared/featureconfig/flags.go
> Release State Field Trie

- beacon-chain/state/getters.go
- beacon-chain/state/getters_test.go
> Audit resolution
Addresses feedback from Audit point qsp8
Part of #6327
> QSP8 - ActivationEligibilityEpoch nil case

- beacon-chain/rpc/debug/p2p.go
- beacon-chain/sync/deadlines.go
> Minor Improvements

- beacon-chain/blockchain/service.go
- beacon-chain/interop-cold-start/service.go
Bug fix
- Fixes 5 and 77 from [Audit Best Practices report](https://github.com/prysmaticlabs/prysm/issues/6337)
N/A
None
> Fixes error message wording

- beacon-chain/db/kv/BUILD.bazel
- beacon-chain/db/kv/blocks.go
- beacon-chain/db/kv/check_historical_state.go
- beacon-chain/db/kv/checkpoint.go
> Feature
Remove usages of `--enable-new-state-mgmt` within DB package
Part of #6072 
> Remove new state mgmt within db package

- beacon-chain/sync/initial-sync/service.go
Reverts prysmaticlabs/prysm#6368
This reverts the PR and adds in a comment on why we double unsubscribe.
> Revert "QSP-42 Remove Double Unsubscribe in Initial Sync"

- beacon-chain/sync/validate_proposer_slashing_test.go
Bug fix
It seems somehow TestValidateProposerSlashing_ContextTimeout has been failing for a while while not being detected by our CI.
This PR fixes the test so it doesn't panic
> Fix proposer slashing context timeout test

- beacon-chain/sync/service.go
> Add Back Disconnection Handler

- beacon-chain/db/iface/interface.go
- beacon-chain/db/kafka/passthrough.go
- beacon-chain/db/kv/blocks.go
- beacon-chain/db/kv/blocks_test.go
- beacon-chain/db/kv/operations.go
- beacon-chain/db/kv/operations_test.go
- beacon-chain/db/kv/slashings.go
- beacon-chain/db/kv/slashings_test.go
- slasher/db/kv/attester_slashings.go
- slasher/db/kv/proposer_slashings.go
>
Audit feedback
Move db delete functions to test scope only
Part of #6327 
> QST40 QST42 QST44 - Move deletes to test scope only

- beacon-chain/blockchain/head.go
Other
This PR adds more tracing visibility into blockchain operation for updating the head of the blockchain.
N/A
> Add span for updateRecentCanonicalBlocks

- shared/params/config.go
- shared/params/network_config.go
Testnet Config
-[x] Changes Genesis time for altona
-[x] Updates bootnodes for altona.
Fixes #
> Update Config for Altona

- beacon-chain/blockchain/chain_info.go
- beacon-chain/blockchain/head.go
- beacon-chain/blockchain/head_test.go
- beacon-chain/blockchain/info.go
- beacon-chain/blockchain/testing/mock.go
- beacon-chain/rpc/beacon/committees.go
- beacon-chain/rpc/validator/attester.go
Other
In some cases, block production can take over 500ms. After a brief investigation, I noticed that retrieving the head state was taking over 500ms. This PR adds more tracing spans to help capture and understand the time taken to produce a block.
N/A - No fixes here, just data collection.
> Add spans for head state access

- beacon-chain/rpc/service.go
> Bug fix
No mutex was added in code which handles new gRPC client connection logs, which led to concurrent map writes
Fixes #6434
> Fix Concurrent Map Write in gRPC Client Connected Logger

- beacon-chain/db/kv/archive.go
- beacon-chain/db/kv/attestations.go
- beacon-chain/db/kv/blocks.go
- beacon-chain/db/kv/checkpoint.go
- beacon-chain/db/kv/encoding.go
- beacon-chain/db/kv/encoding_test.go
- beacon-chain/db/kv/finalized_block_roots.go
- beacon-chain/db/kv/operations.go
- beacon-chain/db/kv/slashings.go
- beacon-chain/db/kv/state.go
- beacon-chain/db/kv/state_summary.go
> Best practice/code health
Add spans to beacon db kv's encode and decode
Part of #6337 
> Add spans to db kv's encode and decode

- beacon-chain/p2p/service.go
- beacon-chain/sync/rpc.go
- beacon-chain/sync/rpc_beacon_blocks_by_range.go
- beacon-chain/sync/rpc_beacon_blocks_by_root.go
- beacon-chain/sync/rpc_chunked_response.go
- beacon-chain/sync/rpc_goodbye.go
- beacon-chain/sync/rpc_metadata.go
- beacon-chain/sync/rpc_ping.go
- beacon-chain/sync/rpc_status.go
Other/Refactoring
- instead of inline constant literals, uses defined config constants
- item 49 from #6337
> QSP-BestPractice: Refactors inline ttfb/resp time constants

- shared/bls/BUILD.bazel
- shared/bls/bls.go
- shared/bls/herumi/BUILD.bazel
- shared/bls/herumi/signature.go
- shared/bls/herumi/signature_test.go
- shared/bls/signature_set.go
It adds in a new Signature Verification method called `VerifyMultipleSignatures` , which can quickly verify multiple signatures
securely. It also adds in a new Singature Set type which will be needed when batch verifying blocks.
Part of #6469 
> Add New Secure Batch Signature Verification Method

- beacon-chain/sync/BUILD.bazel
- beacon-chain/sync/initial-sync/BUILD.bazel
- beacon-chain/sync/initial-sync/blocks_fetcher.go
- beacon-chain/sync/rpc.go
- beacon-chain/sync/rpc_beacon_blocks_by_root.go
- beacon-chain/sync/rpc_goodbye.go
- beacon-chain/sync/rpc_metadata.go
- beacon-chain/sync/rpc_ping.go
- beacon-chain/sync/rpc_status.go
Logging Improvements
Only log errors which are of non stream resets.
Fixes #
> Add in Better Logging for Requests

- beacon-chain/state/stategen/service.go
- beacon-chain/state/stategen/service_test.go
Bug Fix
Saves archived state when resuming state gen service.
N.A
> Save Archived State

- slasher/detection/service.go
- slasher/rpc/service.go
Feature
Returns the current status of the slashing service. returns nil is slasher is ready
Fixes #6433
> Slasher readiness status response

- beacon-chain/state/stateutil/attestations.go
Other
This method was unused, no tests either!
N/A - cleanup
> Remove unused EpochAttestationsRoot method

- beacon-chain/p2p/encoder/ssz.go
> Other / audit
Close out buf writer in the event of an error
Part of #6337 
> Close buf writer in event of an error

- beacon-chain/sync/metrics.go
- beacon-chain/sync/subscriber.go
- beacon-chain/sync/subscriber_test.go
Bug Fix
Handle Static subnets appropriately by registering with the correct topic and periodically checking if there are enough peers
subscribed to all the appropriate topics.
Fixes #6521 #6447
N.A
> Fix Static Subnets

- shared/roughtime/BUILD.bazel
- shared/roughtime/roughtime.go
Feature
We believe there may be some issues with roughtime offsets, adding a metric to track the offsets over time.
Part of investigation for #6544 
> Add roughtime offset histogram metric, log on large offsets

- shared/roughtime/roughtime.go
Feature
This PR verifies the results returned from roughtime servers before accepting the offset.
Part of mitigation of #6544.
I am not sure that this helps with #6544, but it seems like the appropriate thing to do to mitigate potential MitM attacks from NTP servers.
> Verify roughtime results before accepting time offset

- beacon-chain/p2p/dial_relay_node.go
- beacon-chain/p2p/service.go
- beacon-chain/p2p/watch_peers.go
Audit Best Practices
Part of #6337 
> Specify Dial Timeouts

- beacon-chain/p2p/encoder/varint.go
- beacon-chain/p2p/encoder/varint_test.go
> QSP18: Add Varint Header Validation

- beacon-chain/p2p/BUILD.bazel
- beacon-chain/p2p/addr_factory_test.go
- beacon-chain/p2p/broadcaster_test.go
- beacon-chain/p2p/connection_gater_test.go
- beacon-chain/p2p/dial_relay_node_test.go
- beacon-chain/p2p/discovery_test.go
- beacon-chain/p2p/encoder/BUILD.bazel
- beacon-chain/p2p/encoder/snappy_test.go
- beacon-chain/p2p/encoder/ssz_test.go
- beacon-chain/p2p/encoder/varint_test.go
- beacon-chain/p2p/fork_test.go
- beacon-chain/p2p/options_test.go
- beacon-chain/p2p/parameter_test.go
- beacon-chain/p2p/peers/BUILD.bazel
- beacon-chain/p2p/peers/status_test.go
- beacon-chain/p2p/rpc_topic_mappings_test.go
- beacon-chain/p2p/sender_test.go
- beacon-chain/p2p/service_test.go
- beacon-chain/p2p/subnets_test.go
- applies `testutil/assert` and `testutil/require` to `p2p` tests
Part of #6590
- This PR reduces line count in `p2p` tests (w/o touching semantics) by almost 500 lines
> Applies assertion funcs to p2p tests

- beacon-chain/operations/attestations/BUILD.bazel
- beacon-chain/operations/attestations/kv/BUILD.bazel
- beacon-chain/operations/attestations/kv/aggregated_test.go
- beacon-chain/operations/attestations/kv/block_test.go
- beacon-chain/operations/attestations/kv/forkchoice_test.go
- beacon-chain/operations/attestations/kv/unaggregated_test.go
- beacon-chain/operations/attestations/prepare_forkchoice_test.go
- beacon-chain/operations/attestations/prune_expired_test.go
- beacon-chain/operations/attestations/service_test.go
- beacon-chain/operations/slashings/BUILD.bazel
- beacon-chain/operations/slashings/service_attester_test.go
- beacon-chain/operations/slashings/service_proposer_test.go
- beacon-chain/operations/voluntaryexits/BUILD.bazel
- beacon-chain/operations/voluntaryexits/service_test.go
- applies `testutil/assert` and `testutil/require` to `operation` tests
Part of #6590
> Applies assertion funcs to operation tests

- beacon-chain/core/epoch/precompute/reward_penalty.go
- beacon-chain/core/epoch/precompute/reward_penalty_test.go
Bug fix
This fixes a potential panic with an invalid state.
N/A
Found from fuzzing empty state transitions on randomized states.
> Check for array out of bounds when calculating proposer delta

- beacon-chain/state/BUILD.bazel
- beacon-chain/state/field_trie_test.go
- beacon-chain/state/getters_test.go
- beacon-chain/state/references_test.go
- beacon-chain/state/state_trie_test.go
- beacon-chain/state/stategen/BUILD.bazel
- beacon-chain/state/stategen/cold_test.go
- beacon-chain/state/stategen/epoch_boundary_state_cache_test.go
- beacon-chain/state/stategen/getter_test.go
- beacon-chain/state/stategen/hot_test.go
- beacon-chain/state/stategen/migrate_test.go
- beacon-chain/state/stategen/replay_test.go
- beacon-chain/state/stategen/service_test.go
- beacon-chain/state/stategen/setter_test.go
- beacon-chain/state/stateutil/BUILD.bazel
- beacon-chain/state/stateutil/attestations_test.go
- beacon-chain/state/stateutil/benchmark_test.go
- beacon-chain/state/stateutil/blocks_test.go
- beacon-chain/state/stateutil/state_root_test.go
- beacon-chain/state/stateutil/trie_helpers_test.go
- beacon-chain/state/types_test.go
- applies `testutil/assert` and `testutil/require` to `state` tests
Part of #6590
> Applies assertion funcs to state tests

- shared/cmd/BUILD.bazel
- shared/cmd/config_test.go
- shared/cmd/customflags_test.go
- shared/cmd/helpers_test.go
- shared/depositutil/BUILD.bazel
- shared/depositutil/deposit_test.go
- shared/featureconfig/BUILD.bazel
- shared/featureconfig/config_test.go
- shared/featureconfig/flags_test.go
- shared/hashutil/BUILD.bazel
- shared/hashutil/hash_test.go
- shared/hashutil/merkleRoot_test.go
- shared/htrutils/BUILD.bazel
- shared/htrutils/hashers_test.go
- shared/htrutils/helpers_test.go
- shared/htrutils/htrutils_test.go
- shared/htrutils/merkleize_test.go
- shared/interop/BUILD.bazel
- shared/interop/generate_genesis_state_test.go
- shared/interop/generate_keys_test.go
- shared/iputils/BUILD.bazel
- shared/iputils/external_ip_test.go
- applies `testutil/assert` and `testutil/require` to part of `shared` tests
Part of #6590
> Applies assertion funcs to shared tests

- beacon-chain/rpc/BUILD.bazel
- beacon-chain/rpc/beacon/BUILD.bazel
- beacon-chain/rpc/beacon/assignments_test.go
- beacon-chain/rpc/beacon/attestations_test.go
- beacon-chain/rpc/beacon/blocks_test.go
- beacon-chain/rpc/beacon/committees_test.go
- beacon-chain/rpc/beacon/config_test.go
- beacon-chain/rpc/beacon/slashings_test.go
- beacon-chain/rpc/beacon/validators_stream_test.go
- beacon-chain/rpc/beacon/validators_test.go
- beacon-chain/rpc/debug/BUILD.bazel
- beacon-chain/rpc/debug/block_test.go
- beacon-chain/rpc/debug/forkchoice_test.go
- beacon-chain/rpc/debug/p2p_test.go
- beacon-chain/rpc/debug/state_test.go
- beacon-chain/rpc/node/BUILD.bazel
- beacon-chain/rpc/node/server_test.go
- beacon-chain/rpc/service_test.go
- beacon-chain/rpc/validator/BUILD.bazel
- beacon-chain/rpc/validator/aggregator_test.go
- beacon-chain/rpc/validator/assignments_test.go
- beacon-chain/rpc/validator/attester_test.go
- beacon-chain/rpc/validator/exit_test.go
- beacon-chain/rpc/validator/proposer_test.go
- beacon-chain/rpc/validator/server_test.go
- beacon-chain/rpc/validator/status_test.go
- applies `testutil/assert` and `testutil/require` to `rpc` tests
Part of #6590
> Applies assertion funcs to rpc tests

- validator/accounts/v1/BUILD.bazel
- validator/accounts/v1/account_test.go
- validator/accounts/v2/list_test.go
- validator/accounts/v2/new_test.go
- validator/accounts/v2/wallet_test.go
- applies `testutil/assert` and `testutil/require` to part of `validator/accounts` tests
Part of #6590
> Applies assertion funcs to validator/accounts tests

- beacon-chain/blockchain/receive_block.go
- beacon-chain/blockchain/receive_block_test.go
> Bug fix
Make sure we update and save head before sending processed block notification via feed. There's implication that down stream RPC end points use processed block feed to respond fork choice related info. Hence it's important to run fork choice first before we feed
Fixes #6680
> Update head before send feed

- shared/featureconfig/config.go
- shared/featureconfig/flags.go
- shared/params/BUILD.bazel
- shared/params/testnet_medalla_config.go
This adds the medalla testnet configuration.
Details obtained from https://gist.github.com/q9f/941b2621214d05ef8759abde30e4f9ef
> Add medalla testnet configuration.

- beacon-chain/blockchain/process_attestation.go
- beacon-chain/blockchain/process_block.go
Part of #6716 
Update pseudocode comments to reflect the latest changes. There's nothing to change in the code
References:
ethereum/eth2.0-specs#1884
ethereum/eth2.0-specs#1880
ethereum/eth2.0-specs#1886
> Update on block/attestation comments

- beacon-chain/state/field_trie.go
-[x] Preallocates memory before appending to slices so as to prevent unnecessary copies.
Fixes #
> Preallocate Memory for Slices

- WORKSPACE
Reverts prysmaticlabs/prysm#6712
> Revert "Update rules go to v0.22.9"

- validator/accounts/v2/accounts_create.go
- validator/accounts/v2/prompt.go
> Fix Accounts Creation Error

- deps.bzl
- go.mod
- go.sum
Reverts prysmaticlabs/prysm#6761 as it is blocking #6769 from merging, which is critical
> Revert "Update Ethereumapis"

- shared/featureconfig/flags.go
Other
Long running e2e tests are currently failing.
See: #6786
> Disable --enable-eth1-data-majority-vote in e2e

- validator/accounts/v2/prompt.go
Bug fix
%s was transforming bytes to ascii so it would usually just produce garbage.
Fixes #6801
> Fix public key formatting

- beacon-chain/blockchain/service.go
- beacon-chain/blockchain/service_test.go
- beacon-chain/db/kv/checkpoint.go
- beacon-chain/db/kv/checkpoint_test.go
Bug Fix
Retrieve a zero hash instead of the genesis block root.
Fixes #
> Fix Justified and Finalized Retrieval in Genesis

- beacon-chain/state/BUILD.bazel
- slasher/rpc/BUILD.bazel
- slasher/rpc/server.go
- slasher/rpc/server_test.go
Bug fix
Race condition makes slasher protection miss slashing conditions
this pr aim to add lock to avoid this issue
Fixes #6868
> Slasher protection race condition fix 

- beacon-chain/sync/error.go
- beacon-chain/sync/metrics.go
- beacon-chain/sync/pending_attestations_queue.go
- beacon-chain/sync/pending_blocks_queue.go
- beacon-chain/sync/rate_limiter.go
- beacon-chain/sync/rpc.go
- beacon-chain/sync/rpc_beacon_blocks_by_range.go
- beacon-chain/sync/rpc_beacon_blocks_by_root.go
- beacon-chain/sync/rpc_metadata.go
- beacon-chain/sync/rpc_ping.go
- beacon-chain/sync/rpc_status.go
- beacon-chain/sync/subscriber.go
- beacon-chain/sync/validate_aggregate_proof.go
- beacon-chain/sync/validate_beacon_blocks.go
- beacon-chain/sync/validate_proposer_slashing.go
- beacon-chain/sync/validate_voluntary_exit.go
- endtoend/components/beacon_node.go
Change error logs to debug logs in most of our sync subscribers and handlers.
Most average users will not be able to interpret any of this errors correctly and this runs
the risk of confusing them. So these errors are pushed to debug for now.
Fixes #
> Change Sync Error Logs To Debug Logs

- README.md
Removing fuzzit badage (last run was early July) as we switched to cluster fuzz
> Remove Fuzzit badge

- beacon-chain/p2p/BUILD.bazel
- beacon-chain/p2p/discovery.go
- beacon-chain/p2p/service_test.go
- beacon-chain/p2p/subnets.go
Reverts prysmaticlabs/prysm#6848
> Revert "Use Less Intensive Search"

- shared/prometheus/service.go
- validator/client/validator.go
Code cleanup
Applies fixes discovered by DeepSource.
https://deepsource.io/gh/chsatyap/prysm/issue/SCC-S1025/occurrences
https://deepsource.io/gh/chsatyap/prysm/issue/SCC-SA4004/occurrences/
Part of #6747
I skipped any issues related to accounts v2.
> Manual code cleanup

- validator/accounts/v2/BUILD.bazel
- validator/accounts/v2/wallet_recover.go
- validator/keymanager/v2/derived/derived.go
> Feature
We previously allowed for only english mnemonic recovery, but bip39 includes several other languages we should also support. This will unblock several users.
> Allow for Different Language Mnemonic Recovery

- tools/keystores/main.go
- validator/keymanager/v2/direct/import.go
> Bug fix
If a keystore.json file we are importing into Prysm does not contain a `Pubkey` field in its JSON, we should attempt to decrypt and use the public key derived from the private key we just decrypted. This issue is causing some keystores imported from lighthouse to fail in Prysm.
For example, for this keystore.json file
```
{"name": "keystore", "uuid": "ed98ea7f-e7ef-4326-a4ca-54d006bc747b", "crypto": {"kdf": {"params": {"n": 32768, "p": 1, "r": 8, "salt": "1fa4ea621659b11f5aca0966ed3273a759d754b5f4b529300356ad04067c012b", "dklen": 32}, "message": "", "function": "scrypt"}, "cipher": {"params": {"iv": "fdd8e56744b4883a5d260446eeddf68c"}, "message": "a8969e1b0e60dc0d45a0abdb1f3c9fe97834273f67510f0a33dc0c7dfde98 …
```
> Fix Pubkey Not Specified Issues in External Keystore Imports

- deps.bzl
- go.mod
- go.sum
Resolves #6833, which was a problem in the underlying code of the prometheus client. Online suggestions point towards updating the library as a resolution.
> Update Prometheus Client

- go.mod
- go.sum
- validator/accounts/v2/BUILD.bazel
- validator/accounts/v2/wallet.go
> Bug fix
We should be using standardized file permissions using our ioconfig everywhere. This PR fixes some permissions issues users are seeing with accounts files.
Fixes #6863
> Standardize File Permissions in Accounts-V2

- beacon-chain/operations/attestations/kv/unaggregated_test.go
Other/Fix Tests
- In #6993 some test cases were commented out, this PR makes sure that those are uncommented and passing.
N/A
> Uncomments tests in kv/unaggregated_test

- shared/featureconfig/config.go
> Initialize Config Correctly

- beacon-chain/blockchain/receive_block.go
- beacon-chain/p2p/peers/status.go
- beacon-chain/p2p/peers/status_test.go
- beacon-chain/sync/initial-sync/blocks_fetcher.go
- beacon-chain/sync/initial-sync/round_robin.go
- beacon-chain/sync/initial-sync/round_robin_test.go
> Fix 2nd Stage of Sync

- shared/featureconfig/config_test.go
>
> Test
`TestInitFeatureConfig` did not reset config and poisoned rest of the tests 
Fixes #
> Featureflag test: reset init

- beacon-chain/sync/subscriber.go
Other
Fixes #7000
Fixes #6449
This wasn't properly ignored before since the errors are not equal.
> Ignore subscription cancelled warning

- beacon-chain/blockchain/process_block_helpers.go
Bug fix
There have been some issues where a context deadline is reached when migrating to cold. This could make it so that the finalized checkpoint is not updated in the database but the blocks were saved.
> Save finalized checkpoint before migrate to cold

- slasher/beaconclient/receivers.go
- slasher/db/kv/spanner_new.go
- slasher/flags/flags.go
- slasher/rpc/server.go
Bug fix
this pr fixes:
- reconnect open files issue
- add log for rpc server calls
- sets spans-cache-size to 1500 by default
- remove traces to improve performance
> Slasher improvements

- beacon-chain/blockchain/log.go
> Feature
Add "current epoch in slot" in log. H/t to @djrtwo for the suggestion. Very useful one.
Fixes # N/A
> Add "slotInEpoch" to log

- beacon-chain/core/epoch/precompute/spectest/rewards_penalties_test.go
- beacon-chain/state/stategen/replay_test.go
To unblock #7066 and address https://deepsource.io/gh/rkapka/prysm/issue/SCC-SA4000/occurrences/
> Fix identical expressions

- beacon-chain/interop-cold-start/service.go
> Fix For Non Existent Validators In Interop

- beacon-chain/sync/error.go
- beacon-chain/sync/rpc_beacon_blocks_by_range.go
- beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
- beacon-chain/sync/service.go
> Validate Beacon Block By Range Requests Better

- shared/params/config.go
Other/Fix Comments
- When reviewing specs and comparing them to code we have, noticed that there're number of minor issues in `params/config.go` comments. This PR fixes those issues.
N/A
> Fixes comments in params/config

- proto/validator/accounts/v2/web_api.proto
- validator/keymanager/v2/derived/derived.go
- validator/keymanager/v2/derived/derived_test.go
- validator/keymanager/v2/direct/BUILD.bazel
- validator/keymanager/v2/direct/direct.go
- validator/keymanager/v2/direct/direct_test.go
- validator/rpc/BUILD.bazel
- validator/rpc/accounts.go
- validator/rpc/accounts_test.go
- validator/rpc/auth.go
- validator/rpc/gateway/gateway.go
- validator/rpc/server.go
This PR implements the create and list accounts RPC methods for the validator client with tests
> Implement Create and List Accounts Validator RPC

- beacon-chain/blockchain/process_attestation.go
- beacon-chain/blockchain/process_block_helpers.go
- beacon-chain/blockchain/service.go
- beacon-chain/core/helpers/slot_epoch.go
- beacon-chain/core/helpers/slot_epoch_test.go
- beacon-chain/node/node.go
- beacon-chain/rpc/beacon/validators_stream.go
- beacon-chain/rpc/validator/status.go
- beacon-chain/sync/initial-sync/service.go
- shared/params/config.go
- shared/params/testnet_medalla_config.go
Revert #6966
See #7173 for more details
> Revert 6966

- beacon-chain/core/blocks/block_operations_fuzz_test.go
- beacon-chain/core/blocks/header.go
- beacon-chain/core/blocks/randao.go
- beacon-chain/core/blocks/spectest/block_header_test.go
- beacon-chain/core/state/transition.go
- fuzz/block_header_fuzz.go
> Clean up
Used pipelines for `ProcessBlockNoVerifyAttSigs` and `ProcessBlockNoVerifyAttSigs`. No functional changes, just refactoring for clarity and readability 
Tested run time with 1k validators
> Pipelines for `ProcessBlockNoVerifyAttSigs` and `ProcessBlockStateRoot`

- beacon-chain/core/helpers/slot_epoch.go
- beacon-chain/core/helpers/slot_epoch_test.go
- shared/params/config.go
- shared/params/mainnet_config.go
> Feature
Implement weak subjectivity check point epoch helper outlined:
https://notes.ethereum.org/@adiasg/weak-subjectvity-eth2#Updating-Weak-Subjectivity-Checkpoint-States
> Implement helper method `WeakSubjectivityCheckptEpoch`

- beacon-chain/core/blocks/attestation.go
- shared/fileutil/BUILD.bazel
- shared/fileutil/fileutil.go
- shared/fileutil/fileutil_test.go
- validator/node/node.go
Bug fix
rename (move) fails on some filesystems. this pr changes to use copy instead
> Fix rename issue

- shared/featureconfig/config.go
- shared/featureconfig/flags.go
Other/Flag Inversion
`enable-finalized-deposits-cache` -> `disable-finalized-deposits-cache`
Part of #6518
N/A
> Invert enable-finalized-deposits-cache

- beacon-chain/core/blocks/exit.go
Other
Follow-up to #7207. I forgot to change the comment.
N/A
N/A
> fix exit comment

- shared/logutil/stream.go
This PR fixes websocket connection handling for log subscriptions by properly closing connections if there is a failure and also defer closing channels and the subscription properly
> Websocket Connection Fixes

- shared/logutil/BUILD.bazel
- shared/logutil/stream.go
- shared/logutil/stream_test.go
- shared/mock/beacon_service_mock.go
Feature
This feature makes for a better experience when joining the websocket stream.
N/A
Needs tests still.
> Streaming logs: add backfill of messages for new connections"

- shared/bls/blst/BUILD.bazel
- shared/bls/blst/signature_test.go
> Fix Blst Signature Copy Test

- WORKSPACE
- beacon-chain/core/epoch/precompute/spectest/rewards_penalties_test.go
- proto/testing/BUILD.bazel
- proto/testing/ssz_static_mainnet_test.go
Update spec tests to v0.12.3
Part of #7274
> Update spec tests to v0.12.3

- tools/bootnode/BUILD.bazel
- tools/bootnode/bootnode.go
> Update Bootnode With New Flags

- deps.bzl
- go.mod
- go.sum
Updates our referenced `blst` update to `cd0847a7580b22677e9069f671a79f0d874442b3` and 
potentially solves #7312 .
N.A
> Update BLST to Latest Commit

- shared/params/testnet_spadina_config.go
> Add Spadina Bootnodes

- validator/accounts/v2/accounts_exit.go
Bug fix
The URL pointing to documentation about voluntary exit was incorrect.
N/A
N/A
> Fix URL to voluntary exit documentation

- shared/featureconfig/config.go
- shared/featureconfig/flags.go
Bug fix
in order to support protection signature verification use the same fork version for signature validation
no issue
reported in discord
> Add slasher support for different testnets

- validator/flags/flags.go
> Other
- Removes unused flags from `validator/flags.go`; those flags are not used anywhere (just defined in that file, and remain unused).
N/A
> Removes unused validator flags

- validator/rpc/wallet.go
- validator/rpc/wallet_test.go
> Feature
Implements the ImportAccounts RPC method in the validator RPC server for use with the web interface
> Import Accounts RPC Implementation

- beacon-chain/node/node.go
> add display contract

- beacon-chain/cache/committee.go
Bug Fix
` -build` is not valid go build syntax, this PR changes it so that we use the appropriate syntax.
cc @pventuzelo
N.A
> Use Valid LibFuzzer Go Build Tags

- beacon-chain/p2p/pubsub.go
- beacon-chain/p2p/pubsub_test.go
> Use Full Hash for Message ID

- nogo_config.json
- slasher/db/testing/BUILD.bazel
- slasher/db/testing/setup_db.go
- slasher/detection/testing/BUILD.bazel
- slasher/detection/testing/utils.go
> Other / QA
- enables `cryptorand` static code analyzer for `slasher/*` code
- fixes issues found
N/A
> Enable cryptorand analyzer in slasher

- shared/params/testnet_zinken_config.go
Config Addition
Adds in Prysm's Zinken Bootnode
Fixes #7390 
> Add Zinken Bootnode

- beacon-chain/main.go
- go.mod
- slasher/main.go
- validator/main.go
> Other
- #7429 has been accepted w/o normal checks, so we need to re-run `go fmt` and `go mod tidy`. This PR does this.
N/A
> Apply go fmt + tidy: issue introduced in #7429

- endtoend/README.md
> Fix E2E Readme to Include Bazel Define Flag

- beacon-chain/BUILD.bazel
- beacon-chain/main.go
- deps.bzl
- go.mod
- go.sum
- shared/cmd/flags.go
- slasher/BUILD.bazel
- slasher/main.go
- validator/BUILD.bazel
- validator/main.go
Other
See #7454
Fixes #7454
Reopens #7353
> Revert PR #7429 to fix building on windows

- .buildkite-bazelrc
- beacon-chain/powchain/block_reader_test.go
- beacon-chain/powchain/log_processing.go
- beacon-chain/powchain/service.go
> Eth1 Handling Cleanup

- WORKSPACE
Other
Updates to include this release https://github.com/prysmaticlabs/prysm-web-ui/releases/tag/0.0.1-alpha
N/A
> Update validator UI to 0.0.1-alpha

- shared/sliceutil/slice.go
There's a few conditions in the form of ​(X-Y) == 0​. The conditions could be written more simply as ​X == Y​
> Simplify comparisons ​(X-Y) == 0

- beacon-chain/core/blocks/attester_slashing_test.go
- beacon-chain/node/helper.go
- beacon-chain/p2p/service.go
- beacon-chain/p2p/testing/fuzz_p2p.go
- beacon-chain/powchain/BUILD.bazel
- beacon-chain/powchain/log_processing_test.go
- beacon-chain/powchain/powchain_test.go
- beacon-chain/powchain/service.go
- beacon-chain/rpc/service_test.go
- beacon-chain/rpc/validator/proposer_test.go
- beacon-chain/sync/initial-sync/blocks_fetcher_test.go
- slasher/rpc/server_test.go
- slasher/rpc/service_test.go
- validator/accounts/v2/wallet/wallet.go
- validator/db/kv/new_proposal_history.go
- validator/keymanager/v1/direct_unencrypted.go
- validator/keymanager/v1/remote.go
- validator/rpc/accounts.go
> Other
- Fixes reported anti-pattern ([see DeepSource report](https://deepsource.io/gh/prysmaticlabs/prysm/issues/?category=antipattern)).
N/A
- Cases of single case channel selects have been resolved by adding extra case allowing to unblock on context close.
> Fix reported anti patterns

- beacon-chain/blockchain/head.go
- beacon-chain/blockchain/head_test.go
A few users reported when syncing to head, during the processing of first batch block, fork choice complains missing justified root. This PR ensures that in the event of missing justified root, it gets refilled
> Add justified block insertion to forkchoice when missed

- shared/tos/tos.go
- shared/tos/tos_test.go
Fixes paths for windows in #7527
> Accept ToS: fix paths for windows

- shared/featureconfig/config.go
- shared/featureconfig/flags.go
- validator/client/attest_protect.go
- validator/client/attest_protect_test.go
- validator/client/attest_test.go
- validator/client/propose_protect.go
- validator/client/propose_protect_test.go
- validator/client/propose_test.go
- validator/client/runner.go
Deprecating Flags
--[x] Removes local protection flag as this has been the default for a while.
Part of #7509 
> Remove Local Protection Flag

- validator/accounts/wallet/wallet.go
> Bug fix
fix system specific err msg
Fixes #7499
> Fix import cannot find the file on windows

- shared/featureconfig/flags.go
> Remove checkpoint cache flag from --dev

- beacon-chain/blockchain/service.go
> Fix Unsafe Sync Flag

- shared/featureconfig/config.go
- shared/featureconfig/deprecated_flags.go
- shared/featureconfig/flags.go
Other/Flag Inversion
`enable-pruning-deposit-proofs` -> `disable-pruning-deposit-proofs`
Part of #7504
N/A
> Invert enable-pruning-deposit-proofs

- beacon-chain/blockchain/BUILD.bazel
- beacon-chain/blockchain/metrics.go
- beacon-chain/blockchain/metrics_test.go
- beacon-chain/blockchain/process_block.go
- beacon-chain/blockchain/process_block_test.go
- beacon-chain/core/epoch/precompute/attestation.go
After chatting with @potuz. This PR updates participation metric to use `head` view instead of `last_processed` view. Since metrics are the only changes and this code path has been tested. I also verified run time and metrics were correctly representing head view
> Update participation metrics

- shared/cmd/helpers.go
- shared/cmd/helpers_test.go
Bug Fix
In #7557, we expand filepaths in the event we do not provide endpoints with a standard url scheme. However doing this leads to invalid endpoint paths being set when the webprovider flag isn't set at all.
This PR adds a check for it.
N.A
> Fix Powchain Error In Startup

- beacon-chain/powchain/service.go
- beacon-chain/powchain/service_test.go
Bug Fix
no suitable state is found.
N.A
> Initialize State Correctly In Powchain

- beacon-chain/blockchain/receive_attestation.go
Other / cleanup
This method was not used or tested. Yikes!
> Remove unused and untested IsValidAttestation

- beacon-chain/blockchain/receive_attestation.go
- beacon-chain/blockchain/receive_attestation_test.go
Reverts prysmaticlabs/prysm#7663
> Revert "Remove redundant checks in `processAttestation`"

- beacon-chain/blockchain/receive_attestation.go
- beacon-chain/blockchain/receive_attestation_test.go
- beacon-chain/core/helpers/attestation.go
- beacon-chain/core/helpers/attestation_test.go
- beacon-chain/sync/validate_aggregate_proof.go
- beacon-chain/sync/validate_aggregate_proof_test.go
- beacon-chain/sync/validate_beacon_attestation.go
Bug fix
As title describes. We should not propagate attestations that will then fail processing.
None reported
Also see https://github.com/ethereum/eth2.0-specs/pull/2115
> Check attestation target checkpoint epoch matches attestation slot

- beacon-chain/blockchain/process_attestation_helpers.go
- beacon-chain/blockchain/process_attestation_test.go
- beacon-chain/cache/checkpoint_state.go
- beacon-chain/cache/checkpoint_state_test.go
Reverts prysmaticlabs/prysm#7659 in favour of #7669 .
> Revert "Add In Progress Checker For Checkpoint Cache"

- beacon-chain/blockchain/process_attestation_helpers.go
- beacon-chain/blockchain/process_attestation_test.go
- beacon-chain/cache/checkpoint_state.go
- beacon-chain/cache/checkpoint_state_test.go
Reverts prysmaticlabs/prysm#7672
> Revert "Revert "Add In Progress Checker For Checkpoint Cache""

- beacon-chain/core/validators/validator.go
> Exit Validators More Efficiently
