testing/endtoend/evaluators/beaconapi_evaluators/util.go

Other
adds response body to logging error of not successful statuses

E2E: improve beacon api logging

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/chain_info_test.go
beacon-chain/blockchain/error.go
beacon-chain/rpc/eth/helpers/sync.go

Bug Fix
In the event we have the referenced block in our database but not its summary, we fallback and correctly recover it.
Fixes #12208 

Recover State Summary Correctly

---

beacon-chain/node/node.go
beacon-chain/p2p/config.go
beacon-chain/p2p/options_test.go
beacon-chain/p2p/utils.go
cmd/beacon-chain/main.go
cmd/beacon-chain/usage.go
cmd/flags.go

Feature
In the event a node operator wants to keep their peer id fixed, they can run prysm with this flag. This flag will persist 
any generated network key to disk. In the event a peer restarts their node, they will have the same peer id as in their previous run. As a added note, `p2p-priv-key` will take precedence to the default key path in the event it is used in conjunction with the static peer id flag.
N.A

Enable Static Peer ID

---

beacon-chain/sync/rpc_send_request.go
cmd/prysmctl/p2p/BUILD.bazel
cmd/prysmctl/p2p/p2p.go
cmd/prysmctl/p2p/request_blobs.go

This PR extends `prysmctl` utility's p2p functionality to request blobs by range using p2p's rpc request response protocol
As part of testing, the PR also implements barebone for `SendBlobsByRangeRequest`. We verified blobs by range request and response working through the utility

Prysmctl request blobs by ranges

---

beacon-chain/node/config.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
cmd/beacon-chain/flags/base.go
config/params/config.go
config/params/mainnet_config.go

This pull request adds a new flag to `local-block-value-boost` that allows the local block value multiplied by the boost value. The resulting value will be used if higher than the original builder's bid value. 
(i.e `builder_bid_value * 100 > local_block_value * (local-block-value-boost + 100`)
By default, the boost value is set to 0. This means that the current behavior remains unchanged. However, if preferred, the value of the boost can be adjusted to shift prioritization to the local block
The proposed change is designed to provide greater flexibility in censorship resistance defense, allowing for more dynamic and potentially more competitive bidding between local builders and mev builders

Add flag to boost local block value

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/core/transition/trailing_slot_state_cache.go
beacon-chain/core/transition/trailing_slot_state_cache_test.go
beacon-chain/core/transition/transition.go

This PR refactors the next slot cache to keep track of two alternative states. This makes the cache safe under skipped slots and 1-slot reorgs, including across epoch boundaries. Design is in https://www.notion.so/arbitrum/Next-Slot-Cache-2-0-301e3788c1b248e6a587bd3505c4034a
This also fixes some bugs making the cache not thread safe  (by copying the root slice instead of keeping the slice parameter in the cache).

refactor next slot cache

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go

In the event where setting `builderPayload` to block's execution field fails, we can recover and use `localPayload` instead of failing block production. To set `localPayload`, we need to unblind the block

Default to local payload should set block to not blind

---

beacon-chain/core/transition/trailing_slot_state_cache.go
beacon-chain/core/transition/trailing_slot_state_cache_test.go
beacon-chain/core/transition/transition.go

Bug Fix
In E2E a few of our runs were constantly failing with `could not process slots: expected state.slot 289 < slot 288` . After an investigation it was determined that #12233 added the ability for our cache to store different states with the same parent root. To allow the next slot cache to return the correctly desired state to the caller, we added in a `wantedSlot` parameter which should allow states with the desired slots to be returned. 
A simple regression test was also added for this.
N.A

Fix Next State Mismatch

---

beacon-chain/state/genesis/BUILD.bazel
beacon-chain/state/genesis/genesis.go
beacon-chain/state/genesis/genesis_mainnet.go
cmd/prysmctl/BUILD.bazel

Feature
This is one small step to reducing the binary size of prysmctl. We'll get much bigger benefits from excluding validator web ui data, but since those are generated files it will take some more work to figure out how to accomplish that through bazel.

build tag to exclude mainnet genesis from prysmctl

---

beacon-chain/rpc/prysm/v1alpha1/beacon/blocks.go
beacon-chain/rpc/prysm/v1alpha1/beacon/blocks_test.go

Bug Fix
Fixes a deadlock in `StreamChainHead` which happens when we are syncing due to how forkchoice locks were refactored.
We ignore blocks being streamed in when syncing so as to not acquire the forkchoice read locks.
N.A

Fix Deadlock in StreamChainHead

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/execution_engine_test.go
beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/head.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/core/feed/state/events.go
beacon-chain/rpc/eth/events/events.go
config/features/config.go
config/features/flags.go

Adds a `--prepare-all-payloads` flag so that builders/relayers can pretend to be proposing every slot

Add prepare-all-payloads flag

---

beacon-chain/builder/service.go
beacon-chain/builder/service_test.go

Bug Fix
In the event our builder client is not initialized, we return an error rather than trying to access the builder client and triggering a panic. A regression test has been added in. 
Fixes #12275 

Fix Panic In Builder Service

---

beacon-chain/rpc/eth/validator/validator_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

Bug Fix
This checks that the builder is configured on the beacon node before we send out requests via the builder client. This also modifies the function's unit test to check for this configuration.
N.A

Check that Builder Is Configured

---

cmd/prysmctl/testnet/generate_genesis.go
runtime/interop/genesis.go

Feature
Better support for modifying existing genesis.json files in `prysmctl testnet generate-genesis` to support a smoother ux when using github.com/rauljordan/eth-pos-devnet.  https://github.com/rauljordan/eth-pos-devnet/pull/16 uses this new workflow.

support modifying genesis.json for capella

---

deps.bzl
go.mod
go.sum
monitoring/journald/BUILD.bazel
monitoring/journald/journald_linux.go
monitoring/journald/journalhook.go
monitoring/journald/journalhook_test.go

Dependency Fix
This vendors the broken dependency into prysm so that we no longer will need to import it or any
of its forks.
Supersedes #12292 

Fix Broken Dependency

---

beacon-chain/sync/BUILD.bazel
beacon-chain/sync/validate_attester_slashing.go
beacon-chain/sync/validate_attester_slashing_test.go

Bug Fix
Fixes a missing check for slashable validators in our gossip pipeline. This adds in the check and also adds in
a respective regression check for it.
N.A

Fix Attester Slashing Validation In Gossip

---

consensus-types/blocks/execution.go

Set the payload header in the right order as in the consensus specs.

set payload header in right order

---

beacon-chain/rpc/eth/validator/validator.go
beacon-chain/rpc/eth/validator/validator_test.go

Other
Our current error on producing blinded block is not clear especially when the validator is not registered while using the mev relay. Now it should display an error that reflects this and shows the underlying type used.
Fixes # https://github.com/prysmaticlabs/prysm/issues/12103#issuecomment-1514343838

improve the blinded block error

---

testing/endtoend/components/eth1/transactions.go

E2E Fix
In #12270, we returned errors in our transaction fuzzer if a transaction wasn't able to be successfully completed. However due
to the nature of how the fuzzer constructs transactions, this would always be a possibility. The end result is that our e2e runs started failing much more often. This PR adds in exceptions for them so that we don't need to return errors if a transaction isn't valid.
N.A

Add Exceptions For Transaction Fuzzer

---

beacon-chain/db/kv/state.go

Bug fix
db.View inside GenesisState used to return crtErr which doesn't store any error value and thus db.View doesn't correctly return the error after unmarshalState.

Corrected err return for GenesisState while calling db.View

---

beacon-chain/state/stategen/getter.go

Optimization
The call to `s.finalizedState()` makes a copy of the beacon state. We unnecessarily make two copies: in the condition check and inside the condition statement.

Avoid double state copy in `latestAncestor`

---

api/client/builder/BUILD.bazel
api/client/builder/bid.go
beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/log.go
beacon-chain/core/blocks/BUILD.bazel
beacon-chain/core/blocks/payload.go
beacon-chain/rpc/eth/beacon/BUILD.bazel
beacon-chain/rpc/eth/beacon/blinded_blocks.go
beacon-chain/rpc/eth/beacon/blocks.go
cmd/prysmctl/p2p/BUILD.bazel
cmd/prysmctl/p2p/request_blocks.go
consensus-types/BUILD.bazel
consensus-types/blocks/BUILD.bazel
consensus-types/blocks/execution.go
consensus-types/blocks/execution_test.go
consensus-types/blocks/getters.go
consensus-types/blocks/proto.go
consensus-types/blocks/setters.go
consensus-types/blocks/types.go
consensus-types/payload-attribute/BUILD.bazel
consensus-types/payload-attribute/getters.go
consensus-types/types.go

Cleanup
`ErrNilObjectWrapped`, `ErrUnsupportedGetter` and `ErrNotSupported` all currently live in the `blocks` package, but they are applicable to all consensus types. This PR moves these members out to the top-level `consensus-types` package.

Move some errors to separate `consensus-types` package

---

beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/receive_attestation.go

Other
Adds some additional spans to properly group and analyze data during block production when tracing is enabled.

blockchain: add more spans to analyze block production timing

---

beacon-chain/blockchain/process_block.go

Update next slot cache currently happens after many things.
- forkchoice methods
- setter methods
This PR moves it earlier to the right after update head and only if it's head. There's no reason to wait for this

Move update next slot cache earlier

---

validator/client/attest_test.go
validator/client/key_reload_test.go
validator/client/propose_test.go
validator/client/validator_test.go
validator/client/wait_for_activation_test.go

Bug fix
I started out trying to fix a racy test in the validator code and wound up doing a cleanup pass on how we set up the mock keymanager. Goal is to make test setup more concise and easy to read, get rid of unnecessary boilerplate. Most importantly give tests control over the ordering of the return value from the `FetchValidatingPublicKeys` mock method, since the mock tests are a bit fragile and can break due to the non-deterministic ordering from iterating over the keymap.

Keymanager mock cleanup

---

consensus-types/payload-attribute/getters.go

Post capella updates, PbV2 is usable if there's no schema changes. This is the case for deneb

Fix `PbV2` version check for post capella upgrades

---

validator/client/validator.go
validator/client/validator_test.go

Bug Fix
In #12322 we introduced the ability to filter keys based on the current validator status. However the change introduced a bug which lead to only 1 key being passed into the `MultipleValidatorStatus` request. For an example on how this would happen:
https://go.dev/play/p/1cPEh5fYIvx
The PR copies the key and appends it to the slice along with modifying the unit test so that this particular case can be caught correctly.
N.A

Fix Key Filtering In Validator

---

beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/broadcaster_test.go

Two broadcast methods, namely for attestations and sync committees, can panic a node if we try to broadcast nil objects. Instead, we fail early and return an error. Closes #11926

Do Not Panic on Broadcasting Nil Object

---

math/math_helper.go
math/math_helper_test.go

`WeiToGwei` did not copy input `v` before so it gets mutated and that led to some confusion from the caller
This PR copies the input and adds a unit test

`WeiToGwei` copy input big.int

---

validator/accounts/testing/mock.go
validator/client/iface/validator.go
validator/client/runner.go
validator/client/testutil/mock_validator.go
validator/client/validator.go
validator/client/validator_test.go

Bug fix
Found and fixed by @nisdas 
There is a subtle bug with the filtering check, or actually with MultipleValidatorStatus . But since the check is done at the start of an epoch, before any new block has come in, the state's head slot is at the previous epoch. So 'active' validators are marked as pending and they would be unable to have their registrations submitted to the builder. Caused by this method `assignmentStatus`, it will use the head slot from the current head state ( which is still at the previous epoch)
Code was taken from #12343

fix edgecase when filtering active validators

---

beacon-chain/rpc/eth/beacon/config_test.go
beacon-chain/state/state-native/beacon_state_mainnet.go
beacon-chain/state/state-native/beacon_state_minimal.go
beacon-chain/state/state-native/getters_block_test.go
beacon-chain/state/state-native/getters_checkpoint_test.go
beacon-chain/state/state-native/getters_payload_header.go
beacon-chain/state/state-native/getters_state.go
beacon-chain/state/state-native/getters_test.go
beacon-chain/state/state-native/getters_validator_test.go
beacon-chain/state/state-native/getters_withdrawal_test.go
beacon-chain/state/state-native/hasher.go
beacon-chain/state/state-native/references_test.go
beacon-chain/state/state-native/setters_payload_header.go
beacon-chain/state/state-native/setters_withdrawal_test.go
beacon-chain/state/state-native/spec_parameters.go
beacon-chain/state/state-native/state_fuzz_test.go
beacon-chain/state/state-native/state_test.go
beacon-chain/state/state-native/state_trie.go
beacon-chain/state/state-native/state_trie_test.go
beacon-chain/state/state-native/types/types.go
beacon-chain/state/stategen/replay.go
config/params/config.go
config/params/loader_test.go
config/params/mainnet_config.go
config/params/minimal_config.go
config/params/testnet_prater_config.go
testing/spectest/shared/deneb/ssz_static/BUILD.bazel
testing/spectest/shared/deneb/ssz_static/ssz_static.go
testing/util/BUILD.bazel
testing/util/deneb_state.go

This PR adds deneb beacon state native type. It also uses native type hash tree root for spec test

Add Deneb state

---

beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/pending_attestations_queue.go
beacon-chain/sync/service.go

Bug fix
The `sync` and `initial-sync` services directly call methods on the clock, and in the case of `sync` these calls may not always be blocked on the `WaitForClock` event, leading to a panic. This PR sets up zero-values for the `*startup.Clock` fields in those services, resulting in behavior similar to the previous startup code and avoiding panics.
n/a

Fix initialization race

---

beacon-chain/node/node.go
beacon-chain/operations/attestations/BUILD.bazel
beacon-chain/operations/attestations/prepare_forkchoice.go
beacon-chain/operations/attestations/service.go
config/features/config.go
config/features/flags.go
time/slots/BUILD.bazel
time/slots/slotticker.go
time/slots/slotticker_test.go
time/slots/slottime.go

This PR adds:
- It adds a `SlotTickerWithIntervals`  that accepts a series of intervals between 0 and 12 seconds (not inclusive) so that the ticker ticks every slot at those offsets. 
- It adds feature flags that allow to customize the precise three spots where we aggregate attestations (they are done three times per slot). 
- Waits for init sync to complete before starting the attestation service

Add a new slot ticker and use it on attestation aggregation

---

beacon-chain/core/helpers/attestation.go

If the attestation time is received before lower bound, it should be too late
If the attestation time is received after upper bound, it should be too early
This was flipped

Metrics: Invert too late and too early att received count

---

beacon-chain/node/node.go

Bug fix
Fixes a panic when the `--slasher` flag is specified on the beacon node.
Fixes #12404

fix broken slasher service init

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

`build-block-parallel` is a great optimization for proposer, it has been tested on testnet over the last 2 weeks. 
The feature was enabled in v4.0.4 and we are planning to make it default for v4.0.5 with a disable option.

Flip `build-block-parallel` feature flag

---

beacon-chain/operations/attestations/metrics.go
beacon-chain/operations/attestations/prepare_forkchoice.go
config/features/config.go
time/slots/slottime.go
time/slots/slottime_test.go

This PR removes the logs when batching attestations for forkchoice and adds metrics for the first two intervals in the slot where we aggregate.

Add aggregation metrics

---

beacon-chain/operations/synccommittee/message.go
beacon-chain/sync/metrics.go
beacon-chain/sync/validate_sync_committee_message.go
beacon-chain/sync/validate_sync_committee_message_test.go

This PR caches the blockroot of the votes for fast access and uses forkchoice to check that it matches the headroot (that is also cached in the blockchain package)

Use forkchoice to validate sync messages faster

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/options.go
config/features/config.go
config/features/flags.go

Feature Gating
This adds in a flag so that the resource manager component for libp2p can be switched on/off via a flag.  
N.A

Add Flag To Disable Resource Manager

---

beacon-chain/builder/service_test.go
beacon-chain/cache/BUILD.bazel
beacon-chain/cache/registration.go
beacon-chain/cache/registration_test.go
config/params/config.go
config/params/mainnet_config.go

Bug fix
the `--enable-registration-cache` currently has expiration logic to ensure timely updates and regular updates to validator registrations. Although validator registrations are sent every epoch, the registration currently has a buffer of 3 epochs before expiration. If a validator client is updated to not use builder settings or there are relay issues for accepting the validator registration for 3 epochs then the registration will expire, returning to local execution.
Assuming the relay is regularly responsive for validator registrations was an error and many relays may not respond to validator registration calls in a timely manner. This resulted in users losing MEV value due to rolling back onto local execution …

reverting expiration logic on validator while using --enable-registration-cache

---

beacon-chain/forkchoice/doubly-linked-tree/on_tick.go
beacon-chain/forkchoice/doubly-linked-tree/proposer_boost.go

Removes a trivial helper that is a oneliner that can't error out.

remove trivial helper

---

beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks_test.go
beacon-chain/rpc/eth/beacon/config_test.go
config/params/config.go
config/params/mainnet_config.go

See https://github.com/ethereum/consensus-specs/pull/3034#issuecomment-1551808727
And https://ethresear.ch/t/selfish-mining-in-pos/15551/3
The value of 160 may be discussed.

Fix sandwich attack on honest reorgs

---

beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/broadcaster_test.go
beacon-chain/p2p/monitoring.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/topics.go

Add `BroadcastBlob` to enable the broadcast of blob. Similar to Broadcast sync committee and attestation design

P2P: broadcast blob 

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go

This PR added two proposer RPC logs and modified one proposer RPC log
- It adds an `info` log to signal the start of block construction. Good signal for node operators to know when the beacon node started building block. (similar to geth's begin building payload). `sinceSlotStartTime` is the time diff between now and slot start time.
- It adds an `info` log to signal the end of the block construction. Good signal for node operators to know when the beacon node has completed the building block. (similar to geth's stopped building payload). `sinceSlotStartTime` is the time diff between now and slot start time.
- It added more fields to `Received header with bid` to signal slot, validator index, and time difference since start. 
More thoughts
- Should them be debug? I thought info is …

Add logs for build block times

---

api/client/builder/client.go

I'm unsure why `SubmitBlindedBlock` imposes a context deadline of 3s. This is more confusing than good. Reasons being:
- Validator already submitted the signed blind block. There's no default to local building
- Relayer may delay on block return to defend against the unbundling attack
- The parent caller already has a slot context deadline at 12s
It's better to wait for the block until the 12s mark than surface error like: 
```
Unknown desc = could not submit blinded block: error posting the SignedBlindedBeaconBlockCapella to the builder api: Post \"http://mev-boost/eth/v1/builder/blinded_blocks\": context deadline exceeded","message":"Failed to propose block","prefix":"validator","severity":"ERROR"}
```

Remove `SubmitBlindBlock` context timeout

---

async/event/feed.go
async/event/feed_test.go

Bug Fix
In the event we recover a feed which has had a panic triggered on it, a subsequent send on it will trigger a deadlock. This
PR releases the lock before triggering the panic and adds in a regression test for it.
Found in the TOB Audit: `TOB-PRYSM-7`

Release Lock Before Panicking

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go

`setExecutionData` has gotten too convoluted since Capella with builder payload, withdrawal root, and bid value comparisons. This PR cleans and refactors it to be extensible to future hard fork
Today:
```mermaid
flowchart TD
A[Check if you can use builder]
A -->|No|B[Get local payload]
B -->C[Set local payload]
A -->D[Get builder payload]
D -->|Fails|B
D -->|Ok|E[Get local payload]
E -->F[Get local value]
F -->G[Get builder value]
G -->H[Compare withdrawal root]
H -->|Fail|I[Return. NOTE: THIS IS A BUG]
H -->|Pass|J[Compare values]
J -->|Builder>Local and can set|K[Set builder payload and return]
J -->|Else|L[Set local payload and return]
```
What I propose is the following. Get local payload and builder payload outside of `setExecutionData`. Make `setExecutionData` as minimal as possible …

Proposer RPC: make `setExecutionData` better

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/service.go

In the event there's a late block coming (ie, no block 4s mark), we should still update the next slot cache without proposing the next slot
Also fixed a deep source complaint on: `Remove the internal goroutine and call the function using 'go'`

Update next slot cache correctly under late task

---

beacon-chain/rpc/eth/node/node.go

>
> Bug fix
When there are multiple inbound nodes and some nodes suddenly disconnect, the `/eth/v1/node/peers` interface may return `{"message":"Could not get peer info: Could not obtain ENR: peer unknown","code":500}`. This PR fixes this bug.

Fix the bug that return 500 in /eth/v1/node/peers interface

---

beacon-chain/blockchain/setup_test.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/testing/fuzz_p2p.go
beacon-chain/p2p/testing/mock_broadcaster.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

Changes 
- `ProposeBeaconBlock` absorbs `proposeGenericBeaconBlock`. `proposeGenericBeaconBlock` is becoming harder to maintain. 
- Broadcast and save blobs if block version is greater than Deneb

Update `ProposeBeaconBlock` Prysm RPC for Deneb (Non builder)

---

beacon-chain/p2p/options.go
beacon-chain/p2p/options_test.go

Bug Fix
We initialize `yamux` before `mplex` for stream multiplexing when building the libp2p host. This also fixes the unit test to assert that `yamux` is the first option that we do use.
Related to #12255 

Always Favour Yamux for Multiplexing

---

beacon-chain/monitor/process_sync_committee.go

Bug Fix
In the event we have phase0 blocks, we avoid processing them in the validator monitor for sync aggregates.
N.A

Ignore Phase0 Blocks For Monitor

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Hash tree root a block is not cheap. It was ~10-20ms last time I benchmarked on an M1 Max. There's no reason to HTR a block before broadcasting a block in the proposer critical path `proposeGenericBeaconBlock` except for logging. Here we replace logging block root to block slot and move HTR to after broadcast since we still need the root for `ReceiveBlock` anyway.

optimization(proposer-rpc): move htr to after broadcast

---

beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go
validator/client/validator.go
validator/client/validator_test.go

- beacon node RPC can handle Deneb version block for streaming endpoint
- validator client can accept streamed Deneb version block

feat(rpc/validator): stream and use deneb block

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/execution_engine_test.go
beacon-chain/rpc/eth/events/events.go

Update `getPayloadAttribute` to account for deneb state version

feat(blockchain): update payload attribute for deneb

---

tools/pcli/main.go

Add a command to benchmark hashing of cold beacon states. Tool is broken in many places but it's on tree and it's a common hack that I keep adding from time to time and need to keep it stashed  otherwise.

benchmark cold hashing of capella beaconstates

---

beacon-chain/core/altair/sync_committee.go
beacon-chain/core/helpers/attestation.go
beacon-chain/sync/subscriber.go

Cleanup
In gossip there are a lot of late attestation aggregates and sync committee messages being constantly broadcasted, unfortunately due to the large number of messages from these objects they can fill up our debug logs which makes it difficult 
to parse what is happening with a particular node. We now check that errors from gossip for `ignored` messages are only of
those that we infact care about.  
N.A

Ignore Late Message Logs

---

cmd/validator/accounts/delete_test.go
tools/keystores/main.go
validator/accounts/accounts_import.go
validator/accounts/accounts_import_test.go
validator/accounts/accounts_list_test.go
validator/keymanager/local/backup.go
validator/keymanager/local/import_test.go
validator/keymanager/types.go
validator/rpc/standard_api.go
validator/rpc/standard_api_test.go
validator/rpc/wallet.go
validator/rpc/wallet_test.go

Bug fix
We've had this bug for a while, user @sleepyqadr attempted to fix but the PR went stale...
https://github.com/prysmaticlabs/prysm/pull/11443
circling back on this 
>This PR tweaks the JSON in passing to change 'name' to 'description' in the resulting Keystore-0.json as per [EIP2335](https://eips.ethereum.org/EIPS/eip-2335#description)
while still supporting old formatted files via the "Name" field and set it as the description if not populated. When generating new files the Name field is now omitted. 
Fixes #11437

Reopenning fix for keystore field name change to align with EIP2335

---

cmd/prysmctl/testnet/generate_genesis.go
runtime/interop/genesis.go
runtime/interop/premine-state.go

Feature
Adds support to generate deneb genesis states via prysmctl. 
This doesn't cover enabling starting from deneb in e2e.

Integrate generate genesis

---

encoding/ssz/detect/configfork.go
encoding/ssz/detect/configfork_test.go

Bug fix
Adds state version detection support for deneb blocks and states. This is needed to use checkpoint sync to start at a deneb checkpoint.

ssz detection support for deneb

---

tools/interop/convert-keys/BUILD.bazel
tools/interop/convert-keys/main.go
tools/specs-checker/BUILD.bazel
tools/specs-checker/download.go

Bug Fix
In the event a file already exists for our key converter and specs checker, we error out rather than truncating the already existing file.
N.A
TOB-PRYSM-2

Ensure File Does Not Exist

---

api/client/builder/types.go
api/client/builder/types_test.go
beacon-chain/rpc/apimiddleware/structs_marshalling.go
beacon-chain/rpc/apimiddleware/structs_marshalling_test.go

Bug Fix
Similary to #12534 , we can also accept invalid json strings for `uint256` values in our builder api. We add stronger checks for these along with adding more robust checks to epoch participation parsing in a similar fashion.
N.A
Audit Finding: TOB-PRYSM-12

Fix Uint256 Json Parsing

---

cmd/prysmctl/p2p/BUILD.bazel
cmd/prysmctl/p2p/p2p.go
cmd/prysmctl/p2p/request_blobs.go

extend prysmctl to be able to request blobs via by range request, tested on interop

feat(prysmctl): request blobs

---

beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/sync/subscriber.go
consensus-types/blocks/getters.go

fix: devnet6 interop issues

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/chain_info_test.go
beacon-chain/blockchain/head.go
beacon-chain/blockchain/service.go

Track the optimistic status of head block instead of requesting from forkchoice. After two missed slots we revert back to forkchoice.

Track optimistic status on head

---

beacon-chain/blockchain/process_block.go

Use the incoming block instead of an unnecessary call to forkchoice.

use the incoming payload status instead of calling forkchoice

---

beacon-chain/blockchain/process_block.go

In order to optimize the updating of caches in the background, we should use a separate context instead of the main context. When the main context is returned, it triggers cancellation, leading to the termination of the corresponding goroutine. We already do this for the next slot cache and deposit cache.

fix: use diff context to update proposer cache background

---

beacon-chain/state/fieldtrie/field_trie_helpers.go
beacon-chain/state/stateutil/field_root_validator.go

Optimization
Instead of individually hashing each validator, we now use our optimized routine to 
accelerate this by a large factor. 
Helps with #12434 

Optimize Validator Roots Computation

---

beacon-chain/state/stategen/epoch_boundary_state_cache.go
beacon-chain/state/stategen/replay.go
beacon-chain/state/stategen/setter.go
beacon-chain/state/stategen/setter_test.go

Bug Fix
In certain situations in the network, we can miss saving the epoch boundary state into our boundary cache. This can cause issues in future epochs, as if we need to fetch the justified/finalized state we end up having to regenerating it from scratch. Instead of doing that, we have now decided to add an optimization to always save epoch boundary states into our cache. 
We also handle the edge case where the incorrect epoch boundary state is saved into our cache in the event of shallow re-orgs(1 slot) at the start of an epoch. Both these cases have test cases added in along with bug fixes in the deletion of values for the boundary cache.
N.A

Handle Epoch Boundary Misses

---

beacon-chain/core/altair/sync_committee.go
beacon-chain/core/altair/sync_committee_test.go

Other
When reviewing some logs, I found this error message to be somewhat confusing when the range overlaps with multiple slots due to the message disparity allowance. 
I've added the spec validation requirements to the godoc for `ValidateSyncMessageTime` and amended the error message to print the current slot rather than the computed slots based on the time disparity allowance.
Cosemetic only -- no logic changes.

Clarify sync committee message validation

---

beacon-chain/blockchain/metrics.go
beacon-chain/blockchain/receive_block.go

Add metric for chain service process block (ie. `ReceiveBlock`) This is a valuable metric to track, before we were using `onBlock`, but since the refactor, `onBlock` becomes `postBlockProcessing` and no longer conveys the whole end to end. `chainServiceProcessed` time is displayed on log only

feat: add metric for `ReceiveBlock`

---

crypto/bls/signature_batch_test.go

Bug fix
We randomly observe this failure when running unit test
go test -test.v -run=^TestSignatureBatch_AggregateBatch/common_and_uncommon_messages_in_batch_with_multiple_messages
=== RUN   TestSignatureBatch_AggregateBatch
=== RUN   TestSignatureBatch_AggregateBatch/common_and_uncommon_messages_in_batch_with_multiple_messages
signature_batch_test.go:643: AggregateBatch() Descriptions got = [test signature bls aggregated signature test signature bls aggregated signature test signature bls aggregated signature], want [bls aggregated signature test signature bls aggregated signature test signature bls aggregated signature test signature]
--- FAIL: TestSignatureBatch_AggregateBatch (0.02s)
--- FAIL: …

Fix bls signature batch unit test

---

beacon-chain/blockchain/receive_block.go

Bug Fix
In #12589 , we moved the finalization of deposits into its own method and modified its control flow. However we incorrectly cancelled the context when `onBlock` finishes executing, when we should only be cancelling the context once the execution of  
`insertFinalizedDeposits` finishes. This PR fixes it.
N.A

Fix Context Cancellation

---

encoding/bytesutil/bytes.go
encoding/bytesutil/bytes_test.go

Optimization
We allow the option of casting a slice to a 32-byte array to directly copy it. This is so as to allow calls to `runtime.mallocgc` and `runtime.memove` to be replaced with a single call to `runtime.NewObject` . This particular function is executed for a large amount of times in a critical block proposal path path. 
Helps with #12434 

Copy Bytes Alternatively

---

WORKSPACE

Other
As title describes.
Mostly security issues that are not immediate concerns to Prysm.
https://go.dev/doc/devel/release#go1.20.6
```
go1.20.4 (released 2023-05-02) includes three security fixes to the html/template package, as well as bug fixes to the compiler, the runtime, and the crypto/subtle, crypto/tls, net/http, and syscall packages. See the Go 1.20.4 milestone on our issue tracker for details.
go1.20.5 (released 2023-06-06) includes four security fixes to the cmd/go and runtime packages, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/rsa, net, and os packages. See the Go 1.20.5 milestone on our issue tracker …
```

Update go version to 1.20.6

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_altair.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_altair_test.go

Bug fix
In case getSyncAggregate throws error and emptyAggregate variable of type SyncAggregate is generated, where SyncCommitteeBits expected to be 512 bits which is 64 bytes. However, in the existing code it is intialised by 512 bytes which makes it 4096 bits.

Fix: Size of SyncCommitteeBits should be 64 bytes (512 bits) instead of 512 bytes

---

tools/pcli/main.go

Adds the deserialization time to pcli's benchmark

Add deserialization time in pcli benchmark

---

cmd/beacon-chain/flags/base.go
cmd/beacon-chain/main.go
cmd/beacon-chain/usage.go

Add blob-related flags to `main` and `usage` so they get initialized correctly. This fixes the panic/division 0 we see on devnet7
```
time="2023-07-11 15:53:24" level=error msg="Panic occurred" error="runtime error: integer divide by zero" prefix=sync recovered_at=registerRPC stack="goroutine 1512899 [running]:
```

fix: add blob flags to main

---

beacon-chain/blockchain/metrics.go

Optimization
Instead of fetching the whole validator registry and copying each validator, we can't significantly optimize this by only fetching read only validators. Read only validators are not copied but instead are simply wrapped with a `ReadOnlyValidatorStruct` , which allows the caller to read values from it without copying the whole validator.
N.A

Do Not Perform Full Copies For Metrics Reporting

---

tools/pcli/main.go

When we benchmark deserialize for pcli, we use `InitializeFromProtoCapella`, which internally calls `proto.Clone`. This does a copy of a protobuf beacon state which calls proto reflect library. That could be slow. This PR changes it to using `InitializeFromProtoUnsafeCapella` which doesn't call `proto.Clone`

fix: benchmark deserialize without clone and init trie

---

beacon-chain/execution/engine_client_test.go
encoding/bytesutil/BUILD.bazel
encoding/bytesutil/bytes.go
encoding/bytesutil/bytes_test.go
proto/engine/v1/json_marshal_unmarshal.go
proto/engine/v1/json_marshal_unmarshal_test.go

blobs bundle should use [hexutil.Bytes](https://github.com/MariusVanDerWijden/go-ethereum/blob/4844-devnet-6/beacon/engine/types.go#L91). h/t to @prestonvanloon

fix: use hexutil bytes for blobs bundle

---

proto/migration/v1alpha1_to_v2.go
proto/migration/v1alpha1_to_v2_test.go

Bug fix
Capella state returned from [/eth/v2/debug/beacon/states/{state_id}](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Debug/getStateV2) was missing historical roots.
Fixes #12618

Return historical roots in Capella state

---

crypto/bls/blst/BUILD.bazel
crypto/bls/blst/init.go
crypto/bls/blst/public_key.go

> Other
This replaces our public keys cache used in our crypto/blst/ package #12476 to a slightly modified one that is thread-safe across concurrent readers that only acquire a read-lock instead of a read-write-lock. This is a considerable improvement, as concurrent readers have to all wait for a lock to `Get()` a public key, and is noticeable during the pipelines of multiple signature verification. This is far worse when running with a lot of subnets, for example, and shows up in pprof for a beacon node on mainnet.
The LRU cache introduced is the same as before, except it has a few core modifications in that it uses a mutex.RLock for Get() calls instead of a mutex.Lock and adds greater thread-safety and nil checks. …

Integrate Read-Only-Lock-on-Get LRU Cache for Public Keys

---

beacon-chain/core/blocks/block_operations_fuzz_test.go
beacon-chain/core/blocks/exit.go
beacon-chain/core/blocks/exit_test.go
beacon-chain/core/signing/BUILD.bazel
beacon-chain/core/signing/signing_root.go
beacon-chain/operations/voluntaryexits/pool.go
beacon-chain/rpc/eth/beacon/pool.go
beacon-chain/rpc/prysm/v1alpha1/validator/exit.go
beacon-chain/sync/validate_voluntary_exit.go
testing/util/block_test.go

Feature
EIP-7044 essentially freezes the signature domain to the Capella fork data in Deneb. This PR updates the signing domain computation and verification in deneb to fulfill the requirements of the EIP.
~This PR is rather small and could possibly be a good candidate for the develop branch. It does not require any Deneb specific structs (except beacon state) and shouldn't effect the critical path as the new logic only runs on a state version of Deneb or greater.~ Nevermind, it depends on deneb beacon state for tests.

Deneb: Implement EIP-7044

---

beacon-chain/blockchain/receive_attestation.go
beacon-chain/sync/rpc_beacon_blocks_by_range.go

Clean up
This cleans up some cosmetic logs so that users are not alarmed by the errors that are logged out. We wait till the node
is synced before running the `spawnAttestationsRoutine` . 
N.A

Clean Up Logging

---

testing/spectest/mainnet/capella/operations/BUILD.bazel
testing/spectest/mainnet/capella/operations/bls_to_execution_change_test.go
testing/spectest/mainnet/capella/operations/withdrawals_test.go

h/t to @potuz , we missed these
side question, how do we close the loop moving forward, perhaps we can write a tool to check upstream folders and fail if something is not implemented

fix: add mainnet withdrawals and bls spec tests

---

beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/service_test.go

Feature
If we require 0 peers to sync, then we exit initial sync immediately and enter regular sync. This allows users running
single node devnets to start and stop with ease. 
N.A

Exit Initial Sync Early

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/receive_block.go

Paralellizes CL and EL validation, should shed about 200ms on a normal slot, and a bit more on slower slots.

Parallelize cl el validation

---

validator/client/metrics.go

Bug fix
Pending validator values are showing up as 32000000000 instead of 32 in the metrics. This PR addresses this issue. again it's approximate and does not account for the actual value the user deposited, once active the value should be reflected.

Bugfix: Metrics adding fix pending validators balance

---

beacon-chain/rpc/eth/beacon/BUILD.bazel
beacon-chain/rpc/eth/beacon/handlers.go
beacon-chain/rpc/eth/beacon/handlers_test.go
beacon-chain/rpc/eth/beacon/structs.go
network/BUILD.bazel
network/reader.go
proto/migration/BUILD.bazel
proto/migration/v1alpha1_to_v2.go
proto/migration/v1alpha1_to_v2_test.go
proto/migration/v2_to_v1alpha1.go
proto/migration/v2_to_v1alpha1_test.go

Feature
Implements the following, unit test values should be updated with sample data instead of using mock data.
Implements the following APIs for Deneb
part of #12248

Deneb: publishblockv2 endpoint

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/service.go

This is an alternative to #12651 It does the following
- It removes the updating of caches at the start of epochs (this is handled now on late block tasks)
- It updates the cache both on skipped slots 31 (at 4 seconds) and on incoming blocks 31 performing a copy in both cases. 
- It refactors the function `handleEpochBoundaries`  so that it can be used both from `postBlockProcess`  and within `lateBlockTasks` 
- Fixes an existing bug: we should update the cache with the headState, not the incoming block state. 
- Moves epoch reporting away from the hot forkchoice lock to `ReceiveBlock`. 
- Removes the variable from the service that tracks the next epoch boundary slot
- It adds some missing locks
There is the problem of the extra copy done whenever slot 31 comes late, but this is …

update shuffling caches at epoch boundary

---

beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/beacon_committee_test.go

When we call `UpdateCommitteeCache`, we update `epoch` and `epoch+1`. If `epoch` exists, the function returns `nil` instead of `continue`. This means in the happy case, `epoch+1` never gets updated
Besides the inefficiency, here is what the real bug is:
1.) Start beacon node, at the end of epoch 1, we update the cache for epochs 2, and 3
2.) At end of epoch 2, epoch 3 is pre-cached, we skip updating epoch 4 because of the return nil 
3.) We then call `UpdateProposerIndicesInCache` for epoch 4. `UpdateProposerIndicesInCache` calls `ActiveValidatorIndices` which fills on the miss. Because epoch 4 doesn't have an entry, it caches epoch 4 and epoch 5(!)
4.) Here is the bug. At the end of epoch 2, the committee cache creates an entry for epoch 5
Another consideration is to remove fill on miss …

fix: update committee cache epoch + 1

---

beacon-chain/sync/metrics.go
beacon-chain/sync/validate_beacon_blocks.go

This is a very useful metric to have: how long did the block take to arrive from gossip's perspective? Besides logging, we don't have anything to monitor this

feat: add metric for block gossip time

---

validator/client/runner.go

Bug fix
In rare instances, the validator gets activated and proposes very close to its activation, since we moved the api call to mid epoch it may result in proposing with the fallback fee recipient on the beacon node. this PR will reverse this back to being at the epoch start.

Bugfix: proposer-settings edge case for activating validators

---

beacon-chain/state/stategen/replay.go

the metric existed but it was never used for the old regen code

feat: add state regren duration metric

---

beacon-chain/blockchain/process_block.go

This PR handles the following situations
The current behavior is this
- A block for slot 31 comes in but it is not canonical (say it's based on slot 16 for some reason)
- We do not update the NSC, but later on `handleEpochBoundary` we update the shuffling committee and this requires an epoch transition (bug number 1) 
- Later in `lateBlockTasks` we call again `handleEpochBoundary` to update the committees again (bug number 2). 
This PR removes the first call since it will happen anyway in `lateBlockTasks`. Notice that this doesn't affect the scenario when block 31 comes in and is late: 
- If it is canonical then we will call `handleEpochBoundary` at block processing. 
- If it is not, then already `lateBlockTasks` took care of it.

only handle epoch boundary on canonical blocks

---

beacon-chain/blockchain/process_block.go

I saw a few context deadline around at slot 31 and using the wrong context was the reason
```
[2023-08-02 07:01:49] DEBUG sync: Received block blockSlot=7013407 graffiti=Lodestar-v1.9.2/72beda1 proposerIndex=704602 sinceSlotStartTime=2.872754726s validationTime=4.470042ms
[2023-08-02 07:01:50] DEBUG blockchain: Synced new block block=0x400eda79... chainServiceProcessedTime=318.499025ms deposits=16 epoch=219168 finalizedEpoch=219166 finalizedRoot=0x618bbf93... justifiedEpoch=219167 justifiedRoot=0x6796db2a... parentRoot=0x8
a3fc4a6... sinceSlotStartTime=3.196996676s slot=7013407 slotInEpoch=31 version=capella
[2023-08-02 07:01:50] DEBUG blockchain: Synced new payload blockHash=0x2c7e1f71ff7a blockNumber=17827777 blsToExecutionChanges=0 gasUtilized=0.72 parentHash=0x406ff7bf7e5c …
```

Fix: use correct context for `UpdateCommitteeCache`

---

proto/prysm/v1alpha1/attestation/attestation_utils.go

Span is not free and `ConvertToIndexed` is one of the highest traffic path. It is called on every attestation. About 21k times every 12s if a node subscribes to all the subnets. The span itself shows up on the profile when a block takes 1s to process.

Remove: span for convert to indexed attestation

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

`aggregate-parallel` by default with a backoff flag `disable-aggregate-parallel`.
This feature has been battled and tested on testnet and some mainnet nodes. It reduces aggregation time ~80% if you run more than 10 validators. A node without beacon subnet will treat additional background routines as no-op, which should also be very fast

Feat: aggregate parallel default

---

deps.bzl
go.mod
go.sum
third_party/blst/blst.BUILD

Security Update
This updates blst to address this vulnerability:
https://github.com/supranational/blst/security/advisories/GHSA-8c37-7qx3-4c4p
While we are not affected, future use of `SigValidate` with infinity checks enabled would lead to the incorrect result.
N.A

Update BLST to v0.3.11

---

consensus-types/payload-attribute/getters.go
consensus-types/payload-attribute/getters_test.go

To follow engine API spec and like V1 and V2, in the event where payload attribute v3 is empty or fields containing zero values, it should return nil/null instead of an empty struct. This is part of the engine API definition

fix: payload attribute v3 return nil

---

beacon-chain/rpc/eth/blob/BUILD.bazel
beacon-chain/rpc/eth/blob/handlers.go
beacon-chain/rpc/service.go

Other
Wrong URL is used on the handler, It should be /eth/v1/beacon/blob_sidecars/{block_id}, not /eth/v1/beacon/blobs/{block_id}
adding a trace span and using handle error

deneb: fixing route handler and small cleanup items

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/db/kv/blob.go
beacon-chain/db/kv/blob_test.go
beacon-chain/sync/subscriber_blob_sidecar.go

When we receive a blob over a subscriber, it must be saved to the DB later for `isDataAvailable` in the blockchain pkg. This allowed a beacon node to process consensus and execution checks in parallel. The beacon node should not block the processing of a block until it has received all the blobs. Instead, it should process the block as soon as it gets it. 
This PR implements the following 
- DB pkg `SaveBlobSidecar` allows merging blobs and only delete blobs if the key is older than the retention period. Removed blob index check
- Blockchain pkg `removeInvalidBlockAndState` also removes the blob for block root
- Sync pkg `blobSubscriber` saves the blob to the DB
This PR does not touch the following but needs to be discussed (separate issues?)
- DB pkg `SaveBlobSidecar` inputs a list of …

feat: save blobs to db for subscriber

---

beacon-chain/p2p/gossip_scoring_params.go

Add blob peer scoring params with a TODO as it currently uses block scoring. This is better than nothing and fixes the `unrecognized topic provided for parameter registration` error for every run. We should figure out the detailed scoring params and I'll default that to @nisdas

feat: add blob peer scoring params

---

validator/client/propose.go
validator/client/propose_test.go

The `signedBlobs` slice in  `ProposeBlock` is allocated. Instead of `append`, it should `assign`. Also added a regression test

fix: validator returning the right # of blobs

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_block.go

Cleanup
In #12625, we checked for the optimistic status of blocks right after they had been processed. We would log an error in the event the forkchoice store was unable to retrieve their status. This log is changed from an error log to a debug log.
N.A

Shift Error Logs To Debug

---

beacon-chain/blockchain/receive_block.go

Use the optimistic status of the last block imported in a batch. If it's valid all parents are guaranteed to be valid. If it's optimistic, then it's safe to send some blocks as optimistic.

Use last optimistic status on batches

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_blob.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/sync/service.go
beacon-chain/sync/subscriber_blob_sidecar.go

Adds a new channel to the blockchain package to keep track of blobs that have been added to database. 
It's an unbuffered channel that notifies the blob sidecar's `blockroot`. 
When processing blocks, if the blob is not in the database, we block until the channel receives the right blockroot or the slot context deadline is done. 
The channel is unbuffered since blobs are always consumed by blocks.

Blob channel

---

beacon-chain/sync/initial-sync/blocks_fetcher.go

Bug fix
This fixes a bug in the `lowestSlotNeedsBlob` func. This method was trying to use binary search to find the first block in the sorted list that contained commitments. Which was an utterly deranged thing to do. Now the func iterates through the slice in order and returns the slot of the first block that contains commitments.

binary search is the wrong tool for the job, derp

---

cmd/beacon-chain/flags/base.go

Other
changing the flag type to support the correct type.
this is a breaking change and will result in an error such as the following example
` invalid value "100.30" for flag -local-block-value-boost: parse error  prefix=main`
removing the .30 will result in the correct value
prysm docs must be updated accordingly

local-block-value-boost flag from float64 to uint64 [BREAKING CHANGE]

---

.github/workflows/fuzz.yml

Updates the fuzz github workflow list timeout to 180 minutes

Update Fuzz List Timeout Github Workflow

---

config/params/testnet_e2e_config.go

Bug fix
Rebasing deneb-integration onto develop brought over an unused import. We also need to set an appropriate value for deneb epoch in the e2e config when deneb-integration merges into develop. This PR kills 2 birds with one stone by turning off deneb e2e now. We will set up a new branch to run e2e for deneb testnets.

set e2e to math.MaxUint64 (fixes build)

---

beacon-chain/db/kv/blob.go
beacon-chain/db/kv/kv.go
beacon-chain/db/kv/schema.go

Other
This is addresses @nisdas feedback on #12773.
This is directly a response to Nishant's feedback, so I'll be looking for his approval before merging.
I changed from a single key bucket for the retention period to using the `chainMetadataBucket` used by other single values in the db. I prefer this pattern of consolidating all the metadata type values over adding more single-value buckets.

re-use metadata bucket, group db constants

---

validator/client/beacon-api/beacon_api_node_client.go
validator/client/beacon-api/beacon_api_node_client_test.go

Feature
It adds REST API implementation of node version endpoint to get node version of the beacon node. Refer: https://ethereum.github.io/beacon-APIs/#/Node/getNodeVersion
It is needed to use prysm specific endpoints on the VC side by using this endpoint to check if we are connected to prysm beacon node first.

Add REST implementation of node version endpoint

---

beacon-chain/blockchain/service.go
config/params/config.go

Other
Addresses one of Nishant's deneb integration feedback items: https://github.com/prysmaticlabs/prysm/pull/12773#discussion_r1303089808

Don't call kzg.Start if deneb fork isn't "scheduled"

---

runtime/interop/premine-state.go

Ensure populating current and previous epoch participation in the genesis state for interop; otherwise, proposer at slot 1 can't compute state root (participation bits out of bounds).

fix: set current and prev epoch participations for interop genesis

---

beacon-chain/state/state-native/hasher.go
beacon-chain/state/state-native/state_trie.go
config/params/config.go
config/params/configset_test.go
config/params/mainnet_config.go
config/params/testnet_config_test.go

Other
Gives deneb its own field count variable (used by native state code).
In response to @nisdas review on https://github.com/prysmaticlabs/prysm/pull/12773 needs approval from him

give deneb it's own field count config value

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deneb.go

This PR reinstates the option to disable build block parallel. While it's currently enabled by default, the `deneb-integration` removed this feature for major release assumption and simplicity. Since we're merging `deneb-integration` into `develop`, the fallback should be retained.

fix: add back non parallel proposer

---

beacon-chain/execution/log_processing.go
beacon-chain/execution/log_processing_test.go

Other(improvement)
In prysm's heap profile, I see a lot of memory(14%) is hold inside the `ProcessLog`  
And after some digging, seems it was caused by the value copy

beacon-chain/execution: use pointer instead of value to reduce copy

---

WORKSPACE
beacon-chain/node/node.go
beacon-chain/state/stategen/errors.go
beacon-chain/state/stategen/getter.go
beacon-chain/state/stategen/service.go
cmd/beacon-chain/main.go
cmd/prysmctl/validator/cmd.go
cmd/validator/accounts/accounts.go
cmd/validator/slashing-protection/slashing-protection.go
cmd/validator/wallet/wallet.go
config/features/config.go
config/features/flags.go
config/params/BUILD.bazel
config/params/testnet_holesky_config.go
config/params/testnet_holesky_config_test.go
config/params/values.go

Feature
Adds holesky config support for the upcoming holesky testnet.
The holesky genesis state is far too large to bundle inside of the prysm distribution binary (200Mb) so it must be loaded from disk or checkpoint sync. This is existing behavior for other testnets, but I felt it would be helpful to provide a meaningful failure message when the user attempts to run prysm on a non-mainnet network. 
#12724
Example of running Prysm without a genesis state
```
[2023-08-28 11:37:34]  WARN flags: Running on the Holesky Beacon Chain Testnet
[2023-08-28 11:37:34]  WARN node: In order to receive transaction fees from proposing blocks, you must provide flag …
```

Holesky support

---

beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go

When requesting a block using by root we also should request the blobs if the block is Deneb and there exists kzg commitments. This PR implements `requestPendingBlobs` under `SendBeaconBlocksByRootRequest`. This PR has been verified to work in devnet8 and has unit test coverage until SendBlobSidecarByRoot, which becomes hard to test

fix(sync/rpc): use blobs by root when requesting block

---

beacon-chain/db/kv/blob.go
beacon-chain/db/kv/blob_test.go

**Background:**
Bolt DB struggles with pruning, which has been evident during the development of the slasher. With the introduction of EIP-4844 in Prysm, there will be a significant amount of blob data. In the last design, we implemented a rotating buffer database schema for blobs. This schema will overwrite old data once the expiration period for blobs is reached, eliminating the need for pruning or deletion routines.
**How It Works:**
- Store a maximum of N epochs worth of blobs.
- Once epoch N is reached, overwrite the contents of epoch 0 using a modulo operation.
- Given the possibility of multiple blob sidecars per slot, a straightforward overwriting algorithm won't suffice.
Saving blobs involves:
- Convert the slot using a modulo operator to a range of `[0, maxSlots]`, where …

db: fix save blob sidecar using wrong prefix

---

beacon-chain/db/kv/blob.go
beacon-chain/db/kv/blob_test.go

Other
This comment (https://github.com/prysmaticlabs/prysm/pull/12849/files#r1315352106) got me thinking
about how we can improve the use and readability of the blob storage keys and prevent accidental
misuse. This PR adds a simple bytes alias with some accessor methods to make it clear to the reader
and writer about the information they intend to access.
~Merge after #12849~

db: Use blobRotatingKey alias for readability 

---

beacon-chain/blockchain/process_block.go

Bug fix
fixes a small bug where we wrap the wrong value for err in the slot context deadline.

wrap ctx.Err, not the random last value of err

---

validator/client/attest.go
validator/client/validator.go

> Bug fix
This PR adds a RW lock for modifying and accessing the `duties` struct in the `validator` struct. Together with the [antithesis](https://antithesis.com/) team we discovered a race condition where two go routines are trying to access the same memory location related to the `v.duties` struct. The race condition can lead to a panic exiting the validator process.
The data race before the panic:
```
[ 1320810] [  1667.682068] [service_prysm-geth-0--prysm-vc]             [I] WARNING: DATA RACE
[ 1320810] [  1667.682078] [service_prysm-geth-0--prysm-vc]             [I] Read at 0x00c0003778f8 by goroutine 1235:
[ 1320810] [  1667.682088] [service_prysm-geth-0--prysm-vc] …
```

add a RW lock for duties

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

**Issue:**
The `blobs_sidecar.block_root` was found to be incorrect due to the premature invocation of `hash_tree_root` before the `state_root` was inserted into the `block`.
**Solution:**
This Pull Request addresses the issue by:
1. Reordering the sequence of function calls: Now, `blobsBundleToSidecars` and `blindBlobsBundleToSidecars` are called after `SetStateRoot`.
2. Implementing minor refactoring: This was necessary to accommodate the use of bundles before sidecars in previous calls.
fixes #12858

fix: use correct blob root in blobs sidecar

---

cmd/prysmctl/BUILD.bazel
cmd/prysmctl/testnet/generate_genesis.go

This PR adds the option to delay the genesis time by a duration in Prysmctl, helpful for some CLI / docker workflows without needing to invoke bash commands of delaying timestamps

Add Delay Option for Genesis to Prysmctl

---

validator/client/validator.go
validator/client/validator_test.go

Fixes https://github.com/prysmaticlabs/prysm/issues/12840

don't send pre-genesis signed validator registration objects to relayers

---

beacon-chain/db/kv/blob.go
beacon-chain/db/kv/blob_test.go

Bug fix
Allows the blob db to store sidecars under multiple roots at a given slot. With the current db design, we are unable to do this, which causes inconsistent reads when equivocating blobs are received.

Allow equivocating blobs

---

beacon-chain/sync/fork_watcher.go
beacon-chain/sync/fork_watcher_test.go

Bug Fix
This allows prysm nodes to register for the deneb sync rpc topics once the deneb fork has happened. This will allow 
blobs to be requested by root/range between peers. Otherwise no prysm node will be able to serve any blob data without a manual restart. This PR also adds in a respective regression test.
N.A

Fix Deneb Fork Registration

---

beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
beacon-chain/rpc/prysm/v1alpha1/validator/unblinder_test.go

h/t to @marioevz
Copy kzg commitments before and after submit blind block. This ensures kzg commitments stay consistent through out beacon block body

Copy kzg commitments when using builder block

---

validator/client/blob.go
validator/client/blob_test.go
validator/client/propose.go
validator/client/propose_test.go

**Summary:**
This PR introduces the ability for the validator client to sign blind blob sidecars. 
**Details:**
- A new function, `signBlindBlob`, has been added. This function will be utilized by `ProposeBlock`.
- In the `ProposeBlock` method, if the block is blinded with version deneb, the validator client will sign the blind blob sidecars.
- As a result, it will construct the appropriate `GenericSignedBeaconBlock_BlindedDeneb` to be returned later in the process.

Add Blind Blob Sidecar Signing in Validator Client

---

api/pagination/pagination.go
api/pagination/pagination_test.go

Bug Fix
Currently if we provide negative page size values or negative token values our API endpoints will panic as
these values are invalid. This PR checks for negative page sizes along with negative token values to handle these panics. Regression test for these particular cases have been added in. 
Alternative solutions to use unsigned integers for these values had been considered but was ignored as changing the method signature to use unsigned values would require changing all the respective api endpoints.
TOB-PRYSM-5

Fix Pagination Panic

---

beacon-chain/rpc/eth/validator/handlers.go
beacon-chain/rpc/eth/validator/handlers_test.go

Part of fixing #12936 
This PR removes the caching of the proposer ID during `GetProposerDuties`

Do not cache proposer ID on GetProposerDuties

---

beacon-chain/db/kv/blob_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block.go
beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

This PR focuses on refactoring the `proposer.go` file, precisely the logic around constructing various versions of beacon blocks. The primary goal is to improve maintainability by abstracting repetitive code into helper functions.
- Removed code for constructing `GenericBeaconBlock` based on different versions and conditions.
- Added a new function `constructGenericBeaconBlock` that leverages a switch-case structure to call appropriate helper functions based on the block version.
- Created helper functions like `constructDenebBlock`, `constructCapellaBlock`, etc., for each version-specific block construction.
- Added `IsBlinded` and `PayloadValue` for deneb conditions

Refactor construct generic beacon block for proposer

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go

This pull request aims to improve the maintainability and readability of the `getLocalPayloadAndBlobs` function. The refactor introduces a new helper function, `getParentBlockHash`, which streamlines the logic for fetching the parent block hash based on various conditions. This change aligns with the consensus spec as outlined in [PR #3350](https://github.com/ethereum/consensus-specs/pull/3350).
- **New Helper Function**: Adds `getParentBlockHash` to encapsulate the logic for obtaining the parent block hash.
- **Optimization for Capella or Older**: If the beacon state is Capella or older, the function optimizes the `IsMergeTransitionComplete` check and fetches the parent block hash directly from `st.LatestExecutionPayloadHeader()`.
- **Consistent Checks**: Retains the existing checks for …

Refactor `getLocalPayloadAndBlobs` with New Helper `getParentBlockHash`

---

cmd/beacon-chain/flags/base.go

`--safe-slots-to-import-optimistically` is no longer used, we should clarify that in usage and mark it as deprecated

Deprecate `--safe-slots-to-import-optimistically` beacon flag

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

This PR fixes issue #12950 where `GetBeaconBlock` in the beacon API does not correctly utilize the `skip-mev-boost` parameter when making a call to the underlying prysm API.
In the beacon API, there are distinct endpoints for requesting a full block or a blind block. However, the prysm API does not make this distinction, instead relying on a `skip-mev-boost` parameter. The issue arises because the `skip-mev-boost` parameter was not being recognized or used within the `GetBeaconBlock` function in the beacon API. Here is the beacon API request:
```
v1alpha1req := &ethpbalpha.BlockRequest{
Slot:         req.Slot,
RandaoReveal: req.RandaoReveal,
Graffiti:     req.Graffiti,
SkipMevBoost: true, // Skip mev-boost and relayer network
}
```
This PR rectifies this oversight by incorporating the …

Fix `GetBeaconBlock` to use `skip-mev-boost`

---

beacon-chain/rpc/core/validator.go
beacon-chain/rpc/eth/beacon/handlers_pool.go
beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go

Other
Makes error handling of core service more standard

Return RpcError from core service's `SubmitSyncMessage`

---

beacon-chain/core/blocks/exit.go

Bug Fix
In #12737 , we refactored our exits function to only calculate the churn once while processing voluntary exits. However this has lead to us computing the churn even for blocks which have 0 exits. This PR adds in a short-circuit to allow blocks with 0 exits to be processed more efficiently
N.A

Do Not Calculate Churn With 0 Exits

---

beacon-chain/rpc/eth/beacon/BUILD.bazel
beacon-chain/rpc/eth/beacon/handlers_pool.go
beacon-chain/rpc/eth/shared/structs.go
beacon-chain/rpc/eth/validator/BUILD.bazel
beacon-chain/rpc/eth/validator/handlers.go
beacon-chain/rpc/eth/validator/structs.go

Other
When converting data posted in the request to the consensus type, we check that the input is correct before we can decode it (example below). The validation package doesn't bring us much benefit, it essentially duplicates the same checks. We can bring it back in the future in case more sophisticated validation is needed that this package handles well.  
```
func (s *SyncCommitteeContribution) ToConsensus() (*eth.SyncCommitteeContribution, error) {
slot, err := strconv.ParseUint(s.Slot, 10, 64)
return nil, NewDecodeError(err, "Slot")
}
bbRoot, err := hexutil.Decode(s.BeaconBlockRoot)
return nil, NewDecodeError(err, "BeaconBlockRoot")
}
subcommitteeIndex, err := …
```

Remove go-playground/validator from Beacon API

---

beacon-chain/rpc/eth/validator/handlers.go
beacon-chain/rpc/eth/validator/handlers_test.go

This reverts #12939 temporarily while we work on the proper fix

Revert "Do not cache proposer ID on GetProposerDuties (#12939)"

---

beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/core/helpers/weak_subjectivity.go
beacon-chain/core/validators/validator.go
beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go
beacon-chain/rpc/prysm/v1alpha1/beacon/validators_stream.go
beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go

This refactors the churn limit helper functions related to validator activities: 1) Activation, 2) Exit, and 3) Activation in Deneb.
- Separated the `activate` and `exit` functionalities into distinct helper functions for clarity.
- Introduced a dedicated function for the Deneb-specific activation churn limit.
- Ensured the new helpers are applied consistently across all relevant parts of the code.

Refactor churn limit helpers

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/pending_blocks_queue_test.go
beacon-chain/sync/validate_beacon_blocks.go

This PR centralizes the invocation of `setBadBlock` within the `validateBeaconBlock` function. Previously, `setBadBlock` was called in various places outside this function, which was redundant and fragmented error handling.
Now, `setBadBlock` is called in the following scenarios exclusively within `validateBeaconBlock`:
- New: Validate DenebBeaconBlock for bad kzg commitment count
- When the parent block is not in fork choice
- When the block has a bad signature
- When the block has a bad execution payload

Don't mark block as bad in `validateBeaconBlock` for pending queue

---

testing/endtoend/evaluators/operations.go

Bug Fix
In #12959, we added support for EIP-7514, which capped the max activation limit but also in the process broke long running e2e due to how the epoch churn limit was calculated. This PR fixes it to use the test config when calculating the correct churn
N.A

Fix Long Running E2E

---

beacon-chain/sync/BUILD.bazel
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go

Fixes #13011
This PR enhances blob retrieval from peers by first checking if the blobs are already present in the DB before requesting. It also includes refactoring of the `requestPendingBlobs` function to improve code clarity.
Inside `requestPendingBlobs`, the PR introduces two steps:
- **`constructPendingBlobsRequest`**: This function constructs the request object by filtering out known indices through a db call.   
- **`sendAndSaveBlobSidecars`**: Utilizes the request object from `constructPendingBlobsRequest` to request blobs by their root and subsequently save them to the DB.

Check blob exists before requesting from peer

---

beacon-chain/sync/pending_attestations_queue.go
beacon-chain/sync/pending_blocks_queue.go

Fixes an issue where redundant requests were made to peers for blocks already present in the pending queue, adversely affecting peer scoring.
1. **Pending Attestation Queue**: Check if the block exists in the queue before appending pending roots.
2. **Batch Root Request**: Similar to `BlockBeingSynced`, removes the root from the request list if it's already seen.
This PR adds checks in both places for future-proofing.

Check block exists in pending queue before requesting from peer

---

beacon-chain/sync/rpc_beacon_blocks_by_root.go

This PR introduces a length check for the blob request parameter at the function level. The aim is to prevent errors that get triggered and subsequently propagated upstream when the parameter's length is 0.
This check could be added at the caller level, implementing it at the function level centralizes the logic, thereby making the code easier to maintain and less prone to errors.

Exit early if blob by root request is empty

---

beacon-chain/sync/validate_blob.go
beacon-chain/sync/validate_blob_test.go

On P2P handling of blobs, in the typical case, we will ignore blobs with an invalid parent instead of rejecting them.

Reject blobs with invalid parent

---

beacon-chain/sync/validate_blob.go

Use a separate `ctx` for `sendBatchRootRequest` because it operates as its own routine. Otherwise, upon return, `sendBatchRootRequest` would be canceled, and cause block request to fail

Use correct context for `sendBatchRootRequest`

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go

When performing blob alignment checks in the `sendAndSaveBlobSidecars` path, it's possible that the block may not yet exist in the database if it's in the pending queue. To address this issue, we should pass the block directly as an argument. It's  more simpler and more efficient this way

Passing block as arugment for sidecar validation

---

beacon-chain/rpc/apimiddleware/endpoint_factory_test.go
beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
beacon-chain/rpc/eth/beacon/blocks_test.go
beacon-chain/sync/rpc_goodbye.go
cmd/prysmctl/p2p/handler.go
proto/prysm/v1alpha1/slasher.pb.gw.go

Cleanup
As an alternative to #13074, we set only the goodbye logs to trace so as to reduce the burden of filtering debug logs. Currently goodbye logs account for a large amount of debug logs, which aren't helpful for doing log analysis.
Supersedes #13074

Set Verbosity of Goodbye Logs to Trace

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/process_block.go
beacon-chain/db/iface/interface.go
beacon-chain/db/kv/blob.go
beacon-chain/db/kv/blob_test.go

Remove sidecars when they have invalid proofs. Also rename function in anticipation of an existing DeleteBlobSidecar

Remove sidecars with invalid proofs

---

beacon-chain/sync/initial-sync/round_robin.go

When syncing to the finalized checkpoint on init sync (what we call phase 1) we sync blocks in batches until we reach an epoch that is strictly higher than the finalized checkpoint's epoch. That is, if our finalized checkpoint is for epoch 1, we skip this step when the head slot is 64 or higher. 
This PR changes this behavior to skip this step starting when the head slot is within the finalized checkpoint epoch, that is 32 in the example above. This is so that we skip stage 1 syncing during checkpoint sync.

sync only up to previous epoch on phase 1

---

beacon-chain/state/state-native/references_test.go
beacon-chain/state/state-native/setters_validator.go
beacon-chain/sync/backfill/status_test.go

Bug Fix
The multivalue slice deadlocks when processing validator updates for certain methods. This PR fixes this along with adding in a regression test.
N.A

Fix Multivalue Slice Deadlock

---

beacon-chain/blockchain/receive_block.go
testing/spectest/shared/common/forkchoice/builder_test.go

We typically do not attempt to sync the same block twice but this validation is done in the sync package. When we broadcast a block we call `ReceiveBlock` directly. Forkchoice returns early, but the whole validation is performed twice. This PR returns early from `ReceiveBlock` if the block is already found in forkchoice.

Return early from ReceiveBlock if already sycned

---

testing/endtoend/component_handler_test.go
testing/endtoend/components/lighthouse_beacon.go
testing/endtoend/components/lighthouse_validator.go

Bug Fix
If we want to run builders in a multiclient E2E setup it will panic due to improper initialization paths. This fixes it 
so that we can test builder paths in a multiclient test setup.
N.A

Fix Builder Testing For Multiclient Runs

---

cmd/prysmctl/deprecated/checkpoint/latest.go
cmd/prysmctl/deprecated/checkpoint/save.go
validator/accounts/accounts_import.go

This PR fixes improper error string formatting. According to the Go best practices outlined in the [Error Strings](https://github.com/golang/go/wiki/CodeReviewComments#error-strings) documentation, error strings should not be capitalized or end with punctuation marks. They might be embedded within other strings or concatenated with additional context.

Refactor Error String Formatting According to Go Best Practices

---

beacon-chain/sync/rpc_beacon_blocks_by_root.go

Fixes #13101
If the requested and returned blob sidecars lengths don't match, the node will become stuck at ReceiveBlock due to the DA check. In this update, we verify the lengths and fail the process entirely if they mismatch. The node will automatically attempt to request the block again after 4 seconds.

Check return and request lengths for blob sidecar by root

---

beacon-chain/sync/validate_blob.go

This PR logs blob's kzg commitment at sync. It makes the logging more useful in the event of equivocating blob or blob that later fails reference validation

Log blob's kzg commmitment at sync

---

beacon-chain/sync/pending_blocks_queue.go

Add context deadline for pending queue's receive block function. It's currently set to two slots

Add context deadline for pending queue's receive block

---

beacon-chain/core/altair/sync_committee.go
beacon-chain/core/altair/sync_committee_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/core/transition/transition_test.go
beacon-chain/rpc/prysm/v1alpha1/beacon/assignments_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go

Bug fix
Prevents a divide by zero panic
Fixes #13051

Add zero length check on indices during NextSyncCommitteeIndices

---

beacon-chain/rpc/eth/debug/structs.go

Bug fix
https://github.com/prysmaticlabs/prysm/pull/13099 had a bug in `PendingAttestationFromConsensus` - `Data` field is always nil

Fill state attestations

---

beacon-chain/blockchain/receive_blob.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go

Ensure the blob index is not duplicated before sending it to the blob notifier. This resolves an issue observed in devnet10. The trigger involves writing the blobs to a specific channel and subsequently calling `ReceiveBlock` within the same goroutine.

Check blob index duplication for blob notifier

---

testing/endtoend/evaluators/beaconapi_evaluators/beacon_api.go

Tests
The `/node/peers/{peer_id}` endpoint is very flaky. Even though we request one of the peers obtained through `/node/peers`, it often fails with
> Evaluation failed for epoch 1: prysm request failed with response code: 500 with response body map[code:%!s(float64=500) message:Could not obtain ENR: could not serialize nil record]
This results in post-submit e2e failures. This PR removes testing the endpoint for the time being.

Remove `/node/peers/{peer_id}` from Beacon API evaluator

---

WORKSPACE

Other
Zig release 0.11.0 does not work for Mac OSX users on Sonoma. 
Fixes #13130
It is known that these nightly releases are only available for 90 days. I've uploaded these to
mirror on prysmaticlabs.com so that we have an alternative link in the event that these assets are
deleted from the zig builds site.

zig: Update zig to recent main branch commit

---

beacon-chain/sync/pending_blocks_queue.go

Bug Fix
In #13114, we introduced a context deadline for pending blocks. However it could lead to a valid block being marked as invalid if the context exceeds its deadline. In order to not trigger this we shift the deadline to outside the method to allow for the correct context to be used here.
Found by Antithesis

Fix Pending Queue Deadline Bug

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/rpc_beacon_blocks_by_range.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_blob_sidecars_by_range.go
beacon-chain/sync/rpc_send_request.go
config/params/BUILD.bazel
config/params/mainnet_config.go
config/params/mainnet_config_test.go
config/params/network_config.go

Fixes #12998
This PR added a helper to unify `MaxRequestblock` and `MaxRequestBlockDeneb` given an epoch

Add a helper for max request block

---

beacon-chain/state/stategen/mock_test.go
beacon-chain/state/stategen/replayer.go
beacon-chain/state/stategen/replayer_test.go

This PR optimizes the ReplayBlocks function to exit early when the difference (diff) is zero, reducing unnecessary processing and logs. This change is prompted by observing no-op behavior in logs when diff equals zero.
```
Nov 17 07:51:54 t beacon-chain[13351]: time="2023-11-17 07:51:54" level=debug msg="Replaying canonical blocks from most recent state" diff=0 endSlot=7784357 prefix=state-gen startSlot=7784357
Nov 17 07:51:54 t beacon-chain[13351]: time="2023-11-17 07:51:54" level=debug msg="Finished calling process_blocks on all blocks in ReplayBlocks" duration=27.879µs prefix=state-gen
```

Optimize `ReplayBlocks` for Zero Diff

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/receive_block.go

Lock RecentBlockSlot and move it to chain_info where all other forkchoice accessers are  located.

lock RecentBlockSlot

---

beacon-chain/sync/validate_beacon_blocks.go

Do not ignore block when the only error is in logging the time of arrival.

Accept block when error is only in logging

---

cmd/beacon-chain/storage/BUILD.bazel
cmd/beacon-chain/storage/options.go
cmd/beacon-chain/storage/options_test.go

Bug Fix
In #13190, we introduced a separate blob storage database along with a new path for it. Unfortunately the beacon node option had a bug with it whereby the wrong path for blob storage would always be initialized an used. This PR fixes that along with adding in a respective regression test.
N.A

Fix Blob Storage Path

---

validator/client/beacon-api/json_rest_handler.go
validator/client/beacon-api/json_rest_handler_test.go

Bug fix
After https://github.com/prysmaticlabs/prysm/pull/13203 was merged, post-submit REST VC e2e started failing:
```
FAIL: TestEndToEnd_MinimalConfig_WithBuilder_ValidatorRESTApi (74.91s)
--- FAIL: TestEndToEnd_MinimalConfig_WithBuilder_ValidatorRESTApi/chain_started (60.00s)
```
There were 2 mistakes in the mentioned PR:
- `resp == nil` check added at the beginning, when it's OK to emit `resp` if the endpoint doesn't return any data
- treating `200 OK` as an error in case of non-JSON responses
This PR fixes both issues and adds extensive tests to `decodeResp` function. The failing e2e passes after these changes.

Fix handling POST requests in the REST VC

---

beacon-chain/p2p/pubsub.go
beacon-chain/p2p/pubsub_tracer.go

Bug Fix
In #13226 , we added additional metrics to improve granularity of pubsub metric collection. However one change introduced a deadlock, this PR reverts that change.
N.A

Fix Deadlock With Subscriber Checker

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go

This PR updates Prysm Proposer endpoints to use builder APIs
- `getBuilderPayloadAndBlobs` returns `builderKzgCommitments`
- `setExecutionData` inputs `builderKzgCommitments` and will set builder kzg commitments to the block body along side execution 
- added tests to test functionalities of above

Update Prysm Proposer end points for Builder API

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/receive_attestation_test.go

Use forkchoice to verify FFG/LMD consistency of attestations instead of resorting to database and loop lookups.

Verify lmd without ancestor

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/doubly-linked-tree/store_test.go
beacon-chain/forkchoice/interfaces.go

Same idea as #13257 but by adding a new helper `TargetRootForSlot`. This makes `VerifyLmdFfgConsistency` cleaner and can be used for the attester server

Fix FFG LMD Consistency Check (Option 2)

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go

Other
When a blobstorage directory was created without Prysm's strict permissions requirement, an
unhelpful message is displayed.
```
...
{"addr":"http://127.0.0.1:6060/debug/pprof","message":"Starting pprof server","severity":"INFO"}
{"message":"Finished reading JWT secret from /secret/authrpc/jwt.hex","severity":"INFO"}
dir already exists without proper 0700 permissions
```
Now the error message is more clear.
```
failed to create blob storage at /tmp/beacon/blobs: dir already exists without proper 0700 permissions
```
None reported yet.
Also included regression test :muscle:

blobstorage: Improve mkdirall error 

---

beacon-chain/db/filesystem/blob_test.go
io/file/fileutil.go
io/file/fileutil_test.go

Other
In some deployments, file mode 770 is set by the infrastructure. Namely, using kubernetes fsGroup
will modify the directory permissions to 770. This ought to be fine for a directory and does not
pose and significant security risk.

io/file: Relax file permissions enforcement on existing directory

---

beacon-chain/db/filesystem/blob.go

Bug fix
This PR fixes two things:
1. It's not a good idea to `defer` in a loop, as this can lead to resource exhaustion. In this situation, we may run out of file descriptors when pruning as they are held until the function returns. If there 1000 folders, this may become a problem.
2. While not actually a problem because golang handles it appropriately, I prefer to use `filepath.Join()` rather than joining strings with slashes manually, like `bs.fs.Open(folder.Name() + "/0." + sszExt)` does.

Prevent possible resource exhaustion when pruning blobs

---

beacon-chain/db/filesystem/blob.go

> Bug fix
This PR ensures that the partial file is deleted if there's an error saving. For example, if we attempt to save the same blob at the same time (race condition) and `Rename` returns an error. Just being extra defensive.
Worth noting, the deferred removal is queued before the file is created so it should always cleanup. The return value is ignored because it is expected to return an error if everything is successful (because the file won't exist).
Fixes #13287

Ensure partial blob is deleted if there's an error

---

beacon-chain/rpc/eth/blob/handlers_test.go
beacon-chain/rpc/lookup/blocker.go
beacon-chain/rpc/lookup/blocker_test.go

Bug fix
Fixes the error response on empty blob return, should return an empty array now.  adds some unit tests to cover the specific case.
Fixes #13134

Beacon API: fix get blob returns 500 instead of empty

---

validator/client/BUILD.bazel
validator/client/beacon-api/index.go
validator/client/validator.go

Bug fix
The `validatorIndex` function compared the error returned from the API client with a gRPC status code to handle the case when an index is not found. The REST endpoint doesn't return such a status code, and because of this `validatorIndex` always fails for unknown pubkeys when the REST client is used. This PR creates a custom error in the REST API client and checks against it inside `validatorIndex`.

Gracefully handle unknown validator index in the REST VC

---

testing/endtoend/endtoend_test.go

Bug Fix
This fixes some race failures in e2e by only running the evaluator in the middle of an epoch.
N.A

Run Evaluator In the Middle Of An Epoch

---

beacon-chain/rpc/eth/events/events.go

Other
The way our event feed works is that it copies events to all subscribers and blocks if any subscriber is full. This means that if there is a very slow reader, its channel, which currently has a buffer size of 1, will quickly get full and all other subscribers will be blocked. This PR increases the buffer to 1000, meaning that the event feed will stop producing events only when a single subscriber reaches 1000 pending events. Given that the size of all events is very small, it's unlikely to happen.

Increase buffer of events channel

---

beacon-chain/blockchain/log.go
beacon-chain/blockchain/receive_block.go

This PR ensures that the DA wait time is excluded from the chain service processing time calculation. The rationale for this change is that the `isDataAvailable` function, which is responsible for the DA wait time, does not perform any validation but merely waits. Therefore, it is appropriate to exclude its duration from the processing time of the chain service. This adjustment provides a more accurate measure for log and metric

Excluse DA wait time for chain processing time

---

beacon-chain/db/filesystem/blob.go

Minor cosmetic improvement to not log `purning old blobs` unless we are actually pruning

Move pruning log to after retention check

---

beacon-chain/sync/rpc_blob_sidecars_by_range.go

> Bug fix
This is a really interesting bug that I'm surprised errcheck didn't identify. The error from `newBlockRangeBatcher` isn't checked. This could actually be exploited to crash Prysm with a nil pointer dereference.
https://github.com/prysmaticlabs/prysm/blob/1123df7432f2fa36c69a1c7022ced7b08385c0ed/beacon-chain/sync/rpc_blob_sidecars_by_range.go#L93-L97
If an attacker sends a BlobSidecarsByRange request with the start slot greater than the current slot, it will return a `rangeParams` with `size: 0`.
https://github.com/prysmaticlabs/prysm/blob/1123df7432f2fa36c69a1c7022ced7b08385c0ed/beacon-chain/sync/rpc_blob_sidecars_by_range.go#L149-L153
When `newBlockRangeBatcher` gets this, it will return `nil, someErr` …

Handle potential error from newBlockRangeBatcher

---

beacon-chain/blockchain/receive_blob.go
beacon-chain/db/filesystem/blob.go
beacon-chain/sync/initial-sync/blocks_fetcher.go

Bug fix
Another `makezero` finding. This PR fixes the initialization of `missStr` so that it behaves as expected.
Also, fix two minor typos I noticed that aren't worthy of their own PR.

Fix error string generation for missing commitments

---

beacon-chain/rpc/eth/validator/handlers_block.go
beacon-chain/rpc/eth/validator/handlers_block_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Bug fix
Fixes two issues that cause the linked bug to happen:
- full block production in Beacon API should set `SkipMevBoost` to `true` because we don't want to receive blinded blocks from relays when producing full blocks
- `BuildBlockParallel` didn't use the `req.SkipMevBoost` field. I believe this is a local testing artifact from a previous PR.
I also updated Beacon API tests.
Fixes #13259

Use `SkipMevBoost` properly during block production

---

hack/workspace_status_ci.sh
tools/prysm_image.bzl

Bug fix
Docker images uploaded by CI automatically were missing the git commit.
Also adds a oci label for the image source. I thought that was a fun addition so I added it.

Fix version string in automated docker images

---

.golangci.yml
api/client/builder/client.go
api/client/errors.go
testing/endtoend/components/web3remotesigner.go
testing/endtoend/evaluators/beaconapi/util.go
validator/web/handler.go

Other
This PR enables the [`usestdlibvars`](https://golangci-lint.run/usage/linters/#usestdlibvars) (use standard library variables) linter in golangci-lint.

Enable usestdlibvars linter and fix findings

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/cache/BUILD.bazel
beacon-chain/cache/attestation_data.go
beacon-chain/cache/attestation_data_test.go
beacon-chain/cache/common.go
beacon-chain/cache/error.go
beacon-chain/cache/skip_slot_cache.go
beacon-chain/rpc/core/BUILD.bazel
beacon-chain/rpc/core/service.go
beacon-chain/rpc/core/validator.go
beacon-chain/rpc/eth/validator/BUILD.bazel
beacon-chain/rpc/eth/validator/handlers_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/attester_mainnet_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
beacon-chain/rpc/service.go

Alternate Implementation to #13286 and #13256
This proposal introduces a modified caching strategy for single attestation entries, implementing stricter controls on the RPC behavior.
- Check if the current slot matches the request slot. If not, the service is not provided (New behavior).
- If a cached entry exists for the same slot, the committee index is appended to it.
- If no relevant cached entry is present, retrieve the necessary data from the fork choice once, and cache it, replacing the existing cached attestation.

Use a cache of one entry to build attestation

---

beacon-chain/blockchain/process_block.go
beacon-chain/cache/proposer_indices.go
beacon-chain/cache/proposer_indices_disabled.go
beacon-chain/cache/proposer_indices_test.go
beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go

This PR removes an LRU cache and moves to a cache that keeps maps indexed as
epoch -> state root -> proposer indices. 
They are updated in the same places as before and they are pruned on each update.

use different keys for the proposer indices cache

---

beacon-chain/db/filesystem/metrics.go
beacon-chain/node/node.go

Other
This may help with troubleshooting.
We are seeing an occasional failure to start with an EOF error.
```
time="2023-12-19 08:48:18" level=debug msg="Pruning old blobs"
unable to start beacon node: EOF
```
Ideally, these error wrappings will give some more hints to where the issue is occurring.

Enhance errors from blobstore.Initialize

---

beacon-chain/execution/engine_client.go
beacon-chain/execution/log_processing.go
beacon-chain/execution/service_test.go
beacon-chain/rpc/prysm/v1alpha1/beacon/attestations.go
beacon-chain/verification/cache_test.go

I found few typos, mostly in error messages printer to the user.
Doesn't require testing or changelog entry.

beacon-chain: Fixing typos

---

beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block.go
consensus-types/blocks/getters.go

Retrieve block value correctly only under specific versions or else you will log warning messages like `failed to retrieve execution payload` or `failed to retrieve value in gwei` when proposing a block for phase0 or altair or bellatrix

Use block value correctly when proposing a block

---

beacon-chain/state/state-native/getters_state.go
beacon-chain/state/state-native/state_trie_test.go

Bug Fix
For deneb states we do not initialize the inactivity scores field correctly when initializing the state object from the proto object. This breaks for any node running with the experimental state feature and will lead to nodes not being able to start up from deneb onwards.
N.A

Initialize Inactivity Scores Correctly

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go

Log the value of the local payload when proposing. This is a low volume log in Debug level

Log value of local payload when proposing

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/tracked_proposer.go

This PR is the first of a series modifying the interaction with the engine. In this PR we fix the underlying problem with Payload ID cache misses and shuffling cache misses at the epoch boundary. 
The main issue is that the following events happen currently when importing block 63 and we are proposing at slot 64:
- We validate the block and insert it in forkchoice
- We call FCU, this call eventually calls to get the payload attribute for the next block proposal. This itself performs an epoch transition and processes the slot for the current state. 
- We then call to update the shufflings, this again performs an epoch transition and recomputes the shufflings!
In addition to this, during the call to get the payload attributes, in order to find out if the next proposer is being tracked by …

update shuffling caches before calling FCU on epoch boundaries

---

api/client/builder/client_test.go
beacon-chain/p2p/types/BUILD.bazel
beacon-chain/p2p/types/object_mapping.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/sync/rpc_chunked_response_test.go
consensus-types/blocks/factory_test.go
consensus-types/blocks/getters.go
consensus-types/blocks/getters_test.go
consensus-types/blocks/proto.go
consensus-types/blocks/proto_test.go
consensus-types/blocks/setters.go
consensus-types/blocks/types.go
consensus-types/interfaces/beacon_block.go
consensus-types/mock/block.go

This PR removes the `blind` field from the block type.
Having a `blind` field as part of the block type has proven to be error-prone. This requires the caller to manually set the field before assigning the execution data, which could be either header or payload. There's no necessity for setting this field to determine the block type. In fact, whether the block is blind or not can be discerned by examining if it's using a header or a payload.
```go
func (b *SignedBeaconBlock) IsBlinded() bool {
return b.version >= version.Bellatrix && b.body.executionPayload == nil
}
```
We revise the logic so that a block is considered blinded if its version is greater than Bellatrix and the execution payload is `nil`. This change simplifies the code by eliminating the need for `SetBlinded`, thereby …

Remove blind field from block type

---

beacon-chain/blockchain/process_block.go
beacon-chain/cache/proposer_indices.go
beacon-chain/cache/proposer_indices_test.go
beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go

This PR removes the unused unsafe proposer indices cached an epoch in advance as they are no longer used. This still caches the committee duties in advance in the background. 
Review this incrementally after #13383 has merged

Remove unsafe proposers

---

beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/forkchoice_update_execution_test.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/cache/proposer_indices.go
beacon-chain/cache/proposer_indices_test.go
beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go

This PR starts the process of gradually simplifying FCU
It removes the responsibility of getting the state and block from this
function and informing if head has changed. It is only called when the
imported block has actually become head.
Please review incrementally after #13383

Simplify fcu 1

---

cmd/validator/flags/flags.go
cmd/validator/main.go
cmd/validator/usage.go
validator/client/service.go
validator/client/validator.go
validator/node/node.go

Other
Initially, the VC flag `--validator-registration-batch-size` was named like this to be consistent with Lighthouse.
Unfortunately, it is quite inconsistent with others Prysm flags. See:
```
--tls-cert value                                                                                   Certificate for secure gRPC. Pass this and the tls-key flag in order to use gRPC securely.
--validators-external-signer-public-keys value [ --validators-external-signer-public-keys value ]  comma separated list of public keys OR an external url endpoint for the validator to retrieve public keys from for usage with web3signer
--validators-external-signer-url value …
```

`--validatorS-registration-batch-size` (add `s`)

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/process_block.go
consensus-types/payload-attribute/getters.go
consensus-types/payload-attribute/getters_test.go
consensus-types/payload-attribute/interface.go

This PR decouples `getPayloadAttributes` from the FCU call, making it the responsibility of the calller to pass them. In subsequent PRs we will call FCU with and without attributes multiple times during the same slot.

Remove getPayloadAttributes from FCU call

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/execution_engine_test.go
beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/process_block.go
time/slots/slottime.go
time/slots/slottime_test.go

This PR consists of two independent commits. The first one changes the signature of `getPayloadAttributes`. Since the payload ID cache has changed, a call to get the payload attributes should already know that the validator is being tracked. There is no need to return the boolean. The second commit unifies the different arguments for `forkchoiceUpdateWithExecution` and `notifyForkchoiceUpdate`. In a subsequent PR the first funciton will be completely removed. 
Please review after #13399

Simplify fcu 2

---

beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go

This PR removes the `getPayloadAttribute` call from `updateForkchoiceWithExecution`. It makes the logic of `postBlockProcess` strictly uglier but it makes it possible to decouple the calls to FCU from the calls to update the NSC and perform epoch transition, which will come in the next PR. 
Please review after: #13400

Remove the getPayloadAttribute call from updateForkchoiceWithExecution

---

testing/endtoend/helpers/helpers.go

E2E Improvement
In each e2e run along with CPU and heap profiles, we also fetch the goroutine trace of the individual beacon nodes. This is done so that in the event we have deadlocks in the beacon node during a run, we are able to correctly capture them.
N.A

Fetch Goroutine Traces in E2E Too

---

beacon-chain/db/filesystem/metrics.go
beacon-chain/node/node.go

This PR initializes blob storage without pruning, recognizing that it should rely on normal pruning once we start saving blobs. In my opinion, we don't need to worry about reclaiming disk space until we actually begin using it.

Initialize blob storage without pruning

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/core/helpers/validators.go
time/slots/slottime.go

This PR breaks the calling of FCU during block insertion in two parts. One without payload attributes, regardless if we are proposing or not, and another with payload attributes as is done asynchronous after the block has been inserted. 
FCU is called in three places in our codebase
1. On Block insertion
2. 4 seconds into the slot if no block has been seen
3. When checking for attestations at 10 seconds and right before proposing. 
2 and 3 are unchanged: we always check for the proposer to see if it's tracked and we send with attributes. This is safe since 2. updates the next slot cache and the shuffling, and 3 happens after 2 has already done this. 
1. Is trickier: if we get a block late, then there' s no change, we lock, update the caches and perform all epoch transitions necessary and …

Simplify fcu 4

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

Feature
similar to notifying blocks, when blobs are broadcasted ( triggered from rpc) we should send an event.
continuing off of https://github.com/prysmaticlabs/prysm/pull/13315
https://github.com/ethereum/beacon-APIs/issues/348

Add rpc trigger for blob sidecar event

---

beacon-chain/forkchoice/doubly-linked-tree/node.go
beacon-chain/forkchoice/doubly-linked-tree/node_test.go
beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks_test.go

This computes the voting window at runtime instead of hardcoding it at 4 seconds.

Don't hardcode 4 seconds in forkchoice

---

beacon-chain/rpc/eth/shared/BUILD.bazel
beacon-chain/rpc/eth/shared/request.go
beacon-chain/rpc/eth/shared/request_test.go
beacon-chain/rpc/eth/validator/BUILD.bazel
beacon-chain/rpc/eth/validator/handlers_block.go
beacon-chain/rpc/eth/validator/handlers_block_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
proto/prysm/v1alpha1/BUILD.bazel
proto/prysm/v1alpha1/validator.pb.go
proto/prysm/v1alpha1/validator.proto

Feature
Implements the query parameter `builder_boost_factor` used for `[/eth/v3/validator/blocks/{slot}](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Validator/produceBlockV3)`
description from beacon apis
```
Percentage multiplier to apply to the builder's payload value when choosing between a builder payload header and payload from the paired execution node. This parameter is only relevant if the beacon node is connected to a builder, deems it safe to produce a builder payload, and receives valid responses from both the builder endpoint and the paired execution node. When these preconditions are met, the server MUST act as follows:
if exec_node_payload_value >= builder_boost_factor * …
```

adding builder boost factor to get block v3

---

beacon-chain/db/filesystem/blob.go

Description:
This PR addresses improvements in the logging behavior of our blob pruning process. The current log output includes repetitive entries and lacks efficiency in conveying meaningful information, particularly in a goroutine context. 
**Current Log Output:**
- Multiple entries of "DEBUG Pruning old blobs" without significant status changes.
- Logs of "DEBUG Pruned old blobs" even when `numberBlobsPruned` is 0, leading to unnecessary verbosity.
**Proposed Changes:**
1. **Remove Redundant Log Entries**: Eliminate the repetitive "DEBUG Pruning old blobs" messages. These do not provide meaningful status updates and clutter the log.
2. **Conditional Logging for 'Pruned old blobs'**: Alter the logging condition to omit the "DEBUG Pruned old blobs" entry when `numberBlobsPruned` equals …

Enhance blob pruning log

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go

If a folder lacks a blob with index 0, the following error will persist indefinitely. Therefore, we should examine all potential blobs and prune accordingly.
```
[2024-01-05 09:41:51] ERROR failed to prune blobs from slot 267809 error=failed to process folder 0xc55288171d8ba959d1614327e20df7f11cb0742eadec907ba48fee19ad7b2157: open /Users/t/devnet12/blobs/0xc55288171d8ba959d1614327e20df7f11cb0742eadec907ba48fee19ad7b2157/0.ssz: no such file or directory
```

Prune dangling blob

---

beacon-chain/operations/attestations/BUILD.bazel
beacon-chain/operations/attestations/kv/BUILD.bazel
beacon-chain/operations/attestations/kv/aggregated.go
beacon-chain/operations/attestations/kv/aggregated_test.go
beacon-chain/operations/attestations/prepare_forkchoice_test.go
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Makes aggregating unaggregated attestations from our attestation pool in parallel the permanent default. This particular feature has been running for a few months as our default, therefor it is a good time to make it our permanent default.
N.A
Requires #13406 to be merged in beforehand

Make Aggregating In Parallel The Permanent Default

---

beacon-chain/node/node.go

Bug fix
The sync package should use the ROForkchoice type to ensure it only accesses fast forkchoice methods in a threadsafe fashion.  Background on ROForkchoice: https://github.com/prysmaticlabs/prysm/pull/13244

Use ROForkchoice in blob verifier

---

beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/verification/blob.go
beacon-chain/verification/blob_test.go
beacon-chain/verification/cache.go
beacon-chain/verification/cache_test.go
beacon-chain/verification/initializer.go

This PR fills in the current proposer cache stub from the verification package to use the proposer index cache in the validator core helpers.

Use proposer index cache for blob verification

---

beacon-chain/db/filesystem/BUILD.bazel
beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go
beacon-chain/db/filesystem/ephemeral.go
beacon-chain/db/filesystem/metrics.go
beacon-chain/db/filesystem/pruner.go
beacon-chain/db/filesystem/pruner_test.go
beacon-chain/node/node.go

The pruning routine appears to consume a ton of disk or syscall resources on some systems. We can make it a lot lighter by choosing different methods of filesystem traversal that use more efficient syscalls and caching the results of previous root->slot lookups.

minimize syscalls in pruning routine

---

beacon-chain/das/cache.go
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/rpc_beacon_blocks_by_range.go
consensus-types/blocks/roblock.go
container/trie/sparse_merkle.go
testing/util/deneb.go

Bug fix
This PR fixes a mistake which will reprocess `BlockWithBlobs` that have already been processed. I believe this is an accident, but the error handling for `errBlockAlreadyProcessed` gives me some doubts.
* Replace `data.bwb` (processed & unprocessed) with `bwb` (unprocessed).
* Remove switch case for handling already processed block; this is impossible now, right?
https://github.com/prysmaticlabs/prysm/blob/0e043d55b4e71257d40675903c38b0940723f8ac/beacon-chain/sync/initial-sync/round_robin.go#L162-L176
Also, unrelated to the primary purpose of this PR:
* Fix a few typos.
* Update a few comments to fix function names.
* Redo error format string that I find a little awkward.
* Replace `parent` with …

Only process blocks which haven't been processed

---

cmd/beacon-chain/usage.go

Bug fix 
No functional change.
New `--help` output:
```
...
interop OPTIONS:
--genesis-state value           Load a genesis state from ssz file. Testnet genesis files can be found in the eth2-clients/eth2-testnets repository on github.
--interop-genesis-time value    Specify the genesis time for interop genesis state generation. Must be used with --interop-num-validators (default: 0)
--interop-num-validators value  Specify number of genesis validators to generate for interop. Must be used with --interop-genesis-time (default: 0)
deprecated OPTIONS:
--db-backup-output-dir value  Output directory for db backups.
```
I do not remove this flag not to break compatibility.
An other PR in documentation will remove the …

BN: Move  `--db-backup-output-dir` as a deprecated flag.

---

validator/accounts/cli_manager.go
validator/client/beacon-api/beacon_api_beacon_chain_client.go
validator/client/beacon-api/beacon_api_node_client.go
validator/client/beacon-api/beacon_api_validator_client.go
validator/client/beacon-api/json_rest_handler.go
validator/client/beacon-api/json_rest_handler_test.go
validator/client/beacon-api/prysm_beacon_chain_client.go
validator/client/beacon-chain-client-factory/beacon_chain_client_factory.go
validator/client/node-client-factory/node_client_factory.go
validator/client/service.go
validator/client/validator-client-factory/validator_client_factory.go
validator/rpc/BUILD.bazel
validator/rpc/beacon.go

Other
Changes how we depend on `JsonRestHandler` by reusing the same dependency between several clients.

Use a single rest handler

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_helpers.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/service.go
beacon-chain/core/feed/state/events.go
beacon-chain/rpc/eth/events/BUILD.bazel
beacon-chain/rpc/eth/events/events.go
beacon-chain/rpc/eth/events/structs.go
beacon-chain/rpc/eth/light-client/handlers.go
beacon-chain/rpc/eth/light-client/handlers_test.go
beacon-chain/rpc/eth/light-client/helpers.go
beacon-chain/rpc/eth/light-client/structs.go
config/features/config.go
config/features/flags.go

Feature
** What does this PR do? Why is it needed?**
Implements the Altair spec logic defined in this version:
https://github.com/ethereum/consensus-specs/tree/208da34ac4e75337baf79adebf036ab595e39f15/specs/altair/light-client
It also implements the relevant endpoints specified at https://github.com/ethereum/beacon-APIs
Specifically, this PR adding light client event sub/pub for `optimistic update` and `finalized update`
https://github.com/prysmaticlabs/prysm/pull/11815
Partially addresses https://github.com/prysmaticlabs/prysm/issues/11571
This PR is a follow up to https://github.com/prysmaticlabs/prysm/pull/11815 which was too big to be reviewed. This is the third PR in a series of 5 that I will be …

[3/5] light client events

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/setup_test.go
beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go

Simultaneously delete invalid blobs and blocks during block processing. Since a block might not have an associated blob, logging blob deletion failures at the debug level is appropriate. Note that this is a rare occurrence.

Delete invalid blob at block processing

---

beacon-chain/core/deneb/upgrade.go
beacon-chain/core/deneb/upgrade_test.go

Correctly set historical roots when upgrading Capella state to Deneb state

Use correct HistoricalRoots

---

beacon-chain/operations/attestations/prepare_forkchoice.go

`Aggregated Unaggregated Attestations` is the only log I've seen that's not capitalized. Consistency will be nice here

Capitalize Aggregated Unaggregated Attestations Log

---

beacon-chain/blockchain/process_block.go

In the happy case, validators will not propose the next block. In such scenarios, we will return early due to `attribute.IsEmpty()` being true, eliminating the need to call `s.headBlock()` unless the validator is proposing the next slot. This approach avoids an unnecessary block copy.
Note to the reviewer: Please exercise caution when reviewing any locking mechanisms in this PR, particularly the fork choice lock and head lock. It appears that `s.getPayloadAttribute` may not require locking, but kindly verify this to ensure accuracy.

Late block: move checking of empty attribute earlier

---

beacon-chain/sync/pending_attestations_queue.go
beacon-chain/sync/pending_attestations_queue_test.go
beacon-chain/sync/pending_blocks_queue.go

Currently, if a block's parent or attestation head vote is not in the database, the beacon node logs a request message for it. This message can be either "**Requesting block for pending attestation**" or "**Requesting parent block**"'. However, these logs are misleading because they are generated before the requested root is filtered by `s.seenPendingBlocks[r] || s.cfg.chain.BlockBeingSynced(r)`. It would be more accurate to log these messages after applying the filter. Although logging later in the function means losing information like `attSlot`, `attCount`, or `slot`, these details are likely irrelevant for a debug log, and changing the debug log format should not be a concern...

Enhance block by root log

---

beacon-chain/rpc/eth/blob/structs.go

Bug fix
Renames the blob sidecar field containing the inclusion proof from `commitment_inclusion_proof` to `kzg_commitment_inclusion_proof`, which is the field name in the [beacon API specification](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlobSidecars).
Hive was complaining and failing all tests when it came to verifying the blob sidecars from the beacon node, but I've tested with this change and test are not failing anymore due to this issue.
No issue number for this afaik.
There are other uses of `commitment_inclusion_proof` but I did not want to touch anything else that was unnecessary.

Fix KZG commitment inclusion proof tag in blob sidecar JSON RPC response

---

beacon-chain/core/altair/epoch_precompute.go
beacon-chain/core/altair/epoch_precompute_test.go
beacon-chain/rpc/eth/rewards/handlers.go
beacon-chain/rpc/eth/rewards/handlers_test.go
beacon-chain/rpc/eth/rewards/structs.go
testing/spectest/shared/altair/rewards/rewards_penalties.go
testing/spectest/shared/bellatrix/rewards/rewards_penalties.go
testing/spectest/shared/capella/rewards/rewards_penalties.go
testing/spectest/shared/deneb/rewards/rewards_penalties.go

Feature
Implements https://github.com/ethereum/beacon-APIs/pull/340. 
In order to return the inactivity penalty, I added an `InactivityPenalty` field to the `AttData` struct and split out its value from `TargetPenalty`.
On the API side, apart from adding the `Inactivity` field I removed the `InclusionDelay` field. This is because we currently don't support it and it might be confusing to the caller to see a `"0"` value instead of what they are expecting. Not returning this field makes it clear that it's not supported.

Return activity penalty from attestation rewards

---

testing/endtoend/evaluators/BUILD.bazel
testing/endtoend/evaluators/slashing.go
testing/endtoend/evaluators/slashing_helper.go
testing/endtoend/minimal_slashing_e2e_test.go

Bugfix, Re-enables the Slasher E2E Test. 
In a nutshell, slashing was flaky because the other beacon node doesnt get a chance to propose. See https://github.com/prysmaticlabs/prysm/issues/12415#issuecomment-1874643269 for more details.
Fixes #12415
Tests ran 50 times locally:
```
[57 / 107] 1 / 1 tests; Testing //testing/endtoend:go_default_test (run 50 of 50); 115s darwin-sandbox
Target //testing/endtoend:go_default_test up-to-date:
bazel-bin/testing/endtoend/go_default_test_/go_default_test
INFO: Elapsed time: 5804.892s, Critical Path: 120.36s
```
There are 2 commits to this PR:
1. Commit 1 introduces the bare minimum fix by copy-pasting and duplicating the relevant parts in the …

Re-enable Slasher E2E Test

---

beacon-chain/verification/blob.go
beacon-chain/verification/blob_test.go

Bug Fix
For blobs we validate that the parent is descended from the last finalized checkpoint. However our blob validation pipeline required that the parent blocks were canonical which is different from what is in the specification and what has been implemented similarly for block validation.
This PR fixes that condition along with its test.
N.A

Fix Blob Parent Descendant Check

---

tools/pcli/main.go

Cleanup
This adds in a debug state transition method which allows us to compare post-state diffs better.
N.A

Add Debug State Transition Method

---

beacon-chain/p2p/message_id.go
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/validate_bls_to_execution_change.go

Bug fix
* Small fix in `postAltairMsgID` which used the wrong domain when calculating length; was using `ValidSnappy` in length calculation and using `InvalidSnappy` later. It doesn't make a difference though because both domains are the same length, four bytes. Just fixing to fix.
* Fix a typo in a comment about blob requests.
* The primary reason for this PR: check that `blsChange.Message` isn't `nil` before derefencing it. The gossip topic message validators, like this one, will recover from any panic. So Prysm won't crash, but it will print an annoying panic stack trace to the console.

Fix minor issue in blsToExecChange message validator

---

beacon-chain/sync/validate_aggregate_proof.go
beacon-chain/sync/validate_aggregate_proof_test.go
beacon-chain/sync/validate_beacon_attestation.go

This PR implements https://github.com/ethereum/consensus-specs/pull/3552 by adding the following gossip verifications for aggregated attestation:
```
- [REJECT] The committee index is within the expected range -- i.e. `aggregate.data.index < get_committee_count_per_slot(state, aggregate.data.target.epoch)`.
- [REJECT] The number of aggregation bits matches the committee size -- i.e. len(aggregate.aggregation_bits) == len(get_beacon_committee(state, aggregate.data.slot, aggregate.data.index)).
- [REJECT] The aggregate attestation has participants -- that is, len(get_attesting_indices(state, aggregate.data, aggregate.aggregation_bits)) >= 1.
```
The check to ensure the 'committee index is within the expected range' has been moved to occur after the retrieval of the target state, to prevent …

Align aggregated att gossip validations

---

beacon-chain/rpc/eth/debug/handlers_test.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go

Bug fix
the wrong route was used for the debug forkchoice rest endpoint, this PR fixes that and organizes the tests to align with the specs
Fixes #13500

fixing route to match specs

---

WORKSPACE
config/params/testnet_holesky_config.go

Reference: https://github.com/eth-clients/holesky/pull/94

Add Holesky Deneb Epoch

---

beacon-chain/rpc/lookup/BUILD.bazel
beacon-chain/rpc/lookup/blocker.go

Other
protect users by responding with a generic error when there is one while accessing blobs, users will need to look at server logs for specifics.
Fixes #13505

Blob API: make errors more generic

---

beacon-chain/sync/rpc_send_request.go
beacon-chain/sync/rpc_send_request_test.go

We already perform sufficient checks to ensure that we safely handle RPC responses, but we can improve efficiency by performing some checks closer to the rpc network reads. This is a proof of concept to show the direction we can move, more refactoring is needed to move the entire blob validation chain to this point.

Start validating blobs closer to RPC response reader

---

testing/endtoend/evaluators/validator.go

Test Improvement
Reduces the required participation rate to bring down flakes
N.A

Lower Participation Rate For Multiclient Runs

---

beacon-chain/sync/validate_beacon_blocks.go

Cleanup
In this PR, we cleanup our `validateBeaconBlock` method and instead group all the different validity conditions by fork. All the phase 0 conditions are grouped into their own method.
N.A

Cleanup Validate Beacon Block

---

beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go

Skip origin root when cleaning dirty state

---

beacon-chain/sync/backfill/BUILD.bazel
beacon-chain/sync/backfill/service.go
beacon-chain/sync/backfill/service_test.go
beacon-chain/sync/backfill/status.go
beacon-chain/sync/backfill/worker.go
cmd/beacon-chain/BUILD.bazel
cmd/beacon-chain/main.go
cmd/beacon-chain/sync/backfill/BUILD.bazel
cmd/beacon-chain/sync/backfill/flags/BUILD.bazel
cmd/beacon-chain/sync/backfill/flags/flags.go
cmd/beacon-chain/sync/backfill/options.go
cmd/beacon-chain/usage.go
config/features/BUILD.bazel
config/features/flags.go
testing/endtoend/components/beacon_node.go

E2E Improvement
This enables backfill for our E2E runs by adding it to our `dev` mode.
N.A

Enable Backfill in E2E

---

beacon-chain/rpc/eth/validator/handlers.go
beacon-chain/rpc/eth/validator/handlers_test.go

Bug fix
While running the REST VC, many times signature aggregation failed with the `Could not get matching attestation` error, even though the aggregator did send a matching attestation for the slot. In the implementation of the same functionality in v1alpha1 we don't aggregate first, but we try to find a matching aggregated att first, and then an  unaggregated one as a fallback. After implementing the same behavior, there are no more errors observed.

Fetch unaggregated atts in `GetAggregateAttestation`

---

beacon-chain/sync/validate_beacon_blocks.go

These metrics should be displayed as ms not ns

Correct metrics from ns to ms

---

cmd/beacon-chain/flags/base.go

Sets the blob rate limit 2x higher than currently deployed goerli nodes. This ramps up the speed of syncing without going over the rate limits of currently deployed nodes.

set limit to multiple of burst for goerli

---

cmd/beacon-chain/flags/base.go

Reverts prysmaticlabs/prysm#13544
Discussed offline that the original change does not solve a problem we detected in testnets.

Revert "set limit to multiple of burst for goerli"

---

validator/accounts/accounts_helper.go

Other
a size was not passed for promptui resulting in only 5 public keys displayed while using voluntary exits, this PR adds a log to print recommendations and allows the user to use promptui with more than 5 keys.

validator exiting ux improvement, add a log and update size for promptui

---

beacon-chain/db/slasherkv/schema.go
beacon-chain/db/slasherkv/slasher.go
beacon-chain/slasher/chunks.go
beacon-chain/slasher/detect_attestations.go
beacon-chain/slasher/detect_attestations_test.go
beacon-chain/slasher/detect_blocks.go
beacon-chain/slasher/detect_blocks_test.go
beacon-chain/slasher/helpers.go
beacon-chain/slasher/params.go
beacon-chain/slasher/receive.go
beacon-chain/slasher/receive_test.go
beacon-chain/slasher/service.go

**Please read this PR commit by commit. Some commit messages contain a lot of information.**
Bug fix
Commits with commit message ending by `NFC` (no functional changes) do not contain any functional change.
Fixes:
- #13550 in commit https://github.com/prysmaticlabs/prysm/pull/13549/commits/27565903583a01e212ff8c83353cc429ce3a0351
- #13551 in commit https://github.com/prysmaticlabs/prysm/pull/13549/commits/c33ec19da396927c03ffbe7b21ea5c197ad1a406

Beacon node slasher improvement

---

validator/rpc/intercepter.go
validator/rpc/intercepter_test.go

Bug fix
Fix check on jwt for validator

handle slice out of range

---

beacon-chain/sync/rpc_blob_sidecars_by_root.go

Revised log messaging to clarify scenarios where a node, despite having the blob sidecar locally, encounters an error serving it to a peer due to the sidecar not being found in the database

Revise blob sidecar not found log

---

beacon-chain/sync/validate_attester_slashing.go
beacon-chain/sync/validate_attester_slashing_test.go
beacon-chain/sync/validate_proposer_slashing.go
beacon-chain/sync/validate_proposer_slashing_test.go

Bug Fix
In the event we receive an old slashing message we should ignore and drop it rather than outrightly rejecting it. This is to allow nodes running slashers to not be penalized.
N.A

Fix Slashing Gossip Checks

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

This fixes the following bug:
The node is about to propose block N+1. It syncs block N, based on N-1, and is late, the node head remains being N-1 and will attempt a reorg. If at the beginning of the slot N+1 the node N has shown to be strong, the node relents and starts building a local payload immediately on top of N. 
The node obtains the blockroot of N from forkchoice and requests the corresponding state advanced to N+1. 
If the node **also** has a cache miss (in the NSC) then the node will advance the **head** state to N+1. Here's the bug since this would produce the state based from N-1, instead of N as we want. 
cc @nisdas

Get the right head state when proposing a failed reorg

---

beacon-chain/rpc/eth/blob/BUILD.bazel
beacon-chain/rpc/eth/blob/handlers_test.go
beacon-chain/rpc/lookup/blocker.go
beacon-chain/rpc/lookup/blocker_test.go
beacon-chain/rpc/service.go

Bug fix
fixes the [/eth/v1/beacon/blob_sidecars/{block_id}](https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Beacon/getBlobSidecars) endpoint to handl the additional cases below correctly without a 500 error. currently, we will try to use the root even if the block doesn't exist which doesn't correctly handle all our cases.
- block exists, no commitment, 200 w/ empty list
- block exists, has commitments, inside retention period (greater of protocol- or user-specified) serve then w/ 200 unless we hit an error reading them. we are technically not supposed to import a block to forkchoice unless we have the blobs, so the nuance here is if we can't find the file and we are inside the protocol-defined …

Beacon API: get blob fix retention cases

---

beacon-chain/sync/BUILD.bazel
beacon-chain/sync/error.go
beacon-chain/sync/rpc.go
beacon-chain/sync/rpc_status.go
go.mod

Cleanup
This PR attempts to suppress unwanted p2p errors from being logged out. Some of these errors are those that come up on occasion from slow/overloaded peers which can overwhelm debug logs. This attempts to reduce them
N.A

Suppress Unwanted P2P Errors

---

beacon-chain/execution/engine_client.go
beacon-chain/execution/engine_client_test.go

Bug Fix
Handles the case where an EL is syncing and cannot provide us with the desired payloads.
Fixes #13566

Handle Syncing Executon Client

---

config/features/deprecated_flags.go

This has been there for one major release. We can remove it now for the next release

Remove deprecated late reorg flag

---

config/features/deprecated_flags.go

This has been there for one major release. We can remove it now for the next release

Remove deprecated aggregate parallel flag

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go
beacon-chain/db/kv/kv.go
beacon-chain/db/slasherkv/kv.go
beacon-chain/node/node.go
validator/db/kv/db.go
validator/db/testing/setup_db.go

Feature
When a user sets `--clear-db` or `--force-clear-db` they are expecting to erase all of Prysm's long
term data. Understandably, the users may expect that blobs are cleared as well. 
Fixes #13547
Also put a `Close()` call in the `ClearDB()` method as every caller was closing the DB anyway. It should be safe to do this. I verified at runtime that this worked OK

db: clear blobs when using --clear-db or --force-clear-db

---

config/features/deprecated_flags.go

These flags have been deprecated since March and June last year. I think it's fine to remove them for V5

Remove deprecated flags: gossip batch registration and registration cache

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go

We use Gwei for all the values in the proposer logs. It'd make sense to align and use Gwei to get header log

Use Gwei for value in get header log

---

beacon-chain/db/slasherkv/slasher.go
beacon-chain/db/slasherkv/slasher_test.go
beacon-chain/slasher/chunks.go
beacon-chain/slasher/detect_attestations.go
beacon-chain/slasher/detect_attestations_test.go
beacon-chain/slasher/process_slashings.go
beacon-chain/slasher/process_slashings_test.go
beacon-chain/slasher/receive.go
beacon-chain/slasher/types/types.go
testing/slasher/simulator/BUILD.bazel
testing/slasher/simulator/attestation_generator.go

Please read this PR commit by commit.
Bug fix
This pull requests fixes 2 bugs:
**Double votes false positive**
- For a given validator, when two different attestations with the same target epochs are received by the slasher **in the same batch**, the slasher detects them as a slashable offence. ==> ✅
- However, for a given validator, when two different attestations with the same target epochs are received by the slasher **in two different batches**, the slasher does **not** detect any slashable offence. ==> ❌. This PR fixes this point.
**Redondant attester slashing objects sent**
When an equivocating attestation is detected, then the same attester slashing object is sent multiple times. The number of copies of the same object depends of the number of …

Slasher: Fixes double votes false positive and attester slashings duplication.

---

validator/accounts/accounts_exit.go

Other
Holesky and sepolia were missing from this list when running a validator exit

validator/exit: Print other testnet beaconcha.in URLs

---

beacon-chain/execution/log_processing.go

Cleanup
This PR cleans up our deposit processing logs with an interval of 1024. 
Fixes #13548 

Clean Up Deposit Processing Logs

---

beacon-chain/db/slasherkv/slasher.go
beacon-chain/db/slasherkv/slasher_test.go
beacon-chain/slasher/detect_attestations.go
beacon-chain/slasher/detect_attestations_test.go

Please read commit by commit, with commit messages.
Bug fix.
Currently, the slasher is unable to detect surrounded votes if corresponding attestations are received in different batches.
This PR fixes this issue.
Fixes https://github.com/prysmaticlabs/prysm/issues/13591

Slasher: Fix surrounded votes false negative

---

proto/eth/v1/events.proto
proto/eth/v2/beacon_lightclient.proto

Fixed warnings for bazel build: 
`proto/eth/v2/beacon_lightclient.proto:19:1: warning: Import proto/eth/v1/attestation.proto is unused`

Rm unused import

---

beacon-chain/rpc/eth/debug/handlers.go
beacon-chain/rpc/eth/debug/handlers_test.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go

Cleanup
Removes an API endpoint that's already removed from the spec

Remove /eth/v1/debug/beacon/states/{state_id}

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/metrics.go
beacon-chain/db/filesystem/pruner.go
beacon-chain/db/filesystem/pruner_test.go

Feature
Adds 2 new gauge metrics, `blob_disk_count`, `blob_disk_bytes` to count the number and size of blob sidecars on disk.
Also changes the spelling of `blobs_written` -> singular `blobs_written` to be consistent with the other blob metrics.
Fixes #13613

metrics for count and size of blob files

---

beacon-chain/node/node.go
beacon-chain/sync/backfill/service.go

Backfill doesn't cooperate with init-sync to preserve rate limit capacity. Making backfill requests concurrently with init-sync requests could be causing peers serving init-sync requests to give init-sync rate limit errors, especially on goerli where some prysm nodes are running with excessively low blob batch limits. We should prioritize init-sync over backfill at node startup so the node can get up to head as soon as possible.
This PR adds a step to backfill service startup to block on the signal that other services use to wait for init-sync to catch up to head for the first time. Backfill won't spawn the worker pool or begin computing batches until node begins gossip syncing at head.

Backfill start after init-sync at head

---

beacon-chain/operations/attestations/metrics.go

Since aggregate parallel has been default, we never updated the bucket values. Aggregate parallel yields ~5-10x im provements. On my node it's always the first bucket:
```
aggregate_attestations_t1_bucket{le="100"} 64229
aggregate_attestations_t1_bucket{le="200"} 64238
aggregate_attestations_t1_bucket{le="500"} 64239
aggregate_attestations_t1_bucket{le="1000"} 64240
aggregate_attestations_t1_bucket{le="1500"} 64240
aggregate_attestations_t1_bucket{le="2000"} 64240
aggregate_attestations_t1_bucket{le="2500"} 64240
aggregate_attestations_t1_bucket{le="3500"} 64240
aggregate_attestations_t1_bucket{le="+Inf"} 64240
Feb 10 16:38:42 t beacon-chain[527495]: time="2024-02-10 16:38:42" level=debug msg="Aggregated unaggregated attestations" Duration=29.257958ms prefix="pool/attestations"
Feb 10 …
```

Update aggregate atts t1 bucket values

---

cmd/beacon-chain/flags/base.go

This has been marked deprecated for a while. It's not used anywhere. Can remove

Remove safe slots to import flag

---

beacon-chain/db/slasherkv/slasher.go
beacon-chain/db/slasherkv/slasher_test.go
beacon-chain/slasher/chunks.go
beacon-chain/slasher/chunks_test.go
beacon-chain/slasher/detect_attestations.go
beacon-chain/slasher/detect_attestations_test.go

Bug fix
Improve slasher cold boot duration.
Before this commit, on a slasher cold boot (aka, without any db),
the `updatedChunkByChunkIndex` function looped for all validators
AND for all epochs between the genesis epoch and the current epoch.
This could take several dozen of minutes, and it is useless since the
min/max spans are actually a circular buffer with a limited lenght.
Cells of min/max spans can be overwritten (with the same value)
plenty of times.
After this commit, the `updatedChunkByChunkIndex` function loops
for all validators AND AT MOST `historyLength` lenght.
Every cell of min/max spans are written AT MOST once.
Time needed for slasher boot goes from `O(nm`) to …

Slasher: Reduce cold start duration.

---

beacon-chain/rpc/eth/beacon/handlers.go
beacon-chain/rpc/eth/beacon/handlers_test.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go

Cleanup
Removes deprecated Beacon API endpoint that's no longer present in the spec.

Remove /eth/v1/beacon/blocks/{block_id}

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
beacon-chain/sync/service.go

Bug fix
There appears to be an edge case where the pending block queue can send a block to ReceiveBlock without requesting blobs first. The pending block broadcast code tries to fetch any necessary blobs before calling ReceiveBlock and broadcasting, but will silently skip the blob fetch if there are no connected peers. ~~I believe this could cause a deadlock when coupled with a Resync.~~ I no longer think there's a deadlock, but it does generally cause the syncing process to get messy and gets the pending block wedged in da check for at least 3 slots before Resync can do its job.
~~This PR also removes blob fetching from the step where the batch of pending blocks is retrieved, deferring that work until broadcast …

Fix pending block/blob zero peer edge case

---

beacon-chain/sync/checkpoint/BUILD.bazel
beacon-chain/sync/checkpoint/api.go
beacon-chain/sync/checkpoint/file.go
beacon-chain/sync/checkpoint/log.go

Cleanup
Makes chekpoint logs and errors consistent with the rest of the system:
- `log.go` file with a common prefixed `log` variable
- uppercase logs

Normalize checkpoint logs.

---

beacon-chain/db/filesystem/BUILD.bazel
beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/log.go
beacon-chain/db/filesystem/pruner.go

Cleanup
Unifies `filesystem` package logging with the rest of Prysm

Normalize filesystem/blob logs

---

beacon-chain/sync/backfill/blobs.go

`blobBatchVerifier` should be a pointer receiver for `VerifiedROBlobs` like `newVerifier`. The value is 2 pointers so this is just an aesthetic issue that shows up as a warning in people's IDE

Fix blob batch verifier pointer receiver

---

beacon-chain/db/filesystem/blob.go

Bug fix
Add some error returning paths when the following bad things happen:
- The blob sidecar produced a zero length byte slice for the SSZ encoded data
- The amount of data saved to disk does not match the length of the ssz encoded data
- The amount of data written was zero bytes (redundant check, probably, but free to verify)
We've found empty blob files on disk and this PR aims to prevent that scenario.

db/blobs: Check non-zero data is written to disk

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go

Bug fix
We have observed blob sidecars being truncated. My theory is that this is due to a race when 2 of the same blob sidecar are concurrently written and the second calls `Create`, which opens the same path with `O_TRUNC`.

avoid part path collisions with mem addr entropy

---

beacon-chain/blockchain/service.go
beacon-chain/execution/service.go
beacon-chain/node/node.go

Cleanup
During node startup, we persist a finalized state that is completely unused. This takes up a non-trivial amount of memory in our heap. In order to be more economical with how much memory the node requires we do not reference this state after its purpose has been carried out.
N.A

Do not Persist Startup State

---

beacon-chain/core/blocks/signature.go
beacon-chain/core/blocks/signature_test.go
beacon-chain/sync/validate_beacon_blocks.go

Optimization
This PR reduces the amount of times we recompute the root of the block. In the `VerifyBlockSignatureUsingCurrentFork` we were needlessly recomputing it again. This is expensive and delays gossip validation across the network.
N.A

Do Not Compute Block Root Again

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go
beacon-chain/node/node.go
beacon-chain/node/options.go
cmd/beacon-chain/storage/options.go
config/features/config.go
config/features/flags.go

Feature
This PR adds a feature flag `--blob-save-fsync`. When this flag is set, the blob storage code will call fsync after writing blob data to the `.part` file, before renaming the part file to the `.ssz` file.
This can be used by node operators who want extra reassurance that zero-length blob files won't be written, particularly in the event of a node restart.

call fsync between part file write and rename

---

beacon-chain/state/state-native/setters_misc.go
beacon-chain/state/state-native/state_test.go
container/slice/slice.go

Optimization
We optimize how we add dirty indices for a particular field. In the event we do hit our indices limit, we attempt to remove duplicates before determining whether or not to rebuild the trie. This helps in prevent us from unnecessarily rebuilding a whole field trie. 
N.A

Optimize Adding Dirty Indices

---

validator/client/log.go

Cleanup
`msg="Submitted sync committee messages successfully to beacon node" messages=0` log is completely useless

Do not log zero sync committee messages

---

beacon-chain/sync/initial-sync/BUILD.bazel
beacon-chain/sync/initial-sync/service.go

Bug fix
With this PR a checkpoint synced node will fetch blobs for the checkpoint sync origin block in initial-sync before entering round robin sync. This ensures that the node can guarantee availability of the checkpoint sync blobs before participating in the gossip protocol.
We could have fetched blobs from the checkpoint sync provider beacon node instead, but this approach seemed more robust, since it doesn't assume public beacon node apis will provide blobs.

Download checkpoint sync origin blobs in init-sync

---

beacon-chain/blockchain/head_test.go
beacon-chain/core/transition/BUILD.bazel
beacon-chain/core/transition/altair_transition_no_verify_sig_test.go
beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
beacon-chain/rpc/eth/builder/handlers.go
beacon-chain/rpc/eth/rewards/service.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_altair.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
beacon-chain/sync/validate_sync_committee_message_test.go
testing/util/helpers_test.go

Other
replace Slot()-1 with slots.PrevSlot call

small cleanup on functions: use slots.PrevSlot

---

WORKSPACE

Bug fix
Builds are broken with missing upstream dependency
```
WARNING: Download from http://security.ubuntu.com/ubuntu/pool/main/libx/libxml2/libxml2_2.9.10+dfsg-5ubuntu0.20.04.6_amd64.deb failed: class java.io.FileNotFoundException GET returned 404 Not Found
```
New machines won't be able to build until this dependency is updated.
See: https://github.com/aspect-build/bazel-lib/issues/769

bazel: Update aspect-build/bazel-lib to v2.5.0

---

beacon-chain/gateway/helpers.go
beacon-chain/node/node.go
beacon-chain/rpc/service.go

Bug fix
There is a race introduced by registering the route at the start of the services within the beacon chain particularly between the rpc service and the grpc gateway service which use the underlying route. under these conditions if the enduser calls an endpoint without a pause at the start of the service a panic may occur. This PR moves the setting of route handlers in the registration instead of when the service starts.
example of an error 
```
2024/02/23 09:24:09 http: panic serving 172.18.0.6:59022: runtime error: invalid memory address or nil pointer dereference
goroutine 214271 [running]:
net/http.(*conn).serve.func1()
GOROOT/src/net/http/server.go:1868 +0xb9
panic({0x42c7e0?, 0x33f1ee0?}) …
```

move setting route handlers to registration from start

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

h/a to Antithesis for reporting this. 
We treat succesful reorgs as failed ones and log them incorrectly. This PR fixes this.

Fix failed reorg log

---

cmd/validator/main.go
validator/node/node.go

Other
If running the VC with, for example, a non-existing `--wallet-password-file`, the most useful information (aka, the error message) is actually the less visible on the screen.
Example:
After this PR, the log message preventing the VC to run is displayed as `FATAL`.
**NOTE:** In such a case, the error code is still non-zero.

VC: Improve logging in case of fatal error

---

beacon-chain/sync/initial-sync/BUILD.bazel
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/service_test.go

Bug fix
If the checkpoint sync origin is outside the blob retention epoch, we will have pruned its blobs. This creates a false positive where we think we need to fetch the blobs, but since they are outside the retention period, we may not be able to get them from peers.
This PR exits the checkpoint block blob fetching routine if the checkpoint block slot is outside the retention period.

exit blob fetching for cp block if outside retention

---

beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks_test.go

When a late block arrives and the beacon is proposing the next block, we perform several checks to allow for the next block to reorg the incoming late block.
Among those checks, we check that the parent block has been heavily attested (currently 160% of the committee size).
We perform this check in these circumstances:
- When the late block arrives
- At 10 seconds into the slot
- At 0 seconds into the next slot (at proposing time)
The problem is that for blocks that arrive between 4 seconds and 10 seconds, the parent block will not have yet this expected weight since attestations from the current committee were not imported yet, and thus Prysm will send an FCU with payload attributes anyway at this time.
What happens is that Prysm keeps the EL building different blocks based on different …

Do not check parent weight on early FCU

---

validator/keymanager/types.go
validator/rpc/BUILD.bazel
validator/rpc/handlers_keymanager.go
validator/rpc/handlers_keymanager_test.go

Bug fix
statuses should be in lowercase for keymanager APIs
note: additional cleanup on keymanager APIs

keymanager api: lowercase statuses

---

beacon-chain/p2p/service.go

> Bug fix found using [Antithesis](https://antithesis.com/)
Fixes a race condition where the underlying `pingMethod` changes while it is being read and vice versa.
```
WARNING: DATA RACE
Read at #HEX by go routine: #DIG:
github.com/prysmaticlabs/prysm/v5/beacon-chain/p2p.(*Service).pingPeers()
beacon-chain/p2p/service.go:361 +0x37
github.com/prysmaticlabs/prysm/v5/beacon-chain/p2p.(*Service).RefreshENR()
beacon-chain/p2p/discovery.go:94 +0xa7a
github.com/prysmaticlabs/prysm/v5/beacon-chain/p2p.(*Service).Start()
beacon-chain/p2p/service.go:218 +0xe24
github.com/prysmaticlabs/prysm/v5/runtime.(*ServiceRegistry).StartAll.func1()
runtime/service_registry.go:46 +0x42
Previous write at #HEX by go routine: #DIG: …
```

fix race condition when pinging peers

---

beacon-chain/rpc/eth/config/handlers_test.go
config/params/config.go
config/params/mainnet_config.go

Other
This seems to be an artifact from early Deneb implementation. The spec has removed this config and
it is no longer required.
See https://github.com/ethereum/consensus-specs/pull/3542

config: Remove DOMAIN_BLOB_SIDECAR.

---

api/client/beacon/BUILD.bazel
api/client/beacon/checkpoint.go
api/client/beacon/client.go
api/client/beacon/log.go
beacon-chain/db/kv/kv.go
beacon-chain/db/kv/wss.go
beacon-chain/execution/rpc_connection.go
beacon-chain/p2p/service.go
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/subscriber.go
cmd/beacon-chain/execution/BUILD.bazel
cmd/beacon-chain/execution/log.go
cmd/beacon-chain/execution/options.go

Other
This PR has two commits:
- The first one fix logs
- The second one fixes (unrelated) deepsource errors.

Improve logging.

---

beacon-chain/execution/block_reader.go
beacon-chain/execution/log_processing.go
beacon-chain/execution/service.go

Other
- Clean up unreachable code inside an if statement with an always-false condition. 
- Use new(big.Int), which is more efficient than big.NewInt(0).
- Use built-in max/min functions, supported since Go 1.21. 
No issues have been fixed in this PR—only code improvement.

chore(execution): Clean up unreachable code; use new(big.Int) instead of big.NewInt(0)

---

beacon-chain/sync/subscriber.go

Bug Fix
In the event we hit a context deadline processing a message, we do not reject that message and penalize the peer. Instead we simply ignore and drop them.
N.A

Ignore Pubsub Messages Hitting Context Deadlines

---

beacon-chain/rpc/core/validator.go
beacon-chain/rpc/eth/validator/handlers_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/attester_mainnet_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go

Currently, the justified checkpoint for attestation is derived from the fork choice store. To ensure maximal safety, the justified checkpoint for attestation should be derived from the head state and process slots across epoch boundaries when necessary.

Use justified checkpoint from head state to build attestation

---

beacon-chain/sync/BUILD.bazel
beacon-chain/sync/subscriber_beacon_blocks.go
config/features/config.go
config/features/flags.go

Add the new flag `--save-invalid-block-temp` to save invalid gossip and received blocks to a temporary folder. This will be useful for the Deneb hard fork happening in one day. The choice of a feature flag and a temporary folder was made for their simplicity and minimal manual intervention. If necessary, we can later switch to a regular flag and a user-specified folder.

Save invalid block to temp `save-invalid-block-temp`

---

beacon-chain/sync/validate_blob.go
config/features/config.go
config/features/flags.go

This PR saves an invalid blob to temp under `--save-invalid-blob-temp`. Here the invalid blob is defined by failing `SidecarKzgProofVerified`, we would still perform the proposer signature beforehand to prevent invalid spamming

Save invalid blob to temp under new flag

---

beacon-chain/sync/metrics.go
beacon-chain/sync/validate_blob.go

This PR adds gossip blob sidecar verification metric. Beacon block gossip already has this

Add gossip blob sidecar verification ms metric

---

beacon-chain/sync/validate_blob.go

`blobSidecarVerificationGossipSummary` was using the arrival time instead of the verification time

Use correct gossip validation time

---

beacon-chain/sync/backfill/batcher.go
beacon-chain/sync/backfill/batcher_test.go
cmd/beacon-chain/sync/backfill/flags/flags.go

Bug fix
Other
This PR fixes a panic that occurs soon after the first backfill batch completes, if the backfill worker count flag is set to 1 (`--backfill-worker-count=1`).
Also, the default value for `--backfill-batch-size` is lowered from 64 to 32, based on testing in mainnet where it was observed that this value led to a healthier mix of peer implementations, due to the higher batch size triggering rate limits more frequently for some peer implementations.

fix 1-worker underflow; lower default batch size

---

beacon-chain/sync/backfill/service.go
beacon-chain/sync/backfill/service_test.go
cmd/beacon-chain/main.go
cmd/beacon-chain/sync/backfill/BUILD.bazel
cmd/beacon-chain/sync/backfill/flags/flags.go
cmd/beacon-chain/sync/backfill/options.go
cmd/beacon-chain/usage.go

Feature
Adds the ability to control the slot where the backfill operation will be marked complete. This flag only allows specifying a slot that is older than `<current_slot> - MIN_EPOCHS_FOR_BLOCK_REQUESTS`. If the specified slot is newer than that, it will be ignored with a warning log. Setting a value of `0` allows backfilling to genesis.
Note that this flag does not change the behavior of the backfill process with regard to blobs. Blobs outside the retention window still will not be downloaded, as nodes may be unable to find peers capable of serving expired blobs and requiring them to be present would create complexities re peer scoring and delay syncing for the majority of nodes that do not need expired blobs.

Backfill min slot flag

---

beacon-chain/db/kv/finalized_block_roots.go
beacon-chain/db/kv/finalized_block_roots_test.go

Bug fix
Fixes an edge case where backfill batch size of 1 leads to backfill status being updated while finalized index is not updated.

handle special case of batch size=1

---

beacon-chain/cache/skip_slot_cache.go
beacon-chain/cache/skip_slot_cache_test.go

Bug Fix
For our skip slot cache, we always set the in-progress boolean for a particular root regardless if it is enabled or disabled. This helps avoid wierd edge cases where the skip slot cache is disabled and then enabled which might lead to wierd deadlocks.

Always Set Inprogress Boolean In Cache

---

beacon-chain/verification/BUILD.bazel
beacon-chain/verification/blob.go
beacon-chain/verification/metrics.go

Feature
The blob verification package uses a proposer signature cache to avoid re-verifying the same signature over the same block root multiple times. This PR adds a metric to keep track of how often this cache has a miss, a hit for a valid signature, and a hit for invalid signatures.

adds a metric to track blob sig cache lookups

---

beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_attestation_test.go

In the event a peer hasn't imported slot 0 and attests for slot 31 as target during slot 0. All prysm nodes that have seen the block in slot 0 and are receiving these attestations, go through the following in `gettAttPrestate`
```
// If the attestation is recent and canonical we can use the head state to compute the shuffling.
headEpoch := slots.ToEpoch(s.HeadSlot())
if c.Epoch == headEpoch {
```
This code path is missed since `c.Epoch > headEpoch`. 
Later in the code we hit:
```
// Do not process attestations for old non viable checkpoints otherwise
ok, err := s.cfg.ForkChoiceStore.IsViableForCheckpoint(&forkchoicetypes.Checkpoint{Root: [32]byte(c.Root), Epoch: c.Epoch})
return nil, errors.Wrap(err, "could not check checkpoint condition in forkchoice")
}
if !ok {
return …
```

Use headstate for recent checkpoints

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go

When proposing a block, if the validator is not in the tracked validators cache, set it's fee recipient from the beacon node.

Set default fee recipient if tracked val fails

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/options.go
beacon-chain/p2p/service.go

Enable Configurable Mplex Timeouts

---

validator/node/node.go
validator/rpc/server.go

Bug fix
Running validator client in rest mode with `--enable-beacon-rest-api` with the web UI causes the following error 
this is due to the beacon API endpoint not being set. by setting these settings during registration it should fix the issue.

validator client should set beacon API endpoint in configurations

---

beacon-chain/blockchain/process_block.go
beacon-chain/sync/service.go

Feature
This changes the DA check so that it will log if the check is running at the end of the slot for the given block, which provides helpful debugging information for blocks with late blobs.

add log message if in da check at slot end

---

validator/rpc/handlers_beacon.go
validator/rpc/handlers_beacon_test.go

Bug fix
Running validator client in rest mode with `--enable-beacon-rest-api` with the web UI causes the following error
This is caused by a poor handling of the query parameters for rest. This PR introduces some fixes.

Fix get validator endpoint for empty query parameters

---

beacon-chain/blockchain/service.go

This proved useless in Goerli and it's a hack that can be safely removed. I suggest we don't merge this PR (marked as blocked) until mass ejection happens in a couple of weeks. 
With the current #13695 merged, nodes follow the chain and the beacon chain db is correct, while the validators are deadlocked. As soon as the chain justifies they will continue attesting. 
If we merge this PR, the beacon nodes will not be able to follow the chain and will continue sending wrong attestations possibly being banned by peers.

Revert "pass justified=finalized in Prater (#13695)"

---

beacon-chain/p2p/parameter_test.go
beacon-chain/p2p/pubsub.go

Bug Fix/ Spec Change
Following on from https://github.com/ethereum/consensus-specs/pull/3627 , we expand the seen ttl to address the extended attestation validity conditions brought about from EIP 7045.
N.A

Expand Our TTL for our Message ID Cache

---

beacon-chain/blockchain/process_block.go

Logging DA block root in hex so it's more readable
`Mar 21 09:23:23 t beacon-chain[1002098]: time="2024-03-21 09:23:23" level=error msg="Still waiting for DA check at slot end." blobsExpected=6 blobsWaiting=6 prefix=blockchain root=[0 227 89 28 9 157 91 149 221 20 236 163 60 205 170 26 210 157 250 150 115 236 122 252 192 154 175 201 86 164 60 51] slot=8684514`

Log da block root in hex

---

beacon-chain/blockchain/process_block.go

The log typically appears in the next slot and it's not clear what block triggered the fault

Log the slot and blockroot when we deadline waiting for blobs

---

tools/cross-toolchain/darwin_cc_hack.bzl

chore: fix some typos

---

validator/client/beacon-api/BUILD.bazel
validator/client/beacon-api/duties.go
validator/client/beacon-api/duties_test.go

Other
This PR reduces the time to fetch duties from ~8-9s to ~2.5s by utilizing wait groups and making concurrent requests. Concurrency is spread between two layers:
1. Fetch duties for current and next epoch concurrently
2. Within each epoch, fetch attester duties, proposer duties, sync committee duties and committees concurrently
Another piece of this PR is a `getValidatorsForDuties` function that is used instead of `multipleValidatorStatus`, This is because the latter does many things that we don't need for duties, including a call to `GetValidatorCount` which currently takes around 250ms on Holesky.

Optimize `GetDuties` VC action

---

beacon-chain/sync/rpc_goodbye.go

Bug fix
I've noticed these rate limit errors on the goodbye topic:
```[2024-03-20 18:11:17] DEBUG sync: Could not handle p2p RPC (ptr) error=rate limited peer=16Uiu2HAm34cymQmtLYvFQJd5jzW1fYE4xcUPyW4LRmBxGhLfsR4U topic=/eth2/beacon_chain/req/goodbye/1/ssz_snappy```
I'm assuming what's happening here is that we rate limit a peer, and they choose to disconnect with us as a result, at which point they can send us a (optional) goodbye message, and we then raise this error saying "you can't call my goodbye rpc, you are rate limited". The problem is this prevents us from correctly handling the disconnect as implemented in the goodbye rpc handler. Since we're about to disconnect the peer with a reconnect backoff anyway, we …

fix handling of goodbye messages for limited peers

---

WORKSPACE
tools/prysm_image.bzl

Other
We do not currently have a nice way to produce a docker tarball that can be loaded via docker load.
This PR fixes that. 
Required for https://github.com/prysmaticlabs/documentation/issues/928

docker: Add bazel target for building docker tarball

---

validator/client/beacon-api/beacon_api_node_client.go
validator/client/beacon-api/beacon_api_validator_client.go
validator/client/beacon-api/genesis.go
validator/client/beacon-api/genesis_test.go
validator/client/beacon-api/wait_for_chain_start_test.go

Other
Throughout the whole time while the validator client is running, it is connected to a beacon node from one and the same network. Although the genesis time of this network is fixed, we request it from the beacon node many times over and over again, which is wasteful, This PR uses a sync primitive called `Once` to make sure that we perform only one API request (allowing another call if the previous failed). We then store the result of this request in a struct field and return it immediately from further invocations of `GetGenesis`.
The result of this change is clearly visible in the below picture, The blue line marks the point at which a validator client running 32 keys was restarted with this PR's changes. For …

Call `GetGenesis` only once

---

beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go

ValidateClock in ValidateAttestationTime is useless
The check is that the attSlot is not > than the currentslot + 128 slots.
Later there's a check that the attSlot start time is not > than current slot start time + clockDisparity.
if attSlot > than currentSlot + 128 slots, then the second check would fail anyway.
The lattest check already guarantees that the attSlot cannot be larger than the currentSlot, therefore it may never happen that attEpoch > currentEpoch. We just need to check for Deneb that attEpoch >= currentEpoch - 1.
Removes also some duplicated variables like the attestation epoch being computed twice.

Simplify ValidateAttestationTime

---

beacon-chain/sync/pending_attestations_queue.go
beacon-chain/sync/pending_attestations_queue_test.go

The current queue will only save 1 unaggregated attestation for a pending block because we wrap the object into a SignedAggregatedAttestationAndProof with a zeroed aggregator. Since the unique callers of this queue already make sure that the objects are not duplicated in the gossip pipeline, we can safely remove the check
This is a bug present since genesis.

Remove check for duplicates in pending attestation queue

---

beacon-chain/sync/metrics.go
beacon-chain/sync/pending_attestations_queue.go

This adds two counters to keep track of how many pending attestations the node has seen

Add metrics to track pending attestations

---

beacon-chain/sync/rpc_goodbye.go

More appropriate for debug given the occurrence and lack of control client can do

Change goodbye message from rate limited peer to debug verbosity

---

beacon-chain/verification/blob.go

Fill in missing debug logs for blob p2p IGNORE/REJECT

---

beacon-chain/p2p/pubsub.go

> Feature
This PR enables [Gossipsub v1.1 "Explicit Peering Agreement](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#explicit-peering-agreements) as discussed in #13635 
Closes #13635 
Explicit peers (called "direct" in the codebase, to follow `go-libp2p-pubsub` convention) are considered also "static" in order to connect with them at startup and persist the connection with them. Then, the peers specified in the CLI option are just passed downstream to pubsub configuration.

Explicit Peering Agreement implementation

---

beacon-chain/db/kv/BUILD.bazel
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/blocks_test.go
beacon-chain/db/kv/error.go
beacon-chain/db/kv/finalized_block_roots.go
beacon-chain/db/kv/finalized_block_roots_test.go
beacon-chain/db/kv/migration.go
beacon-chain/db/kv/migration_finalized_parent.go
beacon-chain/db/kv/state.go
beacon-chain/state/stategen/replay_test.go

Bug fix
#13486 broke the finalized index update process for checkpoints, always setting the parent root equal to the checkpoint root. This PR reverts that commit and adds a migration to repair impacted databases.

Repair idx 13486

---

async/event/feed.go

using slices.IndexFunc

---

container/slice/slice.go

>
> Bug fix
> Feature
> Other
Fixes #

using slices.Contains

---

beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_block_test.go

Bug fix
When sending the finalized event to the event feed we send the root of the _received_ block's state as the finalized state root, but it should be the root of the _finalized_ block's state.
Fixes #13752

Send correct state root with finalization event

---

beacon-chain/node/node.go
beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/config.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/discovery_test.go
beacon-chain/p2p/fork_test.go
beacon-chain/p2p/log.go
beacon-chain/p2p/options.go
beacon-chain/p2p/options_test.go
beacon-chain/p2p/peers/status.go
beacon-chain/p2p/peers/status_test.go
beacon-chain/p2p/service.go
beacon-chain/p2p/service_test.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/subnets_test.go
beacon-chain/p2p/watch_peers.go
beacon-chain/sync/rpc.go
cmd/beacon-chain/main.go
cmd/beacon-chain/usage.go
cmd/flags.go
cmd/prysmctl/p2p/BUILD.bazel
cmd/prysmctl/p2p/client.go
cmd/prysmctl/p2p/request_blobs.go
cmd/prysmctl/p2p/request_blocks.go
config/features/config.go
config/features/flags.go
testing/endtoend/components/beacon_node.go
testing/endtoend/params/params.go
testing/endtoend/params/params_test.go

Feature
This pull request adds the QUIC protocol support. For more information about the QUIC protocol, and how it is supported into libp2p, please checkout [here](https://docs.libp2p.io/concepts/transports/quic/).
This PR adds a new `--p2p-quic-port (default: 13000)` flag.
```
--p2p-quic-port value The QUIC port used by libp2p. (default: 13000)
```
This new feature is hidden behind the `--enable-quic` feature flag:
```
features OPTIONS:
...
--enable-quic                             Enables connection using the QUIC protocol for peers which support it. (default: false)
...
```
P2P ports are now:
```
ALREADY EXISTING:
--p2p-udp-port value   The UDP port used by the discovery service discv5. (default: 12000) …
```

P2P: Add QUIC support

---

beacon-chain/p2p/broadcaster.go

Bug Fix
With EIP7045, attestations are valid from both the current and previous epoch. Our broadcast method chooses to filter out attestations which are beyond 32 slots. With Deneb this would be unnecessarily rejection valid attestations. This PR fixes it.
N.A

Extend Broadcast Window For Attestations

---

testing/endtoend/components/beacon_node.go

Rationale:
The `FindFollowingTextInFile` seems to have troubles with `logrus` fields.

`e2e`: Expected log `Running node with peerId=` -> `Running node with`.

---

config/features/config.go
config/features/flags.go

Feature
This PR implements a feature flag so that all peer das related changes to core code can be put behind a flag. Doing this allows us to be able to experiment on this in an easier fashion along with making this much simpler to modify for any future forks.
N.A

Add PeerDAS Feature Flag

---

beacon-chain/das/cache.go
beacon-chain/das/cache_test.go
beacon-chain/sync/rpc_send_request_test.go
beacon-chain/verification/batch.go
consensus-types/blocks/kzg_test.go
consensus-types/blocks/roblob.go
consensus-types/blocks/roblob_test.go
consensus-types/blocks/roblock_test.go
consensus-types/blocks/types.go

Bug fix
PR #13827 introduced a bug where the data availability check will panic on blocks where some blobs are available locally, due to allocating a list that is too large when not all commitments need to be checked. This PR fixes that bug, adds some unit tests and tightens up some of the ROBlock/Blob constructor logic.
Thanks to @nalepae for noticing the panic in local testing and @prestonvanloon for identifying the fix.

Fix bug from PR 13827

---

beacon-chain/p2p/options.go
testing/endtoend/components/beacon_node.go

Bug Fix
In #13786 , we added QUIC support to prysm. One of the changes included in that was that the peer id would be logged differently. Unfortunately this has broken our E2E setup as it relies on us searching our log file to determine current peer ID. The logging change lead to just a quote `"` being returned. This PR changes it to what it was before.
N.A

Revert Peer Log Changes

---

beacon-chain/rpc/eth/beacon/handlers_validator.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/getters_validator.go

Other
This is a simplified version of https://github.com/prysmaticlabs/prysm/pull/13782, applying `ReadOnlyValidators()` only to Beacon API, which speeds up fetching all validators ~3x

Use read only validators in Beacon API

---

beacon-chain/rpc/eth/node/handlers.go
beacon-chain/rpc/eth/node/handlers_test.go

Other
Our implementation of the https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Node/getHealth endpoint currently returns 200 when the node is optimistically synced. This might be misleading to node operators who will deem the node as ready to serve validators.

Return syncing status when node is optimistic

---

beacon-chain/cache/BUILD.bazel
beacon-chain/cache/column_subnet_ids.go
beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/discovery.go
beacon-chain/p2p/discovery_test.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/service.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/testing/fuzz_p2p.go
beacon-chain/p2p/testing/mock_peermanager.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/sync/subscriber.go

Feature
This PR allows a peer to compute its assigned custody column subnets and record the entries in a cache. Using these values a node can now subscribe to its custodied gossip subnets. The subscription of these subnets requires the implementation and support of the gossip validation pipeline for data columns. This will come up in a follow up PR
N.A

Add Support For Discovery Of Column Subnets

---

beacon-chain/db/filesystem/blob_test.go
beacon-chain/db/filesystem/mock.go
beacon-chain/db/filesystem/pruner_test.go
beacon-chain/rpc/lookup/blocker_test.go

Other
Trivial change to remove a useless error return so callers don't need to handle it.

Don't return error that can be internally handled

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_sidecar.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/core/blocks/signature.go
beacon-chain/core/feed/operation/events.go
beacon-chain/p2p/discovery_test.go
beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/p2p/pubsub_filter_test.go
beacon-chain/p2p/topics.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/decode_pubsub.go
beacon-chain/sync/service.go
beacon-chain/sync/subscriber.go
beacon-chain/sync/subscriber_data_column_sidecar.go
beacon-chain/sync/validate_data_column_sidecar.go

Feature
This PR adds in support for data column gossip validation. It initializes the validation pipelines for data columns and adds in the respective subscriber. This will allow a peerDAS enabled node to subscribe to data columns. The only things left out are the validation of kzg inclusion proofs and kzg proofs which depend on #13877 . 
This PR also doesn't handle the column event handling in `blockchain`. That will be addressed in a future PR
Fixes #

Add Data Column Gossip Handlers

---

testing/endtoend/evaluators/beaconapi/verify.go
testing/endtoend/params/params.go

Post-submit e2e is broken because the health check call uses the wrong constant. This constant does not take test shards into account. Apart from fixing this, the PR changes the visibility of constants that should not be used outside of the `params` package.

Use correct port for health check in Beacon API e2e evaluator

---

beacon-chain/p2p/discovery_test.go

Bug fix
DNS record has changed for example.org causing tests to fail.
A longer term fix might be changing this to a domain record prysm controls

Change example.org DNS record

---

beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/beacon_committee_test.go
beacon-chain/core/helpers/private_access_fuzz_noop_test.go
beacon-chain/core/helpers/private_access_test.go
beacon-chain/core/helpers/randao_test.go
beacon-chain/core/helpers/rewards_penalties_test.go
beacon-chain/core/helpers/sync_committee.go
beacon-chain/core/helpers/sync_committee_test.go
beacon-chain/core/helpers/validators_test.go

Other
I started doing this as part of #13903, but probably won't need it there. 
In any case, I think it's a good pattern to adopt so I'm propose these changes here. The gist is
that the tests should call the imported package as if it were using the public API. There are some
test setups that require access to the private caches. Therefore, a privace_access_test.go is added
to surface package private methods or members to the tests.

Refactor beacon-chain/core/helpers tests to be black box

---

testing/spectest/utils/utils.go

Bug fix
I noticed that an invalid spectest directory will pass successfully. This PR prevents that.

spectests: fail hard on missing test folders

---

beacon-chain/db/filesystem/blob.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/rpc_topic_mappings.go
beacon-chain/p2p/service.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/testing/fuzz_p2p.go
beacon-chain/p2p/testing/mock_peermanager.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/p2p/types/rpc_errors.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/rpc.go
beacon-chain/sync/rpc_chunked_response.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/rpc_send_request.go

Feature Work
This PR implements our p2p request and response handlers for data columns. This will allow prysm nodes to serve saved data columns as well as requesting them for sampling from other peers. As done with the other methods, this will all be toggled under the peerdas flag.
N.A

Add Request And Response RPC Methods For Data Columns

---

encoding/ssz/BUILD.bazel
encoding/ssz/htrutils.go
encoding/ssz/htrutils_test.go

Feature
Required for translations of ExecutionPayloadElectra -> ExecutionPayloadHeaderElectra
See #13919 & #13903 for use cases

Electra: HTR util for DepositReceipt and ExecutionLayerWithdrawalRequest

---

.bazelrc

Build Fix
Fixes builds for peerDAS branch by running optimized builds by default. Our default paths were not able to link our ckzg lib correctly. This is a workaround till our default paths have no issues compiling ckzg
N.A

Use optimized builds by default

---

consensus-types/blocks/execution.go
consensus-types/blocks/factory_test.go
consensus-types/blocks/getters.go
consensus-types/blocks/getters_test.go
consensus-types/blocks/types.go
consensus-types/interfaces/BUILD.bazel
consensus-types/interfaces/beacon_block.go
consensus-types/interfaces/cast.go
consensus-types/interfaces/error.go
consensus-types/interfaces/error_test.go
consensus-types/mock/block.go

Other
Demonstrates how we can start splitting interfaces up per-fork and use interface assertions to add getters across forks without updating the structs for all previous forks.

demo fork-specific interface

---

beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_sidecar.go
beacon-chain/blockchain/setup_test.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/core/feed/operation/events.go
beacon-chain/core/peerdas/helpers.go
beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/monitoring.go
beacon-chain/p2p/pubsub.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/testing/fuzz_p2p.go
beacon-chain/p2p/testing/mock_broadcaster.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/server.go
beacon-chain/rpc/prysm/v1alpha1/validator/unblinder.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/service.go
beacon-chain/sync/subscriber_blob_sidecar.go
beacon-chain/sync/subscriber_data_column_sidecar.go
beacon-chain/sync/validate_data_column.go
config/features/config.go
consensus-types/blocks/BUILD.bazel
consensus-types/blocks/rodatacolumn.go
consensus-types/blocks/types.go

Feature
A lot of tests have still to be implemented. (Tagged with `TODO: Add tests`)

Implement peer DAS proposer RPC

---

consensus-types/blocks/execution.go
consensus-types/blocks/factory.go
consensus-types/blocks/factory_test.go
consensus-types/blocks/getters.go
consensus-types/blocks/getters_test.go
consensus-types/blocks/types.go
consensus-types/interfaces/BUILD.bazel
consensus-types/interfaces/beacon_block.go
consensus-types/interfaces/cast.go
consensus-types/interfaces/error.go
consensus-types/interfaces/error_test.go
consensus-types/mock/block.go

Other
This brings back the changes from https://github.com/prysmaticlabs/prysm/pull/13928 that got lost in the shuffle of various electra branches.
The goal of this PR is to deprecate the following patterns:
- monolithic block body interface across all forks. This model requires all non-phase0 attributes getters to return an error that must be checked.
- monolithic ExecutionData interface. In addition to the unsupported getter error checking issue, these types also require new getters to be backported to every previous fork.
In place of these patterns, we can use interface composition to add a new interface at each fork. The ExecutionData version for a particular fork can be accessed with a vanilla go type assertion. …

Fork-specific consensus-types interfaces

---

WORKSPACE
beacon-chain/rpc/eth/config/handlers_test.go
config/params/config.go
config/params/mainnet_config.go

Spectest: v1.5.0-alpha.1

---

beacon-chain/state/state-native/state_test.go
beacon-chain/state/stateutil/validator_map_handler.go

`Copy` for `ValidatorMapHandler` is not used. When a state is copied, it points to the same reference. It's better to remove an unused method to prevent future misuse.

Remove unused validator map copy method

---

beacon-chain/core/blocks/attester_slashing.go
beacon-chain/core/blocks/proposer_slashing.go
beacon-chain/core/validators/BUILD.bazel
beacon-chain/core/validators/slashing.go
beacon-chain/core/validators/slashing_test.go
beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go

Feature
This PR comes with some minor refactoring. 
- tests in beacon-chain/core/validators are blackbox tests
- instead of requiring switch statements from the caller, the correct parameters are derived from within slash_validator using the state version.
Part of #13903
Tracking @ #13849
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.2/specs/electra/beacon-chain.md#updated-slash_validator

eip-7251: Updated slash_validator

---

beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/blocks_test.go
beacon-chain/db/kv/key.go
beacon-chain/db/kv/schema.go
beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go
encoding/ssz/equality/BUILD.bazel
encoding/ssz/equality/deep_equal.go
testing/util/electra_state.go

This PR adds electra changes to db. Mainly two things and a note
1.) Add electra block support
2.) Add electra state support
3.) Refactor `saveStatesEfficientInternal` into multiple helpers. The functionality remains the same. It needs to be done to reduce cognitive complexity or CI will be red

Add electra DB

---

beacon-chain/p2p/fork_watcher.go
beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/p2p/gossip_topic_mappings_test.go
beacon-chain/p2p/pubsub_filter.go
beacon-chain/p2p/types/object_mapping.go

This PR adds p2p support for Electra

Add p2p support for Electra

---

consensus-types/blocks/testing/factory.go
testing/util/block.go
testing/util/merge.go
validator/client/propose.go
validator/client/propose_test.go

This PR adds proposer support for Electra. Blind block is not handled. It can be addressed in a later PR

Add proposer suppot for Electra

---

beacon-chain/core/electra/consolidations.go

In Go, if you range over a nil slice, it behaves like an empty slice. The loop body will not execute because there are no elements to iterate over. This means that the program won't panic or throw an error. 
For a beacon block, if the block does not contain any consolidation, the field is nil by default. This is similar to attestation and other deposit objects. We should not cause the state transition function to fail, as that would result in a consensus failure. Another approach to altering this behavior involves how the block is initialized; if the object is nil in p2p, we initialize an empty list instead of nil, but this warrants a more significant change.

Ignore `[]*ethpb.SignedConsolidation` if it's nil

---

beacon-chain/blockchain/kzg/BUILD.bazel
beacon-chain/blockchain/kzg/trusted_setup.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_data_column.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/core/peerdas/BUILD.bazel
beacon-chain/core/peerdas/helpers.go
beacon-chain/core/peerdas/helpers_test.go
beacon-chain/db/filesystem/cache.go
beacon-chain/db/filesystem/cache_test.go
beacon-chain/node/node.go
beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/gossip_scoring_params.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/service.go
beacon-chain/sync/validate_data_column.go
config/features/config.go
consensus-types/blocks/kzg.go
testing/endtoend/components/beacon_node.go
testing/endtoend/endtoend_setup_test.go
testing/endtoend/evaluators/metrics.go

Testing Addition
This PR enables E2E and also addresses the respective bugs found in our e2e run.
Current Bugs Fixed:
Fixes #

Enable E2E For PeerDAS

---

beacon-chain/execution/engine_client.go
consensus-types/payload-attribute/getters.go

This ensures we can call FCU with the correct attribute post Electra

Support version Electra for ForkchoiceUpdated

---

consensus-types/blocks/getters.go
consensus-types/blocks/getters_test.go

Block getter `Attestations()` returns non-Electra attestations even if the block version is Electra. This PR ensures the correct version of attestation is returned with a unit test.

Correctly return electra attestations for block getter

---

.buildkite-bazelrc

Other
The remote downloader enables CI to cache remote downloads and save on bandwidth consumption.
Related: https://github.com/bazel-contrib/rules_oci/issues/292
We should update that issue if this PR merges successfully and is not reverted after a few days.

CI: Enable experimental_remote_downloader

---

beacon-chain/p2p/discovery.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/sampling_data_columns.go

Bug Fix
We marshal the custody count correctly as an 8-byte slice instead of 1. 
N.A

Set Custody Count Correctly

---

beacon-chain/p2p/encoder/BUILD.bazel
beacon-chain/p2p/encoder/ssz_test.go

Other (adds fuzzer)
This PR adds a new fuzzer for testing ssz roundtrip coding. It is needed to increase test coverage.
None
Incorporates earlier feedback from private PR.

Fuzz ssz round trip

---

api/client/beacon/health.go
api/client/beacon/health_test.go

Bug fix
`bazel test //... --@io_bazel_rules_go//go/config:race` detected multiple race conditions present in our code base. 
This PR fixes the race condition detected in `TestNodeHealth_Concurrently`.

Fix TestNodeHealth_Concurrently race condition

---

beacon-chain/rpc/prysm/v1alpha1/validator/construct_generic_block_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
consensus-types/blocks/get_payload.go
consensus-types/primitives/wei.go
consensus-types/primitives/wei_test.go

Bug fix
Well this isn't a bug yet but it probably would be someday. I defined a package var for `ZeroWei` to serve in places where we need a default value for a `primitives.Wei` which is an alias for a `*big.Int`, but since this is a reference type it seems dangerous to share a pointer value that something could accidentally mutate. So this simple PR converts that value to a func.

Convert ZeroWei to a func (avoid shared pointer)

---

beacon-chain/sync/initial-sync/blocks_fetcher.go
consensus-types/primitives/slot.go

Another "not a bug, yet" change. I found this commit in a branch on my laptop. I meant to commit it in the PR where these blob request filtering methods were added but it got left out. Essentially I want to add this additional option for avoiding slot underflows, because it's good to be paranoid and prevent panics when subtracting slots, but it's also silly to have to handle errors when the underflow should be impossible based on other invariants. In this case the list of blocks has to be sorted by slot by p2p validation rules, so we should never fool the request bound calculation into picking a high slot lower than low slot, but this change makes sure that if some bug is introduced that breaks that invariant we at least won't panic.
Bug fix

paranoid underflow protection without error handling

---

validator/client/runner_test.go
validator/client/testutil/mock_validator.go

Bug fix
`bazel test //... --@io_bazel_rules_go//go/config:race` detected multiple race conditions present in our code base. 
This PR should fix all the race condition detected in `validator/client/runner.go`.

Fix race conditions in `validator/client/runner.go`

---

beacon-chain/core/electra/BUILD.bazel
beacon-chain/core/electra/effective_balance_updates.go
beacon-chain/core/electra/effective_balance_updates_test.go
testing/spectest/mainnet/electra/epoch_processing/BUILD.bazel
testing/spectest/mainnet/electra/epoch_processing/effective_balance_updates_test.go
testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
testing/spectest/minimal/electra/epoch_processing/effective_balance_updates_test.go
testing/spectest/shared/electra/epoch_processing/BUILD.bazel
testing/spectest/shared/electra/epoch_processing/effective_balance_updates.go

Feature
Required for electra. 
Extracted from #13903.
Tracking @ #13849
https://github.com/ethereum/consensus-specs/blob/v1.5.0-alpha.2/specs/electra/beacon-chain.md#updated-process_effective_balance_updates

eip-7251: process_effective_balance_updates 

---

validator/client/validator.go

Other
If for whatever reason we are unable to check if the validator is an aggregator, instead of failing and not assigning any roles we should assume the validator is not an aggregator, log the error and continue. That way the validator will be able to get other rewards for the slot.

Only log error when aggregator check fails

---

beacon-chain/rpc/eth/validator/handlers.go
beacon-chain/rpc/eth/validator/handlers_test.go

#14039 fixed several issues related to duty retrieval. One key fix was to avoid heavily mutating the state for retrieving the beacon state proposer. However, after merging the PR, we realized it broke long-running end-to-end tests for the beacon API.
```
helpers.go:242: time="2024-05-24 19:14:42" level=error msg="error getting validator duties" error="failed to get duties for next epoch `1`: failed to get attester duties for epoch `1`: HTTP request unsuccessful (500: Could not get dependent root: could not get block root: slot 0 out of bounds)" prefix=client
```
Currently, getting the dependent root does not work in the genesis case. A genesis state does not have any dependent root when requesting at slot 0, as demonstrated by these two test cases:
```
func Test_attestationDependentRoot(t …
```

Fix dependent root retrival genesis case

---

beacon-chain/rpc/eth/validator/handlers.go

The issue we encountered during the long-running e2e post-summit is as follows:
- The caller requests duties for epoch 1 at the end of epoch 0
- In this case, we still use the genesis state even if the requested epoch is 1
- We should use the genesis root for the dependent root if the requested epoch is 1

Fix dependent root retrieval for first epoch

---

beacon-chain/rpc/eth/beacon/handlers.go
beacon-chain/rpc/eth/beacon/handlers_test.go
beacon-chain/rpc/eth/rewards/handlers.go

Bug fix
`s.Blocker.Block(ctx, []byte(blockId))` can return a nil block which results in a panic below. this happens when you request for a block you haven't synced yet. Adding checks in the appropriate places.
Fixes #[14061](https://github.com/prysmaticlabs/prysm/issues/14061)

api fix for panic on unsynced unfound block

---

beacon-chain/core/altair/transition.go
beacon-chain/core/altair/transition_test.go
beacon-chain/core/electra/transition.go
beacon-chain/core/transition/altair_transition_no_verify_sig_test.go
beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
beacon-chain/core/transition/transition.go
beacon-chain/state/stategen/replay.go

h/t Seamonkey for pointing out a regression from #14001.
If the `ProcessEpoch` function returns an error, the state is `nil` by default. We can't use that to get the state version, or it will panic as seen below:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x468 pc=0x37a1d60]
goroutine 607921584 [running]:
github.com/prysmaticlabs/prysm/v5/beacon-chain/core/transition.ProcessSlots({0x1b5eb88?, 0xc10910b1f0?}, {0x1b8abe8, 0xc10de18700}, 0x1b16a0)
beacon-chain/core/transition/transition.go:263 +0xba0
github.com/prysmaticlabs/prysm/v5/beacon-chain/core/transition.UpdateNextSlotCache({0x1b5eb88, 0xc10910b1f0}, {0xc07f7ffea0, 0x20, 0x1ed738942d8c?}, {0x1b8abe8?, 0xc05b936a80?})
```
This PR fixes the caller …

Process epoch error to use correct state version

---

beacon-chain/db/filesystem/BUILD.bazel
beacon-chain/db/filesystem/blob.go
beacon-chain/sync/decode_pubsub.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/subscriber_beacon_attestation.go

Please read commit by commit.
When receiving a `dataColumnByRoot` requests, this pull request replaces the 100 ms polling by a event system, produced by the database.
In the following scenario:
1. We custody all the columns
2. When a peer sends us a `dataColumnByRoot`, it wants to retrieve the following columns: `[20 58 83 91 96 102 116 123]`
3. However, column `123` is not (yet) available
4. Once the column is available, we move on
```
...
["2024-05-30 15:22:13"]  DEBUG sync: "Received data column sidecar by root request" custodied=[0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 …
```

PeerDAS: Implement / use data column feed from database.

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
config/features/config.go
config/features/flags.go

This PR introduces the **hidden** `--data-columns-withhold-count` flag.
When set to a non null `i` value, the block proposer will withhold all the data columns with index `< i`.
The main purpose of this flag is to test the correctness of the reconstruction either in E2E tests or in interop with Kurtosis.

PeerDAS: Withhold data on purpose.

---

beacon-chain/sync/data_columns_reconstruct.go

Fix:
```
["2024-05-30 15:15:19"]  ERROR sync: "Panic occurred" error="runtime error: index out of range [4] with length 4" recoveredAt=subscribeWithBase stack="goroutineruntime/debug.Stack()
```

`recoverBlobs`: Cover the `0 < blobsCount < fieldparams.MaxBlobsPerBlock` case.

---

beacon-chain/db/filesystem/pruner.go
beacon-chain/db/filesystem/pruner_test.go

Bug fix
`5.0.4-rc.1` has a bug where invalid blobs in blob storage can cause the cache warmup code to fail to close the channel which other users of the cache wait on to indicate the cache is ready. This results in initial-sync (which does not use a timeout when requesting the cache) to hang indefinitely if there are truncated blobs in storage.
This PR fixes the issue by ensuring the sentinel channel is always closed, even if the cache warmup call to the pruning func produces an error.

always close cache warm chan to prevent blocking

---

beacon-chain/sync/data_columns_reconstruct.go

**Before this PR:**
1. If a node custody < 50% of the columns, then no reconstruction happens. The node stores only columns it received via gossip.
2. I a node custody 100% of the columns, and if at least 50% of the columns are received via gossip, then 100% of the columns are reconstructed and 100% of the columns are stored.
3. If a node custody `]50%; 100%[` of the columns, and if at least 50% of the columns are received via gossip,  then 100% of the columns are reconstructed and **100% of the columns are stored.**
`3.` is kind of unexpected since some non custodied columns will be stored.
**After this PR:**
1. No change
2. No change
3. If a node custody `]50%; 100%[` of the columns, and if at least 50% of the columns are received via gossip,  then 100% of the columns are reconstructed …

PeerDAS: Store only custodied columns

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_data_column.go
beacon-chain/core/peerdas/helpers.go
beacon-chain/sync/data_columns_reconstruct.go
beacon-chain/sync/service.go
beacon-chain/sync/subscriber_data_column_sidecar.go
testing/endtoend/components/beacon_node.go

**Definition of a missing column:**
A missing column is a column we should custody but which actually was not received via gossip.
- Columns are reconstructed as soon as 50% of the total columns are available.
- Missing columns are gossiped after 3 seconds into the slot. (We can gossip them since we reconstructed them.)
- If reconstruction is done later than 3 seconds into the slot, then missing columns are gossiped immediately.
When a block proposer withhold on purpose a data column, this log is displayed:
```
["2024-06-04 20:08:45"]  WARNING "rpc/validator": "Withholding data column" dataColumnIndex=26 root=0xc4914ff33f7651f18f8e437b5c42689e39c8a06e7585bc1ea42ae2e752c801af subnet=26
```
Then, on a non-proposer node, this log is NOT displayed (since the corresponding data column is not …

PeerDAS: Gossip the reconstructed columns

---

api/client/beacon/health.go
api/client/beacon/health_test.go
api/client/beacon/testing/mock.go

Bug fix
https://github.com/prysmaticlabs/prysm/pull/14033 introduced a subtle race condition. The channel has a buffer size of 1. Previously we unlocked before sending to the channel. This means that if we tried to send a second value, sending to the channel blocked but any other function that required the lock could take it. In the current version this other function will need to wait for the lock. And that's what happened with the REST VC. I don't know how exactly it got to this, but apparently a second value was sent to the channel before reading the first one, which captured the lock. Another function tried to obtain the lock, and reading the first value from the channel depended on this function returning.
To …

Keep only the latest value in the health channel

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/custody.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/discovery_test.go
go.mod

Feature
Rework ENR custody_subnet_count related code
Fixes #

[PeerDAS] rework ENR custody_subnet_count and add tests

---

beacon-chain/rpc/eth/validator/BUILD.bazel
beacon-chain/rpc/eth/validator/handlers.go
beacon-chain/rpc/eth/validator/handlers_block.go
beacon-chain/rpc/eth/validator/log.go

Other
We sometimes see sync committee signature verification failures when trying to get sync committee rewards for a given block. The reason for this bug is still unknown, but failing block production because of such a non-critical thing is too radical.
Fixes #13910
I modified the comment for Phase 0 to explain why we ignore it.

Do not fail production when consensus block value is unavailable

---

beacon-chain/p2p/rpc_topic_mappings.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go

This PR fixes a regression introduced in https://github.com/prysmaticlabs/prysm/pull/14103 and fixed both in https://github.com/prysmaticlabs/prysm/pull/14109 and https://github.com/prysmaticlabs/prysm/pull/14116.
However, none of https://github.com/prysmaticlabs/prysm/pull/14109 or https://github.com/prysmaticlabs/prysm/pull/14116 are able to be merged yet. So this PR only fixes the regression.
Without the fix:
```
["2024-06-18 11:23:41"]  ERROR sync: "Failed to sample data columns" error="sample data column from peer: send data column sidecar by root: send: accompanying message type is incorrect for topic: wanted *types.BlobSidecarsByRootReq  but got *types.DataColumnSidecarsByRootReq"
```

Fix columns sampling

---

validator/accounts/accounts_helper.go

Bug fix
This PR solves a bug to the prysmctl ui where given a list of 20 or more validators the user would be unable to scroll through and select the validators to exit.
This was due to setting a dynamic size of `len(pubKeyStrings)` in the `promptui.Select` statement which set the window size for the interactive selection. This meant that when someone had over 20 keys, the window would be so large that the scrolling would break.
Fixing the window size to 10 items solves the problem on all affected versions of prysm (v5+).
Fixes #14092

Prysmctl ui bug

---

beacon-chain/p2p/iterator.go

Bug Fix
In #14137, we introduced a few things to allow for nodes running in more restrictive operating systems to be able to maintain their peer count. Unfortunately these changes have lead to poorer attestation and sync committee performance, this PR reverts one of those changes which would slow down peer search if we encountered too many non-viable peers. 
N.A

Revert Backoff When Searching For Viable Peers

---

beacon-chain/core/epoch/BUILD.bazel
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/epoch/sortable_indices.go
beacon-chain/core/epoch/sortable_indices_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go

Bug fix
state.Validators() is a full copy of 1M+ validators. By using a series of validator index slices, we can reduce the worst case copy to ~8M bytes ~= 8Mb of indices to process. 
The average case is near zero allocation.
Special shoutout to @terencechain for the idea and the debugging of my implementation.
Soft requirement for #14005.
I moved sortableIndices to its own file and added unit tests for this specifically. The lack of unit tests on this struct cost us nearly a full day of debugging a silly mistake.

process_registry_updates without a full copy of the validator set

---

third_party/README.md

In[ PR#7910](https://github.com/prysmaticlabs/prysm/pull/7910/files#diff-b6cd85961a9400da4aaf7b171890389189819ed30fcfac0860f61450af7da26aL62) , deleted the sections [Updating Patches] and [Ethereum APIs Patch], but the related references were not removed.

fix(third_party): removed internal expired jump targets

---

beacon-chain/operations/attestations/kv/kv.go

h/t to @nerolation for discovering this
We updated the expired helper to work with the Deneb boundary, which now considers the current and previous epochs. The expired helper will only return true if the attestation is older than the previous epoch. Additionally, there is a seen cache that tracks attestations the node has observed using a bitfield. This seen cache operates on a time-based expiration system, expiring entries after 32 slots. However, it has not been updated to align with Deneb behavior. As a result, the seen cache and expired helper do not align perfectly. An old attestation can remain in the pool for over 32 slots and will not be pruned until it is older than the previous epoch. This PR updates seen cache to respect expire boundary

Increase attestation seen cache exp time to two epochs

---

beacon-chain/core/electra/BUILD.bazel
beacon-chain/core/electra/registry_updates.go
beacon-chain/core/electra/registry_updates_test.go
beacon-chain/core/electra/transition.go
testing/spectest/mainnet/electra/epoch_processing/BUILD.bazel
testing/spectest/mainnet/electra/epoch_processing/registry_updates_test.go
testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
testing/spectest/minimal/electra/epoch_processing/registry_updates_test.go
testing/spectest/shared/electra/epoch_processing/BUILD.bazel
testing/spectest/shared/electra/epoch_processing/registry_updates.go

Feature
Required for Electra.
Extracted from #13903.
Tracking @ #13849

eip-7251: process_registry_updates

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/sync_committee.go
beacon-chain/core/altair/sync_committee_test.go

Feature
https://github.com/ethereum/consensus-specs/pull/3783
Updates get_next_sync_committe_indices to use electra max eb.
Reviewers may notice that this is more code branching in prior fork logic, which I have been against. I plan to revisit this after devnet-1 is feature complete.

Electra: updated `get_next_sync_committee_indices`

---

.github/actions/gomodtidy/Dockerfile
.github/workflows/fuzz.yml
.github/workflows/go.yml
.golangci.yml
WORKSPACE
deps.bzl
go.mod
go.sum
testing/endtoend/components/eth1/transactions.go

Build Update
This updates Prysm to Go v1.22.3 . A summary on the changes in this minor version upgrade of golang can be
found [here](https://go.dev/doc/go1.22).
N.A

Update to Go v1.22

---

beacon-chain/core/electra/churn_test.go
beacon-chain/core/electra/consolidations.go
beacon-chain/core/electra/consolidations_test.go
beacon-chain/core/helpers/validators.go
testing/spectest/mainnet/electra/operations/consolidation_test.go
testing/spectest/shared/electra/operations/consolidations.go

Feature
https://github.com/ethereum/consensus-specs/pull/3775

Electra: new `process_consolidation_request`

---

testing/spectest/mainnet/electra/finality/finality_test.go
testing/spectest/mainnet/electra/sanity/blocks_test.go
testing/spectest/shared/electra/rewards/rewards_penalties.go
testing/spectest/shared/electra/sanity/block_processing.go
testing/spectest/shared/electra/sanity/slot_processing.go

Other
Unskips all spectests that are passing without modifications after #14112.

Electra: unskip passing spectests at v1.5.0-alpha.3

---

beacon-chain/p2p/custody.go

Reason: If a peer does not expose its `csc` field into its ENR, then there is nothing we can do.

Move log from error to debug.

---

beacon-chain/core/electra/registry_updates.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/helpers/validators.go

Optimization
Instead of copying a new checkpoint for every single validator, we simply copy it once since it is a static value. This significantly reduces memory allocations in an epoch transition.
N.A

Optimize ProcessRegistryUpdates Further

---

beacon-chain/core/blocks/exit.go
beacon-chain/core/blocks/exit_test.go
testing/spectest/mainnet/electra/operations/voluntary_exit_test.go
testing/spectest/minimal/electra/operations/voluntary_exit_test.go

Feature
Updates process_voluntary_exit to the spec changes at v1.5.0-alpha.3
Introduced in https://github.com/ethereum/consensus-specs/pull/3668

Electra: EIP-7251 Update `process_voluntary_exit`

---

beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/p2p/gossip_topic_mappings_test.go
beacon-chain/sync/decode_pubsub.go

Optimization
Instead of performing a protobuf clone operation from our base message map, we simply replace it with a method which generates a new message each time. Doing this is significantly cheaper rather than an expensive clone operation on an empty message each time.
N.A

Avoid Cloning When Creating a New Gossip Message

---

beacon-chain/core/blocks/exit.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/getters_validator.go
beacon-chain/state/state-native/getters_validator_test.go

Other
Follow up to #14176. This PR implements HasPendingBalanceToWithdraw which improves on the best case lookup.

State: HasPendingBalanceToWithdraw

---

proto/prysm/v1alpha1/attestation/BUILD.bazel
proto/prysm/v1alpha1/attestation/id.go
proto/prysm/v1alpha1/attestation/id_test.go

Other
This PR fixes tests failing with `could not create attestation ID` in https://github.com/prysmaticlabs/prysm/pull/14180.
We need to allow more than 1 committee bit set when creating an attestation ID because when we prune attestations we create IDs based on what we see in a block. And an Electra block will have aggregated attestations with more than 1 committee bit.

EIP-7549: Allow multiple committee bits

---

beacon-chain/verification/blob_test.go
consensus-types/blocks/kzg.go

This fixes the blob inclusion  Merkle proof generator for Electra due to the hardcoded limits for Attestations and Attester slashings that changed in the Electra fork.

Fix Merkle proof generator for Electra

---

testing/spectest/shared/common/forkchoice/builder.go
testing/spectest/shared/common/forkchoice/runner.go

Other
This still fails, but no longer failing for ssz unmarshalling errors. 
The test is currently skipped, but unskipping shows the following errors for minimal spectest
```
--- FAIL: TestMinimal_Electra_Forkchoice (26.47s)                                                                                                                         
--- FAIL: TestMinimal_Electra_Forkchoice/voting_source_within_two_epoch (0.60s)                                                                                       
assertions.go:144: builder.go:139 Unexpected error: could not create attestation ID: 2 committee bits are set instead of 1                                        
--- FAIL: …
```

Electra: Handle AttestationElectra in forkchoice spectest

---

beacon-chain/core/blocks/withdrawals.go
beacon-chain/core/blocks/withdrawals_test.go
beacon-chain/core/electra/withdrawals.go
beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/state/state-native/getters_withdrawal.go

Feature
Part of https://github.com/ethereum/consensus-specs/pull/3668
~Draft until unit tests are added for the DequeuePendingPartialWithdrawals call.~

Electra: EIP-7251 implement process_withdrawal updates

---

beacon-chain/core/electra/transition_no_verify_sig.go

Other
Resolves a TODO
This method is primarily tested through spectests. A PR to unskip the relevant spectests is
forthcoming this week.

Electra: process_consolidation_requests in state transition

---

beacon-chain/core/electra/registry_updates.go
beacon-chain/core/electra/registry_updates_test.go

Bug fix
ProcessRegistryUpdates should not fail when exiting a validator that is already exiting. This is
expected and can safely be ignored.
Required for #14220

Electra: process_registry_updates handle exiting validators

---

testing/spectest/mainnet/electra/fork_transition/transition_test.go
testing/spectest/mainnet/electra/forkchoice/forkchoice_test.go
testing/spectest/mainnet/electra/random/random_test.go
testing/spectest/minimal/electra/finality/finality_test.go
testing/spectest/minimal/electra/fork_transition/transition_test.go
testing/spectest/minimal/electra/forkchoice/forkchoice_test.go
testing/spectest/minimal/electra/random/random_test.go
testing/spectest/minimal/electra/sanity/blocks_test.go
testing/spectest/shared/electra/fork/upgrade_to_electra.go
testing/spectest/shared/electra/operations/block_header.go
testing/spectest/shared/electra/operations/execution_payload.go
testing/spectest/shared/electra/operations/helpers.go
testing/spectest/shared/electra/operations/withdrawals.go

Other
Merge this PR after other issues are resolved.
Requirements:

Electra: Unskip all spectests

---

beacon-chain/rpc/endpoints.go
beacon-chain/rpc/eth/events/BUILD.bazel
beacon-chain/rpc/eth/events/events.go
beacon-chain/rpc/eth/events/events_test.go
beacon-chain/rpc/eth/events/server.go

Bug fix
Makes the fee recipient more consistent with other clients such as lighthouse. the default value will be used when the proposer is not registered and the value from the proposer cache will be used when a known validator proposes. 
this fee recipient field should not be used by builders and apis as the correct version should be from the validator registration endpoint. 
Fixes #14204

Payload attributes misleading value fix

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/execution_engine_test.go
beacon-chain/db/kv/encoding.go
beacon-chain/rpc/core/validator.go
beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go
validator/db/filesystem/attester_protection.go
validator/db/iface/interface.go
validator/db/kv/attester_protection.go
validator/helpers/metadata_test.go

Other
- Set committee index to `0` for Electra inside `GetAttestationData`
- Use `PayloadAttributesV3` for Electra inside `getPayloadAttribute`
- Save `AttestationElectra` and `AttesterSlashingElectra` as SSZ objects
- Use `IndexedAtt` interface in validator database code

Add missing pieces of Electra

---

beacon-chain/core/peerdas/helpers.go
beacon-chain/sync/data_columns_sampling.go
beacon-chain/sync/data_columns_sampling_test.go
beacon-chain/sync/service.go

Feature
- Parallelize data column sampling
- Add tests

[PeerDAS] Parallelize data column sampling

---

beacon-chain/sync/service.go
beacon-chain/sync/validate_data_column.go
beacon-chain/verification/initializer.go
beacon-chain/verification/interface.go

Optimization
Rather than advancing slots for each data column, we instead use the proposer cache to verify them. This prevents Prysm from unnecessarily advancing states and incurring large memory allocations from them.
N.A

Use Proposer Cache to Verify Data Columns

---

beacon-chain/execution/engine_client.go
beacon-chain/execution/engine_client_test.go
beacon-chain/execution/payload_body_test.go
proto/engine/v1/json_marshal_unmarshal.go
proto/engine/v1/json_marshal_unmarshal_test.go
testing/util/electra.go

Feature
adds the correct serialization for consolidation requests to proto and json, needed for the execution payload for electra
Fixes #

adding consolidation requests to json serialization

---

config/params/loader_test.go
testing/spectest/exclusions.txt

Other
deposit receipts was change to deposit requests, we should remove references to deposit receipts
Fixes #

removing unused naming convention

---

beacon-chain/rpc/prysm/validator/BUILD.bazel
beacon-chain/rpc/prysm/validator/validator_performance.go
beacon-chain/rpc/prysm/validator/validator_performance_test.go

Bug fix
This PR correctly handles the case where there is no body and returns a BadRequest error.
N/A

GetValidatorPerformance empty body bug

---

beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_data_column.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/core/peerdas/helpers_test.go
beacon-chain/das/availability_columns.go
beacon-chain/das/cache.go
beacon-chain/p2p/types/types.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/rpc_blob_sidecars_by_root.go
beacon-chain/sync/rpc_blob_sidecars_by_root_test.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/subscriber_data_column_sidecar.go

Please read commit by commit.
E2E OK on my local computer.
(Still no artifact on CI.)

Make deepsource happy

---

beacon-chain/blockchain/process_attestation.go
beacon-chain/operations/attestations/kv/aggregated.go
beacon-chain/operations/attestations/kv/block.go
beacon-chain/operations/attestations/kv/forkchoice.go
beacon-chain/operations/attestations/kv/unaggregated.go
beacon-chain/operations/attestations/prepare_forkchoice.go
beacon-chain/rpc/prysm/v1alpha1/validator/attester.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_utils_bench_test.go
beacon-chain/state/state-native/getters_attestation.go
beacon-chain/state/state-native/getters_checkpoint.go
beacon-chain/state/state-native/references_test.go
proto/prysm/v1alpha1/BUILD.bazel
proto/prysm/v1alpha1/attestation.go
proto/prysm/v1alpha1/attestation/aggregation/attestations/attestations.go
proto/prysm/v1alpha1/attestation/aggregation/attestations/maxcover.go
proto/prysm/v1alpha1/attestation_fuzz_test.go
proto/prysm/v1alpha1/cloners.go
proto/prysm/v1alpha1/cloners_test.go
proto/prysm/v1alpha1/export_test.go

Other
code cleanup and removal of self-generated clone tests. instead, we can use fuzzing to resolve clones 
Fixes #

moving cloners to attestation.go and adding fuzzing

---

beacon-chain/core/blocks/eth1_data.go
beacon-chain/core/blocks/eth1_data_test.go
beacon-chain/core/transition/altair_transition_no_verify_sig_test.go
beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
beacon-chain/state/state-native/getters_balance_deposits.go
beacon-chain/state/state-native/getters_consolidation.go
beacon-chain/state/state-native/getters_eth1.go
beacon-chain/state/state-native/getters_misc.go
beacon-chain/state/state-native/getters_withdrawal.go
beacon-chain/state/state-native/setters_block.go
contracts/deposit/deposit.go
proto/prysm/v1alpha1/BUILD.bazel
proto/prysm/v1alpha1/attestation_fuzz_test.go
proto/prysm/v1alpha1/beacon_block.go
proto/prysm/v1alpha1/beacon_block_fuzz_test.go
proto/prysm/v1alpha1/cloners.go
proto/prysm/v1alpha1/cloners_test.go
proto/prysm/v1alpha1/eip_7521.go
proto/prysm/v1alpha1/eip_7521_fuzz_test.go
proto/prysm/v1alpha1/fuzz_test.go

Other
more code cleanup by moving cloners for beacon block fields to separate file, adding fuzzing, and exposing the CopySlice function for the rest of the application.
Fixes #

moving cloners to beacon_block.go and adding fuzzing

---

beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/payload_attestation.go
beacon-chain/core/helpers/payload_attestation_test.go

This PR modifies `get_ptc` function to follow the Python spec. The Python spec extracts PTC members from the beginning of committee array while current Prysm implementation assembles PTC members from the rear.

Modify `get_ptc` function to follow the Python spec

---

beacon-chain/core/electra/deposits.go

Should we be logging empty deposit requests, which are presumably the normal case? It seems to me it makes more sense to log deposit requests if they are >0 and, under existing state transition log

Remove no deposit requests found debug log

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go

Many thanks to @potuz and @nisdas for helping and iterating on this idea.
This PR introduces a filter for proposer-pack attestations to exclude invalid signature attestations. The primary design goal is to minimize the work in the common case by implementing the following filtering scheme. We assume the following variables:
**Local Variables:**
$\text{CurrentEpoch} = \text{ToEpoch(CurrentSlot)}$
$\text{TargetEpoch} = \text{ToEpoch(HeadSlot)}$
$\text{PrevTargetEpoch} = \text{ToEpoch(HeadSlot) - 1}$
$\text{TargetRoot} = \text{TargetRootForEpoch(HeadRoot, TargetEpoch)}$
$\text{PreviousTargetRoot} = \text{TargetRootForEpoch(HeadRoot, PrevTargetEpoch)}$
**Attestation Variables:**
$\text{AttEpoch} = \text{ToEpoch(Att.Data.Slot)}$
$\text{AttTargetEpoch} = \text{Att.Data.Target.Epoch}$ …

Proposer: filter attestations for invalid signature

---

beacon-chain/sync/data_columns_sampling.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/rpc_send_request.go
beacon-chain/sync/service.go
beacon-chain/sync/service_test.go

*Please read commit by commit, and please read the content of each commit message.*
Some logs from Kurtosis:
```
[2024-07-26 12:45:55]  DEBUG sync: Start data columns sampling columns=[107, 81, 117, 40, 91, 3, 66, 69] root=0x98977d6d68b5c83eec2f8a6e2cd869d22e918cb95537bb9d54bd12578c99ac1d round=1
[2024-07-26 12:45:55]  DEBUG sync: Sampled columns from peer sucessfully peerID=16Uiu2HAmAfg7dQgGoa9E4jbDDTPkjpWJ8BSYauCUc4Cuok6mCMEF requestedColumns=[3, 40, 81, 91, 117] root=0x98977d6d68b5c83eec2f8a6e2cd869d22e918cb95537bb9d54bd12578c99ac1d
[2024-07-26 12:45:56]  DEBUG sync: Sampled columns from peer sucessfully peerID=16Uiu2HAmB8Vsg1ipYvC2R3wXBLzACJJtnYahcWTvjfoaSrZTB4kN requestedColumns=[66, 69, 107] root=0x98977d6d68b5c83eec2f8a6e2cd869d22e918cb95537bb9d54bd12578c99ac1d
[2024-07-26 …
```

Fix data columns sampling

---

consensus-types/payload-attestation/BUILD.bazel
consensus-types/payload-attestation/readonly_test.go
consensus-types/payload-attestation/verifier_test.go

Tests addition for payload-attestation package
This PR adds unit tests for Payload attestation package
This provides mocks and tests required for payload attestation package

Payload attestation tests

---

beacon-chain/blockchain/process_attestation.go
beacon-chain/blockchain/process_block.go
beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/doubly-linked-tree/types.go
beacon-chain/forkchoice/interfaces.go

Changes the latest message structure "Vote" to use slot as in ePBS instead of the target epoch.

Use slot for latest message in forkchoice

---

beacon-chain/state/interfaces_epbs.go
beacon-chain/state/state-native/beacon_state_mainnet.go
beacon-chain/state/state-native/beacon_state_minimal.go
beacon-chain/state/state-native/getters_epbs.go
beacon-chain/state/state-native/getters_payload_header_epbs.go
beacon-chain/state/state-native/getters_setters_epbs_test.go
beacon-chain/state/state-native/getters_state.go
beacon-chain/state/state-native/hasher.go
beacon-chain/state/state-native/setters_epbs.go
beacon-chain/state/state-native/state_trie.go
beacon-chain/state/state-native/state_trie_epbs.go
beacon-chain/state/state-native/state_trie_epbs_test.go

Ensure that epbs state getters and setters check the version. This prevents potential panics when calling epbs getters with an outdated state. A similar pattern is followed in Electra and Deneb functions.

Ensure epbs state getters & setters check versions

---

beacon-chain/core/helpers/beacon_committee.go

Do not loop calling to obtain the beacon committee by index but rather get all committees at once.

Refactor CommitteeAssignments to get all committees at once

---

validator/accounts/testing/mock.go
validator/client/iface/validator.go
validator/client/runner.go
validator/client/testutil/mock_validator.go
validator/client/validator.go
validator/client/validator_test.go

Bug fix
PR https://github.com/prysmaticlabs/prysm/pull/14155 broke builder e2e but upon debugging it appears that deadline probably won't be needed in this design with submissions every slot so I removed explicit deadlines on the calls, all deadlines should be inherited or explicit on the HTTP client.
the current issue results in context cancellation while the registrations are being submitted
```
time="2024-07-31 00:27:31" level=warning msg="failed to register validator on builder" error="could not submit signed registrations to beacon node: failed to perform request for endpoint http://localhost:4375/eth/v1/validator/register_validator: Post "http://localhost:4375/eth/v1/validator/register_validator": context …
```

removing explicit deadlines on push proposer settings

---

beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/beacon_committee.go
beacon-chain/core/helpers/payload_attestation.go
beacon-chain/core/helpers/payload_attestation_test.go

This removes the unnecessary helper `PTCAssignments` and computes the assignments in the loop by getting all committees at once.

Use BeaconCommittees helper to get the ptc

---

beacon-chain/core/electra/transition_no_verify_sig.go

https://github.com/ethereum/consensus-specs/blob/dev/specs/electra/beacon-chain.md#operations
```python
...
for_ops(body.bls_to_execution_changes, process_bls_to_execution_change)
for_ops(body.execution_payload.deposit_requests, process_deposit_request)  # [New in Electra:EIP6110]
for_ops(body.execution_payload.withdrawal_requests, process_withdrawal_request)
for_ops(body.execution_payload.consolidation_requests, process_consolidation_request)
```

process Electra operations in the right order

---

beacon-chain/blockchain/receive_block.go

`ReceiveBlock`  makes any PR that touches the blockchain package fail the DeepSource CI because of its cognitive complexity.  This PR addresses this.

Reduce cognitive complexity of ReceiveBlock

---

beacon-chain/p2p/broadcaster_test.go
beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/p2p/gossip_topic_mappings_test.go
beacon-chain/p2p/topics_epbs.go
testing/util/random/epbs.go

This PR introduces `execution_payload` and `payload_attestation_message` P2P global topics. Since the tests for ePBS topics are nearly identical, now they use a helper function to avoid redundancy. Additionally, this PR corrects a typo by adjusting the `SourcePubkey` length from 20 bytes to 48 bytes and adds a testing utility for randomly populating `PayloadAttestationMessage` object.

Add `execution_payload` and `payload_attestation_message` topics

---

consensus-types/epbs/indexed_payload_attestation_test.go

What does this Pr do ?
Adds Test for IndexedPayloadAttestation

Indexed paylaod attestation test

---

beacon-chain/execution/mock_test.go
beacon-chain/execution/payload_body.go

Bug fix
engine_getPayloadBodiesByRangeV1  parameters should be hex-encoded before call
Fixes #14313

engine_getPayloadBodiesByRangeV1 - fix, adding hexutil encoding on request parameters

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go

Refactored `getLocalPayload` by moving part of its functionality into a new helper function, `getLocalPayloadFromEngine`. This helper function is utilized by epbs' `GetExecutionPayloadHeader` API implementation. `getLocalPayloadFromEngine` retrieves the local execution payload based on the slot, proposer ID, and parent root, assuming the payload is cached. If the payload ID is not cached, the function prepares a new payload using the local EL engine and returns it based on the head state.

Refactor get local payload

---

beacon-chain/p2p/testing/mock_peersprovider.go
beacon-chain/rpc/prysm/v1alpha1/node/server_test.go

Bug fix
`TestNodeServer_GetPeer` often failed, because the first element of peer list is not guaranteed to be same with what `MockPeersProvider` actually added to its peer list. `All()` method returns peer list by iterating a map structure, and that iteration can be random: second added peer can be placed at first as a result. Consult this [link](https://stackoverflow.com/questions/9619479/go-what-determines-the-iteration-order-for-map-keys).
So the test should be changed to explicitly find the first peer by its id.
Same issues at `TestNodeServer_ListPeers`.
N/A

fix(tests): Fix v1alpha1/node/server_test.go

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go

This PR is part of #14309.
Currently, to accept a bid, we do not check the gas limit, but we should. If the builder's bid header gas limit is incorrect, it will simply defer back to local building.
Implications:
1. If the validator's registration is not part of the DB, we will not be able to get the registration for the gas limit. It currently fails here (proposer defaults to local block), but should we be more lenient?
2. Getting registration from RegistrationByValidatorID adds a few milliseconds to the overall hot path, but there's no other way around this, it seems. Block preparation is concurrent here anyway.

Proposer checks gas limit before accepting builder's bid

---

runtime/interop/genesis.go

E2E Fix
In E2E , we were setting the max Uint63 value for our gas limit in genesis. This ended up conflicting with the limit provided to the builder which is the default value(30000000). This PR fixes it to the builder default so that the el is always in sync with the provided gas limit.
N.A

Fix Gas Limit in Genesis

---

WORKSPACE
beacon-chain/p2p/discovery_test.go
beacon-chain/p2p/testing/BUILD.bazel
beacon-chain/p2p/testing/p2p.go
beacon-chain/rpc/eth/config/handlers_test.go
beacon-chain/sync/data_columns_sampling_test.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
config/params/mainnet_config.go

Update Config To Latest Value

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/currently_syncing_execution_payload_envelope.go
beacon-chain/blockchain/receive_execution_payload_envelope.go
beacon-chain/blockchain/service.go

Refactors the `currentlySyncingPayload` cache to keep the withholding status for the payload. 
This is one part of two. A PTC voter will request first to this cache. If thi call fails then it will request from forkchoice

Refactor currentlySyncingPayload cache

---

beacon-chain/node/config.go
cmd/flags.go
validator/node/node.go

> Bug fix
By #11166, this fix made bug to always load mainnet bootnodes when just using testnet flags like --Holesky.
In `configureBeacon()` at beacon-chain/node/node.go it first initialize testnet network config by `ConfigureBeaconChain()` -> configureTestnet(). 
Than it always overrides beaconchain network config bootnodes value as a mainnet bootnodes(which is default value for `bootstrap-node` flag)  in `configureNetwork()` because len(cmd.BootstrapNode.Name) is always >1.
So this default value for  `bootstrap-node` flag should be removed to run testnet beacon node with just testnet flag. 
And also removing this default value doesn't disturb using mainnet flag usage.

bugfix : Removed the default value of the bootnode flag to prevent it from being overridden during testnet usage

---

beacon-chain/sync/data_columns_sampling.go
beacon-chain/sync/data_columns_sampling_test.go
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/initial-sync/blocks_queue.go
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/service.go
beacon-chain/sync/verify/BUILD.bazel
beacon-chain/sync/verify/blob.go
beacon-chain/verification/batch.go
beacon-chain/verification/data_column.go
beacon-chain/verification/initializer.go

Feature
This PR builds on from #14287 and uses the validation pipeline across prysm. Instead of calling kzg verification directly we specify a set of requirements to our verifier and use that across the repository. This is now used in normal verification, data column sampling and initial sync. 
Part of #14129 

Use Data Column Validation Across Prysm

---

.github/workflows/go.yml
.golangci.yml

This PR is updating the following dependencies in go CI checks:
- Update Lint to go 1.22.6 
- Update checkout and setup-go version to v4
- Update .golangci.yml to 1.22.6

PR to update workflow check dependencies

---

beacon-chain/rpc/eth/config/handlers_test.go
beacon-chain/sync/backfill/verify.go
beacon-chain/sync/backfill/verify_test.go
config/params/config.go
config/params/interop.go
config/params/loader.go
config/params/loader_test.go
config/params/mainnet_config.go
config/params/minimal_config.go
config/params/testdata/e2e_config.yaml
config/params/testnet_e2e_config.go
config/params/testnet_holesky_config.go
config/params/testnet_sepolia_config.go

This PR adds ePBS fork schedule to config. I guess it was omitted as Electra fork epoch is not defined yet, making both `cfg.ElectraForkEpoch` and `cfg.EPBSForkEpoch` have `math.MaxUint64` in `HoleskyConfig` and `SepoliaConfig` after adding ePBS fork. If it ought to be added later, please feel free to close this PR.

Add ePBS fork schedule to config

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/error.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_payload_attestation_message.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/sync/payload_attestations.go
beacon-chain/sync/service.go

Move the handling of PTC messages from the sync package to the chain package so that it can be called from rpc

Receive ptc message

---

beacon-chain/blockchain/process_block.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/data_columns_reconstruct.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/subscriber.go
beacon-chain/sync/validate_blob.go
beacon-chain/sync/validate_data_column.go
beacon-chain/verification/BUILD.bazel
beacon-chain/verification/blob.go
beacon-chain/verification/cache.go
beacon-chain/verification/data_column.go
beacon-chain/verification/log.go
config/features/config.go
config/features/flags.go
runtime/logging/data_column.go

Please read commits by commits.
All commits expect the last one are for logging.
The last one reduces the number of goroutines for reconstruction.
New logs:
```
[2024-08-29 11:58:28]  INFO rpc/validator: Updated fee recipient addresses for validator indices validatorCount=25
[2024-08-29 11:58:28]  DEBUG sync: Received block blockSlot=173 graffiti=1-geth-prysm proposerIndex=1 sinceSlotStartTime=0.818789s validationTime=0.003129s
[2024-08-29 11:58:28]  DEBUG sync: Accepted data column sidecar gossip blockRoot=0x654884 colIdx=97 intoSlotTime=0.817572s kzgCommitments=[0x8a113c 0xa5492f] parentRoot=0xd5aa9c propIdx=1 slot=173 valTime=0.004918s
[2024-08-29 11:58:28]  DEBUG sync: Accepted data column sidecar gossip blockRoot=0x654884 colIdx=64 intoSlotTime=0.819443s kzgCommitments=[0x8a113c …
```

PeerDAS: Improve logging and reduce the number of needed goroutines for reconstruction

---

CHANGELOG.md
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Feature
This enables use of multivalue slice in the beacon state by default. See #12549
This feature has a better runtime improvement on memory usage by beacon states.

feature: Enable experimental state by default (opt out)

---

beacon-chain/blockchain/kzg/trusted_setup.go

Optimization
This sets a non-zero number for the precompute step when loading the trusted setup. A number of 8 has been chosen according to the table here: https://notes.ethereum.org/@jtraglia/windowed_multiplications
N.A

Initialize Larger Precompute For The Trusted Setup

---

CHANGELOG.md
beacon-chain/rpc/eth/light-client/helpers.go

Feature
Some places use an epoch where a sync committee. This PR fixes that issue
Fixes #14206

fix: make some places use sync committee period instead of epoch

---

beacon-chain/p2p/discovery.go
beacon-chain/p2p/handshake.go
beacon-chain/p2p/pubsub_filter.go
beacon-chain/p2p/service.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/sync/data_columns_sampling.go
beacon-chain/sync/rpc_ping.go
beacon-chain/sync/subscriber.go
cmd/beacon-chain/main.go
config/features/config.go
config/params/BUILD.bazel
config/params/testnet_custom_network_config.go

**Please read commit by commit, with commits message.**
- E2E on my local computer: ✅
- Kurtosis 2 super nodes + 1 full node: ✅
- Kurtosis 2 super nodes + 1 full node started at epoch 4: ✅

Fix Initial Sync with 128 data columns subnets

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/chain_info_forkchoice.go
beacon-chain/blockchain/epbs_test.go
beacon-chain/forkchoice/doubly-linked-tree/epbs.go
beacon-chain/forkchoice/doubly-linked-tree/epbs_test.go
beacon-chain/forkchoice/doubly-linked-tree/types.go
beacon-chain/forkchoice/interfaces.go
beacon-chain/forkchoice/ro.go
beacon-chain/forkchoice/ro_test.go

This PR adds 
- A forkchoice helper to determine the PTC status of the current slot. 
- A `withheld` boolean to forkchoice nodes to signal that we have synced succesfully a `PAYLOAD_WITHHELD` message
- A chain info wrapper that checks on forkchoice and otherwise returns information from the current cache if it's being synced.

Add GetPTCVote helpers

---

CHANGELOG.md
beacon-chain/node/config_test.go
cmd/validator/flags/flags.go
testing/endtoend/components/validator.go

Bug fix
https://github.com/prysmaticlabs/prysm/pull/14089 changed the flags for gateway, the release e2e uses the previous version to run e2e so that we know settings did not change. in this case the default name of the flag changed and a temporary use of the alias in the e2e test will be needed in the mean time until a future release where the updated name can then be used.
Fixes #

gateway flag changes breaking release e2e

---

beacon-chain/blockchain/chain_info_forkchoice.go
beacon-chain/blockchain/receive_execution_payload_envelope.go
beacon-chain/forkchoice/BUILD.bazel
beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
beacon-chain/forkchoice/doubly-linked-tree/epbs.go
beacon-chain/forkchoice/doubly-linked-tree/epbs_test.go
beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/doubly-linked-tree/metrics.go
beacon-chain/forkchoice/interfaces.go

This PR adds an exported function to import an exectution payload envelope in forkchoice

Handle execution payload insertion in forkchoice

---

CHANGELOG.md
beacon-chain/core/electra/effective_balance_updates.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/precompute/slashing.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/readonly_validator.go
beacon-chain/state/state-native/references_test.go
beacon-chain/state/state-native/setters_validator.go
beacon-chain/sync/validate_bls_to_execution_change_test.go

This PR changes the signature of the closure that is needed on `ApplyToEveryValidator`
This function is dangerous as It provides directly a pointer to the validator and the caller can actually do damage by modifying it. There are two bugs that we have seen with this interface
- Not returning changed boolean correctly, which indicates that the validator has changed to later mark the field as dirty
- Modifying the validator in place, instead of copying.
The second type of error is silly because there is no need at all to pass a slice of pointers to that function. That function anyway would need to copy the validator if we change it in any way, therefore we can prevent entirely these bugs by changing the signature of the closure to take a `[]ReadOnlyValidator` slice and return a …

Use read only validators on ApplyToEveryValidator

---

CHANGELOG.md
testing/middleware/builder/BUILD.bazel
testing/middleware/builder/builder.go

Bug fix
PR https://github.com/prysmaticlabs/prysm/pull/14416 removed gorilla mux which included a regex pathing feature that now broke post upgrade. This PR migrates the builder API registration to something that is supported by the standard HTTP package.
Fixes #

E2E: fixing builder route registration after gorilla mux removal

---

CHANGELOG.md
beacon-chain/rpc/eth/config/handlers_test.go
config/params/config.go
config/params/mainnet_config.go

Other
The signing domain is no longer used now that consolidations are created from the EL.
See https://github.com/ethereum/consensus-specs/pull/3915
This can merge without a spectest release since it's just code cleanup.

Electra: Remove signing domain for consolidations

---

beacon-chain/blockchain/process_block.go
beacon-chain/core/peerdas/helpers.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/subnets.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/service.go

This PR:
- For columns, stops using peer sampling and use subnet sampling only.
- Modifies `sendBatchRootRequest` so we stop sending columns by root requests to peers which do not custody them.
- Improve logs
Full node logs - subscribed to `SAMPLES_PER_SLOT` (8) subnets:
```
[2024-09-14 12:38:06.00]  INFO sync: Subscribed to topic=/eth2/aabc67ec/data_column_sidecar_84/ssz_snappy
[2024-09-14 12:38:06.00]  INFO sync: Subscribed to topic=/eth2/aabc67ec/data_column_sidecar_63/ssz_snappy
[2024-09-14 12:38:06.00]  INFO sync: Subscribed to topic=/eth2/aabc67ec/data_column_sidecar_31/ssz_snappy
[2024-09-14 12:38:06.00]  INFO sync: Subscribed to topic=/eth2/aabc67ec/data_column_sidecar_29/ssz_snappy
[2024-09-14 12:38:06.00]  INFO sync: Subscribed to …
```

Peerdas: Full subnet sampling and `sendBatchRootRequest` fix.

---

beacon-chain/blockchain/kzg/kzg.go
beacon-chain/blockchain/kzg/trusted_setup.go
deps.bzl
go.mod
go.sum
third_party/com_github_ethereum_c_kzg_4844.patch

Other
This PR updates the c-kzg-4844 dependency to the latest version:
* https://github.com/ethereum/c-kzg-4844/releases/tag/v2.0.1
I'm pretty sure I did the patch correctly, but please double check.
The new c-kzg-4844 version uses blst v0.3.12, so that's why that changed.
Also, we split the implementation into several files, hence the updated `hdrs` line in the patch.

Update c-kzg-4844 to v2.0.1

---

.policy.yml
hack/README.md
hack/common.sh
hack/update-go-pbs.sh
proto/eth/v1/attestation.pb.gw.go
proto/eth/v1/beacon_block.pb.gw.go
proto/eth/v1/beacon_chain.pb.gw.go
proto/eth/v1/events.pb.gw.go
proto/eth/v1/node.pb.gw.go
proto/eth/v1/validator.pb.gw.go
proto/eth/v2/beacon_block.pb.gw.go
proto/eth/v2/beacon_chain.pb.gw.go
proto/eth/v2/beacon_lightclient.pb.gw.go
proto/eth/v2/custom.go
proto/eth/v2/ssz.pb.gw.go
proto/eth/v2/sync_committee.pb.gw.go
proto/eth/v2/validator.pb.gw.go
proto/eth/v2/version.pb.gw.go
proto/eth/v2/withdrawals.pb.gw.go

Other
_*Farewell to gateway files*_
#14089 deprecates `*pb.gw.go` files, but there are some dregs around `*pb.gw.go` file supports. This PR fully deprecates those supports, which will help newcomers investigate this project.

Deprecate `pb.gw.go` files

---

CHANGELOG.md
beacon-chain/rpc/eth/debug/handlers.go
beacon-chain/rpc/eth/debug/handlers_test.go

Bug fix
This PR addresses an issue when trying `/eth/v2/debug/beacon/states/{state_id}`. Since `version.Electra` is not in the case, it will return "Unsupported spec version" after Electra fork epoch.

Add Electra case for GetBeaconStateV2

---

beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/rpc_data_column_sidecars_by_range.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/rpc_send_request.go

This PR:
- Improve logging.
- Stop decrease a peer's score if the peer requests a data column we do not custody. (It just serves data columns it stores, and filters out data columns it does not store.)
- When requesting a data column by root, stop hanging is the data column is not (yet) available in the DB. This behaviour was useful for peer sampling but not any more.
- Stop filtering nodes for initial sync. Rationale: Currently we are only able to sync from super nodes. On the the devnet, there is not so many super nodes. (And LH already does not like our requests that are too large when we are a super node.) If we keep filtering on peers, initial sync takes hours.

PeerDAS: Misc improvements

---

beacon-chain/sync/subscriber.go

Bug Fix
In the event a node does not have sufficient peers in its subnets, this particular method will block while its trying to find peers. In order to prevent it from not subscribing to other required topics, this method is placed in the goroutine.
N.A

Put Sync Subnet Subscriber in Goroutine

---

validator/client/payload_attestation.go
validator/client/payload_attestation_test.go

`waitUntilPtcDuty` is not used in `SubmitPayloadAttestationMessage`

Use wait for ptc duty in submit payload attestation message

---

beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/rpc_send_request.go
beacon-chain/sync/rpc_status.go

Mainly, this pull request reduces any data columns by range requests to 512 items.
This value lets all other clients enough time to respond and does not trigger "too large request" error response.

PeerDAS: Fix initial sync with super nodes

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/service_test.go
beacon-chain/blockchain/setup_test.go
beacon-chain/core/peerdas/helpers.go
beacon-chain/das/BUILD.bazel
beacon-chain/das/availability.go
beacon-chain/das/availability_columns.go
beacon-chain/das/availability_columns_test.go
beacon-chain/das/availability_test.go
beacon-chain/das/cache.go
beacon-chain/das/iface.go
beacon-chain/das/mock.go
beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_eth1data.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
beacon-chain/sync/backfill/BUILD.bazel
beacon-chain/sync/backfill/status.go
beacon-chain/sync/initial-sync/BUILD.bazel
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/rpc_data_column_sidecars_by_range.go

Bug Fix
Fixes non-existent commitments array. Copying a 2 dimensional slice does not work as it has to be initialized beforehand. This PR fixes it by just assigned the value to the slice and adding a relevant regression test.

Fix Commitments Check

---

CHANGELOG.md
api/headers.go
api/server/structs/conversions.go
async/event/BUILD.bazel
async/event/feed.go
async/event/interface.go
async/event/subscription.go
beacon-chain/blockchain/setup_test.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/core/feed/operation/notifier.go
beacon-chain/core/feed/state/notifier.go
beacon-chain/execution/service_test.go
beacon-chain/node/node.go
beacon-chain/rpc/eth/events/BUILD.bazel
beacon-chain/rpc/eth/events/events.go
beacon-chain/rpc/eth/events/events_test.go
beacon-chain/rpc/eth/events/http_test.go
beacon-chain/rpc/eth/events/server.go
deps.bzl
go.mod
go.sum

Bug fix
This PR separates event stream api processing across 2 staged queues. First is a channel where event subscriptions are buffered, and second is an "outbox" with a capped size. The send to the outbox is protected by a select statement, so if the outbox can't be written, the event is dropped on the floor and a cleanup sequence is triggered, ending the event stream. Validation and filtering happens before the write to the outbox, but serialization is deferred via a closure until the event is ready to be written to the client.
A separate goroutine processes the outbox, draining the queue and calling flush on the response writer only once all events have been written to the client, removing the need for unnecessary …

SSE implementation that sheds stuck clients

---

CHANGELOG.md
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Other
Makes committee aware packing the default. This flag will become obsolete after Electra, so the sooner we flip it, the more impact it will have. It does improve attestation inclusion for blocks with max number of atts. Below are results I got when applying the flag on Holesky testnet.
> Since then we deployed the new algorithm to our Holesky REST nodes on Aug 7th at around block 2,085,350. I backfilled my Holesky DB to slot ~1,864,000 and synced to ~2,330,000. Then I extracted data for all blocks that have 128 attestations in them (the new algorithm doesnt make a difference if the block is not full). In total I have 421,647 such blocks, which is a big majority of all blocks on the Holesky network. Out of these …

Flip committee aware packing flag

---

CHANGELOG.md
beacon-chain/blockchain/execution_engine.go
beacon-chain/rpc/eth/events/BUILD.bazel
beacon-chain/rpc/eth/events/events.go
consensus-types/primitives/BUILD.bazel
consensus-types/primitives/kzg.go

exporting functions in the blockchain package makes them very difficult to be used as not that many packages have access to the blockchain package due to circular dependencies. This PR moves one of them to the primitives package. It breaks a dependency circle on ePBS.

Move back ConvertKzgCommitmentToVersionedHash to primitives package

---

CHANGELOG.md
beacon-chain/p2p/pubsub.go

`pubsubGossipParam()` is the function to set the parameters for the underlying libp2p-pubsub. But the setting for parameter “gParams.Dhi” is missing in this function.  Details can be found in the following link.
https://github.com/prysmaticlabs/prysm/issues/14516

Fix mesh size in libp2p-pubsub

---

CHANGELOG.md
beacon-chain/state/state-native/getters_withdrawal.go
beacon-chain/state/state-native/getters_withdrawal_test.go
testing/spectest/mainnet/electra/operations/withdrawals_test.go
testing/spectest/minimal/electra/operations/withdrawals_test.go

Blocked by #14430 for spec tests
Bug description: https://hackmd.io/@ttsao/S13TVqkA0
Fix: reference: https://github.com/ethereum/consensus-specs/pull/3943
The bug in Electra occurs during the processing of partial withdrawals. When a pending partial withdrawal is skipped due to insufficient effective or excess balance, an offset is created because the `partial_withdrawals_count` doesn't account for the skipped withdrawal. This leads to the same withdrawal being processed twice, as skipped withdrawals aren't properly counted. The solution is to increment `partial_withdrawals_count` even for skipped withdrawals to ensure accurate pruning of `pending_partial_withdrawals`.

Fix partial withdrawals

---

beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
beacon-chain/sync/validate_data_column.go
beacon-chain/sync/verify/blob.go

This pull requests rework the way data columns sidecars are retrieved from peers.
**Before this PR:**
If in `bwb` we needed to retrieve columns `[1, 3]` for block `[12, 13]` and columns `[8,9]` for block `20`, then, we sent a data column sidecar by range request corresponding to columns `[1, 3, 8, 9]` for blocks `[12, 13, 14, 15, 16, 17, 18, 19, 20]`.
So, 
- columns `[8, 9]` for blocks `[12, 13]`, 
- columns `[1, 3]` for blocks `20`, and
- columns `[1, 3, 8, 9]` for blocks `[14, 15, 16, 17, 18, 19]`
were returned by our peer for strictly no usage at all.
==> This occurs a useless bandwidth usage and a higher initial sync time (especially in small devnets) due to our internal rate limiting.
**With this PR:**
We carefully craft columns by range requests to ask peers to return exactly the …

Data columns initial sync: Refactor

---

CHANGELOG.md
beacon-chain/core/electra/consolidations.go
beacon-chain/core/electra/consolidations_test.go
beacon-chain/core/electra/validator.go
beacon-chain/core/helpers/BUILD.bazel
testing/spectest/mainnet/electra/epoch_processing/pending_consolidations_test.go
testing/spectest/mainnet/electra/operations/consolidation_test.go
testing/spectest/mainnet/electra/sanity/blocks_test.go
testing/spectest/minimal/electra/epoch_processing/pending_consolidations_test.go
testing/spectest/minimal/electra/operations/consolidation_test.go
testing/spectest/minimal/electra/sanity/blocks_test.go

This PR modifies the handling of switching validators to compounding credentials by consolidating the logic into the `process_consolidation_request` flow. Key code changes include:
- Removed `switch_to_compounding_validator` from `process_pending_consolidations`.
- Removed `switch_to_compounding_validator` from `apply_deposit`.
- Added a helper function `is_valid_switch_to_compounding_request`.
- Updated `process_consolidation_request` to check `is_valid_switch_to_compounding_request`, and if valid, switch the source index validator to compounding.
- Updated `process_consolidation_request` to automatically switch the target validator to compounding if it has an eth1 credential.
Note to the reviewers: In `process_consolidation_request`, we used to return errors in many places, but in the …

Switch to compounding when consolidating with source==target

---

CHANGELOG.md
cmd/client-stats/flags/flags.go

~~Bug fix~~
~~Feature~~
~~Documentation~~
Other
This PR adjusts the default value for the `scrape-interval` in the `Client-stats` app. The default scrape interval is currently set to 1 minute (60 seconds), which can cause users on the free plan of the Beaconcha.in API to exceed the rate limit of 30,000 requests per month. By increasing the default scrape-interval to 2 minutes (120 seconds), the number of requests is reduced, helping users avoid hitting the rate limit.
Fixes #14536
The current scrape-interval of 1 minute leads to rate-limiting issues (HTTP 429) for users on the free tier of the Beaconcha.in API. This change will ensure better compliance …

Update default scrape-interval to 2 minutes for Beaconcha.in API rate limit

---

beacon-chain/sync/rpc_data_column_sidecars_by_range.go

So we comply with [the specification](https://github.com/ethereum/consensus-specs/blob/dev/specs/_features/eip7594/p2p-interface.md#datacolumnsidecarsbyrange-v1).
> The following data column sidecars, where they exist, MUST be sent in (slot, column_index) order.
(Before, the order was undefined because coming from the iteration of a map.)

`dataColumnsByRange`: Sort data columns by index.

---

CHANGELOG.md
beacon-chain/rpc/eth/events/events.go

Bug fix
There is a panic race condition that seems to involve sudden disconnects from a backlogged stream events queue. This PR adds a recover() call as a band-aid to prevent the node crashing when that condition is triggered. Another PR will attempt to address the root cause of the panic.

recover from panics when writing the event stream

---

CHANGELOG.md
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
testing/spectest/mainnet/electra/epoch_processing/slashings_test.go
testing/spectest/minimal/electra/epoch_processing/slashings_test.go

This PR fixes an issue in the correlation penalty computation that caused a zero penalty for 32 ETH validators and a non-zero penalty for 2048 ETH validators under certain slashed balances, leading to an imbalance. The fix ensures penalties are computed per effective balance increment, preventing overflow and balancing penalties for different validator sizes.
Reference: https://github.com/ethereum/consensus-specs/pull/3882

Update correlation penalty for EIP-7251

---

CHANGELOG.md
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_block_test.go

This PR adds two core logic changes
- `HasBlock` returns false in the event that the block is being synced at the current time. 
- If there is an error after saving the block to db but before saving the state to db, then rollback the block insertion to db.

rollback on SaveState error

---

CHANGELOG.md
beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
beacon-chain/forkchoice/doubly-linked-tree/store.go
beacon-chain/forkchoice/doubly-linked-tree/store_test.go

In the event of errors when inserting a node in forkchoice, rollback all internal changes and remove the node before returning an error. This prevents forkchoice from erroneously keeping a node that couldn't be really processed.

Rollback on errors from forkchoice insertion

---

CHANGELOG.md
beacon-chain/monitor/process_attestation.go

Feature
Updates the `beacon-chain/monitor` package to Electra

Update the monitor package to Electra

---

CHANGELOG.md
consensus-types/blocks/proofs.go

Bug fix
The description of https://github.com/ethereum/consensus-specs/blob/dev/specs/capella/light-client/sync-protocol.md#custom-types says
> Merkle branch of `execution_payload` within `BeaconBlockBody`
The _**body**_, not the full block. We currently prove the payload within the entire block.
Part of #12991 

Return the correct light client payload proof

---

beacon-chain/core/peerdas/helpers.go
beacon-chain/core/peerdas/helpers_test.go
beacon-chain/das/availability_columns.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/data_columns_sampling.go
beacon-chain/sync/data_columns_sampling_test.go
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/initial-sync/blocks_queue.go
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/service_test.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_send_request.go
beacon-chain/sync/service.go
beacon-chain/sync/validate_data_column.go
beacon-chain/sync/verify/BUILD.bazel
beacon-chain/sync/verify/blob.go
beacon-chain/verification/batch.go
beacon-chain/verification/blob_test.go
beacon-chain/verification/data_column.go
beacon-chain/verification/data_column_test.go
beacon-chain/verification/initializer.go
beacon-chain/verification/interface.go

This PR transforms `NewColumnVerifier` (1 column) into `NewDataColumnsVerifier` (multiple columns, `Data` has been added for consistency).
The purpose of this PR is to batch data columns verification, and especially `VerifyDataColumnsSidecarKZGProofs`, which is much more efficient when called by batch than when called columns by columns.
On my computer (ARM M-2), duration of KZG verification assuming a constant blob count per block, for 32 blocks:
- column by column: `~12-13 s`
- batch (all columns in the batch of 32 blocks): `~700 ms`
==> `x18` (!) improvement.

PeerDAS: Batch columns verifications

---

CHANGELOG.md
beacon-chain/core/light-client/lightclient.go
consensus-types/interfaces/light_client.go
consensus-types/light-client/update.go

Bug fix
`LightClientUpdate` setters only updated fields of the wrapper type without changing fields of the wrapped proto object. Marshaling the wrapper into SSZ, which in turn marshals the wrapped proto object, would return the incorrect result.
Shout out to @Inspector-Butters for finding this issue. 
Part of #12991 

Set fields of wrapped proto object in light client setters

---

beacon-chain/blockchain/process_block_helpers.go
beacon-chain/rpc/eth/events/events.go

>
> Bug fix
> Feature
> Other
This PR addresses the TODOs that were mentioned in #14549
Part of #12991

fix TODOs for events

---

CHANGELOG.md
beacon-chain/execution/engine_client.go
beacon-chain/execution/engine_client_test.go

The `exists` array is always returned as `[6]bool`, with a fixed length of 6. Until this is made dynamically sized, we cannot assume it will always match the count of KZG commitments in the block body. 
The key requirement is ensuring that the block body's KZG length doesn’t exceed the bounds of `exists`, meeting this constraint:
```go
for i, commitment := range kzgCommitments {
if !exists[i] {
kzgHashes = append(kzgHashes, primitives.ConvertKzgCommitmentToVersionedHash(commitment))
}
}
```
This PR modifies the check from an equality check to a greater-than check, so the body’s KZG count cannot be greater than the `exists` count.

Fix length check between kzg commitments and exist

---

CHANGELOG.md
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go

Bug Fix
In the event that there are issues during the processing of a block we rollback the block insertion so as to ensure that the node is not left in an inconsistent state. This will allow the node to be able to process the block quickly again via req/resp . 
N.A

Rollback Block During Processing

---

CHANGELOG.md
cmd/beacon-chain/sync/backfill/options.go

Bug fix
This fixes an embarassing bug where the code handling `--backfill-oldest-slot` was pulling a value from the wrong flag. Big thanks to @xinzhongyoumeng for an incredibly helpful bug report pointing to the exact line of code that was incorrect.
Fixes #14563

fix --backfill-oldest-slot flag handling

---

CHANGELOG.md
validator/rpc/BUILD.bazel
validator/rpc/handlers_keymanager.go
validator/rpc/handlers_keymanager_test.go
validator/rpc/intercepter.go
validator/rpc/intercepter_test.go

Bug fix
fixes some reported inconsistencies and errors with keymanager APIs 
does not solve
> I'm not sure if this is a bug since the spec is a bit vague on it. Prysm returns a fee-recipient for each and every pubkey which is put into the endpoint /eth/v1/validator/<pubkey>/feerecipient. In my understanding it should only return the fee recipient for managed validators.
it's my belief that since we can set the suggested fee recipient if a new key is added it would just default to that value. its not clear what should be the correct response. 
Fixes #14577

keymanager API: bug fixes and inconsistencies 

---

CHANGELOG.md
beacon-chain/blockchain/chain_info.go

Optimization
When computing the current active validator count, we do not need to perform a state copy. This is very expensive when it is run in high traffic paths. Instead we use a read only state to be able to perform the computation.
By reducing the number of state copies, we can reduce the amount of memory allocated in large networks such as holesky by about 500mb. 
Fixes #

Use Read Only Head State When Computing Active Indices

---

CHANGELOG.md
beacon-chain/core/validators/validator.go
beacon-chain/rpc/core/validator.go

Bug fix
This PR fixes a bug in the `EjectedValidatorIndices` function within `GetActiveSetChanges` where incorrect indices were being returned for ejected validators.
Similar to the `ExitedValidatorIndices` (#14587) fix, the previous implementation had issues with its `withdrawableEpoch` calculation that could cause the function to miss validators that were actually ejected in the queried epoch. The function was using a global withdrawable epoch based on the maximum exit epoch across all validators, which could lead to incorrect data.
The fix simplifies the logic to only check two key conditions:
- If the validator's ExitEpoch matches the queried epoch
- If the validator's EffectiveBalance is at or below the ejection …

Simplify EjectedValidatorIndices

---

CHANGELOG.md
validator/client/BUILD.bazel
validator/client/key_reload.go
validator/client/key_reload_test.go
validator/client/validator.go
validator/client/validator_test.go
validator/client/wait_for_activation.go
validator/client/wait_for_activation_test.go

Other
We shouldn't be counting total validators just to print a log for queue position of a validator. Calling the validators count endpoint isn't standard and removing a call to it from the validator client will put us closer to the path of standardization. Logs are updated in accordance.
Fixes #

Remove validator count log

---

CHANGELOG.md
beacon-chain/blockchain/process_block_test.go
beacon-chain/blockchain/receive_block.go

Use ROBlock before validating state transition

Use ROBlock earlier in the pipeline

---

CHANGELOG.md
beacon-chain/db/kv/state.go

Bug Fix
During serialization of a state to be persisted in our db, we have a step to lay it out as a protobuf object so that serialization can occur. We do this step twice, which can allocate a lot more memory than what is needed. This PR fixes that
N.A

Build Proto State Object Once 

---

CHANGELOG.md
beacon-chain/state/state-native/getters_state.go
beacon-chain/state/state-native/getters_validator.go

Optimization
For the experimental state, when building out the protobuf state we end up copying the whole validator registry just to serialize it. Doing this has lead much longer state write transaction times, this PR fixes this by not copying the whole registry. This is as it is understood by the caller that we are accessing the internal state data (without copying). This behaviour maintains parity as it was done previously. 
We do the same for balances and inactivity scores fields.
N.A

Allow Protobuf State To Be Created Without Copying

---

CHANGELOG.md
api/client/event/event_stream.go
api/client/event/event_stream_test.go

Bug fix
Returns from Subscribe before accessing nil response body if the http request fails.
Prevents a panic that occurs when subscribing to EventStream if request fails resulting in a nil response body

prevent panic by returning on connection error

---

CHANGELOG.md
beacon-chain/core/blocks/withdrawals.go
beacon-chain/core/electra/deposits.go
beacon-chain/core/electra/transition.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/beacon_state.go
beacon-chain/state/state-native/setters_consolidation.go
beacon-chain/state/state-native/setters_deposits.go
beacon-chain/state/state-native/setters_withdrawal.go
beacon-chain/state/state-native/setters_withdrawal_test.go
beacon-chain/state/state-native/spec_parameters.go
beacon-chain/state/state-native/state_trie.go

Other
* To mimic `AppendPendingPartialWithdrawal`, add a nil check for the value.
* Remove unused `ProcessSyncAggregate` alias.
* Move `historicalSummaries` that is in the "wrong" spot.
* Move `PendingDeposit.Amount` that is in the "wrong" spot.
* Rename `DequeuePartialWithdrawals` to `DequeuePendingPartialWithdrawals`.
* Remove parentheses from `errNotSupported` argument.
* In `state_trie.electraFields`, move `LatestExecutionPayloadHeaderDeneb`.

Fix various small things in state-native code

---

CHANGELOG.md
beacon-chain/sync/subscriber_beacon_blocks.go
beacon-chain/sync/subscriber_beacon_blocks_test.go

If the block is before Deneb, we don’t need to reconstruct the blob sidecar, and in this case, it’s reasonable to return early in the future instead of encountering errors down the line

Return early blob constructor if not deneb

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/execution_engine_epbs.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/receive_execution_payload_envelope.go
beacon-chain/core/blocks/payload.go
beacon-chain/execution/engine_client.go
consensus-types/payload-attribute/types.go

This deals with sending FCU on the ePBS paths
- Removes calls from process CL blocks
- Adds a call after processing the payload
- Adds calls on reorgs by attestations
- Adds a call on late block tasks
- Also recreates the ticker for late block tasks to happen at 3 seconds instead of 4. 
Still broken by stategen (that needs to recover the right head state empty/full) and possibly the NSC

Epbs payload

---

CHANGELOG.md
beacon-chain/rpc/prysm/v1alpha1/validator/status.go
validator/client/beacon-api/status.go
validator/client/beacon-api/status_test.go
validator/client/validator.go
validator/client/validator_test.go

Bug fix
validator REST mode did not handle cases where the validator checks for validator status after removing all keys. This PR handles the panic presented when the endpoint is called but no keys are provided.
Fixes #14636

Validator REST api: adding in check for empty keys changed

---

beacon-chain/node/node.go

Other
P2P and backfill service registrations aren't starting in the right spots, these services are not started at the time of registration so they should probably be moved. 
Fixes #

reorganizing p2p and backfill service registration for consistency

---

CHANGELOG.md
beacon-chain/rpc/eth/events/events.go

Bug fix
This PR updates the event stream api to support electra `attestation` and `attester_slashing` messages. The approach taken is to marshal these values as they would be represented elsewhere in the beacon api, without any special treatment around distinguishing the different schema of events that could be streamed in the same client session. This is unlikely to be the correct way to marshal these events when the [beacon API spec discussion on this topic](https://github.com/ethereum/beacon-APIs/pull/459) resolves, but in the meantime this approach should be backwards-compatible with the [attestantio/go-eth2-client](https://github.com/attestantio/go-eth2-client) stream client used by tools like xatu and …

Fix eventstream electra atts

---

CHANGELOG.md
beacon-chain/core/electra/deposits.go
beacon-chain/core/electra/deposits_test.go

When two pending deposits for a new validator are processed in the same epoch, the second one adds a new validator with a repeated pubkey, instead we should update the balance.

Check if validator exists when applying pending deposit

---

CHANGELOG.md
beacon-chain/execution/engine_client.go
beacon-chain/verification/blob.go

Remove the KZG proof check for the blob reconstructor. The CL gets blobs and proofs from the EL, assuming a trusted relationship. Verification of the KZG proof is likely unnecessary, and in some cases, it takes more than 20ms. Removing it is safe, as the tradeoff is no longer worth it

Remove kzg proof check for blob reconstructor

---

CHANGELOG.md
api/client/builder/BUILD.bazel
api/client/builder/client.go
api/client/client.go
api/client/errors.go
api/client/options.go
beacon-chain/sync/checkpoint/BUILD.bazel
beacon-chain/sync/checkpoint/api.go
cmd/prysmctl/checkpointsync/download.go

In a few places prysm makes http connections to other systems and reads all bytes before attempting to unmarshal the response. A best practice for this kind of client connection is to limit the number of bytes read to a reasonable upper bound.
Other
Fixes #

Improvements to HTTP response handling

---

CHANGELOG.md
beacon-chain/rpc/endpoints.go
beacon-chain/rpc/eth/events/BUILD.bazel
beacon-chain/rpc/eth/events/events.go
beacon-chain/rpc/eth/events/server.go

Bug fix
This PR fixes bug introduced by #14670 which caused issues with SSE endpoint. The issue arises because wrapping of `ResponseWriter` disrupts the way Server-Sent Events (SSE) work. SSE requires the ResponseWriter to flush data to the client continuously during the stream. Specifically, the `WriteHeader` method is being overriden, and while this generally works well for standard HTTP responses, it causes issues with streaming endpoints like SSE which rely on direct and uninterrupted access to the underlying `http.ResponseWriter`. This PR handles error counting of SSE endpoint separately and excludes SSE endpoint with from the usual flow.
Below are logs tested using kurtosis that detected this issue:
``` …
```

Add error counter for SSE endpoint

---

CHANGELOG.md
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go
deps.bzl
go.mod
go.sum
testing/endtoend/components/beacon_node.go

Feature
This makes `QUIC` the default transport protocol in prysm and will make every prysm node connect to other nodes via QUIC if supported.
N.A

Make QUIC The Default Transport

---

CHANGELOG.md
api/client/client.go
beacon-chain/sync/checkpoint/api.go
beacon-chain/sync/genesis/BUILD.bazel
beacon-chain/sync/genesis/api.go
cmd/prysmctl/checkpointsync/download.go

Bug fix
This fixes a bug where checkpoint sync could not be started against holesky when downloading the genesis state from the checkpoint origin server. This issue was unique to holesky where the genesis state is much larger than the default 8MB limit.

Raise http body limit for fetching genesis state on Holesky

---

CHANGELOG.md
beacon-chain/p2p/encoder/ssz.go
beacon-chain/p2p/encoder/ssz_test.go

This PR changes the max payload size by using a new variable to represent the uncompressed payload size so that the correct value is checked against when decoding payloads.
N.A

Change Max Payload Size

---

CHANGELOG.md
beacon-chain/node/node.go

Other
When starting a node with checkpoint sync (especially on Holesky on a low bandwidth connection), nothing at all is happening in beacon node logs. The user may think the node is in a deadlock.
This PR just adds a log warning the user something is downloading (and possibly can take some time).
```
[2024-12-04 10:32:21]  INFO execution: Finished reading JWT secret from /Users/manu/OffchainLabs/ethereum/jwt.hex
[2024-12-04 10:32:21]  INFO flags: Running on the Holesky Beacon Chain Testnet
[2024-12-04 10:32:21]  WARN node: In order to receive transaction fees from proposing blocks, you must provide flag --suggested-fee-recipient with a valid ethereum address when starting your beacon node. …
```

`startDB`: Add log when checkpoint sync.

---

CHANGELOG.md
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go

Reverts prysmaticlabs/prysm#14311
The PR was incorrect because it uses the registration gas limit instead of computing the gas limit and comparing it

Revert "Proposer checks gas limit before accepting builder's bid"

---

CHANGELOG.md
beacon-chain/p2p/encoder/ssz.go
beacon-chain/p2p/encoder/ssz_test.go

Revert Feature
This reverts commit df81fa3e9a5fcfb2550be3bdf70af4726a036f4a. #14692
N.A

Revert "Change Max Payload Size (#14692)"

---

CHANGELOG.md
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Other
When building a block, display the error only if not `nil`.
**Before:**
```
INFO rpc/validator: Finished building block err=None sinceSlotStartTime=0.121271s slot=60 validator=19
```
**After:**
```
INFO rpc/validator: Begin building block sinceSlotStartTime=0.080358s slot=2
```

Display error in "Finished building block" only if error.

---

CHANGELOG.md
beacon-chain/sync/subscriber.go
beacon-chain/sync/subscriber_test.go

Other
This pull requests refactors subnets subscriptions.
It removes `subscribeDynamicWithSubnets` and `subscribeStaticWithSyncSubnets` to only use `subscribeDynamicWithSubnets ` and `subscribeStaticWithSubnets`.
It also paves the way of future data columns (for peerDAS) subscriptions without the need to add specifics functions.

Refactor subnets subscriptions.

---

CHANGELOG.md
beacon-chain/rpc/eth/light-client/BUILD.bazel
beacon-chain/rpc/eth/light-client/handlers.go
beacon-chain/rpc/eth/light-client/handlers_test.go

Feature
Checks if light client feature flag is enabled in rpc handlers. If not, return a 404
Part of #12991 

add light client flag check to rpc handlers

---

CHANGELOG.md
beacon-chain/execution/engine_client.go
beacon-chain/p2p/rpc_topic_mappings.go
beacon-chain/rpc/eth/config/handlers_test.go
beacon-chain/sync/blobs_test.go
beacon-chain/sync/fork_watcher_test.go
beacon-chain/sync/rate_limiter.go
beacon-chain/sync/rate_limiter_test.go
beacon-chain/sync/rpc.go
beacon-chain/sync/rpc_blob_sidecars_by_range.go
beacon-chain/sync/rpc_blob_sidecars_by_root.go
beacon-chain/sync/rpc_send_request.go
beacon-chain/sync/subscriber.go
beacon-chain/sync/validate_blob.go
config/params/config.go
config/params/loader_test.go
config/params/mainnet_config.go

This PR implements [EIP-7691](https://github.com/ethereum/consensus-specs/pull/4023)

Implement EIP7691: Blob throughput increase

---

CHANGELOG.md
beacon-chain/sync/subscriber.go

Bug fix
**Issue before this commit:**
The `currentSlot` in the `getSubnetsToSubscribe` is really set to the current slot.
So, even if the `registerSubscribers` function is called one epoch in advance, as done in `registerForUpcomingFork`, then `currentSlot` will still be - really - the current slot.
==> The new blobs subnets will be subscribed only at the start of the Electra fork, and not one epoch in advance.
**With this commit:**
The new blobs subnets will be effectively subscribed one epoch in advance.
In the following test, we have:
- Deneb: Epoch 0 (genesis)
- Electra: Epoch 2
At epoch 0 (Deneb), the BN registers to all the Deneb blob subnets: ✅
```
...
[2024-12-30 23:38:29]  INFO sync: Subscribed to …
```

`registerSubscribers`: Register blobs subnets correctly.

---

CHANGELOG.md
beacon-chain/core/altair/epoch_spec_test.go
beacon-chain/core/altair/transition.go
beacon-chain/core/electra/transition.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
testing/spectest/shared/altair/epoch_processing/BUILD.bazel
testing/spectest/shared/altair/epoch_processing/slashings.go
testing/spectest/shared/bellatrix/epoch_processing/BUILD.bazel
testing/spectest/shared/bellatrix/epoch_processing/slashings.go
testing/spectest/shared/capella/epoch_processing/BUILD.bazel
testing/spectest/shared/capella/epoch_processing/slashings.go
testing/spectest/shared/deneb/epoch_processing/BUILD.bazel
testing/spectest/shared/deneb/epoch_processing/slashings.go
testing/spectest/shared/electra/epoch_processing/BUILD.bazel
testing/spectest/shared/electra/epoch_processing/slashings.go
testing/spectest/shared/phase0/epoch_processing/BUILD.bazel
testing/spectest/shared/phase0/epoch_processing/slashings.go

Other
Cleans up the API of this method. There is no need for the this second argument, which is derived from the beacon state.

Remove slashingMultiplier argument from ProcessSlashings

---

CHANGELOG.md
beacon-chain/core/electra/registry_updates.go

Documentation
Updates the spec definition with v1.5.0-alpha.10

Electra: Update spec definition for process_registry_updates

---

CHANGELOG.md
config/fieldparams/minimal.go

H/t to @lucassaldanha for noting that the minimal value for the KZG inclusion proof is 10, not 17.  
Reference: [https://github.com/ethereum/consensus-specs/blob/dev/presets/minimal/deneb.yaml](https://github.com/ethereum/consensus-specs/blob/dev/presets/minimal/deneb.yaml)

Fix kzg commitment inclusion proof depth minimal value

---

CHANGELOG.md
beacon-chain/p2p/rpc_topic_mappings.go
beacon-chain/sync/blobs_test.go
beacon-chain/sync/fork_watcher_test.go
beacon-chain/sync/rate_limiter.go
beacon-chain/sync/rate_limiter_test.go
beacon-chain/sync/rpc.go

Reference: https://github.com/ethereum/consensus-specs/pull/4077

Revert `BlobSidecarsByRoot/Range` version to v1

---

.github/workflows/changelog.yml
changelog/kasey_stabilize-unclog.md

Other
The current workflow uses a hardcoded run-id to download the unclog binary as an artifact from the unclog repository. This is fragile because this artifact will be cleared 90 days after it is built, so we'll need to continually update the run-id to the latest cron job run in the unclog repo. I have removed the cron job on the unclog repo and set it up to automatically produce a release whenever a release tag is pushed. This branch switches the workflow to instead use the latest release artifact built by that process.

switch to unclog latest release instead of run artifact

---

beacon-chain/core/time/slot_epoch_test.go
changelog/syjn99_clean-upgrade-tests.md

Other
#14761 cleans `TestCanUpgrade*` beautifully except Altair and Bellatrix. This PR consolidates all similar tests into one test(`TestCanUpgradeTo`).

Clean `TestCanUpgrade*` tests

---

beacon-chain/db/kv/state.go
changelog/manu_fulu_to_blinded.md
config/params/mainnet_config.go
consensus-types/blocks/execution.go
consensus-types/blocks/getters.go

Bug fix
`ToBlinded`: Use Fulu for Fulu fork instead of Electra.

`ToBlinded`: Use Fulu.

---

changelog/james-prysm_handle-pbgeneric-error.md
consensus-types/blocks/getters.go
testing/util/block_test.go

Bug fix
a user reported the tech debt we had since deneb around our pbgenericblock function which returns the generic block type based on the underlying block version. the issue is if we pass a signed deneb ( or greater) block instead of block contents we get a panic during the type conversion. the better way to handle this is to throw an error. This is still a bit of a tech debt item for us in its use but will at least prevent panics in the system.
Fixes #14789

adding in error for generic block check

---

.github/workflows/changelog.yml
changelog/kasey_unclog-v0-1-3.md

Other
Currently the `unclog` changelog management action always uses the latest release from the `OffchainLabs/unclog`. Given that a bad release could wedge prysm's ability to merge PRs it seems like a good idea to version pin.

version pin unclog release

---

changelog/tt_fix_generate_genesis.md
runtime/interop/premine-state.go

h/t to @yahgwai for the report
`Extradata` specified in the execution layer's genesis JSON can be arbitrary in length. However, when used to generate an execution header for the beacon state, we made a deliberate choice to truncate it to 32 bytes instead of leaving it empty. This behavior has been in place since #11809.
#14351 removed the extra data truncation, causing genesis state generation to fail as follows:
```
INFO[0000] Specified a chain config file: /Users/t/go/src/github.com/prysmaticlabs/prysm/config.yml  prefix=genesis
INFO[0000] No genesis time specified, defaulting to now()  prefix=genesis
INFO[0000] Delaying genesis 1736981389 by 15 seconds     prefix=genesis
INFO[0000] Genesis is now 1736981404                     prefix=genesis
INFO[0000] Setting fork geth times …
```

Prysmctl: generate genesis state with correct extra data

---

beacon-chain/core/electra/consolidations.go
beacon-chain/core/electra/effective_balance_updates.go
beacon-chain/core/electra/effective_balance_updates_test.go
beacon-chain/core/electra/upgrade.go
beacon-chain/core/electra/withdrawals.go
beacon-chain/core/fulu/upgrade.go
beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/rpc/eth/events/events_test.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/readonly_validator.go
changelog/potuz_credentials_as_methods.md

This PR removes the helpers `HasCompoundingWithdrawalCredential`, `HasETH1WithdrawalCredential` and `HasExecutionWithdrawalCredentials`  to exposed methods within the `ReadOnlyValidator` interface. 
It also fixes the naming to be coherent in number.

move credential helpers to ReadOnlyValidator methods

---

changelog/hidewrong_use_time.DateTime.md
cmd/beacon-chain/main.go
cmd/client-stats/main.go
cmd/validator/main.go
tools/pcli/main.go

> Other
use time.DateTime 
Fixes #

refactor: use time.DateTime

---

beacon-chain/p2p/types/object_mapping.go
beacon-chain/sync/decode_pubsub_test.go
changelog/radek_fulu-object-mapping.md

Bug fix
The attestation map that holds fork-->type mappings for our p2p code has the incorrect type for Fulu. It should be `SingleAttestation`, not `AttestationElectra`.

Use `SingleAttestation` for Fulu in p2p attestation map

---

beacon-chain/sync/metrics.go
beacon-chain/sync/validate_data_column.go

Feature
This PR adds gossip verification metrics align with the [PeerDAS metrics specs](https://github.com/ethereum/beacon-metrics/pull/14):
- `beacon_data_column_sidecar_processing_requests_total`
- `beacon_data_column_sidecar_processing_successes_total`
- `beacon_data_column_sidecar_gossip_verification_milliseconds`
Fixes (partially) #14129

Add PeerDAS gossip verification metrics

---

beacon-chain/verification/data_column.go
beacon-chain/verification/metrics.go

Feature
This PR adds reconstruction metrics align with the [PeerDAS metrics specs](https://github.com/ethereum/beacon-metrics/pull/14):
- `beacon_data_column_sidecar_inclusion_proof_verification_milliseconds`
- `beacon_kzg_verification_data_column_batch_milliseconds`
Fixes (partially) #14129

Add PeerDAS kzg and inclusion proof verification metrics

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/execution/engine_client_focil.go

This PR makes the naive interop work between prototypes in Prysm and Geth.

Make the naive interop work betweem Prysm and Geth

---

beacon-chain/core/fulu/BUILD.bazel
beacon-chain/core/fulu/upgrade.go
beacon-chain/core/fulu/upgrade_test.go
changelog/manu_fulu_fork.md

Bug fix
`UpgradeToFulu`: Respect the [specification](https://github.com/ethereum/consensus-specs/blob/188a2ff8183d19dd79d87308bb42906ab1dd3a31/specs/fulu/fork.md#upgrading-the-state).
Before this commit, the `UpgradeToFulu` function did not really respect the specification. This commit fixes that.
How can we be sure now the specification is really respected?
As long as the equivalent of Electra [Spectests](https://github.com/ethereum/consensus-spec-tests/tree/master/tests/mainnet/electra/fork/fork/pyspec_tests) are not released, we cannot be sure.
However, with this commit, Prysm and Lighthouse do agree with the post state after the Fulu fork (which is not the case without this commit).
So either Prysm and Lighthouse …

`UpgradeToFulu`: Respect the specification.

---

beacon-chain/p2p/subnets.go
changelog/manu_blob_subnets_node_filter.md

Bug fix
Before this commit, this kind of logs were possible:
```
[2025-01-22 17:18:48]  DEBUG sync: Could not search for peers error=node filter: no subnet exists for provided topic: /eth2/d1f05cae/blob_sidecar_0/ssz_snappy
[2025-01-22 17:18:48]  DEBUG sync: Could not search for peers error=node filter: no subnet exists for provided topic: /eth2/d1f05cae/blob_sidecar_1/ssz_snappy
[2025-01-22 17:18:48]  DEBUG sync: Could not search for peers error=node filter: no subnet exists for provided topic: /eth2/d1f05cae/blob_sidecar_2/ssz_snappy
[2025-01-22 17:18:48]  DEBUG sync: Could not search for peers error=node filter: no subnet exists for provided topic: /eth2/d1f05cae/blob_sidecar_3/ssz_snappy
[2025-01-22 17:18:48] …
```

`nodeFilter`: Add `GossipBlobSidecarMessage` case.

---

beacon-chain/core/electra/deposits.go
changelog/tt_fix_pending_deposits.md

This PR ensures that a pending deposit can create a new validator even if an invalid deposit exists before a valid one under the same public key. It checks the state directly instead of the cache.

Fix batch deposit processing by retrieving validators from state

---

beacon-chain/blockchain/process_block_test.go
beacon-chain/core/blocks/attester_slashing_test.go
beacon-chain/core/transition/transition.go
beacon-chain/core/transition/transition_test.go
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/key.go
beacon-chain/db/kv/lightclient.go
beacon-chain/db/kv/schema.go
beacon-chain/db/kv/state.go
beacon-chain/db/slasherkv/BUILD.bazel
beacon-chain/db/slasherkv/pruning_test.go
beacon-chain/db/slasherkv/slasher.go
beacon-chain/db/slasherkv/slasher_test.go
beacon-chain/rpc/eth/events/events_test.go
changelog/radek_eip-7549-slasher-pt1.md
changelog/radek_eip-7549-slasher-pt2.md
config/params/configset_test.go
config/params/loader_test.go
config/params/testnet_config_test.go
testing/util/attestation.go
validator/client/attest.go

Feature
Updates several pieces of the codebase for Electra slashing support:
- Tests cases in several packages
- Bug fix in `transition.go`, where the maximum number of slashings in a block was always the Phase0 config value
- Add electra key check for attestation encoding/decoding in SlasherDB
- Support for Electra slashings in Beacon API events
- Enable slashing protection check in the VC

Handle `AttesterSlashingElectra` everywhere in the codebase

---

beacon-chain/core/electra/churn_test.go
changelog/pvl_electra_mutation.md

Other
Using mutation testing to find various issues.
```
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍┅
┃ 🧬 Mutant survived: beacon-chain/core/electra/churn.go → Arithmetic
┠┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
┃ --- beacon-chain/core/electra/churn.go (original)
┃ +++ beacon-chain/core/electra/churn.go (mutated with 'Arithmetic')
┃ @@ -64,7 +64,7 @@
┃       if consolidationBalance > consolidationBalanceToConsume {
┃               balanceToProcess := consolidationBalance - consolidationBalanceToConsume
┃               // additional_epochs = (balance_to_process - 1) // per_epoch_consolidation_churn + 1
┃ -             additionalEpochs, err := math.Div64(uint64(balanceToProcess-1), …
```

electra: Improve test coverage for beacon-chain/core/electra/churn.go

---

beacon-chain/core/electra/deposits.go
beacon-chain/core/electra/deposits_test.go
changelog/tt_deposit_req_nil_check.md

Deposit request nil check was only applied under `requestsStartIndex == params.BeaconConfig().UnsetDepositRequestsStartIndex`, but it should be applied under all conditions. Moving it outside the if condition

Move deposit request nil check for all

---

beacon-chain/rpc/eth/blob/BUILD.bazel
beacon-chain/rpc/eth/blob/handlers.go
beacon-chain/rpc/eth/blob/handlers_test.go
changelog/james-prysm_electra-blobs-api.md

Feature
implements https://github.com/ethereum/beacon-APIs/pull/488
- Adds version header to API
- Verifies that we can handle the electra block and new blob limit
- Adds unit tests
- Fixes nil block case
Fixes #14847

Electra blob sidecar API update

---

changelog/kasey_warn-hist-state-rep.md
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Documentation
logs the following warning if `--enable-historical-state-representation`
```
WARN flags: --enable-historical-state-representation is pending deprecation and will be removed in the next release. This node will need to be resynced once the flag is removed.
```
This is needed because we have decided to deprecate this feature and want to notify users ahead of time, because removing the feature code will render their state database unusable.

warn that --enable-historical-state-representation is up for deprecation

---

beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go

**Please read commit by commit**
Fix edge case where initial sync was blocked because of a bug in the `buildBwbSlices` function when, at the same time, we reach the batch limit **and** the set of missing columns is changing.
The first commit adds a new (failing) test case.
The second commit modifies the `buildBwbSlices` to comply with the newsly introduced test case.
The other commits are cosmetics.

Peer das sync empty requests

---

CHANGELOG.md
changelog/taran_geth_v1.14.13_update.md
deps.bzl
go.mod
go.sum

This PR updates Geth dependency to v1.14.13

Update go-ethereum to v1.14.13

---

api/server/structs/BUILD.bazel
api/server/structs/conversions.go
api/server/structs/conversions_test.go
changelog/james-prysm_nil-check-to-consensus.md

Bug fix
ToConsensus functions convert json representations to the consensus object, this conversion should validate the json for lengths and should try to check for nils or other unsafe data.
Fixes #

nil checks on ToConsensus() functions

---

changelog/potuz_fix_forkmaps_log.md
config/params/loader.go

when we load a config file, we call eventually UnmarshalConfig which first copies the mainnet config by calling MainnetConfig().Copy().
MainnetConfig() calls InitializeForkSchedule  which in turn calls to configForkSchedule(b) and configForkNames(b) so these maps are made from the default config and not from the config file. After that the unmarshaller finishes changing the config values, this will read the new fork versions and epochs from the config file, but not change the maps So the config file values printed at the end have bogus maps that do not corresponds to the config file. 
What worries me is that even if this is corrected later, this function UnmarshalConfig is returning a bogus config in inconsistent state.

Fix startup log for config file values

---

beacon-chain/operations/slashings/service_new.go
changelog/potuz_overflow_slashings.md

The overflow of  #14844 should not be treated as an error.

Do not error on overflow when converting slashings

---

beacon-chain/core/electra/churn_test.go
beacon-chain/db/kv/blocks_test.go
beacon-chain/sync/rpc_blob_sidecars_by_range.go
beacon-chain/sync/sync_test.go
changelog/nisdas_increase_electra_limits.md
cmd/beacon-chain/flags/base.go

Networking Limit Change
In Electra we have `EIP-7691` included which changes the blob target per block to 6 and the max to 9. With these parameters changing, Prysm nodes serving blobs to syncing nodes after Electra will need to serve more blobs  beyond the current rate limits per batch if blocks are consistently filled with the maximum amount of blob transactions. 
With the standard block batch size among clients being 64, the maximum amount of blobs a prysm node would have to serve per batch is 574. For that reason we have changed the `blob-batch-limit` and the `blob-burst-factor` to be able to satisfy this constraint. 
N.A

Set New Blob Limits For Electra

---

beacon-chain/execution/engine_client_focil.go

This PR changes the IL engine API calls to communicate IL with EL in hex.

Communicate IL with EL in hex

---

beacon-chain/state/state-native/setters_churn.go
beacon-chain/state/state-native/setters_consolidation.go
beacon-chain/state/state-native/setters_consolidation_test.go
beacon-chain/state/state-native/setters_deposit_requests.go
beacon-chain/state/state-native/setters_deposits.go
beacon-chain/state/state-native/setters_deposits_test.go
beacon-chain/state/state-native/setters_withdrawal.go
beacon-chain/state/state-native/setters_withdrawal_test.go
beacon-chain/state/state-native/state_trie.go
changelog/tt_fix_electra_state.md

This PR fixes: 
- **Pending queue objects:** References were not shared correctly. If the reference count is greater than 1 (meaning another process is holding it), a copy is required.  
- **Rebuild trie misuse:** It was incorrectly applied to fields like `uint64`, which should not be rebuilt this way.  
- **Dirty indices:** Now properly added after appending.
Note to the reviewers: please review `DequeuePendingPartialWithdrawals`, I added a unit test, the current implementation seems ok as test passes, but please double check no action is needed there

Fix electra state to safe share references on pending fields when append

---

beacon-chain/execution/engine_client.go

There are three new engine APIs so there should be three conversions. Previous commit missed one.

Add missing hex conversion

---

beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
beacon-chain/rpc/eth/config/handlers_test.go
changelog/radek_add-missing-config-values.md
config/params/config.go
config/params/loader_test.go
config/params/mainnet_config.go
config/params/minimal_config.go

Bug fix
Adds missing config values (`'MAX_BYTES_PER_TRANSACTION', 'MAX_TRANSACTIONS_PER_PAYLOAD', 'MAX_BLOB_COMMITMENTS_PER_BLOCK', 'BYTES_PER_LOGS_BLOOM', 'MAX_EXTRA_DATA_BYTES', 'FIELD_ELEMENTS_PER_BLOB', 'KZG_COMMITMENT_INCLUSION_PROOF_DEPTH'`) and returns these values from `/eth/v1/config/spec`
Also renames `'REORG_WEIGHT_THRESHOLD'` to `'REORG_HEAD_WEIGHT_THRESHOLD'` to match the spec.
Fixes #14863

Add missing config values from the spec

---

changelog/tt_add_pectra_testnet_dates.md
config/params/testnet_holesky_config.go
config/params/testnet_sepolia_config.go

- Holesky upgrades at slot 3710976 → Feb 24, 21:55 UTC
- Sepolia upgrades at slot 7118848 → Mar 5, 07:29 UTC

Add pectra testnet dates

---

beacon-chain/rpc/eth/beacon/handlers.go
beacon-chain/rpc/eth/beacon/handlers_test.go
changelog/james-prysm_fix-block-api-electra.md

Bug fix
The following error was reported by Chris Berry on the vouch team on POST request endpoint ` /eth/v2/beacon/blocks`
```
{
"message": "rpc error: code = Internal desc = Could not broadcast/receive block: broadcast/receive block failed: failed to validate consensus state transition function: could not execute state transition: could not process block: state and block are different version. 5 != 6",
"code": 500
}
```
this error is caused by how we have handled blocks in our publish block function. a new fork block type ( FULU) was added which has the same structure as the electra block type, the existing code believed the block was a fulu type.
This fix handles the API in 2 different ways. 
- v2 requires a …

fix: /eth/v2/beacon/blocks post api to handle electra and fulu blocks correctly 

---

beacon-chain/sync/rpc_send_request_test.go
changelog/tt_blob_by_range_electra_test.md

Covers blobs by range electra the following conditions:
```go
maxBlobsPerBlock := uint64(params.BeaconConfig().MaxBlobsPerBlock(req.StartSlot + primitives.Slot(req.Count)))
max := params.BeaconConfig().MaxRequestBlobSidecars
if slots.ToEpoch(req.StartSlot) >= params.BeaconConfig().ElectraForkEpoch {
max = params.BeaconConfig().MaxRequestBlobSidecarsElectra
}
if max > req.Count*maxBlobsPerBlock {
max = req.Count * maxBlobsPerBlock
}
```

Add blobs by range electra test

---

beacon-chain/sync/rpc_chunked_response.go

This PR fixes:
```
[2025-02-11 01:21:28]  DEBUG sync: Could not handle p2p RPC error=block version 7 is not recognized: cannot determine context bytes for unrecognized object peer=16Uiu2HAmMC87uxtpjUPUXYyXZZpefc8qX5wzVxuYnFWF5mytrAAf 
```

Fix cannot determine context bytes for unrecognized object

---

beacon-chain/rpc/lookup/BUILD.bazel
beacon-chain/rpc/lookup/blocker.go
beacon-chain/rpc/lookup/blocker_test.go
changelog/radek_blob-404.md

Other
- Currently we return an `500 InternalServerError` when a blob for a requested index is not found. It would be more useful to return a 404 instead, letting the user know that we don't have the blob, not that something went wrong when trying to fetch it.
- Additional information in some errors, such as block root or slot number

Improve blobs Beacon API endpoint
