prysmaticlabs/prysm

sharding/client.go
sharding/client_test.go
sharding/contracts/README.md
sharding/contracts/validator_manager.go
sharding/vmc.go

Using the WIP solidity files from PR #4, update the sharding client to use the generated go bindings. 
I've also included a readme to describe how these can be generated when #4 is finalized and ready to merge.
~~Tests are still broken / not finalized, but will be completed when the sharding client has more functionality.~~ Fixed it.

Use generated go bindings for validator management contract

---

cmd/geth/shardingcmd.go
sharding/client.go

In windows the IPC endpoint opens in //./pipe/geth.ipc than in the data directory. IPCPath flag is added so that it can be specified when running the sharding client

Add IPC Path Flag to sharding client

---

sharding/collator.go

Header 5418 was skipped and warning message was logged
Header 5419 has the client address, get eligible proposer was called
./build/bin/geth shard --datadir=../datadir/ --password=password.txt
INFO [02-26|14:45:16] Starting sharding client
INFO [02-26|14:45:16] No validator management contract found at 0x0000000000000000000000000000000000000000. Deploying new contract.
INFO [02-26|14:45:44] New contract deployed at 0xbffa8d2f672403052d84769F08a83A2B5C5e17D7
INFO [02-26|14:45:46] Deposited 100ETH into contract with transaction hash: 0x54382051352db9abbf4fdd1b1e4177788fa92f9755130c3790223ac3569c4c8b
INFO [02-26|14:45:46] Listening for new headers...
**INFO [02-26|14:45:51] Received new header: 5418
WARN [02-26|14:45:53] client not in validator set, re-try next block
INFO [02-26|14:46:06] …

verify the client is in validator pool before querying for eligible proposer

---

sharding/client.go
sharding/collator.go
sharding/collator_test.go

This addresses #42. Tested with both scenarios:
1) correct password
`❰terencetsao❙~/prysmaticlabs/geth-sharding(git✱≠refactorAccounts)❱✘≻
./build/bin/geth shard --datadir=../datadir/ --password=password.txt
INFO [02-27|09:00:31] Starting sharding client
INFO [02-27|09:00:32] No validator management contract found at 0x0000000000000000000000000000000000000000. Deploying new contract.
INFO [02-27|09:00:49] New contract deployed at 0xe5126F4b9d7D6F9eB1B4954519469ccbf4fe52Cc
INFO [02-27|09:00:49] Deposited 100ETH into contract with transaction hash: 0xf89755adc63b82ccfd8a58c9911e1507d3d083f4b8bf6d5f87819031170e3caf
INFO [02-27|09:00:49] Listening for new headers...
`
2) incorrect password
`./build/bin/geth shard --datadir=../datadir/ --password=password.txt
INFO [02-27|09:01:20] Starting …

refactor account interface, and unlock account when client is created

---

cmd/geth/main.go
cmd/geth/shardingcmd.go
cmd/utils/flags.go
sharding/vmc.go

To be consistent with the documentation in #51, I propose we change the main geth entrypoint to become a validator to the following:
```
$ geth sharding-validator --deposit --datadir /path/to/your/datadir --password /path/to/your/password.txt --networkid 12345
```
Just changed all the necessary items and this now works. Tests pass.

Proposing cli entrypoint name change as sharding-validator instead of geth shard --validator

---

README.md
sharding/README.md

As an extension to #67, I fixed up some minor outstanding instances of old words such as validator and modified the diagrams to reflect our new structure.

Modified Diagrams to Reflect Glossary Changes

---

sharding/client/client.go
sharding/collator/collator.go
sharding/collator/collator_test.go

Added test for the basic functionality of joinCollatorPool
Also renamed CreateTXOps to CreateTXOpts to match the `TransactOpts` type

Collator: add test for joinCollatorPool

---

sharding/client/client.go
sharding/collation.go
sharding/config.go
sharding/notary/notary_client.go
sharding/proposer/proposer_client.go

Hi all,
This is a quick PR done to fix the comment formatting across our packages. I always get warnings from my linters in VSCode due to the problem of not commenting exported types. This is something we should do and is best practice. For example, if I create a type:
```go
type Collation struct {
header *CollationHeader
body *CollationBody
}
```
We have to add a comment above that begins with the name of the type as follows:
```go
// Collation defines the base struct for a sharding primitive
type Collation struct {
header *CollationHeader
body *CollationBody
}
```
Also removed punctuation from some comments in order to be consistent with our other comments throughout our packages.

Fixing Comment Formatting According to Best Linter Practices

---

.travis.yml

This should reduce the amount of flaky test failures.

Only run travis tests on go 1.10

---

sharding/database/inmemory.go

Added a simple mutex to make updating or deleting a value from the in-memory, kv store concurrency safe. Quick fix.

Making In-Memory DB Concurrency Safe

---

sharding/collation.go
sharding/collation_test.go

Collation serializer function requires a point receiver, it should just be a pure function. See #134 
I updated collation serializer function to be a pure function so we can generate the data (header, body, txs) upfront to construct a collation. And I verified this did not break the existing tests

Serialize Function Should be Pure

---

sharding/collation_test.go

Initial results:
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/sharding
BenchmarkSerialization10-4                 20000             84624 ns/op           97347 B/op        565 allocs/op
BenchmarkSerialization100-4                 2000            820836 ns/op          994422 B/op       5528 allocs/op
BenchmarkSerialization1000-4                 200           8076776 ns/op        10630373 B/op      55047 allocs/op
BenchmarkSerialization10000-4                  5         242064047 ns/op        244503252 B/op    350102 allocs/op
PASS
ok      github.com/ethereum/go-ethereum/sharding        9.118s
```
Here's a comparison against other protocols:
Protocol Buffers Marshal: *819 ns/op*
Protocol Buffers Unmarshal: *1163 ns/op*
JSON Marshal: *3316 ns/op*
JSON Unmarshal: *7196 …

Benchmarking Serializer

---

build/ci.go

Linter in Travis has failed due to following:
> WARNING: deadline exceeded by linter goimports (try increasing --deadline)
> WARNING: deadline exceeded by linter varcheck (try increasing --deadline)
> WARNING: deadline exceeded by linter vet (try increasing --deadline)
Set Gometallinter deadline to 10 mins so it doesn't time out and cause Travis to fail

Set Gometallinter Deadline to 10 Minutes 

---

sharding/database/database.go
sharding/database/database_test.go
sharding/database/inmemory.go
sharding/database/inmemory_test.go
sharding/interfaces.go
sharding/node/node.go
sharding/notary/service.go
sharding/notary/service_test.go
sharding/proposer/service.go
sharding/shard.go
sharding/shard_test.go

Hi all,
This PR references #109 in order to use a persistent, key-value db as a shard backend that is stored to a local folder in the user's `DataDir` called `shardchaindata` as geth currently does with the `eth` and `les` clients.

Use Persistent Key-Val DB for Shard Node Collation Storage

---

sharding/collation.go
sharding/collation_test.go
sharding/utils/marshal.go
sharding/utils/marshal_test.go

Here's the numbers on my computer for the existing benchmark with 150 byte txs
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/sharding
BenchmarkSerialization10-12                30000             69008 ns/op           27805 B/op        353 allocs/op
BenchmarkSerialization100-12                5000            739374 ns/op          324040 B/op       3425 allocs/op
BenchmarkSerialization1000-12                300           5558360 ns/op         3127289 B/op      34044 allocs/op
BenchmarkSerialization10000-12                30          48292393 ns/op        63835295 B/op     160091 allocs/op
PASS
```
Here's the numbers for the equivalent benchmark on this branch:
```
goos: linux
goarch: amd64
pkg: github.com/ethereum/go-ethereum/sharding
BenchmarkSerializeRoundtrip10-12 …
```

Serialization Perf

---

sharding/database/database.go
sharding/database/database_test.go
sharding/database/inmemory.go
sharding/database/inmemory_test.go
sharding/node/backend.go
sharding/notary/service.go
sharding/observer/service.go
sharding/proposer/service.go
sharding/shard.go
sharding/shard_test.go

This PR is to address #156. With shardEthereum as a container of every single sharding service, we can integrate our DB service shardChainDB into our shardEthereum container. We'll integrate sharding/database subpackage by giving shardEthereum levelDB support or other key-value stores (leveldb, badger, or others) support. We'll also verify shardDb instance can be used across different services
work flow:

Implement ShardChainDB Into the ShardEthereum Instance

---

sharding/interfaces.go
sharding/node/backend.go
sharding/notary/service.go
sharding/observer/service.go
sharding/p2p/service.go
sharding/proposer/service.go
sharding/txpool/service.go

Hi all,
This is a PR to handle graceful shutdown of the sharding node upon signal interrupts, using similar mechanisms to Geth with respect to even including ["panic mode"](https://github.com/ethereum/go-ethereum/blob/6cf0ab38bd0af77d81aad4c104979cebee9e3e63/cmd/utils/cmd.go#L74) where a user can keep doing ctrl-c to force a shutdown.
This PR also converts the current actor services (proposers, observers, notaries) into non-blocking services via goroutines. Error handling is done within these goroutines to prevent from blocking the main sharding node thread.

Graceful Shutdown on SIGINT and Non-Blocking Services

---

sharding/mainchain/interfaces.go
sharding/mainchain/smc_client.go
sharding/mainchain/smc_client_test.go
sharding/notary/notary.go
sharding/notary/service.go
sharding/notary/service_test.go
sharding/proposer/proposer.go
sharding/proposer/service.go
sharding/proposer/service_test.go

Hi all,
This is a PR referencing #183 which aims to use effective go practices of using small, but useful interfaces in our code.
We had giant monolith interfaces such `Client` that mapped 1-to-1 to the structs implementing them. When writing tests, we had to mock a lot of unnecessary methods and were no better off than using the struct itself.
We make smaller interfaces that only require specific, useful mocks for the tests in which they are used. Ex:
```go
// ContractCaller defines an interface that can read from a contract on the
// Ethereum mainchain as well as call its read-only methods and functions.
type ContractCaller interface {
SMCCaller() *contracts.SMCCaller
GetShardCount() (int64, error)
Account() *accounts.Account
}
// ContractTransactor defines an interface that can …
```

Simplify Interfaces Into Smaller, Useful Ones

---

sharding/utils/log_helper_test.go

This can be used to verify log messages occurred in a test.
Example:
```golang
func TestSomething (t *testing.T) {
h := &utils.LogHandler{t:t}
logger.SetHandler(h) // logger is a package variable of type log.Logger
MethodThatLogsSomething()
h.VerifyLogMsg("Something")
}
```

Add a log handler helper

---

sharding/database/database.go
sharding/database/database_test.go
sharding/internal/log_helper.go
sharding/node/backend.go
sharding/notary/service.go
sharding/observer/service.go
sharding/proposer/service.go

This fixes #187 
As discussed yesterday,`ShardchainDB` should not be a value in `ShardEthereum`. It should just be a registered service. This was fixed by registering ethdb's leveldb as a service via `registerShardChainDB` and pass the service to the actors.

Implement shardchainDB as a service

---

sharding/database/database.go
sharding/node/backend.go
sharding/observer/service.go
sharding/observer/service_test.go

The goal of this PR is to increase test coverage for observer package. There's currently no test and it's at 0%
```
❰terencetsao❙ ≻ go test -cover
testing: warning: no tests to run
PASS
coverage: 0.0% of statements
ok  	github.com/ethereum/go-ethereum/sharding/observer	0.136s
```

Increase Observer Test Coverage

---

sharding/proposer/service_test.go

Continue working on #202. This PR refactors proposer tests to use internal mock client. Got rid of 77 lines. Yay!

Use Internal Mock Client for Proposer Tests

---

sharding/internal/client_helper.go
sharding/notary/service_test.go

Continue working on #202. This PR refactors notary tests to use internal mock client.

Use Internal Mock Client for Notary Tests

---

sharding/node/backend.go
sharding/simulator/service.go
sharding/simulator/service_test.go
sharding/syncer/service.go
sharding/syncer/service_test.go

Previously, the `Simulator` struct in the simulator service would take in a `client *mainchain.SMCClient` as an input argument, making testing extremely difficult as this encompasses an rpcClient among other complex structures. This would lead us to some nil pointer errors when running tests as we would provide an incomplete `mainchain.SMCClient` to the struct initializer.
This was fixed by using the pattern of smaller interfaces in our service initializers in the `simulator` and `syncer` packages. Now, `NewSimulator` looks like this:
```go
func NewSimulator(config *params.Config, reader mainchain.Reader, fetcher mainchain.RecordFetcher, p2p *p2p.Server, shardID int, delay time.Duration) (*Simulator, error)
```
Making it easy to test with simple mocks.

Use Small Interfaces to Fix Nil Pointer Errors in Simulator/Syncer Tests

---

cmd/geth/shardingcmd.go

This gives the sharding command the following functionality:
```
LOGGING AND DEBUGGING OPTIONS:
--verbosity value         Logging verbosity: 0=silent, 1=error, 2=warn, 3=info, 4=debug, 5=detail (default: 3)
--vmodule value           Per-module verbosity: comma-separated list of <pattern>=<level> (e.g. eth/*=5,p2p=4)
--backtrace value         Request a stack trace at a specific logging statement (e.g. "block.go:271")
--debug                   Prepends log messages with call-site location (file and line number)
--pprof                   Enable the pprof HTTP server
--pprofaddr value         pprof HTTP server listening interface (default: "127.0.0.1")
--pprofport value         pprof HTTP server listening port (default: 6060)
--memprofilerate value    Turn on memory profiling with the given …
```

Add debug flags to shardingcmd

---

sharding/database/database.go
sharding/database/database_test.go
sharding/database/inmemory.go
sharding/node/backend.go
sharding/p2p/service.go
sharding/simulator/service.go
sharding/simulator/service_test.go
sharding/syncer/service.go
sharding/syncer/service_test.go
sharding/utils/service.go
sharding/utils/service_test.go

Hi all,
This resolves #197. Previously, we were using the following pattern in goroutines which made testing a bit hard.
```go
func (s *Syncer) someGoroutine(arg1, arg2, arg3, arg4, ..) {
ch := make(chan p2p.Message, 100)
for {
select {
// Makes sure to close this goroutine when the service stops.
case <-arg1:
return
case req := <-arg2
doStuff(arg3, arg4)
}
}
}
```
We had a massive number of arguments to our functions where we could have simply been using their associated struct fields and mocking them during the testing process. This PR fixes this issue. Props to @rawfalafel for pointing in the right direction.

Simplify Goroutines for Better Testing

---

sharding/database/database.go
sharding/interfaces.go
sharding/node/backend.go
sharding/notary/service.go
sharding/observer/service.go
sharding/proposer/service.go
sharding/simulator/service.go
sharding/simulator/service_test.go
sharding/syncer/service.go

Hi all,
This resolves #214 and #215.
Previously, we were starting each service in our sharding node by simply iterating over the service registry map.
```go
for _, kind := range s.serviceTypes {
// Start each service in order of registration.
s.services[kind].Start()
}
```
Go, however, does not order keys in maps, so we are not preserving the order of registration of each service. That is, the shardDB could be initialized last and we do not want this to happen.
Additionally, our previous approach to a sharding registry would pass in a copy of each dependency into corresponding services instead of passing in a reference. This would mean that if a service would set a property in its Start function, its dependent services would not see this updated property as they have a copy but not a …

Simplify Service Registry, Pass in References as Dependencies to Prevent Nil Pointer Errors

---

sharding/proposer/proposer.go
sharding/proposer/service.go
sharding/proposer/service_test.go
sharding/syncer/handlers_test.go

This fixes #209. When we send an addHeader transaction, we don't check whether the transaction gets mined before proceeding to the next step. This PR addressed the bug by adding a `WaitForTransaction` function after `AddHeader` gets called. The `WaitForTransaction` time out duration is set for 5 minutes for Ruby Release. The `AddHeader` logic will change when we bring in beacon chain, let's not worry on the hard coded time out.

Check AddHeader Transaction Gets Mined

---

sharding/internal/log_helper.go
sharding/simulator/service.go
sharding/simulator/service_test.go

Here's the race condition causing the tests to be flaky:
```
simulator.cancel()
// The context should have been canceled.
if simulator.ctx.Err() == nil {
t.Error("Context was not canceled")
}
```
The docs for [CancelFunc](https://golang.org/pkg/context/#CancelFunc) state that `cancel` is non-blocking, meaning that the next line in the test isn't guaranteed to run after `cancel` executes. So what's the fix? Pass the channel returned by `ctx.Done()` into the goroutine and control the channel in the test. Here's what that would look like:
```
doneChan := make(chan, struct{})
go simulator.simulateNotaryRequests(..., doneChan)
doneChan <- struct{}{} // this is equivalent to simulator.cancel()
h.VerifyLogMsg("Simulator context closed, exiting goroutine") // check logs instead of ctx.Err()
``` …

Fix race condition in simulator tests

---

.travis-bazelrc

This is blocking other PRs so lets remove it until it can be resolved effectively.

Disable remote caching for now on Travis

---

beacon-chain/BUILD.bazel
beacon-chain/main.go
beacon-chain/node/BUILD.bazel
beacon-chain/node/node.go
beacon-chain/node/node_test.go
beacon-chain/params/BUILD.bazel
beacon-chain/params/config.go
sharding/BUILD.bazel
sharding/main.go
sharding/node/BUILD.bazel
sharding/node/backend.go
shared/BUILD.bazel
shared/service_registry.go
shared/service_registry_test.go
shared/types.go

Hi all,
This resolves #262. This PR abstracts the service registry structure we have been using for a sharding node into the shared package where it is well-documented and tested. We then import this service registry to use in the creation of a beacon chain node as well as in a sharding client. I have also added a main entry point for a beacon node which can be built using:
```
bazel build //beacon-chain/...
```
and then the binary can be run:
```
./bazel-bin/beacon-chain/YOURARCHITECTURE/beacon-chain
```

Abstract Service Registry Into Shared Folder, Add Beacon Node and Beacon Entry Point

---

beacon-chain/BUILD.bazel
beacon-chain/main.go
beacon-chain/node/BUILD.bazel
beacon-chain/node/node.go
sharding/BUILD.bazel
sharding/main.go
sharding/node/BUILD.bazel
sharding/node/backend.go
sharding/utils/BUILD.bazel
sharding/utils/flags.go
shared/debug/BUILD.bazel
shared/debug/debug.go

Hi all,
This PR resolves #274 and attaches debug flags to the beacon node endpoint. It also calls debug.Exit() to ensure CPU profile data and trace are flushed. Geth's license header is kept in the debug.go file to give credit.

Abstract Debug Into Shared/Debug and Reinclude Debug.Exit()

---

WORKSPACE

Maybe solves some issues on MacOS. Not sure yet, but there are some good fixes in this release

Update rules_go and gazelle to 0.13.0

---

WORKSPACE

I tested this on a 2015 Macbook with Bazel `0.14.1`.
`bazel test //...` was able to build and execute tests appropriately. 
```
$ ~/bin/bazel version
Build label: 0.14.1
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Jun 8 12:17:00 2018 (1528460220)
Build timestamp: 1528460220
Build timestamp as int: 1528460220
```
```
$ ~/bin/bazel test //... --flaky_test_attempts=3
INFO: Analysed 45 targets (0 packages loaded).
INFO: Found 27 targets and 18 test targets...
INFO: Elapsed time: 126.255s, Critical Path: 125.18s
INFO: 2 processes, darwin-sandbox.
INFO: Build completed successfully, 3 total actions
//beacon-chain/node:go_default_test                             (cached) PASSED in 0.5s …
```

Update go-ethereum with fix for mac OS builds

---

README.md

Updated in readme to use the binary intead of `bazel run` since `bazel run` isnt very good

Update Readme to Execute Binary Instead of Bazel Run

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/core.go
beacon-chain/blockchain/core_test.go
beacon-chain/params/config.go

To kick off on the beacon state transition function, we first implement a pure function to shuffle validator indices. This function simply shuffles an array of indices based on a random seed. For example:
```
validatorCount := 5
preShuffle := [0,1,2,3,4]
postShuffle: = [1,0,4,2,3]
```
Later, `getAttesters` and `getProposer` functions will use this shuffle function to return the list of validators.
References:
https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ?view#Helper-functions
https://github.com/ethereum/beacon_chain/blob/master/beacon_chain/state/state_transition.py#L43

Implemented Shuffle Function for Beacon State

---

client/p2p/service_test.go

This PR is a quick fix to a linter error in the p2p service_test which gives us an incorrect type conversion linter message.

Fix P2P Linter Error

---

client/CONTRIBUTING.md

The README.MD and READINGS.MD links were broken in the CONTRIBUTING.MD doc, I've fixed both.

Fixed broken links in CONTRIBUTING.MD

---

client/main.go
client/node/backend.go
shared/cmd/flags.go

Currently sharding client only supports IPC interface to a main chain node. In this PR, we added RPC interface support so multiple processes can work together.
`--rpc` is the flag name, Example:
`--rpc http://localhost:8545/ --password ./password.txt --datadir ./data`

Add RPC Support to Client

---

.travis-bazelrc
WORKSPACE
shared/p2p/BUILD.bazel
shared/p2p/feed.go
shared/p2p/feed_concurrent_test.go
shared/p2p/feed_test.go
shared/p2p/service.go
shared/p2p/service_test.go

While working on #316, after enabling the commented proposer tests I'm eventually getting:
```
fatal error: concurrent map writes
goroutine 96 [running]:
runtime.throw(0xe5e088, 0x15)
GOROOT/src/runtime/panic.go:616 +0x81 fp=0xc4204a9c50 sp=0xc4204a9c30 pc=0x42e1e1
runtime.mapassign(0xcf8760, 0xc420313620, 0xc4204a9d48, 0x171bd00)
GOROOT/src/runtime/hashmap.go:607 +0x553 fp=0xc4204a9ce0 sp=0xc4204a9c50 pc=0x40b113
github.com/prysmaticlabs/prysm/shared/p2p.(*Server).Feed(0xc42004ccc0, 0xe25860, 0xdd11e0, 0x0)
shared/p2p/feed.go:41 +0x176 fp=0xc4204a9d78 sp=0xc4204a9ce0 pc=0xb66ef6
github.com/prysmaticlabs/prysm/shared/p2p.(*Server).subscribeToTopic(0xc42004ccc0, 0x1, 0x10659c0, 0xdd11e0)
shared/p2p/service.go:141 +0x17f fp=0xc4204a9fc0 sp=0xc4204a9d78 pc=0xb6800f
runtime.goexit() …
```

Add Mutex on Top of p2p Feeds Map

---

.travis.yml
beacon-chain/network/BUILD.bazel
beacon-chain/sync/BUILD.bazel
check_visibility.sh

Example with failing visibility (fixed in this PR):
```text
//beacon-chain/sync:go_default_library
//beacon-chain/network:go_default_library
FAIL: The above targets belong to protected packages and the targets are visible outside of their package!
Please reduce the target visibility.
```
Otherwise you should see this:
```text
INFO: Empty results
OK: Visibility is good.
```

Add script to ensure visibility is OK

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/core.go
beacon-chain/blockchain/core_test.go
beacon-chain/sync/service.go
beacon-chain/sync/service_test.go
beacon-chain/types/block.go

Noticed that there were a couple of methods on `types.Block` that were only being used to facilitate testing. These methods shouldn't be exposed to prod, so I moved them into the test file.

Eliminate test only methods on types.Block

---

beacon-chain/blockchain/core.go
beacon-chain/blockchain/core_test.go
beacon-chain/simulator/service.go
beacon-chain/simulator/service_test.go
beacon-chain/sync/service_test.go
beacon-chain/types/block.go

This PR adds an additional condition in the beacon chain's block processing function, to verify that the block has a parent hash, and that this parent hash is stored in the db.
Furthermore it modifies existing test cases by setting parent hash, and adds a new test to ensure blocks with invalid parent hashes won't be processed.
This is my first PR; sorry in advance if the PR doesn't satisfy the requirements :) I will be happy to modify if anything's missing or should be changed.
Fixes #324

Check Parent Hash in Block Processing Function

---

beacon-chain/README.md

Was getting 404 for the gitter link in Beacon Chain readme, now working.

Fix Gitter Link

---

client/README.md

There is a small duplicate typo, "proposers, attesters, and attesters", this commit fixes it. The other changes are just the removal of trailing spaces.

Fix duplicate typo in client/README.md

---

beacon-chain/main.go
beacon-chain/node/node.go
beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go
beacon-chain/utils/flags.go
client/rpcclient/BUILD.bazel
client/rpcclient/service.go
client/rpcclient/service_test.go
client/types/flags.go

This is for #366
It originally said to use gRPC securely by default but that would be unfeasible since node's need their own certs/keys.

Add support to pass in TLS key/crt to use gRPC securely

---

WORKSPACE
beacon-chain/rpc/BUILD.bazel
beacon-chain/simulator/BUILD.bazel
beacon-chain/types/BUILD.bazel
validator/proposer/BUILD.bazel

The latest version of rules_go and bazel_gazelle support go 1.11 which has a lot of nice features.
I don't foresee any issues, but please checkout this branch and build it on your local machine before clicking approve.
Need
I've built and ran tests for ubuntu, but I haven't tested on MacOS.

Update rules_go, bazel_gazelle, and go-ethereum to Support Go 1.11

---

beacon-chain/types/attestation.go
beacon-chain/types/block.go
beacon-chain/types/block_test.go

This addresses #468 
Verifying a valid `Attestation`'s `JustifiedHash` is in the current chain and the `JustifiedSlot` is earlier or equal to the `CrystalizedState.LastJustifiedSlot`.
I think there is a chance of optimization and reducing database load by instead of checking the database for the block belonging to the current chain, only checking `ActiveState.RecentBlockHashes` - what do you think?

Attestation Justified Slot Validation Per Spec

---

beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go

The attestation feed was subscribing to `protobuf` for aggregated attestation instead of `types` which led to the beacon-node throwing a panic when the validator client was connected. This PR fixes that

Fixes Error on Startup for Validator Client

---

beacon-chain/attestation/service.go
validator/beacon/service.go
validator/beacon/service_test.go

No tracking issue, quick fix
---
Slot assignments are in the range [0, params.CycleLength]. However, current beacon slot can be some big number such as 10929039023. In this case, we want to calculate the start of the current cycle and set the assignment to be CYCLE_START_SLOT + assignedSlot. This PR fixes that issue in the validator client.

Fix State Recalc in Slot Assignment

---

beacon-chain/rpc/service.go

This allows for a block proposed by a proposer to be processed by the beacon node successfully and not panic. This is a temporary solution to allow the demo to function smoothly , ultimately #589 will move this to be done in the validator client instead of the beacon node.

Adding Proposer Index to block

---

beacon-chain/blockchain/service.go
beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go
beacon-chain/types/block.go
beacon-chain/types/block_test.go

This resolves #605.
---
Beacon node was unable to start from where it left off. That is, if in one session the chain advanced to slot 13, when the system restarts it would go back from slot 0 rather than starting from the current slot based on the persisted genesis timestamp.
We start the system by fetching the persisted genesis block's timestamp instead of using the params default GenesisTimestamp.

Beacon Node Determines Slot From Genesis Block if ChainState Detected

---

beacon-chain/params/config.go
beacon-chain/simulator/service.go
beacon-chain/types/crystallized_state.go

No tracking issue here.
---
This PR fixes validator assignments such that cycles happen at exactly the right time and beacon node always starts from slot 0.

Fix Validator Assignment

---

.buildkite-bazelrc
WORKSPACE

This is reducing clean builds with zero cache to about 3 minutes with the 2 CPU 3.75Mb ram machine.
Adding a remote config there to test out, but there are some issues with go stdlib failing to cache properly/quickly. (bazelbuild/rules_go#1531)
Updating rules_go since I think there is a bit of a performance improvement when building cgo targets.

More fixes to bazel buildkite and update rules_go

---

.buildkite-bazelrc
beacon-chain/blockchain/BUILD.bazel
beacon-chain/casper/BUILD.bazel
beacon-chain/node/node_test.go
beacon-chain/rpc/service_test.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/service_test.go
beacon-chain/types/BUILD.bazel
contracts/sharding-manager-contract/BUILD.bazel

This fixes #377, as well as flaky tests in `sync` and `rpc` that were reproduced on buildkite but haven't been reported on GitHub.
I didn't find any race conditions for `blockchain`, `casper`, `types`, so I re-enabled race there as well.

Fix Flaky Tests

---

beacon-chain/casper/sharding.go
beacon-chain/casper/sharding_test.go

This is to enforce the max committee size as per the spec as of 2.1 and to remove multiple slots per committee as they aren't a benefit to security.
resolves #579 
resolves #639

Enforce Max Committee Size and Remove Multiple Slots Per Committee 

---

beacon-chain/sync/service.go
beacon-chain/sync/service_test.go

Resolves #594.
---
This is a simple PR that discards incoming blocks through sync that have a slot lower than the crystallized state's last finalized slot.

Discard Block With Slot Lower Than LastFinalizedSlot

---

beacon-chain/blockchain/service.go
beacon-chain/types/active_state.go
beacon-chain/types/active_state_test.go

This changeset allows the demo mode to advance past slot 15 in #680 
2 issues:
* `cState.IsCycleTransition(block.SlotNumber())` continues to be called after a failure, causing a NPE.
* `aState.CalculateNewActiveState` failed to clean up old attestations, causing a bounds error in 2 cycles.

Properly clean up attestations during state transitions

---

beacon-chain/node/node_test.go

If a test fails, the database isn't cleaned up, causing the next test run to always fail. This ensures that the database is empty when the test runs.
This addresses #720

Delete DB Files Before Running Node Tests

---

tools/bootnode/BUILD.bazel
tools/bootnode/bootnode.go

This PR introduces a simple tool for bootstrapping newly connected nodes. 
The bootnode serves as an entrypoint for peer discovery.

Add basic bootnode

---

beacon-chain/casper/sharding_test.go
beacon-chain/casper/validator.go
beacon-chain/casper/validator_test.go

The master is broken due to an "index out of range" panic from `GetShardAndCommitteesForSlot` while syncing slot 10.
Problem Description:
- Given we have 10 shards, the ShardCommitteees array is sized 10 from index [0-9]
- Each cycle length is 5, every 5 slots, state recalculation happens
- At slot 10, Sync calls GetShardCommitteees for [10], but it really should be [9]
- From config's point of view, we start at 1 but ShardCommitteees slice starts at 0. I added a +1 to lower bound calculation for offset
- With this, I was able to advance beacon node to slot 100+

Fixed GetShardAndCommitteesForSlot index out of range

---

validator/main.go
validator/node/node.go

This fixed the following errors when launching a validator client
`ERROR beacon: unable to assign a role: validator role was not assigned for key:`
and 
`panic: validator flag redefined: beacon-rpc-provider`

Fixed Duplicated Flag and PubKey Empty Issues

---

beacon-chain/types/BUILD.bazel
beacon-chain/types/active_state.go

Resolves #903
This PR resolves the error by completely removing any appending of the specials records that occured when a new active state was calculated. Due to appending of 2 new special records each cycle transition, the first two active validators were logged out due to the following function in `Casper` 
```go
func ProcessSpecialRecords(slotNumber uint64, validators []*pb.ValidatorRecord, pendingSpecials []*pb.SpecialRecord) ([]*pb.ValidatorRecord, error) {
// For each special record object in active state.
for _, specialRecord := range pendingSpecials {
// Covers validators submitted logouts from last cycle.
if specialRecord.Kind == uint32(params.Logout) {
validatorIndex := binary.BigEndian.Uint64(specialRecord.Data[0])
exitedValidator := v.ExitValidator(validators[validatorIndex], …
```

Validator Fix

---

genesis.json

Updated Validator's pubkey in genesis.json, the last 3 pub keys were the same. Now starting from the top
```
AA..
BB..
CC..
DD..
EE..
FF..
GG..
HH..
```

Fixed Validator's Pubkey in Genesis.json

---

validator/README.md

[Resolves] #958
Description:
Ethereum Serenity Design Specs have been moved from:
(https://notes.ethereum.org/SCIg8AH5SA-O4C1G1LYZHQ) --->(https://github.com/ethereum/eth2.0-specs)

Serenity Design Specs have been moved

---

shared/slotticker/simulatorticker.go

This is never used.
Requires approval from @nisdas.

Delete unused CurrentSimulatorSlot

---

beacon-chain/types/active_state.go
beacon-chain/types/active_state_test.go

This fixes #961
in that latest spec, special record object can be processed during block interval, we no longer need to store them to state object

Remove Function to Add SpecialRecord to ActiveState

---

shared/p2p/dial_relay_node.go
shared/p2p/dial_relay_node_test.go
tools/bootnode-query/BUILD.bazel
tools/bootnode-query/main.go

This tool can be used to query the peers of a DHT / bootstrap node.

Bootnode query tool

---

shared/p2p/BUILD.bazel
shared/p2p/dial_relay_node.go
shared/p2p/dial_relay_node_test.go
shared/p2p/discovery.go
shared/p2p/service.go

The `dht.Bootstrap()` method is the key part of the DHT service for discovering peers. 
I've also added some tracing spans to inspect how long things take in the future.

Bootstrap the DHT service

---

WORKSPACE
contracts/validator-registration-contract/deployVRC/BUILD.bazel
contracts/validator-registration-contract/deployVRC/deployVRC.go

This bit of functionality allows the `deployVRC` tool to update a kubernetes config map. 
The config map is then consumed by beacon-chain nodes, and potentially other services within the cluster.

Added kubernetes config map update for deployvrc

---

WORKSPACE

This fixes build breakage from #1016.
It wasn't caught earlier because those dependencies were already cached on the disk of the CI runner. After I recycled the CI runners, this problem became apparent.

Native git_repository rule is deprecated and should no longer be used

---

.gitignore
shared/p2p/service.go
shared/p2p/service_test.go

Resolves #1017 
---
I have provided a check before executing the p2p so it takes care if the port is already taken.

Issue 1017 taken port

---

beacon-chain/db/db.go

Resolves #1112  
---
Previously, the database package would hang when two processes tried to access the same datadir simultaneously. Now, there is a one second timeout and an error returned if two processes access simultaneously.

Fixed hang when multiple processes open same DB

---

WORKSPACE

https://github.com/shyiko/kubesec/pull/19 is merged with the fix we needed.

Update kubesec to use canonical repo

---

WORKSPACE

This should reduce build times since some of the dependencies were being build twice, at different versions.

Use bazel managed deps for go-ethereum

---

.gometalinter.json
.travis.yml

This is a quick PR to update .travis.yml to exclude proto generated files from gometalinter in our CI pipeline

Exclude Protos from Gometalinter in Travis

---

shared/ssz/encoder_decoder_lib.go

Resolves #1194.
This PR ignores struct fields beginning with XXX (proto internal fields) when SSZ encoding.

Ignore XXX Fields in XXX SSZ Encoding

---

shared/ssz/decode.go
shared/ssz/decode_test.go
shared/ssz/encode.go
shared/ssz/encode_test.go
shared/ssz/encoder_decoder_lib.go

Resolves #1189 
---
Removed the sorting of struct when encoding/decoding.

Remove Struct Fields Ordering for SSZ Encoding/Decoding

---

beacon-chain/BUILD.bazel
contracts/validator-registration-contract/deployVRC/BUILD.bazel
tools/bootnode/BUILD.bazel
tools/relaynode/BUILD.bazel
validator/BUILD.bazel

I ran into an issue with a minimal deployment if `build --features=race` is present. 
Since this is how the CI pushes the images, we should not build docker images with the race detection.
I think that race detection would also unnecessarily inflate the image size. 
Edit: Yes, this is about a 7mb savings. 49Mb -> 42Mb for beacon-chain.

Disable race detection on go docker images

---

beacon-chain/core/attestations/attestation.go
beacon-chain/core/attestations/attestation_test.go

Resolves #1190
---
Updates `IsDoubleVote` and `IsSurroundVote` functions according to the latest specs.
Ref: https://github.com/ethereum/eth2.0-specs/pull/373

Update slashing conditions according to specs

---

shared/ssz/BUILD.bazel
shared/ssz/README.md
shared/ssz/decode.go
shared/ssz/encode.go
shared/ssz/encoder_decoder_lib.go
shared/ssz/example_and_test.go
shared/ssz/hash.go
shared/ssz/hash_test.go
shared/ssz/ssz_utils_cache.go

Resolves #716 
---
Implement tree-hash defined by ssz.

Implement SSZ Tree Hash Algorithm

---

.travis.yml

https://github.com/libp2p/go-reuseport/issues/58

Update .travis.yml to use go1.11 to run coverage

---

beacon-chain/blockchain/service.go
beacon-chain/chaintest/backend/simulated_backend.go
beacon-chain/core/attestations/attestation.go
beacon-chain/core/balances/rewards_penalties_test.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/state/state.go
beacon-chain/core/state/state_test.go
beacon-chain/core/validators/committees.go
beacon-chain/core/validators/committees_test.go
beacon-chain/core/validators/validator.go
beacon-chain/db/block_test.go
beacon-chain/utils/shuffle_test.go
shared/params/BUILD.bazel
shared/params/config.go
shared/params/config_test.go
validator/beacon/service.go

Code clean up. This PR reformats config constants into sections, updates the descriptions and deletes deprecated code.
What changes in this PR:
- Reformated configs with sections, aligned with the format in [spec](https://github.com/ethereum/eth2.0-specs/blob/fd2cc6956fa15c98a4a3a0cb1ab9c478584ef2ea/specs/core/0_beacon-chain.md#constants)
- `IsValidatorSetChange` is deprecated and no longer needed. The validator set change logic is now part of epoch processing in `transition.go`
- `ZeroBalanceValidatorTTL` is deprecated, I removed it from `ProcessDeposits`

Reformat Configs for Readability 

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go

As part of the block processing routine, I found that there were 3 DB fetches for the beacon state. This PR passes a reference to the same state object from the caller.

Remove some redundant fetches from DB for the beacon state

---

beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/service.go

> Server Reflection provides information about publicly-accessible gRPC services on a server, and assists clients at runtime to construct RPC requests and responses without precompiled service information. It is used by gRPC CLI, which can be used to introspect server protos and send/receive test RPCs.

Add reflection gRPC service to beacon-chain gRPC server

---

beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go

How we encoded and decoded deposit data , was wrong as it followed the wrong ordering as compared to how the VRC concatenates the data. This caused bugs when trying to test for logs emitted from the VRC, as the decoding was incorrect. This PR fixes that.

Encoding/Decoding Deposit Data Fix

---

.github/stale.yml

Introducing a bot that will automatically label inactive PRs with "stale" label after 7 days of inactivity.
A PR will be autoclosed after 7 more days inactivity once the "stale" label has been applied.
This only applies to PRs for now.
This is just the config, someone will still need to install the github app before anything starts to happen.
https://github.com/probot/stale

Add config for probot stale bot

---

beacon-chain/core/attestations/attestation_test.go

This removes a useless double function call in the test

removes duplicate function call in test

---

proto/beacon/p2p/v1/messages.pb.go
proto/beacon/p2p/v1/messages.proto

Adding rest of the beacon block operations to `message.proto`, these beacon block operations will be propagated around the network

Add Beacon Block Operations to Messages.proto

---

validator/main.go
validator/types/flags.go

This is a pre-req to #1436. This PR incorporates the structure used by geth for subcommands such as
```
geth accounts new
```
into our validator client. Now, we can create a new validator client account with the command:
```
bazel run //validator -- accounts create
```
This will be a pre-requisite to launching a validator client as the client would expect the user to have created a new private key and keystore to use in the system.

Allow for CLI Subcommands Validator Client

---

.buildkite-bazelrc
validator/BUILD.bazel

We probably should enforce these builds in buildkite. They are currently not selected in `//...` since they have the manual tag.
Edit: Added `--build_manual_tests` to build all manual targets. 
Edit2: `--build_manual_tests` doesn't work because the buildkite runners don't have access to the secrets in k8s. Will look alternative solutions later...

Fix missing import in validator image

---

.buildkite-bazelrc

This sets the timeout for short tests to 5 seconds, medium tests to 60 seconds, and the long or enormous tests will use their default timeout values.  
This is needed because the default test size is medium which has a timeout of 5 minutes. The test runner will run the test 5 times for flakiness which means the runner is bogged down for 25 minutes.

Override reasonable defaults for bazel test timeout

---

beacon-chain/core/blocks/BUILD.bazel
beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/block_test.go
beacon-chain/core/state/BUILD.bazel
beacon-chain/core/state/state.go
beacon-chain/core/state/state_test.go

No tracking issue for this PR.
---
This PR implements the last lines of the on_startup routine for the beacon chain as defined in the spec at commit hash [190d9d288736ec43b833eb32ba8fb4b7aee1046c](https://github.com/ethereum/eth2.0-specs/tree/190d9d288736ec43b833eb32ba8fb4b7aee1046c) which are missing from our current master branch.
```python
genesis_active_index_root = hash_tree_root(get_active_validator_indices(state, GENESIS_EPOCH))
for index in range(LATEST_INDEX_ROOTS_LENGTH):
state.latest_index_roots[index] = genesis_active_index_root
state.current_epoch_seed = generate_seed(state, GENESIS_EPOCH)
```
This PR also adds ETH1Data to our genesis block function as:
```python
eth1_data=Eth1Data(
deposit_root=ZERO_HASH,
block_hash=ZERO_HASH
),
```

Align Initial Beacon State to Latest Spec

---

shared/ssz/decode.go
shared/ssz/decode_test.go
shared/ssz/encode.go
shared/ssz/encode_test.go

This solves the issue #1461 
Since the encoding/decoding is not defined in the spec:
- We assume we will only encode/decode pointer of array, slice or struct.
- The encoding for nil pointer shall be `0x00000000`.
This introduces our custom logic and it might lead to issues when communicating between clients, so this is only a short-term walk-around.

Support Encode/Decode of Nil Pointer

---

beacon-chain/core/blocks/block_operations.go

Part of #1541, this changes all docs for functions to use `message_hash` instead of `message`

change to message hash

---

WORKSPACE

Added a flag to disable / ignore all of the gcc warnings from sepc265k. This will make the CI runs less verbose.

Disable gcc warnings for geth

---

beacon-chain/blockchain/fork_choice_test.go
beacon-chain/chaintest/backend/helpers.go
beacon-chain/chaintest/backend/simulated_backend.go
beacon-chain/core/blocks/validity_conditions_test.go
beacon-chain/rpc/validator_server_test.go
shared/params/config.go

Part of #1565 
---
This PR revives our --demo-config flag so we can test a system of 8 local validators without having to remember what values to use for global parameters. The changes are:
```go
demoConfig.ShardCount = 1
demoConfig.TargetCommitteeSize = 2
demoConfig.DepositsForChainStart = 8
demoConfig.EpochLength = 4
demoConfig.GenesisEpoch = demoConfig.GenesisSlot / 4
demoConfig.SlotDuration = 10
demoConfig.MinDepositAmount = 100
demoConfig.MaxDepositAmount = 3200
```
This PR also eliminates two unnecessary and unused fields in our config, GenesisTime and SimulatedBlockRandao, as they are no longer relevant.

Revive Our Demo Config for Local Testing

---

WORKSPACE
shared/bls/BUILD.bazel
shared/bls/bls.go
shared/bls/bls_test.go
shared/keystore/BUILD.bazel
shared/keystore/key.go
shared/keystore/key_test.go
shared/keystore/keystore.go
shared/keystore/keystore_test.go
shared/keystore/utils.go
validator/BUILD.bazel
validator/accounts/account.go
validator/accounts/account_test.go
validator/client/validator.go
validator/client/validator_attest.go

Reverts commit bc2afa04c6aa870225f72ff1ec40941335afd9dd
This isn't a clean revert; had many conflicts so please review.
Tests pass, but `BufferedPublicKey` returns an empty byte array so I doubt that the validator epoch assignment requests are going to work...
Resolves #1582 since bls/mcl are no longer present.

Revert go-bls

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/validity_conditions.go
beacon-chain/core/blocks/validity_conditions_test.go

No tracking issue
---
Currently, our block validity conditions had 4 conditions even though the spec on master has 3. One of them was wrong, as we previously had that:
```
Verify time.Now() > state.genesis_time + block.slot* SLOT_DURATION.
```
but instead we should have
```
Verify time.Now() > state.genesis_time + (block.slot-GENESIS_SLOT)* SLOT_DURATION.
```
Additionally, we were checking that the `DepositRoot` of the ETH1 data existed in the powchain, but instead we should be checking if `BlockHash` points to a block.

Update Validity Conditions to Match Spec

---

beacon-chain/core/blocks/validity_conditions.go
beacon-chain/core/epoch/epoch_processing.go

This is part of #1542 
Reference: https://github.com/ethereum/eth2.0-specs/pull/600/files

Add a Note for Leap Sec in Block Validity Condition

---

beacon-chain/core/epoch/epoch_processing.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/regular_sync.go
beacon-chain/sync/regular_sync_test.go

This is an enhancement to #1565.
To prevent spamming attacks, the sync service should drop attestations with `slot < state's last finalized slot` and not pass the attestation to operation service (attestation pool)

Skips Attestation Older than Finalized Slot

---

beacon-chain/attestation/service_test.go
beacon-chain/core/epoch/epoch_operations_test.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/validators/validator_test.go
shared/bitutil/bit.go
shared/bitutil/bit_test.go

This is part of #1621 
Key changes:
* Updated `CheckBit` to work with small endian
* Fixed tests

Update CheckBit for Small Endian

---

beacon-chain/blockchain/fork_choice_test.go
beacon-chain/blockchain/service_test.go
beacon-chain/chaintest/backend/BUILD.bazel
beacon-chain/chaintest/backend/helpers.go
beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_test.go
beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/deposits.go
beacon-chain/core/helpers/deposits_test.go
beacon-chain/core/state/BUILD.bazel
beacon-chain/core/state/state.go
beacon-chain/core/state/state_test.go
beacon-chain/db/BUILD.bazel
beacon-chain/db/state_test.go
beacon-chain/powchain/BUILD.bazel
beacon-chain/powchain/service.go
beacon-chain/powchain/service_test.go
beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/validator_server_test.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/regular_sync_test.go

Currently, encoding of deposits is in the `blocks` package, which led to a lot of import cycles when building out the RANDAO functionality. Instead, we move this logic to the helpers package to prevent import cycles in the future as there are pretty much pure functions that should live alongside other pure utilities such as the ones found in helpers.

Move Deposit Encoding to Helpers Package

---

shared/keystore/utils.go

Before:
```
.UTC--2019-02-19T20-47-33.890586363Z--8e28ead22989a939fd6a8e770c290e67a738c44c530ab00ac5e5104c7da3e60c91b1b6e8d48316eb036c637ad2c639110803f2cd329ad9e75a9fc0cdab7e05906931faab788586cb4ad8079afa66b44c8564b14ec998b91211cc205e8232ff2e.tmp909348847
```
After 
```
.UTC--2019-02-19T20-47-33.890586363Z--8e28ead2.tmp909348847
```
Why? On some systems, this creates a filename/path that is too long. Particularly in tests.

Shorten keystore filename

---

beacon-chain/node/node.go
beacon-chain/rpc/beacon_server.go
beacon-chain/rpc/beacon_server_test.go
beacon-chain/rpc/service.go
validator/client/fake_validator_test.go
validator/client/runner.go
validator/client/validator.go
validator/client/validator_test.go

Currently, if our beacon node shuts down while validators are connected to it and waiting for chainstart to occur, they will believe chainstart was time.Unix(0, 0) and begin performing their responsibilities. This is due to not properly handling the errors on both the beacon node and validator rpc server and client. Additionally, if --chain-start-delay was on in the beacon node, a validator client would panic as it would request epoch assignments even though the chain has technically not started due to the flag. This PR fixes these two bugs.

Fatal if ChainStart Receiving Fails

---

shared/cmd/flags.go
validator/main.go
validator/node/node.go
validator/types/flags.go

This PR removes ambiguous or old flags used from previous iterations of our binaries and favors keeping a `--password` flag which allows the user to supply the string value of a password directly when running a validator client.

Deprecate Old Configuration Flags

---

shared/mathutil/math_helper.go
shared/mathutil/math_helper_test.go

zero isn't a power of two
Verified inline with spec PR: https://github.com/ethereum/eth2.0-specs/pull/674

fix zero being power of two

---

shared/ssz/BUILD.bazel
shared/ssz/example_encode_test.go

I wasn't satisfied with the docs on how to ssz.Encode something so here's an example.

Add example encoding for godoc ssz

---

contracts/deposit-contract/deployContract/BUILD.bazel

I've also added changes to buildkite to build the images as part of the presubmit so this shouldn't happen again.

Add missing dep to the docker image

---

shared/params/config.go

This modifies the params of the sync polling interval and consequently reduces sync test time by 60%

Reduce Sync Test Time

---

beacon-chain/powchain/service.go
shared/keystore/key_test.go

This was causing various issues.
I also fixed a tmpdir issue in the keystore

Remove preemptive chainstart variable set on start

---

beacon-chain/core/balances/rewards_penalties.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/helpers/committee.go
beacon-chain/powchain/service.go

Previously, we weren't using the registryChange bool flag when calling `CrosslinkCommitteesAtSlot`, which could have caused failures at epoch boundaries. This PR addresses this bug.

Use RegistryChanged Flag in CrosslinkCommitteesAtSlot Everywhere

---

beacon-chain/db/BUILD.bazel
beacon-chain/db/verify_contract.go
beacon-chain/db/verify_contract_test.go
beacon-chain/node/node.go

Forget to clear your datadir? No problem! Now you get a wonderful red error.
Example error:
```
[2019-02-26 12:23:08] ERROR main: invalid deposit contract address, expected 0x247b06d9890ab9b032ec318ca436aef262d0f08a
```

Complain if contract address changes

---

beacon-chain/powchain/service.go
beacon-chain/powchain/service_test.go

In our code, we had an error condition that would throw if the chainstart time is greater than the current time. However, this will be the case in testnet and production so we will remove that condition.

Fix Invalid Timestamp From ChainStart Log Issue

---

beacon-chain/core/validators/validator.go

This is part of #1707
The validator's slashed epoch calculation was incorrect. We forgot to add `LatestSlashedExitLength` to it.
Reference: https://github.com/ethereum/eth2.0-specs/pull/656/files

Fix Validator Slashed Epoch Calculation

---

beacon-chain/core/balances/rewards_penalties.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/validators.go

We previously added a next epoch check (if requesting slot for next epoch, set `registryChange` = true), this is not necessary for the following processing function because they will never request slot of next epoch. Reverted back to what we had before with explicit comments. Confirmed with Danny on this.
* Process crosslinks justifications don't process cross link of future slot
* Process crosslinks rewards don't process cross link of future slot
* Getting beacon proposer and attestation participants from beacon node's perspectives won't request slot of next epoch

Remove Next Epoch Registry Change Checks

---

beacon-chain/core/balances/rewards_penalties.go
beacon-chain/core/epoch/epoch_operations.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/state/transition.go
beacon-chain/core/state/transition_test.go
beacon-chain/core/validators/validator.go

This PR aims to be align current epoch processing to spec and see if there's any last min bug that we miss.
Key changes:
- `ProcessEth1Data` doesn't need to pre condition check, it's already done in `CanProcessEth1Data`
- `ProcessEth1Data` has an incorrect condition check for best ETH1Data
- Added logging for prev boundary attestations, attester indices and balances

Misc Fixes for Epoch Processing

---

beacon-chain/BUILD.bazel
beacon-chain/main.go
beacon-chain/usage.go
validator/BUILD.bazel
validator/main.go
validator/usage.go

Resolves #1595 
---
These changes are being made so that (1) the flags are grouped in a different file and grouped into distinct groups with sorted elements in each group, (2) the main file doesn't implement redundant logic, and (3) the project builds. 
The changes I made consisted of changing the usage template so that it would use flag groups rather than printing all of the global options. The `cli.HelpPrinter` value was overwritten so that this custom template would be rendered correctly and within this overwritten `HelpPrinter` function I sort the flags in a particular group. Additionally, I removed the old template from the **main.go** file and updated the **beacon-chain** directory so that the project would build properly. 
The **usage.go** file that I created is based off of geth's …

Implemented the flag grouping logic

---

beacon-chain/powchain/BUILD.bazel
beacon-chain/powchain/block_cache.go
beacon-chain/powchain/block_cache_test.go
beacon-chain/powchain/service.go
beacon-chain/powchain/service_test.go
beacon-chain/rpc/beacon_server.go
beacon-chain/rpc/beacon_server_test.go
beacon-chain/rpc/service.go

Includes #1760, see that PR for a more detailed description.
This PR started out as some minor suggestions to #1760, but I ended up with some slight refactoring and added metrics to understand cache misses/hits.
Additions to #1760:
- Prometheus metrics
- Two FIFO (one per key type pointing to the same underlying blockInfoObj)
- Refactored out of service.go into block_cache.go

Block caching for ETH1Data (includes #1760)

---

validator/client/runner.go

This makes the log an `Info` log instead of a `Warn` log, when the validator is standing by, since its not really something that is worrying.

Change Validator Log

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/state/state.go

Found a bug via: https://github.com/ethereum/eth2.0-specs/pull/713
We are suppose to xor `hash(block.randao_reveal)` not `block.randao_reveal`, therefore it's 32 bytes entropy not 96 bytes entropy

Fix Randao Reveal Bug

---

beacon-chain/core/epoch/epoch_operations_test.go

removed the unnecessary `fmt.print`

Remove Print in Test

---

beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/querier.go
beacon-chain/sync/regular_sync.go
beacon-chain/sync/regular_sync_test.go
beacon-chain/sync/service.go
beacon-chain/sync/simulated_sync_test.go
shared/params/config.go

Sync stalls at runtime, this PR is to fix any bugs for it.

Fixing Sync

---

beacon-chain/powchain/service.go

This removes an old timestamp error log which would throw if the chainstart time was found to be greater than time.Now(). This is not an error in our current system because in production we expect chainstart to be in the future.

Remove Old Timestamp Error Log

---

beacon-chain/main.go
beacon-chain/node/node.go
beacon-chain/node/node_test.go
beacon-chain/powchain/service.go
beacon-chain/usage.go
beacon-chain/utils/flags.go

Since connecting to POW chain is required to run beacon-chain, remove this flag.
Also sets the default provider to goerli and adds better logging if the user doesnt provide a deposit contract address

Enable POW chain by default

---

shared/p2p/monitoring.go

Resolves #1874 
This exposes the currently connected peer count to /metrics

Metrics: currently connected peers

---

beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/service_test.go

There were issues where blocks included expired attestations from proposers, these changes filter out attestations from before the previous epoch.

Proposer Service: Only return attestations within the last epoch

---

beacon-chain/attestation/service.go
beacon-chain/attestation/service_test.go
beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/node/BUILD.bazel
beacon-chain/node/node.go

This PR implements attestation targets for fork choice, attestation targets a list of `validator index` and its `latest attested block` struct and they are tracked up to the last finalized epoch:
`[(V1 attested block2),(V2 attested block 3),(V3 attested block1)...]`
This was missing before and it is needed to calculate vote count to find fork choice head

Implement AttestationTargets for ForkChoice

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/service_test.go

Scenario:
- The current slot in the beacon chain is last slot in an epoch
- A validator is requesting attestations to include in a the next block (which will be in the next epoch)
- The pending attestations, which were valid for the current slot, may not be valid for the next epoch
Solution:
- Increment the beacon slot before determining the boundary. If the current slot isn't the last slot in an epoch, this has no effect. If it is the last slot in an epoch, it correctly changes the boundary window for the proposer inclusion of attestations.

Fix off by one edge case for pending attestations

---

beacon-chain/rpc/validator_server.go

---
This PR fixes a problem we had in that wait for activation would sometimes get stuck waiting for a canonical state. What we do instead is to trigger a time.After channel that reattempts verifying activation every 3 seconds in case the system gets stuck.

Fix WaitForActivation Race Condition

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/rpc/proposer_server.go

So the actual desired behavior is that we want the attestations that are between `MinAttestationInclusionDelay` (4) and `SlotsPerEpoch` (64) slots behind the slot of the propose block slot.

Fix attestations again

---

beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/service_test.go
beacon-chain/sync/regular_sync.go

This PR is to allow us to handle skipped slots in initial sync.

Handle Skipped Slots in Sync

---

beacon-chain/blockchain/service.go
beacon-chain/core/state/transition.go
beacon-chain/sync/regular_sync.go

We use `hashProto` instead of `hashBeaconBlock` which leads to an incorrect hash being announced. This PR fixes that by instead sending only the `blockAnnounce` data needed to be broadcasted from chain service and also  removing any other references to using HashProto for a block

Fix Hashing Errors in Sync

---

beacon-chain/blockchain/service.go
beacon-chain/core/blocks/validity_conditions.go
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/helpers/slot_epoch_test.go
k8s/beacon-chain/beacon-chain.deploy.yaml

Minor fixes to beaconchain service

---

renovate.json

This runs on Mondays before 3am. ~I think~ this is in ~CET or~ UTC.
Preset: https://github.com/renovatebot/presets/blob/e42344569d441ce90962da73a5bf6fd43e378448/packages/renovate-config-schedule/package.json#L12

Only run renovate on Mondays

---

beacon-chain/sync/initial-sync/service.go
validator/client/validator_propose_test.go

This changes the error logs to a debug log by adding a debug prefix

Remove Incorrect Error Logs in Sync

---

shared/iputils/BUILD.bazel
shared/iputils/external_ip.go
shared/p2p/BUILD.bazel
shared/p2p/discovery_norace_test.go

Resolves #1524. The discovery tests require some network attached device, as far as I can tell. 
I've added `requires-network` tag to p2p tests to indicate it is required

Return loopback address when disconnected from network

---

shared/p2p/service.go

This is to rule out possible scenario where messages are not being fully propagated to the network

Use floodsub instead of gossipsub for now 

---

validator/client/validator.go
validator/client/validator_test.go

Otherwise the validator will wait until the next epoch to ask for assignments.
This probably can be improved further with retry, but it's better than it was.

Clear validator assignments on failure

---

beacon-chain/db/db.go
beacon-chain/db/db_test.go
beacon-chain/main.go
beacon-chain/node/node.go
shared/cmd/flags.go

This adds a Clear DB flag, which cleans the data directory before we start the beacon node. We don't have to clear the data directory manually now whenever we test out a new contract

Add Clear DB Flag

---

beacon-chain/node/node.go

Slight UX improvement to log the path of DB instead of just `checking db...`
It took me a while to locate where the DB was stored hopefully it helps other people

Log the DB path

---

beacon-chain/sync/regular_sync.go

The context should be updated with the span metadata, not ignored

Fix spans in regular_sync

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/block_processing.go
beacon-chain/blockchain/block_processing_test.go
beacon-chain/blockchain/fork_choice.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/operations/service.go
beacon-chain/operations/service_test.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/regular_sync.go
beacon-chain/sync/regular_sync_test.go
beacon-chain/sync/service.go
shared/p2p/interfaces.go

Using imported interfaces and composition makes it easier to locate the actual definition of the method.

Use imported interfaces in sync package

---

beacon-chain/blockchain/fork_choice.go

Do not merge, I'm still working on regression test.
**Background:**
Slots: 1 2 3 4 5 6 7 **8** 9 10 11 12 13 14 15 **16** 17 18 19 20 21 22 23 **24** 25 26 27 28 29 30 31 (each epoch is 8 slots)
Let’s say at the end of 31 we start epoch processing, and we find there's a new justified epoch (epoch 2,
because there's a new justified epoch, we replace the new justified block (the one at the boundary slot 16) with the existing one in DB, but slot 16 happens to be a skip slot, in this case we should just take its ancestor slot 15.
This PR implements the behavior
More info: https://github.com/ethereum/eth2.0-specs/issues/768

Handle skip slots for FFG check points

---

beacon-chain/blockchain/fork_choice.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/blockchain/stategenerator/BUILD.bazel
beacon-chain/blockchain/stategenerator/state_generator.go
beacon-chain/blockchain/stategenerator/state_generator_test.go

State Gen previously take input block which doesn't account for skip slot. This PR updates state gen with more comments and allows state gen to take input slot instead of input block

Refactor State Gen To Take Input Slot

---

validator/client/validator_attest.go
validator/client/validator_attest_test.go

The current logic:
- Create the attestation 
- Sleep to midpoint
- Broadcast attestation
The expected logic:
- Sleep to midpoint
- Create the attestation
- Broadcast attestation

Fix sleep logic for attesting

---

k8s/beacon-chain/beacon-chain.service.yaml

This will give validators some stickiness with the beacon nodes they are connected with.

Add IP based LB for validators

---

k8s/beacon-chain/beacon-chain.deploy.yaml
shared/p2p/service.go

Problem: when a bootnode pod is rescheduled, it is assigned a new IP. Passing the IP statically by environment variable doesn't update this flag value.
Solution: Use istio sidecar to have a proper headless service. Additionally use DNS resolution in the mulitaddr. Also, use faster queries with DHT lookup. 
I've tested this and it seems to be working well, reconnecting to the bootnode without issue.

Use DNS resolution and istio for redialing bootnode

---

beacon-chain/core/balances/rewards_penalties.go

`ActiveValidatorIndices` was suppose to use `epoch` as input but `slot` was passed in when we calculate rewards and penalties. 
This was the reason why post pending registered validators were losing balances

Fix ActiveValidatorIndices use slot

---

beacon-chain/blockchain/fork_choice.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/sync/regular_sync_test.go
beacon-chain/sync/service_test.go
beacon-chain/sync/simulated_sync_test.go

Before when we compute fork choice we always use **current state** as **start state**, this changes to use **justified state** as **start state**

Use justified state as start state for running fork choice

---

beacon-chain/rpc/validator_server.go

Getting active validators was using `slot` instead of `epoch` for `ValidatorPerformance`

Fix getting active validators for ValidatorPerformance

---

validator/client/service.go

Part of #2025
Obsolete in #2069 
This is temporary fix to take the first validator key so that validators can perform their behavior until multikey support actions are supported in #2069.

take first validator key

---

shared/p2p/service.go
shared/params/config.go

---
Given we are transmitting state over the wire, we should make our p2p buffer sizes large enough to accommodate this. Additionally, we should set our batch block limit to something reasonable like 4 epochs worth of blocks, as that is the number of epochs since finality that will kick in Casper penalties.

Modify p2p Allowed Buffer Size & Batch Block Limit

---

k8s/beacon-chain/beacon-chain.deploy.yaml

This allows all of the beacon-chain nodes to start at once or be torn down at once rather that in a sequence.

k8s: Fix podManagementPolicy for beacon-chain

---

beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go

There was an order of operations mismatch between the spec and the implementation.

Fix max churn calculation 

---

shared/hashutil/beacon_block.go
shared/hashutil/beacon_block_test.go

This returns an error if we are about to hash a nil block instead of marshaling it and panicking.

Fix Hashing of Beacon Blocks

---

k8s/beacon-chain/beacon-chain.deploy.yaml
k8s/beacon-chain/infura.yaml

Our Goerli nodes seem to be unstable and cannot sync well.
We should ultimately have a failover from our own nodes to infura if issues are not resolved. 
Temporarily using infura nodes for goerli communication.

Use infura for now for Goerli

---

beacon-chain/blockchain/block_processing.go
beacon-chain/blockchain/block_processing_test.go
beacon-chain/blockchain/fork_choice.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/sync/initial-sync/service_test.go
beacon-chain/sync/initial-sync/sync_blocks.go
beacon-chain/sync/regular_sync_test.go

We should be using an argument ctx so that the span can be followed from the originating request.

Avoid using service context in blockchain package

---

beacon-chain/rpc/attester_server.go
beacon-chain/rpc/attester_server_test.go

Like #2154, could not produce attestations when justification slot was too far away, but could not resolve skip blocks.

Handle skip blocks when fetching justified block for producing attestations

---

shared/p2p/service.go
shared/p2p/service_test.go

Given that a node has at least 3 peers, rather than 5, it should be adequate to serve requests to validators.

Lower the p2p peer count minimum for a successful status

---

beacon-chain/sync/service.go
beacon-chain/sync/service_test.go

This is part of #2180 and resolves #2181
---
Our current sync.Status method is broken. Instead, we can use the initial sync `IsNodeSynced()` method to verify we have completed initial sync.

Correct Sync Status for Healthz

---

beacon-chain/sync/querier.go
beacon-chain/sync/service.go
beacon-chain/sync/simulated_sync_test.go

Follow up to #2182 
Resolves #2181 
---
If the node is at genesis, return healthy sync status. If prechainstart, return healthy status as well.

If At Genesis or !ChainStarted, Return Healthy Sync Status

---

beacon-chain/db/state.go
beacon-chain/db/state_test.go

This removes an unused db method, `SaveCurrentAndFinalizedState`

Remove DB Method

---

shared/bitutil/BUILD.bazel
shared/bitutil/bit.go
shared/bitutil/bit_test.go
validator/client/BUILD.bazel
validator/client/validator_attest.go
validator/client/validator_attest_test.go

This resolves #2224, where bitfields were being constructed with smaller committee sizes, which failed verification. So this PR adds in the committee size when constructing a bitfield to mitigate that

Add in Committee size to Set Bitfield

---

beacon-chain/core/balances/BUILD.bazel
beacon-chain/core/balances/rewards_penalties.go
beacon-chain/core/balances/rewards_penalties_test.go
beacon-chain/core/blocks/BUILD.bazel
beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/blocks/block_test.go
beacon-chain/core/epoch/BUILD.bazel
beacon-chain/core/epoch/epoch_operations.go
beacon-chain/core/epoch/epoch_operations_test.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/state/transition.go
beacon-chain/core/validators/BUILD.bazel
beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go

I suspect this causes a surge of goroutines when creating many short spans very quickly, so I have removed many of the spans.

Remove too many spans in block/slot/epoch processing

---

beacon-chain/core/balances/rewards_penalties.go
beacon-chain/core/balances/rewards_penalties_test.go
beacon-chain/core/state/transition.go
beacon-chain/sync/receive_block.go
beacon-chain/sync/regular_sync.go

Add Lock to Block Processing in Sync

---

k8s/beacon-chain/beacon-chain.deploy.yaml

k8s: --enable-committees-cache as default for beacon-chain

---

shared/p2p/service.go

Resolves #2233 
The fallback is to request the information on broadcast. There seem to be scenarios where we cannot connect to a peer, or we are not actually peered with the person we want to dial. Instead, we will just broadcast for the information.

Do not directly dial a peer we cannot reach

---

beacon-chain/sync/receive_block.go

This is part of #1586 
---
Right now, we have a lot of calls to apply fork choice and a high possibility of creating a ton of goroutines in our receive block function in regular sync. The way it works is as follows:
See a block, do we have its parent?
- **No**: store it in a map of pending child blocks, and issue a call for a parent request.
- **Yes**: Does the block have pending children we put in the prior map? Then call receiveBlock recursively and apply fork choice on the block and all its children. If the block does not have pending children at the end of the recursive call, end.
This creates a lot of calls to ApplyForkChoice and also a lot of calls to Jaeger spans, which do not end until the child span returns, which can …

Apply Fork Choice at End of Ancestor Block Fetching

---

beacon-chain/db/BUILD.bazel
beacon-chain/db/validator.go
beacon-chain/db/validator_test.go

In an effort to split up #2069, I have added the database methods to query whether some or all validators exist in the database by their public key.

Add database methods for has any or all validators

---

beacon-chain/cache/BUILD.bazel
beacon-chain/cache/block.go
beacon-chain/cache/block_test.go

As specified in Vitalik's optimized LMD GHOST [implementation](https://github.com/ethereum/research/blob/master/ghost/ghost.py), we should cache block ancestor. This PR implements a block ancestor FIFO cache in our cache package, it alleviates us from the following scenario:
Without block ancestor cache:
```
validator 1: voted block A (calculate block ancestor of block A)
validator 2: voted block A (recalculate block ancestor of block A)
validator 3 voted block A (recalculate block ancestor of block A)
validator 4: voted block B  (calculate block ancestor of block B)
validator 5: voted block B (recalculate block ancestor of block B)
```
With block ancestor cache:
```
validator 1: voted block A (calculate block ancestor of block A, save it to cache)
validator 2: voted block A (cache hit) …
```

Cache Block Ancestor for Fork Choice

---

.buildkite-bazelrc

Google's remote caching API is in alpha and we are whitelisted.
This adds the config to support remote caching for our CI builds.

Remote caching with GCP

---

beacon-chain/blockchain/block_processing.go
beacon-chain/blockchain/block_processing_test.go
beacon-chain/db/block.go
beacon-chain/db/db.go
beacon-chain/sync/receive_block.go
beacon-chain/sync/receive_block_test.go

This is part of #1586 
---
Previously, if we deleted a block, we might get an infinite ping pong of block requests in regular sync when we listen for block announcements. Additionally, we should blacklist block hashes in our db package as an in-memory map that we use to prevent spam requests or duplicate bad blocks received eternally.

Blacklist Bad Block Hashes

---

beacon-chain/node/node.go
beacon-chain/powchain/block_reader_test.go
beacon-chain/powchain/log_processing.go
beacon-chain/powchain/log_processing_test.go
beacon-chain/powchain/service.go
beacon-chain/powchain/service_test.go
beacon-chain/utils/flags.go

This resolves #2295 
---
Using websocket to fetch all historical contract logs would give us message size limit responses.
This PR uses our goerli HTTP endpoint for fetching past logs when a node first starts up. All other future logs will continue to be done via websocket.

Use HTTP RPC Endpoint for Logger to Fetch Past Logs

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/fork_choice.go
beacon-chain/sync/receive_block.go
beacon-chain/sync/receive_block_test.go
beacon-chain/sync/regular_sync_test.go

Only Update Head of Chain with Child Blocks

---

nogo_config.json

3rd party code was causing build failures on mac os

Exclude all third party code from unsafeptr

---

BUILD.bazel
nogo_config.json
validator/client/runner.go

Follow up to #2317 
---
We were canceling the context to each of the goroutines in the block of code in validator/runner.go:
```go
for id, role := range v.RolesAt(slot) {
go func(role pb.ValidatorRole, id string) {
switch role {
case pb.ValidatorRole_ATTESTER:
v.AttestToBlockHead(slotCtx, slot, id)
...
}
cancel()
```
This PR removes the cancel call.

Prevent Canceling Goroutines in Validator Client

---

beacon-chain/core/state/transition.go
beacon-chain/core/state/transition_test.go

No tracking issue. We had a problem where we would attempt to update the validator registry and request a mutex lock many times if many validators were requesting assignments through a skip slot. We prevent this from happening by not allowing the registry to be updated if there is a nil block.

Do Not Update Validator Registry on Nil Block

---

beacon-chain/attestation/service.go
beacon-chain/db/db.go
beacon-chain/db/state.go
beacon-chain/rpc/validator_server.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/regular_sync.go

This PR adds new getters for Validator Registry and Balances, so that they can be retrieved quickly instead of cloning the whole state. This also adds a getter for the canonical state hash, so that hashing doesnt need to be repeated

Separate Registry and Balances

---

shared/p2p/service.go

Messages are already signed, at least the ones we care about.

Disable pubsub signatures and verification

---

beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/validators/validator.go
shared/params/config.go

Part of #2307 
Mainly doc changes
Relies on #2343

Update slot helpers v0.6

---

beacon-chain/core/balances/BUILD.bazel
beacon-chain/core/balances/rewards_penalties.go
beacon-chain/core/balances/rewards_penalties_test.go
beacon-chain/core/blocks/BUILD.bazel
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/state/transition.go

This is a follow-up to #2346 
---
We only need the inclusion maps in epoch processing, eliminating the need to use mutexes and other complex operations outside of the state transition function. This PR moves the maps there and resolved the problems this caused with initial sync.

Move Inclusion Maps to Epoch Processing

---

beacon-chain/db/db.go
beacon-chain/db/state.go

This removes proto clone from state reads, and just ensures the cached state has not been corrupted

Remove Proto Clone from State Reads

---

beacon-chain/node/node.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go
beacon-chain/sync/service.go
shared/params/config.go

This resolves #2222, it continuously checks the status of the sync service before serving RPC requests. If the node is not synced RPC will be disabled

Disable RPC while Syncing

---

beacon-chain/blockchain/fork_choice.go
beacon-chain/blockchain/fork_choice_test.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

This is part of #1586 
---
Our block ancestor cache has been working well and offers significant improvements in fork choice. However, it is still hidden behind a feature flag.
This PR makes the ancestor cache enabled the default behavior and removes the feature flag for it.

Enable Ancestor Cache By Default

---

beacon-chain/db/verify_contract.go
beacon-chain/main.go
beacon-chain/node/node.go
shared/cmd/flags.go

Part of #1586 
---
As we are planning on doing short-lived testnets, it will make for a bad user experience if someone keeps using the same persistent db between runs as initial sync will fail and users might not know why. For now, we are disabling the use of a persistent DB between runs, making the default behavior to clear the db upon startup.

Suggest to ClearDB if Contract Mismatches Cluster

---

k8s/beacon-chain/beacon-chain.deploy.yaml

Our goerli node is not reliable enough at the moment.

k8s: Use infura for http provider

---

beacon-chain/attestation/service.go
beacon-chain/db/db.go
beacon-chain/db/state.go
beacon-chain/db/state_test.go

Our current pattern of reading and writing state, led to nodes not ever being able to sync with the cluster. This was because the cached state didn't handle concurrent operations utilizing it well. What would be regarded as 'corrupted' when used by one function would be regarded as the canonical one when used by another function, since they were both referring to the same state.

Fix State Reads

---

beacon-chain/attestation/service.go
beacon-chain/attestation/service_test.go
beacon-chain/blockchain/block_processing.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/blockchain/service.go
beacon-chain/db/attestation.go
beacon-chain/db/db.go
beacon-chain/db/schema.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/sync_blocks.go
beacon-chain/sync/initial-sync/sync_state.go
shared/ssz/hash_cache.go

Instead of using block fetch in retrieving latest attestation target, we use attestation target fetch. This is an improvement because it's a smaller data structure comparing to unmarshaling blocks with great #s of attestations. (versus something small that's just `pb.AttestationTarget{BlockRoot: blockRoot, ParentRoot: block.ParentRootHash32, Slot: block.Slot}`) 
Changed:
- when we save a block we also save attestation target to its own bucket using block root as key
- fetch for attestation target instead of block in `LatestAttestationTarget`

Optimize block fetch with attestation target fetch

---

beacon-chain/core/helpers/rewards_penalties.go
beacon-chain/core/helpers/rewards_penalties_test.go
shared/params/config.go

---
includes:
get_balance
set_balance
increase_balance
decrease_balance
to comply with 0.6 spec
changes in:
- beacon-chain/core/helpers/rewards_penalties_test.go 
- beacon-chain/core/helpers/rewards_penalties.go
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_balance

Update balance helpers v0.6

---

shared/cmd/flags.go

This flag is really for people behind a NAT, specifically the testnet cluster nodes.

Relay node should not be default to the cluster relay 

---

beacon-chain/attestation/BUILD.bazel
beacon-chain/attestation/service.go
beacon-chain/attestation/service_test.go
beacon-chain/core/state/transition.go

Handle Panics In Attestation and Disable Logging

---

WORKSPACE
shared/tracing/BUILD.bazel
shared/tracing/tracer.go

No tracking issue - this simply updates the go.opencensus.io package based on tag https://github.com/census-instrumentation/opencensus-go/releases/tag/v0.21.0

Update Jaeger Export Tracing

---

beacon-chain/db/validator.go
beacon-chain/db/validator_test.go
beacon-chain/rpc/validator_server.go
beacon-chain/rpc/validator_server_test.go

This PR implements the following failover, when looking up validator index in DB, If the validator index is not in the DB, as a secondary fail over it will search in the state and then save index to the DB when found in state.
Changed:

RPC Validator Index Lookup Failover

---

beacon-chain/node/node.go
beacon-chain/powchain/log_processing.go

Resolves #2401
----------------
Currently, websockets from geth are unstable and lead to many errors or frame payload exceeded in our runtime. This causes forked blocks as perhaps 1 node is not able to process a block while the others can. HTTP is more stable and we can replace on demand requests for blocks by hash by http.

Use HTTP for On Demand Block Requests

---

shared/p2p/discovery.go

The API is not intuitive, but we should be using `Network()` for listing the current peers.

Use Network, not Peerstore for peer logging

---

shared/debug/debug.go

Try running with `--pprof` and accessing :6060/debug/pprof
Also see: https://golang.org/pkg/net/http/pprof/

Serve pprof http

---

shared/p2p/negotiation.go

Peering with nodes behind a relay is currently broken. Temporarily disabling disconnecting peers if they do not support the handshake protocol.

Add a temporary disable for issue #2408

---

validator/client/validator.go

No tracking issue - we might be seeing some issues due to fetching assignments every single slot that can lead to weird behavior. Instead, we should fetch at every epoch start.

Only Fetch Assignments at Epoch Start

---

beacon-chain/db/state.go
beacon-chain/db/state_test.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

Part of #1586  
---
This PR enables historical state pruning by default, preventing local db's from getting into the Gigabyte range.

Enable Historical State Pruning By Default

---

k8s/beacon-chain/testnet-site.yaml
k8s/letsencrypt-issuer.yaml
k8s/prylabs-wildcard-gateway.yaml

Two changes here:
- Support SSL certificates for prylabs.net & *.prylabs.net
- Temporarily serve prylabs.net/assets from the alpha binary (needed for social sharing of alpha.prylabs.net)

Add SSL support for prylabs.net, support opengraph on alpha.prylabs.net

---

beacon-chain/core/helpers/committee_test.go
beacon-chain/core/helpers/randao.go
beacon-chain/core/helpers/randao_test.go
shared/bytesutil/bytes.go

---
includes:
GenerateSeed
to comply with 0.6 spec
changes in:
- beacon-chain/core/helpers/randao.go
- beacon-chain/core/helpers/randao_test.go
- shared/bytesutil/bytes.go
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#generate_seed

Update generateseed to 0.6 spec

---

k8s/beacon-chain/testnet-site.yaml

Using server side rendering on port 4000 now.
Redirecting https://prylabs.net to alpha.prylabs.net for now.

Use new port for testnet site, redirect prylabs.net 

---

beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go

Kudos to @shayzluf for pointing this out!
There's a bug on the old `ExitValidator` spec, where a validator can exit but re-exit again within `entryExitEffectEpoch` period. This prevents the bug by not letting validator exit again if the exit epoch is no longer set `FarFutureEpoch` so the validator can only get exited/slashed/ejected once

Prevent Validator Exit Re-entance

---

shared/params/config.go

Raising ejection balance to 3.15ETH for test net stability. Due to shorter epoch length (8 slots) we don't want too many offline validators in our 1st iteration of single client test net

Raise Ejection Balance to 3.15ETH

---

beacon-chain/core/state/BUILD.bazel
beacon-chain/core/state/transition.go

One of the initial test net feedback is to see the percent of validators that correctly participated in the most recent epoch. This adds metrics to do that

Add metric for correctly attested rate

---

beacon-chain/db/validator.go
beacon-chain/db/validator_test.go
beacon-chain/rpc/validator_server.go
beacon-chain/rpc/validator_server_test.go

Part of #1586 
---
If we clear the db and restart our active validator, it will forever be stuck on waiting for activation. Underneath the hood, it calls HasAnyValidators, which should fallback to looking into the state and repopulating the db accordingly.
This PR repopulates the db and falls back to looking into the state if a validator index is in there.

Fixed HasAnyValidators to Fallback to Looking Into the BeaconState

---

beacon-chain/attestation/service_test.go
beacon-chain/core/epoch/epoch_operations_test.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/validators/validator_test.go
shared/bitutil/bit.go
shared/bitutil/bit_test.go
shared/testutil/checkbit.go

---
to sync with the new spec
added methods:
VerifyBitfieldNew (replacing caused all the tests to fail)
BitfieldBit
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_bitfield_bit
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#verify_bitfield

Update bitfield helpers v0.6

---

k8s/beacon-chain/contract-address.yaml
k8s/beacon-chain/testnet-site.yaml

This hopefully saves a bit of resources when the server side rendering is under heavy load. The rendered page never changes so we can cache it in nginx reverse proxy. 
Also add liveness probs to contract service.

Add nginx proxy caching in front of SSR

---

beacon-chain/sync/querier.go

This is part of #2457 
---
Right now, if we do not receive a chain head response within 5 seconds, our chain head querier exits context after a timeout and our node cannot sync.
This PR polls forever until the first response, _then_ starts a 10 seconds timeout to keep receiving responses from peers before starting initial sync.

Querier Polls Forever Until 1st Response

---

beacon-chain/powchain/block_reader.go
beacon-chain/rpc/beacon_server_test.go
beacon-chain/rpc/service.go
beacon-chain/rpc/validator_server.go
beacon-chain/rpc/validator_server_test.go

Follow up to #2469 
---
This PR estimates the deposit inclusion slot as follows:
1. Obtain the eth1 height of when the deposit occurred from the db
2. Add eth1height + ETH1_FOLLOW_DISTANCE and fetch the block timestamp at that height
3. Add voting period seconds to that timestamp
4. Get the eth2 genesis time
5. Subtract the result of 3 from the eth2 genesis time
6. Convert that result to slots

Fix Estimation of Deposit Inclusion Slot in ValidatorActivationStatus

---

beacon-chain/rpc/validator_server.go
beacon-chain/rpc/validator_server_test.go

No tracking issue - this standardizes returned values from the validator status response to be in terms of slotsSinceGenesis or epochsSinceGenesis (that is, starting from a genesis of 0) for greater readability and aligned with v0.6 of the spec.

Standardize Slot Numbers in Validator Status Response

---

beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/validator_server.go
beacon-chain/rpc/validator_server_test.go
validator/client/validator.go
validator/client/validator_test.go

Allow Client to Retrieve Multiple Validator Statuses

---

beacon-chain/db/deposits.go
beacon-chain/rpc/validator_server.go

We had a problem in our code that fetches a deposit by pubkey:
```go
func (db *BeaconDB) DepositByPubkey(ctx context.Context, pubKey []byte) (*pb.Deposit, *big.Int, error) {
ctx, span := trace.StartSpan(ctx, "BeaconDB.DepositByPubkey")
defer span.End()
db.depositsLock.RLock()
defer db.depositsLock.RUnlock()
var deposit *pb.Deposit
var blockNum *big.Int
for _, ctnr := range db.deposits {
depositInput, err := helpers.DecodeDepositInput(ctnr.deposit.DepositData)
return nil, nil, fmt.Errorf("could not decode deposit input: %v", err)
}
if bytes.Equal(depositInput.Pubkey, pubKey) {
deposit = ctnr.deposit
blockNum = ctnr.block
break
}
}
return deposit, blockNum, nil
}
```
the above will fail if there was ever a faulty deposit, but it should not.

Do Not Throw Error in Fetching Deposit By Pubkey

---

shared/params/config.go

Increase proposer ejection to 3.175.
Currently set at 3.15 takes a while to reach (a day and half) considering we envision a lot of participation in the beginning, we don't want active validator size to grow become untenable

Increase ejection to 3.175

---

beacon-chain/core/state/transition.go

When logging highest and lowest balances, filter active only validators

Only Log Active Balances

---

beacon-chain/sync/querier.go

When the querier runs, it logs peers again from  already whom we have received a response. This prevent relogging of those peers

Don't Log Old Peers

---

validator/client/validator.go

Fixes error logs in validator client by setting the ticker only  after activation and not chainstart

Fix Error Logs in Validator Client

---

shared/p2p/negotiation.go

Part of #1586, this gives a better UX to the the user that a warning occurred instead of a scary error log which makes it seem as if the node died or failed when disconnecting a peer

Issue warn log on disconnecting peer instead of error

---

beacon-chain/main.go
beacon-chain/node/p2p_config.go
scripts/gcp_startup_script.sh
shared/cmd/flags.go
shared/p2p/service.go

`--p2p-host-ip` flag was necessary to broadcast an external IP address.
`scripts/gcp_startup_script.sh` has instructions on how to create a GCP binary and instance template.

Add GCP test configuration and p2p-host-ip flag

---

beacon-chain/blockchain/block_processing.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/rpc/service_test.go
beacon-chain/sync/regular_sync.go
beacon-chain/sync/regular_sync_test.go

This PR handles return of canonical blocks (ONLY) for batch block request in regular sync.
Previously we would return any blocks of a saved slot which could include forked blocks

Canonical Blocks for Batch Block Request

---

beacon-chain/blockchain/block_processing.go
beacon-chain/blockchain/service.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go
beacon-chain/sync/regular_sync_test.go

This PR also inserts canonical blocks when a chain head is updated via RPC into the canonical block roots map of a node

Use Single Code Path for Receiving Blocks and Fork Choice

---

beacon-chain/rpc/attester_server.go
beacon-chain/rpc/attester_server_test.go

We don't update attestation target when attester calls `AttestHead`, this will cause asymmetry issue when proposer submits head block and run fork choice.
This PR updates attestation target in DB when we call `AttestHead`

Update Attestation Target for AttestHead

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/rpc/proposer_server.go

To [process attestation](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attestations), one of the assertion is defined as the following:
```python
assert attestation_slot + MIN_ATTESTATION_INCLUSION_DELAY <= state.slot <= attestation_slot + SLOTS_PER_EPOCH
```
We previous had:
`if att.Data.Slot+params.BeaconConfig().SlotsPerEpoch <= beaconState.Slot`
which should have been
`if att.Data.Slot+params.BeaconConfig().SlotsPerEpoch < beaconState.Slot`

Fix Attestation Verification

---

beacon-chain/db/attestation.go
beacon-chain/rpc/proposer_server.go

It's proposer server's duty to respond valid attestations, but proposer server does not delete failed attestation as it detects them. This issue was amplified in test net where we saw attestations from 80 epochs ago were trying to get included.
`time="2019-05-07 22:15:12" level=warning msg="Skipping, pending attestation failed verification" error="expected attestation.JustifiedEpoch == state.JustifiedEpoch, received 14514 == 14571" prefix=rpc slot=116579`
As an enhancement, when proposer server detects an attestation can no longer be valid, it should just delete it from the DB

Delete Failed Pending Atts for Proposer Server

---

beacon-chain/sync/initial-sync/service_test.go
beacon-chain/sync/initial-sync/sync_blocks.go

I believe this solves an issue where we are prematurely exiting initial sync.

Sort list before processing batched blocks

---

beacon-chain/sync/initial-sync/helpers.go

#2532 was merged with the following Travis failure:
`beacon-chain/sync/initial-sync/helpers.go:36:23: U1000: func `(*InitialSync).doesParentExist` is unused (unused)`
This PR fixed the travis failure so we can be green again :)

Removed unused doesParentExist

---

shared/p2p/BUILD.bazel
shared/p2p/connection_manager.go
shared/p2p/negotiation.go
shared/p2p/service.go
tools/bootnode-query/BUILD.bazel
tools/bootnode-query/main.go
tools/bootnode/BUILD.bazel
tools/bootnode/bootnode.go

Resolves #2408 due to the connection manager penalty for peers that can't handshake.
This updated bootstrap node only supports the prysm DHT protocol instead of the default IFPS DHT protocol ID.

Use a prysm specific DHT protocol

---

beacon-chain/attestation/service.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/service_test.go
shared/bitutil/bit.go
shared/bitutil/bit_test.go
validator/client/BUILD.bazel
validator/client/validator_attest.go
validator/client/validator_attest_test.go

Fix Bitfield in Attestations

---

beacon-chain/powchain/service.go

Resolves #2282
---
This fixes a panic when the beacon node is shut down.
The panic was because there was no check for the channel being closed when receiving from it.  This is now checked for using the appropriate receive semantics as per https://golang.org/ref/spec#Receive_operator
I considered logging if the channel was closed (the !ok branch) but ultimately decided the information would not be a lot of use as the only time headerChan should be closed is during shutdown.  If there is a concern this could be silently swallowing errors I could log in this branch as an error, but in that case should also add a flag to Web3Service that would be set in Stop() to avoid reporting said errors when shutting down cleanly.
Unfortunately no easy way to add tests for this change.

Do not panic when the beacon node is shut down.

---

beacon-chain/cache/attestation_data.go
beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/attester_server.go
beacon-chain/rpc/attester_server_test.go

I am seeing an occasional race condition where a request is marked in progress. 
This provides a retry for fetching the cached method.

Handle race condition in progress

---

WORKSPACE
beacon-chain/BUILD.bazel
beacon-chain/main.go
k8s/beacon-chain/beacon-chain.deploy.yaml
k8s/beacon-chain/validator.deploy.yaml
shared/cmd/flags.go
validator/BUILD.bazel
validator/main.go

As title describes.
Try new flag `--log-format=json` default is text and fluentd is the format supported by GKE and other log aggregation systems.

Add new log formats and set fluentd as default for cluster

---

README.md

Resolves #2597
---
Updated instructions for running Beacon Node in Docker on Windows. The process requires a few additional steps to make a local volume available to mount the data dir. If this doesn't happen, the /tmp/prysm-data dir won't be created at run, and the chaindata will not be stored locally, nor will the account creation process store the key files appropriately for reference when running the validator.
Added content related to docker on Windows specifically, including adding he -it switch to 'docker run', adding information regarding the need to share a local drive for mounting from the container, and an updated example of the local data directory path that must be …

Updated README Deploying with Docker in Windows

---

beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/state/transition.go

This PR updates [process_eth1_data](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#eth1-data)
Part of #2307
Description:
- Updated ProcessEth1Data in epoch_processing.go
- Modified tests for ProcessEth1Data in epoch_processing_test.go
- Changed invocation of ProcessEth1Data in transition.go

Update processEth1Data for v0.6

---

shared/p2p/options.go
shared/p2p/service_test.go

Reverts prysmaticlabs/prysm#2622
This is not behaving properly with the bootnode and relay.

Revert "Disable libp2p TLS security protocols for now"

---

beacon-chain/rpc/proposer_server.go

After chatting with Danny and Vitalik, we have agreed that canonical filtering is not necessary and it's not a rational validator's behavior. This PR removes canonical attestation filtering

Remove Canonical Attestation Filter

---

beacon-chain/rpc/attester_server_test.go

I saw the following error message when I ran unit test with `-race` flag enabled.
```
==================
WARNING: DATA RACE
Write at 0x00c0000be134 by goroutine 79:
sync.(*WaitGroup).Wait()
/usr/local/Cellar/go/1.12.5/libexec/src/internal/race/race.go:41 +0xef
github.com/prysmaticlabs/prysm/beacon-chain/rpc.TestAttestationDataAtSlot_handlesInProgressRequest()
/Users/htkao/go/src/github.com/prysmaticlabs/prysm/beacon-chain/rpc/attester_server_test.go:285 +0x5a0
testing.tRunner()
/usr/local/Cellar/go/1.12.5/libexec/src/testing/testing.go:865 +0x163
Previous read at 0x00c0000be134 by goroutine 80:
sync.(*WaitGroup).Add()
/usr/local/Cellar/go/1.12.5/libexec/src/internal/race/race.go:37 +0x169 …
```

Fix attester server test data race

---

beacon-chain/core/helpers/committee.go
beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/attester_server.go
beacon-chain/rpc/attester_server_test.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/validator_server_test.go

This PR fixed most of the skipped tests for RPC server. The only ones left are beacon server because it needs a new implementation of ETH1Data end point.
`TestPendingAttestations_OK` was removed because it was a pointless test, not only it wasn't testing much, the main functionality was already covered in `TestPendingAttestations_FiltersExpiredAttestations`

Fixed Skipped Tests for RPC Server

---

shared/p2p/monitoring.go
shared/p2p/service.go

I found static peers were not being dialed. They also were not tracked as peers with the prometheus gauge.
This PR fixes this behavior.

Fix static peering

---

beacon-chain/attestation/service.go
beacon-chain/blockchain/block_processing_test.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/blockchain/stategenerator/state_generator_test.go
validator/client/validator_test.go

Resolves #2696 
This removes `t.skip()` from the tests that were skipped when branch spec-v0.6 was broken. 
The following tests were fixed:
`TestReceiveBlock_DeletesBadBlock`
`TestVoteCount_CacheEnabledAndHit`
`TestGenerateState_OK`
`TestUpdateAssignments_DoesNothingWhenNotEpochStartAndAlreadyExistingAssignments`
The test `TestGenerateState_WithNilBlocksOK` was removed due to the function it was testing for being removed in [this commit](https://github.com/prysmaticlabs/prysm/commit/c0c2671c5f18eda7fbc1022f3027983a5557e080#diff-6ee4abce3ee9e6bd081889b033b07a3e).
The skipped tests I didn't fix are related to Eth1Data which is what #2733 is for and for proposer signatures which are not fully implemented yet.

Fix most of skipped tests

---

beacon-chain/blockchain/fork_choice_test.go
beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/block_test.go
beacon-chain/core/state/state.go
beacon-chain/core/state/state_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go
beacon-chain/rpc/attester_server_test.go
beacon-chain/rpc/validator_server.go
shared/params/config.go

This PR cleaned up all the deprecated beacon chain configs from `config.go`
`LATEST_BLOCK_ROOTS_LENGTH` was renamed to `SLOTS_PER_HISTORICAL_ROOT` in the spec

Remove Deprecated Beacon Chain Configs

---

beacon-chain/core/blocks/block.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_test.go
beacon-chain/core/blocks/validity_conditions.go
beacon-chain/core/helpers/block.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/randao.go
beacon-chain/core/helpers/rewards_penalties.go
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/state/state.go
beacon-chain/core/state/transition.go
beacon-chain/core/validators/validator.go
beacon-chain/rpc/attester_server.go

This PR marie kondo'd the Godoc comments for core package

Tidying up Godoc for Core Package

---

shared/debug/BUILD.bazel
shared/debug/maxprocs_metric.go

This is a simple metric to understand the runtime GOMAXPROCS.

Add go maxprocs metric

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/state/state.go
beacon-chain/rpc/attester_server.go
shared/params/config.go

Part of #2790 
Rename: 
`MaxCrosslinkEpochs` to `MaxEpochsPerCrosslink` in Beacon Chain config 
`BaseRewardQuotient` to [`BaseRewardFactor`](https://github.com/ethereum/eth2.0-specs/pull/1123/files#diff-51a43328a58414e132a744f3771f018cR227) 
parameters in [`get_genesis_beacon_state`](https://github.com/ethereum/eth2.0-specs/pull/1049/files#diff-51a43328a58414e132a744f3771f018cR1195)
Also documentation updates in `process_slashings`

Minor v0.7 updates to config names and function parameters

---

.codecov.yml

I think codecov is counting these files for coverage.

Update codecov to ignore generated code

---

README.md

It was displaying the latest build status, so it was often failing if PRs were being worked on.

Update buildkite badge to show build for master only

---

tools/cluster-pk-manager/server/allocations.go

This was blocking the gRPC server from starting.

Fix blocking routine in cluster pk manager

---

shared/bls/BUILD.bazel
shared/bls/bls.go
shared/bls/bls_test.go

Reverts prysmaticlabs/prysm#2833
We don't need this functionality in our BLS API for spec tests alone. We can test the underlying library to ensure hash g2 messages work properly

Revert "Add Functions for Compressed and Uncompressed HashG2 With Domain"

---

.bazelignore
.bazelrc
.buildkite-bazelrc
WORKSPACE

Reverts prysmaticlabs/prysm#2850
rules_nodejs requires bazel 0.27.0 and rules_go is blocked on 0.27.0.

Revert "Merge renovate updates"

---

beacon-chain/main.go
beacon-chain/node/p2p_config.go
beacon-chain/usage.go
shared/cmd/flags.go
shared/p2p/options.go
shared/p2p/service.go
validator/main.go

If the user specifies this feature flag (adds --enable-upnp as an argument) - the Beacon-chain and Validator services, when started, will initialize libp2p with the UPNP options.
This pull request will resolve issue #2757 
**summary of the changes**
I added a new command line argument : 'enable-upnp'. 
If the user specifies this feature flag (adds --enable-upnp as an argument) - the Beacon-chain and Validator services, when started, will initialize libp2p with the UPNP option.

Added the 'enable-upnp' flag to the list of command line args

---

beacon-chain/attestation/service.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go
beacon-chain/core/helpers/block.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/helpers/randao.go
beacon-chain/core/helpers/randao_test.go
beacon-chain/core/helpers/rewards_penalties.go
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/core/validators/validator.go
beacon-chain/rpc/validator_server_test.go
beacon-chain/utils/shuffle.go
shared/bls/bls.go

This PR is part of:
* cleanup helpers grouping, consistency in naming, comments, etc (https://github.com/ethereum/eth2.0-specs/pull/1237, https://github.com/ethereum/eth2.0-specs/pull/1241)
Change list:
- Updated pseudocode definition for the helper methods
- `CrosslinkCommitteeAtEpoch` -> `CrosslinkCommittee`
- `EpochCommitteeCount` -> `CommitteeCount`
- `EpochStartShard` -> `StartShard`

Update Helper Function's Pseudocode Definitions

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/state/BUILD.bazel
beacon-chain/core/state/state.go
beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go
beacon-chain/rpc/validator_server_test.go
shared/params/config.go
shared/sliceutil/slice.go

Part of #2891, this PR updates the beacon chain config to explicitly mention which fields are constants and which are configurable.
Added `Constants (non-configurable)` section to beacon chain config. Did not include `SECONDS_PER_DAY` and `ENDIANNESS` with changes.
Removed `ActivateValidator` function, replaced with appropriate hard coding in `GenesisBeaconState`, it serves almost no purpose now and would just spam logs upon genesis. 
Removed `MAX_INDICES_PER_ATTESTATION` replaced with `MAX_VALIDATORS_PER_COMMITTEE`.
Renamed `MinValidatorWithdrawalDelay` to `MinValidatorWithdrawabilityDelay` to be aligned with spec.
Renamed `WhistleBlowingRewardQuotient` to `WhistleblowerRewardQuotient` to be aligned with spec.

Make Constants Explicit and Minor Cleanups

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/core/state/transition.go
beacon-chain/core/state/transition_test.go

Brought up in #2892, this moves all length checks to a `verifyOperationLengths` function to prevent extra unneeded computing if an invalid block is submitted.

Move Block Operation Length Checks to ProcessOperations

---

proto/beacon/p2p/v1/types.proto

This PR fixed the ordering of the Protobuf fields to align with the freeze commit
Reference: https://github.com/ethereum/eth2.0-specs/blob/v0.8.0/specs/core/0_beacon-chain.md

Proto Fields Reordering

---

beacon-chain/attestation/service.go
beacon-chain/attestation/service_test.go
beacon-chain/blockchain/block_processing_test.go
beacon-chain/cache/attestation_data_test.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/operations/service_test.go
beacon-chain/rpc/attester_server.go
beacon-chain/rpc/attester_server_test.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/sync/regular_sync.go
beacon-chain/sync/regular_sync_test.go
proto/beacon/p2p/v1/types.proto
proto/testing/ssz_minimal.yaml.go
proto/testing/tags_test.go
validator/client/validator_attest.go
validator/client/validator_attest_test.go

This is mostly checkpoint changes. 
Also restores some (but not all) validation that was removed in #2867

Remove deprecated fields from attestation data

---

beacon-chain/core/blocks/block_operations.go
contracts/deposit-contract/sendDepositTx/sendDeposits.go
shared/keystore/BUILD.bazel
shared/keystore/deposit_input.go
shared/keystore/deposit_input_test.go
tools/cluster-pk-manager/server/server.go
validator/accounts/account.go

Deposits inputs were not aligned with beacon chain logic. All deposits failed to verify. 
This issue shines light on a larger testing gap in Prysm. Tracked by https://github.com/prysmaticlabs/prysm/issues/2955

Fix deposit input data

---

beacon-chain/core/state/state.go
beacon-chain/powchain/BUILD.bazel
beacon-chain/powchain/log_processing.go
shared/featureconfig/config.go
shared/featureconfig/flags.go
validator/client/validator_attest.go
validator/client/validator_attest_test.go

Changes:
- ~Verify signature and deposit tree of deposits~ will follow up in a different PR, this breaks a lot of test setup. 
- Add a feature flag to disable standard genesis delay for testing
- Fix validator signing by using tree hash root instead of signing root

Minor fixes for runtime

---

beacon-chain/core/state/transition.go
beacon-chain/rpc/validator_server.go
contracts/deposit-contract/drainContracts/drainContracts.go
shared/params/config.go

Changes:
- ProcessSlots handles context deadlines in case of long requests
- CommitteeAssignment advances empty state transitions if the requested epoch is farther away than the head state can determine w/o advancements
- Update drain contract to use the new topic hash
- Change demo config to be an extension of the minimal config, with very minor changes
- BLSPubkeyLength updated to 48

Minor runtime fixes 

---

beacon-chain/sync/querier.go
beacon-chain/sync/querier_test.go

Now, in the log, the output: “INFO syncQuerier: Peer with highest canonical head peerID=” without specifying peerID.
After correction, the log is displayed correctly.

best peer assignment fix

---

validator/client/validator_attest.go
validator/client/validator_propose.go

This PR fixes validator logging of public keys
**Before:**
`Attested latest head headRoot=0x415341308ef1ce2bdeed479a shard=2 sourceEpoch=0 targetEpoch=3 validator=[56 55 52 102 51 49 49 101 99 56 52 50]`
**Now:**
`Attested latest head headRoot=0x415341308ef1ce2bdeed479a shard=2 sourceEpoch=0 targetEpoch=3 pubKey=a6b7aec63d91`
There was a few redundant logging like: 1.) waiting to attest, 2.) attesting, 3.) attested. I removed the first two in favor of just attested. Gives us the same amount of information without spamming the logs

Update pubkey logging of validators

---

beacon-chain/blockchain/block_processing.go
beacon-chain/core/blocks/BUILD.bazel
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/blocks/validity_conditions.go
beacon-chain/core/state/BUILD.bazel
beacon-chain/core/state/transition.go
beacon-chain/core/state/transition_test.go

This PR removes the general logging for core package. As discussed this morning, logging volume should be controlled by the logging framework, not conditionals in method arguments. The info logs should be pushed on to the service level

Remove logging from state transition functions

---

beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/operations/BUILD.bazel
beacon-chain/operations/service_test.go

Here's the python spec:
```python
def get_beacon_proposer_index(state: BeaconState) -> ValidatorIndex:
"""
Return the beacon proposer index at the current slot.
"""
epoch = get_current_epoch(state)
committees_per_slot = get_committee_count(state, epoch) // SLOTS_PER_EPOCH
offset = committees_per_slot * (state.slot % SLOTS_PER_EPOCH)
shard = Shard((get_start_shard(state, epoch) + offset) % SHARD_COUNT)
first_committee = get_crosslink_committee(state, epoch, shard)
MAX_RANDOM_BYTE = 2**8 - 1
seed = get_seed(state, epoch)
i = 0
while True:
candidate_index = first_committee[(epoch + i) % len(first_committee)]
random_byte = hash(seed + int_to_bytes(i // 32, length=8))[i % 32]
effective_balance = state.validators[candidate_index].effective_balance
if effective_balance * MAX_RANDOM_BYTE >= …
```

Match spec on proposer index division

---

shared/params/config.go

Reset ejection balance to 1.6ETH for run time to 100 slots. Previous 3.175ETH was too low due to validator decryption delays

Set ejection balance 1.6ETH

---

beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go

Thanks to @nisdas for finding it!
The problem is that we were considering other bits when checking the justification. This really only mattered on consecutive justification scenarios (healthy system). 
With this PR and #2986, we have constant finality and a healthy system with genesis validators.

Fix finality issue

---

beacon-chain/powchain/log_processing.go
beacon-chain/powchain/service.go
beacon-chain/sync/querier.go
beacon-chain/sync/querier_test.go

Fix Querier to handle Deposit Logs Race

---

README.md

Part of #2963 
---
While addressing the improve indices check for #2963, it was discovered that the README's https://github.com/prysmaticlabs/prysm#testing-prysm section links to an invalid URL.
This pull request updates the link to the correct URL: https://github.com/golangci/golangci-lint

Update "Testing Prysm" readme section

---

beacon-chain/core/blocks/block_operations.go

Resolves #2963 
---
Use sort.SliceIsSorted with bit slices to verify they are in order.
This improves sort check within VerifyIndexedAttestation function under
block operations.

Improve sorted indices check in blocks package

---

shared/p2p/BUILD.bazel
shared/p2p/negotiation.go
shared/p2p/negotiation_test.go

Resolves #3071 where two similar contracts were failing negotiation

Compare hex/hash bytes instead of strings

---

beacon-chain/blockchain/block_processing_test.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/blocks/spectest/attestation_test.go
beacon-chain/core/blocks/spectest/attester_slashing_test.go
beacon-chain/core/state/transition.go
beacon-chain/core/state/transition_test.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go

This PR is part of #2951 
This PR removes the verifySignature flag from the processes for RandaoReveal, Attestations, and AttesterSlashings. Since this means all of the operations now require BLS verification, the config parameter has been removed from ProcessOperations 😄

Require Signature Verification in Randao, Attestations and AttesterSlashings

---

WORKSPACE
beacon-chain/core/helpers/eth1data.go

No tracking issue - this PR updates our SSZ to utilize latest changes included in https://github.com/prysmaticlabs/go-ssz/pull/58 to have the hash cache enabled for faster runtime/test time

Update SSZ Dependency With Tree Hash Cache Enabled

---

beacon-chain/core/state/transition.go

Resolves #3082, by clearing out caches at the start of each state transition.

Fix State Root Verification in Sync

---

beacon-chain/core/blocks/block_operations.go

The pseudocode for `ConvertToIndexed` was outdated. This PR updated it

Update ConvertToIndexed pseudocode

---

beacon-chain/db/attestation_test.go

`TestRetrieveAttestations_OK` was failing, but it wasn't discovered because `Log` was used instead of `Error`

Fixed TestRetrieveAttestations_OK test

---

beacon-chain/cache/attestation_data.go

Followup to #3107. 
This was causing attestation issues where an in progress cache fetch would resolve to nil. 
```
[2019-07-30 00:54:48] ERROR validator: Could not request attestation to sign at slot 18: rpc error: code = Unknown desc = a request was in progress and resolved to nil
```

Ignore in progress attestation cache while disabled

---

beacon-chain/rpc/validator_server.go

As title suggested, this fixes validator server to advance the correct number of slots for assignment request.
Looking at previous implementation, `req.EpochStart` = `2`, `s.Slot` = `15`. We'll never be able to advance the slot to 16
```go
if req.EpochStart > 1 && s.Slot < helpers.StartSlot(req.EpochStart-1) {
slotsToAdvance := helpers.StartSlot(req.EpochStart - 1)
s, err = state.ProcessSlots(ctx, s, slotsToAdvance)
return nil, err
}
```

Fix assignment to advance state up to requested slot

---

beacon-chain/blockchain/block_processing.go

State root validation is done within [ExecuteStateTransition](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/state/transition.go#L68), there's a extra redundant state root validation in `ReceiveBlock`, this PR removes it

Remove extra state root check

---

validator/client/validator.go

This fixes #3115 
I'm not sure why we are returning nil if `slot==0` there, it doesn't make sense and causes a panic because validator can't determine assignment until the first epoch start slot (slot8 or slot64) meaning `v.assignments` is `nil` before the first epoch

Fix chain start assignment panic

---

beacon-chain/db/deposits.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go

Fixes when Fetching Pending Deposits

---

beacon-chain/attestation/service.go
beacon-chain/attestation/vote_metrics.go
beacon-chain/db/state_metrics.go

We had a 5 metrics that scaled labels with the validator count. 
This causes a larger burden on the time series database as well as the reporting beacon node. 
I've also added metrics to show total slashed, withdrawn, active, and all time counts.

Remove metrics with high cardinality

---

beacon-chain/rpc/beacon_chain_server.go
beacon-chain/rpc/beacon_chain_server_test.go

This PR skips empty public key to query validator balances instead of fair on empty public key

Skip empty criteria for public key instead of fail

---

beacon-chain/cache/active_balance.go
beacon-chain/cache/attestation_data.go
beacon-chain/cache/block.go
beacon-chain/cache/eth1_data.go
beacon-chain/cache/seed.go
beacon-chain/cache/start_shard.go
beacon-chain/cache/total_balance.go

Part of #3106.
This is to reduce noise from pprof as well as eliminate a potential bottleneck where cache insertions are taking longer than the computation of the value!

Stub insertions when flag off

---

shared/bls/BUILD.bazel
shared/bls/bls.go
shared/bls/bls_benchmark_test.go

`bazel test //shared/bls:go_benchmark_test --test_output=streamed`
```
goos: linux
goarch: amd64
BenchmarkSignature_Verify-4                  100          18446299 ns/op          776041 B/op       2482 allocs/op
BenchmarkSignature_VerifyAggregate-4           2         854807342 ns/op        32744296 B/op      86694 allocs/op
PASS
```
18ms to verify single signature, 850ms to verify aggregate signature of 128 keys (yikes!) 
For reference, [Sigma Prime's library](https://github.com/sigp/milagro_bls) benchmarks these at ~7.3ms and ~7.5ms respectively.

Add quick bls benchmark

---

WORKSPACE
shared/bls/bls.go
shared/bls/spectest/g2_compressed_test.go
shared/bls/spectest/g2_uncompressed_test.go
shared/bytesutil/bytes.go

WIP until https://github.com/phoreproject/bls/pull/11
There are some API changes that need to be improved as well. We're doing unnecessary domain conversions now that the underlying library expects `[8]byte` instead of `uint64`.
Tasks: 
Opening this early to test deployment performance and track in progress work.

Update BLS with @protolambda's improvements

---

validator/accounts/account.go

Use `errors.Wrap` for creating new validator account

Wrap account creation errors

---

beacon-chain/blockchain/block_processing_test.go

In the following tests we make state and block roots slices to be `16777216`. Realistically they won't be that long and `16777216 ` is just the max capacity parameter of the field
Resolves #2993

Set test array to SlotsPerHistoricalRoot

---

beacon-chain/blockchain/fork_choice_reorg_test.go
beacon-chain/blockchain/fork_choice_test.go
beacon-chain/core/helpers/block_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/rpc/attester_server_test.go
validator/accounts/account.go

To build off #3158 
Here we replaced block and state roots construction to default size `SlotsPerHistoricalRoot` in all tests

Use size `SlotsPerHistoricalRoot` for block and state roots

---

beacon-chain/powchain/log_processing.go
beacon-chain/powchain/service.go
beacon-chain/rpc/beacon_server.go
beacon-chain/rpc/beacon_server_test.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/service.go

Problem scenario: if the genesis event happens in a block that has remaining deposits then these deposits are incorrectly being selected for inclusion in a block.
Solution: if the eth1data points to the genesis eth1 event block, do not include new deposits. 
This only effects early epochs around chain start.

Fix deposits at genesis eth1data

---

WORKSPACE
shared/roughtime/BUILD.bazel
shared/roughtime/roughtime.go
shared/slotutil/BUILD.bazel
shared/slotutil/slotticker.go

Part of #2834
---
NTP (network time protocol) responses are insecure and may be subject to MITM attacks.
This PR introduces roughtime which provide secure time synchronisation. We query the time server only once during the package init and panic if the query failed. Roughtime is now used in the validator, but could be used in more contexts.
See https://www.cloudflare.com/time/

Query a roughtime server to mitigate NTP attacks

---

beacon-chain/powchain/log_processing.go

This will help alleviate some of the problems in #3169. 
These changes bubble up the error to the top of the powchain service which will mark itself unhealthy when a fatal deposit processing has occurred.

Return errors in log processing

---

beacon-chain/db/db.go
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/state.go

It was discussed offline we do want to save latest head root in DB. Any node could go offline for a few sec and it would be valuable to have such head information in the DB.
Added `SaveHeadBlockRoot` API for DB, keep in mind we don't need to `SaveHeadBlock` and `SaveHeadState`. Just saving the head root is sufficient enough for the future retrievals.

Save head block root for new DB refactor

---

shared/bls/bls.go

I dont have a regression test because I don't know how to force this to happen, but it was happening in prod.

Fix panic on invalid bls key

---

shared/tracing/tracer.go
tools/cluster-pk-manager/client/main.go

This value is copied from Google's error reporting library.
https://github.com/googleapis/google-cloud-go/blob/b8d0ccd262efda18e5b6684077d076e50541dfff/errorreporting/errors.go#L130
Potentially addresses memory leak: https://github.com/census-ecosystem/opencensus-go-exporter-jaeger/issues/12

Lower jaegar BufferMaxCount

---

beacon-chain/p2p/encoder/BUILD.bazel
beacon-chain/p2p/encoder/network_encoding.go
beacon-chain/p2p/encoder/ssz.go
beacon-chain/p2p/encoder/ssz_test.go
beacon-chain/p2p/encoder/varint.go
beacon-chain/p2p/encoder/varint_test.go

Part of #3147 
P2P messages with SSZ must have the length of the data prefixed as a protobuf.Varint.
There's also some API changes with the network encoder to support `io.Reader` which plays much nicer with libp2p streams than `[]byte`.

Add varint prefixing to ssz network encoder

---

beacon-chain/node/node.go

Resolves #3223.
The fork version changes would need to be added everywhere deposits are calculated. 
Instead of using these changes for genesis fork version, we'll add a parameter in p2p that advertises a fork version for handshakes specifically for prysm testnets. 
Reverts part of #3216

remove the fork version changes from 3216

---

beacon-chain/db/kv/attestations.go
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/utils.go

Follow-up to #3221 and resolves #3064.
---
This PR has some miscellaneous improvements to feedback received on #3221 to use strings of bolt buckets instead of points as keys in maps.

Misc Blocks DB Improvements

---

beacon-chain/db/kv/attestations.go
beacon-chain/db/kv/attestations_test.go
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/blocks_test.go
beacon-chain/db/kv/state.go
beacon-chain/db/kv/validators.go
beacon-chain/db/kv/validators_test.go

No tracking issue - the current DB refactor had a bug that would not return a nil element if none was found.

Allow Nil Return from DB Methods

---

beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go

The test `GetHeadFromYaml` fails 13 out of 100 times. The clear cache was outside of the test case loop so it only got cleared after all test cases ran

Fix GetHeadFromYaml is flakey

---

beacon-chain/blockchain/forkchoice/lmd_ghost_test.yaml
beacon-chain/blockchain/forkchoice/service.go

This PR implements tie breaker for for getting head, and fixes existing test for such tie breaker. The tie breaker favors the one that's higher lexicographically

Forkchoice get head tiebreaker

---

beacon-chain/sync/subscriber.go
beacon-chain/sync/subscriber_handlers.go

No tracking issue, this was causing a panic because it was wrongly registered.
Also renamed some receiver names to be consistent.

Runtime fix for p2p --next

---

beacon-chain/p2p/service.go

No tracking issue, just adding logs to avoid silent failures.

p2p --next start error logging

---

beacon-chain/p2p/service.go

No tracking issue. As title describes.

p2p --next: only attempt discv5 listener when no-discovery flag is not present

---

beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/service.go

Found this while testing run time, we were comparing `singing_root(att)` with `head root`, should have compared `att.data.root` with `head root`

Fix conflict attestation logging

---

beacon-chain/sync/subscriber.go
beacon-chain/sync/subscriber_test.go

No tracking, this is an improvement to make panic non-fatal in regular sync.

Add panic handler for reg sync --next

---

beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_block_test.go
beacon-chain/blockchain/service.go
beacon-chain/p2p/discovery_test.go
beacon-chain/p2p/monitoring.go
beacon-chain/p2p/options_test.go
beacon-chain/p2p/service_test.go
beacon-chain/rpc/proposer_server.go

Previously we could log if an incoming attestation's data root is different than the current head root. This was not quite a valid check since attestation can come in late (up to an epoch late)
Now we change the log to if an incoming attestation target root is different than the target root of our canonical chain, then we know this attestation is on a "competing" chain

Fix competing attestation check

---

beacon-chain/p2p/service.go
beacon-chain/p2p/service_test.go

Now, if  the beacon-node starts without DiscoveryV5 (no-discovery flag or empty / incorrect bootstrap-node flag) then panic occurs at the stop of the node 
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1087ffe]
goroutine 196 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/p2p.(*Service).Stop(0xc0000cf3e0, 0xc0001b2c30, 0xc0004bcf28)
beacon-chain/p2p/service.go:119 +0x2e
github.com/prysmaticlabs/prysm/shared.(*ServiceRegistry).StopAll(0xc0000be860)
shared/service_registry.go:54 +0xc9
github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Close(0xc0000d6cd0)
beacon-chain/node/node.go:174 +0xcb
created by github.com/prysmaticlabs/prysm/beacon-chain/node.(*BeaconNode).Start.func1 …
```

Do not panic if  DiscoveryV5 is not initialized

---

beacon-chain/cache/BUILD.bazel
beacon-chain/cache/checkpoint_state.go

Following effort from #3350 , this ensures we don't mutate the cached state via check point

Proto clone read access to cached checkpoint state

---

beacon-chain/rpc/beacon_chain_server.go
beacon-chain/rpc/beacon_chain_server_test.go
beacon-chain/rpc/service.go
tools/forkchecker/forkchecker.go

Change list:
- Fixed `GetChainHead ` rpc call by actually passing down block chain service
- Updated `ForkChecker` tool and tested it works
```
INFO[0030] Comparing all heads for head slot :429        prefix=forkchoice_checker
INFO[0036] Comparing all heads for head slot :430        prefix=forkchoice_checker
INFO[0042] Comparing all heads for head slot :431        prefix=forkchoice_checker
INFO[0042] Participation rate from beacon node 127.0.0.1:4000  Epoch=53 Finalized=false ParticipationRate=0.875 TotalEther=204800000000 VotedEther=179200000000 prefix=forkchoice_checker
```

Fix GetChainHead for RPC

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/chain_info_test.go
beacon-chain/blockchain/service.go

Chain info from blockchain service should never return nil. This PR ensures before chain start we return zero hashes for FinalizedCheckpoint and HeadRoot

Fix chain info's pre chain start return values

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/db/block.go
beacon-chain/db/db.go
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/schema.go
beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go
beacon-chain/db/state.go

Change list:
- Save genesis root and retrieve genesis state in DB
- Save genesis root when `initializeBeaconChain`
- Retrieve genesis state and initialize fork choice store when chain service `Start()` and `headState != nil`

Save genesis state in DB

---

tools/unencrypted-keys-gen/README.md
tools/unencrypted-keys-gen/main.go

Added to the unencrypted-keys-gen a check that the file does not exist yet. This should help prevent accidentally overwriting keys.

Do not overwrite keys in the unencrypted-keys-gen 

---

beacon-chain/db/kv/checkpoint.go
beacon-chain/db/kv/checkpoint_test.go

Before the first justified or finalized epoch, `db.JustifiedCheckpoint` and `db. FinalizedCheckpoint` will return nil. This fixed them to return the expected checkpoint: `Checkpoint{Root:genesisRoot}`

DB: finalized and justified checkpoints can't return nil

---

beacon-chain/blockchain/forkchoice/service.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go

This PR initializes chain info when chain services first starts. This is when `--clear-db` is not used and there's head stored in DB

Initialize chain info w/o clear db

---

beacon-chain/blockchain/forkchoice/BUILD.bazel
beacon-chain/blockchain/forkchoice/process_block.go

Fixes minor bug where validator / beacon chain might be out of sync on the current time.

Use roughtime for block validity check

---

beacon-chain/blockchain/forkchoice/process_attestation.go

As title suggested, here we use `roughttime` instead of `time`

Use rough time to attestation is not from future epoch

---

tools/bootnode/BUILD.bazel
tools/bootnode/bootnode.go

When a random key is generated, print the private key at debug level so it may be reused if desired.
```
bazel run //tools/bootnode -- --debug
```

Bootnode: Print private key at debug

---

beacon-chain/p2p/handshake.go

Previously we incorrectly logged an unsuccessful handshake as a correct one.

Fix Logging of Handshake

---

beacon-chain/p2p/handshake.go
beacon-chain/p2p/service.go

I think this was somehow reverted, but we shouldn't repeatedly try to dial a peer that is unreachable.

Temporarily ban peer if it fails to connect

---

beacon-chain/node/node.go
beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/info.go
shared/prometheus/service.go

Adds new `/p2p` page served on the monitoring port. Try accessing `http://localhost:8080/p2p`. 
Example:
```
bootnode=enode://e410306cb51fecbb94cbfd7d95111e446c5f1f5fc9c9ddcdd587a1fbf3e5f1f2f636137b830bab2555ad0a66c0235cc9fed0bfb9f71cf9c6c9dd0e9dd2e0bec9@127.0.0.1:5544
self=/ip4/192.168.1.8/tcp/32302/p2p/16Uiu2HAkuvwPDqG7R9PmLm5L6cus2hRMiAC2dekGVqgfRv8mXaEA
1 peers
/ip4/192.168.1.8/tcp/12000/p2p/16Uiu2HAm3V9NRkErwwMkwPgS8oQrc9TFzmFooJRYctnZs8CxkkmL
```

Add /p2p page

---

beacon-chain/core/blocks/block_operations.go
shared/trieutil/sparse_merkle.go
shared/trieutil/sparse_merkle_test.go

Resolves #3393 
---
Currently, our deposit proofs have size `[32][32]byte` when they should instead be `[33][32]byte` for SSZ.
This PR fixes such formatting at the trieutil level. It adds a regression test for SSZ round trip marshal/unmarshal for a deposit containing a Merkle proof, which was the panic we saw at runtime.

Fix Prysm Deposit Formatting

---

beacon-chain/sync/initial-sync/service.go

This was causing the node to be unnecessarily marked as "unhealthy" pre-chainstart

Initial Sync: report healthy before chain started

---

beacon-chain/p2p/broadcaster_test.go
beacon-chain/p2p/encoder/network_encoding.go
beacon-chain/p2p/encoder/ssz.go
beacon-chain/p2p/encoder/ssz_test.go
beacon-chain/p2p/sender.go
beacon-chain/p2p/sender_test.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/sync/error.go
beacon-chain/sync/error_test.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/rpc.go
beacon-chain/sync/rpc_beacon_blocks.go
beacon-chain/sync/rpc_beacon_blocks_test.go
beacon-chain/sync/rpc_hello.go
beacon-chain/sync/rpc_hello_test.go
beacon-chain/sync/rpc_recent_beacon_blocks.go
beacon-chain/sync/rpc_recent_beacon_blocks_test.go
beacon-chain/sync/subscriber.go

Accoridng to spec, we should only give the varint length prefix on RPC.
This makes networking fully compatible with other clients.

Fix broadcast ssz

---

beacon-chain/p2p/options_test.go
beacon-chain/p2p/utils.go
tools/bootnode/bootnode.go
tools/bootnode/bootnode_test.go

The base64 encoded data was some protobuf container as the private key. 
That format breaks interop deploy. Let's use hex for compatibility

Use the raw bytes, not the libp2p protobuf container for sepc256k1 private keys

---

beacon-chain/node/node.go
shared/featureconfig/config.go

No tracking issue - we were not using the demo config flag when starting the beacon chain properly, preventing k8s cluster runs from succeeding

Properly Use Demo Config

---

tools/bootnode/BUILD.bazel
tools/bootnode/bootnode.go

This adds more logging with the `--debug` flag

Enable go-ethereum logs for bootnode

---

beacon-chain/sync/peerstatus/peer_statuses.go

Is `len(map)` threadsafe? I'm not so sure about it. It is technically an integer read on a map and all map operations are not threadsafe.
Adding RLock to be safe.

Rlock around len(map)

---

beacon-chain/blockchain/forkchoice/BUILD.bazel
beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/service.go
beacon-chain/blockchain/receive_block.go
beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go
beacon-chain/operations/BUILD.bazel
beacon-chain/operations/service.go
beacon-chain/sync/service.go

Part of the effort to separate out attestation pool from persistent storage. 
This PR implements `AggregatedAttestation` helper. This is to reduce disparity, there's more than one code block that aggregates attestation.
Tested run time and confirmed it works

Implement `AggregatedAttestation` helper

---

beacon-chain/operations/service.go

The beacon state in `HandleAttestation` was never used, this PR removes it and `ProcessSlots`

Removed unused code in `HandleAttestation`

---

WORKSPACE

Prevents bootnode restarts from disrupting the network, by making bootnode's permanent in the local table

Fix DiscoveryV5

---

WORKSPACE
beacon-chain/p2p/discovery.go
beacon-chain/p2p/service.go

This should allow multiple peers to be able to be use discv5 properly

Lookup Bootnode instead of Random Nodes

---

WORKSPACE
tools/bootnode/bootnode.go

This exposes all the bootnode's stored nodes to a page, from which we can inspect them.
`localhost:5000/p2p` would be served with information on all the nodes

Expose Nodes

---

beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/rpc/attester_server.go

1. When logging broadcasted attestation root, use `TreeHashRoot(att.Data)`
2. Use `errors.Wrap` for `VerifyIndexedAttestation` in process attestation

Fixed 2 cosmetic errors

---

beacon-chain/blockchain/forkchoice/process_block.go

#3542 broke initial sync and regular sync by adding `waitForAttInclDelay` and `verifyAttSlotTime` checks for updating block's attestation votes. These checks were redundant as we already check them as part of processing block and processing attestations in block beforehand

Removed `verifyAttSlotTime` check for updating fork choice votes

---

beacon-chain/core/state/interop/BUILD.bazel
beacon-chain/core/state/interop/write_block_to_disk.go
beacon-chain/core/state/interop/write_state_to_disk.go
beacon-chain/core/state/transition.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

This should be opt-in rather than always on. 
Also writes blocks too. 
resolves #3492

Only write interop ssz states to disk with flag ON

---

beacon-chain/sync/service.go
beacon-chain/sync/validate_beacon_blocks.go

We saw multiple processing of beacon block during regular sync:
```
[2019-09-23 16:11:03]  INFO forkchoice: Executing state transition on block slot=531
[2019-09-23 16:11:03]  INFO forkchoice: Executing state transition on block slot=531
[2019-09-23 16:11:03]  INFO forkchoice: Executing state transition on block slot=531
```
This happens because we receive blocks from 3 people at the same time, which is why we are adding a lock around `validateBeaconBlockPubSub`

Lock around validateBeaconBlockPubSub

---

shared/trieutil/BUILD.bazel
shared/trieutil/merkle_trie.go
shared/trieutil/merkle_trie_test.go

Getting us ahead of the curve, this PR starts implementing merkle trie related helpers for testing generalized index and merkle multi proofs. This is a very important component for phase 1 and light client protocol.
References: https://github.com/ethereum/eth2.0-specs/blob/50209ea806820f83ceff3f21e1578191db0a71e5/specs/light_client/merkle_proofs.md#helper-functions

Merkle tree math helpers

---

contracts/deposit-contract/testutils.go
validator/accounts/BUILD.bazel
validator/accounts/account.go

Resolves #3576 
This prints the raw transaction data into the console, so that users can simply copy and paste it when submitting the transaction to the eth1 chain.

Fix Validator Account Creation

---

WORKSPACE

This has a fix for mac where com_github_rjeczalik_notify would not build.
Also deleted some deps that were no longer used in the workspace

Update bazel-go-ethereum, delete unused deps

---

beacon-chain/operations/service.go

This was causing a wall of logs on shutdown at debug level

Operations service: exit go routine on error

---

WORKSPACE
shared/bls/BUILD.bazel
shared/bls/bls.go

No tracking issue
---
pprof was showing this method using up to 25% of wall time during init sync. This cache method has a high hit rate as the pubkeys used in the arguments are the validator keys. 
Results:
- 1 to 2 blocks per second increase in initial sync processing performance

BLS pubkey from bytes cache

---

beacon-chain/blockchain/forkchoice/process_block.go

As title describes, invalid attestations would break initial sync but should be ignored.

Log warning with error instead of returning an error in fork choice attestation votes updates

---

beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/round_robin_test.go

In the scenario where there are many skip slots, the round robin sync would stall if the given range was empty. This PR resolves that unlikely scenario.

Handle large ranges of skipped slots

---

beacon-chain/sync/initial-sync/service.go

Seeing some weird scenario in prod were initial sync never started. These logs might help troubleshoot the event when it happens again.

Add a few logs at start of initial sync

---

beacon-chain/rpc/beacon_chain_server.go
beacon-chain/rpc/beacon_chain_server_test.go

No tracking issue - this PR returns all validators in the activation/exit queues and does not clip them based on churn. Instead, that should be handled by the client requesting the information.

Return All Pending Queue Validators in GetValidatorsQueue RPC

---

beacon-chain/node/node.go
beacon-chain/p2p/discovery.go
shared/cmd/flags.go

At current the `--bootstrap-node` appends to the default list of bootstrap nodes rather than overwriting it.
This patch provides the desired functionality, retaining the ability to supply multiple comma-separate nodes if required.

Allow overwriting of default bootstrap node

---

beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go

Part of #3603
This PR introduces `UpdateCommitteeCache` for updating the previous implemented committee shuffled indices cache during run time. Also added a test to it as well

Part 3 of caching improvement - Update cache

---

INTEROP.md
beacon-chain/interop-cold-start/service.go
beacon-chain/node/node.go
shared/interop/BUILD.bazel
shared/interop/generate_genesis_state.go
tools/genesis-state-gen/main.go

An attempt to generate a genesis with a large number of validators results in the beacon chain not able to start within the first epoch. As a result, the chain never runs.
This patch defaults the `genesisTime` parameter in `genesis-state-gen` to the current time *after all validator-related work has been completed*. This ensures the beacon chain can start in good time regardless of the number of validators.
Also updated interop doc, dropping genesis-time parameter where it is not required.

Default genesisTime to now when generating a genesis state.

---

beacon-chain/sync/service.go

Somehow the nodes are reporting healthy but also rejecting pubsub messages due to syncing.
This marks the regular sync service as unhealthy in the case that init sync is still syncing

Report sync unhealthy in the case that the node is still syncing

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go

Specifically when starting initial sync from an existing database, there is a chance that the node's existing data is on a fork of the finalized chain. Rolling back their view of "head" to the last finalized epoch gives certainty that the beacon chain node will correctly sync the finalized chain.

Bootstrap from finalized checkpoint rather than head slot

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/service.go

There are some rare cases where initial sync is not starting. I suspect that the state was initialized before initial sync service subscribed to feed. 
This PR subscribes to the state feed then checks if the state was already initialized. Maybe another improvement is to panic when trying to subscribe to this feed when we know it would never fire again. 
Also ran gofmt.

Fix init sync race condition

---

beacon-chain/sync/service.go

Otherwise nodes report unhealthy pre-chainstart

Only report reg sync unhealthy after chainstart

---

WORKSPACE

This updates prysm to the current version of our fork of geth. It was updated to v1.9.5, so this allows us 
to fix a few client side bugs when using their rpc client for websocket connections.

Update to latest version of Go-Ethereum

---

contracts/deposit-contract/README.md

The `abigen` command specified in the validator contract's README has the incorrect arguments to create the desired result.  This patch provides the correct arguments (specifically the package and contract function names).

Update abigen command

---

WORKSPACE

Totally unnecessary to have this. The upstream library uses go-ethereum/core which has some reference to go-ethereum/metrics. `gosigar` uses cgo to read some CPU level metrics and we don't use that so we can remove it.
The only code path here was from the contracts bindings.

Remove dep on github.com/elastic/gosigar

---

beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/blockchain/forkchoice/process_block.go
shared/params/config.go

Whether it was attestations in block or individual attestation over the wire, we were saving them one by one. This PR updated to batch save these attestations. This is a better practice because a block can contain up to 128 attestations

Batch save attestations in state transition

---

beacon-chain/sync/subscriber.go
beacon-chain/sync/validate_attester_slashing.go
beacon-chain/sync/validate_attester_slashing_test.go
beacon-chain/sync/validate_beacon_attestation.go
beacon-chain/sync/validate_beacon_attestation_test.go
beacon-chain/sync/validate_beacon_blocks.go
beacon-chain/sync/validate_beacon_blocks_test.go
beacon-chain/sync/validate_proposer_slashing.go
beacon-chain/sync/validate_proposer_slashing_test.go
beacon-chain/sync/validate_voluntary_exit.go
beacon-chain/sync/validate_voluntary_exit_test.go

This adds an error to message validation, so that we only log an error if an actual error exists. Otherwise we ignore it and do not log it.

Add Error to Message validation

---

beacon-chain/sync/initial-sync/round_robin.go

No tracking issue - this just fixes a small aesthetic issue in initial sync logs to make the output look more standardized and aligned.

Tiny Logging Fix

---

shared/prometheus/service.go

Using fluentd logger we saw a lot of errors like 
```
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: map[reflect.Type]error
```

log buf.String() instead of map[reflect.Type]error

---

beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/receive_block_test.go
beacon-chain/blockchain/service_test.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/helpers/attestation_test.go
beacon-chain/core/state/state_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/operations/service_test.go
beacon-chain/powchain/deposit_test.go
beacon-chain/powchain/log_processing_test.go
beacon-chain/rpc/proposer_server_test.go
beacon-chain/rpc/validator_server_test.go
beacon-chain/sync/validate_attester_slashing_test.go
shared/testutil/helpers.go
shared/testutil/helpers_test.go

Second part of the updates to allow smoother transition to a validating deposit contract (first part was #3639)
---
This PR updates the signature of `testutils.SetupInitialDeposits()` to return the hash tree roots of the deposit data for each deposit.  This means that in future as/when the updated deposit contract requires this information it will be available within tests without additional work and reduce the size of that patchset.
At current this additional data is used in only one test, but there are other tests in the codebase that use junk data for the deposits.  Subsequent patches will fix up these tests to use real data from `SetupInitialDeposits()` to allow these structures to pass verification, provide well-defined results against which tests can be made, and to be passed to …

SetupInitialDeposits() now returns deposit data roots

---

beacon-chain/db/BUILD.bazel
beacon-chain/db/db.go
beacon-chain/db/http_backup_handler.go
beacon-chain/db/kv/BUILD.bazel
beacon-chain/db/kv/backup.go
beacon-chain/db/kv/backup_test.go
beacon-chain/db/kv/kv.go
beacon-chain/node/clear_db.go
beacon-chain/node/node.go
beacon-chain/p2p/sender.go
beacon-chain/sync/initial-sync/round_robin.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

Also adds the ability to initiate the database backup via web hook. 
With the flag `--enable-db-backup-webhook`, you can http call `GET http://localhost:8080/db/backup` and the backup will be written to disk.

Add database API for creating backups

---

shared/bls/bls.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

Right now, the BLS pubkey.Copy method does not do a clean copy. It is reusing pointers which could lead to a poisoned cache.
Adding a flag to selectively enable the cache while we resolve that issue.

Add flag to enable BLS pubkey cache

---

beacon-chain/blockchain/chain_info_test.go

Chain service's `GenesisTime` and `CurrentFork` had no test coverage. This PR added coverages for that

Coverage for chain info

---

beacon-chain/powchain/service.go
shared/featureconfig/flags.go

In the case of any failure from our current subscription, we will try to re-subscribe to the current headers from the eth1 chain.

Resubscribe Headers from ETH 1 Chain

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/service.go
beacon-chain/cache/attestation_data.go
beacon-chain/cache/eth1_data.go
beacon-chain/cache/feature_flag_test.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/state/interop/write_block_to_disk.go
beacon-chain/core/state/interop/write_state_to_disk.go
beacon-chain/node/node.go
beacon-chain/powchain/log_processing.go
beacon-chain/rpc/attester_server_test.go
beacon-chain/sync/initial-sync/round_robin.go
shared/bls/bls.go
shared/featureconfig/config.go
shared/featureconfig/config_test.go
validator/main.go
validator/node/node.go

This PR cleans up feature config naming to avoid duplication with package names:
`featureconfig.FeatureConfig` -> `featureconfig.Get`
`featureconfig.InitFeatureConfig` -> `featureconfig.Init`
`featureconfig.ConfigureBeaconFeatures` -> `featureconfig.ConfigureBeaconChain`
`featureconfig.ConfigureValidatorFeatures` -> `featureconfig.ConfigureValidator`

Clean up feature flag namings

---

beacon-chain/powchain/log_processing.go

This adds the tx and block hashes to the error generated when an invalid deposit on the ETH1 chain is detected, to allow for easier tracing on that chain.

Additional log information for invalid deposits

---

beacon-chain/sync/rpc_beacon_blocks_by_root.go

We return a generic error, if the block does not exist in our db. However due to us no longer requiring a 1-1 mapping of requests and responses, we can ignore the request for that block root, and continue on towards the next block root requested to respond to.

Continue Writing to The Stream Despite Failures

---

README.md

3 characters PR because ``--clear-db` require interactivity and terminal emulation to work and have a nice CLI

Fix missing parameters in docker command

---

beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/round_robin_test.go

This fixes our test by fixing some bugs in our initial sync algorithm. 
multiple failures, the step value grows large

Fix Round Robin Test

---

WORKSPACE

Updates to our latest commit in our go-ethereum fork.

Update Bazel Go-Ethereum

---

README.md
validator/client/service.go
validator/client/service_test.go

An earlier commit resulted in copying of the same validator key to all key entries; this fixes that issue.
Note I attempted to add a test to catch this but can't find a way of starting the validator service as it seems to want a valid GRPC endpoint.  Is there a mock endpoint that can be used to allow the test to proceed?
```
func TestSetup_UniqueKeys(t *testing.T) {
ctx, cancel := context.WithCancel(context.Background())
validatorService := &ValidatorService{
ctx:      ctx,
cancel:   cancel,
endpoint: "???",
keys:     keyMapThreeValidators,
}
validatorService.Start()
if bytes.Compare(validatorService.validator.(*validator).pubkeys[0], validatorService.validator.(*validator).pubkeys[1]) == 0 {
t.Fatalf("Multiple validator keys with same value")
}
cancel()
if err := validatorService.Stop(); …
```

Remove key duplication

---

beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go

Returns error `ErrAttestationAggregationBitsOverlap` if two attestations bitfields overlap each other

Check attestations bitfield overlaps

---

tools/unencrypted-keys-gen/main_test.go

The test for the generate-unencrypted-keys tool doesn't generate any keys in its test.  This adds keys to the test to make it more realistic.
This also pre-emptively stops the test failing when it passed 0 to `interop.DeterministicallyGenerateKeys()`, which is required for a future PR.

Generate keys in test

---

beacon-chain/sync/peerstatus/peer_statuses.go

`Count()` tries to secure another RLock when we already had one, to read the length of the map.
This might be causing goroutine issues and/or deadlocking

Do not use mutliple read locks

---

beacon-chain/db/db.go
beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go

This PR adds functions to batch delete in DB. This will be used for pruning beacon state stored in DB prior to finalized check point

Add State Batch Delete for DB

---

beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/round_robin_test.go

Reverts prysmaticlabs/prysm#3775
This is often causing peers to get spammed with erroneous ranges in the hundreds of thousands or millions. This issue is worse than missing blocks in multiple failure conditions.

Revert "Fix Round Robin Test"

---

beacon-chain/blockchain/service.go

Not sure why we `SaveGenesisBlockRoot` twice 🤔

Removed extra save genesis block root

---

docs/READINGS.md

Previous link was broken. Using the new link from `www.ethereum.org`

Fix `What is Ethereum?` link

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go
tools/interop/export-genesis/main.go

Change list:
- Revert the order on `SaveFinalizedCheckpoint` and `rmStatesBySlots`
- Guard `DeleteState` against deleting genesis and finalized states
Resolves #3841

Guard against deleting genesis and finalized state in DB

---

beacon-chain/blockchain/service_test.go
beacon-chain/db/kv/BUILD.bazel
beacon-chain/db/kv/checkpoint.go
beacon-chain/db/kv/checkpoint_test.go
beacon-chain/db/kv/state_test.go

Part of prevention for #3841.
The database must have the finalized state before updating the finalized checkpoint.

Require state to exist when updating finalized checkpoint

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/powchain/deposit.go
beacon-chain/powchain/deposit_test.go
beacon-chain/rpc/validator_server_test.go
shared/bls/BUILD.bazel
shared/bls/bls.go
shared/bls/bls_test.go
shared/featureconfig/flags.go
shared/interop/generate_genesis_state.go
shared/keystore/deposit_input.go
shared/testutil/helpers.go

We were using `get_domain` instead of `compute_domain` to both sign and verify deposits. Thanks to @paulhauner for bringing this up. The spec requires the domain to use a zeroed fork version https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#compute_domain
However we cannot hardcode it yet to use a zeroed fork version until the next testnet restart. This is tracked here #3853

Use Compute Domain Instead of Get Domain

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
shared/featureconfig/flags.go

We saw the following error: 
```
could not process block from fork choice service: could not save finalized checkpoint: no state exists with checkpoint root
```
This was due to incorrect pruning. We did not consider the edge case where `StartSlot` is not the same as `FinalizedSlot`. Example:
```
FinalizedEpoch:1, StartSlot: 8, EndSlot: 15 (Works!)
NewFinalizedEpoch:5, StartSlot: 16, EndSlot: 47 (Doesn't work! 40 gets deleted)
Instead we should delete them in pair:
NewFinalizedEpoch:5, (StartSlot: 16, EndSlot: 39), (StartSlot: 41 EndSlot: 47) 
```

Fix pruning finalized state

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/forkchoice/service.go

Current state pruning scheme does not comply with skip block scenario, given the following example:
```
epoch:10 slots:80-87
epoch:11 slots:88-95
epoch:12 slots:96-103
```
**Problem**
When Epoch 11 finalizes, it deletes states from slots 89 to 95. When epoch 12 finalizes and slot 96 happens to be skipped. State 95 no longer exists, we prematurely deleted a finalized state, but didnt know that at the time of deletion
**Solution**
Track `last_finalized_epoch` and prune states between `last_finalized_epoch` to `finalized_epoch`. Downside of this is we'll have to keep 1 finalized_epoch_duration worth of state but ensures we never prematurely delete finalized state when skip block happens

Prune states since last finalized

---

beacon-chain/sync/initial-sync/BUILD.bazel
beacon-chain/sync/initial-sync/round_robin.go

Fixed the data racing and slightly changed the initial synchronization logic
Related to #3665 (might fix it)
Precisely makes initial synchronization more reliable
Major changes:
* removed multithreaded call of `respBlocks = append (respBlocks, resp ...)`
* variables is localized to avoid overlapping

fix data race in roundRobinSync

---

beacon-chain/core/epoch/precompute/attestation.go
beacon-chain/core/epoch/precompute/attestation_test.go
beacon-chain/core/epoch/precompute/reward_penalty.go

This fixes a bug with process epoch using optimized mode. When we calculate attestation inclusion rewards, it's based off on previous epoch attestations. In the current implementations, we are based off on previous and current attestations

Inclusion rewards are based off previous epoch

---

beacon-chain/powchain/log_processing.go
shared/featureconfig/config.go
shared/featureconfig/config_test.go
shared/featureconfig/flags.go

Make No Genesis Delay the Default

---

beacon-chain/core/state/transition.go
shared/version/version.go

Following on #3879, this resolves a small bug which was introduced where state entries would be written to the cache regardless if the retrieved state from the cache had a higher or lower slot. This fixes it by only writing to the cache in the case that the cached entry has a lower slot then the needed slot.

Set WriteToCache Bool Correctly

---

beacon-chain/core/epoch/spectest/justification_and_finalization_minimal_test.go
beacon-chain/core/epoch/spectest/justification_and_finalization_test.go

Part of #3865 
This PR unskips minimal test for justification and finalization

Unskip minimal spec test for finalization

---

shared/params/config.go

OK to merge now. Testnet is down pending restart.

Testnet restart: bump fork version

---

beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go

Quick fix on committee assignment, we were suppose to use the index of the committee in respective to slot, not the index of the validator in respective to committee

Fix Committee Assignment

---

beacon-chain/db/filters/filter.go
beacon-chain/db/filters/filter_test.go

After we have removed shard from beacon chain, this PR removed shard filter in DB since `shard` is no longer a field in attestation

Remove shard filter in db

---

beacon-chain/p2p/encoder/BUILD.bazel
beacon-chain/p2p/encoder/ssz_test.go

`TestLighthouseBeaconBlockResponse` no longer works with latest SSZ commit and v0.9. The test solely depends on raw bytes data which makes it really hard to maintain.
We'll have more lighthouse compatibility tests and fixes as they join our testnet soon

Remove lightouse compatibility test

---

shared/version/version.go

Resolves #3943 
---
**Did not take into account that `git` would not be installed. This is the main case when run from a stripped down docker image.

do not die if user does not have git installed

---

beacon-chain/db/kv/finalized_block_roots_test.go
beacon-chain/sync/validate_beacon_attestation.go
beacon-chain/sync/validate_beacon_attestation_test.go
proto/eth/v1alpha1/slasher.pb.go
slasher/db/min_max-span_test.go
validator/internal/attester_service_mock.go
validator/internal/node_mock.go
validator/internal/proposer_service_mock.go
validator/internal/validator_service_mock.go

Currently as part of our attestation validation, we reject attestations which have the less than or equal to source/target epoch as our finalized checkpoint. However this also ends up rejecting attestations in our genesis epoch.

Do Not Reject Attestations in Genesis Epoch

---

WORKSPACE
proto/eth/v1alpha1/_compatibility/compatability_test.go

This PR unskips `TestProtoCompatability`

Unskip TestProtoCompatability

---

beacon-chain/blockchain/forkchoice/process_attestation.go

Since we no longer needs to call `AttDataAtSlot` to retrieve attestation's slot, The logic of `verifyAttSlotTime` can be greatly simplified

Simplify verifyAttSlotTime

---

beacon-chain/blockchain/forkchoice/process_block.go

This prevents nil access panic

Check nil base state for attestation tgt root

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/receive_block.go
proto/beacon/db/attestation_container.pb.go
proto/beacon/db/finalized_block_root_container.pb.go
proto/beacon/p2p/v1/messages.pb.go
proto/beacon/p2p/v1/types.pb.go
proto/beacon/rpc/v1/services.pb.go
proto/beacon/rpc/v1_gateway/services.pb.go
proto/eth/v1alpha1/archive.pb.go
proto/eth/v1alpha1/attestation.pb.go
proto/eth/v1alpha1/beacon_block.pb.go
proto/eth/v1alpha1/beacon_chain.pb.go
proto/eth/v1alpha1/node.pb.go
proto/eth/v1alpha1/validator.pb.go
proto/sharding/p2p/v1/messages.pb.go

This performs a copy of the block on receiving it from sync, to prevent mutation of the deposit proof.
Resolves #3965

Copy Block When Receiving it From Sync

---

beacon-chain/rpc/attester_server.go
beacon-chain/rpc/attester_server_test.go
beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/service.go
beacon-chain/rpc/validator_server.go
beacon-chain/rpc/validator_server_test.go

These RPC methods will require beacon node to be sync'ed to latest head. Added a check and if it's not sync'ed, returns error

RPC checks sync status

---

beacon-chain/rpc/proposer_server.go
beacon-chain/rpc/service.go
proto/eth/v1alpha1/slasher.pb.go

We change to a random vote instead of a mocked vote due to the fact that if we do become disconnected with an eth1node. We do not want the mocked eth1Data to form the majority, so we instead utilize a random eth1data vote so that they can never form a majority and be included in the state as each node will have a different eth1data vote.

Change to Random Vote

---

beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_attestation_test.go

Part of #3960 
Given current time now. This PR added validation step to verify attestation's target epoch is the same as current epoch or previous epoch

Decoy flip flop check

---

beacon-chain/archiver/service.go
beacon-chain/archiver/service_test.go
beacon-chain/core/epoch/BUILD.bazel
beacon-chain/core/epoch/participation.go
beacon-chain/core/epoch/participation_test.go
beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go
tools/forkchecker/forkchecker.go

Resolves #3971 
Currently, `GetValidatorParticipation` in the API only gets the participation for the current head, which changes every slot, and is not accurate at all for participation unless called on the last slot, which is not user friendly.
This PR changes `ComputeValidatorParticipation` to allow computing validator participation for the current and previous epoch. It also changes `GetValidatorParticipation` to return the previous epoch participation by default, calculated from the state, and the current head participation can be specifically requested (as I did for fork choice) as needed.

Change GetValidatorParticipation to compute participation from previous epoch 

---

beacon-chain/blockchain/chain_info_test.go
beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/forkchoice/service.go
beacon-chain/blockchain/forkchoice/service_test.go
beacon-chain/blockchain/receive_block_test.go
beacon-chain/core/helpers/slot_epoch.go
shared/params/config.go

Part of #3960
This PR added validation step to prevent fork choice bounce attack. See more: https://github.com/ethereum/eth2.0-specs/pull/1465

Bounce attack check

---

WORKSPACE
beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/spectest/attestation_mainnet_test.go
beacon-chain/core/blocks/spectest/attester_slashing_mainnet_test.go
beacon-chain/core/blocks/spectest/block_processing_mainnet_test.go
proto/testing/ssz_static_mainnet_test.go

Part of #3960 
This PR unskips mainnet spec tests

Unskip mainnet spec tests

---

beacon-chain/rpc/attester/BUILD.bazel
beacon-chain/rpc/attester/server.go
beacon-chain/rpc/beacon/assignments.go
beacon-chain/rpc/beacon/assignments_test.go
beacon-chain/rpc/beacon/attestations.go
beacon-chain/rpc/beacon/attestations_test.go
beacon-chain/rpc/beacon/blocks.go
beacon-chain/rpc/beacon/blocks_test.go
beacon-chain/rpc/beacon/committees.go
beacon-chain/rpc/beacon/committees_test.go
beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go
beacon-chain/rpc/node/server.go
beacon-chain/rpc/proposer/server.go
beacon-chain/rpc/validator/BUILD.bazel
beacon-chain/rpc/validator/assignments.go
beacon-chain/rpc/validator/server.go
beacon-chain/rpc/validator/server_test.go
beacon-chain/rpc/validator/status.go

Resolves #3974
---
This PR creates more informative errors in our RPC package using gRPC status codes, and adds more clarity to failures when attempting to retrieve archival data that does not exist, telling the user it is likely due a node not being `--archive` enabled.

Productionize RPC Server Error Codes

---

beacon-chain/rpc/beacon/validators.go

---
Thanks @tzapu for catching this error:
```
alex@playground:~$ curl -X GET "http://localhost:3001/eth/v1alpha1/validators/activesetchanges?epoch=85" -H  "accept: application/json"
{"error":"runtime error: invalid memory address or nil pointer dereference","code":2,"message":"runtime error: invalid memory address or nil pointer dereference"}alex@playground:~$ 
```
The problem is when we retrieve archival data from the DB in that RPC method, we don't do a nil check on the retrieved data.
This PR adds a nil check to return a proper error instead of panicking.

Nil Check in Active Set Changes RPC

---

WORKSPACE
beacon-chain/BUILD.bazel
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/helpers/attestation_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/gateway/server/BUILD.bazel
beacon-chain/operations/attestation_test.go
beacon-chain/powchain/deposit_test.go
beacon-chain/rpc/validator/server_test.go
beacon-chain/sync/validate_proposer_slashing_test.go
beacon-chain/sync/validate_voluntary_exit_test.go
shared/bls/BUILD.bazel
shared/bls/bls.go
shared/bls/bls_benchmark_test.go
shared/bls/bls_test.go
shared/bls/spectest/BUILD.bazel
shared/bls/spectest/aggregate_pubkeys_test.go
shared/bls/spectest/msg_hash_compressed_test.go
shared/bls/spectest/msg_hash_uncompressed_test.go
shared/bls/spectest/priv_to_pub_test.go
shared/keystore/BUILD.bazel
shared/keystore/key.go
shared/keystore/key_test.go
shared/mathutil/math_helper_test.go
tools/cluster-pk-manager/client/BUILD.bazel
tools/cluster-pk-manager/server/BUILD.bazel
tools/faucet/BUILD.bazel
validator/BUILD.bazel

Reverts #4006 which reverted #3752 . 
This fixes our docker builds which doesn't ask for `libstdc++` when running a binary.

Reverts the Revert

---

beacon-chain/archiver/service.go
beacon-chain/archiver/service_test.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/core/validators/BUILD.bazel
beacon-chain/core/validators/validator.go
beacon-chain/core/validators/validator_test.go
beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go

This PR is a follow-up to #4005 
---
Active set changes were not being properly archived and saved to the DB due to an off by one. In particular, we were trying to store the active set changes for the current epoch, but that is not possible, as those will only exist for a previous epoch given how the helper functions work.
This PR also refactors some helper functions for reusability to take in specific input arguments instead of `state *pb.BeaconState`

Properly Archive Active Set Changes

---

slasher/db/indexed_attestations.go
slasher/db/indexed_attestations_test.go
slasher/db/schema.go

[Part of] #3133
---
remove source epoch from indexed attestation store as it is not needed for indexing and for double vote detection.

remove source epoch from indexed attestation indices

---

beacon-chain/blockchain/forkchoice/process_block.go

This fixes state pruning during the first finalized check point where `prevFinalizedCheckpt` and `finalizedCheckpt` epochs are both 0, we also uncovered a DB bug where end slot > start slot returns invalid block roots

Check end slot for state pruning

---

beacon-chain/blockchain/forkchoice/process_attestation.go

This fixes #4035
When an attestation (bad) fails to verify, we should immediately return error rather than proceed to update its votes

Return err for verifyAttestation

---

.buildkite-bazelrc

I think builds are failing after upgrading bazel to v1.1.0 in build runners, it might be due to fully_async mode for build event service uploads to google cloud.

remove fully async from bes upload

---

beacon-chain/p2p/service.go

Adding on to #4040 , replaces all breaks with returns in cases of canceled context.

Replace all Breaks with Returns

---

beacon-chain/core/helpers/committee.go

The `slot` used to calculate `CommitteeCountAtSlot` was incorrect.

Fix UpdateCommitteeCache slot

---

.buildkite-bazelrc

Build event service is failing 
```
The Build Event Protocol upload failed: INTERNAL: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
```
No idea why and no one really uses it anyway.

Buildkite: Disable failing BES

---

validator/client/validator_aggregate.go
validator/client/validator_aggregate_test.go

For aggregator, one should wait until two thirds of the way through the slot to broad cast the best aggregate. This PR implements `waitToSlotTwoThirds` and test

Implement wait till two thirds

---

validator/client/validator_attest.go
validator/client/validator_attest_test.go

Update the attester to wait till one-third from half of the slot to align with the spec:
https://github.com/ethereum/eth2.0-specs/blob/v0.9.0/specs/validator/0_beacon-chain-validator.md#attesting

Update attester to wait till one-third

---

beacon-chain/blockchain/forkchoice/metrics.go
beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/metrics.go

The previous metrics to capture finalization stats was not enough. It only captures finalization from a processed state. This PR adds additional metrics for
-  head state
- cached check point

Complete finalization metrics

---

shared/params/config.go

Part of #4098 
Reduced genesis validator count from 65536 to 16384
See rationale: https://github.com/ethereum/eth2.0-specs/pull/1467

Reduce genesis validator ocunt

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/options.go

This flag has been broken since the refactoring of p2p library.
I've tested locally that peer count is reduced to the threshold as expected.

Enforce --p2p-max-peers

---

beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go

Resolves #4076
---
We should not allow users to retrieve validator participation for the current epoch, as it is error-prone and almost entirely inaccurate. As seen in #4076, it can lead to big errors regarding out of bounds in certain arrays.
This PR throws an error if attempting to retrieve current epoch participation specifically

Prevent Requesting Current Epoch for Validator Participation

---

beacon-chain/p2p/options.go

We are observing a high churn of peers, probably because they are allowed to be connected for 1 minute before being disconnected.

Lower conn mgr grace period to 1s

---

WORKSPACE
tools/blocktree/BUILD.bazel
tools/blocktree/main.go

This tool helps to generate graphviz data by inputing a db, start slot and end slot. One can paste this graphviz data to a render site to get the full visualized form of the tree. 
example
```
➜  blocktree git:(block-tree-tool) go run main.go --datadir /Users/terencetsao/badfinality/beaconchaindata/ --startSlot 74101 --endSlot 74150
digraph  {
labeljust="l";rankdir="RL";
n10[label="slot: 74114\n root: 0165",shape="box"];
n25[label="slot: 74132\n root: 04bb",shape="box"];
n2[label="slot: 74104\n root: 0bbc",shape="box"];
n33[label="slot: 74148\n root: 0d5e",shape="box"];
n8[label="slot: 74111\n root: 1c5a",shape="box"];
n24[label="slot: 74131\n root: 219a",shape="box"];
n14[label="slot: 74118\n root: 2880",shape="box"];
n6[label="slot: 74109\n root: 2c3f",shape="box"];
n15[label="slot: …
```

Tool to dump graphviz data for block tree

---

beacon-chain/sync/initial-sync/round_robin.go
tools/blocktree/main.go

Resolves #4041
Before sending out a new request, we check if the start slot of the request is higher than the finalized epoch. We also include potential skipped slots in our check.

Account for Skipped Slots When Requesting for Blocks

---

beacon-chain/db/kv/prune_states.go

Removing already pruned states check.  It shouldn't be a problem to go back saving boundary states once it's already pruned 
Flipped `pruneStatesKey` to `0x00` when going back to saving boundary states

Remove pruned states check

---

WORKSPACE

There have been some performance improvements in the google API bundler that is used by the opencensus/jaeger tracing library. 
This PR updates those dependencies and adds a few new transitive deps.

Update tracing dependencies

---

beacon-chain/core/state/benchmarks/README.md
beacon-chain/core/state/benchmarks/benchmarks_test.go

This PR fixes the issue of the sanity tests for benchmarks taking too long, it removes the test for ProcessEpoch (Which takes way too long and isn't really needed for this).
It also caches BLS pubkeys for the block benchmark, to bring us an improved time of 21 seconds.

Reduce amount of time for benchmark tests

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/pending_blocks_queue_test.go

Reverts prysmaticlabs/prysm#4101
This was previously reverted due to cluster issues we encountered. However, a week later it is much more clear now that this was never the root cause of it.

Revert Revert(Update Pending Queue)

---

beacon-chain/rpc/beacon/validators.go

Quick fix on typos on what to return for participation if no epoch is specified
- Should return  `requestedEpoch` instead of `currentEpoch` since we use `requestedEpoch` to query for participation numbers
- `Finalized` should not be hard coded to `false` since it's using last epoch as default

Fix on participation RPC return

---

beacon-chain/sync/initial-sync/service.go

Sometimes you start syncing with a bad peer and end up exiting sync early. Waiting for a few more peers may help alleviate this problem.

Wait for 3 peers to start sync

---

beacon-chain/rpc/validator/server.go

Removes an unnecessary declaration of `err` which is implicitly declared in the following line.

Remove erroneous err

---

beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/blockchain/receive_attestation.go

This error happens somewhat often. Removing the formatting makes the log easier to aggregate and monitor.

Remove formatting from error

---

beacon-chain/core/blocks/block_operations.go

This error happens somewhat often. Removing the formatting makes the log easier to aggregate and monitor.

Remove formatting error for signature fail to verify

---

beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/sync/initial-sync/service.go

The next bottle neck after 100blks/s is `SavedHeadBlockRoot`:
As turns out, when we use `--initial-sync-cache-state`, we already use finalized check point as start point to resume sync. Saving head block root on per slot basis during the first phase of initial sync is no longer needed. 
Change list:
* First part of initial sync calls `ReceiveBlockNoVerify` which calls `OnBlockInitialSyncStateTransition`. With `--initial-sync-cache-state`, we skip saving head block root every slot
* This doesn't change second part of initial sync. Second part of the initial sync doesn't not use `ReceiveBlockNoVerify`
After:

--initial-sync-cache-state don't need to save head root

---

tools/faucet/server.go

This alternative domain is sometimes used in addition to prylabs.net.

Allow faucet on prylabs.network

---

beacon-chain/sync/initial-sync/round_robin.go

Resolves #4225 
Resolves #4221 
Somehow peerstatus.Get(k) can return nil, maybe a peer disconnected during the loop.

Skip accessing peer status if it does not exist

---

beacon-chain/core/state/benchmarks/benchmarks_test.go

Updating process epoch benchmark to use `ProcessEpochPrecompute` the optimized version `ProcessEpoch` the optimized version is deprecated

Update process_epoch benchmark

---

beacon-chain/core/state/benchmarks/BUILD.bazel
beacon-chain/core/state/benchmarks/README.md
beacon-chain/core/state/benchmarks/benchmarks_test.go

This adds the commands to run the benchmarks to the README for benchmarks. It also adds a benchmark for HashTreeRootState, so extra work isn't needed to benchmark it.

Add more detail to README and add benchmark for HashTreeRootState

---

beacon-chain/sync/initial-sync/round_robin.go

The "Requesting blocks" log currently dumps the raw request object, which results in the head root being not very useful:
```
time="2019-12-11 12:08:38" level=debug msg="Requesting blocks..." peer=16Uiu2HAkzsDxvZHjNnF2cmAon4gggjU1YLanSNSFP8gWfchzN2e7 prefix=initial-sync req=head_block_root:"\321\211Q\206\r\335\324\252F\317z\261\314\266\276\002\210V~<\371\366j\225\330\031\210'\372\344\270\017" start_slot:214682 count:23 step:1 
```
This patch dumps each element in the request, giving a cleaner head root:
```
time="2019-12-11 12:08:38" level=debug msg="Requesting blocks" count=23 head=0xd18951860dddd4aa46cf7ab1ccb6be0288567e3cf9f66a95d8198827fae4b80f peer=16Uiu2HAkzsDxvZHjNnF2cmAon4gggjU1YLanSNSFP8gWfchzN2e7 prefix=initial-sync start=214682 step=1
```

Tidy up "Requesting blocks" log in initial sync

---

beacon-chain/core/helpers/validators_test.go

Add unit test to ActiveValidatorIndices

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/peer_decay.go
beacon-chain/p2p/peers/status.go
beacon-chain/p2p/peers/status_test.go
beacon-chain/p2p/service.go

At current once a peer hits `maxBadResponses` in peer status it is ignored forever.  For very long-lived nodes this could result in legitimate peers being ignored because of a few transient network issues, or for upgraded peers to continue to be ignored due to past indiscretions.
This adds a decay feature to peer status: every hour the `badResponses` for all peers is reduced by 1.  If the peer is still bad it will quickly be re-marked as bad, but if it is reformed it will be able to rejoin the network and eventually its `badResponses`will decay to 0.

Give peers a chance

---

beacon-chain/db/iface/interface.go
beacon-chain/db/kafka/BUILD.bazel
beacon-chain/db/kafka/passthrough.go
beacon-chain/db/kv/blocks.go
beacon-chain/db/kv/blocks_test.go

Resolves #4257 
---
Currently, our RPC API returns an error if there is more than 1 genesis block saved in the DB when attempting to retrieve blocks with slot == 0. It turns out the filter for genesis does not work, as we retrieve every possible block from the DB instead of returning 1.
Adds a new DB getter that gets around the complexity of fetching genesis using the db.Blocks functions we would otherwise need

Add Getter for Genesis Block

---

beacon-chain/rpc/testing/beacon_node_validator_service_mock.go
beacon-chain/sync/subscriber.go
endtoend/demo_e2e_test.go
endtoend/minimal_e2e_test.go
validator/internal/beacon_chain_service_mock.go
validator/internal/beacon_node_validator_service_mock.go

Skips all end to end tests for the timebeing.

Skip E2E in v0.9.2

---

beacon-chain/blockchain/forkchoice/BUILD.bazel
beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/operations/attestations/kv/unaggregated_test.go

As part of `process_attestation`, we retrieve `target_state` (ie. state by `target_root`), if such state is behind `target_epoch`, we advance the the state up to `target_epoch` via `process_slots`. To avoid running this this for every attestation, a `check_point` to state cache was advocated in the spec. To avoid mutation of the base target state, state gets cloned before the `process_slot`. This caught my eye because clone it took a big chunk of flame graph:
Upon further investigation, I found a bug where the return of `process_slots` is assigned back to the `baseState`:
`baseState, err = state.ProcessSlots(ctx, stateCopy, helpers.StartSlot(c.Epoch))`
Should be:
`stateCopy, err = state.ProcessSlots(ctx, stateCopy, helpers.StartSlot(c.Epoch))`
Fixed the issue and verified the flame graph …

Fix cloning target state for check point state cache

---

beacon-chain/p2p/connmgr/BUILD.bazel
beacon-chain/p2p/connmgr/connmgr.go
beacon-chain/p2p/service.go
beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/service.go

This is a follow-on to #4285 that converts some more ticker code to use the `RunEvery` helper.
It also updates the `sync` and `p2p` services to cancel tickers when stopped.

Use RunEvery in place of custom tickers

---

beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go
beacon-chain/rpc/aggregator/BUILD.bazel
beacon-chain/rpc/aggregator/server.go

I noticed this from the `SubmitAggregatorSignature` RPC method, the code would hydrate a BLS signature object then marshal it back to the original bytes to determine if the signature is an aggregator.

Don't serialize bls signature just to deserialize it again

---

INTEROP.md

This tidies up INTEROP.md:
- remove deprecated `--no-genesis-delay` flag
- substitute `--force-clear-db` for `--clear-db` as instructions do not mention confirmation
- silence `curl` progress output

Tidy up interop commands

---

shared/stateutil/BUILD.bazel
shared/stateutil/state_root_test.go

No tracking issue
---
This PR adds some useful benchmarks for custom SSZ Hash Tree Root in Prysm, giving us an idea about how fast these take for common validator counts such as 512, 16384, and 300000.
```
BenchmarkHashTreeRootState_Custom_512-4               57          21409712 ns/op
BenchmarkHashTreeRootState_Custom_16384-4             30          35877490 ns/op
BenchmarkHashTreeRootState_Custom_300000-4             1        4419664089 ns/op
```

Add Benchmarks for Custom SSZ Hash Tree Root

---

beacon-chain/interop-cold-start/BUILD.bazel
beacon-chain/interop-cold-start/service.go
beacon-chain/powchain/testing/faulty_mock.go
beacon-chain/powchain/testing/mock.go

ChainStartFeed was removed a while back when it was rolled in to state feed but this mock was missed in a few places.  Removing now

Remove ChainStartFeed mocks

---

beacon-chain/core/state/transition.go

With the recent addition of skip slot cache, we `HashTreeRoot` the `state` every time `ProcessSlots` is called. Even under the condition where input `slot` is equal to `state.slot` 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/state/transition.go#L277
It was an unnecessary operation and was discovered while running a 16384 validators node.  The proper fix here is to return the input `state` early if the `slot` is equal
With this, we see a 3x reduction when profiling RPC request attestations

Process slots exit early if same slot

---

beacon-chain/p2p/monitoring.go
beacon-chain/p2p/service.go

The prometheus metric `p2p_peer_count` was returning the count of all nodes known to libp2p, which isn't very useful.
This patch provides the a count broken down by status as provided by `peers`, e.g.
```
p2p_peer_count{state="Connected"} 22
p2p_peer_count{state="Connecting"} 1
p2p_peer_count{state="Disconnected"} 18
p2p_peer_count{state="Disconnecting"} 0
```
It also takes the opportunity to call the periodic update function directly rather than jump through a single-line function.

Add individual p2p host counts

---

beacon-chain/p2p/service.go
beacon-chain/p2p/watch_peers.go

Another function that loops moved to `RunEvery`; missed this one in the last pass as it used sleep rather than a ticker.

Migrate periodic function to use RunEvery

---

beacon-chain/blockchain/forkchoice/metrics.go

This updates the prometheus validator count to use labels and a breakdown by more states.  It also adds balance and effective balance where useful:
```
$ curl -s localhost:8080/metrics | egrep '^validator'
validator_count{state="Active"} 655
validator_count{state="Exited"} 334
validator_count{state="Exiting"} 0
validator_count{state="Pending"} 0
validator_count{state="Slashed"} 0
validator_count{state="Slashing"} 0
validators_total_balance{state="Active"} 3.84983637343e+12
validators_total_balance{state="Exiting"} 0
validators_total_balance{state="Pending"} 0
validators_total_balance{state="Slashing"} 0
validators_total_effective_balance{state="Active"} 2.0944e+12
validators_total_effective_balance{state="Exiting"} 0
validators_total_effective_balance{state="Slashing"} 0
```
Note this …

More complete validator metrics

---

beacon-chain/sync/subscriber.go

We need not process messages that are received from our own peer.

Pubsub ignore messages from yourself

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go

Part of #4272 
Added a check to disallow duplicated indices for indexed attestation since there's no bitfield. Updated test for further verification. 
See rationale for removing: https://github.com/ethereum/eth2.0-specs/issues/1486#issuecomment-564786571

Disallow allow duplicated indices for indexed attestation

---

beacon-chain/blockchain/forkchoice/BUILD.bazel
beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
shared/params/config.go

Part of #4272 
This PR implements `slotsSinceGenesis` as specified in the spec and minor updates a few time check. No breaking logic changes here
See rationale: https://github.com/ethereum/eth2.0-specs/issues/1502

Explicit use of GENESIS_SLOT in fork choice

---

shared/params/config.go

After further investigating on missing participation of certain epoch, It turns out `TargetAggregatorsPerCommittee` set as 2 was not safe enough for 4 validators committee. There's 6% chance of missing an aggregator per committee. This PR updates `TargetAggregatorsPerCommittee` from 2 to 3 to cut down the chance of missing aggregator to 0.3%
| TargetAggregatorsPerCommittee|  len(committee) | Chance one validator gets selected   | Change of no aggregator  |
|---|---|---|---|
|  2 | 4  | 0.5 | 0.062   |
|  3 | 4  |  0.76 | 0.0033  |

Update TargetAggregatorsPerCommittee  from 2 to 3

---

beacon-chain/rpc/aggregator/BUILD.bazel
beacon-chain/rpc/aggregator/server.go
beacon-chain/rpc/validator/BUILD.bazel
beacon-chain/rpc/validator/attester.go
beacon-chain/rpc/validator/attester_test.go

When running 16384 validators on a beacon node. One of the biggest bottleneck is attestation aggregation. With 16384 validators, there's going to be roughly 64 aggregators per slot (16 per committee, 4 committees). Per aggregator, it verifies all the unaggregated attestations, and doing it 64 times is intensive. Although it's unlikely one will run that amount of validators on a single beacon node in production
This PR removed unaggregated attestation verification as part of aggregating loop. To compensate this removal, we added signature verification when attester service receives unaggregated attestation so attestation with bad signature won't get accepted into the pool nor broadcasted 
Before and after:

Remove verify unaggregated attestation when aggregating

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/receive_attestation.go

Attestation processing should happen at the beginning of each slot.

Use slot ticker instead of run every

---

beacon-chain/rpc/aggregator/server.go

If client goes away or a deadline is exceeded, stop work on request.

SubmitAggregateAndProof: Add context check for unbounded loop work

---

beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/epoch/spectest/registry_mainnet_test.go
beacon-chain/core/epoch/spectest/registry_minimal_test.go

#4359 got merged prematurely while still has one failing test
This PR fixed `TestProcessRegistryUpdates_EligibleToActivate` and caught an implementation bug:
```go
sort.Slice(activationQ, func(i, j int) bool {
return i < j
})
```
⬇️ 
```go
sort.Slice(activationQ, func(i, j int) bool {
return activationQ[i] < activationQ[j]
})
```
This PR also skips registry update spec tests. The last changes are breaking for v0.9.2 spec tests and we can't use v0.9.3 spec tests yet until #4272 gets merged

Fixed failing test from 4359

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/chain_info_test.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go

This fixes check point root to use genesis block root when there's a head state but no justified and finalized check points. In general there's 3 conditions and this PR fixes case 2:
1.) State hasn't initialized, there's no head state. `ChainService.Checkpoint.Root` should be `ZeroHash`
2.) There's head state but justification hasn't happened. `ChainService.Checkpoint.Root` should be `GenesisRoot`
3.) There's head state with justification happened once. `ChainService.Checkpoint.Root` should be `HeadState.Checkpoint.Root`

Checkpoint root to use genesis block root

---

beacon-chain/blockchain/service_test.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/state/state.go
beacon-chain/core/state/state_test.go
beacon-chain/rpc/validator/assignments_test.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
beacon-chain/sync/rpc_status_test.go
shared/interop/generate_genesis_state.go
shared/interop/generate_genesis_state_test.go
shared/testutil/deposits.go

Part of #4370.
This is a prevention fix to make it impossible to continue with the improper number of genesis deposits. The bug still exists as outlined in #4370 and that will be resolved in a follow up PR.

Return an error if the wrong number of deposits are provided for genesis state

---

beacon-chain/powchain/log_processing.go
beacon-chain/powchain/log_processing_test.go
beacon-chain/powchain/service.go

Resolves #4370.
This was a bug where the chain had not started, but the min genesis deposit threshold had been met while new deposit were sent to the contract.

Only add chain start deposits up to min genesis active validator count

---

beacon-chain/core/blocks/block_operations.go
beacon-chain/core/blocks/block_operations_test.go

[is_valid_indexed_attestation](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#is_valid_indexed_attestation) should verify if a list of attesting indices are unique and sorted. We only verify that it's sorted. This PR added in the verification of unique

VerifyIndexedAttestation to verify unique

---

beacon-chain/powchain/log_processing.go
beacon-chain/powchain/testing/faulty_mock.go
beacon-chain/powchain/testing/mock.go

Remove Redundant Trie Generation

---

shared/stateutil/arrays.go

The readLock was never blocking, so that could have been a potential issue.

Use a single lock for arrays cache

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/service.go
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/state/benchmarks/benchmarks_test.go
validator/client/validator_test.go

This covers an edge case when process attestations during epoch transition, the attestations can come from previous epoch. But committee cache update uses current epoch in state and + 1. Such behavior will always trigger a cache miss and excessive cache update when process previous epoch attestations. Hence the following flame

Update committee cache prev epoch

---

validator/client/service.go
validator/client/validator.go
validator/client/validator_aggregate.go
validator/client/validator_aggregate_test.go
validator/client/validator_attest.go
validator/client/validator_attest_test.go
validator/client/validator_propose.go
validator/client/validator_propose_test.go
validator/client/validator_test.go

In worst case, a validator requests its index 4 times on per slot basis. From getting assignment to proposing block, to submit unaggregation attestation and finally submit aggregation request.
This PR improves upon that by saving validator index and conveniently updates them during `UpdateAssignments`. This cuts the worst case to 1 time.
Tested run time 👍

Validator caches index

---

beacon-chain/blockchain/forkchoice/BUILD.bazel
beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/forkchoice/service.go
validator/client/validator_test.go

With the new attestation pool in v0.9.2. Processing block attestations for fork choice in no lounger needed as a separate routine during process block. This routine was taken care of by the attestation pool to aggregate all the similar data attestations together for fork choice in subsequent slot. See new: https://github.com/prysmaticlabs/prysm/blob/e43fa0168db4b9e6891b933c499967a45aa87e76/beacon-chain/blockchain/receive_block.go#L110
This PR removes the old design to process block attestations as a separate routine, we were double processing block attestations for fork choice in v0.9.2 this whole time!

Remove process block attestations as separate routine

---

beacon-chain/core/state/benchmarks/benchmarks_test.go
shared/bls/bls.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

This feature has been running in prod since the beginning of the current testnet. 
It saves significant time on deserializing BLS pubkeys from bytes. 
Since the set of pubkeys rarely changes (except on new deposits / activations), this cache has a very high hit ratio.

Release --enable-bls-pubkey-cache

---

beacon-chain/blockchain/forkchoice/service.go

This was showing a deep call stack far after the deadline had been exceeded for a block processing.

Stop recursive ancestor lookup if context is cancelled

---

beacon-chain/rpc/validator/proposer.go
beacon-chain/rpc/validator/proposer_test.go

When receiving a block proposal, the beacon node was assuming this was built off of the "head state" as indicated by the beacon DB. 
However, this may not always be the case and is not the correct way to compute the state root of a block in RPC.
Edit: the error was 
```
rpc error: code = Internal desc = Could not compute state root: could not calculate state root at slot 6656: could not process block: could not process block header: parent root 0x06afbf5025c87236b3773fd12621c6cda392081e226947e60826f00b09c7428a does not match the latest block header signing root in state 0xf8b1ccfec3a0d3098b5f35e303bfdc41575b3269a65c203c63b4198a1717d5b1
```

Fix proposal bug

---

beacon-chain/db/kv/checkpoint.go
beacon-chain/db/kv/checkpoint_test.go

To prevent a scenario where we are missing the justified state in the database.

Require a state to exist to save justified checkpoint

---

beacon-chain/blockchain/forkchoice/process_block.go

At v0.9.3, bunch of fixes for fork choice went in to treat justification updates. In block processing, there's 2 code paths for processing block. One for normal and one for initial sync case. The normal code path has the v0.9.3 fork choice justification fixes. See:
https://github.com/prysmaticlabs/prysm/blob/v0.9.2/beacon-chain/blockchain/forkchoice/process_block.go#L98
But the initial sync does not have it, and it still updates justified check point using the old method. This PR fixes initial sync update justification to align with normal block processing code

Update initial sync save justification to align with v0.9.3

---

endtoend/beacon_node.go
endtoend/endtoend_test.go
endtoend/validator.go

Resolves #4378
This increases the totalWait for reading the logs from 24 seconds to 36, to make sure the ETH1 chain has time to start.
Also adds several checks if `t.Failed()` to make sure the tests stop running after a failure.

E2E cleanup and fix ETH1 chain startup

---

validator/client/validator.go

Instead of failing the assignment for every validators in the same request, this changes the behavior to log warn and continue if a single validator's public key not in beacon node's db

Log warn and cont if validator pub key not exist in DB

---

beacon-chain/p2p/handshake.go

This seems unnecessary and a permanent blacklist while disconnects are temporary with decay.

Don't blacklist on pubsub when disconnecting

---

beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/beacon/BUILD.bazel
beacon-chain/rpc/beacon/attestations.go
beacon-chain/rpc/beacon/attestations_test.go
beacon-chain/rpc/beacon/server.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go
beacon-chain/rpc/validator/assignments.go
beacon-chain/rpc/validator/exit.go
beacon-chain/rpc/validator/exit_test.go
beacon-chain/rpc/validator/server.go
shared/slotutil/slotticker.go
shared/slotutil/slotticker_test.go
shared/slotutil/testing/BUILD.bazel
shared/slotutil/testing/mock.go
shared/slotutil/testing/mock_test.go

No tracking issue
---
An RPC test that uses time and our slot ticker from `shared/slotutil` was flakey due to poor abstraction. Instead, we create a `Ticker` interface that defines a method `C() <-chan uint64` and are able to use a mock when testing behavior to remove flakeyness.

Fix Flakey Slot Ticker Test

---

beacon-chain/powchain/log_processing.go
shared/featureconfig/config.go
shared/featureconfig/config_test.go
shared/featureconfig/flags.go
shared/params/config.go

Changes based on https://github.com/ethereum/eth2.0-specs/pull/1557
Additionally, we will remove the no-genesis-delay flag. If we want no delay, we'll configure this via config.

Configurable min genesis delay

---

tools/cluster-pk-manager/client/BUILD.bazel
tools/cluster-pk-manager/client/main.go

This saves a lot of time on start up for testnet validators.

Cluster: Save keys unencrypted for validators

---

endtoend/README.md
endtoend/beacon_node.go
endtoend/demo_e2e_test.go
endtoend/endtoend_test.go
endtoend/eth1.go
endtoend/validator.go

Resolves #4060 
This PR only logs out the error logs on erroring for all beacon nodes and validators, debugging a failure no longer needs accessing the files.
Also adds a README to the endtoend/ folder.

Vastly improve E2E logs and add README

---

tools/cluster-pk-manager/server/db.go

Allocating new keys should be an append, not replace with a single key.

Fix pk manager db

---

beacon-chain/archiver/service_test.go
beacon-chain/blockchain/log.go
beacon-chain/blockchain/receive_block.go
beacon-chain/db/kv/attestations.go
beacon-chain/rpc/validator/proposer_test.go
beacon-chain/rpc/validator/status.go
shared/keystore/deposit_input_test.go
shared/keystore/key.go
shared/keystore/key_test.go
shared/keystore/keystore.go
shared/keystore/keystore_test.go
shared/params/config.go
tools/cluster-pk-manager/server/server.go
tools/deployContract/deployContract.go
tools/sendDepositTx/sendDeposits.go
validator/accounts/account.go
validator/accounts/account_test.go
validator/client/service_test.go

This PR removes unused parameters from a few functions like `keystore.NewKey` and entirely removes `DepositContractConfig` since it is no longer used.

Remove unused parameters and unused code

---

beacon-chain/cache/BUILD.bazel
beacon-chain/cache/committee_fuzz_test.go
beacon-chain/rpc/validator/status.go

Added fuzz tests for committee cache. The test contains fuzz tests for converting cache key, saving/retrieving committees and active indices

Committee cache fuzz tests

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/rpc/beacon/committees.go

`ListBeaconCommittees` uses method `ComputeCommittee` which bypasses the committee cache. Instead it should use method `BeaconCommittee` (where the cache is) and `BeaconCommittee` calls `ComputeCommittee` underneath.
It also cleans up code path where we don't need to recalculate `epochOffset` and `totalCount`, it's already taken care of by `BeaconCommittee`

Optimize ListBeaconCommittees to use committees cache

---

beacon-chain/blockchain/forkchoice/metrics.go

The description for the gauge `validator_count` incorrectly stated that the unit was GWei.

Fix gauge description

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/db/iface/interface.go
beacon-chain/db/kafka/passthrough.go
beacon-chain/db/kv/validators.go
beacon-chain/db/kv/validators_test.go
beacon-chain/interop-cold-start/BUILD.bazel
beacon-chain/interop-cold-start/service.go
beacon-chain/rpc/aggregator/BUILD.bazel
beacon-chain/rpc/aggregator/server.go
beacon-chain/rpc/aggregator/server_test.go
beacon-chain/rpc/beacon/assignments.go
beacon-chain/rpc/beacon/assignments_test.go
beacon-chain/rpc/beacon/committees_test.go
beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go
beacon-chain/rpc/validator/BUILD.bazel
beacon-chain/rpc/validator/assignments.go
beacon-chain/rpc/validator/assignments_test.go
beacon-chain/rpc/validator/server.go
beacon-chain/rpc/validator/server_test.go
beacon-chain/rpc/validator/status.go
beacon-chain/rpc/validator/status_test.go

This patch change the signature of the validator-related methods in `beacon-chain/db/iface/interface.go` from taking arrays to taking slices as their argument for the public key.
There are a few reasons for doing this.  First, every instance of the code that called these functions outside of tests held slices, so wrapped all of the keys in `bytesutil.ToBytes48()` to pass the argument which were then all accessed with `[:]` as the downstream functions also use slices.  So this change reduces unnecessary allocations.
Second, wrapping the keys hid potential issues with keys of incorrect lengths, as `ToBytes48()` will always provide a 48-byte array regardless of the length of the slice.  Storing and retrieving keys will now error if they are of an incorrect size.
Third, arrays are hard-coded …

Change database *Index() to use slice

---

beacon-chain/rpc/validator/proposer.go

To ensure we actually have the head block in the DB.

RPC: Use db.headBlock in getBlock

---

beacon-chain/rpc/validator/attester.go
beacon-chain/rpc/validator/attester_test.go

To ensure the correct head info is getting passed to construct attestation

Use db head info for request attestation

---

beacon-chain/sync/validate_aggregate_proof.go

As title describes, only advance the state when there would be an epoch transition. This is because the committee can only change if there is an epoch transition so there is no need to advance empty slots in the same epoch.

Pubsub: Only advance state for validating attestation and proof if different epoch

---

beacon-chain/operations/attestations/aggregate.go
beacon-chain/operations/attestations/aggregate_test.go

We saw quite a few overlapping attestations in the block (example below). The is due to a node does not reuse the already aggregated attestations to aggregate unaggregated attestation. Therefore overlapping attestations could exist in the aggregated pool. To fix this, at the aggregation interval, we aggregate the unaggregated attestations with the aggregated ones in pool
```
Slot / CommitteeIndex/ Aggregation Bitfield
1527 1 [11111111 01110101 11111111 00101011 11111011 11111111 11111111 01111101 11101001 10011111 11111111 11101111 11111101 11111011 11011111 01111110 00000010]
1527 1 [11111111 01110101 11111111 00101011 11111011 11111111 11111111 01111101 11111001 10111111 11111111 11101111 11111101 11111011 11111111 01111110 00000010]
1550 1 [11000011 00000010 01101000 00000011 01101001 …
```

Aggregate unaggregated with prev aggregated attestations

---

beacon-chain/p2p/peers/BUILD.bazel
beacon-chain/p2p/peers/status.go
beacon-chain/p2p/peers/status_test.go
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/rpc_status.go

This (hasty) patch stops a panic if a node is interrupted during initial sync and as such doesn't complete sync.  Sync will end without being marked as complete and will continue next run.

Do not panic if initial sync fails

---

beacon-chain/blockchain/forkchoice/service.go

Here's the edge case I caught at run time. In the case of `process_block` takes longer than `attestation delay` + `process_attestation`. The processed attestation will trigger fork choice but `process_block` is not done. Therefore it'll complain there's no state associated with latest block root. In such case we should return false as the block is ineligible to be accounted for fork choice
The error:
`[2020-01-10 22:44:26] ERROR blockchain: Could not receive attestation in chain service error=no state matching block root e49f52bddde16bb23aad425b47b5e16dea4e00b5007f360983a81ff91b428bb3
`

Filter block tree verifies block root has state

---

beacon-chain/blockchain/forkchoice/service.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/receive_attestation_test.go

This fixes #4484 
Although patrikman's go-cache prunes itself every epoch, it's not guaranteed the cache gets pruned at the start the epoch. Because of that, we see a few target epoch missmatch error. This PR added a filter to ensure target epoch is within range before passing it to vote counter

Add epoch filter for fork choice attestation

---

beacon-chain/blockchain/service.go

Instead of writing to the db for each index, we save all the indexes in a single transaction.

Batch Save Genesis Validators

---

beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/rpc_status.go

This tidies up #4477 to use a helper to calculate epoch from slot rather than carry out the task manually.

Use helper to calculate epoch

---

beacon-chain/rpc/validator/attester.go

Accessing the state is only used for the target root which is the root of the epoch start slot of the requested slot. Given this constraint, we only need to advance skip slots if the head state is not in the same epoch as the requested slot.

RPC: Only advance slot when the request is for a future epoch

---

beacon-chain/powchain/log_processing.go

Provide occasional (every 512 deposits) log entries at info level to keep users informed that prysm is still alive and working when users start it up for the first time.
Fixes #4492 and #4498

Log Ethereum 1 deposits before chainstart

---

beacon-chain/operations/attestations/aggregate.go
beacon-chain/operations/attestations/aggregate_test.go
beacon-chain/operations/attestations/kv/aggregated.go
beacon-chain/operations/attestations/kv/aggregated_test.go
beacon-chain/operations/attestations/kv/block.go
beacon-chain/operations/attestations/kv/block_test.go
beacon-chain/rpc/validator/proposer_test.go

The current attestation pool needs structure changes to better support:
1.) filter out seen attestations from the wire 
2.) attestations to block inclusions 
Change list:
- Updated aggregated attestation pool to `map[HTR(att.Data)]*[]ethpb.Attestation` from `map[HTR(att)]*ethpb.Attestation`
- Updated `HasAggregatedAttestation` to consider bitfield containment 
- Better tests

Fix up attestation pool

---

beacon-chain/sync/rpc_status.go

Iterating over all of the peer statuses is not useful when you are already synced to the current epoch. This change aims to save some CPU time when this method is run. 
cc: @mcdee

p2p: Check if we are already synced to the current epoch before querying peerstore

---

beacon-chain/blockchain/receive_block.go

As title describes, we were doing a DB block fetch on every block that came in when it was rarely necessary.

ReceiveBlock: Only retrieve head block from DB if necessary

---

beacon-chain/blockchain/receive_block.go

Reverts prysmaticlabs/prysm#4506
The fix didn't seem to consider all scenarios. We see `Calculated head diffs from new block` gets logged every slot. Can we revert this for now and come up with a better solution? See screen shot

Revert "ReceiveBlock: Only retrieve head block from DB if necessary"

---

beacon-chain/rpc/validator/proposer.go
beacon-chain/rpc/validator/proposer_test.go

This alleviates #4507
Uses `ProcessAttestationNoVerify` instead of `ProcessAttestation`, the only difference is missing signature verification.  And we will switch back to `ProcessAttestation` after #4512 is implemented.
`ProcessAttestationNoVerify` verifies everything except for attestation signature which is sufficient enough for current testnet

Filter attestation with ProcessAttestationNoSignatureVerify

---

beacon-chain/blockchain/forkchoice/lmd_ghost_yaml_test.go
beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/service_test.go
beacon-chain/blockchain/service.go
beacon-chain/cache/committee.go
beacon-chain/cache/feature_flag_test.go
beacon-chain/core/blocks/block_operations_test.go
beacon-chain/core/blocks/spectest/block_processing_test.go
beacon-chain/core/epoch/epoch_processing_test.go
beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/core/state/benchmarks/BUILD.bazel
beacon-chain/core/state/benchmarks/benchmarks_test.go
beacon-chain/rpc/beacon/assignments_test.go
beacon-chain/rpc/beacon/validators_test.go
shared/featureconfig/config.go
shared/featureconfig/flags.go
shared/testutil/spectest.go

Redo for #4502.
This PR is the same changes from #4502 but also deprecates the shuffled index cache which is no longer used. 
#4502 was reverted quickly due to seemingly irrelevant changes. The --enable-shuffled-index-cache is safe to deprecate as well.

PR #4502 take two

---

beacon-chain/blockchain/receive_block.go

Reattempt for #4506
This fixes logging, we still need `!bytes.Equal(root[:], headRoot)` condition

#4506 take two

---

beacon-chain/p2p/handshake.go

Handshaking has protection against attempts from already-connected peers that attempt to handshake again.  This extends the protection to peers that attempt to connect again whilst going through the connection process (_i.e_. a second attempt to connect before the first attempt has completed).

Only one handshake at a time with active peers

---

.gitignore

A previous commit of mine included a vim swapfile by accident.  This patch adds swapfiles to the list of ignored files for git so it won't happen again.

Ignore VI swapfiles

---

beacon-chain/sync/pending_blocks_queue.go

Resolves #4481 , #4510
This checks whether the requested block exists, before processing it from the pending block queue

Check Block Before Processing it

---

validator/client/service.go
validator/flags/flags.go
validator/main.go
validator/node/node.go
validator/usage.go

I have added a flag `grpc-max-msg-size` for setting GRPC msg size through the command line.
[Resolves] #4444

cli: Added flag for GRPC max msg size

---

beacon-chain/rpc/validator/proposer.go
beacon-chain/rpc/validator/proposer_test.go

Reverts prysmaticlabs/prysm#4513
Discussed offline that this could generate blocks that immediately fail. Given that we only mark attestations as "deleted" from the pool on a successful block inclusion, we could end up with a stalled chain until that attestation is no longer valid. We're also not observing much improvement in GetBlock latency times with this change and we believe the bottleneck is in redundant computation of ProposerIndex.

Revert "Filter attestation with ProcessAttestationNoSignatureVerify"

---

beacon-chain/sync/validate_aggregate_proof.go

The state must be on the same epoch as the attestation, but does not have to advance all the way to the same slot. If we are behind by less than one epoch then this could be a non-trivial improvement.

pubsub: Only advance to the correct epoch

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/service.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/service_test.go
beacon-chain/rpc/beacon/validators.go

One of the bottleneck during round robin sync for `ReceiveBlockNoPubsubForkchoice` is updating filtered tree cache every slot. This is not needed as suggested by the method name, we do not care about fork choice nor compute for head during `ReceiveBlockNoPubsubForkchoice`
To fix this, we implemented `OnBlockCacheFilteredTree` which inherits `OnBlock` plus updating the filtered block tree cache. And make `OnBlockCacheFilteredTree` called from  `ReceiveBlockNoPubsub`. Much better looking flame:

`ReceiveBlockNoPubsubForkchoice` should not update block tree cache

---

beacon-chain/sync/subscriber.go

To ensure the message received metrics are accurate, we increment whenever we receive any message from gossipsub.

Increment Metric at the Start of Validation

---

beacon-chain/sync/initial-sync/service.go

Panicking may not the best response to an error, but we were silently throwing the error away and doing nothing about it.
Until we have a better approach, let's partially revert #4477 and panic if sync fails.

Partially revert #4477

---

shared/featureconfig/config.go
shared/featureconfig/config_test.go
shared/featureconfig/flags.go

This PR makes the naming of flags more consistent, and unexports all the flag objects since it's not needed at all. 👍

Cleanup featureconfig, make naming consistent

---

WORKSPACE
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/error.go
beacon-chain/sync/rpc_beacon_blocks_by_range.go
beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
beacon-chain/sync/service.go

Key changes:
- Add a leaky bucket type rate limiter of 32 blocks per second with a burst of 160
- Respond to peer with rate limit error
- If peer continues to exceed rate limit, we eventually disconnect them

Rate limiter for rpc beacon blocks

---

README.md

`init-sync-no-verify` was removed from `beacon-chain` in 32245a906246b8f152368120d932de032e98ac05
[Resolves] #4561

Remove invalid init-sync-no-verify option

---

beacon-chain/flags/base.go
beacon-chain/main.go
beacon-chain/node/node.go
beacon-chain/rpc/service.go
beacon-chain/usage.go

The beacon chain currently binds its RPC server to all network interfaces.  This is undesirable in implementations where the RPC server should be protected (pretty much any production instance where other servers are on the same network).
This patch adds a `--rpc-host` option that can specify a particular host interface to which to bind.  It can be an IP address (_e.g._ `127.0.0.1`) or a resolvable name (_e.g._ `localhost`).  The default value is `0.0.0.0`, which mirrors the current functionality.

Add --rpc-host option to beacon chain

---

beacon-chain/p2p/handshake.go

It's already handled here:
https://github.com/prysmaticlabs/prysm/blob/d744aaa2cd56519016e6a6058859887b359e20b5/beacon-chain/sync/rpc_status.go#L108
The current implementation might cause the peer to be marked as bad twice and banned quickly.

p2p: Don't mark peer as bad in connection handler

---

beacon-chain/sync/initial-sync/service.go

If round robin were to fail for any reason, we would be stuck in a state where the node reports that it is syncing but no active operation were happening. This may cause nodes to appear stalled.

Fix resync

---

beacon-chain/sync/rpc_status.go

The periodic checker for resync doesn't confirm that the initial sync service is running before checking a value in it.  This patch fixes this.
(Seen a couple of test failures because of this; tests now run okay).

Ensure initial sync is initialised

---

README.md

Port 13000 also needs to be exposed if to improve connectivity and receive more peers, refs #4323.
Also updates the "Docker on Windows" instructions for consistency.

Updates README.md expose docker port 13000

---

beacon-chain/powchain/log_processing.go

This uses a proper bound for eth1 requests.

Use Proper Bound for Eth1 Requests

---

beacon-chain/operations/voluntaryexits/BUILD.bazel
beacon-chain/operations/voluntaryexits/doc.go
beacon-chain/operations/voluntaryexits/service.go
beacon-chain/operations/voluntaryexits/service_test.go

Part one of many for #2766.
This PR defines the voluntary exits pool, but does not wire it up to any services. That will come in the next PR.

Implement voluntary exits pool

---

validator/client/validator_attest.go

Provide more information when a validator fails to submit an attestation, specifically add the public key and slot for all errors.
Also tidy up logging such that errors are included in their own field rather than as part of the message.

Tidy up error logging

---

beacon-chain/main.go
beacon-chain/node/node.go
beacon-chain/p2p/config.go
beacon-chain/p2p/options.go
beacon-chain/usage.go
shared/cmd/flags.go

Adds in a flag so that the beacon node can listen at another local ip address for incoming data. This requires that the beacon node be able to bind to the provided ip address.

Add Flag for Additional Listening Addresses

---

.bazelrc
.buildkite-bazelrc

Building libkafka from source takes a really long time and even fails on some operating systems.
As suggested by @nisdas a few weeks ago, let's make it the default to not build kafka locally, but enable it by default in the CI.

Disable kafka build by default

---

beacon-chain/sync/initial-sync/BUILD.bazel
beacon-chain/sync/initial-sync/round_robin.go
beacon-chain/sync/initial-sync/round_robin_test.go
beacon-chain/sync/initial-sync/service.go

Resolves #4588
Resolves #4621 
Maybe helps #4631 
Part of the issue is that when there are large ranges of skip slots, we might be asking for the peer for many blocks very quickly. Even when there are no blocks present in that range, the server increments that rate limit by the request count. Adding this client side rate limit should reduce the risk of bombing peers with requests.

Use a client side rate limit to reduce chance of getting banned

---

beacon-chain/forkchoice/protoarray/nodes.go
beacon-chain/forkchoice/protoarray/nodes_test.go

This PR implements the `head` function. Simple enough it returns the head root with O(1) look up. By passing in justified index, it looks up the justified node, and returns justified node's best descendant which is the head. Also added tests to go with this

Part 9 of proto array fork choice - get head

---

beacon-chain/rpc/beacon/committees.go
beacon-chain/rpc/beacon/committees_test.go

This PR changes the `ListBeaconCommitees` endpoint to allow requesting the previous epoch of beacon committees without requiring  an archival node as the data should be possible to calculate anyways.
Also add a regression test to make sure requested previous epoch works.

Allow ListBeaconCommittees API to return previous epoch

---

INTEROP.md
README.md

Update README.md and INTEROP.md with new keymanager options to avoid deprecation warnings on startup.

Update docs for keymanager

---

shared/stateutil/validators.go

We were supposed to be writing into the encoding with the withdrawal buffer instead of the exit buffer when performing Hash Tree Root of a validator.

Fix HashTreeRoot Bug

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/info.go
beacon-chain/blockchain/log.go
beacon-chain/blockchain/metrics.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_helpers.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/receive_block_test.go
beacon-chain/blockchain/service.go
endtoend/demo_e2e_test.go
endtoend/minimal_e2e_test.go

In current structure, fork choice is tightly coupled with block chain service, `beacon-chain/blockchain/forkchoice` inside `beacon-chain/blockchain`.  There's important block processing logic in `beacon-chain/blockchain/forkchoice` which needs to be stripped out without fork choice and moved one folder up to `beacon-chain/blockchain`
Change list:
- Copied `process_block.go` from `beacon-chain/blockchain/forkchoice` to `beacon-chain/blockchain`
- Moved helper functions from `process_block.go` to `process_block_helper.go`
- Copied `process_block_test.go` from `beacon-chain/blockchain/forkchoice` to `beacon-chain/blockchain`
- Copied logging and metric functions from `beacon-chain/blockchain/forkchoice` to `beacon-chain/blockchain`
- Above changes are gated by feature flag …

Part 1 of block chain service refactor - move process block

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/process_attestation.go
beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_attestation_test.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/service.go

In current structure, fork choice is tightly coupled with block chain service, `beacon-chain/blockchain/forkchoice` inside `beacon-chain/blockchain`.  There's important attestation processing logic in `beacon-chain/blockchain/forkchoice` which needs to be stripped out without fork choice and moved one folder up to `beacon-chain/blockchain`
Change list:
- Copied `process_attestation.go` from `beacon-chain/blockchain/forkchoice` to `beacon-chain/blockchain`
- Moved helper functions from `process_attestation.go` to `process_attestation_helper.go`
- Copied `process_attestation_test.go` from `beacon-chain/blockchain/forkchoice` to `beacon-chain/blockchain`
- Above changes are gated by feature flag `--proto-array-forkchoice`, it won't affect regular run time

Part 2 of block chain service refactor - move process attestation

---

beacon-chain/powchain/service.go

Resolves #4055
---
We have a `Status()` function that is used in liveness probes in our beacon node for every service. The powchain service upon losing a websocket connection to eth1 returns an error perpetually in this `Status()` function even after it reconnects.
This PR clears the `service.runErr` value back to `nil` after a successful powchain reconnect.

Clear Run Error in Powchain Service Upon Reconnect

---

beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/precompute/new.go
beacon-chain/core/epoch/precompute/slashing.go
beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/committee.go
beacon-chain/core/helpers/rewards_penalties.go
beacon-chain/core/helpers/shuffle.go
beacon-chain/core/helpers/validators.go
beacon-chain/rpc/validator/exit.go
beacon-chain/state/BUILD.bazel
beacon-chain/state/getters.go
beacon-chain/state/setters.go
beacon-chain/state/types.go
beacon-chain/state/types_test.go
beacon-chain/sync/subscriber_handlers.go
shared/hashutil/hash.go
shared/stateutil/arrays.go
shared/stateutil/helpers.go
shared/stateutil/validators.go

Runtime Optimizations

---

beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_helpers.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/blockchain/service.go
beacon-chain/powchain/service.go
beacon-chain/sync/initial-sync/round_robin.go
shared/featureconfig/flags.go

Resolves #4583 
Previous when we switch from initial sync step 1 to step 2, step 2 would fail because there's no real state in DB. (ie the state was still cached). This fixes it by checking both the 1.) cached state and the 2.) DB state for step 1 -> step 2 transition

Fix initial sync cache state

---

README.md
beacon-chain/powchain/BUILD.bazel
beacon-chain/powchain/log_processing.go
beacon-chain/powchain/log_processing_test.go
endtoend/beacon_node.go
endtoend/demo_e2e_test.go
endtoend/evaluators/BUILD.bazel
endtoend/minimal_e2e_test.go
shared/featureconfig/BUILD.bazel
shared/featureconfig/config.go
shared/featureconfig/flags.go
validator/db/attestation_history_test.go
validator/db/proposal_history_test.go

This PR changes `--no-genesis-delay` to `--custom-genesis-delay` in order to allow a 0 genesis delay but also allow configuring it for E2E and other instances where it might be needed.

Replace no-genesis-delay with custom-genesis-delay

---

shared/featureconfig/config.go

This PR fixes a bug regarding the `custom-genesis-delay` flag to ensure it is always set in the config.

Fix genesis delay flag bug

---

beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/blockchain/forkchoice/process_block.go
beacon-chain/blockchain/forkchoice/process_block_test.go
beacon-chain/blockchain/forkchoice/service_test.go
beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_block_helpers.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/cache/skip_slot_cache.go
beacon-chain/cache/skip_slot_cache_test.go
beacon-chain/core/blocks/spectest/block_header_test.go
beacon-chain/core/blocks/spectest/block_processing_test.go
beacon-chain/core/helpers/committee_test.go
beacon-chain/core/state/benchmarks_test.go
beacon-chain/core/state/skip_slot_cache_test.go
beacon-chain/core/state/spectest/slot_processing_test.go
beacon-chain/core/state/state_test.go
beacon-chain/core/state/stateutils/validator_index_map.go
beacon-chain/core/state/transition.go
beacon-chain/state/getters.go
beacon-chain/state/types.go
beacon-chain/state/types_test.go
shared/interop/generate_genesis_state.go
shared/testutil/block.go
shared/testutil/spectest.go

Some minor improvements in memory usage, reuse of HTR cache layers.
Builds on https://github.com/prysmaticlabs/prysm/pull/4646 for easier review.

New beacon state: Only populate merkle layers as needed, copy merkle layers on copy/clone.

---

beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/process_attestation_test.go
beacon-chain/blockchain/process_attestation.go
beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_attestation_test.go
beacon-chain/cache/checkpoint_state.go
endtoend/helpers.go

This PR fixed up `OnAttestation` to better use the check point cache. As we previously implement from the spec, which required duplicated DB and cache read, it was bad as we saw it occupied most of the flames. The better algorithms are specified below:
**Before**
1. Always attestation pre state from DB and perform a few checks with it
2. Then check if the attestation pre state is in cache, if yes, clone the attestation and use it instead of the one in DB
3. Check if the attestation pre state is processed to latest epoch slot
4. if 2 or 3 are *no*, we use the state from step 1, and process state to the latest epoch slot
5. Save the processed state to cache
**After (optimized)**
1. Get the attestation pre state from cache
2. If it's not in cache, we get the attestation pre state from DB, …

Better caching of attestation pre state

---

WORKSPACE
beacon-chain/rpc/beacon/BUILD.bazel
beacon-chain/rpc/beacon/config.go
beacon-chain/rpc/validator/server.go
beacon-chain/rpc/validator/status.go
beacon-chain/rpc/validator/status_test.go
shared/mock/beacon_chain_service_mock.go
third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
validator/client/validator.go

Fixes up validator states to match those in ethereumapis after https://github.com/prysmaticlabs/ethereumapis/pull/95

Validator status updates

---

beacon-chain/cache/skip_slot_cache.go
beacon-chain/core/blocks/block_operations.go
beacon-chain/sync/initial-sync/round_robin.go

- Disable skip slot cache in round robin.
- Return copy the cached state to ensure it is not mutated.

Better skip slot cache

---

endtoend/beacon_node.go
endtoend/endtoend_test.go
endtoend/helpers.go
endtoend/validator.go

This PR fixes a bug with file watching, and changes the logs to use `--log-file` instead of using `stdout` which is unreliable at times. Files are also deleted and cleared on start up to ensure logs don't conflict.
Also overall provides more buffer time to hopefully make timeouts less common.

Make E2E more consistent, change log file setup

---

beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go

---
Validators that already exited were still being shown in the exit queue.
This PR fixes the problem and adds a required regression test.

Remove Already Exited Validators From Queue

---

beacon-chain/blockchain/service.go

Resolves #4706. 
This isn't a full fix because DeleteStates transaction is rolled back when the transaction fails, but it resolves #4706 which was blocking users starting.

Pruning old states: Use a warning level log instead of fatal

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go

A few minor changes:
- Compute HTR before securing the lock
- Use Locker (instead of RLocker) for validatePendingSlots since it mutates the maps
- A few span.End()
The main idea here is we should reduce the time we hold the Lock to the minimum amount of time.

Pending blocks queue: Better locking priority

---

shared/hashutil/hash.go
shared/hashutil/hash_test.go

Before
```
BenchmarkHash-8                  1246952              1097 ns/op             179 B/op          4 allocs/op
BenchmarkHashKeccak256-8          344100              3352 ns/op             515 B/op          4 allocs/op
```
After
```
BenchmarkHash-8                  1967601               513 ns/op              35 B/op          2 allocs/op
BenchmarkHashKeccak256-8          807060              2536 ns/op             515 B/op          4 allocs/op
```
Non-trivial improvement, yay!

Use sync.pool for keccak256 and sha256

---

beacon-chain/core/blocks/block_operations.go

proto.Equal sucks!
Before
```
BenchmarkAreEth1DataEqual-8       227058              4937 ns/op             408 B/op         21 allocs/o
```
After
```
BenchmarkAreEth1DataEqual-8     22890710                46.4 ns/op             0 B/op          0 allocs/op
```

Better eth1data equals

---

beacon-chain/state/getters.go
beacon-chain/state/setters.go
beacon-chain/state/types.go

Copy has practically fallen off the flame graph with this PR!

BeaconState: Use copy on write for validator index map

---

beacon-chain/sync/pending_blocks_queue.go

Since we didn't propagate a block that failed to process when we were missing the parent block, broadcast each block after it has been processed to ensure it reaches the full network.

Propagate blocks again after we process it in pending blocks queue

---

beacon-chain/blockchain/forkchoice/process_attestation.go
beacon-chain/blockchain/forkchoice/service.go
beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/cache/checkpoint_state.go
beacon-chain/cache/checkpoint_state_test.go

- Ensure state is copied for cache
- Ensure pre state exists for attestation before processing in fork choice

Minor fixes

---

beacon-chain/blockchain/receive_block.go

When fork choice is disabled, use a naive "if this block has a higher slot than my previous head" method rather than "whatever comes in next is the new head".
This fix recovered the testnet issues today.

Fork choice: only update head if the new block is a higher block slot

---

beacon-chain/p2p/handshake.go

p2p is quite chatty when it has connection requests from peers it does not want to talk to.  This patch changes a number of log entries from debug to trace, to reduce this.
(Note that when libp2p takes application-layer hints as to which connections to proceed with these could be returned to debug, as at that point they will point out real issues with the handshake process).

Relegate some p2p messages

---

shared/bls/bls.go

Heap was showing about 15mb of usage after an hour or so at this size. This significantly reduced CPU usage in BLS.

Increase BLS pubkey cache to 100k from 10k

---

beacon-chain/sync/pending_blocks_queue.go

Add Lock to Pending Queue
