prysmaticlabs/prysm

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/receive_attestation.go
We still need to save the state (not expensive) because we need to process attestations right after initial sync ends. We also does state pruning during initial sync so it's not a big deal.
This solves the following error:
=> Fix `pre state of target block does not exist` error

beacon-chain/blockchain/metrics.go, beacon-chain/blockchain/receive_attestation.go, beacon-chain/powchain/service.go, beacon-chain/rpc/beacon/blocks.go, beacon-chain/rpc/beacon/blocks_test.go, beacon-chain/sync/rpc.go, tools/bootnode/bootnode.go
This PR is a collection of fixes and small improvements to close out open bug reports.
---
=> Resolve Miscellaneous Bugs in Beacon Node

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/receive_block.go
Added a few more checks after rereading the spec. This should improve new fork choice health
* Update justified check point with best justified check point before calling head
* New finalized check point could imply new justification. Added a check for that
=> Misc fork choice improvements

WORKSPACE
No tracking issue, this PR updates the following dependencies:
- com_github_gogo_protobuf
- prysm testnet site
- io_kubernetes_build
- com_google_protobuf
- com_github_mattn_go_isatty
- com_github_jbenet_goprocess
- com_github_emicklei_dot
- com_github_prometheus_client_model
- com_github_prometheus_common
- com_github_prometheus_procfs
- com_google_cloud_go
- com_github_pkg_errors
- com_github_dgraph_io_ristretto
- com_github_googleapis_gnostic
- io_k8s_apimachinery
- com_github_apache_thrift
=> Update dependencies from renovate

beacon-chain/blockchain/info.go
=> Render blocktree graph in page

beacon-chain/blockchain/service.go
Looking at the Vizgraph, I was confused on why initial sync and regular sync don’t belong in the same branch. As we didn’t think it was that big of the deal, the following warning log was temporary as it eventually goes away:
`[2020-02-04 15:31:07]  WARN blockchain: Skip head update for slot 187055: head at slot 187008 with weight 4831 is not eligible, finalizedEpoch 5842 != 5843, justifiedEpoch 5843 != 5844`
After looking at this more, we realized to resume syncing, node gets the 1.) head block then start start sync from 2.) last finalized check point. So fork choice insert head block into the array as index 0. The issue is illustrated as the following:
```
Index 0, block_at_slot: 888 (head block)
Index 1, block_at_slot: 800 (last finalized block)
Index 2, block_at_slot: 801 (last …
```
=> Don't insert head to proto array DAG as index 0

beacon-chain/blockchain/receive_block.go
I found it weird the reporting of `head_slot` is always one slot behind versus proto array's service reporting. It turns out we update `head_slot` metric before computing for head slot. We should update `head_slot` metric after computing and this PR fixed that.
=> Update head slot metric after compute head

beacon-chain/db/kv/state.go
As title describes, return an error if there is a nil state attempted to be saved.
=> DB: Do not allow attempts to save a nil state

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
We never updated boolean variable `higherThanFinalized` in the loop so the loop traversed all the way back to genesis slot 😸 
Added a regression test. Thanks @prestonvanloon for the catch
=> Update higherThanFinalized in the loop

beacon-chain/db/kv/state.go
This resolves #4619 
---
Even though we had a lot of memory improvements in the beacon node, certain users were still reporting massive mem consumption, which was proven by a mem flame graph extracted by one our community members on discord: 
Most of the time was being spent calling bolt.Batch which only a few functions used, namely `DeleteStates`, which would likely cause a huge amount of resource consumption.
This PR changes the bolt batch call to delete states to a db.Update instead to do in a single transaction.
=> Change Batch Call to Update in Deleting States

beacon-chain/blockchain/info.go
- Added new field `Votes` (ie the number of validators)
- Added color green for head block
- ETH -> Gwei is `1e9` not `10e9`
=> Block tree enhancements

beacon-chain/blockchain/forkchoice/log.go, beacon-chain/blockchain/log.go, beacon-chain/blockchain/metrics/metrics.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/core/epoch/precompute/justification_finalization_test.go, beacon-chain/core/epoch/precompute/reward_penalty.go, beacon-chain/core/helpers/validators.go, beacon-chain/core/state/benchmarks_test.go, beacon-chain/core/state/state_test.go, beacon-chain/rpc/beacon/validators.go, beacon-chain/state/getters.go, beacon-chain/sync/subscriber_beacon_blocks.go, shared/testutil/block_test.go
There were many instances where we were doing `state.FInalizedCheckpoint().Epoch` which makes a full copy of the checkpoint unnecessarily. Looking at this benchmark, it seems to improve epoch processing by about 30%. 
Before
```
BenchmarkProcessEpoch_2FullEpochs-8           39          34897535 ns/op        23557595 B/op     389336 allocs/op
```
After
```
BenchmarkProcessEpoch_2FullEpochs-8           54          25043262 ns/op        18837890 B/op     291021 allocs/op
```
=> Add & use FinalizedCheckpointEpoch() to state

beacon-chain/blockchain/info.go
Fixed a few more bugs
- Don't render page if `s.headState == nil` since node needs it for weight and vote calculations
- Don't mark a node as green if it has a best descendent
=> Fix block tree cosmetic bugs

beacon-chain/operations/attestations/BUILD.bazel, beacon-chain/operations/attestations/aggregate_test.go, beacon-chain/operations/attestations/prepare_forkchoice.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
When a bad attestation makes it into fork choice, it may be aggregated causing the whole attestation to become bad. Until we have a better mechanism to prevent bad attestations from corrupting good ones in fork choice, we will not aggregate them by default. The purpose of the aggregation is to reduce the number of distinct aggregations processed through fork choice. While this type of optimization is desired, better to be safe for the time being.
Maybe supersedes #4660
=> Disable forkchoice pre-processing of attestations

validator/keymanager/BUILD.bazel, validator/keymanager/wallet.go
This exposes a wallet location option in the relevant `keymanageropts` to allow explicit definition of where the wallets can be found.
This is required when the validator is run in a docker container (and can be used when run standalone if the user wishes).
=> Add location option for wallet keymanager

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/service.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/state/setters.go, beacon-chain/sync/initial-sync/service.go
Instead of copying all the data, we just initialize a new object and reference the pointers. 
That way updates are less intensive on memory. Also clear out old states when sync is finished
=> Update Slices More Efficiently

beacon-chain/blockchain/process_block_helpers.go
On a new sync at info level logging I see a *lot* of these:
```
{"indices":[27148,27149,27150,27151,27152,27153,27154,27155,27156,27157,27158,27159,27160,27161,27162,27163],"level":"info","msg":"Validator indices saved in DB","prefix":"blockchain","time":"2020-02-08T09:34:14Z","totalValidatorCount":16}
{"indices":[27164,27165,27166,27167,27168,27169,27170,27171,27172,27173,27174,27175,27176,27177,27178,27179],"level":"info","msg":"Validator indices saved in DB","prefix":"blockchain","time":"2020-02-08T09:34:15Z","totalValidatorCount":16}
{"indices":[27180,27181,27182,27183,27184,27185,27186,27187,27188,27189,27190,27191,27192,27193,27194,27195],"level":"info","msg":"Validator indices saved in DB","prefix":"blockchain","time":"2020-02-08T09:34:15Z","totalValidatorCount":16} …
```
=> Downgrade "Validator indices saved in DB" log entry

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/head.go
if head state is nil, return error. Similar to what we did with block
Also update cached had state on retrieval
=> Don't save nil head state

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, shared/featureconfig/flags.go
Delete block attestations from the pool instead holding them to delete at expiration time
=> Delete block attestations from the pool

beacon-chain/blockchain/process_attestation.go, beacon-chain/sync/rpc_goodbye.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
Computing head for every new attestation is a nice to have but may be too excessive, we can change the strategy to updating head every second. Opening this as an option to not compute  head on every attestation.   
Another option is to remove the tracing for the following methods. They seem to be the main bottlenecks.
=> Feature flag to disable head update on attestation basis

beacon-chain/forkchoice/protoarray/nodes.go, beacon-chain/forkchoice/protoarray/nodes_test.go
Removed spans for `updateBestChildAndDescendant`, `leadsToViableHead`, and `viableForHead`
=> Removed spans for fork choice helpers

beacon-chain/cache/checkpoint_state.go
Previous size 4 was not enough given more forks than expected in current testnet. 
```
check_point_state_cache_hit 133643
check_point_statecache_miss 2762
```
Increased the 10:
```
committee_cache_hit 135609
committee_cache_miss 12
```
Improved hit ratio from 97.9% to 99.9%, it may not seem like a lot but that's a saving of 2000 extra hash tree root and epoch transition of a mainnet state
=> Increase check point state cache size to 10

beacon-chain/blockchain/testing/mock.go, beacon-chain/sync/initial-sync/round_robin.go, beacon-chain/sync/initial-sync/service.go
States were using 600mb in memory after sync.
=> Clear initial sync state caches after round robin sync

beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/rpc_goodbye_test.go
=> Fix Goodbye RPC handler

beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/validate_committee_index_beacon_attestation.go
Resolves #4829 
---
We had a function that would do concurrent map iterations in `beacon-chain/sync/pending_attestations_queue.go` called `processPendingAtt`. Thanks to @shayzluf for pointing this out.
This func adds a lock to the function and properly handles its errors when it is called.
=> Add Lock to Processing Pending Attestations

slasher/beaconclient/BUILD.bazel, slasher/beaconclient/receivers.go, slasher/beaconclient/receivers_test.go, slasher/beaconclient/service.go
Part of #4836
---
Currently, slasher does a lot of things in single files, instead of having proper separation of concerns between services.
This PR creates a `beaconclient` package in `slasher` that initializes a gRPC connection to a beacon node for listening to streamed blocks and attestations. The service then relays received data via a `BlockFeed *event.Feed` and `AttestationFeed *event.Feed` other services in the slasher runtime can subscribe to.
This PR does **not** hook-up this service to a main slasher runtime. This will be done in a separate PR once all the difference pieces are built.
=> Include Beacon Client Package in Slasher

beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/validate_aggregate_proof.go
We also lock it when receiving an aggregate proof.
=> Add Pending Attestation Lock fix

beacon-chain/sync/BUILD.bazel, beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_committee_index_beacon_attestation.go
=> Secure lock when accessing the map only

slasher/beaconclient/BUILD.bazel, slasher/beaconclient/service.go, slasher/beaconclient/submit.go, slasher/beaconclient/submit_test.go, slasher/node/BUILD.bazel, slasher/node/node.go
Part of #4836 
---
This PR sets up the slasher to submit attester/proposer slashing objects via RPC to the connected beacon node as soon as they are seen. It subscribes to a global event feed in the slasher runtime to then submit the items.
=> Send Slashing Objects to Beacon Node via RPC

beacon-chain/blockchain/process_block_helpers.go
If the incoming block's finalized block is not known to us (ie `nil`), it's better to log the following:
```
no finalized block known for block from slot 258817
```
Than
```
block from slot 258817 is not a descendent of the current finalized block slot 258752,  != 0x86724b59c12c
```
=> Improve block descendant error log

validator/client/validator_metrics.go
TODO(you): choose "part of" or "resolves" and the associated github issue #.
[Part of] #4864 
---
prevent additional OOB errors when checking validator balances
=> prevent additional array OOB errors for validator balances

beacon-chain/core/helpers/attestation.go, beacon-chain/core/helpers/attestation_test.go
=> Check attestation bitlist length in aggregation to prevent panic

beacon-chain/blockchain/process_block.go
Part of #4836 
---
We are not saving attestations to the attestations bucket on initial sync even if --archive was enabled. This functionality is important for slasher to fetch historical attestations.
=> Save Attestations In Initial Sync if Archive Enabled

beacon-chain/state/BUILD.bazel, beacon-chain/state/getters.go, beacon-chain/state/types.go, shared/memorypool/BUILD.bazel, shared/memorypool/memorypool.go, shared/memorypool/memorypool_test.go
This was originally from #4844 but has been separated into its own PR
The shift to using a memory pool here is so that we can re-use non-referenced objects on the heap which havent been cleared by the GC. This allows us to avoid allocating new memory again and instead we can just re-use it. Since Randao Mixes is one of our most expensive fields when modifying the state, it would be most useful to re-use already destroyed objects instead of allocating a new array.
=> Use Memory Pool for Randao Mixes

beacon-chain/flags/base.go, beacon-chain/main.go, beacon-chain/usage.go
Originally a part of #4844 
This allows nodes to toggle with the percentage of newly allocated data to live data that the GC is triggered to run again.
=> Utilise a Flag to Toggle With the GC

beacon-chain/blockchain/process_attestation_helpers.go
When an attestation's signature fails to verify, this checks if it's due to different seeds result in different committees. If yes, it'll log the difference in seeds for better debugging
=> Enhance signature fails to verify message

shared/featureconfig/config.go, shared/featureconfig/flags.go, shared/memorypool/BUILD.bazel, shared/memorypool/memorypool.go
A copy of #4824 which had been reverted.
=> Add mempool feature flag 

beacon-chain/blockchain/service.go, beacon-chain/flags/base.go, beacon-chain/flags/config.go, beacon-chain/main.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/usage.go
This leads to the node starting with the previously saved head state instead of finalized state with the flag utilized.
=> Add Unsafe Sync

validator/client/BUILD.bazel, validator/client/service.go
Retries requests on  `ResourceExhausted` and `Unavailable` gRPC codes
=> gRPC retry requests

beacon-chain/db/kv/state.go
Instead of doing a binary search for already deleted keys we store the relevant keys in a map, and use the bolt cursor to efficiently traverse all the keys in the bucket. This results in much faster deletion of states
=> Delete States More Efficiently

beacon-chain/blockchain/process_block_helpers.go
If we use the initial sync flag, we will generate a justified state each time we want to save a justified checkpoint. This PR checks if a state exists first.
=> Check DB for Justified State

beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_attestations_queue_test.go, beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, beacon-chain/sync/validate_committee_index_beacon_attestation.go, beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Here's the problem, when a node receives an attestation and it doesn't have the block. It requests the block. It will then go ahead to validate the signature in sync without waiting for state to be processed. Breaking this down into time line:
1.)
```
[2020-02-18 09:23:15]  INFO blockchain: Executing state transition on block root=0x6b34ab0d... slot=286016
```
2.)
```
[2020-02-18 09:23:16] ERROR blockchain: Failed to validate attestation error=pre state of target block 286016 does not exist
[2020-02-18 09:23:16] ERROR blockchain: Failed to validate attestation error=pre state of target block 286016 does not exist
[2020-02-18 09:23:16] ERROR blockchain: Failed to validate attestation error=pre state of target block 286016 does not exist
[2020-02-18 09:23:16] ERROR blockchain: Failed to …
```
=> Handing pending atts if they dont have the state

slasher/detection/attestations/BUILD.bazel, slasher/detection/attestations/attestations.go, slasher/detection/attestations/attestations_bench_test.go, slasher/detection/attestations/attestations_test.go, slasher/rpc/server.go
This PR goes through the MinMaxSpan detection implementation and does things like organize parameters, reduce redundancy, and clean up logs.
=> Clean up MinMaxSpan implementation

validator/client/validator_aggregate.go
TODO(you): choose "part of" or "resolves" and the associated github issue #.
---
Fixes panic on validator when failing to submit signature, and emit metrics is enabled:
```
[2020-02-20 21:34:24]  INFO validator: Submitted new attestations AggregatorIndices=[] AttesterIndices=[33181] BeaconBlockRoot=0x4ce954a7fbf2 CommitteeIndex=8 Slot=301671 SourceEpoch=9426 SourceRoot=0x1231cd9a1d6c TargetEpoc
h=9427 TargetRoot=0x764252b11e52
[2020-02-20 21:34:44] ERROR validator: Could not submit slot signature to beacon node: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport:
Error while dialing dial tcp 192.168.0.126:4000: connect: connection refused"
panic: inconsistent label cardinality: expected 1 label values but …
```
=> fix missing metrics label on attetation fail

beacon-chain/state/BUILD.bazel, beacon-chain/state/getters.go, beacon-chain/state/types_test.go
We were incorrectly copying the current fork version which lead to failures in the v0.10.1 spectests. This PR has the fix and regression test for it
=> Fix Fork Copying

beacon-chain/operations/attestations/BUILD.bazel, beacon-chain/operations/attestations/aggregate.go, beacon-chain/operations/attestations/kv/aggregated.go, beacon-chain/operations/attestations/kv/unaggregated.go, beacon-chain/operations/attestations/metrics.go, beacon-chain/operations/attestations/pool.go, shared/featureconfig/flags.go, slasher/beaconclient/historical_data_retrieval.go, validator/client/service.go
Part of #4929 
This PR adds metrics for the total count of each **aggregated** and **unaggregated** attestations in pool.
Will be monitoring this tonight. Here's preliminary stats mine after 20 mins... 
`aggregated_attestations_in_pool_count 805`
=> attestations in pool count metrics

beacon-chain/rpc/beacon/BUILD.bazel, beacon-chain/rpc/beacon/validators_stream.go
For infostream to calculate the activation time for pending validators it requires the timestamp of the block in which the deposit was made.  This was being fetched each time the value was calculated, resulting in a lot of extraneous calls to `BlockTimeByHeight()`, which in turn talks to the Ethereum 1 node.
This patch adds a cache mapping block number to block time.  It also adds in prometheus metrics for the two infostream caches.  Finally, it handles blocks inline rather than spinning out a separate goroutine, as the gRPC server already puts the infostream call in a separate goroutine and this ensures the code isn't run for multiple epochs in parallel.
=> Add Ethereum 1 block->timestamp cache for infostream

slasher/detection/attestations/BUILD.bazel, slasher/detection/attestations/iface/BUILD.bazel, slasher/detection/attestations/iface/iface.go, slasher/detection/attestations/mock_spanner_test.go, slasher/detection/attestations/spanner.go, slasher/detection/attestations/spanner_test.go, slasher/detection/attestations/types/BUILD.bazel, slasher/detection/attestations/types/types.go
Part of #4836 
This PR adds a `SpanDetector` interface and a mock `MockSpanner` to be used for future testing.
=> Add interface for spanner and MockSpanner

beacon-chain/sync/initial-sync/BUILD.bazel, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_fetcher_test.go, beacon-chain/sync/initial-sync/round_robin.go, endtoend/beacon_node.go
Part of #4815
---
Reference implementation of non-blocking initial synchronization, where producer-consumer queue is used to separate block fetching from processing (and allow them to run concurrently).  More details are outlined in the [design document](https://docs.google.com/document/d/1mm__vLgJfkq25iryIAqWNSgFNfaXqU2tM7P31e8jyf8/edit?usp=sharing).
This PR, handles only fetching part of the requirements:
- round robin initial sync **has been patched** to use new fetcher
- while new fetcher can be run in a non-blocking mode, since we've decided to move in incremental steps, almost one-to-one functionality port was made. So, ideally, everything should be run as before, but the code underneath is decoupled.
=> init-sync: refactor block fetching

beacon-chain/blockchain/process_attestation_helpers.go, beacon-chain/blockchain/process_block_helpers.go
When processing an attestation or block, we retrieve the pre-state from the db. This PR makes sure that we check the head state first before retrieving from the db.
=> Check HeadState First

beacon-chain/rpc/beacon/validators.go
This allocates slices with a suitable initial capacity so that re-allocations do not occur when responding to the validator performance request.
=> Pre-allocate slices when reporting validator performance

beacon-chain/operations/slashings/service.go, beacon-chain/operations/slashings/service_attester_test.go, beacon-chain/operations/slashings/service_proposer_test.go, validator/client/validator_attest.go
This PR fixes a bug of pending slashings getting "stuck" in the pool. Due to the binary search having the incorrect condition, it would only find the requested index to remove if the list was very short. After the pending queue got longer, it failed to properly find the index needed. Changing the condition to `i >= val` solves this.
Adds regression tests.
=> Fix stalling bug in slashing pool

beacon-chain/state/stategen/BUILD.bazel, beacon-chain/state/stategen/epoch_boundary_root.go, beacon-chain/state/stategen/epoch_boundary_root_test.go, beacon-chain/state/stategen/service.go
This is part of state gen service. To construct or reconstruct the state summary, a node will fill up or use the correct epoch boundary root of any given slot. This allows easy playback for state. This PR simply adds a cache of `slot -> boundary root`
Detail usages: #4834
=> Add epoch boundary root map

validator/keymanager/direct_keystore.go, validator/keymanager/direct_unencrypted.go, validator/keymanager/wallet.go
User hit the situation where they wrapped a shell expansion character for the keymanager options in quotes, so the shell did not expand it.  Although we cannot prevent this, we can detect it and highlight it in the logs, as otherwise it is not an obvious mistake and can cause user confusion (especially in situations where we try to help by creating the path directory if it doesn't exist rather than erroring).
This prints a suitable warning in the log on detection of this condition.
Resolves #4998 (as much as we can).
=> Add warning if shell expansion characters make it in to the path

beacon-chain/p2p/discovery.go, beacon-chain/p2p/service.go
Currently when providing a peer as an argument, we can only represent it as a multi-address. This PR allows peers to be represented as ENRs too
=> Allow Peers to Also be Specified Using ENRs

beacon-chain/p2p/discovery_test.go, beacon-chain/p2p/service.go
This PR changes how we connect to peers, spinning each dial into a separate go-routine to make them non blocking. Also removes the exclusion list we were using an instead uses our peer handler, to handle bad peers.
=> Asynchronous Dials To Peers 

beacon-chain/rpc/beacon/validators.go
The validator performance RPC call fetches a validator index and assumes said index is present in the validator summary slice.  This could be a bad assumption for a new validator.
This patch ensures the validator is present in the validator summary slice before attempting to provide statistics; if not found it will make the validator as missing for completeness' sake.
Resolves #4986
=> Avoid crash due to invalid validator summary index

beacon-chain/powchain/log_processing.go
We now only request blocks in 1000 chunks instead of 2000 so as to not overload an ETH1 node. We also add one more conditional before requesting all the deposit logs from a contract so as to not again overload the eth1 node.
=> Change ETH1 Constant

shared/keystore/BUILD.bazel, shared/keystore/keystore.go, shared/keystore/keystore_test.go, tools/sendDepositTx/sendDeposits.go, validator/accounts/account.go
This fixes an issue on validator startup where any failure to decrypt a keystore would cause the validator to exit.  It now provides a warning about the failure, and continues.
Resolves #4955
=> Warn rather than fail on incorrect keystore password

.bazelrc
The default was fastbuild.
See https://docs.bazel.build/versions/master/user-manual.html#flag--compilation_mode
`fastbuild` means build as fast as possible: generate minimal debugging information (-gmlt -Wl,-S), and don't optimize. This is the default. Note: -DNDEBUG will not be set.
`opt` means build with optimization enabled and with assert() calls disabled (-O2 -DNDEBUG). Debugging information will not be generated in opt mode unless you also pass --copt -g.
Example improvement impact with -c opt
```
Before
BenchmarkProcessEpoch_2FullEpochs-8           25          45139085 ns/op        15178165 B/op     223523 allocs/op
After
BenchmarkProcessEpoch_2FullEpochs-8           32          38769789 ns/op        15178783 B/op     223539 allocs/op
```
=> Define -c opt for release builds

slasher/cache/span_cache.go, slasher/db/kv/kv.go, slasher/db/kv/kv_test.go, slasher/db/kv/spanner_test.go, slasher/node/node.go
Part of #4836 
This PR fixes LRU cache to take cache size as parameter and fix `TestValidatorSpanMap_SaveOnEvict`.
=> on evict test fix

validator/client/validator_propose.go, validator/keymanager/keymanager.go
The protecting keymanager currently sends the entire block as part of its signing call.  This is unnecessary, as only the relevant roots are required.
This changes the relevant call from using `BeaconBlock` to `BeaconBlockHeader`, reducing the data passed around (especially important if the signer is remote).
=> Use BeaconBlockHeader in place of BeaconBlock for protecting keymanager

beacon-chain/state/stategen/BUILD.bazel, beacon-chain/state/stategen/hot.go, beacon-chain/state/stategen/hot_test.go, beacon-chain/state/stategen/replay.go, beacon-chain/state/stategen/replay_test.go
As we previously added method to retrieve hot state by `root`, this PR adds in the method to retrieve hot state by `slot`.  This uses rarely than formal but proven to be useful at times. Also added tests to go with it
=> Add hot state by slot retrival

slasher/detection/BUILD.bazel, slasher/detection/attestations/BUILD.bazel, slasher/detection/attestations/iface/iface.go, slasher/detection/attestations/mock_spanner.go, slasher/detection/attestations/spanner.go, slasher/detection/attestations/spanner_test.go, slasher/detection/attestations/types/BUILD.bazel, slasher/detection/attestations/types/types.go, slasher/detection/detect.go, slasher/detection/listeners_test.go, slasher/detection/service.go
Part of #4836 
This PR modifies how updating and detection is performed on the slasher by changing it to perform the actions on a per attestation basis, rather than a per validating indice basis.
This gives us less overhead, less DB locks, and makes detection much simpler.
=> Change detection and updating in Slasher to per attestation

.bazelrc, WORKSPACE, shared/bls/BUILD.bazel, shared/bls/spectest/BUILD.bazel, third_party/herumi/bls.BUILD, third_party/herumi/bls_eth_go_binary.BUILD, third_party/herumi/bls_eth_go_binary_serialization_alloc_fix.patch, third_party/herumi/herumi.bzl, third_party/herumi/mcl.BUILD
A translation of herumi's makefiles. 
This library works with the llvm toolchain if you have libgmp installed.
For now, the default is to use the precompiled archives, but using herumi's repositories directly rather than maintaining a fork. I'll be continuing progress on this to make building herumi's library more seamless, but checking in progress so far.
=> Build herumi's BLS from source

beacon-chain/powchain/BUILD.bazel, beacon-chain/powchain/service.go
At current if the Ethereum 1 node to which the beacon node is connected isn't syncing we get messages in the log every second.  This patch reduces the frequency to every 15 seconds, to stop the log from being flooded.
=> Reduce frequency of 'eth1 client not syncing' messages

beacon-chain/state/BUILD.bazel, beacon-chain/state/getters.go, beacon-chain/state/getters_test.go
When writing tests for initial sync, I've noticed that `BeaconState.Slot()/SetSlot()` has a data race condition (on getter we don't obtain mutex). This PR fixes that race.
I haven't enabled "race=on" in the `BUILD.bazel` because there are a lot of data races in other tests of the state package (and I can't jump to that rabbit hole just yet).
=> fixes data race in state.Slot

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Part of #4815 
When working on queueing and processing of the init sync, I've discovered couple of issues in the fetcher (race conditions). This PR resolves them.
NB: The PR doesn't touch round robin routine yet, so it is safe to merge - in sense that it will not break anything.
=> fixes races in blocks fetcher

beacon-chain/rpc/beacon/attestations.go, beacon-chain/rpc/beacon/attestations_test.go
Part of #4836 
---
Currently, our beacon node RPC endpoint `StreamIndexedAttestations` uses the current blockchain service HeadSlot to determine committees for converting attestations into indexed form. This is really bad and leads to signature did not verify failures. Instead, we should be using the target epoch of the attestations to convert them into indexed form based on the proper committees.
This PR removes usage of HeadSlot in `StreamIndexedAttestations`.
=> Use Target Epoch to Determine Indexed Attestations for Slasher

validator/keymanager/BUILD.bazel, validator/keymanager/wallet.go, validator/keymanager/wallet_test.go
If the wallet keymanager were given multiple passphrases it would try each for each account, resulting in spurious error messages in the log.
This patch alters the process so that an error message is only written if none of the supplied passphrases can unlock an account.
=> Remove suprious error messages in wallet keymanager

beacon-chain/blockchain/chain_info.go, shared/attestationutil/attestation_utils.go
=> Minor Improvements

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_fetcher_test.go, beacon-chain/sync/initial-sync/round_robin_test.go
Part of #4815
---
Resolves number of issues discovered when implementing queue portion of the feature:
- data race in `round_robin_test` (occurs when fetching and processing is decoupled)
- blocking calls in `blocks_fetcher` which resulted in deadlocks when running along-side the queue
NB: This PR **DOES NOT** yet update current init-sync code.
=> Init sync pre queue

validator/client/runner.go, validator/client/validator_aggregate.go
A couple of changes to validator logging:
- log the deadline when the validator starts work for a given slot
- demote the "nothing to do" log entry to TRACE; in any slot 5/6 of validators would report this and it floods the logs with no useful information
And because it was in my queue, a more detailed error when the "sign slot" operation fails.
=> Tweak validator logging

beacon-chain/state/stategen/service.go, beacon-chain/state/stategen/service_test.go, beacon-chain/sync/initial-sync/blocks_fetcher.go
This PR added a new method `Resume` which resumes the usage of new state management. This gets called whenever node restarts with an existing db. Also added a test to go with this
=> Resume new state mgmt

beacon-chain/blockchain/head.go
When testing initial sync I got segmentation fault:
```
WARN blockchain: Generating missing state of slot 484934 and root 0x64c8990f9bfe5c884f985bbb6d77f074483c6defa338e0441758a0606c2cdc79
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x46a5f36]
goroutine 268 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).HasInnerState(...)
beacon-chain/state/getters.go:121
github.com/prysmaticlabs/prysm/beacon-chain/state.(*BeaconState).Copy(0x0, 0x0)
beacon-chain/state/types.go:87 +0x56
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).setHead(0xc0001b0a80, 0x91e299afbecc6486, 0x87ae3d06cc6e14be, 0xe115cbeb3e4196b9, 0xb3992e5de0ce2335, 0xc01d20c480, 0x0) …
```
=> asserts non-nil state

validator/client/validator.go, validator/client/validator_log.go
This PR makes very minor changes to the validator logs to improve UX.
Changes:
Removed `Waiting for validator to be activated in the beacon chain` log, spammed and provided nothing
Changed waiting deposit log to `Waiting for deposit to be seen` instead of `Waiting to be activated`.
Log out existing assignments for epoch on startup, instead of having the user waiting till next epoch to know if they have any assignments.
=> Improve validator logs

WORKSPACE, beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go, beacon-chain/sync/initial-sync/round_robin.go, third_party/com_github_prysmaticlabs_ethereumapis-tags.patch
This PR adds the support for the `ListValidators` endpoint to retrieve validators by indice and public key.
=> Add fetching validators by indices and public keys

endtoend/BUILD.bazel, endtoend/README.md, endtoend/beacon_node.go, endtoend/endtoend_test.go, endtoend/evaluators/validator.go, endtoend/helpers.go, endtoend/minimal_antiflake_e2e_test.go, endtoend/minimal_slashing_e2e_test.go, shared/featureconfig/flags.go
This PR adds 2 extremely simple tests to make sure flakes do not pass the E2E. Also comments out the flag for #5123 as it causes flakes.
This extends the E2E test by 5 minutes.
=> Add Anti-Flake test for E2E

shared/cmd/flags.go
The default value for the `datadir` option went missing in a recent patch.  This puts it back.
=> Replace default value for datadir

beacon-chain/blockchain/process_attestation_helpers.go, beacon-chain/blockchain/process_block.go, beacon-chain/core/blocks/block_operations.go, beacon-chain/core/blocks/block_operations_test.go, beacon-chain/core/epoch/epoch_processing.go, beacon-chain/core/epoch/precompute/attestation.go, beacon-chain/core/epoch/precompute/attestation_test.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/core/state/transition_test.go, beacon-chain/rpc/beacon/attestations.go, beacon-chain/rpc/beacon/attestations_test.go, beacon-chain/rpc/validator/aggregator_test.go, beacon-chain/rpc/validator/proposer_test.go, beacon-chain/sync/pending_attestations_queue_test.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, shared/attestationutil/BUILD.bazel, shared/attestationutil/attestation_utils.go, shared/attestationutil/attestation_utils_test.go, tools/blocktree/main.go
- Refactor attestationutil.AttestingIndices. It never returned an error anyway.
- ~Add a shortcut if the attestation was fully attested by the committee~
- Add tests
- Refactor attestationutil.ConvertToIndexed. It returned the error from AttestingIndices, which was always nil.
=> Refactor attestationutil.AttestingIndices

beacon-chain/flags/base.go, beacon-chain/gateway/BUILD.bazel, beacon-chain/gateway/cors.go, beacon-chain/gateway/gateway.go, beacon-chain/gateway/server/main.go, beacon-chain/node/node.go
Resolves #5175
This PR adds a flag to use with gRPC gateway to serve CORS pre-flight requests. 
Example: `--grpc-gateway-corsdomain=domain.com,domain2.com,domain3.com`
=> Add CORS preflight support

.buildkite-bazelrc
Seeing some build issues that might be due to over-stressed builders.
Removing some job count overrides, bazel defaults jobs to HOST_CPU. 
50 is way too many for non-RBE builds. 
Colors were polluting the downloaded logs, it's not as pretty but makes better log files :smile: 
Also added repository caching to reduce fetching
=> Buildkite changes

beacon-chain/core/state/BUILD.bazel
Some of the fuzz tests in this package run 1000 times, sharding these test will allow these to run in parallel and less likely to timeout.
=> Shard //beacon-chain/core/state:go_default_test

endtoend/params/params.go
This PR changes the ports for E2E to not use commonly used ports, to prevent conflicts.
=> Change E2E config ports to be non-commonly used

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/blocks_test.go, beacon-chain/db/kv/kv.go
Apply lesson learned from #5192 state slots to block slots 
Change list:
- Add locking to set bit and clear bit for block slots
- Update API to return multiple blocks 
- Address a underflow condition
- Comments on why copy is used
=> Apply fixes to block slots methods in DB

beacon-chain/core/blocks/block_operations.go, beacon-chain/sync/subscriber_beacon_blocks.go, beacon-chain/sync/subscriber_beacon_blocks_test.go, beacon-chain/sync/validate_beacon_blocks.go, beacon-chain/sync/validate_beacon_blocks_test.go
This PR updates beacon block's validation pipeline from verifying "a valid BLS signature" to verifying a "valid proposer signature"
=> Verify proposer signature in sync

beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_attestations_queue_test.go, beacon-chain/sync/service.go, beacon-chain/sync/subscriber_beacon_aggregate_proof.go, beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, beacon-chain/sync/validate_committee_index_beacon_attestation.go, beacon-chain/sync/validate_committee_index_beacon_attestation_test.go
Instead of using `AggregateAttestationAndProof` we use `SignedAggregateAttestationAndProof` instead everywhere in sync ,as our topic mappings use that data type to map aggregation and proof objects. Also fix references in tests for it
=> Fix Signed Attestation In Sync

WORKSPACE, beacon-chain/BUILD.bazel, tools/BUILD.bazel, tools/binary_targets.bzl, tools/build_settings.bzl, validator/BUILD.bazel
This adds `-alpine` suffix tags for using alpine as the base image for the validator client and beacon-chain client.
Using alpine means you have a package manager and other helpful tooling that maybe useful in some deployments. The docker image size is only slightly larger, a few megabytes.
Uses an alpine image with glibc: https://hub.docker.com/r/frolvlad/alpine-glibc
Resolves #5212
=> Add alpine based docker images for validator and beacon chain

beacon-chain/blockchain/head.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/state/state_trie.go
To reduce memory usage from the copying of the field trie, we utilize a new method called `FastCopy` which removes all references to the trie in the source state. This is used when the state we are copying from is going to be garbage collected and eventually destroyed.
=> Add Fast Copy of Trie

beacon-chain/state/stategen/getter.go
Found a minor regression with state mgmt service on latest master.
If the input block root is zero hash, a node should just return what's stored in DB rather than proceed on rest of the computations
=> Short circuit genesis condition for new state mgmt

beacon-chain/core/blocks/BUILD.bazel, beacon-chain/core/blocks/block_operations.go, beacon-chain/core/blocks/block_regression_test.go
We were incorrectly determining slashable indices which lead to 100 innocent validators being slashed in our testnet. This PR contains the fix and the regression test which follows very closely from our slashing event in the testnet , except for a validator set size of 5500 and each index being divided by 10 so as to make test time shorter.
Due to this being testnet breaking we will have to merge it into the v0.11 branch. Thanks to @mcdee for bringing this up.
=> Fix Incorrect Attester Slashing Method

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/blocks_test.go
Say to save blocks `[b0,b1,b2,b3,b4,b5,b6]`, if one of the block exists in the cache, the function will just `return nil` instead of `continue` which doesn't complete saving all the blocks
=> Fix save blocks return nil

beacon-chain/db/kv/BUILD.bazel, beacon-chain/db/kv/check_state.go, beacon-chain/db/kv/kv.go, beacon-chain/db/kv/schema.go
This PR adds a check to ensure new state management service is compatible with beacon node DB. It implements the following conditions:
`old-state-mgmt-service -> new-state-mgmt-service`  is not ok and errors out
`new-state-mgmt-service -> old-state-mgmt-service` is ok
=> Check new state mgmt service is compatible with DB

endtoend/BUILD.bazel, endtoend/minimal_antiflake_e2e_1_test.go, endtoend/minimal_antiflake_e2e_2_test.go
This splits up the antiflake tests to prevent conflicts with the bazel containers.
=> Separate anti flakes to prevent E2E issues

endtoend/BUILD.bazel, endtoend/components/slasher.go, endtoend/params/params.go, slasher/flags/flags.go
This PR fixes some possible issues that could be caused by sharding the E2E tests which we do for every PR now. Should prevent more flakes from occurring.
=> Fix flaky E2E test sharding

third_party/herumi/bls_eth_go_binary.BUILD, third_party/herumi/mcl.BUILD
These changes allow for flag based configuration of BLS build configuration. 
I was not able to find a noticeable improvement with gmp or ssl over the default configuration.
=> Add configurations for BLS builds

beacon-chain/p2p/monitoring.go, beacon-chain/sync/metrics.go, beacon-chain/sync/service.go
No tracking issue, this PR updates p2p topic metrics with fork digests so they show up properly formatted
=> update metrics with fork digest for p2p

endtoend/endtoend_test.go, endtoend/minimal_antiflake_e2e_1_test.go, endtoend/minimal_antiflake_e2e_2_test.go, endtoend/params/params.go
This PR solves the flaky E2E issue of eth1 port not being ready by offsetting the ports by 100, in order to prevent being on a commonly used port like 3000.
=> Fix E2E eth1 flaking 

shared/featureconfig/config.go, shared/featureconfig/flags.go, validator/client/validator_propose.go
Resolves #5267
Also upgrades the warning message to error level.
=> Enable slashing protection in validator by default

beacon-chain/p2p/discovery_test.go, beacon-chain/p2p/fork_test.go, beacon-chain/p2p/service_test.go, beacon-chain/p2p/subnets_test.go
This PR adds in changes that make our testing more robust where we release resources correctly at the ending/termination of a test.
=> Release Resources Correctly in P2P Tests

beacon-chain/p2p/encoder/ssz.go, beacon-chain/p2p/encoder/ssz_test.go
Spec defines a 1Mb chunk size limit that was not enforced in Prysm's network decoder.
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/p2p-interface.md#configuration
Discovered in fuzz testing when the test tried to send a 84 byte message with a length of over 9000 petabytes.
=> Set a max limit for decoding ssz objects from p2p

WORKSPACE, validator/keymanager/BUILD.bazel, validator/keymanager/remote.go, validator/keymanager/remote_internal_test.go
A few updates for the remote keymanager after running it in test for a while:
- increase the maximum message size received from the remote server to allow for larger number of keys
- do not panic on bad response from remote server
- check response code when asking for accounts and error on error situations (requires update to eth2-signer-api dependency)
- when receiving list of accounts to validate with from the remote server check them against user-supplied path specifier to ensure we aren't validating accounts we shouldn't
=> Updates for remote keymanager

beacon-chain/blockchain/process_block.go, beacon-chain/operations/attestations/kv/unaggregated_test.go
This ensures saving of initial sync cached blocks to DB during phase 2 of the syncing where `onBlock` os used.
I saw an edge case that syncing phase 2 kicked in but finalized block did not make it to the db:
```
[2020-04-04 14:15:06] ERROR sync: Could not process block from slot 618374: could not process block: could not save finalized checkpoint: missing block in database: block root=0x76213df966a6a9fb0f6eb53ea57d678ab6eaff2c2acd16a2f822f9ddce821279
```
=> Save cached blocks to db during phase 2 of initial sync

shared/prometheus/BUILD.bazel, shared/prometheus/service.go, shared/prometheus/service_test.go, shared/service_registry.go, validator/client/service.go, validator/node/node.go
The validator log is a little chatty, especially at startup.  This results in potentially important messages being missed by users.
This patch reduces the severity of some log messages that aren't relevant to end users, and cuts down on the number of messages that are emitted by prometheus when the monitoring port is already in use.
Sample startup before this patch:
```
[2020-04-04 16:56:22]  INFO flags: Using custom chain parameters config=demo
[2020-04-04 16:56:23]  INFO node: Found validator keys validators=1
[2020-04-04 16:56:23]  INFO node: Validating for public key pubKey=0xa551e2558c839162b5df961ceb27cd10e9cf711ac15ff7866143cbf6df5fe523e5c3c91fdfa95f47e20b9499ee5766fc
[2020-04-04 16:56:23]  INFO node: Starting validator node version=Prysm/Git commit: …
```
=> Reduce noise in validator logs

beacon-chain/sync/initial-sync-old/round_robin.go
"Round robin**g** sync request failed"
changed to
"Round robin sync request failed"
TODO(you): choose "part of" or "resolves" and the associated github issue #.
[Part of|Resolves] #531 
---
=> Fixed typo in stdout log

beacon-chain/blockchain/service.go
Caught this edge case in v0.11, with the latest features, if the head or finalized state is 0, a node should still properly initialize rest of the components in chain service
=> Initialize chain service properly if head slot is 0

validator/client/validator_attest.go, validator/client/validator_propose.go, validator/db/attestation_history.go, validator/db/attestation_history_test.go, validator/db/db.go, validator/db/proposal_history.go
This change removes a bottleneck for starting a validator client by no longer creating N validator DB transactions upon launch. Instead of preloading default values into the DB, it will return default values if the DB is empty.  
Also removes a wasteful db call for both attesting and proposing
=> Change attester protection to return default if DB is empty

.buildkite-bazelrc, BUILD.bazel, beacon-chain/BUILD.bazel, tools/go_image.bzl, validator/BUILD.bazel
These binary targets are no longer supported since adding cross compile toolchains.
=> Remove old cross compile starlark rules

validator/client/BUILD.bazel, validator/client/service.go, validator/client/validator.go, validator/client/validator_aggregate.go, validator/client/validator_propose_test.go
Given our beacon node aggregate attestations on demand in v0.11, a single validator client (VC) could multiple keys that have duplicated assignment for aggregator for the same committee and the same slot. There's no reason for VC to produce duplicated `AggregateAndProof` request which would result in the same proof signature while there's no reward for aggregating. 
Also the gossip network would try to supress the duplicated `AggregateAndProof`. Confirmed with Adrian from Teku and Paul from Lighthouse that's their design as well. 
We are getting such a performance improvement from this radical change! 
Before bottlenecks:
After bottlenecks:
=> Avoid duplicated aggregation request

beacon-chain/p2p/interfaces.go, beacon-chain/p2p/sender.go, beacon-chain/p2p/service.go, beacon-chain/p2p/testing/p2p.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/service.go, beacon-chain/sync/subscriber_committee_index_beacon_attestation.go
=> Networking Fixes

beacon-chain/operations/attestations/kv/BUILD.bazel, beacon-chain/operations/attestations/kv/aggregated.go, beacon-chain/operations/attestations/kv/aggregated_test.go, beacon-chain/operations/attestations/pool.go, beacon-chain/operations/attestations/prepare_forkchoice.go, beacon-chain/operations/attestations/prepare_forkchoice_test.go, beacon-chain/rpc/validator/aggregator.go, beacon-chain/rpc/validator/proposer.go
With the newly introduced aggregation on demand feature in v0.11, one of the major wasted compute is duplicated aggregating of unaggregated attestations.  In Prysm beacon node, aggregation of unaggregated attestations happens twice per slot. Once during fork choice and once during aggregator request via RPC. 
Before:
There's no reason to aggregate twice. This PR efficiently eliminates the second duplication of aggregation
After:
=> More efficient aggregation on demand

beacon-chain/p2p/service.go
No tracking issue. Given the nodes cannot peer until there is a genesis time, we return a healthy status if the chain is pre-genesis in the p2p service Status() function for healthz checks.
=> Return Nil Error if Pre-Genesis in P2P Service Healthz Check

beacon-chain/flags/base.go, beacon-chain/flags/config.go, beacon-chain/main.go, beacon-chain/node/node.go, beacon-chain/p2p/config.go, beacon-chain/p2p/service.go, beacon-chain/usage.go, shared/featureconfig/flags.go
This makes discoveryV5 the default method of discovery in Prysm, and adds in a flag to disable it
=> Release DiscoveryV5 for Testnet Restart

beacon-chain/sync/BUILD.bazel, beacon-chain/sync/service.go, beacon-chain/sync/service_test.go
=> Fix Overflow in Status Check

beacon-chain/core/blocks/block_operations.go
To calculate domain for `ProposerSlashing`,  it's suppose to use `header.Slot` coverts to epoch, not the start slot of the `header.Slot` which turned out to be `header.Slot * 32`
=> Fix incorrect proposer slashing domain calculation

.github/no-response.yml
This bot will automatically close issues where we don't have enough information to proceed and the author has not responded in 14 days.
Use the label `Need-Info` to activate this process.
=> Add probot no-response configuration

beacon-chain/blockchain/process_attestation.go
Resolves #5359.
There is no need to reject attestations for fork choice if they arrive before their next slot.
=> Remove next slot requirement for processing attestations

shared/featureconfig/config.go, shared/featureconfig/flags.go
This is now running in prod after fixing race conditions in #5364 and the flag is now considered safe to use. :tada: 
This flag gives a very noticeable improvement in getBlock latency stability with 99 percentile under 2.5s. 
(Red line indicates when the flag was flipped)
=> Set ssz cache enabled by default

beacon-chain/archiver/service_test.go, beacon-chain/core/validators/validator.go, beacon-chain/core/validators/validator_test.go, beacon-chain/rpc/beacon/validators_test.go
`ActivatedValidatorIndices` was incorrectly implemented, it should be the following and not use `delayedActivationEpoch`  I think this came from the old spec
```python
validator.activation_epoch <= epoch < validator.exit_epoch
```
=> Fixed a bug in ActivatedValidatorIndices

beacon-chain/state/stategen/cold.go, beacon-chain/state/stategen/cold_test.go, beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/hot.go, beacon-chain/state/stategen/replay.go, beacon-chain/state/stategen/replay_test.go
This PR revamps cold state getters for new state service. 
Change list:
- Modified cold state getters to use `ComputeStateUpToSlot` instead of archived points
- Added a nice helper `recoverStateSummary`
- Added a few short circuits for slot 0 conditions for efficiency 
- Updated tests
=> State service clean up - better cold state getter

beacon-chain/p2p/service.go, beacon-chain/sync/BUILD.bazel, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_committee_index_beacon_attestation_test.go, endtoend/components/beacon_node.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
---
This PR fixes e2e tests for v0.11 and enables attestation committee subnets by default. It increases the refresh rate for node ENRs to twice per slot for a good tolerance necessary to pass tests.
=> Pass E2E Tests for v0.11 and Enable Attestation Subnets By Default

beacon-chain/core/blocks/block_operations.go, beacon-chain/core/blocks/eth1_data_test.go, beacon-chain/rpc/validator/proposer.go
This PR resolves a bug introduced in https://github.com/prysmaticlabs/prysm/commit/ec614578eeaa46e95d5bbe1dad9942cf422c7409 for `eth1data`, it would return the wrong starting time for the Eth1VotingPeriod resulting in no eth1 vote getting enough support and no deposits being processed.
Also cleans up the tests to make sure they're properly working.
=> Fix eth1data on v0.11

beacon-chain/db/iface/interface.go, beacon-chain/db/kafka/passthrough.go, beacon-chain/db/kv/check_historical_state.go, beacon-chain/db/kv/kv.go, beacon-chain/node/node.go
With the testnet restart, there's a UX friction when `--clear-db` or `--force-clear-db` is defined on the existing DB used in previous testnet. This PR solves the UX friction by moving `HistoricalStatesDeleted` to `startDB`
=> Verify historical states exist in node pkg

beacon-chain/flags/base.go, beacon-chain/p2p/broadcaster.go, beacon-chain/p2p/broadcaster_test.go, beacon-chain/p2p/encoder/network_encoding.go, beacon-chain/p2p/encoder/ssz.go, beacon-chain/p2p/encoder/ssz_test.go, beacon-chain/p2p/testing/p2p.go, beacon-chain/sync/decode_pubsub.go, shared/cmd/flags.go
Previously the network encoder defaulted to framed snappy encoding for both rpc and gossip messages. This PR clearly separates it so that rpc messages use framed snappy encoding and gossip messages use snappy block encoding
=> Fix Network Encoder

beacon-chain/powchain/log_processing.go
If the beacon chain detects a duplicate deposit prior to chainstart it warns of this fact, but the log message as-is prints out the hex value of a text string.
This patch changes the log messages so it prints out the full validator key as a log field, congruent with the message format used for deposits that are included.
=> Fix bad log messages for duplicate deposits

beacon-chain/p2p/peers/status.go, beacon-chain/p2p/service.go
=> Fix Panics in P2P Service

beacon-chain/core/blocks/block_operations.go
It's ok to drop this to debug since there's no error in the codebase or impact on the node/chain operaiton
=> Use debug for `Skipping deposit...` log

beacon-chain/blockchain/process_attestation.go, beacon-chain/blockchain/process_attestation_test.go
Resolves #5427
The issue itself (checking for nil) was resolved in https://github.com/prysmaticlabs/prysm/pull/5127 by Terence, this PR just adds necessary regression tests + minor refactoring to check for nil values a bit earlier in the function.
=> nil attestation tests added

.github/workflows/dappnode-release-trigger.yml
This PR adds a workflow that launches a trigger every time that a new release is tagged.
The trigger automates the creation of a new release in our repositories by generating a new DAppNodePacakge with your last release, making easier for us to maintain the package updated on our side.
=> Added dappnode-release-trigger.yml workflow

shared/cmd/flags.go
We have a new discv5 bootnode running in a standalone ec2 instance.
The node is on IP 18.223.219.100 and serving from UDP port 4000.
=> Add default bootnode for discv5

prysm.sh
This PR changes the prysm.sh script to support executing windows binaries, as previously it did not work on windows.
Instructions for use on windows through command prompt would be `.\prysm.sh beacon-chain`
=> Change prysm script to support windows

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
This fixes #5477 
Added `beaconDB.HasBlock` to `verifyBlkPreState` check. This fixed an edge case that request parent blocks syncing at time epoch 0 encountered
The alternative work around is to always `--force-clear-db` when syncing and the chain is before epoch 1
=> Add `HasBlock` to verify parent check

beacon-chain/blockchain/process_attestation_test.go, beacon-chain/state/stategen/hot.go, beacon-chain/state/stategen/hot_test.go
Radical improvement from #5466. Refactored the recursive lookup of parent state into its own method `lastAncestorState` instead of recursively calling `loadHotStateByRoot`
Tested with the bad DB to verify it works and tested with unit test.
Note: We don't have to merge this before Topez genesis, but we should be merging it soon after genesis. Perhaps 20 finalized epochs
=> Retrieve last ancestor state from DB. (Radical improvement from 5466)

tools/bootnode/BUILD.bazel, tools/bootnode/bootnode.go
This fixes some changes introduced in #5469. Only setting fallback ip,ports.
=> Fix Bootnode Again

beacon-chain/BUILD.bazel, beacon-chain/main.go
We allow geth logging to be enabled for discoveryV5 in `trace` .
=> Add Geth Logging

prysm.sh
This PR fixes me accidentally breaking ARM support (sorry Pi users!).
=> Fix prysm.sh for arm64

beacon-chain/rpc/beacon/BUILD.bazel, beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
This PR added back archival end point `GetValidatorParticipation` with a proper fallback when `--disable-new-state-mgmt` is applied
The PR cherry picked #5409 was already approved and the fallback logic was already used in the wild. There's no new logic and nothing substantive here.
Tested first 35 epochs:
=> Add back archival endpoint `ValidatorParticipation` with fallback

prysm.sh
This is to avoid github rate limiting which many users have experienced. 
I'm planning to follow up on this with a PR that verifies the signatures as well.
=> Update prysm.sh to use prysmaticlabs.com/releases

validator/client/validator_metrics.go
Several user reported issues where the success metrics were on the scale of 0 to 1 when they should be on the scale of 0 to 100. This PR multiplies the previous value by 100 to the appropriate scale.
=> Validator: fix percentages to be per 100

beacon-chain/rpc/beacon/BUILD.bazel, beacon-chain/rpc/beacon/attestations_test.go, beacon-chain/rpc/beacon/committees.go, beacon-chain/rpc/beacon/committees_test.go
This PR added back archival end point `ListBeaconCommittees` with a proper fallback when `--disable-new-state-mgmt` is applied
The PR cherry picked #5411 was already approved and the fallback logic was already used in the wild. There's no new logic and nothing substantive here.
Tested first 100 epochs:
=> Add back archival endpoint `ListBeaconCommittees` with fallback

beacon-chain/sync/initial-sync-old/service.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/service.go
Adds a cancel field for the context cancel function, so that we can release our sync services properly.
=> Cancel Initial Sync Properly

beacon-chain/rpc/beacon/slashings.go, slasher/detection/service.go
[Resolves] #5531
---
writes latest detected head every epoch and not just at historic detection end
=> Fix slasher historic attestation detection

shared/featureconfig/config.go, shared/featureconfig/flags.go
Resolves #5270
- Adds `--dev` flag to beacon node.
- Currently, it will enable: `--enable-state-ref-copy`, `--enable-state-field-trie`, `--enable-byte-mempool`
=> add --dev flag

beacon-chain/blockchain/process_block_helpers.go
This fixes #5395
Log warn instead of return err if state deletion fails
Noted this code path is only for `--diable-new-state-mgmt` so almost no risk for current master
=> Log warn instead of return error 

beacon-chain/rpc/beacon/attestations.go, beacon-chain/rpc/beacon/attestations_test.go
This PR changes ListIndexedAttestations to convert attestations using the target root, instead of using the block root which requires a new state generated for every slot.
=> Change ListIndexedAttestations to convert attestations from target root

WORKSPACE
This resolves the panic in #5513 by updating to a patched commit in our geth fork.
=> Fix Panic in Discv5

WORKSPACE, beacon-chain/rpc/beacon/attestations_test.go, shared/featureconfig/config.go
Problem: `bazel test //beacon-chain/rpc/beacon:go_default_test` results in the following:
This PR resolves it.
=> fix tests in //beacon-chain/rpc/beacon

beacon-chain/state/stategen/cold.go, beacon-chain/state/stategen/cold_test.go, beacon-chain/state/stategen/migrate.go
This fixes #5555 
When there's a finalized check point, a node enters in a migration phase to delete states that's not on the archival point.  In previous iteration, a node will regenerate the state if the state does not exist on the migration point but that quickly becomes too buggy as the underlying block may not exist as well.
This PR went with the simpler approach to only preserve the state that is on the archival point.
=> Continue if archival state is not in DB

WORKSPACE, shared/prometheus/BUILD.bazel, shared/prometheus/content_negotiation.go, shared/prometheus/service.go, shared/prometheus/service_test.go
Resolves #5546 
- Extends `/healthz` to accept JSON as preferred output.
- By default `text/plain` context type is used, however, when JSON is accepted as response (that's when `Accept: application/json, */*;q=0.5` header is sent), output is JSON:
```json
{
"data": [
{
"error": "",
"service": "*attestations.Service",
"status": true
},
{
"error": "",
"service": "*powchain.Service",
"status": true
}
],
"error": ""
}
```
- Fixes the response code as well. [Previously](https://github.com/prysmaticlabs/prysm/blob/19b879ec17b0f73cc8f9ec5d836d1b061db638d1/shared/prometheus/service.go#L79) whenever some service was down HTTP 500 error was returned, this is **incorrect** use of the code (that code is suitable for situations when server cannot complete request due to some problem, in our case …
=> /healthz endpoint accepts JSON now

beacon-chain/powchain/service.go
Resolves #5433 
- IPC path normally has `.ipc` extension, so suffix should be checked, but we check prefix (which is ok when it comes to web-sockets, which *start* with `ws://`)
=> fixes issue with ipc path checking

prysm.sh
- When running `prysm.sh validator accounts create` I got strange sequence of chars:
- The problem is that we are concatenating array and string (see https://github.com/koalaman/shellcheck/wiki/SC2145 for more details), so this tiny PR fixes it:
=> fixes param concatenation

beacon-chain/rpc/validator/proposer.go, beacon-chain/rpc/validator/proposer_test.go
This PR returns a random eth1data vote if the node has an issue retrieving data from eth1 in a timely manner.
Resolves #5521
=> Add a 2 second timeout to fetching eth1data

validator/accounts/account.go, validator/keymanager/direct_keystore.go
Resolves #5438 
- decouples password and keystore path processing logic (previously we had a bug where on empty `--password` flag, keystore path input was expected from user too - even when `--keystore-path` is provided)
- moves `DefaultValidatorDir()` to accounts processing, and allows keystore manager to access it to. Effectively, now it is not required to provide path at all - as it will default to OS-specific one and will be used in both account creation and validator node running
- once this PR is merged, it is advised to cut a new release (so that `prysm.sh` works) and merge (and publish) https://github.com/prysmaticlabs/prysm-testnet-site/pull/117
With this PR, when new validator account creation is requested, it features default path:
=> feature default validator keystore path

validator/client/validator.go, validator/client/validator_test.go
This PR gets rid of a case where a validator is in the state, past the DEPOSITED state, but still not assigned a ActivationEpoch. I misunderstood how the activation process works.
=> Fix activationEpoch=FarFutureEpoch in validator client logging

validator/client/validator_metrics.go
This PR turns all percentage logs in the validator into actual percentages, confirmed in runtime to work.
=> Fix percentages for validator metric logging

beacon-chain/db/kv/regen_historical_states.go
This PR fixes #5611.  It has no impact to beacon node run time, it only impacts the duration when beacon node is generating and saving historical states. It's 8 mins given current chain length
Change list:
* Increased cache size from 64 to 80 with rationale
* Garbage collect at the end of `regenHistoricalStates`
=> Increase regen historical state cache size

prysm.sh
Feature
- fixes formatting (we had 6 spaces, 2 spaces, 4 spaces as indents - now, it is 4 spaces everywhere, I've used Golands default shell script formatter).
- adds `--download-only` option, so that `./prysm.sh beacon-chain --download-only` or `./prysm.sh validator --download-only`, checks for updated version, downloads and verifies it, and stops on that - w/o starting (beacon/validator/slasher) node.
Fixes #5580
- I've considered implementing it as `./prysm.sh update`, which would update all the binaries, but it didn't seem to be the most flexible way. With `--download-only` flag we can update any binary (or all three `./prysm beacon-chain …
=> prysm.sh download only option

prysm.sh
Bug fix
- checks args size before working with args themselves
Fixes #5633 
=> checks prysm.sh args size

validator/accounts/account.go
Usability
If you run a validator with `--keystore-path` it still asks you for a keystore path. 
This PR improves usability in two ways:
1. It does not ask you to confirm the path if you already specified one.
2. It clarifies the wording that user interaction is necessary (_"Please specify ..."_).
N/A
As discussed on Discord with  @nisdas
=> validator/accounts: don't ask for keystore path if specified

endtoend/endtoend_test.go
Bug fix
This PR solves an issue for the long running E2E where the bootnode process would not be terminated and conflict with any other tests on that shard. This changes E2E to terminate it with everything else.
=> Terminate bootnode after E2E test completion

WORKSPACE
Other
Updates protobuf, skylib, rules_go, grpc-gateway.
Part of #5651 
This PR allows for the requests outlined in #5651 to work if the parameters are properly URL encoded. I'm not marking that issue as "fixed" because this is different behavior from our envoy production implementation of https://api.prylabs.net
=> Update protobuf, skylib, rules_go, grpc-gateway dependencies

beacon-chain/rpc/validator/attester.go, beacon-chain/rpc/validator/attester_test.go
> Feature
In the event of head slot > request slot, the node starts fetching ancestor head root recursively until the condition satisfies. Every slot is a DB look up. 
Instead, we can use `helpers.BlockRootAtSlot(headState, req.Slot)` to limit the DB look up to just one time.
Could be relevant to #5665 
Tested with my 3k validators with both `enable-new-state-mgmt` on and off
=> More efficient ancestor head retrieval for `GetAttestationData`

beacon-chain/db/kv/regen_historical_states.go, beacon-chain/node/node.go
> Bug fix
We were confusing the usage of the cli context with a regular context used by the beacon node in many different services. So when we would attempt to stop the beacon node process while it was doing some expensive operation, such as regenerating historical states, the node would not stop as it would not be able to understand the root context had been canceled. This PR simplifies the code and ensures we have a global, single ctx for the beacon node in node/node.go which is propagated down to all running services.
This PR also adds a check for ctx.Err() on each iteration of regenerating historical states, which is an expensive operation.
Fixes #5470
=> Ensure Single Context Used for Beacon Node Cancelation on SIGTERM

validator/client/validator_attest.go, validator/client/validator_attest_test.go
> Bug fix
Sometimes due to a node disconnection or other timing-related issue, we get an empty duty with an empty committee when a validator attempts to attest. Instead of logging a scary error of `[2020-04-17 20:00:05] ERROR validator: Validator ID 0 not found in committee of [] pubKey=0xb4cffec577dd slot=0`, we emit a debug-level log that a received committee was empty in the duty value and exit the function early.
Fixes #5481
=> Empty Committee Check in Submit Attestation

beacon-chain/sync/validate_aggregate_proof.go
> Bug fix
Remove one duplicated aggregated attestation signature verification. Get back 10ms 
Fixes #5670
=> Remove duplicated sig verification

beacon-chain/blockchain/log.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/receive_block.go, beacon-chain/sync/initial-sync/BUILD.bazel, beacon-chain/sync/initial-sync/round_robin.go, beacon-chain/sync/pending_blocks_queue.go
Feature
This PR augments sync logs with some additional information that helps identifying the best block and epoch without increasing verbosity but also by avoiding too much log spam.
This PR is the sister of https://github.com/sigp/lighthouse/pull/1084
N/A
Initial Sync:
New Blocks Received:
=> beacon/log: augment logs with block roots

shared/featureconfig/config.go, shared/featureconfig/flags.go, shared/params/config.go, validator/main.go
Feature
This provides a config that modifies a mainnet spec according to the Schlesi testnet variables.
This allows users to run a Prysm node on Schlesi without patching the client by just providing `--schlesi-testnet` instead.
N/A
I will personally commit to keep this updated.
Schlesi does not work on master, so I'll submit this PR to v0.12.
As a follow-up to this, in future, it would be nice to have some kind of abstraction for chain specifications that also would allow for more flexibility also regarding other options such as bootnodes or deposit contract etc.
=> [v0.12] Add Schlesi Testnet Preset

beacon-chain/sync/subscriber.go
Bug Fix
We were incorrectly formatting the topic when de-registering it, which caused us to unregister 
a non existent topic. This is fixed with the correct formatting. 
Resolves #5564 
Changes the subscription cancel error to a warning log, as the error is expected 
and not really a failure condition.
=> Fix Topic Validator Deregistering Bug

beacon-chain/rpc/validator/exit.go, beacon-chain/rpc/validator/exit_test.go
Bug Fix
It prevents the rpc server from panicking if it receives an invalid exit proposal. It checks that 
the exit object exists and that the signature is valid.
A regression test has also been added
N.A
=> Fix Voluntary Exits Panic

beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_test.go
This PR improves subnet subscriptions for aggregators. Previously we did not subscribe 
if we could not find a relevant peer. However this is resolved by subscribing to the 
subnet at all times and then searching for the peer. 
This also adds in a regression test for #5683 .
N.A 
=> Clean Up Of Dynamic Subscriptions

shared/keystore/key.go, shared/keystore/key_test.go, shared/keystore/keystore.go, shared/keystore/keystore_test.go
Other
- minor fixes of issues discovered when implementing #5679 
N/A
This PR:
- makes naming consistent
- removes unused code
- fixes incorrect temp data teardown in tests (temp files were removed at the end of the functions, and `t.Fatalf()` were used in code - so on error teardown never occured, thus making running tests non-idempotent operation)
- also temp directory used wasn't assuming tests can be run concurrently/sharded
=> shared/keystore: cleanup

prysm.bat
=> replaced 265 with 256 ...derp

beacon-chain/core/blocks/block_operations.go, beacon-chain/core/helpers/BUILD.bazel, beacon-chain/core/helpers/signing_root.go, beacon-chain/core/helpers/signing_root_test.go, beacon-chain/state/stateutil/blocks.go
When using the default ComputeSigningRoot Method we use the 
generic ssz library which is very inefficient. This PR , refactors out the method 
so that we can utilise any custom hashing methods.
Also add in a basic regression test so that we ensure basic compatibility. 
N.A
N.A
=> Custom Method For Block Signing Root

beacon-chain/db/kv/regen_historical_states.go
> Bug fix
To regenerate and save historical state, the current behavior is it won't save the historical state on the archived slot if that archived slot is a skip slot. This behavior is obviously not ideal. See: 
(slot 256, 768.. and more are skipped)
After the fix:
Fixes #5711
Tested run time 👌
=> Regen historical state: don't skip saving historical state

beacon-chain/blockchain/receive_attestation.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/sync/validate_aggregate_proof.go
> Feature
This reduces beacon node's memory usage by a good 30%. Instead of using head state + copy to validate `beacon_aggregate_and_proof`, it uses cached check point state to validate.
Before:
After:
Fixes #5736
=> Use cached state to validate `beacon_aggregate_and_proof`

prysm.sh
Other
- Fixes a bug: when incorrect process name was used, process didn't exit properly
- Adds more explicit error message, where it mentions what process has been called - helps us debugging as well:
Fixes #5735
=> More explicit error message on wrong process when running prysm.sh

README.md
Update to spec v0.11.2 badge with #5655 is likely done and in [alpha.6](https://github.com/prysmaticlabs/prysm/releases/tag/v1.0.0-alpha.6)
=> Update to v0.11.2 badge

validator/main.go, validator/node/BUILD.bazel, validator/node/node.go, validator/usage.go
Follow-up to #5694, this adds the same functionality of loading a custom config from a file to the validator client
=> Add Chain Config File for Validator 

shared/bls/bls.go, third_party/herumi/herumi.bzl
Other
SetETHmode(1) was not clear enough for us to understand what draft of BLS we were targeting in Prysm.
N/A - Minor fix, no tracking issue.
https://github.com/herumi/bls-eth-go-binary/pull/15 is out for review as well. We can update BLS again once that merges.
=> Update BLS and use constant for SetETHmode

beacon-chain/core/blocks/block_operations.go, beacon-chain/core/blocks/block_operations_fuzz_test.go, beacon-chain/core/blocks/block_operations_test.go, beacon-chain/core/epoch/epoch_processing.go, beacon-chain/core/helpers/validators.go, beacon-chain/core/helpers/validators_test.go, beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/validator/exit.go, beacon-chain/state/getters.go, beacon-chain/sync/validate_voluntary_exit.go
Optimization
This PR is me going through the beacon chain client and making sure any non-mutating usages of `ValidatorAtIndex` are changed to `ValidatorAtIndexReadOnly`. This reduces memory usage by making sure the full validator isn't fully copied into memory for every usage, and also protects functions that shouldn't mutate from doing so :)
Also adds `IsSlashableValidatorUsingTrie`, and modifies `VerifyExit`.
=> Change non-mutating validator accesses to ReadOnly

beacon-chain/core/blocks/block_operations.go, beacon-chain/state/setters.go
Code Cleanup
Refactor to only append validators and internally add pubkeys to our validator index map. ~This makes each map track the validator field as its 'reference'~. We only copy the whole map once per deposit, so as to reduce the time spent of map copies.
Part of #5779
=> Don't Copy The Whole Validator Map each time

shared/featureconfig/flags.go
Over the last few days, e2e test has grown more flakey with `--enable-new-state-mgmt` flag. I need time to investigate why. In this mean time, disabling it to unblock regular flow
=> Temporarily remove new state mgmt from e2e

beacon-chain/p2p/discovery.go
Bug Fix
Currently if we have a public ip specified, we will still use the endpoint predictor
to update our IP address. In the event we are peered with more local nodes vs 
external nodes, we might end up reverting back to our internal ip address. This 
instead makes our IPs static
N.A
Fixes #
N.A
cc @jrhea
=> Make IP Static for Public IPs

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/receive_block.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/rpc/validator/proposer.go, beacon-chain/sync/initial-sync/blocks_queue_test.go, beacon-chain/sync/initial-sync/round_robin.go, beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/subscriber_beacon_blocks.go
Other
The critical path for ProposeBlock required calling HashTreeRoot ~three~ four times for a beacon block.
Additionally, receiving a block from pubsub would call HashTreeRoot twice, at least. 
N/A - super small
=> Refactor ReceiveBlock to receive the block root.

beacon-chain/sync/initial-sync/BUILD.bazel
Other
Adds second target for codecov to analyze code coverage. This is necessary since the coverage collector 
We are excluding race enabled tests from coverage since it causes issues. We don't have a great way to disable it, see https://github.com/bazelbuild/rules_go/issues/1875
=> Duplicate init sync test target for better coverage reporting

beacon-chain/main.go, beacon-chain/node/node.go, beacon-chain/p2p/config.go, beacon-chain/p2p/options.go, beacon-chain/p2p/options_test.go, beacon-chain/usage.go, shared/cmd/flags.go
Bug Fix 
This adds the ability for the beacon node to restrict outbound dials to undesirable ip ranges. Partially helps with #5663. This is a patch for users, so that they do not have to mess around and configure with `ufw` or `iptables` to prevent dials to internal ips.
#5663
N.A
=> Add Ability to Restrict Outbound Dials

beacon-chain/sync/initial-sync/initial_sync_test.go, beacon-chain/sync/initial-sync/round_robin_test.go
Refactoring
- moves common method (used by all init-sync tests) `connectPeers()` method out of `round_robin_test` to `initial_sync_test` (where all other setup/teardown methods live)
=> Moves connectPeers to common test setup file

beacon-chain/rpc/beacon/BUILD.bazel, beacon-chain/rpc/beacon/server.go, beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go, beacon-chain/rpc/service.go
> Bug fix
When a beacon node is syncing, `GetValidatorPerformance` should return Unavailable upon request. `GetValidatorPerformance` requires the beacon node to be on head since it computes validator performances at the most current time
Part fix for #5746 
Tested it with my local node and validators syncing with Topaz testnet
=> `GetValidatorPerformance` return `Unavailable` when syncing

beacon-chain/rpc/validator/proposer.go
Feature
This is a short cut to exit the deposits routine of GetBlock, if there are no pending deposits. 
Part of #5801
=> Check for pending deposits and exit early, if possible

beacon-chain/p2p/handshake.go
Follows on from #5779 with a minor fix by checking for the zero value of the time struct.
=> Check for Zero Value 

beacon-chain/blockchain/metrics.go, beacon-chain/blockchain/process_block.go
Feature
This PR adds monitoring around attestation inclusion delay. Ideally, all attestations would be included in a block 1 slot after their creation. 
After a few minutes:
```
attestation_inclusion_delay_slots_bucket{le="1"} 469
attestation_inclusion_delay_slots_bucket{le="2"} 599
attestation_inclusion_delay_slots_bucket{le="3"} 669
attestation_inclusion_delay_slots_bucket{le="4"} 702
attestation_inclusion_delay_slots_bucket{le="6"} 721
attestation_inclusion_delay_slots_bucket{le="32"} 1405
attestation_inclusion_delay_slots_bucket{le="64"} 1405
attestation_inclusion_delay_slots_bucket{le="+Inf"} 1405
attestation_inclusion_delay_slots_sum 16402
```
N/A
=> Add attestation inclusion histogram

beacon-chain/flags/base.go, beacon-chain/flags/config.go, beacon-chain/main.go, beacon-chain/sync/service.go, beacon-chain/usage.go
I am working on optimizing init-sync, and want to use whole bandwidth available. So, need to know preferred block batch size and burst factor. In order not to use magic constant in second place (inside of `initialsync` package), new flag is introduced.
=> Adds BlockBatchLimitBurstFactor flag

beacon-chain/rpc/beacon/attestations.go, slasher/beaconclient/receivers.go, slasher/detection/service.go
Bug fix
This PR is a few fixes made after my observations on my running slasher. The main fixes made are:
* Unretrievable committees no longer break detection
* Historical detection did not update the spans whatsoever, now they are updated and detection is reliable.
=> Fix historical detection for the slasher

beacon-chain/core/helpers/committee.go
> Feature
Committee cache checks if the key already exists in cache before updating the cache, but `ShuffledIndices` was placed before the check so it would just shuffle the indices regardless key exists. The extra shuffle was observed in flame during initial syncing. 
Before the fix (shuffle twice per 2 epochs):
After the fix(shuffle once per 2 epochs) :
It may not seem a lot (3% saving in profile) but it resulted in 15% faster initial syncing time!
Fixes #5840 
Tested syncing from genesis to head
=> Remove extra committee shuffling for initial syncing

beacon-chain/blockchain/process_attestation.go, beacon-chain/blockchain/receive_attestation.go
> Feature
Align process attestation with spec. Don't process fork choice attestation until the subsequent slot
Fixes #5385
=> Delay atts until subsequent slot

beacon-chain/db/kv/regen_historical_states.go
> Bug fix
Use proper getters to retrieve last archived state instead of `HighestSlotStatesBelow`
Fixes #5843 
Regen and save from genesis to latest head 🆗
=> Regen historical using `ArchivedPointRoot` then `State`

beacon-chain/p2p/service.go, beacon-chain/p2p/subnets_test.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/rpc_ping.go, beacon-chain/sync/rpc_status.go
Code Cleanup
This PR increases the number of allowed faults from a peer to 5. Given that the network is much larger now, it would make sense to have a larger allowance for peer faults. Also removes us marking a peer as bad in some occasions. 
=> Allow a Larger Allowance for Peer Faults

beacon-chain/sync/BUILD.bazel, beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/rpc_beacon_blocks_by_range_test.go, beacon-chain/sync/sync_test.go
Bug fix
- Fixes issue when rate limiting was too aggressive, depleting capacity excessively
- Improves speed of test (15s -> 5s), but setting up database for blocks used in tests only (not all blocks in range)
Issue located when working on `init-sync` optimizations, and fix was found immediately - so no corresponding issue opened.
We had several issues:
- Rate limiter's capacity was decreased even before any block streaming occurred - which is unfair, as before blocks are streamed, we can't count them. It is correct to check if limits are exceeded **before** sending anything, but updating capacity should occur after the streaming.
- **More …
=> Fixes bug with excessive rate limiting

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/receive_block.go
Code Improvement
We process all blocks that we receive in sync whether we have processed them before or not. This caused issues in schlesi, when other clients returned duplicate blocks to us. Due to certain optimizations we have made in sync, processing the same block twice, leads us to regenerating the prestate, which is expensive. 
N.A
N.A
=> Check Whether Block Is Already Processed

beacon-chain/sync/error.go, beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/rpc_goodbye_test.go, beacon-chain/sync/rpc_status.go, beacon-chain/sync/rpc_status_test.go
Bug Fix
Currently we abruptly disconnect with a peer upon finding out that they are of a different fork. The correct way would be to send them our corresponding status and send them a correct goodbye message and then disconnect with them.
Fixes #5740
=> Return Status And Goodbye for Different Fork Digests

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/receive_block.go
Reverts prysmaticlabs/prysm#5850
Per discussion with @nisdas and @farazdagi , we have concluded that it would be more complicated to satisfy this for `new-state-mgmt`, and it would make more sense to check this in initial sync and remove duplicated blocks from the syncing queue
=> Revert "Check Whether Block Is Already Processed"

beacon-chain/powchain/block_reader.go, beacon-chain/powchain/block_reader_test.go
This reverts commit 159ef3d70260bc2678f68c01861b643cdabf8356.
PR reversion
This was causing issues in schlesi with some bad entries in the cache causing 
us to vote for a non existent eth1 block.
N.A
N.A
=> Revert "Add cache to Eth1 RPC functions (#5347)"

beacon-chain/blockchain/info.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/service.go, beacon-chain/forkchoice/interfaces.go, beacon-chain/forkchoice/protoarray/ffg_update_test.go, beacon-chain/forkchoice/protoarray/no_vote_test.go, beacon-chain/forkchoice/protoarray/nodes.go, beacon-chain/forkchoice/protoarray/nodes_test.go, beacon-chain/forkchoice/protoarray/store.go, beacon-chain/forkchoice/protoarray/types.go, beacon-chain/forkchoice/protoarray/vote_test.go
Made the following enhancements to block tree viewer (http://localhost:8080/tree)
Change list:
- Removed index field. Proposers don't care which index the block is in the proto array. This info was too low level
- Removed best descendent field. Proposers don't care the index of the best descendent and the best descendent can be seen as green
- Added graffiti field. It makes it easier to debug whose proposers submitted the forked blocks. Super useful to debug multi client testnet. If we agree this is too verbose, we also can remove it before mainnet.
=> Enhancing block tree viewer

beacon-chain/flags/base.go, beacon-chain/node/node.go, beacon-chain/usage.go, shared/params/config.go
> Feature
Change list:
* Set default `SlotsPerArchivedPoint` to 2048 to align with LH
* Make `SlotsPerArchivedPoint` configurable via flag `--slots-per-archive-point`
=> Make `SlotsPerArchivedPoint` configurable

beacon-chain/sync/deadlines.go, beacon-chain/sync/rpc_ping.go
Logging Improvement
Shifts a few errors to debug to stop them from polluting the beacon node.
=> Shift To Debug Logs

shared/featureconfig/flags.go, validator/flags/flags.go, validator/main.go, validator/node/node.go, validator/usage.go
Feature
Users have experienced issues where they expected account level metrics to be present in the Prometheus scraped data, but realized this data was only available with --enable-account-metrics. This PR inverts that flag, making the account metrics enabled by default. 
Fixes #5883
=> Enable validator account metrics by default

beacon-chain/rpc/validator/assignments.go, beacon-chain/rpc/validator/assignments_test.go
> Bug fix
As a follow-up to #5849, we are seeing significant problems in the Topaz testnet due to a discrepancy in how duties are computed and sent to the validator client. The server implementation was doing:
```go
func (vs *Server) GetDuties(ctx context.Context, req *ethpb.DutiesRequest) (*ethpb.DutiesResponse, error) {
if vs.SyncChecker.Syncing() {
return nil, status.Error(codes.Unavailable, "Syncing to latest head, not ready to respond")
}
// If we are post-genesis time, then set the current epoch to
// the number epochs since the genesis time, otherwise 0 by default.
genesisTime := vs.GenesisTimeFetcher.GenesisTime()
var currentEpoch uint64
if roughtime.Now().After(genesisTime) {
currentEpoch = …
```
=> Ensure We Use Request.Epoch in the Validator Duties Server Implementation

beacon-chain/p2p/service.go
Resolves #5896 
Shifts the errors to debug logs
=> Change To Debug Logs

shared/featureconfig/config.go, shared/featureconfig/flags.go
Feature
This reduces the number of calls between the beacon node and validator.
Fixes #5680
=> Enable domain data cache by default

beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
> Bug fix
If the participation info of an epoch is not yet available (ie due to skip blocks, node processes epoch based on new block, not based on time), the node should return an `unavailable` error, instead of return new struct with all fields initialized to 0s. This has been confusing to many users, they often asked, why my node reported 0 stake was participated.
=> Return err instead of 0 for unavailable participation

beacon-chain/core/blocks/spectest/attestation_test.go, beacon-chain/core/blocks/spectest/attester_slashing_test.go, beacon-chain/core/blocks/spectest/block_header_test.go, beacon-chain/core/blocks/spectest/block_processing_test.go, beacon-chain/core/blocks/spectest/deposit_test.go, beacon-chain/core/blocks/spectest/proposer_slashing_test.go, beacon-chain/core/blocks/spectest/voluntary_exit_test.go, beacon-chain/core/epoch/spectest/final_updates_test.go, beacon-chain/core/epoch/spectest/justification_and_finalization_test.go, beacon-chain/core/epoch/spectest/registry_test.go, beacon-chain/core/epoch/spectest/rewards_and_penalties_test.go, beacon-chain/core/epoch/spectest/slashings_test.go, beacon-chain/core/helpers/spectest/shuffle_yaml_test.go, beacon-chain/core/state/spectest/slot_processing_test.go
Test skipping
This PR skips all of the spec tests in beacon-chain/core/ to not pollute buildkite with test failures while we work on the branch. Once #5935 is complete, this will be reverted.
This PR does not add skips to `shared/bls/spectest` and `shared/params/spectest`, please let me know if either of those are needed.
=> Skip spec tests until v0.12 changes are complete 

beacon-chain/core/blocks/block_operations.go, beacon-chain/core/blocks/block_operations_test.go, beacon-chain/core/helpers/signing_root.go, beacon-chain/core/helpers/signing_root_test.go, beacon-chain/core/state/transition_test.go, proto/beacon/p2p/v1/types.proto, proto/testing/ssz_static_mainnet_test.go, proto/testing/ssz_static_minimal_test.go, proto/testing/ssz_static_test.go, shared/interop/generate_genesis_state.go, shared/keystore/deposit_input.go, shared/keystore/deposit_input_test.go, shared/mock/beacon_service_mock.go, shared/mock/beacon_validator_client_mock.go, shared/testutil/deposits.go
Part of #5935
Change list:
* Update helper `SigningRoot` container name to `SigningData` to be less confusing
Reference PR: ethereum/eth2.0-specs#1740
=> Update container name `SigningRoot` to `SigningData`

beacon-chain/core/epoch/precompute/reward_penalty.go, beacon-chain/core/epoch/precompute/reward_penalty_test.go, beacon-chain/core/state/interop_regression_test.go
Part of #5935
Change list:
* Align logic to ensure balances remain unchanged for optimal validators
* Add New tests for new helper functions
* Update existing test
Reference PR: ethereum/eth2.0-specs#1830
=> Ensure balance unchanged for optimal validators

beacon-chain/blockchain/process_attestation.go
Part of #5935
Change list:
* Remove redundant future target epoch time check
Reference PR: ethereum/eth2.0-specs#1755
=> Remove redundant check in future target epoch time

beacon-chain/state/stategen/BUILD.bazel, beacon-chain/state/stategen/migrate.go, beacon-chain/state/stategen/migrate_test.go, shared/cmd/flags.go
> Feature
New state management has one deficiency. During migration, if the archived slot happens to have a skip block, then that archived slot will not have any state saved. This fixed that by recovering and resaving skipped archived point
Fixes #5937
Tested run time to confirm it works
=> Recover skipped archived point

beacon-chain/blockchain/testing/mock.go, beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/rpc_beacon_blocks_by_range_test.go, beacon-chain/sync/service.go, endtoend/long_minimal_e2e_test.go, endtoend/minimal_antiflake_e2e_1_test.go, endtoend/minimal_antiflake_e2e_2_test.go, endtoend/minimal_e2e_test.go, endtoend/minimal_slashing_e2e_test.go
Update to Spec v0.12
Updates our blocksByRange Handler to only return canonical blocks. 
Part of #5935, it follows on from the following PRs in the specs repo:
https://github.com/ethereum/eth2.0-specs/pull/1835
https://github.com/ethereum/eth2.0-specs/pull/1795
=> Return Canonical Blocks in Response

shared/featureconfig/config.go
No tracking issue. This PR removes the log `WARN: using default mainnet config` from beacon nodes, as we should only be warning a user if they are using minimal
=> Remove Warning on Using Default Mainnet Config

validator/accounts/account.go
Bug fix
Previous implementation of merging validators had a bug when closing open connections. The `defer` statement was declared not early enough. This PR fixes the problem.
N/A
I am not sure if my solution is idiomatic Go, but it does the job 😉
=> Fixed deferring of closing dbs

beacon-chain/main.go, beacon-chain/usage.go, slasher/main.go, slasher/usage.go
Bug fix
Some flags for configuring TLS certs are missing. This adds the missing flags to Beacon Chain and Slasher. The values are already used but aren't exposed as flags (don't show up under --help). Maybe they already work with the file-based approach and that's why it hasn't been noticed yet.
Didn't create one as it's a small fix.
=> Add missing TLS-related flags to Beacon Chain and Slasher

validator/accounts/account.go, validator/accounts/account_test.go
> Other
A user reported the account creation deposit data is not quite clear, so they ended up pasting their public key into the prylabs.net/participate portal instead. This is because, intuitively, the user ignored the `======RAW TRANSACTION DATA======` text blob in the terminal. Instead, we should rename that to `DEPOSIT DATA` and mention clearly to paste in the deposit data shown above into the prylabs.net/participate page.
=> Improve Deposit Data Account Creation Prompt

beacon-chain/blockchain/chain_info.go
From @protolambda, Prysm is returning the genesis block as the finalized root. But it's supposed to be zeroed. And when lighthouse shares their status, with zeroed finalized root, prysm bans them
=> Return zeroed for finalized root

beacon-chain/sync/rpc_status.go
Update `validateStatusMessage` to handle zeroed response prior to first finalized check point
=> Handle zeroed response

beacon-chain/cache/committee_ids.go, beacon-chain/cache/committee_ids_test.go, beacon-chain/p2p/service.go, beacon-chain/p2p/subnets_test.go, beacon-chain/rpc/validator/assignments.go, beacon-chain/rpc/validator/assignments_test.go, beacon-chain/rpc/validator/attester.go, beacon-chain/rpc/validator/attester_test.go, beacon-chain/sync/subscriber_beacon_attestation.go
=> Cleanup Subnets Feature

beacon-chain/db/kv/check_historical_state.go
Add the skip option to the regen historical states warning log
=> Add skip to regen historical states warning log

beacon-chain/state/references_test.go, beacon-chain/state/setters.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
As part of alpha9 todo, this PR releases`enable-state-ref-copy` flag. This flag has been running in exp pods and on external validators many weeks without any issue
=> Release state-ref-copy flag

beacon-chain/sync/service.go, beacon-chain/sync/service_test.go, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_test.go
Bug Fix
It registers our handlers only after we receive the state initialized event.
Resolves #5990 
=> Register RPC And Pubsub Handlers After Genesis is Determined

prysm.bat, prysm.sh
Users can circumvent their antivirus blocking curl requests to prysm.sh by specifying --ssl-no-revoke. This PR recommends that option to users who may be blocked by their antivirus.
Fixes #5986
=> Recommend Users Blocked By Antivirus a Way to Curl Prysm.sh

.github/ISSUE_TEMPLATE/feature_flag.md
Bug fix
- Fixes template's front-matter, allowing us to use that template
- Wanted to use the template to track recently introduced flag, but template wasn't available on issue selection. Turns out there's a bug in YAML's front-matter.
=> Fixes problem in YAML front-matter of the new flag tracking issue template

shared/featureconfig/config.go, shared/featureconfig/flags.go
Review and merge #6012 first
As part of alpha9 todo, this PR inverts enable-state-field-trie flag. This flag has been running in exp pods and on external validators many weeks without any issue
=> Invert enable-state-field-trie flag

beacon-chain/cache/BUILD.bazel, beacon-chain/cache/attestation_data.go, beacon-chain/rpc/validator/attester.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
> Feature
This significantly reduces the amount of head state copy for RPC attester from `ASSIGNED_COMMITTED_COUNT` down to 1. With great saving when there's multiple keys, because chances are a validator client are assigned to more than 1 committee. In the current experiment, we see with 50 validators, the validator client are very often assigned to 8 committees per slot. That's 7 extra copies saved. This works because shard is not in play for phase 0, all committees are the same from beacon node's perspective.
Gated behind feature flag `--reduce-attester-state-copy`
Fixes #5961 
Tested it locally for 12 hours with 4k validators. This saves ~1GB run …
=> Reduce attester state copies

beacon-chain/rpc/node/server.go, beacon-chain/rpc/node/server_test.go
> Bug fix
If the beacon node is pre-genesis (as in, a genesis time has yet to be determined), the result of 
```
curl -X GET "http://localhost:4001/eth/v1alpha1/node/genesis" -H  "accept: application/json"
```
will be 0001-01-01T00:00:00Z, which is not a realistic value and returns -672637623 when attempting to convert into a unix timestamp. Instead, we should do a sensible default of unix timestamp 0.
Confirmed the result works:
```
{"genesisTime":"1970-01-01T00:00:00Z","depositContractAddress":"vhKJVwd36/uywA1nK2aeiStTAP4=","genesisValidatorsRoot":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="}
```
Fixes #5548
=> Fix Weird Pre-Genesis Timestamp

beacon-chain/operations/slashings/service.go, beacon-chain/operations/slashings/service_attester_test.go, beacon-chain/operations/slashings/service_proposer_test.go
Bug fix
This PR modifies the slashing pool to use more spec code, to prevent duplicated code that needs to be maintained. This fixes an improper calculation for slashing validation, allowing a possibly invalid slashing to be put into the pool.
=> Change slashing pool to use spec code 

beacon-chain/cache/hot_state_cache.go
> Feature
Increase hot state cache size from 16 to 32. This improves hot state miss rate from ~4% to 2% and brings in more memory saving to the `new-state-mgmt` feature. This was discussed with @nisdas and both of us tested this increase and mutually agreed this is a superior approach
=> Increase hot state cache size to 32

slasher/db/testing/setup_db.go, slasher/db/testing/setup_db_test.go, tools/enr-calculator/main.go, tools/sendDepositTx/sendDeposits.go, validator/db/db.go
Other/Cleanup
- Properly handles issues with improper handling of nil values
- Issue was detected when reviewing the following code:
https://github.com/prysmaticlabs/prysm/blob/ac862d1e7e4fa7722f2835a28e7eccfaa87f6881/validator/db/db.go#L69-L71
Here we do not properly handle error and possible nil value returned for the `kv` object. 
- Couple of issues of the same origin have been identified in other places and fixed as well.
=> Properly handles possible nil values

shared/params/config.go
Fixes a bad merge from master by renaming to `ShardCommitteePeriod`
=> Fix Bad Merge 

beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/pending_blocks_queue_test.go
Bug fix
- Fixes possible overflow
Fixes #6038
N/A
=> Fixes overflow issue in sync/pending_blocks_queue

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/options.go
Ensures that for v0.12 only Noise and Secio are used as security transports.
Makes sure that we only use the correct security transports instead of something like 
`TLS` which is now the default option along with secio
Fixes #6032 
=> Ensure Only Noise And Secio Are Security Transports

validator/accounts/account.go, validator/accounts/account_test.go, validator/client/service.go, validator/db/BUILD.bazel, validator/db/db.go, validator/db/manage.go, validator/db/manage_test.go, validator/db/setup_db.go, validator/db/setup_db_test.go, validator/node/node.go
Other
These PR introduces changes requested in #5968's review comments. These comments were added after the PR had been closed.
N/A
=> Merge validators enhancements

beacon-chain/p2p/handshake.go, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/rpc_ping.go, beacon-chain/sync/rpc_status.go
Bug Fix
On long running nodes, profile snapshots constantly showed a larger growing heap. Initially it was not obvious what was the root cause, but after a while it became clear that a large amount of streams were not cleaned up properly. While in most situations closing the stream is fine, as the other user will also close the stream on their end too.  This allows the yamux session to remove the dead stream and clean it up. However there are situations when the other peer does not reply back or no messages are received,etc. This leads to the stream being left open and not being cleaned up. While it was not an issue with 30 peers, it becomes much worse with a larger number of peers over a period of time.
**Which …
=> Reset Streams Properly

shared/sliceutil/slice.go, shared/sliceutil/slice_test.go
Bug fix
- Fixes issue with intersection functions, when argument list has more than 2 slices (issue is reported by audit team)
Fixes #6029
- This is **an alternative** PR to the one that has been created by Terence: https://github.com/prysmaticlabs/prysm/pull/6050 
- Terence's PR was blocked by what seemed to be issues in `init-sync` fetcher tests. The issue proved to be not in tests, but in how intersection was implemented: it modified passed in argument (the first slice), which was unexpected. While debugging the issue, I came up with this alternative implementation.
- This PR uses different implementation (still the one based on map - so efficiency …
=> Fixes intersection functions (uint64, int64, []byte)

beacon-chain/db/kv/BUILD.bazel, beacon-chain/db/kv/utils.go, beacon-chain/db/kv/utils_test.go
Bug fix
- Additional check is added to make sure that `deleteValueForIndices` doesn't match root to subsequences of adjacent values.
Fixes #6034
- Change is trivial, tests took some time!
=> Fixes subsequence matching in deleteValueForIndices

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/process_block_helpers.go
Use stateutil to get block root. For some reason ssz yields an incorrect result there.
Steps to reproduce:
https://discordapp.com/channels/476244492043812875/550365651118850081/717045870847328277
=> Use `stateutil.BlockRoot` instead of `ssz` for fork choice

beacon-chain/state/stateutil/blocks.go
> Bug fix
Discovered a hard-coded block body root if an input is nil in stateutil.BlockBodyRoot. This PR changes that to instead be an empty beacon block body input.
=> Create Empty BlockBody in stateutil.BlockBodyRoot if nil #6094

scripts/common.sh, scripts/update-go-pbs.sh, scripts/update-go-ssz.sh
Other
- allows running `./scripts/update-go-ssz.sh` an `./scripts/update-go-pbs.sh` on OSX (where find is not GNU compatible)
- OSX's version of `find` doesn't have `-regexptype` flag, so those scripts weren't working
- OSX has GNU compatible version, installable via `brew install findutils`
- So, if we are on OS, script checks whether `gfind` is available (GNU compatible find):
- If `gfind` is avaialble, it is used:
=> Assert gfind is available on OSX, for protobufs updates

beacon-chain/core/state/benchmarks_test.go, beacon-chain/sync/validate_aggregate_proof_test.go
This PR fixed the on going broken tests for v0.12
=> Fix broken v0.12 tests

beacon-chain/sync/initial-sync/blocks_fetcher_test.go
Other/Better Testing
- When `EnableInitSyncWeightedRoundRobin` was introduced some parts of the code path were deactivated in tests (we set the flag to true, and that causes some parts of code to be ignored in tests). This is not ideal as we still use the code in production. This PR makes sure that the same code is run using different flags - so is tested using both previous (blocks interleaved) and current fetching algos.
- `fetchBlocksFromPeers` https://codecov.io/gh/prysmaticlabs/prysm/src/master/beacon-chain/sync/initial-sync/blocks_fetcher.go#L288 is all red now:
This should be fixed by this PR.
=> Re-enable previous fetching algorithm testing

beacon-chain/p2p/service.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
Disables libp2p's Kademlia based discovery instead making only discoveryV5 the default. 
This adds a flag to enable kad-dht in `v0.12`, meaning that it will be disabled by default.
Part of #6076 
=> Disable Kademlia Discovery By Default

beacon-chain/core/epoch/precompute/reward_penalty.go, beacon-chain/core/epoch/precompute/reward_penalty_test.go, beacon-chain/core/helpers/rewards_penalties.go
Feature improvement
This removes excessive locking when updating validator balances. Instead of acquiring the lock for
each validator we only acquire it once. This makes balance updates in epoch transitions much more efficient.
Fixes #6111
N.A
=> Remove Balance Updates With Excessive Locking

beacon-chain/node/node.go
Warning of CLI flags
Adds a log to warn users about the use of the default ETH 1.0 RPC at `https://goerli.prylabs.net`
Fixes #6051
=> Notify users' with warning about using default ETH 1.0 RPC

slasher/rpc/BUILD.bazel
Build fix
This PR removes a bazel build target that is unused.
=> Remove unused bazel test target

beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/initial-sync/round_robin_test.go
Other
- There is a commented out test case in init-sync's round robin test file. I suppose there were some issues with multi-failure test case (it was commented out on previous implementation of syncing) - thus it was commented out.
- Our current implementation is capable of processing such multiple bad peers w/o any issues, so the case is re-enabled.
N/A
=> Re-enables multi-failure test case in round robin

.bazelrc, shared/debug/cgo_symbolizer.go
This fixes Mac OS X builds with "go build". 
Bug fix
Error on Mac OS X:
```
go test -v ./validator/node/...
Undefined symbols for architecture x86_64:
"_backtrace_initialize", referenced from:
_fileline_initialize in _x004.o
"_cgoTraceback", referenced from:
__cgohack_cgoTraceback in _cgo_main.o
(maybe you meant: __cgohack_cgoTraceback)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
FAIL    github.com/prysmaticlabs/prysm/validator/node [build failed]
FAIL
```
=> Only build with cgosymbolizer when explicitly requested

endtoend/long_minimal_e2e_test.go, endtoend/minimal_e2e_test.go, endtoend/minimal_slashing_e2e_test.go
This PR unskips e2e tests as the root cause of their previous failures have been resolved.
=> Unskipping E2E Tests

beacon-chain/db/kv/BUILD.bazel, beacon-chain/db/kv/check_historical_state.go, beacon-chain/db/kv/check_historical_test_test.go
> Feature
Lesson learned from #6156
A node should disallow operation to change `--slots-per-archive-point` when the node is already in operation. Meaning if a user has set slots-per-archive-point to 256 to start with. The node should disallow user changing it to 2048 or any value once the node has state in DB`
The consequence of changing --slots-per-archive-point in flight will create inconsistency of archived points mapping, which results in poor UX for the users.
Fixes #6158
Verified run time:
```
DEBUG: /private/var/tmp/_bazel_terence/ab2b20e4e89e932d12c8d013e1bb88e2/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:100:9: rbe_ubuntu_clang_gen …
```
=> Verify historical slots per archived point

beacon-chain/rpc/validator/proposer.go, beacon-chain/rpc/validator/status.go
Other/Minor Fix
- Makes span naming consistent
N/A
- When working on optimizations for `GetBlock` I've noticed that in jaeger it is referred as `RequestBlock`, which is inconsistent with how we are naming the rest of spans.
=> Fixes span naming in rpc/validator

shared/featureconfig/config.go, shared/featureconfig/flags.go
This PR inverts `ReduceAttesterStateCopy` feature flag. This flag has been running great in exp pods for the last 10 days. Exp pods's memories are 500MB less than prod pods
=> Invert reduce attester state copies

shared/featureconfig/config.go, shared/featureconfig/flags.go
Other/Flag Inversion
- Enables weighted round robin fetching (when data batch is fetched from a single peer - with fetching priority determined by weighted round robin)
- `enable-init-sync-wrr` -> `disable-init-sync-wrr`
Part of #6024
- The `enable-init-sync-wrr` was part of `--dev`, so whenever we used `--dev` the flag was enabled.
=> Inverts enable-init-sync-wrr flag

beacon-chain/powchain/service.go
Bug fix
If a user specifies an address like "localhost:8545" and nothing is running at that address, they will not receive a "dial" error and may be spammed with error logs. This PR resolves that issue by making a simple check that they are connected to a real node.
Outlined above.
Required for v0.12 launch.
=> Make a simple json-rpc call to ensure we are connected to a real ETH1 node

scripts/workspace_status.sh, shared/version/BUILD.bazel, shared/version/version.go
Example:
version=Prysm/v1.0.0-alpha.10/28e61fa40c7d16774b3b1c18d8382c64537bfa84. Built at: 2020-06-11 04:29:18+00:00
Feature
This is helpful for understand what the latest git version tag the Prysm client is running.
=> Add the latest git tag as part of the version string

beacon-chain/sync/subscriber_beacon_blocks.go, beacon-chain/sync/validate_beacon_blocks.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
Reverts prysmaticlabs/prysm#6164
I have a few concerns with 6164
* This loosens the security of beacon node because it has to serve slasher; it is not a good compromise. This deviates regular beacon node from the spec implementation and there's no issue to follow up with this. There's also no warning message around it. A user could be using this flag without knowing their beacon node could get spammed 
* The correct implementation should be feed: any incoming block to the slasher RPC server before the `hasSeenBlockIndexSlot` check 
We should either implement proper warning message or fix it by using proper event feed instead of feature flag as a work around
=> Revert "Send blocks that fails validation to slasher"

beacon-chain/state/getters.go, beacon-chain/state/getters_test.go
> Bug fix
Resolves the nil validator panic found by fuzz testing.
Fixes #6127
=> Resolve Nil Validator Panic

beacon-chain/sync/service.go
Bug Fix
Immediately registers p2p rpc methods upon receiving the genesis event instead of waiting till genesis.
N.A
=> Do Not Wait Till Genesis

beacon-chain/sync/service.go
Bug Fix to Bug Fix
Follows on from #6225, seeing as we prematurely set the `chainstarted` var throught those changes we revert it and instead just register the handlers when state is initialized.
N.A
=> Follow Up to #6225 

beacon-chain/BUILD.bazel, slasher/BUILD.bazel, validator/BUILD.bazel
Other
This PR adds support for pushing images directly to dockerhub.
Initially, we will support the following docker repositories:
- prysmaticlabs/prysm-beacon-chain
- prysmaticlabs/prysm-validator
- prysmaticlabs/prysm-slasher
Fixes #3166
CI might not have the credentials to push these images.
I'll work on that after this merges.
=> Add dockerhub image endpoints

beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go
> Bug fix
Proposer should not have duty for slot 0. `CommitteeAssignments` will skip 0 for caching proposer index to slot duty.
Fixes #6227 
Before
```go
[2020-06-12 07:57:55]  INFO validator: Beacon chain started genesisTime=2020-06-13 22:17:24 -0700 PDT
[2020-06-12 07:57:55]  INFO validator: Validator activated index=539 publicKey=0x81a455477ae5
[2020-06-12 07:57:55]  INFO validator: Proposal schedule pubKey=0x81a455477ae5 slot=0
[2020-06-12 07:57:55]  INFO validator: Attestation schedule attesters=1 pubKeys=[0x81a455477ae5] slot=13
```
After
```go
[2020-06-12 07:57:38]  INFO validator: Beacon chain started genesisTime=2020-06-13 …
```
=> Skip proposer duty calculation for slot 0

beacon-chain/gateway/gateway.go
> Bug fix
We were ignoring the max grpc message size in the grpc gateway unless the --enable-debug-rpc-endpoints flag was on, which doesn't make sense as they should not depend on each other.
Fixes #6068
=> Do Not Ignore Max Gateway Size gRPC

beacon-chain/rpc/BUILD.bazel, beacon-chain/rpc/service.go, go.sum, shared/featureconfig/config.go, shared/featureconfig/flags.go
> Feature
This PR adds the ability to log new grpc client connections to beacon nodes:
```
[2020-06-12 15:04:18]  INFO rpc: New gRPC client connected to beacon node addr=127.0.0.1:59704
```
Helping give feedback to users that their validator client is properly connected. This feature can be disabled with `--disable-grpc-connection-logs`
Fixes #5647, which brought up that we log p2p peer connections and disconnections but do not do the same for gRPC client connections (i.e. validator clients).
=> Add a Log for Newly Connected gRPC Clients in the Beacon Node

beacon-chain/blockchain/service.go
If the genesis state is the finalized state or head state. We don't need to regen genesis's parent state. This PR skips regeneration of genesis's parent state.
Fixes #6235 
Tested it run time.
```go
➜  prysm git:(dont-regen-genesis-parent-state) bazel run //beacon-chain -- --datadir=/tmp/onyx2048-1 --min-sync-peers=1  --http-web3provider=http://127.0.0.1:8545/ --monitoring-port=8085  -p2p-udp-port 14622 --p2p-tcp-port 14632 --skip-regen-historical-states
2020/06/13 08:54:37 maxprocs: Leaving GOMAXPROCS=12: CPU quota undefined
[2020-06-13 08:54:37]  WARN flags: Enabling skipping of historical states regen
[2020-06-13 08:54:37]  INFO node: Checking DB …
```
=> Don't regen parent state for genesis state

beacon-chain/blockchain/process_attestation_helpers.go
Reverts prysmaticlabs/prysm#6142
=> Revert "Remove Excess State Copies"

beacon-chain/blockchain/process_attestation_helpers.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
> Bug fix
The `ancestor` function  is old and hasn't been updated in a while. In the event of a skip slot, the `ancestor` function should return most recent root prior to slot. Instead, it was returning nil.
Tested run time to and verified it fixed `FFG and LMD votes are not consistent` issue
=> Fix ancestor to return most recent root in the case of skip slot

beacon-chain/sync/rpc_status.go
We occasionally ping and validate the status messages of our peers to check their liveness. In the event they are unreachable or give us bad data, we do disconnect these peers.
It increments the peer counter on each failed validation. In the event we reach the threshold, we
will disconnect from them. 
N.A
=> Mark Peer As Bad After a Failed Validation

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/connection_gater.go, beacon-chain/p2p/connection_gater_test.go, beacon-chain/p2p/options.go, beacon-chain/p2p/options_test.go, beacon-chain/p2p/service.go
We add filtering to our connection gater so that we can appropriately handle allow and deny lists
properly in its context. Also we now fix allow lists so that only ip's which satisfy the cidr mask are allowed to connect to the beacon node.
Follows on from #6243
=> Filter Peers Properly With Connection Gater

deps.bzl, go.mod
Bug Fix
Updates our go-ethereum fork to handle the discoveryV5 panic.
Fixes #6255 
=> Fix Discovery Panic

beacon-chain/powchain/block_reader.go, beacon-chain/powchain/block_reader_test.go, beacon-chain/powchain/log_processing_test.go, beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
We handle unsynced eth1 nodes, and do not ask data from them until they are fully synced. We also introduce backoffs before redialing an eth1 node so as to not overwhelm them.
N.A
=> Handle Unsynced ETH1 Node

validator/flags/flags.go
> Bug fix
Our beacon node binds its RPC host by default to `127.0.0.1` but our validator tries to connect to `localhost`, which causes some issues in containerized deployments. This PR ensures both match, making validators bind on `127.0.0.1` by default.
Fixes #6238
=> Default BeaconRPCProvider for Validator Should Match Beacon Node's Host

validator/accounts/account.go, validator/main.go
Bug fix
This PR fixes an issue on windows that when reading from the terminal, the command primpt would inject unsupported line endings, and mess up the path entered, preventing windows users from using the script and bat script properly.
Fixes #5456
=> Fix validator creation path issue on windows

shared/slotutil/BUILD.bazel, shared/slotutil/slottime.go, shared/slotutil/slottime_test.go
Bug fix
This PR fixes an underflow condition for SlotsSinceGenesis computation.
Fixes #6273
=> Fix underflow in SlotsSinceGenesis

shared/featureconfig/flags.go
Other
We want to release `--initial-sync-verify-all-signatures` flag soon so I am adding it to the `--dev` flag group for testing. 
Part of #5176
Also adds `--dev` to e2e
=> Add --initial-sync-verify-all-signatures as a dev flag

beacon-chain/core/blocks/block_operations.go, beacon-chain/core/blocks/block_operations_test.go, beacon-chain/core/state/transition.go, shared/bls/bls.go
Feature
Validating all attestations in a block is rather slow, especially when done individually.
This PR verifies all of the attestation signatures of a block in a single cgo call rather than `n` cgo calls to BLS.
Requirement for #5176 
With `--initial-sync-verify-all-signatures`, I was seeing an improvement from around 7bps to around 20bps. 
Also increases the public key cache to 4 megabytes. This greatly reduces the amount of cache misses and public key deserialization required for sync.
=> Verify many block attestations at once

shared/bls/bls.go
Other
This PR allocates the correct amount of memory so that the slices created in AggregateVerify have the correct capacity.
Helps for #5176
Tested at runtime with negligible improvements to init sync.
=> pre-allocate memory for AggregateVerify

.github/CODEOWNERS
Other
This allows any team member to approve deps.bzl changes.
N/A
CODEOWNERS order of precedence is "latest definition wins" so this change must come after the global starlark owners.
=> Add @prysmaticlabs/core-team as codeowner for deps.bzl

beacon-chain/sync/rpc_ping.go
When receiving a ping there is a goroutine that can be spawned, however as it stands that goroutine operates on a closed stream with a cancelled context.
This patch alters the ping handler in a few ways.
First, it doesn't `defer` closing the stream but instead explicitly closes it on return conditions.  This ensures that the stream is available to the goroutine.
Second, the goroutine uses a new context (with appropriate timeout) rather than the one passed in to the function (which is cancelled when the calling function returns).
Finally, it removes an unused context that was created.
=> Ping handler timeout

beacon-chain/rpc/beacon/validators_stream.go
This patch adds a couple of `Unlock()`s for a mutex.  The situations in which these have been added are "should never happen" cast failures, but as the path exists in the code the mutex should be unlocked before returning.
=> infostream: unlock mutex on return

scripts/workspace_status.sh, shared/version/BUILD.bazel
Bug fix
This PR uses the correct prefix for git tag such that a change in git tag will force a relink of //shared/version:go_default_library.
May be related to #6300
=> Use STABLE_ prefix for git tag to force a relink of version

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/round_robin.go, beacon-chain/sync/service.go
Bug fix
- We are using leakybucket in a way that empty buckets are not automatically deleted (this is intended, as resources are using multiple times - no need to reclaim memory too early).
- However, when service stops, we need to call `Free()` method to reclaim the resources.
Part ot #6327
=> Reclaims leakybucket resources in sync service

beacon-chain/sync/decode_pubsub.go, beacon-chain/sync/error.go, beacon-chain/sync/metrics.go, beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/rpc.go, beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_chunked_response.go, beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/rpc_ping.go, beacon-chain/sync/rpc_status.go, beacon-chain/sync/service.go, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_beacon_aggregate_proof.go, beacon-chain/sync/subscriber_beacon_attestation.go, beacon-chain/sync/subscriber_beacon_blocks.go, beacon-chain/sync/subscriber_handlers.go, beacon-chain/sync/utils.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_attester_slashing.go, beacon-chain/sync/validate_beacon_blocks.go, beacon-chain/sync/validate_proposer_slashing.go, beacon-chain/sync/validate_voluntary_exit.go
Other/Refactoring
- in some places it was `r` in others `s`
- this PR, uses `s` as receiver name everywhere (it's short, it is consistent with what `init-sync` uses)
- having receiver as `service` (as suggested) - seems too verbose
73 and 74 in https://github.com/prysmaticlabs/prysm/issues/6337
=> Renames receiver in sync service

beacon-chain/db/kv/archive.go, beacon-chain/db/kv/archived_point.go, beacon-chain/db/kv/attestations.go, beacon-chain/db/kv/backup.go, beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/checkpoint.go, beacon-chain/db/kv/deposit_contract.go, beacon-chain/db/kv/finalized_block_roots.go, beacon-chain/db/kv/kv.go, beacon-chain/db/kv/operations.go, beacon-chain/db/kv/powchain.go, beacon-chain/db/kv/slashings.go, beacon-chain/db/kv/state.go, beacon-chain/db/kv/state_summary.go
Other
- in `db/kv` in some places `k` was used as receiver, in others `kv`
- this PR makes `kv` the receiver, everywhere (it is short, but not too short, stands for key-value)
N/A
- item 60 in https://github.com/prysmaticlabs/prysm/issues/6337
=> Fixes receiver name in db/kv

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_blocks_queue.go
Other
Fixes:
- **Issue 37:** In beacon-chain/sync/initial-sync/block_fetcher.go#269, the name count is reused (previously used as a name of of the argument). We recommend using different names.
- **Issue 38** In beacon-chain/sync/initial-sync/blocks_queue.go#310, there is a switch statement with an empty default label. Some logging/comment would be handy.
- **Issue 75:** In beacon-chain/sync/pending_blocks_queue.go, lock/unlock in processPendingBlocksQueue() is not required, as the internal function execution never overlaps with itself.
- **Issue 76:** In beacon-chain/sync/pending_attestations_queue.go, lock/unlock in processPendingAttsQueue() is not required, as the internal function execution never overlaps with …
=> Resolves issues from the best practices in sync package

beacon-chain/db/filters/filter.go, beacon-chain/db/kafka/export_wrapper.go, beacon-chain/db/kv/archived_point.go, beacon-chain/db/kv/attestations.go, beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/check_historical_state.go, beacon-chain/db/kv/regen_historical_states.go, beacon-chain/db/kv/utils.go, beacon-chain/db/kv/utils_test.go
Other
Fixes:
- **Issue 51:** In beacon-chain/db/filters/filter.go, L21-44: use iota instead of enumerating sequential values.
- **Issue 52:** In beacon-chain/db/filters/filter.go, declaring FilterType as an alias to int seems excessive; rather, uint8 would have sufficed.
- **Issue 53:** In beacon-chain/db/kafka/export_wrapper.go#36, prior to returning, issue a log info just to inform that the db was not wrapped.
- **Issue 54:** In beacon-chain/db/kv/archived_point.go#38, Update is being called, but no side effect occurs. Replace it with View.
- **Issue 56:** In beacon-chain/db/kv/attestations.go, function createAttestationIndicesFromData() does not start & end a span. Following other functions, start & end a span.
- …
=> Resolves issues from the best practices in beacon-chain/db

beacon-chain/rpc/validator/attester.go, beacon-chain/rpc/validator/attester_test.go
A case where `len(req.Slots) != len(req.CommitteeIds)` but `len(req.CommitteeIds) == len(req.IsAggregator)`
should also throw an error. Without this fix only 2 length inequalities will throw the error.
Greetings from PwC Switzerland
Bug fix
Unexpected runtime error can be thrown
Fixes #
A case where `len(req.Slots) != len(req.CommitteeIds)` but `len(req.CommitteeIds) == len(req.IsAggregator)`
should also throw an error. Without this fix only 2 length inequalities will throw the error.
A test case should be added to cover the cse where 
`len(req.Slots) != len(req.CommitteeIds)` but `len(req.CommitteeIds) == len(req.IsAggregator)`
=> SubscribeCommitteeSubnets fields length check

beacon-chain/sync/pending_attestations_queue.go
Currently, we have a function processPendingAttestations() in sync which runs periodically and requests missing blocks from peers from pending attestations we have observed. If there are no peers to request from, the function exits early, however, there is no comment signifying why this is safe.
Part of #6327
=> QSP-61 Clarify Why Process Pending Attestations May Exit Early

beacon-chain/sync/initial-sync/service.go
Part of #6327, removes a call to double unsubscribe from a feed in initial-sync/service.go
=> QSP-42 Remove Double Unsubscribe in Initial Sync

beacon-chain/sync/deadlines.go, beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_chunked_response.go, beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/rpc_ping.go, beacon-chain/sync/rpc_status.go
Part of #6327. Libp2p stream read/write deadlines use the system time instead of roughtime. This PR adds clear information about why that is the case and what would happen if the system time becomes corrupted.
=> QSP-62 Corrupted Clock In Stream Deadlines

beacon-chain/p2p/encoder/network_encoding.go, beacon-chain/p2p/encoder/ssz.go
Other -- Code cleanup
This method was not used (or tested) by any code within Prysm.
No known production issues.
I am not sure if this was going to be used at some point, but we can always add it back (with tests!) in the future if the spec requires this type of encoding.
=> Remove unused p2p encoding method

beacon-chain/p2p/peers/BUILD.bazel, beacon-chain/p2p/peers/status.go, beacon-chain/p2p/peers/status_test.go, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_fetcher_test.go, beacon-chain/sync/initial-sync/round_robin.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/rpc_status.go
Part of #6327, we were not handling the case with 0 connected peers in the peer status BestFinalized() method. Instead, we were checking for no connected peers _around_ the method but not in the method itself, which could lead to misuse down the line
=> QSP-45 Add Check for No Connected Peers BestFinalized

beacon-chain/main.go, beacon-chain/node/node.go, beacon-chain/p2p/config.go, beacon-chain/p2p/service.go, beacon-chain/usage.go, shared/cmd/flags.go, shared/featureconfig/flags.go
This PR is part of #6327, it removes extra pubsub protocol support such as flood and random from Prysm, only allowing for gossip sub
=> QSP-55 Remove Support for Other Pubsub Protocols

beacon-chain/core/helpers/randao.go
Other
state.RandaoMixAtIndex already makes a copy of the 32 byte randao mix, there is no need to make another copy of it.
N/A
=> Remove duplicated randao mix copy

beacon-chain/rpc/beacon/BUILD.bazel, beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
> Bug fix
Fix `ListValidators` retrieval for new-state. The previous implementation had a bug. If one of the validator in the beacon state is not active, then every validators after that inactive validator would not be correctly accounted for.
Fixes #6416 
=> Fix `ListValidators`  retrieval for new state

beacon-chain/state/getters.go
> Code health improvement
`ValidatorAtIndex()` could reuse `CopyValidator()` to copy validator
=> Use `CopyValidator` for `ValidatorAtIndex`

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/options.go, go.mod, shared/featureconfig/config.go, shared/featureconfig/flags.go
We make NOISE as the default for our security handshake, so as to be able to interop with the other clients. This
adds SECIO as the fallback, so that onyx can work as normal.
Part of #6327 and also addresses QSP 50 and QSP 51
=> QSP 50, QSP 51: Make Noise Default 

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/service.go, beacon-chain/blockchain/service_test.go
> code clean up
remove unused code `PruneOldState` this was left over from defaulting block chain service to using new state mgmt
=> Remove unused prune old states

slasher/rpc/service.go
Bug fix
`--tls-key` and `--tls-cert` flags on the slasher rpc server are ignored leading to spinning up a non-tls server.
None created
This was only visible in the validator failing the call to external slashing protection with a hint about tls. The warning code for non-tls enabled connections that are present in beacon chain etc. was missing. I also added that so it's easier to see when the slasher doesn't run with tls.
=> Allow to start slasher RPC server with TLS

beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/initial-sync/blocks_queue_test.go, beacon-chain/sync/initial-sync/round_robin.go
Other
- In https://github.com/prysmaticlabs/prysm/pull/6469 Nishant is woking on multi-block verification of blocks in init-sync, so needs to have a way to access incoming blocks in batches, hence this PR
N/A
=> Refactors init-sync: queue streams blocks in batches

beacon-chain/sync/initial-sync/blocks_queue.go
Bug fix
- Follow up to #6470 
- There's no need for all FSMs pushing block batches concurrently - since up until a previous batch is processed (or thrown away) we cannot determine whether any given FSM's range of slots can be processed or needs to be refetched.
- Previously, channel was buffered with batch limit size - allowing blocks from a single FSM to be streamed w/o blocking. Now, no need to have buffer of size equal to number of FSMs (which I did in #6470), single buffer space is enough: round robin reads constantly, so processing one batch at a time, with first FSM non-blocking, and pre-fetching for all the FSMs is more than enough concurrency.
N/A
**Other notes for …
=> Removes excessive concurrency from init-sync queue

shared/aggregation/aggregation.go, shared/aggregation/attestations/attestations_bench_test.go, shared/aggregation/maxcover.go
Other
- During #6234 benchmark hasn't been moved into the new `shared/aggregation/attestations` package, this PR restores that benchmark file
N/A
=> Restores att-aggregation benchmarks

beacon-chain/state/stategen/BUILD.bazel, beacon-chain/state/stategen/epoch_boundary_state_cache.go, beacon-chain/state/stategen/epoch_boundary_state_cache_test.go
Features
Implemented a cache to store epoch boundary states. Features:
- Cache size is 8. (e.g. one hour of epoch boundary states given current configs)
- Two fifos involved. `slot -> root` and `root -> state`
- Epoch boundary states can be retrieved by root or by slot
=> Epoch boundary cache

validator/accounts/v2/new.go, validator/accounts/v2/testing/BUILD.bazel, validator/accounts/v2/testing/mock.go, validator/accounts/v2/wallet.go, validator/keymanager/v2/direct/BUILD.bazel, validator/keymanager/v2/direct/direct.go, validator/keymanager/v2/direct/direct_test.go, validator/keymanager/v2/types.go
> Feature
This PR implements the `FetchValidatingPublicKeys()` function for a direct keymanager, retrieving account names from disk and unlocking them from their associated passwords using the EIP-2335 keystore reference.
Part of #6220
=> Direct Keymanager: Implement FetchValidatingPublicKeys()

.buildkite-bazelrc
Other
CI builds are currently blocked.
No production code changes, just bazelrc config.
=> CI: Remove GCP remote cache

beacon-chain/state/BUILD.bazel, beacon-chain/state/types.go, beacon-chain/state/types_bench_test.go
Other/Minor Optimization
- The `defer` after release of Go1.4 is almost as good as inlined function call, yet it still has a bit of an overhead.
- I've noticed that `AddRef()` avoids calling `defer`, this PR makes sure that `MinusRef()` also calls unlocking inline.
N/A
- To help gauging utility of the PR, here is the output of `benchstats` (~0.5% improvement on speed -- really tiny optimization):
```
± benchstat bench.old bench.new
name                  old time/op    new time/op    delta
Reference_MinusRef-8    30.4ns ± 0%    28.8ns ± 0%   ~     (p=1.000 n=1+1)
```
=> Tiny optimization in state refs lock/unlock

beacon-chain/db/kv/backup.go, beacon-chain/db/kv/kv.go, shared/keystore/BUILD.bazel, shared/keystore/key.go, slasher/db/kv/kv.go, validator/db/kv/db.go
Permissions cleanup
This PR covers 57 and 58 of the audit best practices feedback by changing all files to the same perms, 0600 as used in the IO Config.
=> Use same permissions for all files in Prysm 

WORKSPACE, go.mod, go.sum, validator/accounts/v2/BUILD.bazel, validator/accounts/v2/cmd.go, validator/accounts/v2/list.go, validator/accounts/v2/list_test.go, validator/accounts/v2/wallet_test.go, validator/flags/flags.go, validator/keymanager/v2/direct/BUILD.bazel, validator/keymanager/v2/direct/direct.go, validator/keymanager/v2/testing/BUILD.bazel, validator/keymanager/v2/testing/mock.go
> Feature
This PR implements `validator accounts-v2 list` with the option of displaying deposit data for all validator accounts using the `--show-deposit-data` flag. It additionally adds created_at and updated_at metadata files containing a raw unix timestamp to each direct keymanager account.
Part of #6220 and depends on #6489
=> Implement Accounts-v2 List: Direct Keymanager

beacon-chain/db/kv/backup.go, beacon-chain/db/kv/kv.go, shared/keystore/key.go, shared/params/io_config.go, slasher/db/kv/kv.go, validator/db/kv/db.go
#6522 uses the same permissions for files and directories, which results in prysm being unable to traverse directories due to the lack of the executable bit.
This patch adds a second permission suitable for directories, and uses it where appropriate.
=> Add separate permission for directories.

validator/accounts/v2/list.go
> Feature
Showing Prysmatic Lab's participation link means our validator accounts are tightly coupled with `https://prylabs.net/p...` as the "canonical" location for sending deposit. It may not be the case in the near future as there maybe better options and launchpad should the canonical one. This PR removes this.
Fixes #
Before:
```
[public key] 0xa802d90ed457a2937ab96218c358f7819ec0239470bdb6088f1ee872f266c52392f377ec44e5320f66e8634138aaabf8
[created at] 2020-07-09 09:09:36 -0700 PDT
(deposit tx file) /Users/terence/Library/Eth2Validators/.prysm-wallet-v2/direct/wildly-well-walrus/deposit_transaction.rlp
======================Deposit Transaction Data===================== …
```
=> Remove participation link when `list` accounts

beacon-chain/operations/attestations/kv/aggregated.go, beacon-chain/operations/attestations/kv/aggregated_test.go
Bug fix
Fixes an error like
```
prefix=message-handler r="bitlists are different lengths" time="2020-07-10 19:13:42" level=error msg="Received nil message on pubsub" prefix=sync
```
Part of https://github.com/prysmaticlabs/prysm/issues/6548#issuecomment-656847650
=> Attestation cache: check bitlist length before checking contains

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/testing/mock.go
Other
Verifying a block root is a descendant of the finalized chain is important for stopping propagation of bad blocks.
See: #6548.
Part of #6548.
Requirement for #6549.
Opening this small PR to reduce review scope / size of #6549.
=> Refactor verifyBlkDescendant to be public in chainservice API

beacon-chain/db/kv/backup.go, shared/params/io_config.go, slasher/db/kv/kv.go, tools/cluster-pk-manager/server/db.go, validator/db/kv/db.go
Best practices 
This is part of #6337 , changes bolt timeout to a global config and sets it to backup.go
=> Add BoltTimeout to IO config 

shared/roughtime/roughtime.go
In the event of recalibration we log roughtime results, so that we are aware of the offset.
Related to #6544 and #6548 .
=> Add More Logging to Roughtime

beacon-chain/blockchain/process_block_helpers.go
Bug Fix
Reverts change from #6562 , so as to save all blocks before we start migrating states upon a new finalized checkpoint.
N.A
=> Save Blocks Before Migrating

shared/testutil/assertions.go
Bug fix
- Fixes minor display issue where full path of tested file is displayed on error:
- Also updates the file being displayed to the one that failed (not one calling assertion)
N/A
=> Fixes display issue in testutils/assert

beacon-chain/p2p/sender.go, beacon-chain/sync/error.go, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_chunked_response.go
=> QSP 32: Add Appropriate Stream Deadlines for RPC Requests

shared/roughtime/roughtime.go
> Bug fix
The log addition in #6575 will cause a panic if `res.Error() != nil`. This PR properly handles such scenario
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x48c89c5]
goroutine 1 [running]:
github.com/prysmaticlabs/prysm/shared/roughtime.recalibrateRoughtime()
shared/roughtime/roughtime.go:57 +0x225
github.com/prysmaticlabs/prysm/shared/roughtime.init.0()
shared/roughtime/roughtime.go:45 +0x22
```
=> Handle roughtime response error

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
This PR ensures cached justified check point in service struct is properly updated during initial sync.
An intermittent issue was caught during initial batch sync where justified check point didn't get cache and a node has to check ancestor block all the way back from genesis
=> Update justified point for batch sync

validator/client/metrics.go, validator/node/BUILD.bazel, validator/node/node.go
Fix inconsistent pubkey formatting in logs. Use `bytesutil.Trunc` for the public keys. 
Fixes #6595
=> Fix inconsistent pubkey formatting in logs 

validator/accounts/v2/cmd_accounts.go, validator/accounts/v2/list.go, validator/accounts/v2/new.go, validator/accounts/v2/wallet.go, validator/flags/flags.go, validator/keymanager/v2/direct/direct.go, validator/keymanager/v2/direct/mnemonic.go, validator/node/node.go
CLI Improvements
This is part of #6220, allows for the creation of accounts without requiring any input from the user by ensuring setting the flags work as intended.
The following flags are added to allow this:
`--password-file`: for passing in a file with a password to copy to the wallet's passwords directory
`--skip-mnemonic-confirm`: to skip the y/n confirm on the withdrawal key
=> Allow creating new accounts to be non-interactive

validator/main.go, validator/node/node.go
> Bug fix (cosmetic)
This fixes a cosmetic bug introduced in #6489. `selectV1Keymanager` was getting called twice. This removes the extra instance inside `ExtractPublicKeysFromKeymanager` 
Fixes #6601 
=> Fix duplicated selectV1Keymanager

shared/testutil/BUILD.bazel, shared/testutil/assert/BUILD.bazel, shared/testutil/assert/assertions.go, shared/testutil/assert/assertions_test.go, shared/testutil/assertions/BUILD.bazel, shared/testutil/assertions/assertions.go, shared/testutil/require/BUILD.bazel, shared/testutil/require/requires.go, shared/testutil/require/requires_test.go
Bug fix
- Assertions shouldn't depend on any of our other packages, otherwise there's a possibility for import cycle (assertions are imported into test that imports such a dependency, which in turn may import sth from the package being tested). This PR fixes this by decoupling assertions base file.
N/A
=> Resolves possible import cycle in testutils assertions

beacon-chain/p2p/connection_gater_test.go, beacon-chain/p2p/peers/status.go, beacon-chain/p2p/peers/status_test.go, beacon-chain/p2p/service.go, beacon-chain/p2p/testing/mock_peersprovider.go, beacon-chain/p2p/testing/p2p.go
Audit Feedback
them from re-dialing us or re-connecting with us.
Part of #6327 
=> QSP 23: Prune Peers From Peer Handler

beacon-chain/blockchain/receive_block_test.go, beacon-chain/cache/BUILD.bazel, beacon-chain/cache/attestation_data_test.go, beacon-chain/cache/checkpoint_state_test.go, beacon-chain/cache/committee_fuzz_test.go, beacon-chain/cache/committee_test.go, beacon-chain/cache/depositcache/BUILD.bazel, beacon-chain/cache/depositcache/deposits_cache_test.go, beacon-chain/cache/depositcache/pending_deposits_test.go, beacon-chain/cache/hot_state_cache_test.go, beacon-chain/cache/skip_slot_cache_test.go, beacon-chain/cache/subnet_ids_test.go
applies `testutil/assert` and `testutil/require` to cache tests
Part of #6590
I don't know how to assert that a slice variable is `nil`. Trying `assert.Equal(t, ([]unit64)(nil), x)` results in
```
panic: runtime error: comparing uncomparable type []uint64 [recovered]
panic: runtime error: comparing uncomparable type []uint64
```
=> Applies assertion funcs to cache tests

validator/accounts/v2/BUILD.bazel, validator/accounts/v2/cmd_wallet.go, validator/accounts/v2/new.go, validator/accounts/v2/wallet_create.go, validator/accounts/v2/wallet_create_test.go, validator/flags/flags.go
> Feature
This PR allows us to run `prysm validator wallet-v2 create` non-interactively with a pure, flag-based setup.
**Remote Keymanager Wallet Creation**
```
bazel run //validator -- wallet-v2 create \
--wallet-dir=/tmp/wallet \
--passwords-dir=/tmp/walletpasswords \
--keymanager-kind=remote \
--grpc-remote-address=host.example.com:4000 \
--remote-signer-crt-path=/tmp/client.crt \
--remote-signer-key-path=/tmp/client.key \
--remote-signer-ca-crt-path=/tmp/ca.crt
```
**Direct Keymanager Wallet Creation**
```
bazel run //validator -- wallet-v2 create \
--wallet-dir=/tmp/wallet \
--passwords-dir=/tmp/walletpasswords \
--keymanager-kind=direct
```
Part of #6220
=> Accounts V2: Create Wallet Non-Interactively + Add Test Coverage

beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go
Bug fix
This prevents a panic out of range issue.
N/A
This bug was discovered by taking a randomized beacon state and advancing empty state transitions until the next epoch start.
Here's the beacon state that generated this input: [crash-2994ca80dfcefc8e626f965c109dcc762710427e.zip](https://github.com/prysmaticlabs/prysm/files/4940944/crash-2994ca80dfcefc8e626f965c109dcc762710427e.zip)
Reproduction steps:
- UnmarshalSSZ
```go
nextEpoch := helpers.SlotToEpoch(s.Slot())+1
if _, err := stateutil.ProcessSlots(context.Background(), s, helpers.StartSlot(nextEpoch)); err != nil {
panic(err)
}
```
=> Add regression test found by fuzzer

beacon-chain/core/epoch/precompute/reward_penalty.go, beacon-chain/core/epoch/precompute/reward_penalty_test.go
Bug fix
Fuzz testing caught this again.
```
panic: runtime error: index out of range [256] with length 256
```
Follow up to #6629.
=> Check for array out of bounds when calculating proposer delta -- follow up

shared/testutil/assert/assertions.go, shared/testutil/assert/assertions_test.go, shared/testutil/assertions/assertions.go, shared/testutil/require/requires.go, shared/testutil/require/requires_test.go
Other/Usability
- Order of arguments in `assert.Equal()` and `require.Equal`, was `expected value, wanted value`. This seems to be confusing (the reason this particular order was chosen was because it seems more extensive libs, like testify, are using it).
- This PR makes sure that there's no assumption on what is expected and what is wanted -- just two values (`x` and `y` like in `go-cmp`), and if they are not equal, they are reported:
N/A
=> Fixes issue with vals order in assert.Equal

beacon-chain/core/epoch/precompute/BUILD.bazel, beacon-chain/core/epoch/precompute/attestation.go, beacon-chain/core/epoch/precompute/attestation_test.go, beacon-chain/core/epoch/precompute/reward_penalty_test.go, beacon-chain/core/state/transition_test.go, beacon-chain/rpc/beacon/validators_test.go
Bug fix
Found by fuzz testing. 
```
panic: runtime error: integer divide by zero
--
  |  
  | goroutine 17 [running, locked to thread]:
  | github.com/prysmaticlabs/prysm/beacon-chain/core/epoch/precompute.attestationDelta(0x10c001334000, 0x10c001334340, 0x1, 0x0, 0x0, 0x0)
  | beacon-chain/core/epoch/precompute/reward_penalty.go:88 +0x805
  | github.com/prysmaticlabs/prysm/beacon-chain/core/epoch/precompute.AttestationsDelta(0x10c000150000, 0x10c001334000, 0x10c000c2f800, 0x100, 0x100, 0x20, 0x20, 0x20, 0x1, 0x1, ...)
  | beacon-chain/core/epoch/precompute/reward_penalty.go:66 +0x14b
  | github.com/prysmaticlabs/prysm/beacon-chain/core/epoch/precompute.ProcessRewardsAndPenaltiesPrecompute(0x10c000150000, …
```
=> ProcessAttestations: Add requirement that inclusion distance is not zero

shared/testutil/assert/assertions.go, shared/testutil/assert/assertions_test.go, shared/testutil/assertions/assertions.go, shared/testutil/require/requires.go, shared/testutil/require/requires_test.go
Other/Tests Usability
- Both `testutil/assert` and `testutil/require` accept optional custom messages, this PR extends the capability by allowing to pass params to such messages (basically enabling `spritf`) i.e. currently we can pass in just messages in form:
```golang
assert.Equal(t, foo, bar, "Expected equality (for slot 12)")
// error will be in form: Expected equality (for slot 12), got: bar want: foo
```
with this PR we can have the following:
```golang
assert.Equal(t, foo, bar, "Expected equality (for slot %d)", 12)
```
- Internally, `sprintf` is used -- so one can have any number of params (including zero)
N/A
- Assertions API is still kept …
=> Extends assertions to accept fmt params

shared/testutil/assert/assertions_test.go, shared/testutil/assertions/assertions.go, shared/testutil/require/requires_test.go
Other/Test Usability
- When comparing scalars having equal numeric values, assertions produce hard to understand messages, like:
> Values are not equal, want: 42, got: 42
- The reason those values are not equal is they have different type. This PR, updates error printing to include type info:
> Values are not equal, want: 42 (int), got: 42 (uint64)
N/A
- When reporting failed equality test, order of got/want, has been changed to want/got (to mimic passed in params to `(assert|require).(Deep)Equal`)
=> Adds type info into equality assertions

beacon-chain/rpc/beacon/blocks.go
Other
The improper context was being used. Any context deadline or timeout would not be respected otherwise. Additionally, this improves jaeger span collection (the call hierarchy would be preserved in the span).
N/A
=> Use correct context for chainHeadRetrieval

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/initial-sync/round_robin_test.go
Bug fix
- When no peers with finalized blocks are found, queue will spin forever. This PR will periodically (when all FSMs are marked as skipped, and before resetting them) check if best finalized slot from peers is ahead of current head. If it is behind (or equal), queue cancels -- allowing normal sync to take control. If node falls behind, normal sync will re-trigger init-sync.
Fixes #6655
=> Handles case when no peers with finalized blocks are found

beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/getter_test.go
Bug fix
This method claims to invalidate the cache, but there were some code paths where it didn't invalidate the cache. 
Using defer will ensure that all code paths will invalidate the cached value.
None reported.
Part of an investigation for corrupted hot state caches.
=> Stategen: always invalidate hot cache state in StateByRootInitialSync

validator/node/node.go
> Bug fix
Accounts V2 was not working properly at runtime as we would still select the v1 keymanager version despite the --enable-accounts-v2 flag being enabled. This PR fixes it.
=> Fix Validator Accounts-V2 Runtime

beacon-chain/core/blocks/BUILD.bazel, beacon-chain/core/blocks/attestation.go, beacon-chain/core/blocks/attestation_test.go
Part of #6716 
Addresses point `Reorder conditions to validator target_epoch before its use`
Wow! We were missing the committee ID check this whole time. This PR adds the committee ID check and a regression test
Reference: https://github.com/ethereum/eth2.0-specs/pull/1996
=> Add committee ID check to process attestation

beacon-chain/core/helpers/committee.go
Part of #6716 
Addresses point `Avoid state in p2p validation, compute committee count per slot for epoch`
Our version of `get_committee_count_per_slot` was already optimized by passing in `active_validator_count` instead of `state` and `epoch`. I updated the pseudocode  comments. 
Reference: https://github.com/ethereum/eth2.0-specs/pull/1904
=> Update comments for `get_committee_count_per_slot`

beacon-chain/blockchain/head.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/receive_block.go, beacon-chain/blockchain/service_test.go
> Bug fix
As stated in #6728, the pre-state retrieval is broken due to `saveHeadNoDB` invalidates the saved state.
1.) Process block 100
2.) Save state 100
3.) Request stategen for state 100 to cache head info, this invalidates caching of state 100 (PROBLEM)
4.) Receive block 101
5.) Request state 100 for pre state to process block 101, caching of state 100 no longer available. Replay blocks for state 100 
This PR changes to:
1.) Process block 100
2.) Save state 100
3.) Cache head info using **passed** state 100 instead of requesting from stategen
4.) Receive block 101
5.) Request state 100 for pre state to process block 101, caching of state 100 is not invalidated. Yay!
Fixes …
=> `saveHeadNoDB ` does not invalidate hot state cache

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/pubsub.go, beacon-chain/p2p/pubsub_test.go, beacon-chain/p2p/service.go
Bug fix
- In `p2p/pubsub` access to the list of handlers for joined topics is not protected by mutex, while concurrent access is allowed. This results in the following failure:
- This PR puts the map behind the mutex.
N/A
=> Fixes issue with concurrent map writes in gossipsub

beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/pending_blocks_queue_test.go, beacon-chain/sync/service.go, beacon-chain/sync/subscriber_beacon_attestation_test.go, beacon-chain/sync/subscriber_beacon_blocks.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, beacon-chain/sync/validate_beacon_attestation.go, beacon-chain/sync/validate_beacon_attestation_test.go, beacon-chain/sync/validate_beacon_blocks.go, beacon-chain/sync/validate_beacon_blocks_test.go
Spec Update
Part of #6716 and corresponding PR in the specs repo is
https://github.com/ethereum/eth2.0-specs/pull/1956
=> Account for Bad Blocks in Gossip

validator/accounts/v2/BUILD.bazel, validator/accounts/v2/accounts_export_test.go, validator/accounts/v2/accounts_import.go, validator/accounts/v2/accounts_import_test.go, validator/accounts/v2/cmd_accounts.go, validator/accounts/v2/prompt.go, validator/accounts/v2/wallet.go, validator/accounts/v2/wallet_test.go, validator/flags/flags.go
Accounts V2 Feature 
This PR changes `accounts-v2 import` to take in a `--keys-dir`, which is a folder containing keystore files.
=> Accounts-V2: Change accounts-v2 import to use directory of keystores

validator/accounts/v2/accounts_import.go, validator/accounts/v2/accounts_list.go, validator/accounts/v2/cmd_accounts.go, validator/accounts/v2/prompt.go, validator/accounts/v2/testing/mock.go, validator/accounts/v2/wallet.go, validator/accounts/v2/wallet_create.go, validator/accounts/v2/wallet_recover.go, validator/flags/flags.go, validator/keymanager/v2/derived/derived.go, validator/keymanager/v2/derived/mnemonic.go, validator/main.go, validator/node/node.go, validator/usage.go
Bug fix and cleanup
Part of #6723, this solves some of the issues reported by rkapka. Issues includes:
--skip-mnemonic-confirm being on `accounts-v2 create help`
--password-file flag not being allowed in runtime
Allowing "y" or "Y" for prompt confirmation entry.
Cleaning up errors for invalid words entered for mnemonics, or just entirely invalid mnemonics
Fixing formatting of accounts list from derived vs. non-hd
Solves some formatting and test issues for logs 
Adds an error if you try to import non-HD accounts into a HD wallet 
Also fixes a bug with password file entry
=> Accounts V2: Fix issues reported by rkapka

beacon-chain/blockchain/process_attestation_test.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/forkchoice/interfaces.go, beacon-chain/forkchoice/protoarray/BUILD.bazel, beacon-chain/forkchoice/protoarray/nodes_test.go, beacon-chain/forkchoice/protoarray/store.go
> Feature
Added a more performant way to retrieve ancestor root for a given block slot. This utilizes fork choice store's DAG  structure in memory for look back.  Before it was using recursive DB look up and it became a bottleneck at 200 epochs no finality.
Before:
After:
Fixes #6750 
=> Faster ancestor root look up via fork choice store

shared/prometheus/service.go, shared/prometheus/service_test.go
Bug fix
The healthz must return an error HTTP status code.
Fixes a regression from #5558
For this, I have chosen 503 since that indicates that the server is not ready to serve requests.
=> Return 503 on healthz with error

go.sum, shared/promptutil/BUILD.bazel, shared/promptutil/prompt.go, shared/promptutil/validate.go
Utility addition
This PR adds a shared promptutil utility for assisting with any needs we have for prompts. Since we don't need much functionality and our existing prompt option had several unsolvable bugs.
The util is made of `prompt.go` which holds prompt functions and `validate.go` which holds functions used for validating text entered.
=> Add promptutil to shared/promptuil

beacon-chain/p2p/encoder/ssz.go, beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go
> Bug fix
This PR removes the deprecated fallback which existed in our codebase for compatibility with Onyx and Altona testnets:
```
// Check if we are unmarshalling block roots
// and then lop off the 4 byte offset and try
// unmarshalling again. This is temporary to
// avoid too much disruption to onyx nodes.
// TODO(#6408)
if _, ok := to.(*[][32]byte); ok {
return ssz.Unmarshal(b[4:], to)
}
```
As this was not properly checking if the input had a length of at least 4 before decoding. This piece of code is no longer needed.
=> Remove Deprecated SSZ Decode Edge Case for BeaconBlocksByRoots

scripts/tag-versioned-docker-images.sh
Feature
As title describes. This will allow users to have a more canonical option for choosing docker images.
Edit: I've already this for v1.0.0-alpha.17
=> Add a script to tag docker images as stable or by their git tag version

shared/promptutil/validate.go, shared/promptutil/validate_test.go
Currently, accounts-v2 does not allow passwords with spaces, but the eth2.0-deposit-cli does. This fixes the discrepancy for users by allowing spaces in our passwords.
=> Allow spaces in keystore account passwords

validator/accounts/v2/accounts_import.go, validator/accounts/v2/accounts_import_test.go, validator/accounts/v2/prompt.go
Feature
As title describes, I tried to put the full path to the keystore I wanted to enter, but the CLI requires a directory. So I have adapted the code to allow for either a directory or a single file for importing.
N/A
Tested once at runtime.
=> Accounts V2: Allow for user to specify single file rather than directory for keystore import

validator/accounts/v2/wallet.go, validator/keymanager/v2/direct/direct.go
Other
This is a minor improvement on the logging of progress bars.
Before this PR, there was no new line after the progress bar and the next log message appeared on the same line.
```
[2020-07-31 12:53:09]  INFO node: Starting validator node version=Prysm/{STABLE_GIT_TAG}/ca2c0f9844143d24b743f8bd2663125d176bda52. Built at: 2020-07-31T12:53:09-07:00
100% [===============================================================]  [0s:0s][2020-07-31 12:53:09]  WARN validator: You are using an insecure gRPC connection. If you are running your beacon node and validator on the same machines, you can ignore this message. If you want to know how to enable secure connections, see: …
```
=> Accounts V2: improve progressbar feedback

validator/accounts/v2/wallet.go
Feature
As title describes. This feature will log a warning to the user suggesting that they edit the config and will override the config value at runtime as the user desires.
Fixes #6794
=> Accounts V2: Allow user to override password-dir set in the wallet config

validator/accounts/v2/accounts_list.go
> Bug fix
When users import their accounts from the eth2.0 deposit cli, Prysm does not have access to their deposit data, so we should display a nice message if the user runs accounts-v2 list --show-deposit-data.
```
Account 7 | ghastly-top-narwhal | Created 16 minutes ago
[validating public key] 0xa77747e96475d26a750218c...
If you imported your account from the eth2 launchpad, you will find your deposit_data.json in the eth2.0-deposit-cli's validator_keys folder
```
Fixes #6806
=> Fix Accounts List Show Deposit Data When Coming From Eth2.0 Deposit CLI

validator/accounts/v2/BUILD.bazel, validator/accounts/v2/wallet.go, validator/accounts/v2/wallet_test.go
Fixes #6800
This considers where an empty wallet (folder) could be one with random files in it.
/wallet/hello_word.  <- wallet is empty
/wallet/derived. <- wallet is not empty
=> Fix empty wallet check

beacon-chain/node/node.go, validator/main.go, validator/node/node.go
Fixes #6820
This ensures that loaded config does not get over written by moving `LoadChainConfigFile` after `ConfigureBeaconChain`
=> `Load` config after `Configure` config

shared/promptutil/validate.go, validator/keymanager/v2/direct/direct.go, validator/keymanager/v2/direct/import.go
> Bug fix
Currently, during the account import process, if a single password fails to confirm, we prompt the user to input it once more. However, this makes us re-prompt for every single following password which makes for a choppy user experience. Additionally, the strong entropy password check is too strong, with many users complaining their typical 'strong passwords' are not making the cut.
=> Better Password Input Experience

beacon-chain/flags/base.go
`DepositContractFlag`'s default was still pointing to Onyx. It doesn't feel right. This updates the default to Medalla contract address.
=> Update `DepositContractFlag` default to Medalla

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/discovery.go, beacon-chain/p2p/service_test.go, beacon-chain/p2p/subnets.go
Bug Fix
If a peer is connected to a very small number of nodes or zero, then this method will cause excessive CPU usage
and build up of memory.
To resolve this we look at the total size of the local table and then select a minimum between that and our lookup limit. So that 
we wont perform lookups for a very small number of peers.
N.A
=> Use Less Intensive Search

validator/accounts/v2/accounts_list.go, validator/accounts/v2/prompt.go, validator/accounts/v2/wallet.go, validator/keymanager/v2/derived/BUILD.bazel, validator/keymanager/v2/derived/derived.go, validator/keymanager/v2/direct/BUILD.bazel, validator/keymanager/v2/direct/direct.go
This PR adds back the displaying of deposit data to show the eth1 deposit tx data users can then easily copy into metamask
Also, gets rid of the following issues:
- Not able to open a wallet if other files exist in the directory
- Fix relative paths in various inputs
- Fix the experience of not asking users to migrate if they are already using an HD wallet
=> Add Back Displaying Deposit Data + Misc Bugs

beacon-chain/core/helpers/attestation.go
Fixed an error log to avoid displaying underflow.
As seen in #6855
```
[2020-08-03 18:28:35] ERROR validator: Could not request attestation to sign at slot error=rpc error: code = InvalidArgument desc = invalid request: attestation slot 21233 not within attestation propagation range of 18446744073709551589 to 5 (current slot) pubKey=0x903e2989e744 slot=21233
```
=> Validate attestation: fix error log

validator/accounts/v2/wallet_create.go
Other
This will prevent a panic in the case that wallet is nil.
I am not sure how this wallet could be nil, but it has been reported on twitter.
=> Return an error when wallet is nil rather than panic

validator/accounts/v2/wallet.go
No tracking issue. The code above panics on the last line for certain users as `info` could be nil. It is unclear how this could happen, but we prevent it for now by adding a nil check and returning false
```go
// Checks if a directory indeed exists at the specified path.
func hasDir(dirPath string) (bool, error) {
fullPath, err := expandPath(dirPath)
return false, err
}
info, err := os.Stat(fullPath)
if os.IsNotExist(err) {
return false, nil
}
return info.IsDir(), err
}
```
=> Fix Panic in Wallet HasDir()

validator/accounts/v2/wallet.go
No tracking issue - this simply returns an error from the helper function hasDir in wallet.go for accounts v2, originally from #6857
=> Return Err in Wallet.HasDir function

beacon-chain/node/node.go
Other
We are planning to remove this default value in the next release. This error level message gives users time to reconfigure their nodes before incurring a breaking change.
Part of https://github.com/prysmaticlabs/prysm/issues/6884
=> Warn users of upcoming breaking change to default value for eth1 provider flag

beacon-chain/rpc/validator/proposer.go
Other
Add additional spans to the GetBlock routine.
Part of investigation for https://github.com/prysmaticlabs/prysm/issues/5801
=> Add trace spans to GetBlock methods for a better understanding of block proposal delays

beacon-chain/rpc/validator/proposer.go
> enhancement
Remove duplicated `deleteAttsInPool`, it's already done in `ReceiveBlock`. 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/blockchain/receive_block.go#L57
Fixes #
=> RPC/proposer: remove duplicated delete pool attestations

beacon-chain/operations/attestations/kv/aggregated.go, beacon-chain/operations/attestations/kv/aggregated_test.go, beacon-chain/operations/attestations/prune_expired.go
> Enhancement
Check if the attestation already exists (bitfield overlaps) in pool before saving it to the pool. This is a cheap and nice way to reduce the size of attestation pool. I also found out that metric update was not used so I added the usage back.
Observed reduction in the attestation pool size
Fixes #
=> Check before saving attestation to pool

validator/accounts/v2/accounts_import.go
We should fail the import if we are importing from an empty directory instead of just showing `successfully imported 0 accounts`
Fixes #6860
=> Fail Immediately if Importing Accounts from Empty Directory

beacon-chain/powchain/service.go
Log Display Clean Up
In the event the connected eth1 node is down, the beacon node would constantly log dial errors. This instead makes those
logs much less frequent in order to stop the node from being spammed.
None
=> Log Error Logs Less Frequently

beacon-chain/blockchain/head.go, beacon-chain/blockchain/info.go, beacon-chain/forkchoice/protoarray/BUILD.bazel, beacon-chain/forkchoice/protoarray/ffg_update_test.go, beacon-chain/forkchoice/protoarray/helpers.go, beacon-chain/forkchoice/protoarray/no_vote_test.go, beacon-chain/forkchoice/protoarray/node.go, beacon-chain/forkchoice/protoarray/nodes.go, beacon-chain/forkchoice/protoarray/nodes_test.go, beacon-chain/forkchoice/protoarray/store.go, beacon-chain/forkchoice/protoarray/types.go, beacon-chain/forkchoice/protoarray/vote_test.go, beacon-chain/rpc/debug/forkchoice.go, beacon-chain/rpc/debug/forkchoice_test.go, go.sum
> Clean up
Currently Proto array fork choice exports all its node and store types. This is not a good practice and is not safe.
This PR un-exports all the types and implements proper getters around them.
Fixes #
=> Unexport protoarray forkchoice types

beacon-chain/sync/subscriber_beacon_attestation.go, beacon-chain/sync/validate_beacon_attestation.go
Reverts prysmaticlabs/prysm#6908
I was notified that #6908 has caused e2e to flake more than usual with the following failures: 
```
TestEndToEnd_MinimalConfig/validators_participating_epoch_14: endtoend_test.go:117: evaluation failed for epoch 14: validator participation was below for epoch 13, expected 0.950000, received: 0.946996
```
Let's revert it for the time being and debug
=> Revert "Subscriber: use target epoch for hasSeen cache"

beacon-chain/state/stategen/replay.go, beacon-chain/state/stategen/replay_test.go
> Bug fix
We have a bug in the loading of historical blocks to replay cold state. We did not check whether the block is finalized before replaying the blocks. Block explorers often see sharp drop of participations and that's due to nodes started the replay using an orphaned block. More analyses: https://github.com/prysmaticlabs/prysm/issues/6927#issuecomment-671613484  
The fix was to implement `loadFinalizedBlocks` and use that for cold state generation
Fixes #6927 
=> Fix loading historical blocks to replay cold state

beacon-chain/p2p/discovery.go, beacon-chain/p2p/discovery_test.go
=> Support Domains For Discovery

beacon-chain/blockchain/process_attestation.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/service.go, beacon-chain/core/helpers/slot_epoch.go, beacon-chain/core/helpers/slot_epoch_test.go, beacon-chain/rpc/beacon/validators_stream.go, beacon-chain/rpc/validator/status.go, beacon-chain/sync/initial-sync/service.go, shared/params/config.go, shared/params/testnet_medalla_config.go
> Feature
This PR created and utilized `params.BeaconChain().GenesisTime` to reference in validator client and beacon chain, if available. Added a helper to check If the genesis time is available for the given network and fallback to the original design of reading `state.GenesisTime`.
Fixes #6545
=> Add and use genesis time in config

shared/testutil/assert/assertions_test.go, shared/testutil/assertions/assertions.go, shared/testutil/require/requires_test.go
Other/Usability
- More verbose output in `assert.DeepEqual()` and `require.DeepEqual()` (uses `%#v` instead of `%v` - so, Go-syntax representation of values will be returned).
- In `Equal()/NotEqual()` methods, we already include type info, so this PR introduces similar output to `DeepEqual()` calls.
N/A
- This functionality came handy when debugging list of `peer.IDs` in peer scorer, as `%#v` displays peer ids as strings, not encoded values.
=> Go syntax-repr in test assertions

tools/sendDepositTx/README.md, tools/sendDepositTx/sendDeposits.go
>
Bug fix
> Feature
Documentation
> Other
The `sendDepositTx` tool is outdated. This PR updates the tool to use Medalla beacon config and updates README
to reflect the current status in terms of geth node being no longer necessary and an updated Deposit Contract Address
in the example.
Fixes #6971
=> Update sendDepositTx tool

beacon-chain/db/kv/blocks_test.go
> Test
DB pkg has block roots test, but it only verified the length of the returned block roots, not the correctness of the block roots. This PR adds an additional test to verify the correctness of the block roots.
Fixes #
=> DB: add block roots test

beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/subscriber_beacon_blocks.go
Other
In the current state of Medalla, it is not unreasonable for a block to fail processing while under load. 
We shouldn't ban these block roots at this moment or potentially find the client stuck, out of sync.
Not reported.
Suggested by @nisdas that this might be an issue.
=> Sync: Dont ban block roots for context.DeadlineExceeded

beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/utils.go, beacon-chain/sync/utils_test.go
> Bug fix
This can panic if the input blocks and roots are different lengths.
```
panic: runtime error: index out of range [146] with length 146
goroutine 31903 [running]:
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).dedupBlocksAndRoots(0xc00012e000, 0xc079ec2800, 0x92, 0x100, 0xc013976000, 0x93, 0x100, 0x0, 0x0, 0xc0136a2d80, ...)
beacon-chain/sync/utils.go:42 +0x505
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).writeBlockRangeToStream(0xc00012e000, 0x1dda6a0, 0xc06a405320, 0x1325f, 0x1345e, 0x1, 0x1df3860, 0xc04efce700, 0x0, 0x0)
beacon-chain/sync/rpc_beacon_blocks_by_range.go:141 +0x646
github.com/prysmaticlabs/prysm/beacon-chain/sync.(*Service).beaconBlocksByRangeRPCHandler(0xc00012e00 …
```
=> Sync: fix panic and check blocks + roots lengths

beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/subscriber_beacon_blocks.go
Reverts prysmaticlabs/prysm#7016
We never return `context.DeadlineExceeded` as the error, it is always wrapped. So the original PR does not do anything helpful.
=> Revert "Sync: Dont ban block roots for context.DeadlineExceeded"

beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
=> Do Not Retrieve From DB For Block Roots

beacon-chain/sync/initial-sync/blocks_queue.go
Other/Improvement
- Since there's no point in quickly spinning on existing peers, when no peers with high enough finalized slot is found, we add a period of 15s (configurable) before proceeding.
- Number of errors tolerated are increased to 1000, so 1000*15 sec (~4 hours) of possible init-sync spinning is allowed by this update, then init-sync gives up.
Fixes #
=> Wait interval, before finalized peers re-checked

beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/pending_blocks_queue_test.go, beacon-chain/sync/validate_beacon_attestation.go
Bug Fix
In #7036 , we allow duplicate blocks to be inserted into the pending block cache. This PR fixes that and 
makes sure duplicates are rejected.
N.A
=> Reject Duplicate Blocks From Being Saved

slasher/flags/flags.go, slasher/main.go, slasher/node/node.go, slasher/usage.go
Feature
On times of no finality spreads between source and target epoch can be great. as a result many spans have to be updated on the slasher. When trying to run validator `--enable-external-slasher-protection` the time it take for the slasher to update the spans is critical and therefore relevant spans must be cached. this pr adds a flag that sets slasher span cache size to enable people to run slasher protection at times like this by using more memory to cache spans
Fixes #7030
=> Slasher span cache size flag

beacon-chain/sync/pending_blocks_queue.go, beacon-chain/sync/pending_blocks_queue_test.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_beacon_blocks.go
Minor improvement from #7044
This PR uses intended `seenPendingBlock` mapping to reject duplicated block in insertion method. Also updated the APIs for insertion and deletion to include block root we can update seenPendingBlock` mapping within the method to avoid disparity. 
I also updated the tests. Now the test results look more realistic than before
=> Use map to reject seen pending block

beacon-chain/sync/rpc_status.go
Other
context.Background() was not appropriate.
=> Use correct context for IsFinalizedBlock call

beacon-chain/p2p/service.go, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/rpc.go
Log Improvement
To reduce confusion for node runners, this shifts all these logs to debug. As they can be very noisy and confusing
if you have a large number of peers.
N.A
=> Shift Sync Warn and Error Messages To Debug

beacon-chain/state/stategen/BUILD.bazel, beacon-chain/state/stategen/hot.go
> Feature
Adding a really useful histogram for replay block count. Replaying blocks for a state is a rare event, but when it happens, this provides node operator details on the full picture of the penalties.
```
replay_blocks_count_bucket{le="64"} 12
replay_blocks_count_bucket{le="256"} 18
replay_blocks_count_bucket{le="1024"} 27
replay_blocks_count_bucket{le="2048"} 27
replay_blocks_count_bucket{le="4096"} 27
replay_blocks_count_bucket{le="+Inf"} 27
replay_blocks_count_sum 7442
replay_blocks_count_count 27
```
=> Add replay block count metric

beacon-chain/state/stategen/hot.go, beacon-chain/state/stategen/hot_test.go
> Feature
When the node is recursively searching back for an ancestor state, it checks if the state exists in:
1. DB
2. Epoch boundary cache
3. Finalized check point
This PR adds check for hot state cache. This is a nice gimme with 0 cost.
Fixes # N/A
=> Use hot state cache for replay

shared/testutil/assert/assertions.go, shared/testutil/assertions/assertions.go, shared/testutil/assertions/assertions_test.go, shared/testutil/require/requires.go
Other/Tests
- Adds `DeepNotEqual` assertion (we have `Equal/NotEqual` assertions, but only `DeepEqual` atm - for consistency, and because I needed on in #7003, this PR adds this extra assertion)
N/A
=> Adds DeepNotEqual assertion

beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_attestations_queue_test.go
=> Handle Nil Signature in Pending Queue

shared/testutil/assertions/assertions.go
Other/Optimization
- No need to parse message passed to test assertions, up until that assertion is triggered (if assertion is not failed, message will never be used -- no point to parse it).
N/A
- This issue was noticed when transforming the following code:
```golang
if err != nil && s != nil {
t.Fatalf("state should be nil on err. found: %v on error: %v for state: %v and block: %v", s, err, state, block)
}
```
to 
```golang
require.Equal(t, false, err != nil && s != nil, 
"state should be nil on err. found: %v on error: %v for state: %v and block: %v", s, err, state, block)
```
Custom error message contained `%v` for `state` object which wasn't …
=> Optimizes error message parsing in testutils

beacon-chain/node/node.go
=> Fix Interop Mode

beacon-chain/rpc/validator/server.go, beacon-chain/rpc/validator/server_test.go, validator/accounts/v2/wallet_create.go
Bug Fix
taking longer to start up. This requires that state initialized events are also listened to, to handle cases such as this.
Fixes #6896 , #6325 
=> Listens For State Initialized Event

beacon-chain/flags/base.go
`--new-state-mgmt` is on by default
=> Update enable-debug-rpc-endpoints help message

beacon-chain/sync/BUILD.bazel, beacon-chain/sync/pending_blocks_queue.go
=> Fix Go Builds

beacon-chain/flags/base.go, beacon-chain/node/node.go, beacon-chain/powchain/service.go
=> Remove Default Prylabs ETH1 Endpoint

beacon-chain/powchain/block_cache.go, beacon-chain/powchain/block_cache_test.go, beacon-chain/powchain/block_reader.go, beacon-chain/powchain/block_reader_test.go, beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
All the data we require is stored in block headers and contract logs.
N.A
=> Request Headers From ETH1 Node Instead of Blocks

beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
Other
This PR gives users more immediate feedback if they did not provide eth1 node and have not already synced a genesis state.
Follow up to #7120 
=> Return an error if no eth1 endpoint defined and we do not have genesis state

beacon-chain/rpc/beacon/BUILD.bazel, beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
> Bug fix
I had an incorrect assumption that we should include in orphaned attestations for participation. Danny pointed out that is wrong and i have been thinking and agreed it is wrong. Although it wouldn't change the outcome much because `process_epoch` would have rejected orphaned atts, but it's unnecessary work for the node.
Reference: https://github.com/prysmaticlabs/prysm/issues/7116#issuecomment-682204891
=> Don't include orphaned atts

beacon-chain/blockchain/metrics.go
> Feature
Adding these metrics as we found them useful in other clients. 
- beacon_prev_epoch_active_gwei
- beacon_prev_epoch_source_gwei
- beacon_prev_epoch_target_gwei
- beacon_prev_epoch_head_gwei
The metrics tracking doc: https://hackmd.io/D5FmoeFZScim_squBFl8oA
Fixes #
=> Add previous epoch participation metrics

beacon-chain/rpc/validator/exit.go, beacon-chain/rpc/validator/exit_test.go, beacon-chain/sync/validate_voluntary_exit.go, beacon-chain/sync/validate_voluntary_exit_test.go
> Bug fix
Spec calls for using state slot to verify exit signature, not the slot in the exit object itself.
Fixes # N/A
=> Use state slot to verify exit signature

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
> Bug fix
Initial sync code path was subjected to an attack where block could link to parent that's far back in the history. The reason was we did not verify block descendent in `verifyBlkPreState`. This PR moved it from `getBlockPreState` (not initial sync code path) to `verifyBlkPreState` (both initial sync and regular sync code path). 
Tested run time with validator. And tested run time syncing from genesis
=> Check initial sync block is descendent of current finalized block

beacon-chain/core/helpers/BUILD.bazel, beacon-chain/core/helpers/attestation.go, beacon-chain/core/helpers/attestation_test.go, beacon-chain/core/helpers/slot_epoch.go, beacon-chain/core/helpers/slot_epoch_test.go, shared/mathutil/math_helper.go, shared/mathutil/math_helper_test.go
=> Verify Attestation Time Correctly

beacon-chain/sync/initial-sync/initial_sync_test.go, beacon-chain/sync/rpc_beacon_blocks_by_range_test.go
> Other/Fix Mock
- When implementing more strict validation/control on blocks returned from `init-sync` queue, I've discovered some failing tests. Those failures where because of a more strict assertions:
- returned block slots from `BeaconBlocksByRange()` MUST be within `[start, start+count*step)` range
- number of returned blocks, MUST be less or equal to `count`
- I've written a regression test `TestRPCBeaconBlocksByRange_EnforceResponseInvariants()` which proved that our `beaconBlocksByRangeRPCHandler` works correctly and honours invariants. After a bit of digging, the problem was discovered to be with our mock code i.e. on production invariants are honoured, but in our tests we are off by one.
- This PR fixes …
=> Asserts response invariants in beaconBlocksByRange

validator/client/aggregate.go, validator/client/aggregate_test.go
> Bug fix
`aggregateAndProofSig ` did not return upon errors. This PR added the return for that
Fixes # N/A
=> Ensure `aggregateAndProofSig` returns when err'ing

beacon-chain/rpc/validator/aggregator.go, beacon-chain/rpc/validator/aggregator_test.go
> Feature
`SubmitSignedAggregateSelectionProof` in aggregator RPC server should block attestations with zero hashes signatures
=> Prevent zero hashes signatures in `SubmitSignedAggregateSelectionProof`

shared/asyncutil/BUILD.bazel, shared/asyncutil/debounce.go, shared/asyncutil/debounce_test.go
Other/Refactoring/Minor fixing
- cc @rauljordan
=> Improves asyncutils/Debounce

beacon-chain/core/blocks/block_operations_fuzz_test.go, beacon-chain/core/blocks/header.go, beacon-chain/core/blocks/randao.go, beacon-chain/core/blocks/spectest/block_header_test.go, beacon-chain/core/state/transition.go, fuzz/block_header_fuzz.go
Reverts prysmaticlabs/prysm#7180
Saw in the local running node with latest master, block proposal failed to calculate state root due to incorrect deposit count. I suspect this is the offender. This needs more testing in the run time in especially with block proposals using full deposits. Will revert this for today's release.
cc on call @rauljordan
=> Revert "Pipelines for `ProcessBlockNoVerifyAttSigs` and `ProcessBlockStateRoot`"

beacon-chain/operations/attestations/prepare_forkchoice.go, beacon-chain/operations/attestations/prune_expired.go, beacon-chain/p2p/peers/scorer_manager_test.go, beacon-chain/powchain/service.go, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_queue.go, shared/fileutil/fileutil.go, slasher/beaconclient/chain_data.go, slasher/beaconclient/receivers.go, validator/client/validator.go
> Bug fix
- Timers and tickers open channels, and to release associated resources must be stopped. So, this PR:
- Adds `Stop()` calls whenever they are missing
- In number of places moves `(timer|ticker).Stop()` method closer to object creation (invoking the stopping routing with `defer`). This is done as a more natural way to work with resources in Go: you allocate resources, and if you can, you immediately call `defer releaseFn()`.
N/A
=> Fix unclosed tickers/timers

beacon-chain/core/blocks/exit.go, beacon-chain/core/blocks/exit_test.go, validator/keymanager/v2/direct/direct.go
Bug fix
Corrects two error messages:
- Accounts' `askUntilPasswordConfirms` function returns an error specific to importing accounts, even though it is used from other commands.
- One validator exit precondition returns an error stating that an exit has already taken place, when in reality only the exit proposal has been submitted, and the exit itself is yet to happen.
N/A
N/A
=> Correct accounts and validator error messages

beacon-chain/operations/attestations/kv/seen_bits.go, beacon-chain/operations/attestations/kv/seen_bits_test.go
Bug fix
- If you push the very same attestation multiple times, it gets added to "hasSeen" cache multiple times, which is unnecessary.
- If item is already in cache, cache doesn't grow - but expiration time gets updated (so cache will remember the item for a longer period of time)
N/A
- cc @terencechain
=> Disallows bitlist duplicates in seen_bits cache

beacon-chain/operations/attestations/kv/unaggregated.go, beacon-chain/operations/attestations/kv/unaggregated_test.go, beacon-chain/operations/attestations/pool.go, beacon-chain/operations/attestations/prune_expired.go
Other/Refactoring
- Currently, we remove seen attestations in `UnaggregatedAttestations()` getter:
https://github.com/prysmaticlabs/prysm/blob/c8e93f87893d41ce7335de0c1ae2c786283d516a/beacon-chain/operations/attestations/kv/unaggregated.go#L61-L65
- Conventionally, getters are to obtain data, not modify it -- otherwise it is a bit unintuitive: you request list of unaggregated attestations, and list gets trimmed (seen attestations are removed). If those seen attestations are unnecessary, and to be removed, then there should be a method specifically for that purpose. This PR introduces such a method.
- So, this PR:
N/A
- cc @terencechain
=> Removes attestation pool pruning from UnaggregatedAttestations getter

beacon-chain/rpc/validator/aggregator.go, beacon-chain/rpc/validator/aggregator_test.go
> Feature
Check attestation slot time before broadcast. It was reported that Prysm nodes have attestations with invalid slot range that are floating over the wire. Implementing this as a preventive measure.
Fixes # N/A
cc: @nisdas if this doesn't fix it, then we know the problem is on the sync side + pending attestation queue
We also can do this for unaggregated attestation but i don't think it's necessary (yet)
=> Check attestation slot before broadcast

beacon-chain/operations/attestations/prune_expired.go
A recent commit added an error condition which was inverted, resulting in log output being seen:
```
[2020-09-11 20:18:38] ERROR pool/attestations: Cannot delete seen attestations error=<nil>
[2020-09-11 20:18:50] ERROR pool/attestations: Cannot delete seen attestations error=<nil>
[2020-09-11 20:19:02] ERROR pool/attestations: Cannot delete seen attestations error=<nil>
[2020-09-11 20:19:14] ERROR pool/attestations: Cannot delete seen attestations error=<nil>
```
This fixes the error condition to only report if an error is present.
=> Reverse error condition.

shared/roughtime/roughtime.go
> Bug fix
Even when `EnableRoughtime` was disabled, it still runs through the following code:
```go
// Log Debug Results.
for _, res := range results {
if res.Error() != nil {
log.Errorf("Could not get rough time result: %v", res.Error())
continue
}
log.WithFields(logrus.Fields{
"Server Name": res.Server.Name,
"Midpoint":    res.Midpoint,
"Delay":       res.Delay,
"Radius":      res.Roughtime.Radius,
}).Debug("Response received from roughtime server")
}
```
This PR makes it exit earlier when `EnableRoughtime` is false in function `recalibrateRoughtime()`
Fixes #7183
=> Skip initial roughtime result when `EnableRoughtime` is disabled

beacon-chain/forkchoice/protoarray/nodes_test.go, beacon-chain/forkchoice/protoarray/store.go
>
> Bug fix
Moved out of bound check within the correct scope in forkchoice pkg's `AncestorRoot`
Fixes #7156 
=> Fix out of bound check in `AncestorRoot`

beacon-chain/rpc/validator/proposer_test.go
> Other/Refactoring
- When working on attestation proposing optimization, it proved to be easier to test things if I can scope tests to run (with `--run` when using go cmd, or `--test_filter` when `bazel test`ing). So, this just renames test methods, to allow such a scoping.
N/A
=> Updates proposer tests namings

shared/featureconfig/config.go, shared/featureconfig/flags.go
Part of #7239
Make `--use-check-point-cache` a default flag. The opt out flag is `--disable-check-point-cache`. Check point info cache has been running in the while in the experimental cluster and in my local set up for over the month. Seeing both good and stable results
=> Opt out `--use-check-point-cache`

shared/featureconfig/config.go, shared/featureconfig/flags.go
Part of #7243 
Make `--batch-verify-block` a default flag. The opt out flag is `--disable-batch-verify-block` Batch verify has been running in the while in `exp` mode in a while. We observed both great and stable results
=> Opt out --batch-block-verify

beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/core/helpers/signing_root.go, beacon-chain/core/helpers/validators.go, beacon-chain/db/kv/regen_historical_states.go, beacon-chain/p2p/broadcaster_test.go, beacon-chain/p2p/discovery_test.go, beacon-chain/p2p/fork_test.go
> Bug fix
A few spots in the core pkg that missed to return `err`. This PR addressed it. It added a regression test for one. Rest of the modifications are not good regression test candidates since the only trigger is from HashTreeRoot
=> Core pkg: properly return errs

endtoend/helpers/helpers.go
Resolves #7253. This PR adds a more reasonably sized buffer for reading eth1 data files in e2e tests, resolving some issues on macos catalina.
=> Use Bufio Large Buffer Instead of Scanner for Large Files in E2E

shared/iputils/external_ip.go, shared/iputils/external_ip_test.go
Bug Fix
Due to #6363 , IP address retrieval was broken in Mac OS Catalina due to the node 
trying to bind to a link-local unicast address.
Fixes #7250 
=> Fix IPV6 Address Retrieval

beacon-chain/flags/base.go, beacon-chain/flags/config.go, beacon-chain/main.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/usage.go
New Flag
initial sync and enter regular sync immediately.
N.A
=> Add Flag To Disable Initial Sync

beacon-chain/sync/service.go
> Other
- Follow-up to #7258 
- Without this change, client will be pushed to init-sync via resync (happens when one is 2 epochs behind the majority of the peers). This PR makes sure that resync goroutine is never started.
N/A
=> Disables resync when init-sync is disabled

beacon-chain/cache/BUILD.bazel
> Other/Toolset improve
- When running `bazel run //:gazelle`, I see the following gazelle warning:
- This PR makes sure that when `fuzzing_enabled` flag is not set, `bazel run //:gazelle` doesn't emit any warnings.
N/A
=> Fix gazelle warning when `fuzzing_enabled` is not provided

shared/params/testnet_spadina_config.go
Spadina's fork version is `0x00000002`, not `0x00000000`
Reference: https://github.com/goerli/medalla/tree/master/spadina
=> Update Spadina fork version to 0x02

slasher/rpc/server.go
Bug fix
when no slashing were found in `IsSlashableAttestation` endpoint and update spans failed it didn't return an error
=> Add missing error handling in slasher

beacon-chain/rpc/validator/BUILD.bazel, beacon-chain/rpc/validator/proposer.go, beacon-chain/rpc/validator/proposer_test.go, beacon-chain/rpc/validator/proposer_utils.go
> Feature / Improves att profitability
- ~~Improves profitability by:~~
After discussion with @terencechain this PR will include:
- Extended test suite
- Minor change to att selection (aggregates will be sorted)
Closes #4507
=> Attestation proposing: more tests

validator/accounts/v2/wallet_create.go, validator/accounts/v2/wallet_create_test.go
> Bug fix
Currently, if you invoke wallet-v2 create with a wallet directory targeting a location that already has a wallet, it simply tries to use the provided [new wallet] password to unlock the old wallet without actually overwriting the old wallet.  A silent overwrite is not desirable either.  If the provided password mismatches with the old wallet's password, you get an error message:
`[2020-09-17 12:20:42] FATAL accounts-v2: Could not create a wallet: could not initialize wallet with derived keymanager: could not initialize keymanager: could not initialize derived keymanager: could not decrypt seed configuration with password: invalid checksum`
If the password provided for the new wallet matches the one needed …
=> Improve error message when creating a wallet in place of one that already exists

beacon-chain/sync/validate_beacon_attestation.go, beacon-chain/sync/validate_beacon_attestation_test.go
Part of #7274 
Added to more gossip validations as specified in https://github.com/ethereum/eth2.0-specs/pull/2030
Also tested run time
=> Two more gossip validations for unaggregated atts subnet

validator/accounts/v2/accounts_backup.go, validator/accounts/v2/accounts_backup_test.go
> Bug fix
Currently there is a bug documented in https://github.com/prysmaticlabs/prysm/issues/7280 -- accounts-v2 backup does not back up HD wallet type accounts.  Whenever it is instructed to do so, the program completes without any complaints but there is no backup file written to the filesystem.  This is due to an unnecessary `return nil` statement.
This PR fixes that and adds a regression test.
Fixes #7280 
None
=> Fix accounts-v2 backup so that it can backup HD wallet accounts

beacon-chain/sync/initial-sync/BUILD.bazel, beacon-chain/sync/initial-sync/round_robin_test.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/initial-sync/service_test.go
> Other / Better Tests
- This PR is a part of effort to improve test coverage of `init-sync` package. Our `service.go` file has a petty `~10%` of coverage - which is due to fact that it is not easy to test the service as it is. So, this file needs some, albeit minor, refactoring. The scope of this PR is simple: only code concerning with checking that beacon node head is ready (that code is extracted into its own method and well tested).
N/A
- Previously we had to calls to `Unsubscribe()`, which was pointed out during audit, and which was an intended semantics and we added, a rather long, comment explaining it (see …
=> Init sync refactor state initialization check + tests

WORKSPACE, proto/testing/ssz_static_mainnet_test.go
Other
The tarballs for v0.12.3 spectests were re-uploaded with different data. The sha256 of these files has changed.
Fixes #7277
See: https://github.com/ethereum/eth2.0-specs/issues/2076
=> Fix sha after v0.12.3 tarballs were re-uploaded. Unskip test to resolve #7277.

beacon-chain/sync/service.go, endtoend/endtoend_test.go
> Other / e2e fix
- Currently we rely on `Chain started within the last epoch` message, to decide whether chain has started or not. However, that message is produced by init-sync, and produced not when chain is started but when genesis is in future or current slot is within 0th epoch: 
https://github.com/prysmaticlabs/prysm/blob/b09b1f3fa5851f90c7757aac5695450d289cd140/beacon-chain/sync/initial-sync/service.go#L95-L118
- As you can see (scroll down) above, `s.chainStarted` is not even reached when the checked message is triggered.
- Instead this PR, emits a `Chain started in sync service` in **normal sync** service, and then in e2e test checks for that message.
N/A
**Other notes …
=> Fixes e2e "chain started" check

beacon-chain/rpc/beacon/validators.go
Observed in #7298
For these types of gRPC error, we should log out the error chain as it helps with debug.
=> Log grpc error chain

shared/featureconfig/config.go, shared/featureconfig/flags.go, validator/accounts/v2/cmd_accounts.go, validator/accounts/v2/cmd_wallet.go
=> Fix Validator For Spadina

beacon-chain/powchain/BUILD.bazel, beacon-chain/powchain/block_reader_test.go, deps.bzl
Update Dependency
updated for our `go.mod` file and its related transitive deps.
Fixes #
=> Fix Bazel Reference For Go-Ethereum

tools/analyzers/comparesame/analyzer.go, tools/analyzers/cryptorand/analyzer.go, tools/analyzers/featureconfig/analyzer.go, tools/analyzers/maligned/analyzer.go, tools/analyzers/nop/analyzer.go, tools/analyzers/shadowpredecl/analyzer.go
Documentation
This PR adds package-level comments to all our code analyzers. Previously only a few packages had comments.
N/A
N/A
=> Package-level comments for static analyzers

beacon-chain/sync/initial-sync/blocks_queue_test.go
> Other / Better Tests
- We need to make sure that FSMs state transition functions are tested completely (for all valid input states, output states, possible execution routes). Otherwise, it is hard to guarantee correct execution of state machine functioning when we need to hot patch init-sync (we had to do that on the start of Medalla).
- This PR aims for a full coverage of state transition functions (and the rest of the queue component, if there will some untested areas left).
N/A
=> Improves test coverage of init-sync queue

shared/featureconfig/config.go, shared/featureconfig/flags.go
This PR reverts #7242. Users reported memory spikes. Let's revert it in the mean time we dive deep into this.
Unfortunately i could not auto revert due to merge conflict
=> Revert 7242: Opt out --use-check-point-cache

beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/pending_attestations_queue_test.go
A node shouldn't save pending attestations in the queue if the attestation with the same beacon block root and aggregator index already exists in the queue. Doing so will cause unnecessary attestation processing once the beacon block is available  
Could help with #7279
=> Skip duplicated aggregated attestation in pending queue

validator/keymanager/v2/direct/BUILD.bazel, validator/keymanager/v2/direct/direct.go, validator/rpc/auth.go, validator/rpc/wallet.go
This PR ensures the change wallet password logic functionality works by storing the new bcrypt hash in the wallet path upon modification
=> Fix Change Wallet Password Logic

beacon-chain/cache/hot_state_cache.go
#7098 mistakenly reset hot state cache size from 32 to 16, this PR reverted that line of change.
This could be the reason and the fix for #7279
=> Reset hot state cache size to 32

beacon-chain/p2p/options.go
instantiated in the event it is not set. This is to reduce the burden on stream handling for the node.
N.A
=> Disable Libp2p Protocols

shared/featureconfig/config.go
This PR adds a log warning the user that accounts-v2 will be deprecated soon and they must upgrade to accounts-v2 within the next 2 releases. At that point, accounts-v2 will become the only supported mechanism. For mainnet, we will likely rename the command to simply: `accounts`
=> Warn About Deprecation of Accounts-V1 Within the Next 2 Releases

validator/client/service.go, validator/node/node.go
> Bug fix
Currently, starting a validator client did not offer any visual feedback to the user for their wallet nor their validating keys. This PR adds more detailed logging:
```
[2020-09-25 12:20:28]  INFO node: Opened validator wallet keymanager-kind=derived wallet=/Users/me/Library/Eth2Validators/prysm-wallet-v2/derived
[2020-09-25 12:20:28]  INFO validator: Waiting for beacon chain start log from the ETH 1.0 deposit contract
[2020-09-25 12:20:28]  INFO validator: Beacon chain started genesisTime=2020-08-04 08:00:08 -0500 CDT
[2020-09-25 12:20:28]  INFO validator: Validating for public key publicKey=0x97558e9caf74
[2020-09-25 12:20:28]  INFO validator: Validating for public key publicKey=0xa5a1a09918d2
[2020-09-25 …
```
=> Display More Info for Validating Keys on Startup

shared/bls/blst/bls_benchmark_test.go, third_party/blst/blst.BUILD
Bug Fix
crashes in `x86_64`. 
Part of #7312 
=> Add New Compiler Flags for BLST

validator/accounts/v2/wallet_recover.go, validator/accounts/v2/wallet_recover_test.go
> Bug fix
Fixes #7350 :  In the logic, there is differing behavior between if NumAccounts == 1 or !=1 primarily for console output purposes.  But in the case of NumAccounts ==1 there is a return of nil,nil where it should be w, nil instead
None
=> Fix panic that happens if you wallet-v2 recover 1 account

beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
This fixes #7349 
Removed the incorrect filter based off on activation epoch. Tested run time and verified the result was indeed correct. Added a regression test
=> Fix ListValidators inactive check

beacon-chain/blockchain/service.go, beacon-chain/blockchain/service_test.go
This fixes #7356
This ensures that we dont use zero hashes to retrieve a genesis block for setting head
=> Ensure block root is non zeros for setting head before genesis

beacon-chain/blockchain/process_attestation_test.go, shared/testutil/assertions/BUILD.bazel, shared/testutil/assertions/assertions.go, shared/testutil/assertions/assertions_test.go, slasher/db/kv/block_header_test.go
> Bug fix
- @nisdas has discovered (the hard way, unfortunately) an ugly bug in our `NotNil()` assertion (it didn't fail when pointer with underlying nil value was passed in, as in that case simple `obj == nil` comparison is NOT enough).
- This PR fixes it:
```golang
var nilBlock *eth.SignedBeaconBlock = nil
assert.NotNil(t, nilBlock) // assertion fails
require.NotNil(t, nilBlock) // assertion fails
```
N/A
- This PR also has fixes to two tests `TestStore_UpdateCheckpointState ` and `TestPruneHistoryBlkHdr ` which have been reported as correct only because of a bug in `NotNil()`
=> Fixes NotNil assertion

beacon-chain/rpc/validator/proposer.go
Check error for `filterAttestationsForBlockInclusion` in proposer RPC server
=> Check err for `filterAttestationsForBlockInclusion`

beacon-chain/sync/initial-sync/round_robin.go
> Other / Minor cleanup
- Since 2nd phase of `init-sync` relies on queue now, `refreshTime` constant is redundant now.
N/A
=> Remove unused constant in round robin

tools/sendDepositTx/sendDeposits.go
Within the `sendDeposits` function, the raw password which loaded from a text file for use on the keystore, gets logged on failure. This PR removed the logging of password for security reasons
=> Remove logging of password if fails

shared/featureconfig/config.go
The feature config variable that points to a Flags struct has no lock around it. This variable is modified in some threads and read in others with no synchronization. Concurrent access to shared resources can lead to undefined behavior and possibly data corruption. This PR added a lock around it
=> Add lock around feature config

beacon-chain/sync/BUILD.bazel, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_test.go
Other
The default value for ValidationResult is ValidationAccept.
This is not acceptable when a validation pipeline fails.
This PR sets the default value to ValidationIgnore.
No known issue.
=> Pubsub: fallback to ValidationIgnore in the event of a validation panic

beacon-chain/operations/attestations/kv/block.go, beacon-chain/operations/attestations/kv/block_test.go
If there's block attestations with the same data but different bit lenghts, it will cause panic when inserting block attestations in to operation pool. This PR prevents it by using a length check.
=> Check block attestation length for operation pool

beacon-chain/blockchain/chain_info.go
Part of #7412 
A few methods in `chain_info` do not have read locks when reading `head` from service store
=> Add locks around head getters

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/head.go
This fixes a bug raised in #7423. `hasHeadState` already calls the read lock so dead lock could happen. This moved read lock to after `hasHeadState`
=> Move read lock after hasHeadState

beacon-chain/powchain/service_test.go
> Other / Audit recommendations
- Item 14 ToB audit.
- Handles not only ` HeaderByNumber()` reported by audit, but `HeaderByHash()` (it has the very same issue).
Part of #7410
- As a side-note: honestly, the `safelyHandlePanic()` looks lot like Horus heresy to avg. Golang dev:
```golang
// safelyHandleHeader will recover and log any panic that occurs from the
// block
func safelyHandlePanic() {
if r := recover(); r != nil {
log.WithFields(logrus.Fields{
"r": r,
}).Error("Panicked when handling data from ETH 1.0 Chain! Recovering...")
debug.PrintStack()
}
}
// processBlockHeader adds a newly observed eth1 block to the block cache and
// updates the …
```
=> Handle nil header properly in powchain service tests

.deepsource.toml
This PR adds support for https://deepsource.io/, which will help us find significant problems in our code, especially during the code review phase
=> Add Deep Source Code Analysis

beacon-chain/core/helpers/attestation.go, beacon-chain/core/helpers/attestation_test.go
`SlotSignature` is not used in run time and has a bug. This PR removes it.
=> Remove unused `SlotSignature` function

beacon-chain/core/epoch/precompute/slashing.go
This was caught and fixed in #7469 
This does not affect v0.12.x and medalla since the config value is 3. I wanted to merge this fix into master to lower the line diff counts for 7469.
=> Update slashing to use config value

beacon-chain/node/BUILD.bazel, beacon-chain/node/node.go, beacon-chain/node/node_test.go, slasher/node/BUILD.bazel, slasher/node/node.go, slasher/node/node_test.go, validator/node/BUILD.bazel, validator/node/node.go, validator/node/node_test.go
> Bug fix
Fixes the issue where --clear-db in Windows leads to an error quoted in #7401 :
```
WARN node: Removing database
ERROR main: could not clear database: could not remove database file: remove C:\Users\Username\AppData\Roaming\Eth2\beaconchaindata/beaconchain.db: The process cannot access the file because it is being used by another process.
ERROR FAILED
```
This is in the validator, beacon-chain, as well as the slasher.
This is because on Linux, you can indeed os.Remove a file in use without the OS complaining-- this unlinks it from the containing directory but since a process has it open, the actual data on disk will remain until the process ends.  At the time the process exits, if there is no other …
=> Fix --clear-db on Windows

beacon-chain/core/epoch/spectest/rewards_and_penalties_mainnet_test.go
Discovered in #7469 but fixing in master to reduce line count.
It came to my attention that we were missing rewards and penalties mainnet spec test under epoch. We only had miminal spec test. 😱
=> Add missing mainet spec test

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/service.go, beacon-chain/core/helpers/committee.go, beacon-chain/operations/attestations/prepare_forkchoice.go, beacon-chain/state/stategen/setter.go, beacon-chain/sync/initial-sync/blocks_queue_test.go, beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/validate_aggregate_proof.go, endtoend/helpers/helpers.go, shared/keystore/key.go, slasher/detection/attestations/spanner.go, slasher/rpc/service.go, tools/benchmark-files-gen/main.go, validator/db/kv/manage.go, validator/db/kv/new_proposal_history.go, validator/db/kv/proposal_history.go
> Other
- Removes redundant error checking (when `if err { return err } else { return nil }` can be simplified to `return err`). This issue has been [found by DS](https://deepsource.io/gh/prysmaticlabs/prysm/issue/RVV-B0005/occurrences)
N/A
=> Remove redundant err checking

beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/service_test.go, beacon-chain/cache/depositcache/deposits_cache_test.go, beacon-chain/cache/depositcache/pending_deposits_test.go, beacon-chain/db/db_test.go, beacon-chain/db/kafka/export_wrapper.go, beacon-chain/db/kv/kv.go, beacon-chain/gateway/gateway.go, beacon-chain/interop-cold-start/service.go, beacon-chain/node/node_test.go, beacon-chain/operations/attestations/pool_test.go, beacon-chain/p2p/encoder/ssz.go, beacon-chain/p2p/service.go, beacon-chain/powchain/service_test.go, beacon-chain/rpc/beaconv1/server_test.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/service.go, shared/rand/rand.go, shared/slotutil/slotticker_test.go, shared/slotutil/testing/mock_test.go, slasher/db/db_test.go, slasher/detection/attestations/mock_spanner.go, slasher/detection/attestations/spanner.go, slasher/detection/proposals/detector_test.go, tools/cluster-pk-manager/server/server_test.go, validator/client/mock_validator.go, validator/client/service_test.go, validator/client/validator_test.go, validator/rpc/accounts_test.go, validator/rpc/server_test.go
> Other
I've noticed that we use the following pattern to verify that a given struct's pointer implements an interface:
```golang
var _ = ChainInfoFetcher(&Service{})
```
Basically, we create an object and try to convert it into `_` using interface. The very same effect is conventionally achieved using the following pattern:
```golang
var _ ChainInfoFetcher = (*Service)(nil)
```
It checks the interface compliance, but does so rather more elegantly, by trying to assign to a var `_` (of a given interface type) **typed nil** value (we need a zero value of asserted type on the right side of `=`, which is `nil` for pointers).
N/A
=> Verify interface compliance using typed nil instead of dereferencing and conversion

beacon-chain/sync/pending_blocks_queue.go
Update "Requesting parent block..." to `debug` level. It's more appropriate given the verbosity and lack of actions required from consumer
=> Update "Requesting parent block..." to debug level

beacon-chain/blockchain/process_block.go, beacon-chain/core/state/transition.go, beacon-chain/core/state/transition_fuzz_test.go, shared/featureconfig/config.go, shared/featureconfig/flags.go
Part of #7515 
This PR removes `disable-initial-sync-verify-all-signatures`. This is a very unsafe flag and we shouldn't have it for beta. This was nice to delete, it enabled us to delete old methods such as `ProcessBlockNoVerifyAttSigs` and `ExecuteStateTransitionNoVerifyAttSigs`
=> Remove inital sync don't verify att sig flag

beacon-chain/core/helpers/slot_epoch.go, beacon-chain/core/state/transition.go, beacon-chain/db/kv/kv.go, beacon-chain/p2p/handshake.go, beacon-chain/rpc/beacon/validators_stream.go, beacon-chain/rpc/validator/attester.go, beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_ping.go, beacon-chain/sync/rpc_status.go, shared/aggregation/attestations/maxcover.go, shared/prometheus/content_negotiation.go, shared/promptutil/prompt.go, slasher/beaconclient/receivers.go, slasher/db/kv/kv.go, tools/cluster-pk-manager/server/server.go, validator/accounts/v1/account.go, validator/accounts/v2/accounts_import.go, validator/accounts/v2/wallet/wallet.go, validator/accounts/v2/wallet_recover.go, validator/client/validator.go, validator/db/kv/db.go, validator/rpc/auth.go, validator/rpc/wallet.go
- In Golang 1.13 extra method for wrapping errors (see https://golang.org/pkg/errors/ for details) has been introduced.
- So, it is generally preferred, to use `errors.Is(err, errType)` instead of `err == errType` when comparing non-nil errors to some type (as former is able to unwrap wrapped errors and compare correctly).
- Additionally, instead of passing the original error in conventional `fmt.Errorf("sth wrong: %v", err)`, it is better to wrap the error using new verb `%w` (just `%v -> %w` is enough i.e. `fmt.Errorf("sth wrong: %w", err)`), as that way client code can get access to the original error (unwrap) if necessary.
N/A
- …
=> Update error usage patterns to go1.13+

shared/tos/tos.go
> Other
Many users who tried to run last master as a systemd service were confused by `could not scan text input` because initial prompt asking for ToS acceptance was getting omitted in journald. Solution is to make error for non-interactive environments more descriptive.
=> Make ToS non-interactive err message more descriptive

beacon-chain/sync/validate_beacon_attestation.go
Bug fix
As title describes. From the logs, the message isn't helpful for troubleshooting without knowing the underlying error.
=> Print the underlying error when attestation fails to get pre state

validator/accounts/cmd_accounts.go, validator/accounts/cmd_wallet.go
This PR adds the AcceptTosFlag to every validator account or wallet subcommand, as reported via issues in beta.0.rc
=> Add Accept Terms of Use Flags to Accounts Commands

beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
This fixes #7581, it checks the response length before return
=> Check `ListValidatorBalances` response length

beacon-chain/main.go, slasher/main.go, validator/accounts/BUILD.bazel, validator/accounts/cmd_accounts.go, validator/accounts/cmd_wallet.go, validator/main.go
In connection to @rauljordan's pr #7584 
if we want to add ToS acceptance to subcommands then we should check and save result for this flag there too
=> Checking ToS cli flag in subcommands

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/forkchoice/protoarray/store.go
While debugging bigger flames with profile, I discovered some missing spans under `AncestorRoot`. This PR fixed that and updated a few naming for `blockchain`
=> Add span for AncestorRoot

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/state.go, beacon-chain/rpc/beacon/validators.go, beacon-chain/state/stategen/replay.go
This PR adds context cancelation checks to the various hot state fetching functions, which will help us cancel gRPC requests that take way too long, such as balances in periods of no finality
=> Context Cancelation Handling for Hot States

beacon-chain/sync/rpc_goodbye.go
Other
Updates our GoodBye status code messages to match those in Lighthouse.
See  
https://github.com/sigp/lighthouse/blob/d7b9d0dd9f4e35680515c0cd0ed437d4e1ad625a/beacon_node/eth2_libp2p/src/rpc/methods.rs#L124
Fixes debug messages like
```
[2020-10-21 16:19:20] DEBUG sync: Peer has sent a goodbye message Reason=unknown goodbye value of 129 Received peer=16Uiu2HAmVsEc2W1Ed7tZmkSGMou7XGvjDLN3hPsppjVyL8LzJigd
```
=> Add lighthouse p2p Good Bye codes

validator/accounts/accounts_exit.go, validator/accounts/cmd_accounts.go
Bug fix
Moves voluntary exit logging into the correct place. Currently errors with stack traces are still logged out from `accounts_exit` even when validator couldn't be exited due to a non-critical reason.
N/A
N/A
=> Move voluntary exit logging to `accounts_exit`

beacon-chain/sync/subscriber.go
Fixes #7437, this PR changes the function signature of `subscribeWithBase` to remove an unused parameter
=> Remove Unusued Base Parameter in SubscribeWithBase

validator/accounts/accounts_backup.go, validator/accounts/accounts_delete.go, validator/accounts/accounts_exit.go, validator/accounts/accounts_list.go, validator/accounts/wallet/wallet.go, validator/accounts/wallet/wallet_test.go, validator/accounts/wallet_edit.go, validator/node/node.go, validator/rpc/wallet.go
Some stakers find it confusing that they create a wallet, then run `prysm validator` but they see a `no wallet found` error message, missing that they had probably created a custom wallet directory. This error is now changed to give them the following info: 
```go
"no wallet found, no accounts to delete. Perhaps you created a wallet in a custom directory, which you can specify using --wallet-dir=/path/to/my/wallet"
```
=> Clarify `No Wallet Found` Error Messages

shared/promptutil/prompt.go, shared/promptutil/validate.go, shared/promptutil/validate_test.go
> Bug fix
This PR states explicit password requirements on startup for wallets, and adds more test cases to ensure passwords with many kinds of characters such as those generated by LastPass.
- We should specify that passwords need to have 1 alphabetical character, 1 number, 1 unicode symbol, and at least length 8
- We should add test cases for passwords that are numbers only
- We should add test cases for long passwords such as those from LastPass
Fixes #7483
=> Explicit Password Requirements

beacon-chain/rpc/node/server.go
This PR fixes #7380, which encounters a nil pointer when getting the string of a multiaddr in the RPC package
=> Fix Nil Pointer in RPC List Peers

beacon-chain/blockchain/metrics.go
Fixes #7141. Instead, we should be using `beacon_prev_epoch_target_gwei and beacon_prev_epoch_active_gwei` which aligns with other client teams' metrics for computing participation
=> Remove Deprecated Participation Metrics

prysm.bat, prysm.sh
This fixes #7552, which tells the user to rerun the prysm.sh or bat script with `--ssl-no-revoke` if blocked by their antivirus. This is confusing as users will try `prysm.sh beacon-chain --ssl-no-revoke` and get failures. Instead, if users are faced with this problem we recommend them to download the executables from our releases page directly.
=> Do Not Recommend --ssl-no-revoke When Downloading Prysm Scripts

beacon-chain/p2p/peers/status.go, beacon-chain/p2p/peers/status_test.go
> Bug fix
- Another minor bug (sorry, should have spotted it in https://github.com/prysmaticlabs/prysm/pull/7619)
- Basically, if two (or more) epochs receive the same number of votes, then `targetEpoch` is not set to best/max finalized, but to arbitrary selected among those best scoring (we are looping using range, so whichever epoch comes first is selected).
- This PR resolves it + adds regression test.
N/A
=> Handle voting ties in BestFinalized()

beacon-chain/node/node.go, beacon-chain/p2p/service.go, beacon-chain/sync/initial-sync/service.go
What type of PR is this?
Bug fix
Fixes a few panics and allows services to gracefully recover when shutting down the beacon node.
Fixes #6924
N/A
=> Fix panic issues on beacon node shutdown

beacon-chain/forkchoice/protoarray/store.go
The following concurrent read write was reported by @dv8silencer . This PR fixes it by updating the previous read only lock to a regular lock.
```
fatal error: concurrent map read and map write
goroutine 23503376 [running]:
runtime.throw(0x19e229d, 0x21)
GOROOT/src/runtime/panic.go:1116 +0x72 fp=0xc05468a500 sp=0xc05468a4d0 pc=0x459722
runtime.mapaccess1(0x1759760, 0xc0445000f0, 0xc05468a568, 0xc05b60bc00)
GOROOT/src/runtime/map.go:411 +0x24b fp=0xc05468a540 sp=0xc05468a500 pc=0x432cab
github.com/prysmaticlabs/prysm/beacon-chain/forkchoice/protoarray.(*ForkChoice).IsCanonical(0xc0444df130, 0x7c60daf2f555100a, 0xbf5198380528c79f, 0x46415d76849e4988, 0xf3ba6b8aff39bdfc, 0x46415d76849e4900)
beacon-chain/forkchoice/protoarray/store.go:167 +0xb0 fp=0xc05468a5a8 sp=0xc05468a540 pc=0xd96390 …
```
=> Forkchoice: update read only lock to regular lock

beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/initial-sync/fsm.go, beacon-chain/sync/initial-sync/fsm_test.go
- While working on new init-sync algorithm in #7564 (one capable to traverse multiple branches during non-finality), minor cleanup was attempted, where it didn't require too much of time/effort.
- This PR updates FSM, to use block/slot terminology more cleanly. It doesn't change any algorithmic logic, but since FSMs were designed to be slot based (not block based), API has been updated to reflect that.
- Additionally, improves test coverage slightly.
N/A
- Filed as separate PR, to make sure that #7564 is not overly cluttered.
=> Update init-sync FSM

beacon-chain/core/validators/validator_test.go
> Other / Test cleanup
- **Very minor** thing spotted when testing type hardening: epoch was being assigned to slot (`helpers.SlotToEpoch()` returns epoch, but value was assigned to `BeaconState.Slot`).
- Ironically, no value is required at all: default value works ok (so settling for 0th slot is ok). 
N/A
- Removed other `Slot: 0` attributes for consistency.
=> Remove redundant attribute in validator test

validator/client/mock_validator.go, validator/client/runner.go, validator/client/validator.go, validator/client/validator_test.go
Bug fix
Logs out information that all validators are exited instead of trying to get duties, which resulted in error messages.
Fixes #7538
N/A
=> Log out that all validators are exited

beacon-chain/db/iface/interface.go, beacon-chain/db/kv/state.go
Other
Marking this method as deprecated. Will remove in a follow up PR after #7648
This fixes potential issues where a method is expecting the highest / head state in the database, but nothing is returned.
Ever since stategen was introduced and less states were saved to the database, the HeadState method has been returning nil and causing issues. An example is PR #7648 where the caller of the method expected a state to be returned to fill the deposits cache.
=> Deprecate db.HeadState

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/state_summary.go
> Other
This PR removes top spans in jaeger, which account for top 3 of all requests, launching a ton of goroutines for span collection, namely:
HasStateSummary
stateSummaryBytes
HasBlock
These functions are fairly simple DB lookups, so it will not be disruptive if we remove their spans to our monitoring pipelines.
=> Remove Top Jaeger Span Offenders

beacon-chain/blockchain/process_attestation_helpers.go, beacon-chain/blockchain/process_attestation_test.go, beacon-chain/blockchain/service.go
Thanks @prestonvanloon for diagnosing
> Bug fix
One of our most critical functions `getAttPreState` was using a top-level mutex which was held throughout the entire direction of the function, which is a very expensive function. This leads to massive goroutines as lock contention is happening in the beacon node. This has manifested as alerts to our team of nodes experiencing excessive goroutines, and we have an answer for this thanks to evidence gathered.
We resolve this issue by not using the lock at all, as the underlying cache we are accessing was already thread-safe.
=> Remove Lock Contention in getAttPreState

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/state_summary.go
Reverts prysmaticlabs/prysm#7655
While these individual spans are very highly used, they are not necessarily causing issues at this time.
We'll keep them around until we have concrete evidence that this is a problem for beacon node operators.
=> Revert "Remove Top Jaeger Span Offenders"

beacon-chain/blockchain/receive_attestation.go, beacon-chain/blockchain/receive_attestation_test.go
Removing the following redundant checks in `processAttestations`. Not only these checks are redundant, they always cause harm. Rationales:
* This is duplicated. These checks are already implemented in sync validation pipelines and core processing logic.
* This is bad. When these checks fail and the loop continue on, it assumes fork choice attestations could forever get stuck in the pool and draining the compute to loop over and over again. In fact we should fail out load, and delete the invalid attestations from the pool
=> Remove redundant checks in `processAttestation`

beacon-chain/blockchain/process_attestation_helpers.go, beacon-chain/blockchain/process_attestation_test.go, beacon-chain/cache/checkpoint_state.go, beacon-chain/cache/checkpoint_state_test.go
target roots, it would be better to have an in progress map to track all these checkpoints.
This follows heavily from our attestation data cache as the problem it had to solve is very similar to the one the checkpoint cache
is trying to solve.
Fixes #
=> Add In Progress Checker For Checkpoint Cache

beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_beacon_attestation.go
Other
I have ordered some of this boolean OR logic such that the cheaper calls are first.
When go has an operation like this
```go
c := a() || b()
```
and the result of a is true, b will not be called. Using this knowledge, we can put the database calls towards the end of the operation, so that a cheaper method takes precedence.
N/A - very minor tweak, maybe no one will notice but I will feel better about it :)
=> validateCommitteeIndexBeaconAttestation: Reorder boolean logic to reduce db calls

beacon-chain/sync/initial-sync/blocks_queue.go
> Other
- FSM's `tick` logs are too frequent, turn them to traces.
N/A
=> Turn init-sync FSM logs to trace level

beacon-chain/state/stategen/service.go
Use `stategen` to retrieve finalized state instead of `db`.  When using `db` to retrieve state, it could return `nil`
=> Use state by root to get finalized state

beacon-chain/blockchain/service.go
`finalizedCheckpt` and `justifiedCheckpt` were switched, im not sure what the implication yet. Fixing this first, but will do detailed analysis later
=> Update `fillInForkChoiceMissingBlocks` to use correct odering

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_queue_test.go, beacon-chain/sync/initial-sync/round_robin.go
Logging Change
if all blocks we receive cannot be processed.
N.A
=> Better Initial Sync Error Logging

beacon-chain/blockchain/process_attestation_helpers.go, beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/getter_test.go
This ensures we still can fill in checkpoint state cache if the state exists in DB. If the state exists in hot state or state summary cache then we don't fill it in.
=> Add and use `HasStateInCache`

beacon-chain/p2p/peers/status.go
- `BestNonFinalized(minPeers int, ourFinalizedEpoch uint64)` function uses misleading param name `ourFinalizedEpoch`, while in reality head epoch is expected -- `ourHeadEpoch`, and peers having higher head than ours are returned.
N/A
=> Fix param naming in BestNonFinalized

beacon-chain/blockchain/testing/BUILD.bazel, beacon-chain/blockchain/testing/mock.go, beacon-chain/rpc/beacon/validators_stream.go, beacon-chain/state/getters.go, beacon-chain/state/getters_test.go
As learned from previous incidents that `ValidatorsReadOnly(...` is not sufficient and should not be used. A better replacement is to use `state.ReadFromEveryValidator(...`
This PR removes `ValidatorsReadOnly(...` and updates its usages and methods in `validators_stream.go` to use `ValidatorsReadOnly(...` instead
=> Remove expensive validators only method

beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
`GetValidatorParticipation` has a bad slot to epoch conversion:
```
currentSlot := helpers.SlotToEpoch(bs.GenesisTimeFetcher.CurrentSlot())
currentEpoch := helpers.SlotToEpoch(currentSlot)
```
should have been:
```
currentSlot := bs.GenesisTimeFetcher.CurrentSlot()
currentEpoch := helpers.SlotToEpoch(currentSlot)
```
=> Fix `GetValidatorParticipation` slot to epoch conversion

beacon-chain/flags/base.go, shared/featureconfig/config.go, shared/params/mainnet_config.go, shared/params/network_config.go
This PR updates genesis time, contract deployment block and deposit contract address to mainnet values It also flips mainnet values to default.
Reference: https://github.com/ethereum/eth2.0-specs/pull/2082
Note:
`ETH1_FOLLOW_DISTANCE`, `GENESIS_DELAY`, `EPOCHS_PER_ETH1_VOTING_PERIOD`, `INACTIVITY_PENALTY_QUOTIENT`, `MIN_SLASHING_PENALTY_QUOTIENT`, `PROPORTIONAL_SLASHING_MULTIPLIER` did not get updated to mainnet because they are consensus breaking. Those updates will come from #7469
=> Update genesis time and deposit contract

beacon-chain/sync/initial-sync/blocks_fetcher.go, beacon-chain/sync/initial-sync/blocks_fetcher_peers.go, beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go, beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
- `filterPeers()` in `init-sync` always returns `nil` for error, making that return type redundant. It is removed as unnecessary complicating the API and serving no purpose.
N/A
=> Remove redundant error return from filterPeers()

beacon-chain/usage.go
`SlotsPerArchivedPoint` was already defined in L103. This removes the duplication
=> Remove duplicated --slots-per-archive-point in help menu

beacon-chain/sync/initial-sync/blocks_fetcher_test.go
- When working on #7564 I've noticed that fetcher's locks (controlling access to rate limiter) lack an easy to check assertion - actual log that peer has been limited. This PR adds that assertion.
N/A
=> Add one more assertion to fetcher test

shared/featureconfig/flags.go
Feature
Adds a no-op `--mainnet` flag for easier docker-compose and docker tooling: main and test can be handled with
the same entrypoint / command.
Fixes #7735 
Thank you for considering this! Makes my life easier!
=> Add `--mainnet` no-op flag for easier docker tooling

validator/client/validator.go, validator/client/validator_test.go
When launching the validator client, if the validator is exiting (in the queue) this PR allows for it to continue attesting. 
Fixes #7745 
Note: not tested, that's why it is a draft still.
=> Allow exiting validators to attest

beacon-chain/db/kv/state.go, beacon-chain/state/stategen/setter_test.go
This PR improves on the design for the delete state functions:
* Currently `DeleteStates` put everything under 1 TX, that means it either all works or none of it works
* For `DeleteStates`, Instead of doing one big update, it's better to do one at a time
* This PR refactored `DeleteStates` to `DeleteState` without the cursor, and updated `DeleteStates` to just call `DeleteState`
=> Update delete state(s) functions

shared/rand/rand.go
Follow up to #7770 , the PR introduced a recursive read lock in our rand package. This PR fixes it
=> Remove Recursive Read Lock in Shared/Rand

beacon-chain/blockchain/receive_block_test.go, beacon-chain/operations/voluntaryexits/BUILD.bazel, beacon-chain/operations/voluntaryexits/service.go, beacon-chain/operations/voluntaryexits/service_test.go
> Bug fix
This is related to #7772. Our exits logic was needlessly complex, as all we needed to do is to check if an exit was already seen by the pool to reject it. Additionally, we needed to simplify further parts of the code in there and ensure our binary search is correct according to the Go stdlib.
=> Fix Up Exits Pool Logic

shared/testutil/BUILD.bazel, shared/testutil/deposits.go, shared/testutil/deposits_test.go
Test helper additions 
This PR adds extra deposit helpers to allow creating deterministic deposits with custom balances. It uses any available cache of secret keys and generates any if it needs.
This is in preparation for testing partial deposits in E2E.
=> Add configurable deposit amounts to testutil 

shared/bls/BUILD.bazel, shared/bls/bls.go, validator/keymanager/derived/BUILD.bazel, validator/keymanager/derived/eip_test.go
Part of #7763, this PR adds tests for key derivation in [EIP-2333](https://eips.ethereum.org/EIPS/eip-2333#key-derivation) for our derived keymanager in Prysm.
**NOTE**: A few test cases are skipped due to an error in our derivation dependency here https://github.com/wealdtech/go-eth2-util/issues/2
=> Add EIP-2333 Conformity Tests

beacon-chain/core/blocks/randao_test.go, beacon-chain/core/blocks/signature.go, beacon-chain/core/state/transition.go
> Cleanup
`RandaoSignatureSet` does not need to return beacon state, this PR cleans it up
Fixes # N/A
=> `RandaoSignatureSet` to not return state

beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
> Bug fix
This fixes `finalized` response for `GetValidatorParticipation`. Previous implementation was always going to be false
Fixes #
=> Fix `finalized` response for `GetValidatorParticipation`

shared/params/mainnet_config.go
Update genesis delay to one week to align with spec in v1.0.0 branch
=> Update genesis delay to one week

beacon-chain/core/helpers/block.go, beacon-chain/core/helpers/block_test.go
Bug fix
There is a potential, albeit unlikely, risk of an overflow for `get_block_root_at_slot`. 
`compute_start_slot_at_epoch` already had overflow protection, so this exploit is probably not reproducable in any production code path.
Fixes https://github.com/ethereum/eth2.0-specs/issues/2129 for Prysm.
I did not test at runtime or sync with this change.
=> Mitigate potential overflow. ethereum/eth2.0-specs#2129

DEPENDENCIES.md, WORKSPACE, deps.bzl
Other
Updates rules_go and go version to 1.15.5.
Fixes security issues in go standard library.
I updated our gazelle command to prune old go_repositories. It seems to have deleted quite a few of them!
=> Update rules_go, prune unused go_repositories

WORKSPACE, deps.bzl, go.mod, go.sum
-  [x] Updates Gazelle to be in line with our updated `rules_go`
N.A
=> Update Go-Ethereum Dependency

shared/tos/tos.go
No tracking issue, this PR simplifies the terms of service logs. Some users thought that saying `you should use the --accept-terms-of-use only once` meant there was a risk to using it again
=> Simplify Terms of Service Log

beacon-chain/blockchain/blockchain_test.go, beacon-chain/cache/cache_test.go, beacon-chain/core/epoch/spectest/spectest_test.go, beacon-chain/p2p/peers/peers_test.go, beacon-chain/p2p/peers/scorers/scorers_test.go, beacon-chain/powchain/powchain_test.go, beacon-chain/rpc/beacon/beacon_test.go, beacon-chain/rpc/validator/validator_test.go, beacon-chain/state/stateutil/stateutil_test.go, beacon-chain/sync/initial-sync/initial_sync_test.go, beacon-chain/sync/initial-sync/service_test.go, beacon-chain/sync/rate_limiter.go, beacon-chain/sync/rpc_beacon_blocks_by_range_test.go, beacon-chain/sync/sync_test.go, shared/aggregation/attestations/attestations_test.go, shared/slotutil/slotutil_test.go, slasher/beaconclient/service_test.go, slasher/db/kv/kv_test.go, slasher/detection/attestations/attestations_test.go, slasher/detection/proposals/proposals_test.go, slasher/node/node_test.go, slasher/rpc/rpc_test.go, tools/bootnode/bootnode_test.go, tools/sendDepositTx/sendDeposits_test.go
> Other
- https://github.com/prysmaticlabs/prysm/pull/7761 updated usage of `TestMain()`
- However, `rules_go` does not support that yet: https://github.com/bazelbuild/rules_go/pull/2716
- This PR updates `TestMain()` back to rely on `os.Exit()` and fixes tests that weren't discovered due to the issue with `rules_go`.
N/A
=> Update TestMain() to use os.Exit()

beacon-chain/sync/subscriber_test.go
Bug fix
Observed this segfault running all tests on `master`, occurring
in around 2-3 out of 10 test runs.
```
FAIL: //beacon-chain/sync:go_default_test (shard 3 of 4, run 1 of 10) (see /home/j/.cache/bazel/_bazel_j/1ba834ca9d49f27aeb8f0bbb6f28fdf3/execroot/prysm/bazel-out/k8-fastbuild/testlogs/beacon-chain/sync/go_default_test/shard_3_of_4_run_1_of_10/test.log)
INFO: From Testing //beacon-chain/sync:go_default_test (shard 3 of 4, run 1 of 10):
==================== Test output for //beacon-chain/sync:go_default_test (shard 3 of 4, run 1 of 10):
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x138eea6]
goroutine 1660 [running]: …
```
=> beacon-chain/sync: fix flaky segfault in tests

beacon-chain/flags/base.go, beacon-chain/flags/config.go, beacon-chain/main.go, beacon-chain/sync/metrics.go, beacon-chain/sync/subscriber.go, beacon-chain/usage.go
Bug Fix
clear and accurate name.
=> Add Back Flag to Subscribe to All Subnets

beacon-chain/p2p/peers/scorers/bad_responses.go, beacon-chain/p2p/peers/scorers/bad_responses_test.go, beacon-chain/p2p/peers/scorers/block_providers.go, beacon-chain/p2p/peers/scorers/block_providers_test.go, beacon-chain/p2p/peers/scorers/service.go, beacon-chain/p2p/peers/scorers/service_test.go, beacon-chain/p2p/peers/status.go, beacon-chain/p2p/service.go
> Other / Refactoring
- Extracted from #7480, adds the following changes:
N/A
=> Refactor scoring service

beacon-chain/core/feed/state/events.go, beacon-chain/powchain/log_processing.go, beacon-chain/rpc/validator/server.go, beacon-chain/rpc/validator/server_test.go, deps.bzl, go.mod, go.sum, validator/client/validator_test.go
API Modification
This PR changes ChainStartResponse to include the GenesisValidatorsRoot for use in the validator client.
=> Add GenesisValidatorRoot to ChainStartResponse

beacon-chain/core/feed/state/events.go, beacon-chain/powchain/log_processing.go, beacon-chain/rpc/validator/server.go, beacon-chain/rpc/validator/server_test.go
Bug fix
This PR removes the ChainStarted event form the WaitForChainStart and removes the GenesisValidatorsRoot from the event as well.
=> Remove listen for ChainStarted in WaitForChainStart

beacon-chain/cache/depositcache/deposits_cache.go, beacon-chain/cache/depositcache/deposits_cache_test.go
Bug Fix
correctly handle the last possible index to prune and instead panicked.
N.A
=> Handle Deposit Prune Proof Panic

beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/getter_test.go
Bug Fix
`loadStateByRoot` .
N.A
=> Return Finalized State Early from StateByRoot

validator/client/validator.go, validator/client/validator_test.go
This PR is a hotfix for a mistake I made in #7855 
Bug fix for where if a validator launches with a genesis validator root assigned, it crashes on startup.
=> Hotfix for WaitForChainStart GenesisValidatorsRoot Check

validator/keymanager/imported/refresh.go, validator/keymanager/imported/refresh_test.go
This PR attempts to reload validating keys from a file in a debounced manner if any fsnotify event is triggered, rather than just writes. The current approach would prevent symbolic links from reloading keys into the validator client. We throw errors if we attempt to reload a bad keystore or a keystore with empty keys.
Fixes #7732
=> Dynamic Reloading of Keys on Any FSNotify Event

beacon-chain/blockchain/service.go, beacon-chain/sync/service.go
>
> Bug fix
It's not appropriate for sync to return this error even if chain has not started, instead blockchain chain service should return the error while it is processing deposits to determine the genesis state. After this fix:
```
When processing deposits (before genesis state):
*prometheus.Service: OK
*p2p.Service: OK
*attestations.Service: OK
*initialsync.Service: OK
*sync.Service: OK
*gateway.Gateway: OK
*powchain.Service: OK
*blockchain.Service: ERROR genesis state has not been created
*rpc.Service: OK
After processing deposits (during sync):
*powchain.Service: OK
*blockchain.Service: OK
*p2p.Service: OK
*initialsync.Service: ERROR syncing
*sync.Service: ERROR out …
```
=> Remove chain not started error

shared/params/mainnet_config.go
Other
The eth1 block time is used to compute the eth1data voting window. We must match with other clients
or mainnet will have a difficult time voting on eth1data.
Fixes #7856
Do not merge without approval from @nisdas. 
I think this also affects how we fetch block headers.
=> Fix spec diff with comments. Fixes #7856

beacon-chain/p2p/service.go, beacon-chain/p2p/service_test.go, beacon-chain/p2p/subnets_test.go
Bug fix
Callers of this function expect that a nil error means a successful connection to a peer. However, bad peers were turning a nil error.
Fixes #7424
=> p2p: return error when attempting to connect to a bad peer

beacon-chain/powchain/block_reader.go, beacon-chain/powchain/service.go
=> Make Follow Distance Lookup Simpler

beacon-chain/rpc/service.go, beacon-chain/rpc/service_test.go
Bug fix
The beacon node should not report healthy when syncing.
N/A
=> RPC: healthz should return an error when the node is syncing

beacon-chain/sync/pending_attestations_queue.go
=> Fix Pending Queue For Unaggregated Attestations

beacon-chain/flags/base.go, validator/flags/flags.go
No tracking issue, but this PR helps improve the experience of running the prysm-web-ui in a dockerized environment by adding support for 0.0.0.0 in the grpc gateway cors domains for the beacon node and validator client
=> Add More Default CORS Domains to the gRPC Gateway

beacon-chain/p2p/service.go
Bug fix
The previous default value of 32 may be causing dropped attestations in large volume deployments.
None reported.
=> P2P: Increase outbound message queue size to 256

validator/accounts/accounts_exit.go, validator/client/service.go
Bug fix
The validator client service currently uses a `grpc.Header` call option to send headers, but no headers are being sent. According to https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#receiving-metadata, `grpc.Header` should be used to retrieve headers from responses. 
This PR fixes the issue by applying practices described in https://github.com/grpc/grpc-go/blob/master/Documentation/grpc-metadata.md#sending-metadata.
N/A
N/A
=> Make grpc-headers flag work

validator/client/attest.go, validator/client/attest_protect.go, validator/client/attest_protect_test.go, validator/client/propose.go, validator/client/propose_protect.go, validator/client/validator_test.go, validator/db/kv/attestation_history_v2.go
> Bug fix
Slashing protection, in current `master`, lives with some really serious problems. Although most of these issues are patched in #7848, that PR needs time to be tested in pre-production environments before making into the master branch due to how radical it is and how much it changes. Unfortunately, we still have some bugs today in detecting surround votes, which we have observed today in our internal infrastructure. The issues are with respect to false positives, meaning that local slashing protection detects certain attestations as slashable which are not. Moreover, **we do not have enough logs available to help us understand the problem**. This PR adds the following changes:
=> Improve Slashing Protection for V1, More Tests and Observability

validator/client/attest.go, validator/client/attest_protect.go
Follow up to #7934, this PR ensures we update the attesting history if an attestation is not found to be slashable. Additionally, we save the protection data to DB _before_ we attest rather than afterwards
=> Always Update Attesting History If Not Slashable

validator/client/attest.go, validator/client/attest_protect.go, validator/client/metrics.go, validator/client/mock_validator.go, validator/client/runner.go, validator/client/validator.go, validator/client/validator_test.go, validator/db/kv/attestation_history_v2.go
This is a follow-up to #7935, the core cause of the error we have observed  "cannot find attesting history for pubkey" in the validator clients on Pyrmont. Was found to be the rewriting of attestationhistory map while some rolls (validator duties) are still using them. (the wait group is in the go routine)https://github.com/prysmaticlabs/prysm/blob/5889670cc74b83f5511f15aa3dc24e4155cf9150/validator/client/runner.go#L158
by removing `ResetAttesterProtectionData` https://github.com/prysmaticlabs/prysm/blob/5889670cc74b83f5511f15aa3dc24e4155cf9150/validator/client/runner.go#L160
we solved most of the cases but still at some extreme cases `v.UpdateProtections(ctx, slot)` was replacing the map content while some validators are still using them in their assignments …
=> Fix locks and fallback to db read if attestation history map is missing a pub key data

validator/client/propose_protect.go, validator/client/propose_protect_test.go, validator/db/iface/interface.go, validator/db/kv/manage_test.go, validator/db/kv/proposal_history_v2.go, validator/db/kv/proposal_history_v2_test.go, validator/slashing-protection/local/standard-protection-format/import_test.go
> Feature
This PR amends our `ProposalHistoryForSlot` method to return (signingRoot [32]byte, exists bool, err error) to align with the requirements of the slashing interchange standard https://ethereum-magicians.org/t/eip-3076-validator-client-interchange-format-slashing-protection/4883 EIP. It is possible we have a proposal history stored in the DB, but with a nil signing root. We handle this with a boolean.
Part of #7813
=> Allow Optional Signing Roots in Proposal History

beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/getter_test.go, beacon-chain/sync/pending_blocks_queue_test.go, beacon-chain/sync/validate_beacon_blocks.go, beacon-chain/sync/validate_beacon_blocks_test.go
> Feature
In the unfortunate case where state summary is missing in cache/db but the block exists in db. This PR added a recover step to generate and save the missing state summary in the db. This should not happen but we have seen it in the rase cases reported by users. This will mitigate the issue and buy more time to root cause the underlying issue.
Fixes #
=> Recover state summary for sync validation

beacon-chain/blockchain/service.go, beacon-chain/blockchain/service_test.go, beacon-chain/state/stategen/migrate.go, beacon-chain/state/stategen/setter.go, beacon-chain/state/stategen/setter_test.go
> Bug fix
One thing i realized as I was auditing state summary usages is that we do not save cached state summary objects upon shutting down beacon node. This triggers an asymmetric behavior where the beacon block is in the DB but state summary object is not in the DB on the very next restart
=> Save cached state summaries on Stop()

validator/db/kv/proposal_history_v2.go, validator/db/kv/proposal_history_v2_test.go
> Bug fix
Users running in dappnode version v1.0.2 of prysm are seeing issues when proposing due to not having a proposal history. This PR creates the bucket if the data does not exist. This is a hotfix because it is blocking proposals on mainnet for several users.
=> Create Bucket If Not Exists When Fetching Proposal History
