beacon-chain/core/epoch/precompute/slashing.go
beacon-chain/rpc/beacon/validators.go

Allocate Fewer Large Slices 

---

third_party/herumi/bls_eth_go_binary.BUILD

Fix Arm64 Builds For Herumi

---

beacon-chain/powchain/log_processing.go
beacon-chain/powchain/service.go

Code Cleanup
Partially helps with #7714 

Retrieve State From Last Finalized Checkpoint

---

beacon-chain/sync/BUILD.bazel
beacon-chain/sync/service.go
beacon-chain/sync/service_test.go
beacon-chain/sync/subscriber.go

Stop Sync Service More Cleanly

---

.github/PULL_REQUEST_TEMPLATE.md

No tracking issue, this updates our PR template to include clear language about where to find the CLA and our contributing guidelines.

Fix Pull Request Template Language

---

shared/params/mainnet_config.go
shared/params/testnet_altona_config.go
shared/params/testnet_medalla_config.go
shared/params/testnet_spadina_config.go
shared/params/testnet_zinken_config.go

Change To Mainnet Block Time

---

.deepsource.toml

This PR adds DeepSource support for bash files, announced just today

Add DeepSource for Bash Files

---

beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go

State Management
Follows on from #7729 .

Keep Non Finalized States

---

validator/flags/flags.go

Fix the code comment in DisableAccountMetricsFlag

Fix comment on DisableAccountMetricFlag

---

deps.bzl

As title describes, gazelle is now sorting deps.bzl and I forgot to update this in #7202. 
This will reduce the diff when someone wants to make a change to deps.bzl
N/A

Run gazelle to sort deps.bzl

---

beacon-chain/cache/depositcache/deposits_cache.go
beacon-chain/powchain/log_processing.go

Code cleanup
These are changes made in my [10th commit to prysm](https://github.com/prysmaticlabs/prysm/commit/365a06e709f88433fe3d03875d839c7af516b9f9), that has had its usages removed a very long time ago.

Remove unused chainStartPubKeys logic

---

README.md

https://goreportcard.com/report/github.com/prysmaticlabs/prysm this PR improves our README by adding the Go Report Card badge

Add Go Report Card to Prysm

---

beacon-chain/p2p/handshake.go

> Other
This PR updates connect and disconnect logs to `debug`. Talked with @rauljordan and @nisdas about this.
Fixes #

Change connect/disconnect logs to debug

---

shared/featureconfig/config.go
shared/featureconfig/deprecated_flags.go
shared/featureconfig/flags.go

This follows on from #6539 , #7760 and #7803 
N.A

Make Blst the Default Library

---

shared/params/testnet_pyrmont_config.go

Update Prymont config to align https://github.com/protolambda/pyrmont

Update Prymont config

---

beacon-chain/db/kv/blocks_test.go
beacon-chain/interop-cold-start/service.go
beacon-chain/rpc/validator/assignments.go

Other, cleanup
As title describes, fixes a few instances of a deepsource highlighted issue.
N/A

Fix instances of "The result of append is not used anywhere SCC-SA4010"

---

beacon-chain/operations/slashings/metrics.go
beacon-chain/operations/slashings/service.go
beacon-chain/sync/metrics.go
beacon-chain/sync/pending_attestations_queue.go

>
> Cleanup
These metrics are old and don't really serve much purpose. This PR removes these out dated metrics
Fixes #

Remove a few old metrics

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/pending_blocks_queue_test.go
beacon-chain/sync/validate_beacon_blocks.go

> Security
This PR adds validation to the pending blocks in queue before calling core processing method. After processing, it sets the seen block cache.
Fixes # N/A

Validate beacon block in pending queue

---

beacon-chain/powchain/log_processing.go

Save Powchain Metadata To Disk On Chainstart

---

beacon-chain/sync/rpc_ping.go

Clean Up
Reverts a change introduced in #7843 as it now fills up our 
debug logs with metadata logs.
Fixes #

Change Back Metadata Error Check

---

README.md

Update eth2 specs version badge in README

---

beacon-chain/p2p/parameter_test.go
beacon-chain/p2p/pubsub.go
shared/featureconfig/config.go
shared/featureconfig/flags.go

Update Gossipsub Parameters 

---

beacon-chain/powchain/block_cache.go
beacon-chain/powchain/block_cache_test.go
beacon-chain/powchain/block_reader.go

Bug fix
User reported a panic when using OpenEthereum. 
None filed.
I don't understand why this is an issue, but this PR should resolve any panic conditions.

Fix potential panic with nil *big.Int

---

shared/featureconfig/deprecated_flags.go

> Clean up
This PR removes deprecated feature flags
Fixes # n/a

Remove deprecated feature flags

---

validator/accounts/cmd_accounts.go
validator/accounts/cmd_wallet.go
validator/accounts/wallet/BUILD.bazel
validator/accounts/wallet/wallet_test.go

Cleanup
This PR removes some outdated text and code for accounts.

Remove outdated code in accounts

---

beacon-chain/BUILD.bazel
slasher/BUILD.bazel
validator/BUILD.bazel

> Bug fix
The creation time of docker images are all 50 years ago now. This PR intends to fix that.
Fixes #6561 

Fix creation time of beacon-node, validator and slasher

---

beacon-chain/sync/validate_beacon_attestation.go

Other
Change from log level `error` to `debug` for errors triggered by attestation signature verifications.
N/A
Discussed and approved by @prestonvanloon

Change attestation signature error to DEBUG level

---

beacon-chain/sync/rpc_goodbye.go

Other
This isn't an actionable error and all of the other "failed to close stream" messages are at debug. This one seems to have been accidentally put as an ERROR level message.
N/A

Change log from ERROR to DEBUG

---

tools/bootnode/bootnode.go

>
> Clean up
Part of mainnet clean up. Removing boot node to not use `pyrmont` as default config.

Update boot node to not use pyrmont

---

scripts/check-todo.sh
shared/params/mainnet_config.go

Other
Adding Teku's bootnode for mainnet.
Part of #7900

Add teku's bootnode

---

beacon-chain/sync/rate_limiter.go
beacon-chain/sync/rpc.go
beacon-chain/sync/service.go
beacon-chain/sync/validate_beacon_blocks.go

UX 
-[x] In #7914 some important sync logs were removed or pushed down to debug. This PR adds them back.
N.A

Add Back Error/Debug Logs

---

beacon-chain/rpc/beacon/attestations.go
beacon-chain/rpc/beacon/blocks.go
beacon-chain/rpc/beacon/validators_stream.go
beacon-chain/rpc/validator/attester.go
beacon-chain/rpc/validator/proposer.go

>
> Cleanup
Cleans up logging for rpc pkg. Replaced several prefix to "Could not". Reconstructed a few message sentence for clarify. Downgraded a few INFO to DEBUG
Fixes #

Reformat logging for rpc pkg

---

deps.bzl
go.mod
go.sum

Update Geth Again

---

beacon-chain/sync/initial-sync/blocks_queue.go
beacon-chain/sync/initial-sync/blocks_queue_test.go

> Feature
- The following issue has been spotted on pyrmont:
- Head slot is updated to some orphaned block (with some previous block missing, so no new blocks can be processed)
- After being stuck for 1 epoch, init-sync re-sync requested. However, since head is set to orphaned block (and init-sync uses head slot as a starting point), that previous proposed block was never requested. This PR resolves it.
N/A

More robust init-sync on detached head block

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/service.go

Remove Exclusion List

---

beacon-chain/sync/initial-sync/round_robin.go

Small enhancement
It changes the field logged in some initial sync warnings from "err" to "error", this reduces slightly the footprint on the journal and simplifies a bit log-parsing scripts. 
None filed.

Log with field error instead of err

---

README.md

Update readme to include latest branching strategy

Update README to include branching strategy

---

shared/featureconfig/config.go
shared/featureconfig/deprecated_flags.go
shared/featureconfig/flags.go

> Other
- Invert `enable-sync-backtracking` to opt-out flag `disable-sync-backtracking`
Part of #7734

Invert enable-sync-backtracking

---

beacon-chain/sync/initial-sync/service_test.go

> Other
- Marks mis-behaving test as skipped (I am looking into fixing it today, but do not want to prevent other PRs from being stuck due to issues in this test).

Skip bogus init-sync test

---

beacon-chain/state/state_trie.go
beacon-chain/state/stateutil/arrays.go
beacon-chain/state/stateutil/state_root.go
beacon-chain/state/stateutil/state_root_test.go
beacon-chain/state/types.go
shared/params/config.go
shared/params/mainnet_config.go

> Clean up
`fieldCount` is defined in two packages, i was a victim of this demise when working on feature road map that involved in state structure changes. This PR consolidated field count to params package 
Fixes # N/A
N/A

Add state field count to config

---

validator/client/attest_protect.go
validator/db/kv/historical_attestations.go

Other
To give some more visibility to the validator routine.

Add spans to pre and post att signing updates

---

validator/accounts/wallet_create.go

Other
Logs a warning in preparation for #7909
N/A
N/A

Warn when creating an imported wallet

---

beacon-chain/blockchain/process_block_test.go
beacon-chain/operations/slashings/service_attester_test.go
beacon-chain/operations/voluntaryexits/service_test.go
beacon-chain/sync/rpc_status_test.go

- This PR removes redundant/unused variables in tests.
N/A

Remove unused vars in tests

---

shared/prometheus/service.go

Other
Set some reasonable defaults on the prometheus metrics handler page.

Limit prometheus requests in flight, set timeout to reasonable 30 seconds

---

validator/rpc/intercepter.go

No tracking issue, this PR resolves a web UI issue where we fail to logout because the endpoint requires authentication, thanks @mohamedmansour

Remove Logout from Validator RPC Authenticated Paths

---

beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
beacon-chain/sync/initial-sync/blocks_queue_test.go
beacon-chain/sync/initial-sync/fsm.go

- All included code changes do not modify the semantics, the aim is to simplify the syntax.
N/A

Init sync: minor style fixes

---

WORKSPACE

No tracking issue, this PR updates Prysm web to beta.3 which has significant quality of life improvements

Update Prysm Web UI to Beta.3

---

validator/client/log.go
validator/client/log_test.go

> Bug fix
Handle nil duty case for validator client, so it doesn't panic in run time
Fixes # N/A

Validator nil duty should not panic

---

beacon-chain/core/blocks/deposit_test.go
beacon-chain/powchain/service_test.go

- Simplifies calls to `defer` by removing unnecessary lambda wrappers
N/A

Remove redundant lambda around cleanup code

---

beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/service_test.go

Bug fix
#8214 introduced a bug because of `Status` changes. This PR reverts them.
N/A
N/A

Revert changes to sync service status check

---

beacon-chain/rpc/nodev1/BUILD.bazel
beacon-chain/rpc/nodev1/node.go
beacon-chain/rpc/nodev1/node_test.go
beacon-chain/sync/initial-sync/testing/mock.go
beacon-chain/sync/service.go
fuzz/block_fuzz.go

Feature
This PR implements Node API's `GetHealth` method according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Node/getHealth
Part of #7510
N/A

Implement GetHealth in the node API

---

beacon-chain/blockchain/service_test.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/info.go
beacon-chain/p2p/peers/status_test.go
beacon-chain/p2p/service_test.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/p2p/watch_peers.go
beacon-chain/powchain/service.go
beacon-chain/rpc/beacon/blocks.go
beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_stream.go
beacon-chain/sync/initial-sync/service_test.go
beacon-chain/sync/subscriber_test.go

Clean up
Ran some code inspections and updated variable names that are the same as import name

Update variable names that are same as imports

---

deps.bzl
go.mod
go.sum
proto/beacon/p2p/v1/generated.ssz.go

Update FastSSZ To Latest Commit

---

deps.bzl
go.mod
go.sum

This PR updates our prysmaticlabs/go-bitfield to the latest version in Prysm

Update Bitfield Dependency

---

validator/keymanager/remote/keymanager.go

Fix to TLS v1.3

---

beacon-chain/blockchain/process_attestation_test.go
beacon-chain/core/blocks/attestation_test.go
beacon-chain/core/blocks/block_regression_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/operations/attestations/BUILD.bazel
beacon-chain/operations/attestations/kv/BUILD.bazel
beacon-chain/operations/attestations/kv/aggregated_test.go
beacon-chain/operations/attestations/kv/block_test.go
beacon-chain/operations/attestations/kv/forkchoice_test.go
beacon-chain/operations/attestations/kv/seen_bits_test.go
beacon-chain/operations/attestations/kv/unaggregated_test.go
beacon-chain/operations/attestations/prune_expired_test.go
beacon-chain/p2p/broadcaster_test.go
beacon-chain/rpc/beacon/attestations_test.go
beacon-chain/rpc/validator/aggregator_test.go
beacon-chain/rpc/validator/attester_test.go
beacon-chain/rpc/validator/proposer_test.go
beacon-chain/rpc/validator/proposer_utils_test.go
beacon-chain/sync/pending_attestations_queue_test.go
beacon-chain/sync/subscriber_beacon_aggregate_proof_test.go
beacon-chain/sync/subscriber_beacon_blocks_test.go
beacon-chain/sync/validate_aggregate_proof_test.go
shared/testutil/BUILD.bazel
shared/testutil/attestation.go
shared/testutil/attestation_test.go
shared/testutil/block.go
validator/client/aggregate_test.go

> Feature
This PR adds `HydrateAttestation` helper for test setup. We no longer have to define empty array to satisfy `fastssz`
More info on the design: https://hackmd.io/zpn8vLwxRDK9uhGfaAoVnA
Only touches test code

Hydrate attestation for tests

---

shared/featureconfig/config.go
shared/featureconfig/flags.go
validator/client/attest.go
validator/client/attest_test.go

> Feature flag
Added a feature flag `attest-timely` to gradually roll out fixes for #8185. Here's the tentative timeline for the fix: 
- v1.0.6 introduce the changes w/ feature flag and opt-in
- v1.1.0 flip the flag to opt-out

Add timely attest bug fix flag for #8185

---

.gitignore
scripts/ci-coverage.sh
tools/gocovmerge/BUILD.bazel
tools/gocovmerge/main.go

Bug fix
Some time ago, our coverage results stopped uploading to deepsource and codecov.
N/A
Previously we were running `@com_github_wadey_gocovmerge//:gocovmerge`, but this was removed from the WORKSPACE as it's not a direct dependency. I've checked in this piece of code with credits to our tooling.
Also added a single script with annotations to make our CI steps easier to parse.

Coverage results upload fix for CI

---

beacon-chain/core/blocks/deposit.go

Other / Code health
Code health!
N/A

verifyDepositDataWithDomain: Use helpers.ComputeSigningRoot

---

beacon-chain/blockchain/process_attestation_helpers.go

Other
There doesn't seem to be any reason to copy this state.
N/A
Tested in Pyrmont for several hours with 100 to 200 validators

Remove unnecessary state copy

---

WORKSPACE

Bug Fix
Updates Rules Go to 1.15.7 
N.A

Update to v1.15.7

---

beacon-chain/powchain/service.go

Fix Deposit Count Metrics

---

beacon-chain/blockchain/process_attestation.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/receive_attestation_test.go
beacon-chain/blockchain/service.go

> Testing
The main inner logic of `processAttestationsRoutine` was untested. This PR refactors the inner logic to `processAttestations` and adds a test
Fixes # N/A
N/A

Test for `processAttestations`

---

validator/client/attest.go
validator/client/service.go
validator/client/validator.go

> Cleanup
Subscriber error was not handled in the `select` block. This handles it
N/A
N/A

Handle subscriber error

---

beacon-chain/rpc/beaconv1/config.go
beacon-chain/rpc/beaconv1/config_test.go
deps.bzl
go.mod
go.sum

Feature
This PR implements config API's `GetForkSchedule` method according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Config/getForkSchedule
Part of #7510
N/A

Implement GetForkSchedule in the config API

---

beacon-chain/slasher/BUILD.bazel
beacon-chain/slasher/chunks.go
beacon-chain/slasher/chunks_test.go
beacon-chain/slasher/types/types.go

> Feature
This PR defines a `Chunker` interface used for optimized slashing detection as specified in our design document: https://hackmd.io/rGRGUicASqiei73xopAwsQ?both and begins implementing this interface for validator MinSpans. We add comprehensive annotations and tests to ensure slashing detection with these methods work effectively.
Part of #8331 
The package is still sitting at 91% code coverage

Defining and Implementing the Chunker Interface for MinSpans

---

beacon-chain/slasher/chunks.go
beacon-chain/slasher/chunks_test.go

> Feature
Follow up to #8350, this PR implements the same logic but for max spans, ensuring we keep the same quality of tests.
Part of #8331

Implement MaxSpanChunksSlice for Optimized Slasher

---

beacon-chain/core/epoch/precompute/reward_penalty_test.go
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/powchain/log_processing.go
beacon-chain/rpc/validator/attester_test.go
shared/params/loader.go
validator/accounts/accounts_import.go

- Simplifies expressions, w/o any change in semantics.
N/A

Simplify expressions

---

beacon-chain/blockchain/process_block.go

> Other
From #8357, we missed one spot where we should have gated by feature config flag. There's no risk to this except for wasted spending resource and we should just avoid it
N/A
N/A

Add missed feature flag usage

---

fuzz/common.go
shared/bls/blst/stub.go
tools/analyzers/slicedirect/testdata/slice.go
validator/accounts/accounts.go
validator/accounts/accounts_delete.go
validator/accounts/wallet/wallet.go
validator/db/kv/attester_protection.go
validator/keymanager/derived/keymanager.go
validator/keymanager/remote/keymanager.go
validator/slashing-protection/cli_export.go
validator/slashing-protection/local/standard-protection-format/export.go
validator/slashing-protection/local/standard-protection-format/format/format.go
validator/slashing-protection/local/standard-protection-format/import.go
validator/slashing-protection/local/standard-protection-format/import_test.go
validator/slashing-protection/local/standard-protection-format/round_trip_test.go
validator/testing/protection_history.go

> Cleanup
Ran goland code inspect for some cleanups. They are
* Reports names starts with package name.
* Generic receiver names
* Sort import names
N/A
N/A

Ran code inspect for clean up

---

DEPENDENCIES.md

Documentation
This line should not have been removed in #8257. We still need to update generated ssz files from time to time.
N/A

Revert DEPENDENCIES.md change from #8257

---

validator/db/kv/attester_protection.go
validator/db/kv/prune_attester_protection.go

Add Spans for Validator DB Methods

---

beacon-chain/core/state/transition.go
beacon-chain/state/stategen/replay.go

> Cleanup
Update span names to align with pkg names
N/A
N/A

Update span names

---

beacon-chain/blockchain/process_attestation.go
beacon-chain/blockchain/service_test.go
beacon-chain/rpc/nodev1/node_test.go
shared/abool/abool_test.go
shared/bls/bls.go
shared/bls/common/error.go
shared/bls/constants.go
shared/bls/error.go
shared/browser/browser.go
shared/bytesutil/bytes.go
shared/depositutil/BUILD.bazel
shared/depositutil/deposit.go
shared/iputils/external_ip.go
shared/keystore/keystore.go
slasher/cache/span_cache.go
slasher/db/kv/kv_test.go
validator/client/runner_test.go
validator/db/kv/migration.go

> Clean up. Yay!
Ran code inspect and cleaned up a bunch of unused functions, empty slice complains and casting complains
N/A
N/A

Clean up unused functions

---

beacon-chain/sync/initial-sync/blocks_queue_test.go

> Other (trivial/cosmetic)
> There are obvious benefits to using constants instead of repeating strings, mostly to ease maintenance.

Make a const instead of 3 'abc' occurences

---

beacon-chain/blockchain/process_block_test.go
beacon-chain/core/state/state_test.go
beacon-chain/operations/slashings/service_proposer_test.go
shared/testutil/assert/assertions.go
shared/testutil/assertions/BUILD.bazel
shared/testutil/assertions/assertions.go
shared/testutil/assertions/assertions_test.go
shared/testutil/require/requires.go

Testing improvement
This PR is in preparation of upcoming protobuf changes, adds new testing functions to be more compatible with native protobufs once those are implemented.

Add DeepSSZEqual and DeepNotSSZEqual

---

deps.bzl
go.mod
go.sum

> Other
The #8373 PR is merged, so this PR:
- Updates deps to master: https://github.com/prysmaticlabs/ethereumapis/commit/7f5672c50eaa2d8e314e2661a4246ce8d9c56189 (`types.Epoch` PR merged to `ethereumapis@master`)
- We're already running on that codebase - but from different branch (`feature/eth2-types`), now switching to `master`.
N/A

Update ethereumapis deps

---

validator/db/kv/attester_protection.go

Other
Helps with debugging batch save duration

Validator: add a DEBUG log to show batch attestation save duration

---

beacon-chain/rpc/beaconv1/BUILD.bazel
beacon-chain/rpc/beaconv1/state.go
beacon-chain/rpc/beaconv1/state_test.go

> Feature
Address feedbacks from #8402
N/A
N/A

Beacon API: update GetStateRoot 

---

beacon-chain/blockchain/head.go
beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_attestation_test.go
beacon-chain/core/blocks/attestation.go
beacon-chain/core/blocks/attester_slashing.go
beacon-chain/core/blocks/deposit.go
beacon-chain/core/blocks/exit.go
beacon-chain/core/blocks/proposer_slashing.go
beacon-chain/core/blocks/randao.go
beacon-chain/core/helpers/block.go
beacon-chain/core/state/transition.go
beacon-chain/db/kv/state.go
beacon-chain/rpc/beacon/blocks.go
beacon-chain/rpc/beaconv1/BUILD.bazel
beacon-chain/rpc/beaconv1/state.go
beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/pending_blocks_queue_test.go

> Feature
Added a helper `VerifyNilBeaconBlock` to replace tedious condition `b.Block == nil || b.Block.Body == nil`...

Verify nil block helper

---

beacon-chain/p2p/discovery.go

Use Correct Peer Status Method

---

beacon-chain/blockchain/receive_attestation.go
validator/client/mock_validator.go
validator/client/runner.go
validator/client/validator.go
validator/client/wait_for_activation.go

Cleanup
Some channels that are only read from or only written to are needlessly declared as read-write channels. This PR limits such declarations.
N/A
N/A

Constrain read/write channels

---

deps.bzl
go.mod
go.sum

Update Geth Fork

---

beacon-chain/p2p/connection_gater_test.go

- Removes redundant import directive (package is already imported). 
N/A

Fix duplicate import

---

beacon-chain/rpc/debugv1/BUILD.bazel
beacon-chain/rpc/debugv1/debug.go
beacon-chain/rpc/debugv1/server.go

Preparation
Part of #7510, this PR adds an outline for the debug endpoints as defined by the standard here: https://ethereum.github.io/eth2.0-APIs/#/

ETH2 API: Add outline for debug endpoints

---

beacon-chain/powchain/BUILD.bazel
beacon-chain/powchain/log_processing_test.go

> Cleanup (test)
Remove an outdated and been long skipped test - `TestConsistentGenesisState`. There has been no action to revamp this test and the test framework so removing is for the best
N/A
N/A

Remove outdated and skipped TestConsistentGenesisState

---

validator/db/kv/migration_source_target_epochs_bucket.go
validator/db/kv/migration_source_target_epochs_bucket_test.go

Bug fix
Prevents an out of bounds error on line 138.
Fixes  #8509

Fix slice out of bounds error in validator db migration

---

go.mod
go.sum
shared/browser/BUILD.bazel
shared/browser/browser.go
shared/bytesutil/bytes.go
shared/keystore/key.go
validator/client/propose_test.go
validator/rpc/health_test.go

Remove unused code

---

validator/db/kv/migration_source_target_epochs_bucket_test.go

Update Test Case in Batching Public Keys

---

endtoend/evaluators/slashing.go
proto/beacon/db/finalized_block_root_container.pb.go
proto/beacon/db/powchain.pb.go
proto/beacon/p2p/v1/messages.pb.go
proto/beacon/p2p/v1/types.pb.go
proto/beacon/rpc/v1/debug.pb.go
proto/beacon/rpc/v1/health.pb.go
proto/beacon/rpc/v1_gateway/debug.pb.go
proto/beacon/rpc/v1_gateway/debug.pb.gw.go
proto/beacon/rpc/v1_gateway/health.pb.go
proto/validator/accounts/v2/keymanager.pb.go
proto/validator/accounts/v2/web_api.pb.go
proto/validator/accounts/v2_gateway/keymanager.pb.go
proto/validator/accounts/v2_gateway/web_api.pb.go
proto/validator/accounts/v2_gateway/web_api.pb.gw.go
validator/accounts/accounts_list.go
validator/accounts/accounts_list_test.go

Ran go import

---

WORKSPACE
beacon-chain/core/state/stateutils/BUILD.bazel
beacon-chain/p2p/peers/peerdata/BUILD.bazel
beacon-chain/p2p/peers/scorers/BUILD.bazel
contracts/deposit-contract/BUILD.bazel
deps.bzl
go.mod
go.sum
shared/attestationutil/BUILD.bazel
shared/bytesutil/BUILD.bazel
shared/depositutil/BUILD.bazel
shared/fileutil/BUILD.bazel
shared/hashutil/BUILD.bazel
shared/htrutils/BUILD.bazel
shared/interop/BUILD.bazel
shared/iputils/BUILD.bazel
shared/mathutil/BUILD.bazel
shared/messagehandler/BUILD.bazel
shared/pagination/BUILD.bazel
shared/runutil/BUILD.bazel
shared/sliceutil/BUILD.bazel
shared/sszutil/BUILD.bazel
shared/testutil/assertions/BUILD.bazel
slasher/detection/attestations/types/BUILD.bazel
validator/accounts/wallet/BUILD.bazel
validator/keymanager/BUILD.bazel

Reverts prysmaticlabs/prysm#8521 and resolves #8537

Revert "Update to go 1.16"

---

beacon-chain/rpc/beacon/assignments.go
beacon-chain/rpc/beacon/assignments_test.go
beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go
shared/htrutils/helpers_test.go
shared/mputil/multilock_test.go
tools/keystores/main_test.go
validator/accounts/BUILD.bazel
validator/accounts/accounts_backup_test.go
validator/accounts/accounts_list_test.go
validator/client/wait_for_activation_test.go
validator/keymanager/derived/BUILD.bazel
validator/keymanager/derived/keymanager_test.go
validator/keymanager/imported/import_test.go
validator/keymanager/imported/keymanager_test.go
validator/rpc/BUILD.bazel
validator/rpc/accounts_test.go
validator/rpc/auth_test.go
validator/rpc/wallet_test.go
validator/testing/BUILD.bazel
validator/testing/constants.go

> Other (mosty cosmetic)
Make the project one step closer to be compliant with `goconst` which is part of golangci
None
If you prefer 1 PR == 1 commit, let me know so I can squash the commits.

A bit of cleanup based on goconst tool

---

deps.bzl

Other
Updates blst dependency to version v0.3.3
N/A

Update blst to v0.3.3

---

go.mod
go.sum

Update Go Mod

---

validator/db/kv/attester_protection.go

Create Bucket Only Once

---

cmd/validator/slashing-protection/slashing-protection.go
proto/beacon/p2p/v1/BUILD.bazel
proto/beacon/p2p/v1/generated.ssz.go
proto/beacon/p2p/v1/types.pb.go
proto/beacon/p2p/v1/types.proto

> Hard fork 1
Add protobuf definition for beacon state at hard fork 1
Reference: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/lightclient/beacon-chain.md#beaconstate
N/A
N/A

HF1: Beacon state protobuf definition

---

validator/db/kv/prune_attester_protection.go

Enhancement
Follows on from #8590 

Prune Better For Larger Buckets

---

shared/featureconfig/config.go

Missed this in #8623 
Resolves #8612

Remove no bootnode error for Prater

---

nogo_config.json
shared/featureconfig/config.go
shared/featureconfig/flags.go
validator/db/kv/BUILD.bazel
validator/db/kv/db.go

> Feature
Given slashing protection pruning has some large bottlenecks, we add a feature flag `--enable-slashing-protection-pruning` which prevents regular use of Prysm to trigger this feature.

Feature Flag for Enabling Slashing Protection Pruning

---

beacon-chain/interop-cold-start/service.go
beacon-chain/operations/attestations/metrics.go
beacon-chain/operations/attestations/prepare_forkchoice.go
beacon-chain/operations/attestations/prepare_forkchoice_test.go
beacon-chain/operations/attestations/prune_expired.go
beacon-chain/operations/attestations/prune_expired_test.go
beacon-chain/operations/attestations/service.go
beacon-chain/powchain/block_reader_test.go
beacon-chain/powchain/log_processing.go
beacon-chain/powchain/log_processing_test.go
beacon-chain/powchain/service.go
beacon-chain/powchain/service_test.go
beacon-chain/rpc/service.go
beacon-chain/rpc/service_test.go

Other
This pull request refactors the Service struct for the Attestation, POW Chain, and RPC services by having a pointer to the Config struct as one of the fields, removing duplicated field declarations.
Part of #8603
See #8618

Embed Config Pattern For Attestation, POW Chain, and RPC Services

---

beacon-chain/powchain/service.go

Fix Deduplication in Powchain Service

---

beacon-chain/rpc/beaconv1/config.go
beacon-chain/rpc/beaconv1/config_test.go
shared/params/config.go
shared/params/loader_test.go
shared/params/mainnet_config.go
shared/params/minimal_config.go

Add altair config for mainnet and minimal
References:
https://github.com/ethereum/eth2.0-specs/blob/dev/configs/minimal/altair.yaml
https://github.com/ethereum/eth2.0-specs/blob/dev/configs/mainnet/altair.yaml

Add altair config

---

endtoend/components/beacon_node.go

> Other / Refactoring
- Similar to #8665, but in this PR beacon node related data structures are defined: `BeaconNode` and `BeaconNodeSet`
Extracted from #8643

E2E refactoring: BeaconNode and BeaconNodeSet

---

beacon-chain/db/kv/slasher.go

Part of #8331, this PR moves as much encoding work outside of bolt DB transactions to reduce lock time in db reads and writes

Optimize Slasher DB Operations

---

beacon-chain/p2p/gossip_scoring_params.go

Add Remaining Gossip Scoring Topics

---

beacon-chain/powchain/service.go

Remove unused Client interface in powchain service

---

beacon-chain/db/kv/genesis.go

Fix typo in comment for LoadGenesis

---

validator/db/kv/deprecated_attester_protection.go

Cleanup
An equivalent of #8686, but for the validator package.
N/A
N/A

Wrap long lines in validator package

---

beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/helpers/slot_epoch_test.go
beacon-chain/core/helpers/weak_subjectivity.go
beacon-chain/core/helpers/weak_subjectivity_test.go
beacon-chain/rpc/beacon/blocks.go
beacon-chain/rpc/beacon/blocks_test.go
validator/db/kv/deprecated_attester_protection.go

> Feature
- implements `ComputeWeakSubjectivityPeriod` as defined in [specs](https://github.com/ethereum/eth2.0-specs/blob/master/specs/phase0/weak-subjectivity.md#calculating-the-weak-subjectivity-period)
N/A

Weak subjectivity period calculating helper

---

beacon-chain/core/state/state.go

> Refactor
Refactor update genesis eth1 data into its own function outside of genesis beacon state creation. This enables reusability across genesis beacon state Altair for testing and eliminates duplicated code

Genesis beacon state: refactor update eth1 data

---

beacon-chain/core/blocks/exit.go
beacon-chain/p2p/gossip_scoring_params.go
beacon-chain/state/stateV0/getters.go
beacon-chain/state/stateV0/getters_test.go

Fix deep source complains (ie. error punctuation, unused code... etc)

Fix deep source complains

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/sync_committee.go
beacon-chain/core/altair/sync_committee_test.go
shared/params/config.go

Add sync committee helpers for Altair:
```python
def get_sync_committee(state: BeaconState, epoch: Epoch) -> SyncCommittee:
"""
Return the sync committee for a given state and epoch.
"""
indices = get_sync_committee_indices(state, epoch)
pubkeys = [state.validators[index].pubkey for index in indices]
partition = [pubkeys[i:i + SYNC_PUBKEYS_PER_AGGREGATE] for i in range(0, len(pubkeys), SYNC_PUBKEYS_PER_AGGREGATE)]
pubkey_aggregates = [bls.AggregatePKs(preaggregate) for preaggregate in partition]
return SyncCommittee(pubkeys=pubkeys, pubkey_aggregates=pubkey_aggregates)
def get_sync_committee_indices(state: BeaconState, epoch: Epoch) -> Sequence[ValidatorIndex]:
"""
Return the sequence of sync committee indices (which may include duplicate …
```

Altair: Sync committee helpers

---

beacon-chain/core/epoch/epoch_processing.go

> Other / Specs compliance
- I've been working on specs checking tool in #8722 and discovered that we have an outdated `process_final_updates()` method, which got split into several methods in https://github.com/ethereum/eth2.0-specs/commit/daa47987045f041a09922a3ae1b244c882aaf5aa
- Currently, spec, instead of `process_final_updates`, features methods extracted from it:
- `process_eth1_data_reset(state)`
- `process_effective_balance_updates(state)`
-  `process_slashings_reset(state)`
-  `process_randao_mixes_reset(state)`
-  `process_historical_roots_update(state)`
-  `process_participation_record_updates(state)`
- Then those methods above are used in `process_epoch()`, see …

Refactor ProcessFinalUpdates(), per updated specs

---

beacon-chain/core/blocks/exit.go
beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/block.go
beacon-chain/core/helpers/randao.go
beacon-chain/core/helpers/shuffle.go
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/state/state.go
beacon-chain/core/state/transition.go
shared/bytesutil/bytes.go

- Follow up to #8724 
- In this PR, number of spec comments have been updated, to reflect what is currently in specs. I've reviewed each change manually, just to make sure that spec didn't change in a way that requires to update code (in addition to comments). Unsurprisingly, there weren't any such places -- so change is purely cosmetic.
- In number of files, we reuse pseudo-code (when a function we are implementing is split into several funcs in our code) for one method in doc comments to several of our functions. Sometimes, we amend the spec (by deleting certain parts, for example validation -- when we are implementing a non-validation-type of the method). In all such places, pristine spec docs is …

Update spec comments

---

.buildkite-bazelrc

Other
Caches external dependency fetching. This should decrease the initial start time for new build agents.
N/A

CI: Use experimental_remote_asset_api

---

beacon-chain/core/helpers/weak_subjectivity_test.go
shared/bls/blst/signature.go

Combine function parameters

---

.deepsource.toml

Other
The file [validator/web/site__data.go](https://github.com/prysmaticlabs/prysm/blob/develop/validator/web/site_data.go) is a generated file. This PR adds it to `exclude_patterns` while running analysis on DeepSource.
Thanks 🙂

Add generated file to DeepSource exclude_patterns

---

beacon-chain/core/state/transition_no_verify_sig.go

Motivated by #8638 
Reuse `ProcessBlockForStateRoot` for `ProcessBlockNoVerifyAnySig` for a much cleaner construction 
```go
func ProcessBlockForStateRoot(
ctx context.Context,
state iface.BeaconState,
signed *ethpb.SignedBeaconBlock,
) (iface.BeaconState, error) {
ctx, span := trace.StartSpan(ctx, "core.state.ProcessBlockForStateRoot")
defer span.End()
if err := helpers.VerifyNilBeaconBlock(signed); err != nil {
return nil, err
}
blk := signed.Block
body := blk.Body
bodyRoot, err := body.HashTreeRoot()
return nil, err
}
state, err = b.ProcessBlockHeaderNoVerify(state, blk.Slot, blk.ProposerIndex, blk.ParentRoot, bodyRoot[:])
traceutil.AnnotateError(span, err)
return nil, errors.Wrap(err, "could not process block header")
}
state, err = …
```

Reuse `ProcessBlockForStateRoot` for `ProcessBlockNoVerifyAnySig `

---

fuzz/block_fuzz.go
fuzz/rpc_status_fuzz.go
fuzz/ssz_encoder_attestations_fuzz.go
fuzz/state_fuzz.go
fuzzbuzz.yaml

cc @prestonvanloon 
Other
- necessary changes for an initial Fuzzbuzz (https://fuzzbuzz.io/) integration
- adds go-fuzz compatible (https://github.com/dvyukov/go-fuzz#usage) interfaces to existing fuzz tests, while leaving the beacon-fuzz interfaces intact
- adds a fuzzbuzz.yaml, which tells Fuzzbuzz how to understand a codebase
N/A

Set up Prysm for fuzz testing on Fuzzbuzz

---

tools/specs-checker/download.go

Fix redundant err check

---

endtoend/components/eth1.go

No tracking issue, small change to e2e test path for geth

Amend E2E Test Path

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/attestation.go
beacon-chain/core/altair/block.go
beacon-chain/core/altair/reward.go
beacon-chain/core/altair/reward_test.go

Part of #8638 
We missed to implement Altair's base reward calculation. It was still using phase 0's base reward calculation.

Altair: base reward implementation

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/transition.go
beacon-chain/core/altair/transition_no_verify_sig.go
beacon-chain/core/altair/transition_no_verify_sig_test.go
beacon-chain/core/helpers/BUILD.bazel
shared/testutil/altair/BUILD.bazel
shared/testutil/altair/altair.go
shared/testutil/helpers.go

Part of #8638 
This PR implements `ExecuteStateTransitionNoVerifyAnySig` along with a few test helpers.

Altair: `ExecuteStateTransitionNoVerifyAnySig` for state transition

---

scripts/ci-coverage.sh
scripts/codecov.sh

Vendor Codecov Script

---

WORKSPACE
beacon-chain/rpc/validator/proposer.go
beacon-chain/rpc/validator/proposer_test.go
third_party/rules_docker_bad_checksum.patch

Bug fix
Prysm nodes were unable to select a viable eth1data which caused issues in block production in mainnet.
Related to #8298

Independent eth1 voting

---

beacon-chain/core/altair/epoch_precompute.go
beacon-chain/core/altair/epoch_precompute_test.go
spectest/mainnet/altair/rewards/BUILD.bazel
spectest/mainnet/altair/rewards/rewards_test.go
spectest/minimal/altair/rewards/BUILD.bazel
spectest/minimal/altair/rewards/rewards_test.go
spectest/shared/altair/rewards/BUILD.bazel
spectest/shared/altair/rewards/rewards_penalties.go

> Other / Spec Tests
- Follow up to #8795
- Implements `mainnet/altair/rewards` tests (see [specs](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/mainnet/altair/rewards))
N/A

Altair: "rewards" spec tests

---

beacon-chain/cache/depositcache/deposits_cache.go

Other
Revert production code from #8809, but keep the tests.
Part of #8298
#8809 is being reverted as the code did not change the behavior of the deposit lookup. The original code used the standard library to perform a binary search lookup of the desired deposit index while the new code uses a linear search starting from the back of the list. 
While #8809 could be an improvement, especially if this list is long and the found elements are typically at the very end of the list, we do not have the supporting benchmarks or data to support the changes at this time. 
Given the sensitivity of the incident, I am proposing we revert the changes introduced in …

Partially revert PR #8809

---

fuzz/state_fuzz.go

Add New Method to Fuzz State

---

proto/validator/accounts/v2/keymanager.pb.go
proto/validator/accounts/v2/web_api.pb.go
proto/validator/accounts/v2_gateway/keymanager.pb.go
proto/validator/accounts/v2_gateway/web_api.pb.go
proto/validator/accounts/v2_gateway/web_api.pb.gw.go

Run go imports

---

beacon-chain/powchain/testing/BUILD.bazel
fuzz/BUILD.bazel
fuzz/block_fuzz.go

Other
Fixes a panic / fatal error with fuzz test runs
N/A

Use mock web3/powchain for fuzz test

---

beacon-chain/core/state/transition.go

Other
Refactoring code to provide better coverage of spec tests and reduce duplicated code.
No issue filed, but inspired by changes in #8840.
I did not test at runtime, but the ExecuteStateTransition method is only used in pcli, benchmark and spec tests. There should be no risk to Prysm runtime with these changes!

Refactor ExecuteStateTransition to use ExecuteStateTransitionNoVerifyAnySig

---

WORKSPACE

Other
Update golang to latest release. This release includes security fixes.
See release notes: https://groups.google.com/g/golang-announce/c/cu9SP4eSXMc

Update golang to 1.16.4

---

beacon-chain/rpc/beacon/validators.go
beacon-chain/rpc/beacon/validators_test.go

Handle Multiple Blocks For Canonical Checker

---

beacon-chain/core/altair/sync_committee.go
beacon-chain/core/altair/sync_committee_test.go

part of #8638 
Added validator helpers outlined [here](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md)

Altair: Add validator helpers for sync committee

---

beacon-chain/state/stateV0/state_trie.go

Fix comments typo

---

proto/beacon/db/finalized_block_root_container.pb.go
proto/beacon/db/powchain.pb.go
proto/beacon/p2p/v1/messages.pb.go
proto/beacon/p2p/v1/types.pb.go
proto/beacon/rpc/v1/debug.pb.go
proto/beacon/rpc/v1/debug.pb.gw.go
proto/beacon/rpc/v1/health.pb.go
proto/beacon/rpc/v1/health.pb.gw.go
proto/beacon/rpc/v1/slasher.pb.go
proto/beacon/rpc/v1/slasher.pb.gw.go
proto/validator/accounts/v2/keymanager.pb.go
proto/validator/accounts/v2/keymanager.pb.gw.go
proto/validator/accounts/v2/web_api.pb.go
proto/validator/accounts/v2/web_api.pb.gw.go

Ran go imports

---

beacon-chain/core/helpers/BUILD.bazel
beacon-chain/core/helpers/slot_epoch.go
beacon-chain/core/helpers/slot_epoch_test.go
beacon-chain/state/stateV0/field_trie_helpers.go
beacon-chain/state/stateV0/helpers_test.go

Other
Copying over pieces of hf1 branch to develop to reduce the total scope of hf1/altair merge.
N/A
Tracking #8638

Minor changes from hf1 branch

---

beacon-chain/p2p/pubsub_filter_test.go
beacon-chain/rpc/beaconv1/config_test.go
shared/params/config.go
shared/params/mainnet_config.go
shared/params/minimal_config.go

Add In Altair Fork Data

---

spectest/mainnet/altair/fork/BUILD.bazel
spectest/mainnet/altair/fork/upgrade_to_altair_test.go
spectest/minimal/altair/fork/BUILD.bazel
spectest/minimal/altair/fork/upgrade_to_altair_test.go
spectest/shared/altair/fork/BUILD.bazel
spectest/shared/altair/fork/upgrade_to_altair.go

Part of #8638 
Adding fork spec tests outlined here: https://github.com/ethereum/eth2.0-specs/tree/dev/tests/formats/forks

Altair: Add fork spec tests

---

beacon-chain/db/db.go
fuzz/ssz_encoder_attestations_fuzz.go
fuzz/state_fuzz.go

Remove unused functions

---

deps.bzl

Other
Follow-up to #8929. I forgot to run `gazelle -- update-repos`. 
N/A
N/A

Update deps.bzl after updating grpc-gateway dependency

---

WORKSPACE

Other
This is dependency hack was added for fuzz testing, but a workaround was added in #5095
N/A
If all tests pass, then this is safe to merge.

Remove unused sszgen dependency

---

WORKSPACE
shared/params/BUILD.bazel
shared/params/loader_test.go

Altair: update spec tests to alpha.6

---

shared/gateway/middleware_structs.go

Other
https://github.com/prysmaticlabs/prysm/pull/8920 updated the ethereumapis dependency. The new version includes some changes in proto field names. This has to be reflected in json tags.
Part of API Middleware feature
N/A

Update json tags to reflect changes in protocol buffers

---

beacon-chain/core/blocks/attestation_test.go
beacon-chain/sync/validate_beacon_attestation_test.go

Sorting imports in a few files

Sort imports

---

scripts/mirror-ethereumapis.sh

Fix repo name in mirror script

---

beacon-chain/db/kv/BUILD.bazel
beacon-chain/db/kv/altair.go
beacon-chain/db/kv/schema.go
beacon-chain/db/kv/state.go
beacon-chain/db/kv/state_test.go

Part of #8638 
Can get, save and delete Altair state in DB

Altair: save state in DB

---

scripts/mirror-ethereumapis.sh

Bug fix / Other
Exit without at status code was showing up as failed in buildkite
N/A

Proto mirror script fix

---

beacon-chain/rpc/beacon/validators.go

Other
This surfaces the underlying error to the user so that they have meaningful feedback.
Part of #9019

RPC: Surface underlying error when failing to return a state.

---

shared/bls/blst/secret_key.go
shared/bls/blst/secret_key_test.go
shared/bls/common/interface.go

Add Better Zero Key Checks

---

proto/eth/v1/beacon_chain_service.pb.go
proto/eth/v1/beacon_chain_service.pb.gw.go
proto/eth/v1/beacon_debug_service.pb.go
proto/eth/v1/beacon_debug_service.pb.gw.go

Run go imports for v1 endpoints

Go imports

---

beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/node/node.go
fuzz/block_fuzz.go

Rename field name `OpsService` to `AttService` to better reflect intend

Rename field ops service to att service 

---

beacon-chain/core/state/altair_transition_no_verify_sig_test.go
beacon-chain/p2p/pubsub_filter_test.go
shared/testutil/altair.go

Use Proper Test Util Methods For Altair

---

validator/client/aggregate.go
validator/client/validator.go

Updated comments and method name for aggregator methods

Better comments for aggregator functions

---

validator/client/wait_for_activation.go

Other
Removed superfluous error logs
Fixes #

Remove noisy / unneeded log.Error() calls

---

beacon-chain/p2p/gossip_scoring_params.go

Split out from #8994 
-[x] Adds in scoring parameters for new topics so that they can be subscribed.
N.A

Add New Parameters for Sync Committees And Sync Contribution

---

beacon-chain/p2p/fork_test.go
beacon-chain/rpc/eth/v1/beacon/BUILD.bazel
beacon-chain/rpc/eth/v1/beacon/config.go
beacon-chain/rpc/eth/v1/beacon/config_test.go
shared/p2putils/BUILD.bazel
shared/p2putils/fork.go
shared/p2putils/fork_test.go
shared/params/config.go
shared/params/loader_test.go
shared/params/mainnet_config.go
shared/params/minimal_config.go
shared/params/network_config.go

Add Updated Fork Utils

---

beacon-chain/cache/BUILD.bazel
beacon-chain/cache/sync_subnet_ids.go
beacon-chain/cache/sync_subnet_ids_test.go

Add Sync Subnet Id Cache

---

validator/client/sync_committee.go

Add logging for submitting 1.) sync message and 2.) sync contribution

Submitting sync committee message logs

---

deps.bzl
go.mod
go.sum
shared/aggregation/sync_contribution/BUILD.bazel
shared/aggregation/sync_contribution/contribution.go
shared/aggregation/sync_contribution/naive.go
shared/aggregation/sync_contribution/naive_test.go
shared/aggregation/testing/BUILD.bazel
shared/aggregation/testing/bitlistutils.go
shared/copyutil/BUILD.bazel
shared/copyutil/cloners.go

Add **naive** aggregation for `SyncCommitteeContribution` object (Altair)
**max-cover** aggregation is a `todo`, it will be tackled later

Naive aggregation for `SyncCommitteeContribution`

---

beacon-chain/rpc/validator/proposer_sync_aggregate.go
beacon-chain/rpc/validator/proposer_sync_aggregate_test.go

Add a method to search for the most profitable sync contribution object based on the bit count

Add search for most profitable sync contribution 

---

beacon-chain/core/altair/attestation.go
beacon-chain/core/altair/reward.go
beacon-chain/state/stategen/BUILD.bazel
beacon-chain/state/stategen/replay.go

Fix Stategen For Altair

---

beacon-chain/node/node.go
shared/params/config.go
validator/node/node.go

Feature Work
there aren't any mismatches when this is used at runtime.
N.A

Set Fork Schedule at Node Initialization

---

endtoend/components/beacon_node.go

E2E Improvement
panics can be captured in.
N.A

Capture All Output For Beacon Node

---

shared/queue/priority_queue.go
shared/queue/priority_queue_test.go

Other
Required / used in hf1 branch for Altair.
N/A
Original author: @terencechain. This was copied from hf1 branch.

shared/queue: Add RetrieveByKey method

---

WORKSPACE
shared/blockutil/block_utils.go

Update spec test

---

beacon-chain/state/stateutil/BUILD.bazel

Other
This target was set to "manual" and was not getting built in CI. 
This PR prevents code rot in this benchmark target.

beacon-chain/state/stateutil: Fix benchmark target

---

shared/copyutil/BUILD.bazel
shared/copyutil/cloners.go
shared/copyutil/cloners_test.go

Other
Incremental merge effort from hf1.
This PR introduces changes to shared/copyutil in the hf1 branch and also adds appropriate tests.
Builds on #9204. Please merge #9204 and sync this branch.

shared/copyutil: Add copy methods for Altair

---

validator/client/BUILD.bazel
validator/client/propose.go
validator/client/propose_protect.go
validator/client/propose_protect_test.go
validator/client/slashing_protection_interchange_test.go

`Hf1` changes but also applies to `develop`. This changes passing in protobuf block to passing in interface wrapper block.

Use block wrapper and interface for propose block

---

beacon-chain/core/helpers/committee.go
beacon-chain/rpc/apimiddleware/endpoint_factory.go
beacon-chain/rpc/apimiddleware/structs.go
beacon-chain/rpc/eth/v1/validator/validator.go
beacon-chain/rpc/eth/v1/validator/validator_test.go

Feature
Implements validator API's GetProposerDuties according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Validator/getProposerDuties
Part of #7510

Implement GetProposerDuties in the validator API

---

beacon-chain/core/epoch/precompute/justification_finalization_test.go
beacon-chain/core/epoch/precompute/new_test.go
beacon-chain/core/epoch/precompute/reward_penalty_test.go
beacon-chain/core/epoch/precompute/slashing_test.go
beacon-chain/core/epoch/precompute/type.go

Other
Introduces precompute package changes from Altair hf1 branch.
N/A

epoch/precompute: Add changes from Altair

---

beacon-chain/db/kv/kv.go

Cleanup
Cleans up the KV Store. The validator cache initialized there is completely unused, this most likely is a part of some long 
deleted piece of code. This came about in the review of #9155 
N.A

Remove Validator DB Cache

---

shared/gateway/gateway_test.go

Test
Regression test for #9264

Regression test for #9264

---

beacon-chain/core/altair/deposit_fuzz_test.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/core/state/state_test.go
beacon-chain/core/state/transition_test.go
beacon-chain/core/validators/validator_test.go
beacon-chain/operations/synccommittee/contribution.go
beacon-chain/operations/synccommittee/contribution_test.go
beacon-chain/operations/synccommittee/message.go
beacon-chain/operations/synccommittee/message_test.go
beacon-chain/operations/synccommittee/pool.go

Continuing #9304, Fixed more bad duplicated import prefix
Discovered in #9123

Fix more duplicated import prefix

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/reward.go
beacon-chain/core/altair/reward_test.go

Add altair base reward calculations
From #9123

Reward: altair base reward

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/sync_committee.go
beacon-chain/core/altair/sync_committee_test.go

Add sync message time validation helper from #9123 to `develop`
Credit to original author: @nisdas

Core helper: validate sync message time

---

beacon-chain/db/kv/state.go

Fix Historical State Representation For Altair

---

beacon-chain/db/kv/BUILD.bazel
beacon-chain/db/kv/migration_state_validators.go
beacon-chain/db/kv/migration_state_validators_test.go
beacon-chain/db/kv/state_test.go

Cleanup
As a follow up to #9326 , we also allow the state migration to 
handle altair states.
N.A

Fix Altair State Migration

---

beacon-chain/rpc/eth/v1/beacon/pool_test.go
beacon-chain/rpc/eth/v1/beacon/state_test.go
beacon-chain/rpc/eth/v1/debug/debug.go
beacon-chain/rpc/statefetcher/fetcher_test.go
beacon-chain/state/altair.go
shared/htrutils/htrutils.go
shared/htrutils/htrutils_test.go
shared/testutil/sync_committee.go

Cleanup: rm duplicated imports

---

beacon-chain/rpc/eth/v1/beacon/config_test.go
shared/params/config.go
shared/params/loader.go
shared/params/loader_test.go
shared/params/mainnet_config.go
shared/params/minimal_config.go

Fix Config Loader Changes

---

beacon-chain/sync/pending_blocks_queue.go
beacon-chain/sync/pending_blocks_queue_test.go

Change to Proto Check For Blocks

---

beacon-chain/p2p/rpc_topic_mappings.go
beacon-chain/p2p/rpc_topic_mappings_test.go

Add in V2 RPC Topic Mappings

---

beacon-chain/p2p/types/BUILD.bazel
beacon-chain/p2p/types/object_mapping.go
beacon-chain/p2p/types/object_mapping_test.go

Altair Work
decide which data type is used in which fork.
N.A

Add in Object Mapping For Types

---

WORKSPACE
shared/params/BUILD.bazel
shared/params/loader.go
shared/params/loader_test.go
shared/testutil/bazel.go
spectest/utils/utils.go

Other
As title describes. I also added some additional sanity checks in the test helpers to ensure that empty directories or files were not processed. 

Update spectests to v1.1.0-beta.1 from hf1 branch

---

beacon-chain/core/blocks/BUILD.bazel
beacon-chain/core/blocks/attester_slashing.go
beacon-chain/core/blocks/attester_slashing_test.go
beacon-chain/core/blocks/proposer_slashing.go
beacon-chain/core/blocks/proposer_slashing_test.go

from #9123 
fixes #9413 
Slash validator with Altair config 🔪

Slash validator with altair config

---

beacon-chain/forkchoice/protoarray/store.go

Remove float64 usage for protoarray forkchoice's apply weight changes

Remove float64 usage for fork choice

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/transition.go
beacon-chain/core/altair/transition_test.go

Add `process_epoch` for altair

Add altair process epoch

---

beacon-chain/p2p/fork.go

Change P2P Logs to Trace Logs

---

beacon-chain/state/stategen/replay.go

Cosmetic Work
from where state regeneration starts and ends.
N.A

Add Stategen Log

---

beacon-chain/core/altair/reward_test.go
beacon-chain/core/state/BUILD.bazel
beacon-chain/core/state/altair_transition_no_verify_sig_test.go
beacon-chain/core/state/transition_no_verify_sig_test.go

Add in Remaining Altair Core Tests

---

spectest/mainnet/phase0/shuffling/core/shuffle/BUILD.bazel
spectest/minimal/altair/sanity/BUILD.bazel
spectest/utils/BUILD.bazel

Other
As title describes, spectest sizes or timeouts were not appropriately set for targets.
Helps with some spectest failures in CI.

fix spectest timeouts and sizing

---

beacon-chain/rpc/eth/beacon/pool.go
beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
beacon-chain/rpc/statefetcher/fetcher_test.go
beacon-chain/state/stategen/mock.go
shared/sszutil/deep_equal_test.go

Cosmetic cleanup, fix span names and import names from #9123

Clean up from `hf1`

---

beacon-chain/sync/subscriber.go

Switch To Debug Log

---

beacon-chain/sync/pending_blocks_queue_test.go
beacon-chain/sync/service.go

Altair Work
This was supposed to be included in #9550, but was missed. The PR adds in the launching of the fork
watcher routine during state initialization.
N.A

Run Fork Watcher

---

shared/featureconfig/config.go
shared/featureconfig/deprecated_flags.go
shared/featureconfig/flags.go

Flips feature to enable insertion of orphaned attestation. This feature is required for testnet support and will be a requirement for v2.0.0.

Enable insert orphaned attestation

---

shared/params/testnet_e2e_config.go
testing/endtoend/evaluators/operations.go

Other
This PR reverts part of #9565 related to e2e and adds an override in the e2e params so that e2e behaves as it did before #9565.

Fix long running e2e tests

---

beacon-chain/blockchain/metrics.go
beacon-chain/p2p/monitoring.go

Metrics Work
https://github.com/ethereum/beacon-metrics/pull/12
N.A

Standardize Metrics To Match Minimal Metric Spec

---

hack/ci-coverage.sh
hack/upload_fuzzers.sh

CI: use nostamp for code coverage and fuzzer uploads

---

async/every.go
async/scatter.go
beacon-chain/core/transition/state.go
network/external_ip.go
runtime/service_registry.go
time/slots/slotticker.go
time/utils.go

Correct package name in the exported comments

Update package name comments

---

config/features/flags.go

Make Opt Max Cover Default

---

beacon-chain/slasher/BUILD.bazel
beacon-chain/slasher/detect_attestations.go
beacon-chain/slasher/detect_attestations_test.go
beacon-chain/slasher/helpers_test.go
beacon-chain/slasher/receive.go
beacon-chain/slasher/service.go

This PR detects slashable attestations in an optimized slasher implementation from feature/slasher. Diff is mostly tests

Detect Slashable Attestations in Optimized Slasher

---

.buildkite-bazelrc

Other
Running into this issue: https://github.com/bazelbuild/bazel/issues/13355
This is blocking some PR submissions.

CI: fix remote caching

---

beacon-chain/p2p/service.go

Increase Pubsub Queue Size

---

config/features/flags.go

Remove Peer Scorer From Dev

---

validator/client/service.go

This PR registers our slashing protection grpc client in the validator, required for remote slashing protection

Register Slashing Protection Client in Validator

---

beacon-chain/state/stategen/getter_test.go

GenesisState when zero hash tests

---

validator/client/validator.go

>
> Bug fix
This PR fixes two typos in `validator.go`. Removing typos improves legibility and reduces cognitive overhead.

Fix typos: repones -> response, attestion -> attestation

---

beacon-chain/p2p/gossip_scoring_params.go
beacon-chain/p2p/gossip_scoring_params_test.go

Cleanup
function signatures to account for that.
N.A

Remove Superflous Errors From Parameter Registration

---

testing/endtoend/minimal_e2e_test.go

Other
This check was skipped previously for prior release as the v2 functionality for Altair had not been released yet.

Unskip v2 end to end check for prior release

---

beacon-chain/blockchain/process_block.go
beacon-chain/core/blocks/attestation_test.go
beacon-chain/core/blocks/header_test.go
beacon-chain/core/blocks/randao_test.go
beacon-chain/core/blocks/signature.go
beacon-chain/core/signing/signing_root.go
beacon-chain/core/transition/transition_no_verify_sig.go
beacon-chain/sync/batch_verifier.go
beacon-chain/sync/batch_verifier_test.go
beacon-chain/sync/validate_aggregate_proof.go
beacon-chain/sync/validate_beacon_attestation.go
beacon-chain/sync/validate_sync_committee_message.go
beacon-chain/sync/validate_sync_contribution_proof.go
crypto/bls/BUILD.bazel
crypto/bls/signature_batch.go
crypto/bls/signature_batch_test.go
testing/spectest/shared/altair/operations/attestation.go
testing/spectest/shared/phase0/operations/attestation.go

Cleanup
than a group of unique signatures.
N.A

Rename To Signature Batch

---

beacon-chain/monitor/process_block.go

Fix for validator_monitor... error of binary operator precendence.

fix operation precedence

---

proto/migration/BUILD.bazel
proto/migration/v1alpha1_to_v1.go
proto/migration/v1alpha1_to_v1_test.go
proto/migration/v1alpha1_to_v2.go
proto/migration/v1alpha1_to_v2_test.go

In anticipation for the merge, moving the migration tools from v1alpha <---> v2 to a separate file.

Add v1alpha1_to_v2.go

---

deps.bzl
go.mod
go.sum

Other
Follow up to #9960, updates go-ethereum to latest release.
No known issues or fixes in this release with regards to Prysm.

Update go-ethereum to v1.10.13

---

beacon-chain/monitor/process_attestation.go
beacon-chain/monitor/process_attestation_test.go

more monitor typos of the same kind, apologies for this.

more typos

---

api/gateway/gateway.go

Bug fix
CORS was blocking the web app after some of our latest changes. this PR fixes the mistake

fix cors middleware

---

WORKSPACE
config/params/loader_test.go

Update spec test to v1.1.7

---

beacon-chain/core/transition/BUILD.bazel
beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go
beacon-chain/core/transition/transition_no_verify_sig.go
beacon-chain/core/transition/transition_no_verify_sig_test.go
testing/util/BUILD.bazel
testing/util/bellatrix.go

This PR adds the following to `process_block`. After this PR we can merge Bellatrix to spec test to `develop` 🎉 
```python
if is_execution_enabled(state, block.body):
process_execution_payload(state, block.body.execution_payload, EXECUTION_ENGINE)  # [New in Bellatrix]
```

Add process_execution_payload to process_block

---

go.mod
go.sum
tools/deployContract/BUILD.bazel
tools/deployContract/deployContract.go

Other
Cleaning up old / rotten code. This is required for updating rules_go (https://github.com/prysmaticlabs/prysm/pull/10064)

tools/deployContract: Remove specific k8s code

---

testing/endtoend/helpers/helpers.go
tools/specs-checker/download.go
validator/accounts/accounts_backup.go

Other
Fixes gosec issues with latest gosec update.

Resolve issues with G304

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Make Batch Verification Of Gossip Default

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Make Get Block Optimization Default

---

beacon-chain/forkchoice/protoarray/BUILD.bazel
beacon-chain/forkchoice/protoarray/optimistic_sync.go
beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
beacon-chain/forkchoice/protoarray/store.go
beacon-chain/forkchoice/protoarray/types.go

Add a function to check whether a synced block is optimistic or not.

Is optimistic

---

beacon-chain/state/state-native/v2/BUILD.bazel
beacon-chain/state/state-native/v2/beacon_state_mainnet.go
beacon-chain/state/state-native/v2/beacon_state_minimal.go
beacon-chain/state/state-native/v2/getters_validator.go
beacon-chain/state/state-native/v2/state_trie.go

Cleanup
Some code inside `/state-native/v2` incorrectly imports non-native packages.

Fix native state imports

---

config/params/testnet_e2e_config.go

Cleanup
to #10020 in time. 
N.A

E2E Config Cleanup

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/chain_info_test.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/forkchoice/interfaces.go

Add `IsOptimistic` chain info getter

Add `IsOptimistic` chain info getter

---

hack/beacon-node-api/README.md
hack/beacon-node-api/beacon-node-api.postman-collection.json

*INSPIRED BY #10209*
Other
Introducing a Postman collection of endpoints along with its documentation.

Beacon Node API Postman collection

---

beacon-chain/powchain/service.go

Bug Fix
a placeholder and doesn't actually exist in the execution layer. We modify our powchain service to handle it better. 
N.A

Handle a ZeroHash as our Eth1 Genesis Block Root

---

beacon-chain/blockchain/process_block.go

This is a first take on enabling optimistically synced blocks. This PR modifies `onBlock` to continue even on failure from `ExecutePayload`. It also modifies the `onBlockBatch` to return a list of optimistic statuses on the block batch, and modifies the call site to save the synced tips accordingly

Sync optimistically candidate blocks 

---

beacon-chain/sync/fork_watcher.go
beacon-chain/sync/fork_watcher_test.go

Fork Addition
bellatrix as well.
N.A

Handle Bellatrix Fork Epochs Correctly

---

beacon-chain/forkchoice/protoarray/store.go

Removes unnecessary reassignment of a pointer in fork choice

Remove unnecessary reassignement

---

beacon-chain/rpc/eth/beacon/config_test.go
beacon-chain/state/state-native/v3/field_roots.go
beacon-chain/state/v3/field_roots.go
config/params/config.go
config/params/mainnet_config.go
config/params/testnet_prater_config.go

Cleaning up some outdated Bellatrix code

Clean up outdated bellatrix code

---

validator/keymanager/remote-web3signer/v1/web3signer_types.go

Bug fix
I discovered that one of the JSON mappings were incorrect with the spec from web3signer side
Fixes #9994

web3signer: JSON Mapping bug

---

beacon-chain/powchain/engine-api-client/v1/client.go
beacon-chain/powchain/engine-api-client/v1/client_test.go

`eth_blockByHash` should be `eth_getBlockByHash`
`eth_blockByNumber` should be `eth_getBlockByNumber`

Fix engine client method names

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

Other
We did a lot of copy pasta and that is bad. 
Expect more PRs like this... there is so much pasta.

Deduplicate TestProposer_ProposeBlock_OK

---

beacon-chain/powchain/service.go

Remove Kiln Flag Check

---

encoding/ssz/merkleize.go
encoding/ssz/merkleize_test.go

Fixes an off-by-one in the logarithm implementation

Fix logarithm of 2

---

validator/keymanager/remote-web3signer/internal/client.go
validator/keymanager/remote-web3signer/v1/custom_mappers.go
validator/keymanager/remote-web3signer/v1/web3signer_types.go

Bug fix
This pr addresses caugh issues from e2e testing for the web3signer feature.
Fixes #9994

web3signer: fixes for e2e

---

beacon-chain/p2p/pubsub.go

Cleanup
This wasn't able to be pushed to #10309 in time, so it is added into this new PR. 
Fixes #

Add Better Error Logs for Context Deadlines

---

async/multilock_test.go

Bug fix
lock.Unlock() should happen before wg.Done()
unit test

fix TestLockUnlock_CleansUnused

---

config/features/README.md

Cleanup
The package name in features' README is incorrect.

Correct package name in features' README file

---

beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/interfaces.go
beacon-chain/forkchoice/protoarray/optimistic_sync.go
beacon-chain/forkchoice/protoarray/optimistic_sync_test.go

Export removal of  optimistic invalid nodes

Export SetOptimisticToInvalid

---

testing/spectest/mainnet/bellatrix/forkchoice/BUILD.bazel
testing/spectest/mainnet/bellatrix/forkchoice/forkchoice_test.go
testing/spectest/minimal/bellatrix/forkchoice/BUILD.bazel
testing/spectest/minimal/bellatrix/forkchoice/forkchoice_test.go
testing/spectest/shared/common/forkchoice/BUILD.bazel
testing/spectest/shared/common/forkchoice/runner.go
testing/spectest/shared/common/forkchoice/service.go
testing/spectest/shared/common/forkchoice/type.go

This PR implements fork choice spec tests for Bellatrix. These comprehensive tests cover total difficulty validation and more.

Bellatrix fork choice spec tests

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go

Add `notifyNewPayload` to `onBlockBatch`. This ensures that `notifyNewPayload` gets called during initial syncing

Add notifyNewPayload to onBlockBatch

---

beacon-chain/blockchain/process_block.go
beacon-chain/state/fieldtrie/field_trie_helpers.go
beacon-chain/state/stateutil/participation_bit_root.go
beacon-chain/state/stateutil/trie_helpers.go
encoding/ssz/helpers.go

Block Processing And State Transition Improvments

---

beacon-chain/blockchain/optimistic_sync.go
beacon-chain/powchain/engine-api-client/v1/BUILD.bazel
beacon-chain/powchain/engine-api-client/v1/client.go

This PR adds tracings to engine API methods and improves debugability by having more instrumentation.

Add tracings for engine api methods

---

beacon-chain/blockchain/receive_block.go
beacon-chain/sync/validate_beacon_blocks.go

Remove TODOs that were already taken care of

---

beacon-chain/blockchain/chain_info.go
beacon-chain/blockchain/error.go
beacon-chain/blockchain/new_slot_test.go
beacon-chain/blockchain/optimistic_sync_test.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/blockchain/service.go
beacon-chain/blockchain/service_test.go
beacon-chain/blockchain/state_balance_cache.go
beacon-chain/blockchain/state_balance_cache_test.go
beacon-chain/blockchain/testing/mock.go

Lots of great work is happening within blockchain pkg lately. It's essential we clean it up once a while

Clean up blockchain pkg

---

beacon-chain/blockchain/error.go
beacon-chain/blockchain/optimistic_sync.go
beacon-chain/blockchain/optimistic_sync_test.go
beacon-chain/blockchain/process_block.go

This PR inserts a block to forkchoice after notifyNewPayload has returned.

insert block to forkchoice after notifyNewPayload

---

beacon-chain/blockchain/chain_info_norace_test.go
beacon-chain/blockchain/head.go
beacon-chain/blockchain/head_test.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/blockchain/receive_attestation_test.go
beacon-chain/blockchain/service_norace_test.go

Use the new correct head for `notifyForkchoiceUpdate`, not previously cached head

Use correct head for `notifyForkchoiceUpdate`

---

beacon-chain/rpc/apimiddleware/structs.go

Bug fix
One field was missed in #10479 (see https://github.com/prysmaticlabs/prysm/pull/10479#issuecomment-1087450033)
Fixes #10460

Fix receipts root field name in API Middleware

---

.github/workflows/horusec.yaml

Feature
Adds Horusec scanner and scheduled it to run every Sunday
Fixes #

Added horusec

---

beacon-chain/blockchain/optimistic_sync.go

Fix optimistic logging

---

beacon-chain/blockchain/process_block.go

This PR optimizes the time-to-set proposer boost. It shreds off the wait time by ~50%
Based on the local setup, it takes ~100ms to set proposer boost, ~50ms of that is saving state and blocks to DB. We can move them after setting proposer boost.
```
state_transition (30ms)
notify_new_payload (10ms)
save_block_to_forchoice (1ms)
save_state_block_to_db (40ms)
set_proposer_boost
state_transition (30ms)
notify_new_payload (10ms)
save_block_to_forchoice (1ms)
set_proposer_boost
save_state_block_to_db (40ms)
```
Discovered in:

Save state to DB after proposer boost

---

WORKSPACE

Update to 1.17.9

---

beacon-chain/db/kv/migration_state_validators.go
beacon-chain/db/kv/state.go
nogo_config.json
tools/analyzers/gocognit/analyzer.go

gocognit: Lower complexity threshold to 100, fix a few complexity issues

---

beacon-chain/node/node_test.go
cmd/beacon-chain/powchain/options_test.go
cmd/validator/slashing-protection/import_export_test.go
io/file/fileutil_test.go
tools/http-request-sink/main_test.go
tools/interop/split-keys/main_test.go
validator/db/kv/attester_protection_test.go
validator/rpc/auth_token_test.go
validator/rpc/wallet_test.go

Cleanup
Use the `T.TempDir` and `B.TempDir` methods from the testing package to create temporary directories. The directories created are automatically removed when the test and subtests are complete

Use the T.TempDir and B.TempDir to create temp dirs for testing

---

testing/endtoend/BUILD.bazel
testing/endtoend/mainnet_e2e_test.go
testing/endtoend/minimal_e2e_test.go
testing/endtoend/multiclient_e2e_test.go
testing/endtoend/params/params.go

Fix Broken E2E Runs

---

validator/client/validator.go

Other
Additional comments were left on https://github.com/prysmaticlabs/prysm/pull/10543 and so we would like to further improve the description of the logs for our users.

Fee Recipient: improve logs

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/pubsub_fuzz_test.go

Other
Fixes pubsub fuzz test to run properly.

p2p: Fix pubsub fuzz test

---

beacon-chain/blockchain/process_block.go

This fixes #10545
Use `notifyEngineIfChangedHead` which does `notifyForkchoiceUpdate` and `saveHead`, in addition, it handles nil head block race conditions within

Use notify engine if changed head method

---

beacon-chain/sync/subscriber_beacon_blocks.go

This fixes #10612 
Don't mark undefined ee error block bad in regular block processing subscriber

Don't mark undefined ee error block bad for regular processing

---

beacon-chain/cache/active_balance_test.go
beacon-chain/cache/committee_fuzz_test.go
beacon-chain/cache/committee_test.go
beacon-chain/cache/proposer_indices.go
beacon-chain/cache/proposer_indices_disabled.go
beacon-chain/cache/proposer_indices_test.go
beacon-chain/core/helpers/validators_test.go
crypto/bls/blst/BUILD.bazel

Other
Follow up to #10618
Fixes #

fuzz: Fix tests with fuzz tags

---

beacon-chain/blockchain/head.go
beacon-chain/blockchain/head_test.go
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Makes insertion of orphaned attestations the permanent default and removes the flag to disable it.
N.A

Graduate Orphaned Attestation Insertion Feature

---

beacon-chain/blockchain/receive_attestation.go

Change log when head changes

---

beacon-chain/blockchain/receive_attestation.go

Move `Head changed due to attestations` to the appropriate spot

Move head change attestation log

---

beacon-chain/rpc/prysm/v1alpha1/validator/server.go

Remove method `CanonicalHead`  from the validator server

Remove unused method

---

beacon-chain/sync/sync_fuzz_test.go

Add More Block Fuzz Targets

---

beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go

Other - Code cleanup
This PR refactors a highly complex StreamBlocksAltair to smaller methods that can improve readability.
go-cognit scores
Before
```
85 validator (*Server).StreamBlocksAltair beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go:16:1
```
After
```
16 validator (*Server).StreamBlocksAltair beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go:16:1
12 validator sendVerifiedBlocks beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go:48:1
9 validator (*Server).sendBlocks beacon-chain/rpc/prysm/v1alpha1/validator/blocks.go:88:1
```

Refactor high complexity StreamBlocksAltair

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/new_slot_test.go

new_slot_test.go was not included in the testsuite. This PR fixes that and fixes the tests since they wouldn't pass.

Add new slot tests

---

beacon-chain/blockchain/error.go
beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/init_sync_process_block.go
beacon-chain/blockchain/state_balance_cache.go
beacon-chain/blockchain/weak_subjectivity_checks.go

Consolidate all the blockchain pkg `error` in one file

Consolidate blockchain errors

---

beacon-chain/core/validators/BUILD.bazel
beacon-chain/core/validators/validator.go
time/slots/BUILD.bazel
time/slots/slottime.go

Cleanup
Uses correct math library, #10739 was used to check for withdrawal epoch overflows. However the PR used the wrong math library. This PR fixes it by using our own internal math util library.
N.A

Use Correct Math Library

---

beacon-chain/powchain/metrics.go

Engine metrics: help text typos

---

testing/endtoend/endtoend_setup_test.go
testing/endtoend/mainnet_scenario_e2e_test.go

Bug Fix
Fixes Scenario test runs by removing some evaluators that do not function well in the scenario test environment.
N.A

Fix Scenario Tests

---

testing/mock/BUILD.bazel
testing/mock/beacon_chain_service_mock.go
testing/mock/beacon_service_mock.go
testing/mock/beacon_validator_client_mock.go
testing/mock/beacon_validator_server_mock.go
testing/mock/node_service_mock.go
validator/client/validator_test.go
validator/client/wait_for_activation_test.go

Discovered from other PRs that we haven't ran mockgen in a while. I did the following
- Upgrade mockgen to latest release v1.6.0
- ./hack/update-mockgen.sh
- Fix bad tests due to updating to new mocks

Run mockgen

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_helpers.go
beacon-chain/blockchain/process_block_test.go

Update Forkchoice justified checkpoint at the end of block batch processing.

Update forkchoice justified on init sync

---

beacon-chain/db/kv/blocks.go

Bug fix
This is a fix in response to a bug pointed out by Nishant here https://github.com/prysmaticlabs/prysm/pull/10772#pullrequestreview-991368080
An issue hasn't been filed - there is currently no way to trigger this bug.
I changed the structure of the loop so that we always check the termination condition and update the values each iteration, but the complex initialization, and the need to look at the initial k/v before moving the cursor, led to the need to create an initialization function to fit into the for statement structure.

rewind cursor upon nil value (bucket)

---

beacon-chain/state/state-native/state_trie.go
beacon-chain/state/v1/state_trie.go
beacon-chain/state/v2/state_trie.go
beacon-chain/state/v3/state_trie.go

Clean Up State Finalizer

---

config/features/config.go

Enable --dev flag when testing on Ropsten.

enable dev on Ropsten

---

testing/endtoend/endtoend_test.go

Other
This sets a fixed 3 minute timeout for the checkpoint sync matching head check, and adds the elapsed time to logs so that we can easily determine if the head check hit the 3m timeout or ctx got canceled somewhere higher in the tree.
This is targeted at gaining some clarity around how the checkpoint sync head comparison test impacts long-running e2e failures.

checkpoint sync e2e to use 3m timeout w/ elapsed log

---

beacon-chain/powchain/metrics.go

Update engine APU buckets to use a more sensible range

Update engine api buckets

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Feature flag
Enables the native state feature by default.

Revert `enable-native-state` flag

---

go.mod
go.sum

Other
Update fastssz dependency to include changes from https://github.com/prysmaticlabs/fastssz/pull/8

Update fastssz dependency

---

beacon-chain/builder/service.go

Bug Fix
This fixes a panic in our builder service when no builder is set in it.
N.A

Fix Builder Service Panic

---

beacon-chain/state/v1/state_fuzz_test.go

Other
Adds fuzz test for unmarshal ssz state and uses the example found in #5167
Fixes #5167

State: add fuzz test for unmarshal ssz

---

beacon-chain/powchain/check_transition_config.go

Don't log `terminal difficulty has not been reached yet...` until Bellatrix

---

config/params/testnet_sepolia_config.go

Added a few more boot nodes from https://github.com/eth-clients/sepolia/tree/main/bepolia

More sepolia boot nodes

---

beacon-chain/blockchain/process_block.go

Avoid a call to `fillInForkchoiceMissingBlocks` during regular sync early if forkchoice has the parent block.

Do not fill in missing blocks on regular sync

---

runtime/fdlimits/fdlimits.go

Minor improvement to the log
`[2022-07-01 08:32:50]  INFO Raised fd limit to 10240 from 61440`
👇🏼 
`[2022-07-01 08:57:42]  INFO main: Raised file descriptor limit to 10240 from 61440`

Improve "rasied file descriptor limit..." log

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go

Compare to prestate checkpoints also when updating finalized checkpoints.

update finalization on onblock

---

api/client/builder/BUILD.bazel
api/client/builder/client.go

Other
As title describes, adds more spans to help debug timeouts and long delays with SubmitValidatorRegistration requests.
Related: https://github.com/prysmaticlabs/prysm/issues/10949

Annotate build client requests

---

testing/endtoend/components/beacon_node.go
testing/endtoend/components/eth1/proxy.go
testing/endtoend/components/lighthouse_beacon.go
testing/endtoend/components/lighthouse_validator.go
testing/endtoend/components/validator.go

fix some typo and comments
Fixes #

fix some comments

---

beacon-chain/powchain/testdata/fuzz/FuzzForkChoiceResponse/2d0486b744e252db538db5a44bfd6e6e22ff2723
proto/engine/v1/json_marshal_unmarshal.go

Bug Fix
This crash was reported in fuzzbuzz, the PR fixes the reported crash by having strict length checks when unmarshalling the payload bytes.
N.A

Fix FuzzForkChoiceResponse Crash

---

beacon-chain/builder/BUILD.bazel
beacon-chain/builder/error.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go

- New metric to track count when falls back to local execution engine due to builder fault
- New info log for builder public key and bid amount. Very useful info for validator to track
- Remove unused error

Misc improvements to interface with builder

---

config/features/config.go

Adding these feature flags to testnet default for more soaking

Add feature flags to testnet default

---

beacon-chain/powchain/service.go

>
> Bug fix
> Feature
> Other
Fixes #

Better Log In Case Contract Code Not Found At Address

---

cmd/validator/flags/flags.go
cmd/validator/main.go
cmd/validator/usage.go
validator/node/node.go

Add flag for validator gas limit catch-all

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

Make Batch Gossip Aggregation The Default

---

beacon-chain/rpc/prysm/v1alpha1/validator/server.go
validator/client/validator.go

Other
Just improve log for public key not found, remove "not found".
Fixes #

improve log for public key not found

---

beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/doubly-linked-tree/store.go
beacon-chain/forkchoice/protoarray/store.go

Fixing deep source complains in #11146

Remove unused ctxs

---

config/features/config.go

Remove Slasher Lookback Toggle as it is completely unused.
Fixes #

Remove Toggle

---

config/features/config.go
contracts/deposit/BUILD.bazel
contracts/deposit/deposit.go
crypto/bls/blst/BUILD.bazel
crypto/bls/blst/public_key.go
crypto/bls/blst/secret_key.go
crypto/bls/blst/signature.go

This PR removes our ability to skip bls verification via our feature config. This is not used used at all now, therefore the feature is redundant.
Fixes #

Remove Skip BLS Verification Feature

---

beacon-chain/p2p/BUILD.bazel
beacon-chain/p2p/pubsub.go
config/features/config.go
config/features/flags.go

This feature was added in a few years back for testing, however this serves no purpose now and might have
adverse effects for users who want to use it.
N.A

Remove Gossip History Flag

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
proto/prysm/v1alpha1/validator.pb.go
proto/prysm/v1alpha1/validator.proto

Remove deprecated `SubmitValidatorRegistration` for v3

Remove deprecated `SubmitValidatorRegistration`

---

.github/workflows/go.yml
.golangci.yml

Use GolangCI-Lint for Goimports Checking Instead of Third-Party Image

---

cmd/validator/flags/flags.go

Fixed flag usage text typo.

---

.github/workflows/go.yml

Tag Gosec To Last Stable Version

---

config/features/deprecated_flags.go
config/features/flags.go

V3 Fix
This gives users appropriate notice before completely removing a flag.
N.A

Handle Deprecated Flags Correctly

---

cmd/beacon-chain/execution/options.go

UX
Adds a log if we successfully parse the JWT secret file.
N.A

Improve Logging When Parsing JWT Secret

---

deps.bzl
go.mod
go.sum
testing/endtoend/components/eth1/miner.go
testing/endtoend/components/eth1/node.go
testing/endtoend/evaluators/fork.go

Update Geth Version In Prysm

---

fuzzbuzz.yaml

Config Fix
Fix Failing fuzzbuzz builds
N.A

Pin Fuzzbuzz to Go 1.18

---

beacon-chain/blockchain/execution_engine.go
beacon-chain/blockchain/log.go
beacon-chain/blockchain/metrics.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/core/epoch/BUILD.bazel
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/validators/BUILD.bazel
beacon-chain/core/validators/validator.go
beacon-chain/execution/engine_client.go
beacon-chain/execution/metrics.go
beacon-chain/sync/initial-sync/round_robin.go

Add new metrics

---

beacon-chain/forkchoice/protoarray/BUILD.bazel
beacon-chain/forkchoice/protoarray/store.go
beacon-chain/forkchoice/protoarray/store_test.go

Defensive pulls protoarray

---

beacon-chain/p2p/monitoring.go

Fix Div By 0 in Small Helper

---

beacon-chain/forkchoice/doubly-linked-tree/node.go
beacon-chain/forkchoice/protoarray/store.go

Make sure we increase finalization.

Harden witholding fix

---

beacon-chain/forkchoice/doubly-linked-tree/store.go

Hint the GC by removing all references to children's nodes.

remove children slice when pruning

---

beacon-chain/rpc/apimiddleware/structs.go

Fix a bad timestamp encoding in forkchoice endpoint

fix forkchoice endpoint

---

beacon-chain/p2p/parameter_test.go
beacon-chain/p2p/pubsub.go
beacon-chain/p2p/service.go

Bug Fix
Our gossipsub parameter was set to 6, while the spec has it as 8. With a smaller mesh size this causes issues with propagating messages effectively and also receiving incoming messages vice versa. This PR fixes the discrepancy so that messages can now be propagated more effectively.
N.A

Fix Gossipsub Parameter

---

WORKSPACE
testing/spectest/shared/common/forkchoice/service.go

Fix sync test setup and update to v 1.2.0

Fix sync tests and update to 1.2.0

---

.github/CODEOWNERS

Cleanup
After merging https://github.com/prysmaticlabs/prysm/pull/11445 we no longer have duplicated code between different types of states. This means we no longer need to take extra precautions when dealing with PRs that touch the state.

Remove state code owners

---

beacon-chain/blockchain/head_sync_committee_info_test.go
beacon-chain/blockchain/testing/mock.go
beacon-chain/core/transition/BUILD.bazel
beacon-chain/core/transition/skip_slot_cache.go
beacon-chain/core/transition/skip_slot_cache_test.go
beacon-chain/core/transition/transition.go
beacon-chain/rpc/eth/beacon/pool_test.go
beacon-chain/rpc/eth/validator/validator.go
beacon-chain/rpc/eth/validator/validator_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go

Reverts prysmaticlabs/prysm#11441

Revert "More efficient way of computing skip slot cache key"

---

beacon-chain/node/BUILD.bazel
beacon-chain/node/node.go
beacon-chain/node/node_test.go

Bug Fix
This properly retrieves values for our validator monitor flag from the cli context along with adding in a regression test.
Fixes #11532

Fix Validator Monitor Registration

---

beacon-chain/p2p/monitoring.go

Handles the change in agent string for newer lodestar nodes.
Fixes #11430 

Handle New Agent Version For Lodestar

---

testing/endtoend/component_handler_test.go
testing/endtoend/components/eth1/node_set.go

>
fix some comment and log error
Fixes #

fix some comment and log error

---

beacon-chain/state/interfaces.go
beacon-chain/state/state-native/readonly_validator.go
beacon-chain/state/state-native/readonly_validator_test.go

This PR adds Capella helpers for state transition.

Add Withdrawal helpers

---

beacon-chain/blockchain/error.go
beacon-chain/state/stategen/replay.go

some minor fixes

---

beacon-chain/blockchain/execution_engine.go

>
Documentation
Corrects the name of a method in the comment describing what it does
Fixes #

corrected method name in comment

---

beacon-chain/p2p/fork_watcher.go
beacon-chain/p2p/gossip_topic_mappings.go

There's no need to change the gossip size in Capella.

don't change again unecessarily

---

testing/endtoend/params/params.go

Feature
Due to flaky test re-run behavior, logs from a failed test run are overwritten by subsequent retries. This makes it difficult to retrieve logs after the first failed run. It also takes some squinting through output to find the location of the log file in the first place. This PR adds the ability to place logs in an arbitrary path by setting an env var called `E2E_LOG_PATH`. The current time at test startup is integrated into the path to ensure that directories are unique across runs/retries. Note that bazel sandboxing generally will force this path to be in the /tmp tree.

env var to control log path with unique paths

---

beacon-chain/state/stategen/BUILD.bazel
beacon-chain/state/stategen/replay.go
beacon-chain/state/stategen/replay_test.go

Upgrade to capella in the replayer

Add upgrade to Capella to statereplay

---

beacon-chain/state/state-native/getters_withdrawal.go
beacon-chain/state/state-native/hasher.go
beacon-chain/state/state-native/setters_withdrawal.go
beacon-chain/state/state-native/setters_withdrawal_test.go
beacon-chain/state/types/types.go

Add Capella state changes from #11629 
These are fixes with respect to compute field roots and mark dirty fields

Add Capella state changes

---

beacon-chain/core/altair/BUILD.bazel
beacon-chain/core/altair/block.go
beacon-chain/core/altair/block_test.go
beacon-chain/core/altair/exports_test.go

This refactors sync committee rewards to remove the optimization of filtering voting keys.

Refactor Sync Committee Rewards

---

WORKSPACE

Other
As title describes. Keeping up to date with rules_go.

bazel: Update rules_go and remove extra repos in WORKSPACE

---

beacon-chain/forkchoice/doubly-linked-tree/metrics.go

fix help message of metric `doublylinkedtree_node_count`
Fixes #

fix help message of metric `doublylinkedtree_node_count`

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/log.go
beacon-chain/blockchain/options.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/process_block_test.go
beacon-chain/blockchain/service.go
beacon-chain/node/node.go

When processing blocks remove the included BLS changes from the pool

Handle BLS to execution changes included in blocks

---

WORKSPACE

Other
See: https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU/m/yZDrXjIiBQAJ
Fixes #

Update go to 1.19.4

---

testing/endtoend/components/lighthouse_beacon.go
testing/endtoend/components/validator.go
testing/endtoend/endtoend_setup_test.go
testing/endtoend/evaluators/validator.go
testing/endtoend/mainnet_scenario_e2e_test.go

Bug Fixes
target peer count and the expected participation rate for multiclient tests.
N.A

Fix Lint and Minor Bugs in E2E

---

beacon-chain/blockchain/chain_info_test.go

> Other
fix mismatch of code and comment
Fixes #

fix mismatch of code and comment

---

container/trie/sparse_merkle.go
container/trie/sparse_merkle_test.go

This is a bug fix PR that was created to replace #11776. The only difference between these PRs is that this has the changes based in the develop branch. For background on the issue, fix, and other info please reference #11776

SparseMerkleTrie depth fix & regression tests

---

validator/client/iface/validator.go
validator/client/key_reload.go
validator/client/runner.go
validator/client/runner_test.go
validator/client/testutil/mock_validator.go

Other
While investigating a user's complex setup of using web3signer +keymanager+mevboost at the same time, we realized the naming of the variable did not reflect the actual use, we are renaming this to avoid future confusion on this. We have also updated the fatal to a warning to prevent the failure of the validator client.

Improve validator set change event readability and error handling

---

beacon-chain/p2p/rpc_topic_mappings.go
beacon-chain/sync/context.go
beacon-chain/sync/rpc_chunked_response.go

Fix missing context in post-altair /v1 messages

---

beacon-chain/blockchain/head.go
beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go
beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go
beacon-chain/forkchoice/interfaces.go

Stealing an idea from LightHouse.

Log forkchoice weights on reorgs

---

validator/client/metrics.go
validator/client/validator.go

Metrics Addition
This PR adds a gauge vec, which allows us to determine if a particular validator is in a sync committee.
N.A

Check If Validator Is In Sync Committee

---

consensus-types/blocks/getters_test.go
consensus-types/blocks/setters.go
consensus-types/interfaces/beacon_block.go
consensus-types/mock/block.go

Method Removal
This PR is taken from our `capella` branch, where we remove this unused block setter from our repo. 
N.A

Remove Unused Block Setter

---

beacon-chain/sync/pending_blocks_queue.go

Fix fallback logic for beacon_blocks_and_sidecar_by_root for pending roots.
Previously, prysm broadcasts blocks without blobs sidecars even after deneb.
cc: @terencechain

sync: Re-broadcast block and blobs sidecar

---

proto/eth/service/beacon_chain_service.pb.gw.go
proto/eth/service/beacon_debug_service.pb.gw.go
proto/eth/service/validator_service.pb.gw.go
validator/web/handler.go

Bug fix
This PR removes unused / errorneous code / import that causes go build failure for commands like `go build -o /build/beacon-chain -buildvcs=false ./cmd/beacon-chain`
Hot fix, no tracking issues
Fixes #

Fix eip4844 branch errors

---

WORKSPACE
hack/README.md
hack/common.sh

Bug fix
running the ./hack/update-go/pbs.sh file fails to find the gfind command at times because the directory it searches may not have it. I've added an additional directory to search which is the default for homebrew installations.

update-go-pbs.sh: fixing script for mac users & updating bazel dependency 

---

validator/rpc/apimiddleware/endpoint_factory.go
validator/rpc/apimiddleware/structs.go

Fixes https://github.com/prysmaticlabs/prysm/issues/11943.

Validator client: Add missing `endpoint.DeleteRequest` - Fixes #11943

---

beacon-chain/rpc/eth/beacon/pool.go
beacon-chain/sync/broadcast_bls_changes.go
beacon-chain/sync/broadcast_bls_changes_test.go

Bug fix where we weren't modifying the slice in place. Credit to @nisdas, this is an alternative to #11954

modify slice in place

---

WORKSPACE

Security Update
Updates our base docker images to a much newer version. This also handles a lot of the related security issues with the older base images.
N.A

Update Base Docker Images

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/state_balance_cache_test.go

Missing the test file in the BUILD.bazel

add balance cache tests to testsuite

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/state/state-native/getters_withdrawal_test.go
beacon-chain/state/state-native/setters_withdrawal_test.go

Cleanup
- removes Altair-specific comment
- renames a few test functions

Small cleanup

---

beacon-chain/core/blocks/withdrawals.go

Documentation
This PR simply adds in clarifying comments for our withdrawal functions.
N.A

Add Clarifying Comments for Withdrawal Functions

---

beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks_test.go

Part of the implementation to reorg late blocks.

implement get_proposer_head

---

beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/topics.go

Add the broadcast blob method which is needed for the validator to broadcast blob to individual subnet

Add broadcast blob 

---

WORKSPACE
cmd/beacon-chain/BUILD.bazel
cmd/prysmctl/BUILD.bazel
cmd/validator/BUILD.bazel

Other
Among other things, this removes the requirement for python2 and improves conditional stamping (now respects `--stamp`).

Update rules docker to v0.25.0

---

testing/endtoend/endtoend_test.go
testing/endtoend/evaluators/execution_engine.go
testing/endtoend/minimal_scenario_e2e_test.go

E2E
This fixes scenario test failures by running the scenarios after capella.
N.A

Fix Scenario Test Failures

---

beacon-chain/blockchain/metrics.go
beacon-chain/blockchain/process_block.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Only increase the attempted reorgs metric when proposing a reorg.

increase attempted reorgs at the right spot

---

build/bazelrc/correctness.bazelrc

Other
This flag of the correctness section is not necessarily correct. Users of remote cache do want to upload their results.

Bazel: fix remote cache uploads

---

beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go

Use the feature flag when proposing

Gate GetProposerHead behind the feature flag

---

testing/endtoend/evaluators/fork.go

Bug Fix
In #12117 , it was revealed that our fork evaluator for altair is never run for any of our e2e tests. This PR fixes it by checking
it correctly.
N.A

Run Altair Fork Transition

---

config/features/deprecated_flags.go

Flag Cleanup
This adds the flag to the deprecated list as it was removed in #12146  .
N.A

Deprecate Reorg Flag Correctly

---

beacon-chain/operations/blstoexec/pool.go

Fix typos from bls pool metric PR

---

beacon-chain/blockchain/process_block.go

Call FCU at 4 seconds if we haven't updated head before for any reason
kudos to @terencechain for a great catch

Call FCU at 4 seconds if we haven't updated head

---

beacon-chain/state/interfaces.go
beacon-chain/state/state-native/getters_withdrawal_test.go
beacon-chain/state/state-native/readonly_validator.go
beacon-chain/state/state-native/readonly_validator_test.go

Remove unused Capella helpers 
fixes: #11619

Remove unused methods from interface

---

beacon-chain/p2p/gossip_topic_mappings.go
deps.bzl
go.mod
go.sum
proto/engine/v1/json_marshal_unmarshal.go

- `SignedBeaconBlockDeneb` was not part of gossip topic mapping
- Forgot `StateRoot` for `ExecutionPayloadDenebWithValue`'s unmarshaller 
- Updated geth to the latest coinbase fork

Fix EIP4844 inteorp bugs for devnet5

---

beacon-chain/node/BUILD.bazel
beacon-chain/node/config.go
beacon-chain/node/node.go
beacon-chain/state/fieldtrie/BUILD.bazel
beacon-chain/state/fieldtrie/field_trie_helpers.go
beacon-chain/state/state-native/hasher.go
beacon-chain/state/state-native/state_trie.go
beacon-chain/state/stateutil/eth1_root.go
beacon-chain/state/stateutil/field_root_attestation.go
beacon-chain/state/stateutil/field_root_eth1.go
beacon-chain/state/stateutil/historical_summaries_root.go

Bug Fix
In #12134 , there was a bad merge for our PR making our vectorized paths the permanent default:#12148 . 
This removed some deprecated code along with a criticl toggle which activated our vectorized paths in fast-ssz. 
This PR fixes it by adding these changes back.
N.A

Fix Bad Merge in V4

---

testing/endtoend/deps.bzl

Other
updating for new version released.

E2E: updating web3signer dependency

---

beacon-chain/rpc/eth/beacon/blinded_blocks_test.go
beacon-chain/rpc/eth/beacon/blocks_test.go

Tests
Some API tests had been written before final fork configuration was in place.

Unskip block tests

---

cmd/prysmctl/testnet/generate_genesis.go

Bug fix
This PR ensures we can override the Eth1Data on genesis states generated both with and without a JSON file.

Testnet: override Eth1Data for genesisState from input JSON

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go

Bug fix
Fall back to local client if builder is giving bad payload, fixes the nil error associated.
fixes regression from #12227

Builder: fix nil panic edgecase

---

api/client/builder/client.go

Bug Fix
Add user agent field to all http requests from our builder client.
N.A

Fix User Agent In Builder Client

---

beacon-chain/rpc/eth/validator/validator_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go

Correctly convert to Gwei to compare builder's block value 
Fixes #12289

Correctly use Gwei to compare builder bid value

---

monitoring/journald/LICENSE

Depedency Update
Adds in license for vendored dependency.
N.A

Add License For Vendored Dependency

---

beacon-chain/builder/BUILD.bazel
beacon-chain/builder/service.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go

Other
Add more tracing data collection for analyzing external block builder code paths.
Provides data to support #12297

builder: add more tracing data for builder code paths

---

validator/accounts/accounts_helper.go

Other
validator exit message says you are not able to withdraw in the validator command.

validator exit says you can't withdraw - cosmetic issue 

---

api/client/builder/client.go
api/client/builder/client_test.go

Other
small defensive check on the returned payload for the proper version

version check to blinded block

---

beacon-chain/db/kv/checkpoint.go
beacon-chain/db/kv/validated_checkpoint.go

Other
Code health: some duplicated code that could be refactored to share the code.

db: Deduplicate saveCheckpoint functionality

---

beacon-chain/state/fieldtrie/BUILD.bazel
beacon-chain/state/fieldtrie/field_trie_helpers.go
beacon-chain/state/state-native/state_trie.go
beacon-chain/state/state-native/types/types.go

Cleanup
Removes unused argument that was needed when we had two state implementations.

Remove unused argument from field index

---

beacon-chain/builder/testing/mock.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go

Bug fix
Reverting my change on payload version check since during hardforks there will be a mixmatch in versions between the head and the bid.

reverting version check on bid header

---

.buildkite-bazelrc
hack/latest_version_tag.sh
hack/workspace_status_ci.sh

Other
Adds support for uploading test results to buildbuddy.io.

CI: Add support for buildbuddy uploads

---

.github/workflows/go.yml
runtime/debug/debug.go
tools/bootnode/bootnode.go
tools/eth1exporter/main.go
tools/http-request-sink/main.go

>
> Bug fix
> Feature
> Other
Fixes #

Update Github Actions Go Version

---

beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_attestation_test.go

If the nsc hits we should save the copy

Save to checkpoint cache if the nsc hits

---

beacon-chain/blockchain/process_attestation_helpers.go
beacon-chain/blockchain/process_attestation_test.go

Add 1.) epoch 2.) root to `not a checkpoint in forkchoice` log

Add epoch and root to `not a checkpt in forkchoice` log

---

tools/eth1voting/main.go

Support Capella Blocks for Tool

---

beacon-chain/node/node.go
beacon-chain/operations/attestations/BUILD.bazel
beacon-chain/operations/attestations/prepare_forkchoice.go
beacon-chain/operations/attestations/service.go
config/features/config.go
config/features/flags.go
time/slots/BUILD.bazel
time/slots/slotticker.go
time/slots/slotticker_test.go
time/slots/slottime.go

adds tickers and feature flags again

revert revert of f6764fe62b9ca43d5777e3c476a9620c7207a940

---

beacon-chain/db/kv/migration_state_validators.go
beacon-chain/db/kv/migration_state_validators_test.go

Bug Fix
Fixes migration of state for both bellatrix and capella states, and also adds in the respective tests for them.
Fixes #12323 

Fix Migration Of State

---

beacon-chain/sync/metrics.go
beacon-chain/sync/validate_sync_committee_message.go

Bug fix
Fixes a typo in #12430

Fix metric name from PR #12430

---

beacon-chain/cache/BUILD.bazel
beacon-chain/cache/payload_id.go

Cleanup
- use constants more often
- improve comments

Cleanup of `ProposerPayloadIDsCache`

---

deps.bzl
third_party/com_github_libp2p_go_libp2p.patch

Adds in a patch for go-libp2p.
N.A

Add Patch For Libp2p

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Bug Fix
In the event the relay doesn't respond in time, we would get a failure in `unblindBuilderBlock` . This would lead us to performing a field access on a nil object leading to a panic. To prevent this, we remove the defer and add in the broadcast to the event feed at the end of the function.
N.A

Remove Defer In ProposeGenericBlock

---

beacon-chain/blockchain/log.go

log the right blocknumber

---

beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/sync/subscriber.go
consensus-types/blocks/getters.go

This PR fixes misc issues found testing local interop for devnet6

fix: devnet6 interop issues

---

CONTRIBUTING.md

fix typo (CONTRIBUTING.md)

---

beacon-chain/node/node.go

fix typo (beacon-chain/node/node.go)

---

beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/service_test.go

Remove unneeded check and consequently simplify the helper.

Remove unneded helper

---

.bazelrc
BUILD.bazel
WORKSPACE
deps.bzl

Other
Fixes warnings about zlib.
~Draft until confirmed works on Mac OS~

Update protobuf and protobuf deps

---

api/client/beacon/checkpoint_test.go
encoding/ssz/detect/configfork_test.go
nogo_config.json
testing/endtoend/component_handler_test.go
testing/endtoend/components/eth1/transactions.go
testing/endtoend/components/lighthouse_validator.go
testing/endtoend/endtoend_test.go

Other
Updates bazel nogo config to run the `ineffassign` static analyzer for all go files
Fixes #12543
Confirmed that `ineffassign` does run for tests, but the `only_files` filter was excluding a lot of files.

run `ineffassign` for all code

---

beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go

To make things more self-explanatory

Rename `payloadHash` to `lastValidHash` in `setOptimisticToInvalid`

---

beacon-chain/blockchain/process_block_helpers.go

Cleanup
This adds a debug log whenever we carry out our finalized deposit insertion.
N.A

Log Finalized Deposit Insertion

---

beacon-chain/rpc/eth/rewards/BUILD.bazel
beacon-chain/rpc/eth/rewards/handlers.go
beacon-chain/rpc/eth/rewards/handlers_test.go
beacon-chain/rpc/eth/rewards/server.go
beacon-chain/rpc/eth/rewards/structs.go
beacon-chain/rpc/service.go

Feature
Implements https://ethereum.github.io/beacon-APIs/?urls.primaryName=dev#/Rewards/getSyncCommitteeRewards
Closes #11952

`getSyncCommitteeRewards` API endpoint

---

validator/client/beacon-api/beacon_api_beacon_chain_client.go

Fix `GetValidatorPerformance` endpoint

---

tools/pcli/main.go

Command Improvement
We also log the total memory allocated in these steps to have a more accurate comparison for HTR times between different algorithms.
N.A

Add Allocation Data To Benchmark

---

beacon-chain/execution/engine_client.go

Bug fix
Fixes a regression due to a change in how blocks are unblinded that was introduced in the latest rebase onto develop. The changes in develop were built without consideration for deneb, so fixes we had made to other ee unblinding methods were bypassed.

support deneb in fullPayloadFromPayloadBody

---

beacon-chain/state/stateutil/BUILD.bazel
beacon-chain/state/stateutil/field_root_validator.go
beacon-chain/state/stateutil/field_root_validator_test.go
beacon-chain/state/stateutil/sync_committee.root.go
beacon-chain/state/stateutil/trie_helpers.go
crypto/hash/htr/BUILD.bazel
crypto/hash/htr/hashtree.go
crypto/hash/htr/hashtree_test.go
encoding/ssz/merkleize.go

different approach to #12637 
Develop
```
Deserialize Duration: 94.858451ms, Hashing Duration: 481.351894ms HTR: 0x5422c2fe46f4fa5719f91b353371428125f04ba684264c4bd2b25967258e66d9
Total Memory Allocation Differential: 597758176 bytes, Heap Memory Allocation Differential: 374948640 bytes
```
#12637 :
```
Deserialize Duration: 91.424014ms, Hashing Duration: 171.870096ms HTR: 0x5422c2fe46f4fa5719f91b353371428125f04ba684264c4bd2b25967258e66d9
Total Memory Allocation Differential: 1023739120 bytes, Heap Memory Allocation Differential: 441275120 bytes
```
This PR:
```
Deserialize Duration: 85.950581ms, Hashing Duration: 143.862648ms HTR: 0x5422c2fe46f4fa5719f91b353371428125f04ba684264c4bd2b25967258e66d9
Total Memory Allocation Differential: 882629456 bytes, Heap Memory Allocation Differential: …
```

Different parallel hashing

---

beacon-chain/rpc/service.go

Register `GetValidatorPerformance` as POST

---

beacon-chain/rpc/eth/beacon/handlers_test.go

Bug fix
broken test by bad rebase

deneb: fixing broken test

---

testing/spectest/mainnet/bellatrix/random/BUILD.bazel
testing/spectest/mainnet/bellatrix/random/random_test.go
testing/spectest/mainnet/capella/random/BUILD.bazel
testing/spectest/mainnet/capella/random/random_test.go
testing/spectest/minimal/altair/fork_transition/BUILD.bazel
testing/spectest/minimal/altair/fork_transition/transition_test.go
testing/spectest/minimal/bellatrix/fork_transition/BUILD.bazel
testing/spectest/minimal/bellatrix/fork_transition/transition_test.go
testing/spectest/minimal/bellatrix/random/BUILD.bazel
testing/spectest/minimal/bellatrix/random/random_test.go
testing/spectest/minimal/capella/fork_transition/BUILD.bazel
testing/spectest/minimal/capella/fork_transition/transition_test.go
testing/spectest/minimal/capella/random/BUILD.bazel
testing/spectest/minimal/capella/random/random_test.go

I'll do the payload ones in another PR

test: add missing random and fork transition spec tests

---

testing/spectest/mainnet/bellatrix/operations/BUILD.bazel
testing/spectest/mainnet/bellatrix/operations/execution_payload_test.go
testing/spectest/mainnet/capella/operations/BUILD.bazel
testing/spectest/mainnet/capella/operations/execution_payload_test.go
testing/spectest/minimal/bellatrix/operations/BUILD.bazel
testing/spectest/minimal/bellatrix/operations/execution_payload_test.go
testing/spectest/minimal/capella/operations/BUILD.bazel
testing/spectest/minimal/capella/operations/execution_payload_test.go
testing/spectest/shared/bellatrix/operations/BUILD.bazel
testing/spectest/shared/bellatrix/operations/execution_payload.go
testing/spectest/shared/capella/operations/BUILD.bazel
testing/spectest/shared/capella/operations/execution_payload.go

We never implemented execution payload tests. This PR adds them

test: add execution payload operation tests

---

cache/nonblocking/lru.go

Bug Fix
In the event we fetch a pubkey from our cache we spin off a new goroutine for each fetch. However this can cause problems 
if we are retrieving a large number of pubkeys in a short amount of time ( processing a block, processing many aggregates over gossip, etc). With the active validator set hitting 700000 keys, you would essentially be spinning up 700,000 goroutines here. While the go runtime can handle many routines being spun up, pushing it to 700,000 can potentially overwhelm it and push up CPU usage. 
This PR sends all these requests to a separate goroutine in the background, to prevent a goroutine from being spun up for each pubkey fetch.
N.A
**Other notes for …

Prevent Pubkey Cache From Overwhelming the Go Runtime

---

beacon-chain/rpc/service.go

Bug fix
Follow up to #12701 
--
--

fix: set CoreService in `beaconv1alpha1.Server`

---

WORKSPACE

Other
Minor security update from go. 
See the [go 1.20.7 announcement](https://groups.google.com/g/golang-announce/c/X0b6CsSAaYI).

Update go to 1.20.7

---

beacon-chain/blockchain/head.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/service_test.go

Set the head to the right optimistic status during init sync

set optimistic status in head at init sync

---

cmd/beacon-chain/BUILD.bazel
cmd/prysmctl/BUILD.bazel
cmd/validator/BUILD.bazel

Cleanup
This PR removes alpine images from our build pipelines. Given that these images haven't been working for a long time, it would be better to not build them at all and slowing down our docker pipelines.
N.A
Closes https://github.com/prysmaticlabs/prysm/issues/9320

Remove Alpine Images From Prysm

---

testing/endtoend/endtoend_setup_test.go
testing/endtoend/evaluators/fork.go
testing/endtoend/helpers/helpers.go

test: skip deneb e2e test with tracking

---

api/client/beacon/checkpoint.go

Fix
```
[2023-08-20 15:34:27]  INFO Downloaded checkpoint sync state and block. block_root=[228 59 35 153 200 104 30 171 213 11 126 94 151 6 208 158 154 55 141 76 227 252 134 139 12 208 228 86 140 179 243 178] block_slot=7144864 state_root=[29 81 72 76 62 249 98 192 58 5 29 99 93 242 253 60 214 217 173 34 183 208 109 164 142 133 94 5 253 13 100 127] state_slot=7144864
```
To
```
[2023-08-20 15:36:17]  INFO Downloaded checkpoint sync state and block. block_root=0xe43b2399c8681eabd50b7e5e9706d09e9a378d4ce3fc868b0cd0e4568cb3f3b2 block_slot=7144864 state_root=0x1d51484c3ef962c03a051d635df2fd3cd6d9ad22b7d06da48e855e05fd0d647f state_slot=7144864
```

Fix: download genesis log

---

beacon-chain/sync/initial-sync/round_robin.go

Bug fix
fixes devnet issue transitioning from init-sync to regular sync.

Save blob last stage init sync

---

beacon-chain/rpc/service.go

Bug fix
somehow the route was accidentally missed and rolled back in the previous pr of #12758

adding register validator route

---

config/params/testnet_sepolia_config.go

Bug Fix
#12783 introduced some deneb related changes which broke running prysm on sepolia. To fix this we initialize the deneb fork parameters for sepolia too.
N.A

Fix Sepolia Version

---

beacon-chain/execution/engine_client.go

Other
Addresses a piece of feedback from Nishant about consistently using a local variable to avoid future bugs.

Consistent bblock

---

config/features/flags.go

Other
Noticed that one of the interim cli flags had a typo.
Fixes #

Minor typo in CLI flag

---

consensus-types/payload-attribute/getters.go
consensus-types/payload-attribute/getters_test.go

Payload attribute for V2 should only be Capella

fix: pbv2 condition

---

beacon-chain/core/helpers/attestation.go
beacon-chain/core/helpers/attestation_test.go

address a feedback from #12773

chore: improve att error

---

beacon-chain/sync/validate_beacon_blocks.go
beacon-chain/sync/validate_beacon_blocks_test.go

Bug fix
Adds missing validation for the number of commitments in a block.
Fixes #12844

reject blocks with more commitments than spec

---

beacon-chain/blockchain/process_block_test.go
config/params/BUILD.bazel
config/params/config_test.go

Other
We were in a hurry to merge https://github.com/prysmaticlabs/prysm/pull/12822 so Potuz approved it without the test coverage he wanted. This is a follow-up to add that test coverage.

Tests for init-sync DA

---

beacon-chain/rpc/eth/validator/handlers.go

Bug fix
Sorting of proposer duties is based on slots, but after switching to HTTP these sorted slots are strings. This means that slot 10 comes before slot 2.
This is not an actual bug, but a UX degradation. It also results in failing muilticlient e2e because the order of duties is different between Prysm and LH.

Fix proposer duties sorting

---

api/client/builder/BUILD.bazel
api/client/builder/client.go
api/client/builder/client_test.go
beacon-chain/rpc/eth/shared/structs_blocks_conversions.go

Bug fix
deneb was not marshalling correctly before calling builder endpoint. 
Introducing type to marshal and adding unit test.

Deneb builder fix

---

beacon-chain/rpc/eth/beacon/handlers.go
beacon-chain/rpc/eth/beacon/handlers_test.go

Return correct root from `GetBlockHeader`

---

beacon-chain/sync/rpc_send_request_test.go

Bug Fix
Fixes an unhandled error in our test setup that had been reported.
TOB-PRYSM-1

Fix Unhandled Error

---

beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
beacon-chain/forkchoice/doubly-linked-tree/last_root.go
beacon-chain/forkchoice/doubly-linked-tree/last_root_test.go
beacon-chain/forkchoice/interfaces.go

Adds a forkchoice helper to return the last canonical root in a given epoch.

forkchoice return last canonical root of epoch

---

beacon-chain/blockchain/receive_block_test.go

Test Improvement
Following on from #12953 , we fix more racy tests that are being triggered in builds of unrelated PRs.
N.A

Fix More Racy Tests in Blockchain

---

beacon-chain/execution/rpc_connection.go
network/endpoint.go
testing/middleware/builder/builder.go

Cleanup
Uses the more idiomatic gethClient.WithHeaders method for setting http headers for the geth client.
Fixes #
cc: @terencechain

clean up code around setting geth client headers

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go
proto/prysm/v1alpha1/slasher.pb.go
proto/prysm/v1alpha1/slasher.pb.gw.go

Feature Progression
This makes our parallel block building feature the permanent default and removes the paths for disabling it. This feature has been running as the default for a while and making it a permanent default reduces the complexity of our block building paths.
N.A

Build Blocks in Parallel Permanently

---

WORKSPACE

Other
Minor security updates. No known issues.
> go1.20.8 (released 2023-09-06) includes two security fixes to the html/template package, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/tls, go/types, net/http, and path/filepath packages. See the Go 1.20.8 milestone on our issue tracker for details.
> go1.20.9 (released 2023-10-05) includes one security fixes to the cmd/go package, as well as bug fixes to the go command and the linker. See the Go 1.20.9 milestone on our issue tracker for details. 

update go 1.20.9

---

beacon-chain/sync/validate_voluntary_exit.go

Optimization
When validating exits, we use the read only head state instead of making a copy. 
N.A

Optimize Exits Gossip Validation

---

tools/image_deps.bzl

Other
These deps were updated and the old URLs are 404 now. Added a copy to prysmaticlabs.com to prevent
the same issue in the future.

Fix missing docker dependencies

---

beacon-chain/state/stategen/setter.go

The summary is saved on every slot

Remove confusing comment

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go

Also rename a badly named function

remove bad comment

---

beacon-chain/rpc/apimiddleware/BUILD.bazel
beacon-chain/rpc/apimiddleware/endpoint_factory_test.go

Other
Regression test for issue https://github.com/prysmaticlabs/prysm/issues/13071
Fails at v4.1.0 release. Currently passes.

rpc/apimiddleware: Test all paths can be created

---

WORKSPACE

Other
Updates go to the latest release.

Update go to 1.20.10

---

testing/endtoend/evaluators/operations.go

Bug Fix
This fixes withdrawals for mainnet e2e runs so that we take into account the withdrawability delay when running the evaluator.
N.A

Fix Withdrawals

---

beacon-chain/db/kv/flags.go
beacon-chain/node/config.go

What type of PR is this? 
Documentation ( Comment typo )  
What does this PR do?  Why is it needed?  
some comments typo.
Which issues(s) does this PR fix? 
No

Comment typo 

---

beacon-chain/blockchain/setup_test.go
beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/broadcaster_test.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/testing/fuzz_p2p.go
beacon-chain/p2p/testing/mock_broadcaster.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Updating the p2p pkg to broadcast `BlobSidecar`

Update broadcast method to use `BlobSidecar` instead of `SingedBlobSidecar`

---

BUILD.bazel
beacon-chain/cache/depositcache/deposits_cache.go
beacon-chain/rpc/eth/rewards/handlers_test.go
testing/endtoend/endtoend_test.go
validator/testing/mock_protector.go

Other
Fix violations of staticcheck
None reported
Review after #13298

Fix staticcheck violations

---

validator/client/validator.go
validator/client/validator_test.go

Bug fix
- The first commit adds some tests cases in `filterAndCacheActiveKeys` function
- The second commit stops filtering out exiting validators in `filterAndCacheActiveKeys`
**Initially:**
If a validator is in exiting (so, with `status==EXITING != ACTIVE`) state,
it is filtered out by the `filterAndCacheActiveKeys` function.
The validator is not registered to the beacon node.
If this exiting validator has to propose a block:
- the block will be proposed using local block building only.
- the fee recipient will be the one set in the beacon node.
(Additionally, if the beacon node is Prysm without any
fee recipient defined at the beacon node level, the fee recipient
will default on the `0x00000...` burn address.) …

`filterAndCacheActiveKeys`: Stop filtering out exiting validators

---

testing/endtoend/evaluators/beaconapi/util.go
testing/endtoend/evaluators/beaconapi/verify.go
time/slots/slottime.go

Other
- `postEvaluation` epoch calculation is much more complicated than it should be. Passing in the current epoch allows to simplify it.

Simplify post-evaluation in Beacon API evaluator

---

beacon-chain/node/BUILD.bazel
beacon-chain/node/node.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/mock_blob_verifier.go
beacon-chain/sync/options.go
beacon-chain/sync/rpc_status_test.go
beacon-chain/sync/service.go
beacon-chain/sync/subscriber_blob_sidecar.go
beacon-chain/sync/validate_blob.go
beacon-chain/sync/validate_blob_test.go
beacon-chain/sync/validate_bls_to_execution_change_test.go
beacon-chain/sync/validate_sync_committee_message_test.go
beacon-chain/sync/validate_sync_contribution_proof_test.go
beacon-chain/sync/validate_voluntary_exit_test.go

This PR introduces the implementation of blob validation gossip, leveraging a unified verification layer. The code is thoroughly tested using mocks, ensuring complete coverage

Use verified blob for gossip checks

---

config/params/init.go

Bug fix
Some testnets were missing from the defaults.
Fixes #13288
This is a bit fragile. I don't have a better solution at the moment though.

Add missing testnet configs to default configsets

---

beacon-chain/sync/rpc.go

Cleanup
In #13077 , we set the verbosity of goodbye logs to trace. This particular section for our rpc errors was missed. This PR makes it a trace log.
N.A

Clean Up Goodbye Stream Errors

---

beacon-chain/db/filesystem/blob.go
beacon-chain/node/node.go

Updated pruning process logging to include time taken and the last pruned epoch

Enhance Pruning Logs 

---

beacon-chain/sync/rpc_send_request.go

Adding fields `start_slot` and `count` to for more visibility

Add more color to sending blob by range req log

---

beacon-chain/sync/validate_blob.go

> Bug fix
This PR is a reordering of the [validations](https://github.com/ethereum/consensus-specs/blob/bf09b9a7c4a7b311e86823235815daf31b117574/specs/deneb/p2p-interface.md?plain=1#L175) that must be done before forwarding a `blob_sidecar` over gossip. The reordering in this PR is meant to prevent resource consumption attacks from malicious peers.
The root issue that this PR aims to fix stems from the ability of a malicious peer being able to trigger `pubsub.ValidationIgnore` conditions after passing the more expensive checks in `ValidProposerSignature()`. Namely the signature verification and validator index lookup. Triggering an `pubsub.ValidationIgnore` in one of the later …

Reordering of validateBlob gossip checks

---

beacon-chain/db/filesystem/blob.go

Bug fix
Logging
This PR adds the total number of blobs pruned during the current epoch to the pruning logs. In addition I realized that the previous placement of `countFiles()` was counting every single blob in every file and returning that value instead of only counting the blobs from the files that we were about to prune.
By moving `countFiles()` within `processFolder()` we can now count only the blobs we are deleting and return the correct number of pruned blobs.

Fix total pruned metric and add the value to logs

---

beacon-chain/rpc/eth/beacon/handlers.go
beacon-chain/rpc/eth/beacon/handlers_test.go

Other
- Implements https://github.com/ethereum/beacon-APIs/pull/331
- Returns better error messages
- Improves existing tests and adds missing ones

Update block publishing to 2.4.2 spec

---

validator/node/node.go

Bug fix
Before this pull request, the location of validator client database relies on multiple options:
- `--datadir`
- `--wallet-dir`
- `--validators-external-signer-url`
Look at #13391 for the whole matrix.
With this PR, the validator client database is always located in the value corresponding to `--datadir` (default or not).
In order to not break the compatibility, if `--datadir` is not specified, and if a database if found in the old directory, this warning message is displayed:
```
[2023-12-29 15:53:36]  WARN node: Database not found in `--datadir` (/Users/manu/Library/Eth2/validator.db) but found in `--wallet-dir` (/Users/manu/Library/Eth2Validators/prysm-wallet-v2/validator.db).
[2023-12-29 15:53:36]  WARN …
```

Validator client: Always use the `--datadir` value.

---

testing/endtoend/evaluators/BUILD.bazel
testing/endtoend/evaluators/builder.go
testing/middleware/builder/builder.go

Bug Fix
In the event our local transaction pool has 0 transactions, prysm will always choose the local payload. To account for this particular edge case we modify the builder evaluator.
N.A

Fix Up Builder Evaluator

---

cmd/beacon-chain/db/db.go
cmd/beacon-chain/flags/base.go
cmd/flags.go
cmd/validator/accounts/accounts.go
cmd/validator/db/db.go
cmd/validator/flags/flags.go
cmd/validator/flags/interop.go
cmd/validator/main.go
cmd/validator/slashing-protection/slashing-protection.go
cmd/validator/usage.go
cmd/validator/wallet/wallet.go
cmd/validator/web/web.go
config/features/flags.go
runtime/debug/debug.go

Other
This PR is best read commit by commit.
Example of wrapped lines:
**Before:**
**After:**
Fixes #13397
**Notes:**
The CLI manager offers the possibility to wrap lines, like [here](https://github.com/urfave/cli/pull/1119/files#diff-4d3f36d62cad94424544bb84fc93b33b73ffe3491a4ddca81a7f825539afc19cR1161-R1169).
However, this behaviour is sometimes very strange, so I preferred to wrap lines manually.

Refactor validator client help.

---

beacon-chain/blockchain/forkchoice_update_execution.go
beacon-chain/blockchain/process_block.go
beacon-chain/blockchain/receive_attestation.go
beacon-chain/forkchoice/doubly-linked-tree/BUILD.bazel
beacon-chain/forkchoice/doubly-linked-tree/reorg_late_blocks.go
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

It makes our reorging of late blocks the permanent default across prysm. This has been the default for nearly a year, therefore it is a good time to make it permanent for good.
N.A

Make Reorging Of Late Blocks The Permanent Default

---

deps.bzl
go.mod
go.sum

Security
This updates our crypto library version from the standard library to address a security advisory pertaining to the Terrapin Attack targeting the SSH protocol. For more details, the CVE is `CVE-2023-48795`
N.A

Update Our Golang Crypto Library

---

beacon-chain/blockchain/metrics.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/multi_value_slices.go
beacon-chain/state/state-native/state_trie.go
container/multi-value-slice/BUILD.bazel
container/multi-value-slice/multi_value_slice.go

Monitoring Improvement
This PR adds the ability to scrape more extensive metrics for individual multi value fields. The ability to do this allows us to track 
the current state of the multivalue slice and account for any changes in behaviour.
N.A

Add Detailed Multi Value Metrics

---

WORKSPACE

Other
Updates go to the latest release from today.
> go1.21.6 (released 2024-01-09) includes fixes to the compiler, the runtime, and the crypto/tls, maps, and runtime/pprof packages. See the Go 1.21.6 milestone on our issue tracker for details.

Update go to 1.21.6

---

tools/bootnode/bootnode.go

Bug fix
This was wrong and now it's not wrong.

Fix port logging in bootnode

---

beacon-chain/execution/log.go
cmd/defaults.go
cmd/password_reader.go
cmd/validator/BUILD.bazel
cmd/validator/log.go
cmd/validator/main.go
config/features/README.md
runtime/prereqs/prereq.go
runtime/service_registry.go
runtime/tos/tos.go
validator/client/BUILD.bazel
validator/client/beacon-api/genesis.go
validator/client/runner.go
validator/client/validator.go
validator/node/node.go

Please read commit by commit.
Other
This PR does not add any functional change, but only aims to increase the validator client readability.

Validator client - Improve readability - NO FUNCTIONAL CHANGE

---

beacon-chain/rpc/core/BUILD.bazel
beacon-chain/rpc/core/validator.go

Instrumentation Improvement
This PR adds in additional spans to our core validator rpc methods to allow us to monitor them better.
N.A

Add Spans to Core Validator Methods

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/metrics.go

- Change blob latency metrics from s to ms
- Change bucket to ms. as seen below, they are in low end ms

Change blob latency metrics to ms

---

testing/endtoend/deps.bzl
testing/endtoend/mainnet_e2e_test.go
testing/endtoend/mainnet_scenario_e2e_test.go

This updates our lighthouse version to one which is deneb compatible and enables the last remaining e2e tests for deneb.
N.A

Update To Deneb Compatible Lighthouse For E2E

---

config/params/testnet_sepolia_config.go

Please cross check: https://github.com/eth-clients/sepolia/pull/61

Update Sepolia Deneb fork epoch

---

beacon-chain/rpc/eth/validator/handlers_test.go
consensus-types/blocks/roblob.go
testing/util/wait_timeout.go

Corrected few typos I found, doesn't require testing or changelog entry.
Have a nice day.

chore: typo fix

---

testing/endtoend/components/lighthouse_beacon.go

Bug Fix
Lighthouse had removed a flag which broke our multiclient E2E startup routine.
N.A

Fix Broken Multiclient E2E

---

testing/endtoend/components/lighthouse_beacon.go

Bug fix
Follow up to #13493
Allows multiclient e2e to run.
Delete flag from lighthouse has been removed.

e2e fix multiclient

---

beacon-chain/rpc/eth/shared/errors.go

Other
fixing typos on error messages from API

fixing small typo in api error messages

---

beacon-chain/blockchain/process_block.go
beacon-chain/cache/proposer_indices.go
beacon-chain/cache/proposer_indices_test.go
beacon-chain/core/helpers/beacon_committee.go

fix off by one

---

cmd/beacon-chain/flags/base.go

Parameter Change
This increases our blob batch limit to a much more reasonable number to allow peers to fetch blobs in a quicker fashion.
N.A

Increase Blob Batch Limit

---

beacon-chain/execution/service.go
config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

This makes our new deposit trie ,which supports eip-4881, the default in prysm.
N.A

Makes Our New Deposit Trie The Default

---

config/features/config.go
config/features/deprecated_flags.go
config/features/flags.go

In the event we have a batch signature failure, we can now recheck all the signatures to correctly attribute the single signature that caused the failure.
N.A

Make Verbose Sig Verification the Default

---

DEPENDENCIES.md
deps.bzl
go.mod
go.sum

Update Gohashtree to v0.0.4-beta

---

beacon-chain/rpc/eth/rewards/service.go
beacon-chain/rpc/eth/validator/handlers_block.go
beacon-chain/rpc/eth/validator/handlers_block_test.go

Return consensus block value in Wei

---

testing/spectest/shared/deneb/fork/transition.go

We do this for Capella and Bellatrix. We should also check for Deneb

Check deneb fork transition test folder is empty

---

validator/client/beacon-api/submit_aggregate_selection_proof.go

Cleanup
Removes a log that I left behind after a debugging session.

Remove leftover log

---

beacon-chain/sync/backfill/verify_test.go
beacon-chain/sync/block_batcher.go
beacon-chain/sync/initial-sync/verification.go
beacon-chain/sync/verify/blob_test.go

Some clean ups on the sync package

---

config/features/config.go

Set the log level for `running on <network>` as `INFO`.
In case of custom ethereum network, keep the log as `WARN`.
Other

Set the log level for `running on <network>` as `INFO`.

---

beacon-chain/blockchain/process_block_test.go
beacon-chain/db/filesystem/ephemeral.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/initial-sync/service_test.go

Other
pr #13665 merged before I added this unit test.

tests for origin blob fetching

---

testing/spectest/shared/common/merkle_proof/single_merkle_proof.go

Other
Seems that test vectors are available. 

Spectest: Unskip Merkle Proof test

---

README.md
WORKSPACE

Update spec test to official 1.4.0 and readme tag

Update spec test to official 1.4.0

---

beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/subnets.go
beacon-chain/p2p/subnets_test.go

Other
Please read this PR commit by commit, with all commit messages.

Re-design `TestStartDiscV5_DiscoverPeersWithSubnets` test

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go

Add bid value metrics

---

validator/rpc/handler_wallet.go

Use this commit to improve the code comment and make it more clear and readable.
>
> Bug fix
> Feature
> Other
Fixes #

chore: enhance comment and more readable

---

config/params/loader_test.go

>
> Bug fix
> Feature
> Other
Fixes #

using slices.Contains

---

cmd/validator/usage_test.go

>
> Bug fix
> Feature
> Other
Fixes #

using slices.ContainsFunc

---

cmd/flags.go

>
> Bug fix
> Feature
> Other
Fixes #

using slices.IndexFunc

---

container/multi-value-slice/multi_value_slice.go

>
> Bug fix
> Feature
> Other
Fixes #

using slices.Index

---

beacon-chain/blockchain/head_sync_committee_info_test.go
beacon-chain/slasher/doc.go
beacon-chain/sync/initial-sync/blocks_fetcher.go

>
> Bug fix
> Feature
> Other
Fixes #

chore: fix some comments

---

config/params/config.go
config/params/mainnet_config.go

Add In Networking Params

---

beacon-chain/db/filesystem/blob.go
beacon-chain/db/filesystem/blob_test.go

Other
Follow-up to https://github.com/prysmaticlabs/prysm/pull/13869, covering the case of an overflow

Handle overflow in retention period calculation

---

config/fieldparams/mainnet.go
config/fieldparams/minimal.go
config/params/config.go
config/params/mainnet_config.go
runtime/version/fork.go

This adds forks and configuration constants for ePBS.

Epbs config

---

WORKSPACE
beacon-chain/rpc/eth/config/handlers_test.go
config/params/config.go
config/params/mainnet_config.go
config/params/minimal_config.go

Electra beacon config

---

WORKSPACE

Other
The workaround introduced in b24b60dbd88aab0e8348c1ae6fe7af50e63f9007 is not needed any more since [Zig 0.12.0](https://github.com/ziglang/zig/releases/tag/0.12.0) is out.

Revert "zig: Update zig to recent main branch commit (#13142)"

---

beacon-chain/p2p/discovery.go

[Link to the specification](https://github.com/ethereum/consensus-specs/blob/dev/specs/_features/eip7594/p2p-interface.md#the-discovery-domain-discv5)

Implement `custody_subnet_count` ENR field.

---

testing/spectest/minimal/altair/operations/sync_committee_test.go
testing/spectest/minimal/bellatrix/operations/sync_committee_test.go
testing/spectest/minimal/capella/operations/sync_committee_test.go
testing/spectest/minimal/deneb/operations/sync_committee_test.go

Bug fix
Fixing a spec test that has been broken since #9413
Part of #13767

Fix broken spec test

---

deps.bzl
go.mod
go.sum

Updates our Libp2p dependencies
N.A

Update Libp2p Dependencies

---

WORKSPACE

Other
New spectests alpha is released.

Update spectests to v1.5.0-alpha.2

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go

Proposal Improvement
Currently blobs are processed sequentially when proposing them, in order to be more efficient with the time a proposer has and to also allow a block to be processed in a more timely manner we handle each blob in its own goroutine. This prevents the propagation of 1 blob from being bottlenecked from processing another one. 
N.A

Parallelize Broadcasting And Processing Each Blob

---

beacon-chain/core/peerdas/helpers.go
deps.bzl
go.mod
go.sum

Other
Upgrade c-kzg-4844 to the latest version of the `das` branch. It has one renamed function.

[PeerDAS] Upgrade c-kzg-4844 package

---

beacon-chain/operations/attestations/kv/seen_bits.go

Other
This PR adds a wrapped error to assist with debugging in electra.

Electra: improve error log when checking attestation bits

---

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
runtime/interop/genesis.go
runtime/interop/premine-state.go
testing/endtoend/endtoend_setup_test.go
testing/endtoend/evaluators/validator.go
testing/endtoend/minimal_e2e_test.go
testing/endtoend/types/types.go

Disable Evaluators For E2E

---

beacon-chain/p2p/custody.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/peers/status.go

Fix Sampling Of Columns

---

beacon-chain/p2p/broadcaster.go

Cleanup
In the event we can't broadcast an attestation, we simply make it a debug log.
N.A

Change Attestation Log To Debug

---

api/server/middleware/middleware.go
api/server/middleware/middleware_test.go
validator/client/beacon-api/json_rest_handler.go
validator/client/beacon-api/json_rest_handler_test.go

Bug fix
the content type check is too strict and doesn't allow for returns with charset attributes
Fixes #[14093](https://github.com/prysmaticlabs/prysm/issues/14093)

content type check is too strict

---

beacon-chain/node/node.go
beacon-chain/node/options.go

Other
Cleaning up this unused field.

cleanup: Remove unused blobRetentionEpochs from beaconNode struct

---

beacon-chain/p2p/discovery.go
beacon-chain/p2p/subnets_test.go
beacon-chain/slasher/receive.go

Other
Corrects small spelling errors, making comments less ambiguous and easier to read.
n/a

Correcting spelling errors

---

config/proposer/loader/loader.go

Other
Improves the logs to better handle debugging
Fixes #

proposer settings log ux

---

beacon-chain/blockchain/BUILD.bazel
beacon-chain/blockchain/process_block.go
beacon-chain/core/peerdas/BUILD.bazel
beacon-chain/core/peerdas/helpers.go
beacon-chain/p2p/custody.go
beacon-chain/p2p/discovery.go
beacon-chain/p2p/subnets.go
beacon-chain/sync/data_columns_reconstruct.go
beacon-chain/sync/initial-sync/BUILD.bazel
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/service.go
beacon-chain/sync/rpc_beacon_blocks_by_root.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go

Other
Move custody subnet count into helper function
Fixes #

[PeerDAS] Move custody subnet count into helper function

---

beacon-chain/state/stateutil/BUILD.bazel
beacon-chain/state/stateutil/historical_summaries_root.go
beacon-chain/state/stateutil/pending_balance_deposits_root.go
beacon-chain/state/stateutil/pending_consolidations_root.go
beacon-chain/state/stateutil/pending_partial_withdrawals_root.go
encoding/ssz/BUILD.bazel
encoding/ssz/htrutils.go
encoding/ssz/slice_root.go

Other
Found more duplicated code that can make use of this generic method. Moved to the ssz package and
used it there.

ssz: Move stateutil.SliceRoot to ssz package

---

beacon-chain/sync/rate_limiter.go
beacon-chain/sync/rpc_data_column_sidecars_by_root.go
cmd/beacon-chain/flags/base.go
cmd/beacon-chain/flags/config.go
cmd/beacon-chain/main.go
cmd/beacon-chain/usage.go
testing/endtoend/components/beacon_node.go

Feature
Add data column batch size config
Fixes #

[PeerDAS] Add data column batch size config

---

BUILD.bazel

Other
Enables another static analysis check at build time. No violations were present in the codebase.

Enable golang.org/x/tools/go/analysis/errorsas static analysis check

---

beacon-chain/p2p/subnets.go

fix the typos in the code comments.
>
Fixes #

chore: fix comments

---

WORKSPACE
go.mod

>
> Bug fix
> Feature
> Other
Fixes Go CVE by updating the go version to 1.21.11
CVE's
https://www.cvedetails.com/cve/CVE-2024-24790/
https://avd.aquasec.com/nvd/cve-2023-45288
Fixes #

go version upgrade

---

beacon-chain/state/state-native/getters_withdrawal_test.go
beacon-chain/state/state-native/setters_churn_test.go
beacon-chain/state/state-native/state_trie_test.go

Other
Enables some state-native tests after merging #14112

Electra: Unskip state-native tests for spectest v1.5.0-alpha.3

---

beacon-chain/db/iface/interface.go
beacon-chain/db/slasherkv/BUILD.bazel
beacon-chain/db/slasherkv/migrate.go
beacon-chain/db/slasherkv/migrate_test.go
beacon-chain/db/slasherkv/pruning.go
beacon-chain/db/slasherkv/pruning_test.go
beacon-chain/db/slasherkv/slasher.go
beacon-chain/slasher/service.go

Bug fix
Commits message explain how, and more importantly, why, we implement some changes.
This pull request fixes the slasher disk usage leak.
- The first part of this pull request solves the issue by encoding slot/epoch as a big-endian instead of little-endian in buckets keys.
- The second part of this pull request implements a database migration to ensure the retro-compatibility fo the database.
- https://github.com/prysmaticlabs/prysm/issues/14142
- It may also fix https://github.com/prysmaticlabs/prysm/issues/13658 (but my intuition is there is an other bug to solve to fully fix this ticket)

Fix slasher disk usage leak.

---

beacon-chain/sync/rate_limiter.go
beacon-chain/sync/rpc.go
cmd/beacon-chain/flags/base.go
config/params/testnet_e2e_config.go
testing/endtoend/components/beacon_node.go
testing/endtoend/types/fork.go

Testing Fix
Since electra is disabled in E2E, we have to activate PeerDAS with deneb. This PR changes our config so that we can do that.
N.A

Trigger PeerDAS At Deneb For E2E

---

beacon-chain/rpc/eth/events/events.go

adding electra version to payload attribute event

---

testing/spectest/minimal/electra/epoch_processing/BUILD.bazel
testing/spectest/minimal/electra/epoch_processing/sync_committee_updates_test.go
testing/spectest/shared/electra/epoch_processing/BUILD.bazel
testing/spectest/shared/electra/epoch_processing/sync_committee_updates.go

Other
This was a missing spectest.

Electra: Add minimal spectests for sync_committee_updates

---

beacon-chain/execution/engine_client.go

Other
Fixes error message to be more accurate
Fixes #

Engine API: Fix typo in error message

---

beacon-chain/blockchain/process_block.go
beacon-chain/sync/BUILD.bazel
beacon-chain/sync/data_columns_reconstruct.go

Please read commit by commit.
```
["2024-07-18 10:49:32"]  DEBUG sync: "Received data column sidecar" columnIndex=119 sinceSlotStartTime=1.035610508s validationTime=139.566584ms
["2024-07-18 10:49:32"]  DEBUG sync: "Received data column sidecar" columnIndex=123 sinceSlotStartTime=1.036644467s validationTime=139.137167ms
["2024-07-18 10:49:32"]  DEBUG sync: "Received data column sidecar" columnIndex=124 sinceSlotStartTime=1.037701008s validationTime=138.669834ms
["2024-07-18 10:49:32"]  DEBUG sync: "Received data column sidecar" columnIndex=122 sinceSlotStartTime=1.038712425s validationTime=138.252ms
["2024-07-18 10:49:32"]  DEBUG sync: "Received data column sidecar" columnIndex=6 sinceSlotStartTime=673.050925ms validationTime=505.294375ms
["2024-07-18 10:49:32"]  DEBUG sync: "Received …
```

PeerDAS: Run reconstruction in parallel.

---

beacon-chain/core/electra/transition_no_verify_sig.go

I think this is done and the todo can be removed. Please correct me if I am wrong

Remove electra todo for process deposit requests

---

beacon-chain/state/state-native/getters_payload_header.go
beacon-chain/state/state-native/getters_state.go
beacon-chain/state/state-native/state_trie.go
proto/engine/v1/execution_engine.go
proto/engine/v1/execution_engine_fuzz_test.go
proto/prysm/v1alpha1/cloners.go
proto/prysm/v1alpha1/cloners_test.go

Other
more code cleanup around cloning and creating fuzzing tests for cloners on execution payloads and payload headers
Fixes #

creating execution payload copy and fuzz tests

---

beacon-chain/sync/validate_aggregate_proof.go
beacon-chain/sync/validate_aggregate_proof_test.go
beacon-chain/sync/validate_beacon_attestation.go
beacon-chain/sync/validate_beacon_attestation_electra.go

Aggregate and proof committee validation is not updated for Electra

Electra committe validation for aggregate and proof

---

beacon-chain/blockchain/process_block_test.go
testing/util/block.go
testing/util/electra_block.go

Other
adding more test generation fields
Fixes #14310

test util functions for electra field generation

---

testing/spectest/shared/electra/operations/execution_payload.go

Other
removing skip, should be tested
Fixes #

removing skip from test

---

config/params/mainnet_config.go

fix a deep source error

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/changelog.yml
CHANGELOG.md
CONTRIBUTING.md

Documentation
This PR 
- Initialize a CHANGELOG.md and backfill up to v2.0.0
- Add soft CI requirements for modifying the CHANGELOG.md.
- This CI check is non-blocking and can be ignored in situations when a changelog is not appropriate.
- Update PR templates to communicate the CHANGELOG should be updated in every PR (see acknowledgements in this PR description)
- Update CONTRIBUTING.md to outline the CHANGELOG requirements and clarify that trivial changes will not be accepted.
Building the release notes is a significant burden for Prysm team members working on the next release. Rather than spending time reviewing the change set in detail to build the changelog for a given …

Add CHANGELOG.md and update CONTRIBUTING.md

---

beacon-chain/rpc/prysm/v1alpha1/validator/aggregator.go

Clean up
Move duplicated code from `aggregator.go` to a separate function so that it can be reused
N/A

Re-use duplicate code in aggregator

---

CONTRIBUTING.md

Documentation
I think the 'no trivial PRs' rule is not clear enough

Update CONTRIBUTING.md to highlight no trivial changes

---

beacon-chain/core/peerdas/helpers.go
beacon-chain/p2p/subnets.go
beacon-chain/sync/subscriber.go

Fix Bugs in PeerDAS Testing

---

CHANGELOG.md
beacon-chain/core/epoch/epoch_processing.go
beacon-chain/core/epoch/precompute/slashing.go

For context https://offchainlabs.slack.com/archives/C0477FMTB3K/p1726070987969209

Avoid allocating in loops

---

CHANGELOG.md
WORKSPACE
config/params/BUILD.bazel
config/params/testnet_sepolia_config_test.go

Other
Adds a test to check that sepolia config matches the upstream yaml file.
N/A

Add sepolia config.yaml check with eth-clients/sepolia

---

beacon-chain/p2p/peers/scorers/BUILD.bazel
beacon-chain/p2p/peers/scorers/bad_responses.go
beacon-chain/p2p/peers/scorers/log.go
beacon-chain/p2p/peers/status.go
beacon-chain/p2p/peers/status_test.go
beacon-chain/p2p/utils.go
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/initial-sync/blocks_fetcher_test.go
beacon-chain/sync/initial-sync/blocks_fetcher_utils.go
beacon-chain/sync/rpc_beacon_blocks_by_range.go

**Please read commit by commit, with commit messages.**

PeerDAS: Fix initial sync

---

beacon-chain/sync/initial-sync/blocks_fetcher.go

PeerDAS: Improve initial sync logs

---

CHANGELOG.md
beacon-chain/rpc/BUILD.bazel
beacon-chain/rpc/endpoints.go
beacon-chain/rpc/endpoints_test.go
beacon-chain/rpc/eth/beacon/handlers.go

Bug fix
- register the deposit snapshot endpoint 
- make the endpoints test more robust
- small cleanup of the endpoint itself

Register deposit snapshot endpoint

---

CHANGELOG.md

Other
Updates CHANGELOG.md to reflect release [v5.1.1](https://github.com/prysmaticlabs/prysm/releases/tag/v5.1.1).

Update CHANGELOG.md for v5.1.1

---

CHANGELOG.md
beacon-chain/core/electra/consolidations.go
beacon-chain/core/electra/deposits.go
beacon-chain/core/electra/validator.go
beacon-chain/core/electra/withdrawals.go
beacon-chain/core/helpers/sync_committee.go
beacon-chain/core/helpers/validators.go
beacon-chain/core/helpers/validators_test.go
beacon-chain/state/interfaces.go
beacon-chain/state/state-native/BUILD.bazel
beacon-chain/state/state-native/getters_validator.go
beacon-chain/state/state-native/getters_validator_test.go
beacon-chain/state/state-native/getters_withdrawal.go
beacon-chain/sync/validate_aggregate_proof.go
beacon-chain/sync/validate_beacon_blocks.go

Use read only validator for processing

---

CHANGELOG.md

Documentation
As title describes

Update CHANGELOG.md to reflect v5.1.2 hotfix release

---

runtime/interop/premine-state.go

Add support to generate the genesis state for ePBS.
Tested with the following command:
```
bazel run //cmd/prysmctl testnet generate-genesis -- \
--num-validators=256 \
--output-ssz=genesis.ssz \
--chain-config-file=config.yml \
--genesis-time=$(($(date +%s) + 30)) \
--fork=epbs \
--geth-genesis-json-in=genesis.json \
--geth-genesis-json-out=genesis.json
```
`config.yml` contains both `EPBS_FORK_VERSION` and `EPBS_FORK_EPOCH`

Add support to generate genesis state for epbs

---

proto/engine/v1/electra.go
proto/engine/v1/electra_test.go

Bug fix
bug fix for engine API on execution requests, duplicate request types should error
Fixes # https://github.com/ethereum/consensus-specs/pull/3998

Engine API: execution requests should be unique

---

CHANGELOG.md
beacon-chain/core/transition/transition_test.go

Other
This adds some benchmarks to review the performance of process slots with a few recent forks.
I found this helpful for testing, so I figured we could preserve it.

Benchmark process slots

---

beacon-chain/rpc/prysm/v1alpha1/beacon/attestations.go
proto/prysm/v1alpha1/beacon_chain.proto

The previous link has expired and has been replaced with the latest address.
Fixes #

chore: fix 404 status URL

---

CHANGELOG.md
deps.bzl
go.mod
go.sum

This updates our `quic-go` dependency to the latest version.
N.A

Update Quic-go to the latest version

---

CHANGELOG.md

Other
Updates the CHANGELOG to reflect v5.2.0 release.

Update changelog for v5.2.0 release

---

beacon-chain/rpc/eth/light-client/handlers.go
beacon-chain/rpc/eth/light-client/handlers_test.go

Other
This PR cleans up the extra code in the `GetLightClientUpdatesByRange()` handler.
part of #12991

clean up the updates by range handler

---

beacon-chain/db/kv/lightclient_test.go

Other
This PR adds some basic tests to the DB functions `kv.SaveLightClientBootstrap()` and `kv.LightClientBootstrap()`. 
These are needed to verify the correctness of future changes these functions. 
Part of #12991

Add tests for save and read LC Bootstrap DB functions

---

consensus-types/light-client/bootstrap.go
consensus-types/light-client/finality_update.go
consensus-types/light-client/optimistic_update.go
consensus-types/light-client/update.go

Other
- More comments
- Remove redundant parenthesis
- Rename variables that clash with imported package names

Light Client: minor improvements

---

CHANGELOG.md
beacon-chain/cache/attestation.go
beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/subnets.go
beacon-chain/rpc/eth/beacon/handlers_pool_test.go
beacon-chain/rpc/eth/events/events.go
beacon-chain/slasher/doc.go
cmd/validator/slashing-protection/import.go
proto/prysm/v1alpha1/attestation/attestation_utils.go
testing/bls/hash_to_G2_test.go
testing/endtoend/evaluators/metrics.go
testing/util/block.go
validator/client/validator_test.go
validator/db/testing/setup_db.go

Other
Running multiple tools to try and find all typos. 

Fix all typos

---

CHANGELOG.md
beacon-chain/core/electra/transition.go

Documentation
This PR references spec at version v1.5.0-alpha.10

Electra: Update spec definition for process_epoch

---

CHANGELOG.md
deps.bzl
go.mod
go.sum

Updates our `go-libp2p-pubsub` dependency to utilize some recent fixes and improvements to it.
N.A

Update Go-Libp2p-Pubsub 

---

api/client/builder/client_test.go
beacon-chain/core/electra/deposits.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer_builder_test.go
beacon-chain/state/state-native/setters_eth1_test.go
beacon-chain/sync/initial-sync/blocks_fetcher.go
beacon-chain/sync/rpc_beacon_blocks_by_root_test.go
testing/util/lightclient.go
validator/rpc/handlers_health_test.go

Cleanup
Remove duplicate imports from Go files.

Remove duplicate imports

---

CHANGELOG.md
beacon-chain/p2p/pubsub_tracer.go

Metrics Improvement
Trace `IDONTWANT` control messages.
Fixes #

Add Ability to Trace IDONTWANT Control Messages

---

beacon-chain/p2p/discovery_test.go
changelog/pvl_dns_test_fix.md

Bug fix
Follow up from #14795. The previous example is already broken and blocking all PRs.

Use ip.addr.tools for DNS resolution test in p2p

---

changelog/james-prysm_e2e-scenario-fork-fix.md
testing/endtoend/endtoend_setup_test.go
testing/endtoend/mainnet_scenario_e2e_test.go
testing/endtoend/minimal_scenario_e2e_test.go

Bug fix
e2e was changed due to the geth upgrade, but scenario test evaluators were missed in this change.
Fixes #

fix e2e scenario evaluators

---

beacon-chain/rpc/eth/rewards/BUILD.bazel
beacon-chain/rpc/eth/rewards/handlers_test.go
changelog/radek_rewards-electra.md

Add Electra test case to rewards API

---

changelog/radek_proto_test-electra.md
consensus-types/blocks/BUILD.bazel
consensus-types/blocks/proto_test.go

Update `proto_test.go` to Electra

---

beacon-chain/blockchain/receive_block.go
beacon-chain/blockchain/setup_test.go
beacon-chain/p2p/broadcaster.go
beacon-chain/p2p/gossip_topic_mappings.go
beacon-chain/p2p/interfaces.go
beacon-chain/p2p/pubsub.go
beacon-chain/p2p/testing/fuzz_p2p.go
beacon-chain/p2p/testing/mock_broadcaster.go
beacon-chain/p2p/testing/p2p.go
beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
config/features/flags.go
deps.bzl
go.mod
go.sum
testing/endtoend/components/beacon_node.go
testing/mock/beacon_validator_client_mock.go
testing/mock/beacon_validator_server_mock.go
testing/validator-mock/validator_client_mock.go

Implement RLNC Broadcasting

---

changelog/james-prysm_proposer-settings-readability.md
config/proposer/loader/loader.go

Other
the proposer settings logic was a bit difficult to read and this PR aims to improve the readability and make it easier to update values in the future.
changes pass existing comprehensive suite of unit tests
Fixes #

improving proposer settings loader readability

---

beacon-chain/state/state-native/setters_consolidation.go
beacon-chain/state/state-native/setters_deposits.go
beacon-chain/state/state-native/setters_eth1.go
beacon-chain/state/state-native/setters_participation.go
changelog/nisdas_remove_useless_assignment.md

Bug Fix
For certain fields in the state, we indicate to the state that certain fields need their field trie to be rebuilt even if these fields do not have any underlying field tries.
N.A

Remove Unused assignment

---

changelog/james-prysm_dynamic-max-blobs.md
config/params/config.go

Other
we should use a dynamic value instead of the static one for calculating which max and target blob we use
Fixes #

Dynamic max blobs config

---

changelog/syjn99_cli-peer-address-format.md
cmd/flags.go

Add p2p address format for CLI users
