prysmaticlabs/prysm

validator/accounts/wallet/wallet.go
When validating account list, there was a missing space. This fixes that nitpick.
=> Fix missing space in error message in account list

beacon-chain/BUILD.bazel, beacon-chain/main.go, validator/BUILD.bazel, validator/main.go
Received late feedbacks from 2 that preferred the old format. The color and prefix placements were the main concerns. Given these late feedbacks, we were not at unanimous decision as we once thought. Reverting for the time being and exploring better alternates that will satisfy the both worlds
=> Revert "Logging with `PadLevelText` to true"

beacon-chain/sync/initial-sync/round_robin.go
> Other
- @shayzluf raised concerns about not including the last slot when reviewing #7999, so I've decided to double-check it.
- Since it is conventional in Golang is to use half-opened intervals for slices/ranges i.e. `[start, end)` (end not included), it is better to set highest expected slot for `syncToFinalizedEpoch` to be the start slot of the first non-finalized epoch (so, no need to step-back which was introduced in #7999, and **this PR reverts that change**)
N/A
- Moreover, it seems that this step-back produces occasional issue with the current init-sync tests. It is not the problem of the code itself, rather than fragile tests, though. As I am …
=> Round robin: half open interval in syncToFinalizedEpoch

beacon-chain/sync/initial-sync/service_test.go
> Bug fix
- Race condition was found in `TestService_waitForStateInitialization`, so it was marked as skiped in #8038 
- This PR resolves the issue, and unskips the test.
N/A
=> Unskip fixed init-sync service test

WORKSPACE
> Other
- `rules_go v0.24.9` https://github.com/bazelbuild/rules_go/releases/tag/v0.24.9 (which has an important fix for `TestMain()` https://github.com/bazelbuild/rules_go/pull/2716 I'll file a separate PR updating our `TestMain()s`).
- `golang v1.15.6`
N/A
I've confirmed that the issue we had with `TestMain()` due to bug in `rules_go` is fixed indeed:
=> Update rules_go to v0.24.9 and golang to v1.15.6

WORKSPACE, beacon-chain/blockchain/blockchain_test.go, beacon-chain/cache/cache_test.go, beacon-chain/core/epoch/spectest/spectest_test.go, beacon-chain/p2p/peers/peers_test.go, beacon-chain/p2p/peers/scorers/scorers_test.go, beacon-chain/powchain/powchain_test.go, beacon-chain/rpc/beacon/beacon_test.go, beacon-chain/rpc/validator/validator_test.go, beacon-chain/state/stateutil/stateutil_test.go, beacon-chain/sync/initial-sync/initial_sync_test.go, beacon-chain/sync/sync_test.go, shared/aggregation/attestations/attestations_test.go, shared/slotutil/slotutil_test.go, slasher/beaconclient/service_test.go, slasher/db/kv/kv_test.go, slasher/detection/attestations/attestations_test.go, slasher/detection/proposals/proposals_test.go, slasher/node/node_test.go, slasher/rpc/rpc_test.go, tools/bootnode/bootnode_test.go
> Other
- Due to issue in `rules_go` we had to wrap `TestMain` contents into local functions (see #7814)
- The issue has been resolved in `rules_go` (#8045), so we can get rid of those wrapper fn's.
N/A
=> Update TestMain(): do not call os.Exit() explicitly

shared/aggregation/attestations/attestations_bench_test.go
- Removes redundant/unused code from the attestation aggregation benchmarks.
Part of #7871
- Extracted from #7938
=> Attestation aggregation: removes redundant code from max-cover benchmarks

shared/aggregation/attestations/BUILD.bazel, shared/aggregation/attestations/attestations_test.go
> Other
- Naive aggregation heavily depends on the order of incoming partial attestations, this PR includes unit test confirming max-cover's better score regardless of the order items come in.
- Part of #7871
N/A
- Extracted from #7938
- cc @terencechain
=> Attestation aggregation: maxcover vs naive aggregation effectiveness test

validator/client/BUILD.bazel, validator/client/service.go, validator/client/service_test.go
Bug fix
Before this commit, it was not possible to pass in base64-encoded
content as a header value if it contained an equals sign. This commit
changes the behavior slightly. Rather than ignore key/value pairs where
the value happens to have an equals sign, we assume the first equals
sign delimits the key from the value and pass in the rest of the value
as-is.
Also, instead of printing the header name along with its value, we only
print the name, so there is less risk of leaking information into logs
that shouldn't be there.
N/A
This has not been tested in the context of the full validator client.
Instead, a small example was made to demonstrate the …
=> fix(grpcHeaders): accept values with "=" symbols

validator/client/propose_protect.go, validator/client/propose_protect_test.go, validator/client/propose_test.go
Part of #7813, this PR adds the following invariant to runtime:
`Refuse to sign any block with slot <= min(b.slot for b in data.signed_blocks if b.pubkey == proposer_pubkey)`
=> Add EIP-3076 Invariants for Proposer Slashing Protection

validator/db/iface/interface.go, validator/db/kv/BUILD.bazel, validator/db/kv/db.go, validator/db/kv/schema.go, validator/db/kv/slashable_keys.go, validator/db/kv/slashable_keys_test.go, validator/slashing-protection/local/standard-protection-format/import.go
This is part of #7813. This PR adds DB methods to save and retrieve slashable keys to and from disk. This is used during slashing protection JSON imports, in case we find any keys that are slashable from the incoming JSON. In the next PR, we can call these DB methods at runtime to prevent those blacklisted keys from performing duties in the validator client.
The scope of this PR is only the DB methods with tests.
=> Save Slashable Keys to Disk in the Validator Client

validator/client/BUILD.bazel, validator/client/log.go, validator/client/log_test.go, validator/client/mock_validator.go, validator/client/runner.go
> Feature
This PR adds a log to validator client on per slot basis to for how much time is left until next duty. If there's no duty until end of the epoch, it logs appropriately.  
Fixes #8056 
I tested with my 5 validators in Pyrmont and tested with 4000 validators in interop mode. Profiled validator client to ensure there's no bottleneck
=> Validator client logs time left to next duty

validator/slashing-protection/local/standard-protection-format/BUILD.bazel, validator/slashing-protection/local/standard-protection-format/import.go, validator/slashing-protection/local/standard-protection-format/import_test.go
> Bug fix
The EIP standard for EIP-3076 slashing interchange requires us to properly handle entries in the JSON with duplicate public keys, such as:
```
"0x2932232930: {
SignedBlocks: [Slot: 5, Slot: 6, Slot: 7],
},
"0x2932232930: {
SignedBlocks: [Slot: 5, Slot: 10, Slot: 11],
},
```
Even if the data in them is the same, we should still process all those entries and not deduplicate. The current approach deduplicates, potentially missing slashable data.
Part of #7813
=> Properly Handle Duplicate Public Key Entries in Slashing Interchange Imports

validator/client/attest_protect.go, validator/client/attest_protect_test.go
Feature Cleanup
in #8100 once it has been well tested and merged in.
N.A 
=> Remove Saving Of Target And Source Epoch

validator/db/kv/historical_attestations.go, validator/db/kv/historical_attestations_test.go, validator/slashing-protection/local/standard-protection-format/round_trip_test.go
> Bug fix
It turns out that when we mark an epoch as attested in our attestation history, we were also marking all epochs in between that epoch the last written one with zero values. Instead, we should mark those epochs as FAR_FUTURE_EPOCH.
Part of #7813
=> Set Empty Epochs in Between Attestations as FAR_FUTURE_EPOCH in Attesting History

shared/fileutil/fileutil.go, shared/fileutil/fileutil_test.go
> Other
- Extracted from #8095 (and required by that PR), this PR adds the following extra methods (and their tests) to `shared/fileutil`:
- `CopyDir(src, dst)` to copy directory files, recursively i.e. files w/i a given directory, and all its sub-directoriesl
- `DirsEqual(dir1, dir2)` calculates directories checksums and returns whether  `dir1` and `dir2` have same contents.
- `HashDir(dir)` calculates directory checksum/hash.
- `DirFiles(dir)` returns list of files in directory, recursively.
Part of #5660
=> Add extra methods to shared/fileutil

validator/db/kv/attestation_history_v2.go, validator/db/kv/db.go, validator/db/kv/proposal_history_v2.go, validator/db/kv/schema.go
Other (code health)
These buckets are not used and have not been used since before v1.0.0
N/A - clean up
Minor renaming to remove the "new" prefix from the appropriate buckets.
=> Validator DB cleanup: remove obsolete buckets

WORKSPACE
Other
The previous base images were from 2019. This PR updates our base docker images to a more recent image circa 2020-10-30.
N/A
=> Update rules docker to include bazelbuild/rules_docker#1666, which updates the base images

validator/db/kv/attestation_history_v2.go, validator/db/kv/db.go
No tracking issue, this PR simply locks around map access in retrieving attesting history to prevent significant lock contention when running a large amount of validators
=> Lock Only When Needed When Fetching Attesting History

beacon-chain/db/restore.go, shared/tos/tos.go, slasher/db/restore.go, validator/accounts/accounts_delete.go, validator/accounts/accounts_enable_disable.go, validator/accounts/accounts_exit.go, validator/accounts/wallet_create.go, validator/accounts/wallet_recover.go, validator/db/restore.go
- When comparing/matching unicode strings in a case-insensitive manner `strings.EqualFold()` should be used (it is more performant than manual turning string `ToLower()`, plus, it is intended for comparisons).
- This PR amends string comparisons to use `EqualFold()`.
N/A
=> Compare strings using strings.EqualFold()

beacon-chain/core/epoch/epoch_processing_test.go, beacon-chain/core/epoch/precompute/slashing_test.go
> Clean up
Fixes a go test complain:
`conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)`
Fixes #
=> Update int -> string conversion to make go test happy

beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/initial-sync/service_test.go
Feature
Allows to check whether the initial sync service has been initialized. This is required for node APIs, specifically returning 503 from https://ethereum.github.io/eth2.0-APIs/#/Node/getHealth
Needed for #7510 
I also aligned the implementation of `Status` with `Syncing` after a discussion with @farazdagi
=> Check if initial sync service has been initialized

validator/client/attest.go, validator/client/attest_protect.go, validator/client/attest_protect_test.go, validator/client/attest_test.go
Bug fix
When we introduced #8086 we removed the redundant call for attestation slashing protection and combined the external slashing checks. This change introduced a problem as external slashing protection using slasher `IsSlashableAttestation` grpc endpoint require signed attestation as an input(slashing can not be proved without signed attestation)
slasher endpoint `IsSlashableAttestationNoUpdate` could not be used as it doesn't update the spans in db and will break the correctness of future slashing detections if used.
This pr :
- move the attastation protection check down the flow after signing 
- remove redundent check as validation is also being done when calling `IsSlashableAttestation` endpoint
**Which …
=> Move attestation protection call after signing

shared/aggregation/attestations/maxcover.go, shared/aggregation/maxcover.go, shared/aggregation/maxcover_test.go
> Other / Optimization
- Extracted from #7938
- This PR removes redundant deduplication routine from max cover function:
- Duplicate items do not have any effect on the resultant cover, and are effectively excluded by greedy selection routine (we are selecting based on **uncovered** bits, and any duplicate coming second to that selection procedure, will hence have a zero score and excluded).
- Deduplication is certainly not a part of algorithm anyway, so if one wants to dedup - it must be done outside the max-cover functionality (and we, indeed, are checking for attestation duplicates when adding unaggregated attestations to attestation pool).
Part of #7871
**Other notes for …
=> Max-cover: remove redundant dedup routine

validator/db/kv/BUILD.bazel, validator/db/kv/db.go, validator/db/kv/migration.go, validator/db/kv/migration_optimal_attester_protection.go, validator/db/kv/migration_optimal_attester_protection_test.go
Follow-up to #8212, which was taking almost 10Gb for 1000 validators, we need a way to optimize how we perform a db migration to the optimal format for attester protection. Thanks to @nisdas for this logic, he was able to reduce it to 140Mb for around 2000 validators by splitting the migration into multiple boltdb transactions.
=> Optimize Migration for new Attester Protection DB

validator/client/attest_protect.go, validator/db/iface/interface.go, validator/db/kv/BUILD.bazel, validator/db/kv/attester_protection.go, validator/db/kv/attester_protection_test.go, validator/db/kv/db.go, validator/db/kv/db_test.go, validator/db/kv/historical_attestations.go, validator/db/kv/log.go, validator/db/kv/migration_optimal_attester_protection_test.go, validator/slashing-protection/local/standard-protection-format/import.go
> Feature
Part of #8242, the new attester protection methods have a serious flaw when running many validating keys, as all of them will attempt to acquire the boltDB write lock and lead to significant contention. Instead of every single attestation being its own boltDB transaction, we do the following:
When a validator attempts to save an attestation record to the DB:
1. We send the attestation over a channel and also subscribe to a feed that will notify us when the saving is complete. Block until we are notified.
2. We run a routine in the background which batches these channel receives into a slice
3. If a certain amount of time passes or if the max capacity of the slice is reached, **whichever comes first**, we …
=> Batch Attestation Records and Flush All at Once in Validator DB

shared/testutil/attestation.go, shared/testutil/attestation_test.go
> Bug fix
Fixes a bug in `GenerateAttestations` in pkg `testutil`.  `GenerateAttestations` works by decreasing input slot (n) by 1 (n-1), this ensures computed attestation has the on time property for the current slot. The `currentEpoch` which is used to calculate target root should respect the (n-1) property, or else at the epoch boundary slot we will be getting epoch out of bound. (ex: input slot 32, attestation slot 31, the epoch suppose to be 0 but it's 1)
No issue. Discovered while writing blockchain unit tests.
Only touches test code
=> Testutil: Can generate attestation at epoch boundary

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/blocks_test.go
> Bug fix
It is a follow up on the finding here: https://github.com/prysmaticlabs/prysm/pull/8184#issuecomment-752040000
`db.Blocks` filtering will return `[][]byte{}` if `endSlot=0`, which seems to be intended before for the case that no slot related parameters are set. But it is legitimate to query `startSlot=0 and endSlot=0` for the genesis block, this PR fixes this behaviour. Also, instead of checking `endSlot=0`, it checks if any slot related parameters are set at the beginning, if not, return empty slice.
We have `db.getBlocksBySlot` now for getting blocks for particular slot so there is not much chance to query with filter `startSlot=0 and …
=> Blocks filtering should return genesis when startSlot=0 and endSlot=0

beacon-chain/core/blocks/attestation.go, beacon-chain/core/blocks/attestation_test.go, beacon-chain/core/helpers/attestation.go, beacon-chain/core/helpers/attestation_test.go, beacon-chain/operations/attestations/kv/aggregated.go, beacon-chain/operations/attestations/kv/aggregated_test.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_beacon_attestation.go
> Feature
This PR adds a `ValidateNilAttestation` helper method to return error if any of the attestation's composite field is nil. It then applies the helper method across Prysm attestation's validation pipelines. This is great for standardization. Mean while it made improvements on operation pool to actually return `err` for faulty attestation instead of returning `nil` or `false`
=> Add a helper to validate nil attestation

beacon-chain/rpc/beacon/validators.go, beacon-chain/rpc/beacon/validators_test.go
> Enhancement
Immediately return `true` from `isSlotCanonical` when `slot=0`, so it doesn't need to reach the DB and found that the block root matches genesis block root. It is a followup PR of the discussion here: https://github.com/prysmaticlabs/prysm/pull/8184#issuecomment-752143115
=> isCanonical for slot 0 should return true

validator/db/BUILD.bazel, validator/db/migrate.go, validator/db/migrate_test.go, validator/db/testing/BUILD.bazel, validator/db/testing/setup_db.go
There was a dumb mistake I made in the validator database rollback, essentially saying a folder does not exist when it should due to a flipped boolean. Fixed and added a regression test
=> Allow Validator Database Rollbacks

.buildkite-bazelrc
Other
Since the builders / workers are ephemeral, a stable remote cache should significantly reduce build times in CI.
I have been running this setup locally for about a week and noticed a great improvement when switching branches and cross compiling.  
N/A
Follow up to #8111.
=> Use remote cache in CI

.buildkite-bazelrc
Reverts prysmaticlabs/prysm#8280
Remote caching is still not a clear win in buildkite. Some builds are taking 45 minutes with remote caching where they would previously take 15 minutes.
=> Revert "Use remote cache in CI"

.bazelrc
Other
Previously, only `--config=release` flag would stamp binary build information. This makes it default behavior.
N/A
Confirmed that bazel doesn't relink when nothing has changed, except for any `STABLE_` prefixed environment variable. Currently, only the git commit. 
Also updated "experimental_sandbox_default_allow_network" to the new, non-experimental flag.
cc: @potuz
=> Stamp binaries by default

deps.bzl, go.mod, go.sum
> Other
- Updates dependency to [https://github.com/prysmaticlabs/go-bitfield/commit/a490c91c5a59d5b4f523ba559ac4d89d8c4feca5](https://github.com/prysmaticlabs/go-bitfield/commit/a490c91c5a59d5b4f523ba559ac4d89d8c4feca5) (where support for `Bitlist64` has been added)
N/A
=> Update bitfield dependency

shared/aggregation/attestations/attestations_bench_test.go
> Other / Tests
- Introduces a baseline benchmark test which compares `naive vs max-cover`
- Filing this a separate PR, as I need this test to exist both in our `develop` branch and in my feature branch (so that I can compare and contrast the stats).
Extracted from #7938, part of #7871
=> Attestation aggregation: baseline benchmark

beacon-chain/rpc/nodev1/node.go, beacon-chain/rpc/nodev1/node_test.go
Feature
This PR implements Node API's `PeerCount` method according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Node/getPeerCount
Part of #7510
N/A
=> Peer count node api

beacon-chain/blockchain/process_attestation.go, beacon-chain/blockchain/process_attestation_test.go, beacon-chain/blockchain/receive_attestation.go
> Clean up
`on_attestation` returns `([]uint64, error)`. The attesting indices `[]uint64` was never used. This PR removes it
Fixes # N/A
N/A
=> Refactor `on_attestation` return signature

beacon-chain/rpc/validator/assignments.go
Other
Investigating performance issues with GetDuties and found this duplicated call for validator status.
N/A
I did not run this or test this in any testnet.
=> GetDuties: Refactor assignment status to deduplicate status computation

shared/aggregation/attestations/maxcover.go, shared/aggregation/attestations/maxcover_test.go
> Other / Optimization
- This PR improves performance of the max-cover aggregation w/o any major changes (in follow-up PR the new optimized `Bitlist64` based implementation of max-cover will be pushed).
- Optimizations include:
- Getting rid of **redundant** bit length validation, as we validate once, when aggregation starts, see:
https://github.com/prysmaticlabs/prysm/blob/9cc1438ea9ad1a08151cfc5787ad29f7f9fcb225/shared/aggregation/attestations/maxcover.go#L25-L30
- Replacing manual list merging with simple call to `append()`
- Using a filtering w/o allocation (see [how it works in Slice Tricks](https://github.com/golang/go/wiki/SliceTricks#filtering-without-allocating)
Part of …
=> Max-cover: minor optimizations

beacon-chain/blockchain/head_test.go, beacon-chain/core/blocks/randao_test.go, beacon-chain/core/state/skip_slot_cache_test.go, beacon-chain/core/state/transition_test.go, beacon-chain/db/kv/migration_archived_index_test.go, beacon-chain/db/kv/migration_block_slot_index_test.go, beacon-chain/p2p/fork_test.go, beacon-chain/p2p/options_test.go, beacon-chain/p2p/types/types_test.go, beacon-chain/rpc/beaconv1/blocks_test.go, beacon-chain/rpc/validator/proposer_test.go, beacon-chain/state/state_trie_test.go, beacon-chain/state/stateutil/attestations_test.go, beacon-chain/sync/rpc_status_test.go, beacon-chain/sync/rpc_test.go
Test cleanup
`assert.DeepEqual` works with byte arrays, which means we can replace `bytes.Equal` assertions in tests with our library.
N/A
N/A
=> Replace bytes.Equal with assert.DeepEqual in tests

beacon-chain/blockchain/process_attestation.go, beacon-chain/blockchain/process_attestation_helpers.go
> Clean up
`verifyAttestationIndices` violated the basic function principle "do one thing", it did two things:
* verify attesting indices
* return attesting indices
It was structured to return attesting indices because a subsequent method needed it. For this reason, we should break `verifyAttestationIndices` apart and bring index conversions to the upper layer
Fixes #
=> Refactor `verifyAttestationIndices` method

validator/accounts/accounts_import_test.go
Test fix
`TestImport_DuplicateKeys` currently asserts the value of a package-level variable, which causes the test output to be non-deterministic. This PR removes the assert from the test. We create a new wallet and keymanager, therefore verifying whether there are no accounts is not necessary.
Fixes all PRs ;-)
N/A
=> Remove test assertion that reads a package-level variable

shared/sszutil/deep_equal.go, shared/sszutil/deep_equal_test.go
Bug fix
This PR changes `sszutil.DeepEqual` to ignore unexported fields in structs, which will always cause a panic in the current function. This solves the panic.
=> Change sszutil DeepEqual to ignore unexported fields

validator/client/attest.go
> Bug fix
There's no reason to grab the attester lock before waiting 1/3 slot. At worst this would cause a lock contention when proposer and attester are perform together in the same slot
Fixes #8346 
N/A
=> Wait for one third before grabbing the lock

validator/client/attest.go, validator/client/propose.go
> Feature
Validator locking should be role based. There has been reports where attesting of previous/current slot delay proposing of the current slot
Could fix #8346 
=> Add role based lock for validator

validator/client/attest.go
> Minor improvement
Use strings builder to construct lock key for attesting. It is more performant than casting. It's about 70% faster and 10% less bytes per allocation. 
```go
BenchmarkTwoInputs-12    	 2901903	       397 ns/op	     432 B/op	       7 allocs/op
BenchmarkOneInputWithConcat-12    	 3710899	       316 ns/op	     448 B/op	       7 allocs/op
BenchmarkOneInputWithStringBuilder-12    	 4719397	       245 ns/op	     408 B/op	       7 allocs/op
func BenchmarkTwoInputs(b *testing.B) {
pubKey := [48]byte{'a'}
b.ReportAllocs()
for i := 0; i < b.N; i++ {
mputil.NewMultilock(fmt.Sprint(roleAttester), string(pubKey[:]))
}
}
func BenchmarkOneInputWithConcat(b *testing.B) {
pubKey := [48]byte{'a'}
b.ReportAllocs() …
```
=> Use strings builder for attester lock key

shared/grpcutils/BUILD.bazel, shared/grpcutils/grpcutils.go, shared/grpcutils/grpcutils_test.go, slasher/beaconclient/service.go, validator/accounts/BUILD.bazel, validator/accounts/accounts_exit.go, validator/client/BUILD.bazel, validator/client/propose.go, validator/client/service.go, validator/rpc/BUILD.bazel, validator/rpc/beacon.go, validator/rpc/beacon_test.go, validator/slashing-protection/BUILD.bazel, validator/slashing-protection/slasher_client.go, validator/slashing-protection/slasher_client_test.go
Refactor
https://github.com/prysmaticlabs/prysm/pull/8334 includes adding gRPC headers to context metadata. This is basically the same code repeated for the 4th time in the repo. This PR:
- introduces a new helper function in the `grpcutils` package that should be used moving forward
- changes existing header manipulation code to use the new helper
- does a small clean-up to the `grpcutils` package
N/A
N/A
=> Introduce helper function for adding context metadata from gRPC headers

shared/aggregation/BUILD.bazel, shared/aggregation/maxcover.go, shared/aggregation/maxcover_bench_test.go, shared/aggregation/maxcover_test.go, shared/aggregation/testing/bitlistutils.go
> Other / Optimization
- Adds `aggregation.MaxCover()` function (which will outdate the `MaxCoverProblem.Cover()` -- and overall, `MaxCoverProblem` struct).
- This new implementation relies on optmized `bitfield.Bitlist64` heavily (both for bitwise operations and for tracking processed attestations -- there `Bitlist64` is used as bitmap/bitset).
- Adds necessary unit tests.
- Adds bechnmark tests comparing our current (`MaxCoverProblem`-based) implementation and the new, optimized, one.
Extracted from #7938
Benchmark (`cur_` is the current implementation, `new_` is this PR's implementation, ~x8-10 improvement):
**Note:** ❗  Also, please, notice number …
=> Max-cover: optimized implementation based on Bitlist64

validator/accounts/cmd_wallet.go
Improvement
This PR adds the `--wallet-password-file` flag to enable non-interactive usage of the `wallet edit-config` command.
Fixes #8355
=> Add wallet file flag to edit-config command

beacon-chain/rpc/beacon/blocks.go, beacon-chain/rpc/beacon/blocks_test.go
> Feature
Adding `canonical` flag to `/eth/v1alpha1/beacon/blocks` so client can identify if the block is orphaned.
Fixes #8064 
=> Add canonical flag to ListBlocks API response

beacon-chain/sync/initial-sync/BUILD.bazel, beacon-chain/sync/initial-sync/blocks_queue.go, beacon-chain/sync/initial-sync/blocks_queue_test.go, shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
> Other
- Exploration of alternative forks has been tested in Pyrmont, and made it to the tagged release. Time to deprecate the flag.
Fixes #7734
=> Deprecate enableSyncBacktracking flag

beacon-chain/slasher/chunks.go, beacon-chain/slasher/chunks_test.go
Other
This PR simplifies the design of the `Chunker` interface a little bit. The removed return value is redundant because `slashertypes.NotSlashable` returned from the function already signifies that the attestation is not slashable.
N/A
N/A
=> Remove redundant bool return value from CheckSlashable

deps.bzl, go.mod, go.sum, third_party/herumi/herumi.bzl
=> Update Herumi BLS Library

beacon-chain/slasher/BUILD.bazel, beacon-chain/slasher/chunks.go, beacon-chain/slasher/chunks_test.go, beacon-chain/slasher/detect_attestations.go, beacon-chain/slasher/detect_attestations_test.go, beacon-chain/slasher/receive.go, beacon-chain/slasher/receive_test.go, beacon-chain/slasher/service.go, endtoend/endtoend_test.go, endtoend/helpers/BUILD.bazel, shared/slotutil/BUILD.bazel, shared/slotutil/epochticker.go, shared/slotutil/epochticker_test.go
> Feature
Part of #8331, this PR adds a few helper functions and tests required before we actually implement the detection algorithm for attester slashings. Namely, it adds the logic of batching attestations by validator chunk index, processing batches per epoch using an epoch ticker, and adding comprehensive tests for this new logic. It adds a `NewEpochTicker` function to our shared/slotutil package for further use, as it is also used by e2e tests. We mark the actual `detectAttestationBatch` function as a stub.
=> Add Helpers Required for Attestation Slashing Detection, Begin Detection Framework

shared/sszutil/deep_equal.go, shared/sszutil/deep_equal_test.go
Partially reverts prysmaticlabs/prysm#8336. 
The original PR changes the behavior of ssz deep equal, which does not panic on all unexported fields. 
More context is needed in the original PR before this logic change can be released.
=> Revert "Change sszutil DeepEqual to ignore unexported fields"

beacon-chain/blockchain/process_block.go, beacon-chain/core/state/trailing_slot_state_cache.go
Bug Fix
when updating the cache, as the context used can be canceled prematurely before the state has had a chance to 
advance. This instead uses a custom deadline so that it doesn't exit prematurely.
N.A
=> Add Custom Deadline for Slot Progression

validator/testing/BUILD.bazel
Other
This prevents a testing library from being linked into a production binary.
N/A
=> Validator testing library should be marked as testonly

validator/db/kv/db.go
> Other
This PR restricts certain validator buckets that write more data than needed to be fed to metric collector
N/A
N/A
=> Block validator buckets

beacon-chain/db/iface/interface.go, beacon-chain/db/kv/slasher.go, beacon-chain/db/kv/slasher_test.go, beacon-chain/slasher/chunks.go, beacon-chain/slasher/chunks_test.go, beacon-chain/slasher/detect_attestations.go, beacon-chain/slasher/detect_attestations_test.go, beacon-chain/slasher/receive.go, beacon-chain/slasher/receive_test.go, beacon-chain/slasher/service.go, beacon-chain/slasher/types/types.go
Part of #8331, this PR defines a few more useful types and slashing detection helpers, such as a CompactAttestation type used for the minimal information we need to perform slashing detection on attestations
=> Detection Further Helpers and Types for Attester Slashing Detection

third_party/herumi/herumi.bzl
Bug fix
Users with Intel chips gen 4 or older cannot run Prysm.
Fixes #8410 
=> Update Herumi with a fix for older intel chips

beacon-chain/gateway/BUILD.bazel, beacon-chain/gateway/gateway.go, beacon-chain/gateway/server/main.go, beacon-chain/node/node.go
Bug fix
gRPC gateway is effectively a gRPC client that connects to the beacon node. The gRPC gateway needs the TLS certificate if the beacon node is serving gRPC with TLS.
Fixes #8414 
I had to generate an SSL cert with `subjectAltName = IP:127.0.0.1` or gRPC client was complaining.
Tested by accessing `http://127.0.0.1:3500/eth/v1alpha1/node/version` and `:8080/healthz` without issue.
=> Provide TLS certificate to gRPC gateway

beacon-chain/blockchain/log.go, beacon-chain/blockchain/receive_block.go
> Feature
Add 
Add `timeSinceSlotStart` field to "Synced new block..." log, this enhances debugging capability for both propagation issue and attesting issue.
=> Add `timeSinceSlotStart` field to "Synced new block..." log

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/receive_block.go
> Feature
A node should be able to send `BlockProcessed` feed faster when feature flag `UpdateHeadTimely` is on.  Also gated the second send to be behind `UpdateHeadTimely` is off
=> Send feed faster with UpdateHeadTimely feature flag

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/service.go, beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/core/helpers/validators.go
> Clean up
Update proposer cache took two arguments:
```go
UpdateProposerIndicesInCache(state *stateTrie.BeaconState, epoch types.Epoch)
```
One argument would have been better to avoid fragmentation: 
```go
UpdateProposerIndicesInCache(state *stateTrie.BeaconState)
```
With this change:
* The `epoch` (i.e. `helpers.CurrentEpoch(state)`)  should have been derived from the state instead of allowing caller to dictate.  
* `postState` should also be advancing one slot to `UpdateProposerIndicesInCache` since it is one slot behind
N/A
This was discovered in #8319. With this, e2e test in #8319 passes
=> Some improvements to proposer cache

beacon-chain/p2p/service.go
Bug Fix
completely dropped. While the proper behaviour would actually to not drop any outbound messages from the host at all, this will require an upstream change to patch in. For now we increase the validation queue size to deal with it and bring the size in parity with our outbound queue size.
N.A
=> Increase Validation Queue

beacon-chain/main.go, beacon-chain/usage.go, shared/debug/debug.go, validator/main.go, validator/usage.go
This PR adds the --blockprofilerate and --mutexprofilefraction flags to both beacon node and validator client
=> Add Mutex and Block Profiling

beacon-chain/blockchain/process_block.go
=> On Block Cleanup

validator/db/kv/BUILD.bazel, validator/db/kv/attester_protection.go, validator/db/kv/attester_protection_test.go, validator/db/kv/db.go
Other
Better locking and flushing of this slice can help prevent dropped saves, in the event that there is already some batch save in progress.
N/A
=> Validator: Safer pending attestation records flushing

beacon-chain/slasher/chunks.go, beacon-chain/slasher/chunks_test.go, beacon-chain/slasher/detect_attestations.go, beacon-chain/slasher/helpers.go, beacon-chain/slasher/helpers_test.go, beacon-chain/slasher/params.go, beacon-chain/slasher/params_test.go, beacon-chain/slasher/types/BUILD.bazel, beacon-chain/slasher/types/types.go
> Feature
When performing slashing surround detection, we need to figure out the start epoch of a chunk we are updating. This differs depending on whether the chunk is a min span chunk or max span chunk. As such, we should add methods for this as part of the `Chunker` interface. Additionally, this PR adds a useful `Slashing` type which summarizes all the information about surround vote slashings.
Part of #8331
=> Methods For StartEpoch and Slashing Helper Types for Optimized Slasher

beacon-chain/rpc/validator/assignments.go, shared/hashutil/hash.go, slasher/beaconclient/receivers.go, tools/analyzers/comparesame/analyzer.go, tools/analyzers/cryptorand/analyzer.go, tools/analyzers/errcheck/analyzer.go, tools/analyzers/featureconfig/analyzer.go, tools/analyzers/maligned/analyzer.go, tools/analyzers/nop/analyzer.go, tools/analyzers/properpermissions/analyzer.go, tools/analyzers/shadowpredecl/analyzer.go, tools/analyzers/slicedirect/analyzer.go, validator/accounts/accounts_backup.go, validator/accounts/accounts_delete.go, validator/accounts/accounts_exit.go, validator/client/aggregate.go, validator/client/propose.go
> Code health
Ran code inspect and fixed warnings revolving: 
* Variable name the same as package name
* Conversion from int to string interprets integer value as code point 
N/A
N/A
=> Code inspect - clean ups

beacon-chain/sync/initial-sync/blocks_fetcher.go, validator/accounts/wallet_create.go, validator/slashing-protection/local/standard-protection-format/import.go
Cleanup
We should use `%w` when formatting errors inside `fmt.Errorf`. This PR fixes a few occurrences.
N/A
N/A
=> Fix error formatting inside fmt.Errorf

beacon-chain/core/state/skip_slot_cache.go
> Feature
Having to HTR for beacon state for skip slot cache key is inefficient. See flame graphs:
* During initial sync 
* Regular run time
Instead we can do better by HTR the latest block header and hash it with current state slot. This should be much nicer to the memory
N/A
N/A
=> Use latest block header + slot as skip slot cache key

shared/fileutil/fileutil.go, shared/fileutil/fileutil_test.go, validator/node/node.go
> Other
Summarizing the issue found by a contributor:
> If Prysm is started with --web and --write-wallet-password-on-web-onboarding it will store the wallet password in ~/.eth2validators/prysm-wallet-v2/walletpassword.txt after onboarding is completed, and this is later used to unlock the wallet when starting Prysm with the --web flag. File permissions are set correctly at file creation (0600), but Prysm will continue to start in the event that permissions are later adjusted to be readable by any user on the server.
Starting Prysm with --wallet-password-file and pointing to a wallet password file with incorrect file permissions also allows Prysm to start.
Given that this file contains sensitive data (cleartext …
=> Ensure Default Wallet Password Permissions Are Consistent

.bazelrc, validator/db/kv/attester_protection.go
Other
A very small optimization which may provide a minor improvement on memory churn / usage.
N/A
=> Validator: Choose a reasonable cap for the attested target epochs slice

.deepsource.toml
This PR ignores `tools/analyzers/**` in deep source, which always fails in some PRs because the analyzers package intentionally tries to create bad code that is static checked
=> Ignore Analyzers Package in DeepSource Config

beacon-chain/rpc/beaconv1/state.go, beacon-chain/rpc/beaconv1/state_test.go
Feature
This PR implements beacon API's `GetFinalityCheckpoints` method according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Beacon/getStateFinalityCheckpoints
Part of #7510
N/A
=> Implement GetFinalityCheckpoints in the beacon API

validator/db/kv/migration_source_target_epochs_bucket.go
Bug fix
Prevents a panic like the one below.
```
10:48:29" level=error msg="Runtime panic: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0xc002a87318, 0x33c360, 0x1b5a730)
GOROOT/src/runtime/debug/stack.go:24 +0x9f
main.main.func3()
validator/main.go:180 +0x6a
panic(0x33c360, 0x1b5a730)
GOROOT/src/runtime/panic.go:969 +0x1b9
go.etcd.io/bbolt.(*Bucket).Bucket(0x0, 0x1b82f70, 0x18, 0x18, 0x0)
external/io_etcd_go_bbolt/bucket.go:97 +0x37
github.com/prysmaticlabs/prysm/validator/db/kv.(*Store).migrateSourceTargetEpochsBucketUp.func2(0xc0000ec0e0, 0x1, 0xc0000ec0e0)
validator/db/kv/migration_source_target_epochs_bucket.go:54 +0x113 …
```
=> Add nil check for validator db migration

beacon-chain/slasher/chunks.go, beacon-chain/slasher/chunks_test.go, beacon-chain/slasher/detect_attestations.go, beacon-chain/slasher/detect_attestations_test.go
Refactor
`args` struct should not be mutated inside functions. It is passed as a pointer, therefore mutating it can cause bugs if the struct is reused after calling a function with such side-effects.
There are 2 possible ways to fix this: pass copies of the struct or remove the mutated fields. I opted for the latter, as `args` are to me like options - a read-only collection of information that the function can make use of.
N/A
N/A
=> Remove mutated fields from slasher args

beacon-chain/rpc/beacon/attestations_test.go, beacon-chain/rpc/beacon/blocks_test.go, shared/sszutil/deep_equal.go
> Feature
Makes testing happy for using standard `go test`. Fixes the following...
```
panic: interface conversion: interface {} is bitfield.Bitlist, not []uint8 [recovered]
```
N/A
N/A
=> Use DeepSSZEqual for tests

beacon-chain/db/iface/interface.go, beacon-chain/db/kafka/passthrough.go, beacon-chain/db/kv/kv.go, beacon-chain/db/kv/schema.go, beacon-chain/db/kv/slasher.go, beacon-chain/db/kv/slasher_test.go, beacon-chain/slasher/BUILD.bazel, beacon-chain/slasher/detect_blocks.go, beacon-chain/slasher/detect_blocks_test.go, beacon-chain/slasher/helpers.go, beacon-chain/slasher/helpers_test.go, beacon-chain/slasher/receive.go, beacon-chain/slasher/receive_test.go, beacon-chain/slasher/types/types.go
> Feature
Part of #8331. This PR adds the logic to detect double blocks in our optimized slasher. The approach is a simple batch call that checks for existing block proposals for a list of incoming (proposer_index, slot) items. If the existing proposals have a different signing root, we detect a proposer slashing.
=> Double Block Slashing Detection for Optimized Slasher

beacon-chain/blockchain/log.go
Enhancement
Moves the timing-related fields in the log message "Synced new block" to a debug level message "Timings for synced block". 
Pros: 
- Less cluttering on the Info level message
Cons:
- Increase in debug size as it adds an entire new message every 12 seconds. 
See https://discord.com/channels/476244492043812875/483017808658169866/812858407203504129
=> Move timings of synced block to debug level

beacon-chain/sync/subscriber.go
Cleanup
There was an unnecessary `WithField` statement in the log for "Could not subscribe topic"
N/A
=> Clean duplicated topic field in debug log

beacon-chain/rpc/node/server.go, beacon-chain/rpc/service.go, validator/rpc/health.go
> Bug fix
Thanks to @nisdas, after doing some investigation of why the beacon node gets into a deadlock when running the web ui, he was able to identify the following offender:
```
```
Essentially, the subscriber to the event feed where beacon node logs are being sent to is blocked and does not get unblocked at all.
```go
func (ns *Server) StreamBeaconLogs(_ *ptypes.Empty, stream pb.Health_StreamBeaconLogsServer) error {
ch := make(chan []byte, ns.StreamLogsBufferSize)
defer close(ch)
sub := ns.LogsStreamer.LogsFeed().Subscribe(ch)
defer sub.Unsubscribe()
```
We believe the buffer size is too small, and also, we should not be defer closing a buffered channel this way in a grpc call. Additionally, we were **not …
=> Better Handling of Subscriber Errors in Logs Streams

beacon-chain/db/kv/state_test.go, beacon-chain/db/restore_test.go, beacon-chain/operations/attestations/kv/aggregated_test.go, beacon-chain/rpc/beacon/blocks_test.go, beacon-chain/rpc/beacon/validators_test.go, beacon-chain/rpc/validator/aggregator_test.go, beacon-chain/state/stategen/epoch_boundary_state_cache_test.go, beacon-chain/state/stategen/getter_test.go, beacon-chain/state/stategen/migrate_test.go, beacon-chain/state/stategen/replay_test.go, beacon-chain/state/stategen/service_test.go, beacon-chain/state/types_test.go
> Test
Running go test pkg by pkg to get them to pass. This PR fixes
* Usages should have been `DeepSSZEqual`
* Configs should have been `UseMinimalConfig` 
* Slots should have been `types.Slot`
N/A
N/A
=> Use DeepSSZEqual to satisfy go tests

validator/client/propose.go, validator/client/propose_test.go, validator/client/service.go, validator/client/validator.go, validator/db/iface/interface.go, validator/db/kv/BUILD.bazel, validator/db/kv/db.go, validator/db/kv/graffiti.go, validator/db/kv/graffiti_test.go, validator/db/kv/schema.go, validator/graffiti/BUILD.bazel, validator/graffiti/parse_graffiti.go, validator/graffiti/parse_graffiti_test.go
> Feature
This is based on top of #8189 by @pinglamb. I extended it so that instead of resetting upon validator restart the index is stored in the database. Alongside it I store a hash of the graffiti file so that the index can be reset whenever the file is updated.
Fixes #8181 and fixes #8189
I left the behavior of cycling through the graffiti untouched, however I think it would be better if each was only emitted once. That way `ordered` could be combined with `random`/`default` which would take effect once all the ordered entries have been emitted.
=> Graffiti ordered index

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/rpc_topic_mappings.go, beacon-chain/p2p/types/BUILD.bazel, beacon-chain/p2p/types/rpc_goodbye_codes.go, beacon-chain/p2p/types/types.go, beacon-chain/p2p/types/types_test.go, beacon-chain/sync/pending_attestations_queue_test.go, beacon-chain/sync/rpc_goodbye.go, beacon-chain/sync/rpc_goodbye_test.go, beacon-chain/sync/rpc_ping.go, beacon-chain/sync/rpc_ping_test.go, beacon-chain/sync/rpc_status_test.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, deps.bzl, go.mod, go.sum, shared/testutil/BUILD.bazel, shared/testutil/helpers.go, shared/testutil/helpers_test.go, validator/client/BUILD.bazel, validator/client/aggregate.go, validator/client/propose.go
> Other
Follow up of discussion here: https://github.com/prysmaticlabs/prysm/pull/8257#discussion_r556770945. `p2p/types` defined some basic `SSZType` and are extracted to `sszutil/types` as they are not specific to `p2p`. This PR used `SSZUint64` from `eth2-types`.
@nisdas' [suggestion](https://github.com/prysmaticlabs/prysm/pull/8464#pullrequestreview-592825149).
=> Use eth2-types SSZUint64

beacon-chain/operations/slashings/mock.go, beacon-chain/rpc/beaconv1/BUILD.bazel, beacon-chain/rpc/beaconv1/pool.go, beacon-chain/rpc/beaconv1/pool_test.go, proto/migration/BUILD.bazel, proto/migration/migration.go
Feature
This PR implements beacon API's `SubmitAttesterSlashing` method according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Beacon/submitPoolAttesterSlashings
Part of #7510
This PR does not contain tests for code added to the `migration` package. This will be included in a separate PR.
=> Implement SubmitAttesterSlashing in the beacon API

beacon-chain/rpc/beacon/slashings.go, beacon-chain/rpc/beaconv1/pool.go
> Code health
Follow up #8515, this ensures the return error has proper status code
N/A
N/A
=> RPC: Proper status code for error

beacon-chain/rpc/beaconv1/config_test.go, shared/params/config.go, shared/params/loader_test.go, shared/params/mainnet_config.go, shared/params/minimal_config.go
> Feature: HF1
Add 3 new HF1 penalty configs. Note that we do not override constants at forks and instead create a new value and define its usage.
```
InactivityPenaltyQuotientHF1: reduced from 2**26 (= 67,108,864) to 3 * 2**24 (= 50,331,648)
MinSlashingPenaltyQuotientHF1: increased from 1 to 2
ProportionalSlashingMultiplierHF1: reduced from 2**7 (= 128) to 2**6 (= 64)
```
The new config values certainly help to move toward maximum planned security, but do not yet reach those planned maximally punitive values. Those values will be put in before the merge.
=>  HF1: Add penalty config values

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/options.go, go.mod
=> Fix Default Transport Option

beacon-chain/operations/slashings/mock.go, beacon-chain/operations/voluntaryexits/mock.go, beacon-chain/rpc/beaconv1/pool.go, beacon-chain/rpc/beaconv1/pool_test.go, proto/migration/migration.go, proto/migration/migration_test.go
Feature
This PR implements beacon API's `SubmitVoluntaryExit` and `SubmitProposerSlashing` methods according to the spec: https://ethereum.github.io/eth2.0-APIs/#/Beacon
Part of #7510
Very similar to #8515
=> Implement SubmitVoluntaryExit and SubmitProposerSlashing in the beacon API

shared/cmd/flags.go
=> Increase default peer limit from 30 to 45

WORKSPACE, beacon-chain/core/state/stateutils/BUILD.bazel, beacon-chain/p2p/peers/peerdata/BUILD.bazel, beacon-chain/p2p/peers/scorers/BUILD.bazel, contracts/deposit-contract/BUILD.bazel, deps.bzl, go.mod, go.sum, shared/attestationutil/BUILD.bazel, shared/bytesutil/BUILD.bazel, shared/depositutil/BUILD.bazel, shared/fileutil/BUILD.bazel, shared/hashutil/BUILD.bazel, shared/htrutils/BUILD.bazel, shared/interop/BUILD.bazel, shared/iputils/BUILD.bazel, shared/mathutil/BUILD.bazel, shared/messagehandler/BUILD.bazel, shared/pagination/BUILD.bazel, shared/runutil/BUILD.bazel, shared/sliceutil/BUILD.bazel, shared/sszutil/BUILD.bazel, shared/testutil/assertions/BUILD.bazel, slasher/detection/attestations/types/BUILD.bazel, validator/accounts/wallet/BUILD.bazel, validator/keymanager/BUILD.bazel
Bug fix
go 1.16 had some register changes for ARM64 as a performance improvement. This broke snappy v0.0.2. 
Fixes #8537 as a long term solution.
See: https://github.com/golang/snappy/pull/56
=> Update snappy to fix ARM64 with go.1.16 (Reverts #8538)

beacon-chain/state/BUILD.bazel, beacon-chain/state/doc.go, beacon-chain/state/getters.go, beacon-chain/state/getters_test.go, beacon-chain/state/setters.go, beacon-chain/state/state_trie.go, beacon-chain/state/validator_getters.go
> Cleanup
Before we use interface for state pkg's getter and setter, I want to do one round of clean up. Changes:
* `HasInnerState()` can be private `hasInnerState()`
*  Getter's `GenesisUnixTime` and `ParentRoot` are not used. They dont seem to have much use cases so deleting them
*  Setter's `SetValidatorIndexByPubkey` is not used. Deleting it
*  Validator read only getter's `CopyValidator()` is not used. Deleting it
* Move validator read only getter's to `validator_getter.go` to stay lean
N/A
N/A
=> Clean up state pkg's getter and setter

validator/client/service.go
Other
This stream interceptor is already defined in ConstructDialOptions. 
https://github.com/prysmaticlabs/prysm/blob/5a299ae6b72746a7ad319e05542d4ebff702abc0/validator/client/service.go#L258-L309
None reported
=> Validator: Remove optional and duplicated dialopts for streaming middleware

beacon-chain/db/iface/interface.go, beacon-chain/db/kafka/passthrough.go, beacon-chain/db/kv/slasher.go, beacon-chain/db/kv/slasher_test.go, beacon-chain/slasher/BUILD.bazel, beacon-chain/slasher/detect_attestations.go, beacon-chain/slasher/detect_attestations_test.go, beacon-chain/slasher/detect_blocks_test.go, beacon-chain/slasher/receive_test.go, beacon-chain/slasher/service_test.go
> Bug fix
Currently, slasher chunks for min/max spans in the optimized slasher implementation track only 16 epochs at a time. Our code works fine until we get an attestation that spans multple chunks, in which we get an issue of "chunk not found", and then slasher failing to work as expected for its entire duration.
The issue can be reproduced by creating an attestation with source 15 and target 16. This attestation lives in 2 different chunk indices, and our current approach could not handle this. As a solution, we fallback to the DB to retrieve a chunk if we get an attestation across chunk boundaries for ease of access.
Part of #8331 
It seems that …
=> Fallback to DB When Retrieving Missing Chunk in Optimized Slasher

beacon-chain/rpc/beaconv1/pool_test.go, shared/params/config.go
Cleanup
It simplifies validator configuration in tests. Some fields were unnecessarily initialized making tests harder to read.
It also corrects the comment of `FarFutureEpoch` configuration param.
N/A
N/A
=> Simplify API beacon pool tests

validator/client/metrics.go, validator/client/validator.go
>
> Bug fix
Feature
> Other
This PR adds metrics for the next scheduled proposal and attestation slot, per keys.
This information is available today as a log line, it would be more convenient to have it as a metric, because it would allows programmatic automation, such as when to schedule the next validator restart/maintenance.
-
Re-opening of #8526
=> Add metrics per keys for next scheduled attestation and proposal 

beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go
> Bug fix
- Since non-skipped slot is located using random sampling of future epochs, number of rounds in non-deterministic (normally 100 rounds cap is more than enough, but from time to time this is not enough -- and test fails).
- Instead of counting rounds, 5 seconds time cap is used (normally, completes in less than a second, occasionally spiking to 2 seconds). I've run the test for 1000 rounds, several times (with previous code ~ 1 out of every 20 tests were failing, with new time cap -- no failures were produced, so we are more robust now).
Fixes #8201
=> Fixes flaky TestBlocksFetcher_nonSkippedSlotAfter test

beacon-chain/cache/checkpoint_state_test.go, beacon-chain/cache/skip_slot_cache_test.go, beacon-chain/db/kv/state_test.go, beacon-chain/state/stategen/hot_state_cache_test.go
- Removes redundant parentheses around interface, when we need nil value of it
N/A
=> Simplify nil assignments

beacon-chain/state/field_trie.go, beacon-chain/state/state_trie.go
In `FieldReferencesCount()`, we call `f.Refs()` which uses the `reference` lock
Then it calls `len(f.fieldLayers)` which uses the `reference` lock again. Instead it should be using `FieldTrie` lock.
```go
// FieldTrie is the representation of the representative trie of the particular field.
type FieldTrie struct {
*sync.RWMutex // <- We should use this lock
*reference
fieldLayers [][]*[32]byte // <- When reading this
field       fieldIndex
}
type reference struct {
refs uint
lock sync.RWMutex // <- We SHOULD NOT use this lock
}
```
Note that I changed `FieldTrie`'s lock to `RWMutex` to gain read locking
=> Use proper read lock for `FieldTrie`

beacon-chain/state/BUILD.bazel, beacon-chain/state/field_trie.go, beacon-chain/state/getters.go, beacon-chain/state/references_test.go, beacon-chain/state/setters.go, beacon-chain/state/state_test.go, beacon-chain/state/state_trie.go, beacon-chain/state/stateutil/BUILD.bazel, beacon-chain/state/stateutil/reference.go, beacon-chain/state/stateutil/reference_bench_test.go, beacon-chain/state/stateutil/validator_map_handler.go, beacon-chain/state/types.go, beacon-chain/state/validator_getters.go
> Cleanup
Clean up `state` pkg in anticipation for future hard fork state. The goal is to extract some of the common usages into `stateutil` pkg
- Move `Reference` to `stateutil` pkg so it can be reused
- Move `ValidatorMapHandler` to `stateutil` pkg so it can be reused
Open question for previous author, do we need proper locking around `ValidatorMapHandler`? There wasn't any to begin with
Testing: Been running 10 pyrmont validators. So far so good
=> State: Refactor `Reference` and `ValidatorMapHandler` to stateutil pkg

shared/aggregation/aggregation.go, shared/aggregation/attestations/attestations_test.go, shared/aggregation/maxcover.go, shared/aggregation/maxcover_test.go
> Other / UTs improval
- Unused code is removed
- All important paths are tested (improving coverage from `80% -> 95%+`)
N/A
=> Improves UTs coverage in  shared/aggregation

beacon-chain/sync/initial-sync/service_test.go
> Bug fix
- When one runs test using bazel (our CI does) no issue occurs i.e. `bazel test //beacon-chain/sync/initial-sync:go_default_test --test_arg=-test.v --test_output=streamed --test_arg=-test.failfast --test_filter=TestService_Initialized` works just fine.
- However, when run using `go test ./beacon-chain/sync/initial-sync -v -failfast -run TestService_Initialized` goroutines are executed in a way that segmentation fault is always reproduced (nil `StateNotifier`):
It seems that `waitForStateInitialization()` makes to its execution in `go test` and doesn't in `bazel test`, hence issue with `go test`
N/A
=> Fix race condition in TestService_Initialized

validator/db/kv/db.go
it will be a freelist. Constantly syncing the freelist on each write is wasteful and has a non trivial impact on performance. 
This PR allows a validator db to skip syncing the freelist for each write, which will be useful for large users running with a lot of validators.
N.A
=> Ignore Syncing Freelist For Validator DB

beacon-chain/sync/subscriber_beacon_aggregate_proof.go, beacon-chain/sync/subscriber_beacon_attestation.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, beacon-chain/sync/validate_beacon_attestation.go, beacon-chain/sync/validate_beacon_attestation_test.go
> Bug fix
To send attestations over feed for type `AggregatedAttReceived`, the attestations should be sent when it is arrived, not after it is verified.
Beacon block has this correct in `validate_beacon_block.go`
Compliment #8602
There's no risk with this move, there's no real usage around operation feed `AggregatedAttReceived` except for `StreamAttestations` and that is used for old slasher which verifies attestation again upon receiving
=> Sync: send received attestations over feed at right places

beacon-chain/core/state/interop/write_state_to_disk.go, beacon-chain/rpc/debug/state.go, beacon-chain/rpc/debug/state_test.go, beacon-chain/state/getters.go, beacon-chain/state/getters_test.go, beacon-chain/state/interface/interface.go, shared/testutil/state_test.go, tools/benchmark-files-gen/main.go, tools/interop/export-genesis/main.go
> Feature
It seems anti pattern to always have to do:
```go
InnerStateUnsafe().MarshalSSZ()
CloneInnerState().MarshalSSZ()
```
Where we should just define the `MarshalSSZ` for beacon state and hide implementation detail
N/A
Discovered in #8584
=> BeaconState: Expose MarshalSSZ

beacon-chain/blockchain/service_test.go, beacon-chain/cache/checkpoint_state_test.go, beacon-chain/core/blocks/spectest/block_header_test.go, beacon-chain/core/blocks/spectest/block_processing_test.go, beacon-chain/core/state/benchmarks_test.go, beacon-chain/core/state/skip_slot_cache_test.go, beacon-chain/core/state/spectest/slot_processing_test.go, beacon-chain/core/state/state_test.go, beacon-chain/db/kv/state.go, beacon-chain/powchain/log_processing.go, beacon-chain/state/BUILD.bazel, beacon-chain/state/getters.go, beacon-chain/state/interface/interface.go, beacon-chain/state/state_trie_test.go, beacon-chain/state/types_test.go, shared/interop/BUILD.bazel, shared/interop/generate_genesis_state.go, shared/testutil/attestation.go, shared/testutil/spectest.go
> Refactor
After chatting with @rauljordan and @farazdagi, we came to conclusion since golang doesn't have conventional inheritance and overloading. With just embedding, we cant do the following:
```go
type BeaconState interface {
InnerStateUnsafe() *pbp2p.BeaconState
...
} 
type BeaconStateV1 interface {
BeaconState
InnerStateUnsafe() *pbp2p.BeaconStateV1
}
```
Ideally we will like to avoid returning interface but this is a good candidate for being an exception from "accept interfaces, return structs"  rule. We added `ProtobufBeaconState` helper to convert input, return pb beacon state and error if the input is not type pb beacon state
Part of #8584  …
=> State: Return interface{} for pb related methods

validator/db/kv/db.go
Reverts prysmaticlabs/prysm#8601
The original PR seems to have caused major issues with freelist sync, in Pyrmont. Specifically, without keeping a freelist in sync, the bolt db will spend a large amount of time reconstructing the freelist on start up. This exceeded 2 hours in Pyrmont test environment.
=> Revert "Ignore Syncing Freelist For Validator DB"

slasher/beaconclient/chain_data.go, slasher/beaconclient/chain_data_test.go, slasher/beaconclient/historical_data_retrieval.go, slasher/beaconclient/historical_data_retrieval_test.go, slasher/beaconclient/receivers.go, slasher/beaconclient/receivers_test.go, slasher/beaconclient/service.go, slasher/beaconclient/submit.go, slasher/beaconclient/submit_test.go, slasher/beaconclient/validator_retrieval.go, slasher/beaconclient/validator_retrieval_test.go, slasher/detection/detect.go, slasher/detection/detect_test.go, slasher/detection/listeners.go, slasher/detection/listeners_test.go, slasher/detection/service.go, slasher/rpc/service.go, validator/slashing-protection/slasher_client.go, validator/slashing-protection/slasher_client_test.go
Other
This pull request refactors the Service struct for the Slasher and the Validator Slashing Protection services by having a pointer to the Config struct as one of the fields, removing duplicated field declarations.
Part of #8603
Last batch of changes for #8603
=> Embed Config Pattern For Slasher, Slashing Protection

beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
=> Fix Powchain Genesis

beacon-chain/core/blocks/exit.go
Currently when exiting a validator before the required threshold of `SHARD_COMMITTEE_PERIOD` epochs, the message is a bit misleading, eg:
``` 
WARN accounts: Could not perform voluntary exit for account 0x974dc2826f2d: failed to propose voluntary exit: rpc error: code = InvalidArgument desc = validator has not been active long enough to exit: 187 epochs vs required 384 epochs
```
which can be read as "the validator has been active for 187 epochs and 384 are required. While in fact 187 is the current epoch and 384 is the epoch at which the validator becomes eligible for exit in the above example. In this example the validator was active for only 64 epochs. 
This PR changes the message for 
```
validator has not been active long enough to exit: 64 of 256 epochs. Validator will be eligible …
```
=> Change early exit error message

beacon-chain/core/epoch/epoch_processing.go, beacon-chain/state/interface/phase0.go, beacon-chain/state/stateV0/BUILD.bazel, beacon-chain/state/stateV0/setters.go, beacon-chain/state/stateV0/setters_test.go
Other
This is a minor refactoring to streamline a bit for Altair. In Altair, we have a similar rotation of participation in the state where the previous epoch participation is set to the current epoch participation.
The idea here is that another minor refactoring for Altair could rename this to an even more generic "RotateParticipation" which would apply to both v0 and v1 states. 
This is also less copying and lock contention.
N/A
=> Add beaconState RotateAttestations API method

endtoend/components/BUILD.bazel, endtoend/components/beacon_node.go, endtoend/components/slasher.go, endtoend/components/validator.go, endtoend/helpers/BUILD.bazel, endtoend/helpers/helpers.go
> Other / Refactoring
- Follow up to #8659 (see it for implementation details)
- In this PR:
- Adds `SlasherNode` and `SlasherNodeSet`, and corresponding `ComponentRunner` methods (similar to validator and beacon nodes, we need to start processes individually or in bunches, see #8665 for details).
- Additionally, per @rkapka request, for deduplication of code, process set rely on helper method to spawn and wait on processes (see `helpers.go:WaitOnNodes()`. Corresponding updates to `ValidatorNodeSet` and `BeaconNodeSet` are also added to this PR.
Extracted from #8643
=> E2E refactoring: SlasherNodeSet and SlasherNode

beacon-chain/forkchoice/protoarray/store.go, beacon-chain/forkchoice/protoarray/store_test.go
> Feature
Protoarray forkchoice to expose chainheads to support eth2.0 api:
https://github.com/ethereum/eth2.0-APIs/blob/master/apis/debug/heads.yaml
Helps #8675
=> Protoarray: add ChainHeads

tools/http-request-sink/BUILD.bazel, tools/http-request-sink/main.go, tools/http-request-sink/main_test.go
> Feature
No tracking issue. This PR adds a tool called http-request-sink which provides a simple http listener that stores all incoming request bodies into a local file.
=> HTTP Request Sink Tool

beacon-chain/state/state-altair/BUILD.bazel, beacon-chain/state/state-altair/deprecated_setters.go, beacon-chain/state/state-altair/field_trie_test.go, beacon-chain/state/state-altair/setters.go, beacon-chain/state/state-altair/state_trie.go, beacon-chain/state/state-altair/state_trie_test.go
Follow up on #8658 
Add copy, hash tree root. Most of them are identical to existing ones. Will add commentary in code
Note: Some tests are missing and that will come in next part (For preview of tests, check out #8584). The reason that we can't do tests in this PR is because tests require the testutil functions. If we include them then the diff will be 3000+
=> Part of 3 of beacon state Altair pkg - copy and hash tree root 

endtoend/minimal_slashing_e2e_test.go
- After discussion with Raul, we've concluded that the current e2e test for slasher should be skipped:
-  the implementation is to be replaced by the new in-beacon slasher developed in [feature/slasher](https://github.com/prysmaticlabs/prysm/tree/feature/slasher) and to be released soon.
- current test is flaky 
N/A
=> Skip e2e test for previous implementation of slasher

shared/bls/blst/signature.go, shared/bls/common/interface.go, shared/bls/herumi/signature.go
Other
AggregateVerify is not used in production code.
AggregateVerify does not match BLS spec exactly in that it does not check that all `msgs` are distinct. 
If possible, we could remove AggregateVerify. However, it seems critical for some spectests.
N/A.
=> BLS: Deprecate usage of AggregateVerify

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/forkchoice/protoarray/store.go, beacon-chain/forkchoice/protoarray/store_test.go
> Refactor
Park `Chainheads` implementation in to `Blockchain` service instead of `protoarray` service. It's a better place for this.
A good follow up issue will be to tighly couple proto array fork choice under blockchain service. Seems like it's exclusively used for blockchain while other services don't really need it
=> Move chainheads to blockchain pkg

shared/fileutil/fileutil.go
Bug Fix
to do that for larger files and prevents OOMs from happening during a database restoration.
Fixes #8702
=> Copy File More Efficiently

beacon-chain/core/altair/BUILD.bazel, beacon-chain/core/altair/block.go, beacon-chain/core/altair/block_test.go, beacon-chain/core/helpers/slot_epoch.go, beacon-chain/core/helpers/slot_epoch_test.go, beacon-chain/rpc/beaconv1/config_test.go, beacon-chain/state/interface/altair.go, beacon-chain/state/interface/phase0.go, beacon-chain/state/state-altair/getters.go, beacon-chain/state/state-altair/getters_test.go, beacon-chain/state/state-altair/state_trie.go, beacon-chain/state/stateV0/unsupported_getters.go, beacon-chain/state/stateV0/unsupported_setters.go, shared/params/config.go, shared/params/mainnet_config.go
Add process sync committee for beacon block for Altair:
```python
def process_sync_committee(state: BeaconState, aggregate: SyncAggregate) -> None:
committee_pubkeys = state.current_sync_committee.pubkeys
participant_pubkeys = [pubkey for pubkey, bit in zip(committee_pubkeys, aggregate.sync_committee_bits) if bit]
previous_slot = max(state.slot, Slot(1)) - Slot(1)
domain = get_domain(state, DOMAIN_SYNC_COMMITTEE, compute_epoch_at_slot(previous_slot))
signing_root = compute_signing_root(get_block_root_at_slot(state, previous_slot), domain)
assert eth2_fast_aggregate_verify(participant_pubkeys, signing_root, aggregate.sync_committee_signature)
total_active_increments = get_total_active_balance(state) // EFFECTIVE_BALANCE_INCREMENT …
```
=> Altair: Process sync committee 

beacon-chain/core/altair/BUILD.bazel, beacon-chain/core/altair/attestation.go, beacon-chain/core/altair/attestation_test.go, beacon-chain/rpc/beaconv1/config_test.go, beacon-chain/state/interface/altair.go, beacon-chain/state/interface/phase0.go, beacon-chain/state/state-altair/deprecated_setters.go, beacon-chain/state/state-altair/setters.go, beacon-chain/state/stateV0/unsupported_setters.go, shared/params/config.go
Add process attestation for beacon block in Altair:
```python
def process_attestation(state: BeaconState, attestation: Attestation) -> None:
data = attestation.data
assert data.target.epoch in (get_previous_epoch(state), get_current_epoch(state))
assert data.target.epoch == compute_epoch_at_slot(data.slot)
assert data.slot + MIN_ATTESTATION_INCLUSION_DELAY <= state.slot <= data.slot + SLOTS_PER_EPOCH
assert data.index < get_committee_count_per_slot(state, data.target.epoch)
committee = get_beacon_committee(state, data.slot, data.index)
assert len(attestation.aggregation_bits) == len(committee)
if data.target.epoch == get_current_epoch(state):
epoch_participation = state.current_epoch_participation
justified_checkpoint = …
```
=> Altair: process attestation for block

beacon-chain/core/altair/epoch.go, beacon-chain/core/altair/epoch_test.go
Add process participation flags for epoch in Altair:
```python
def process_participation_flag_updates(state: BeaconState) -> None:
state.previous_epoch_participation = state.current_epoch_participation
state.current_epoch_participation = [ParticipationFlags(0b0000_0000) for _ in range(len(state.validators))]
```
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/beacon-chain.md#participation-flags-updates
Part of #8638
=> Altair: process participation flag update for epoch

beacon-chain/slasher/rpc.go
> Feature
Currently, using remote slashing protection for attestations does not save the attestations it receives in slasher's history. This means remote slashing protection is pointless because it will not be able to check an incoming, *slashable* attestation is slashable with respect to a previous attestation slasher has seen.
Even with this change, any found slashings by remote slashing protection **will not** be forward to the operations pool. We do not want to slash our own validator.
Part of #8331
=> Save Attestations in Slasher's History During Remote Protection

beacon-chain/core/altair/BUILD.bazel, beacon-chain/core/altair/epoch.go, beacon-chain/core/altair/epoch_test.go, beacon-chain/core/altair/validator.go, beacon-chain/core/altair/validator_test.go
Add process slashing for block and epoch for Altair:
```python
def process_slashings(state: BeaconState) -> None:
epoch = get_current_epoch(state)
total_balance = get_total_active_balance(state)
adjusted_total_slashing_balance = min(sum(state.slashings) * PROPORTIONAL_SLASHING_MULTIPLIER_ALTAIR, total_balance)
for index, validator in enumerate(state.validators):
if validator.slashed and epoch + EPOCHS_PER_SLASHINGS_VECTOR // 2 == validator.withdrawable_epoch:
increment = EFFECTIVE_BALANCE_INCREMENT  # Factored out from penalty numerator to avoid uint64 overflow
penalty_numerator = validator.effective_balance // increment * adjusted_total_slashing_balance
penalty = penalty_numerator // total_balance * increment
decrease_balance(state, …
```
=> Altair: Slashing for block and epoch

beacon-chain/rpc/validator/BUILD.bazel
Other
I noticed an issue where buildkite will timeout on this test exceeding 800s.
Fixes angry developers.
moderate is 5 minute timeout. See: https://docs.bazel.build/versions/master/be/common-definitions.html#common-attributes-tests
=> Set test timeout on //beacon-chain/rpc/validator:go_default_test. Sometimes exceeds 800s otherwise

shared/trieutil/helpers.go, shared/trieutil/helpers_test.go
> Other / Update per specs
- In this PR not only specs comment is updated, to reflect the current specs, but the code is also updated as for `get_power_of_two_ceil(0)` and `get_power_of_two_floor(0)` expected output value (in the current specs) is 1, not 0.
- This shouldn't change anything as those functions are hardly called with 0 as input, but still should be updated to reflect the current specs.
N/A
=> Update NextPowerOf2() and PrevPowerOf2() funcs

.buildkite-bazelrc
Other -- On a quest for faster CI builds!
Buildkite CI is constantly backlogged, any improvements to build speed will help merge PRs faster.
Minimal remote downloads will only download cached items required for local operations, this saves on network I/O and disk space.
Strict action environment leads to higher cache hits and more reproducible builds. 
Both of these improvements should show an overall decrease in build times on buildkite.
=> CI: minimal remote downloads, strict action environment

beacon-chain/core/epoch/precompute/reward_penalty.go
Move the calculation of finality delay to within the 2 `if` block where it's really needed
=> Move finality delay calculation

beacon-chain/blockchain/process_block.go, beacon-chain/core/state/transition_no_verify_sig.go
- The last update for specs comments (for phase0 specs).
- Double checked that our code implements the specs (and only comments need to be updated).
N/A
=> Update specs comments

.codecov.yml
Testing
The current codecov configuration ignores all files with `_mock` suffix, but only generated files have such names. All other mock files are *prefixed* with `mock`. This change ignores all files whose names contain `mock`. It's very unlikely that a regular file will be named like that.
N/A
N/A
=> Codecov: ignore all mock files

beacon-chain/node/BUILD.bazel, beacon-chain/node/config_test.go
Testing
Adds tests for the `beacon-chain/node/config.go` file.
N/A
N/A
=> Tests for `beacon-chain/node/config.go`

beacon-chain/core/altair/BUILD.bazel, beacon-chain/core/altair/transition.go, beacon-chain/core/altair/transition_test.go, beacon-chain/core/state/skip_slot_cache.go, beacon-chain/core/state/transition.go
Add `ProcessSlots` for Altair. This is the same implementation as phase 0 except using Altair version of `ProcessEpoch`
=> Altair: Add `ProcessSlots`

beacon-chain/node/registration/powchain.go
Other
Fixes a weird log message.
```
[2021-04-16 12:31:40] ERROR registration: context.BackgroundNo ETH1 node specified to run with the beacon node. Please consider running your own ETH1 node for better uptime, security, and decentralization of ETH2. Visit https://docs.prylabs.network/docs/prysm-usage/setup-eth1 for more information.
[2021-04-16 12:31:40] ERROR registration: context.BackgroundYou will need to specify --http-web3provider and/or --fallback-web3provider to attach an eth1 node to the prysm node. Without an eth1 node block proposals for your validator will be affected and the beacon node will not be able to initialize the genesis state.
```
None filed, quick fix. …
=> POW: remove context from log message

.bazelignore, beacon-chain/core/altair/BUILD.bazel, beacon-chain/state/state-altair/BUILD.bazel, spectest/mainnet/altair/operations/BUILD.bazel, spectest/mainnet/altair/operations/attestation_test.go, spectest/mainnet/altair/operations/attester_slashing_test.go, spectest/mainnet/altair/operations/block_header_test.go, spectest/mainnet/altair/operations/deposit_test.go, spectest/mainnet/altair/operations/proposer_slashing_test.go, spectest/mainnet/altair/operations/voluntary_exit_test.go, spectest/minimal/altair/operations/BUILD.bazel, spectest/minimal/altair/operations/attestation_test.go, spectest/minimal/altair/operations/attester_slashing_test.go, spectest/minimal/altair/operations/block_header_test.go, spectest/minimal/altair/operations/deposit_test.go, spectest/minimal/altair/operations/proposer_slashing_test.go, spectest/minimal/altair/operations/voluntary_exit_test.go, spectest/shared/altair/operations/BUILD.bazel, spectest/shared/altair/operations/attestation.go, spectest/shared/altair/operations/attester_slashing.go, spectest/shared/altair/operations/block_header.go, spectest/shared/altair/operations/deposit.go, spectest/shared/altair/operations/helpers.go, spectest/shared/altair/operations/proposer_slashing.go, spectest/shared/altair/operations/voluntary_exit.go
> Other / Tests
- Implements `mainnet/altair/operations` tests (see [specs](https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/mainnet/altair/operations))
- Adds `spectest/minimal/altair` to `.bazelignore` for time being (minimal tests are included in this PR, they are just not run i.e. ignored). Once I figure out what is wrong with minimal config SSZ unmarshalling, single PR enabling all the Altair minimal tests (in `operations`, `epoch_processing` etc) will be added.
N/A
=> Altair: "operations" spec tests

beacon-chain/core/altair/epoch_precompute.go
Base reward in spec is defined as 
```python
(state.validators[index].effective_balance // EFFECTIVE_BALANCE_INCREMENT) * Gwei(EFFECTIVE_BALANCE_INCREMENT * BASE_REWARD_FACTOR // integer_squareroot(get_total_active_balance(state)))
```
I thought I could cross out `EFFECTIVE_BALANCE_INCREMENT` but found it the hard way during spec test 😢
=> Fix `BaseReward` calculation

beacon-chain/cache/depositcache/deposits_cache.go, beacon-chain/cache/depositcache/deposits_cache_test.go
> Bug fix
In summary, there was a serious incident affecting eth2 mainnet this past evening CST, which affected block proposals from Prysm validators throughout an eth1 voting period. This bug was causing Prysm nodes to vote in an incorrect eth1 data due to an off-by-one error through an edge case in the Go standard library.
In summary, we have the following problem:
```go
items := []int{1, 2, 2, 2, 3, 4, 4, 5}
```
and we use binary search from the Go standard library `sort` package, `sort.Search`, to find the index of an element `x` such that `items[i] > x`. However, the [official Go docs](https://golang.org/pkg/sort/#Search) for `sort.Search` state the following:
```
func Search(n int, f func(int) bool) int
Search …
```
=> Amend DepositNumberAndRootAtHeight Function to Fix Off-By-One

beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
=> Initialize Data Correctly For Powchain Service

beacon-chain/core/altair/epoch_precompute.go
Part of #8638 
Credit to @rkapka, this was discovered in #8813. 
We should apply additional penalty during inactivity to slashed validators
=> Apply inactivity when validator is slashed

shared/bls/BUILD.bazel, shared/bls/bls.go, shared/bls/bls_test.go
=> Validate Big Number Strings Better

beacon-chain/powchain/BUILD.bazel, beacon-chain/powchain/log_processing.go, beacon-chain/powchain/log_processing_test.go, beacon-chain/powchain/service.go
Cleanup
missing deposit logs. This helps simplify our code and also resolves a potential nested RLock found in the course of building a RLock analyzer in #8775 . By removing the related methods, we treat a skipped index as a failure condition from the currently connected eth1 node.
N.A
=> Remove Missing Logs Method

spectest/shared/phase0/rewards/rewards_penalties.go
- When working for rewards tests for Altair (in #8818), I've noticed that test outputs do not feature what type/subcategory of "rewards" tests is being run:
- This small PR updates output of those tests:
N/A
=> Spec tests: improve readability of rewards tests output

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
This PR inverts `ProposerAttsSelectionUsingMaxCover` flag to improve validator performance. This flag has also been tested for a while. It's part of `--dev`
=> Invert `proposer-atts-selection-using-max-cover` flag

beacon-chain/core/altair/transition.go
Since we refactored out `ProcessInactivityScores`, let's make sure it's used in `ProcessEpoch` or else spec test will fail
=> Altair: use `ProcessInactivityScores`

beacon-chain/core/altair/block.go, shared/bls/blst/signature.go, shared/bls/blst/signature_test.go, shared/bls/blst/stub.go, shared/bls/common/interface.go, validator/client/propose_test.go
Part of #8638 
Add `Eth2FastAggregateVerify` implementation and use it for `ProcessSyncCommittee`. We were using the canonical `FastAggregateVerify` instead which caused spec test to fail
=> Altair: Add `Eth2FastAggregateVerify`

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
This PR inverts `next-slot-state-cache` flag to improve validator performance. This flag has also been tested for a while. It's part of --dev
=> Invert `next-slot-state-cache` flag

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
Reverts prysmaticlabs/prysm#8830
@nisdas pointed out he is seeing 30% memory inc in latest develop and suspects this is the cause. It's seems sane to revert this before the release
=> Revert "Invert `next-slot-state-cache` flag"

beacon-chain/state/state-altair/BUILD.bazel, beacon-chain/state/state-altair/field_root_participation_bit.go, beacon-chain/state/state-altair/field_root_sync_committee.go, beacon-chain/state/state-altair/state_trie_block_box_test.go
Part of #8638 
This PR implements the correct version of 1.) sync committee and 2.) participation bits roots for HTR.
We had to temporarily skip two tests where the use of generic FSSZ HTR is compared. They will be fixed by @rauljordan in the upcoming week.
We should merge this first to unblock progress as I verified these implementations are passing spec tests in #8847
=> Altair: Fix field roots computations 

beacon-chain/core/altair/epoch_spec.go, beacon-chain/core/altair/epoch_spec_test.go
Part of #8638 
Fix an epoch offset for sync committee rotation in Altair. Discovered and verified using spec test in #8831
=> Fix an epoch offset for sync committee rotation

shared/clientstats/BUILD.bazel, shared/clientstats/scrapers.go, shared/clientstats/scrapers_test.go
> Feature
Adds the `validator_total` and `validator_active` metrics to the client-stats metrics scraper.
Fixes #8848 
that's it, thanks!
=> fixes #8848 -- scrape validator_(total|active)

beacon-chain/state/stateutil/validator_root.go
Cleaning up on how we mix length root in `Uint64ListRootWithRegistryLimit ` by improving usages around `PutUint64`
=> Minor clean up on mixing length root

beacon-chain/rpc/service.go
> Bug fix
Listing pooled voluntary exits through the API results in nil reference because the pool is not initialized anywhere. This PR adds the initialization code.
Update: The same thing fixed for `BlockReceiver`.
N/A
N/A
=> Initialize `VoluntaryExitsPool` and `BlockReceiver` in rpc server

beacon-chain/powchain/service.go
When the followBlockHeight is zero we should only request the genesis block only. 
Perhaps a better fix would be to fix `determineEarliestVotingBlock` so that if the `earlestValidTime` is earlier that ETH1 genesis, then we should return the genesis hash, but this requires knowledge of the eth1 genesis, which is ugly
=> Remove spurious ETH1 not connected logs when near chainstart

beacon-chain/db/kv/backup.go, beacon-chain/rpc/validator/attester.go, beacon-chain/state/stateV0/setters_attestation_test.go, cmd/client-stats/flags/flags.go, cmd/validator/flags/flags.go, shared/clientstats/scrapers.go, shared/gateway/gateway.go, tools/analyzers/ineffassign/ineffassign.go, validator/accounts/wallet/wallet.go, validator/client/iface/validator.go, validator/client/propose.go, validator/client/validator_test.go, validator/db/kv/deprecated_attester_protection.go, validator/db/kv/prune_attester_protection.go
Performed a round of code cleanups. Fixed the following:
- Comment of exported elements started with incorrect name
- Error string should not be capitalized
- Unused declarations
- Redundant casting
- Redundant parentheses
=> Various code cleanups

beacon-chain/rpc/beaconv1/state.go, beacon-chain/rpc/statefetcher/fetcher.go
Other
Changes the way state API endpoints treat incoming hex values of state ID. Currently they assume hex values contain the `0x` prefix, but since we receive a byte array it's more reasonable to send only the state ID. This change will make state endpoint behave in the same way as block endpoints.
The `0x` prefix will be removed by the HTTP proxy server before forwarding the request.
N/A
N/A
=> Simplify handling hex state ID

beacon-chain/cache/BUILD.bazel, beacon-chain/cache/sync_committee.go, beacon-chain/cache/sync_committee_disabled.go, beacon-chain/cache/sync_committee_test.go
Part of #8638 
Adding a sync committee cache for facilitate 
- Quick lookup whether validator is part of sync committee for current epoch or next epoch
- Quick lookup the validator index position with respect to sync committee
Having this cache enables cheap compute for functions like `is_assigned_to_sync_committee` and `compute_subnets_for_sync_committee` and `get_sync_committee_selection_proof`
=> Altair: sync committee cache

beacon-chain/db/iface/interface.go, beacon-chain/db/slasherkv/pruning.go, beacon-chain/db/slasherkv/pruning_test.go, beacon-chain/db/slasherkv/slasher.go, beacon-chain/slasher/receive.go, beacon-chain/slasher/receive_test.go
> Bug fix
Our new slasher in #8340 has serious performance issues when performing database pruning. For the purposes of slashing, we only care about data from the last N epochs where N is a safe weak subjectivity period, such as 4096 epochs. We should be pruning old data every slot to avoid accumulation of unnecessary info. Our current pruning algorithm has a serious bug in that it does as follows:
1. Run for 4096 epochs
2. Upon hitting epoch 4097, prune _everything_ before it
This is very dangerous and incorrect as a solution. Instead, we should be using a _sliding window_ between [current_epoch-HISTORY_LENGTH, current_epoch]. For example:
With `HISTORY_LENGTH = 4`, if we have epochs `0, 1, 2, 3` and we then reach …
=> Use Pruning Sliding Window for Slasher

beacon-chain/rpc/beaconv1/pool.go, beacon-chain/rpc/beaconv1/pool_test.go, shared/testutil/assertions/assertions.go
Test fix
This PR is a follow up for #8902 which fixes the testing methodology as before we had assumed the results from `attestationPool.AggregatedAttestations()` to follow the same order as input, but this was not the case. 
This also improves testing coverage to include unaggregated attestations.
=> Fix testing for attestation pools endpoint

beacon-chain/db/kv/state.go
Bug Fix
existence.
Fixes #8886
=> Fix Panic When Accessing State Frequently

go.mod, go.sum
Bug fix
Because of updating grpc-gateway from v1 to v2 in https://github.com/prysmaticlabs/prysm/pull/8697, existing v1alpha1 APIs stopped working correctly when the URL included specific chars in a base64-encoded parameter. https://github.com/prysmaticlabs/grpc-gateway/pull/7 fixed the issue so now we have to update the dependency.
N/A
N/A
=> Update grpc-gateway dependency

beacon-chain/rpc/nodev1/node.go, beacon-chain/rpc/nodev1/node_test.go, shared/gateway/api_middleware.go, shared/gateway/middleware_structs.go
Feature
#8920 updated the ethereumapis dependency, which resulted in adding a missing `IsSyncing` field that should be added to the response of `/node/syncing`. This PR updates the gRPC function and runs the endpoint through API Middleware. 
Part of API Middleware feature
N/A
=> Run `/node/syncing` through API Middleware

shared/interfaces/BUILD.bazel, shared/interfaces/altair_block_wrapper.go, shared/interfaces/block_interface.go, shared/interfaces/phase0_block_wrapper.go
Block interface's copy should return interface type or else it can't be extensible with different versions of block
=> Block interface's Copy() to return interface

beacon-chain/rpc/node/BUILD.bazel, beacon-chain/rpc/node/server.go, shared/bls/blst/bls_benchmark_test.go, shared/bls/blst/signature_test.go, tools/analyzers/errcheck/analyzer.go, validator/client/propose.go, validator/testing/BUILD.bazel, validator/testing/mock_slasher.go
Cleanup 
Fixes #6891
This PR goes through the deprecated usages mention in #6891 on top of me looking through with `inspect code` and changing any function usages that made sense to update.
=> Update deprecated function usages

beacon-chain/powchain/service.go
Log cleanup 
This PR fixes #8852, by removing stack traces from eth1 connection errors as they confuse users and aren't very helpful for these types of issues.
=> Remove stack trace from eth1 connection errors

shared/gateway/api_middleware.go, shared/gateway/middleware_structs.go
This PR implements the https://ethereum.github.io/eth2.0-APIs/#/Beacon/getBlockHeaders API endpoint.
It is a part of the API Middleware feature.
=> Implement `/beacon/headers` API endpoint (#8904)

spectest/mainnet/altair/operations/BUILD.bazel, spectest/mainnet/altair/operations/sync_committee_test.go, spectest/minimal/altair/operations/BUILD.bazel, spectest/minimal/altair/operations/sync_committee_test.go, spectest/shared/altair/operations/BUILD.bazel, spectest/shared/altair/operations/sync_committee.go
Part of #8638 
Adding sync committee spec test:
https://github.com/ethereum/eth2.0-spec-tests/tree/master/tests/mainnet/altair/operations/sync_committee/pyspec_tests
=> Altair: Add sync committee spec test

cmd/client-stats/flags/flags.go, cmd/client-stats/main.go
Bug fix
Fixes help text for the client-stats `--scrape-interval` flag. With this change the flag parsing library knows the intended default value so that it is correctly displayed in generated `--help` text.
n/a -- quick fix, reported by Preston
=> use urfave defaulting method for correct help text

scripts/mirror-ethereumapis.sh
Follow-up to #8980, this PR fixes a small issue in the bash script to use https for git cloning instead
=> Fix EthereumAPIs Mirror Script

shared/gateway/gateway.go
Bug fix
https://github.com/prysmaticlabs/prysm/pull/8697 introduced a breaking change to `v1alpha1` APIs. JSON output was modified from `camelCase` to `snake_case`, thus breaking the Web UI.
Hotfix
N/A
=> Do not use proto casing in `v1alpha1` API JSON fields

shared/mathutil/math_helper.go, shared/mathutil/math_helper_test.go
Bug fix
This method is unused and may have an precision loss issue with values over 52 bits.
Fixes #8989
=> Remove unused ClosestPowerOf2 method

scripts/mirror-ethereumapis.sh
> Other
Improves the ethereumapis mirror script with the following improvements:
- Copies over only proto, go files, and markdown files
- Does not push if diff is empty
- Replaces remaining import changes
- Does not override global git config
=> Improve Mirror Bash Script for EthereumAPIs

shared/copyutil/cloners.go
Added a copy method for `SyncAggregate` object then use it for `CopyBeaconBlockBodyAltair`
=> Altair: Copy sync aggregate

beacon-chain/db/kv/BUILD.bazel, beacon-chain/db/kv/block_altair_test.go, beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/blocks_test.go, beacon-chain/rpc/beacon/blocks.go, shared/testutil/block.go
Part of #8638 
Ensures that we can save and get altair versioned beacon blocks in db
Lots of tests
=> Altair: beacon block operation in DB

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
Reverts prysmaticlabs/prysm#8827
Pending concrete data and release of sigp/lighthouse#2319, we are reverting the opt-in/out feature flag for attest-timely.
=> Revert "Invert `attest-timely` flag"

beacon-chain/cache/BUILD.bazel, beacon-chain/cache/error.go, beacon-chain/cache/sync_committee.go, beacon-chain/cache/sync_committee_disabled.go, beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/operations/synccommittee/BUILD.bazel, beacon-chain/rpc/validator/assignments.go
Add fall back checks to is in sync committee helper. It ensures when there is a cache miss, it also checks the input committee object for a public key match
=> Add fallback check to sync committee helper

beacon-chain/rpc/apimiddleware/endpoint_factory.go, shared/gateway/api_middleware.go, shared/gateway/gateway.go, shared/gateway/gateway_test.go
Bug fix
Validator client does not need the API Middleware. It does not provide configuration required to properly register the middleware. This causes the validator client to fail on startup.  
The bug fix makes sure that the API Middleware is registered only when proper configuration is provided.
Fixes the validator client
N/A
=> Do not register API Middleware with validator gateway

beacon-chain/core/blocks/block_regression_test.go, beacon-chain/core/blocks/deposit_test.go, beacon-chain/core/blocks/header_test.go, beacon-chain/core/blocks/proposer_slashing_test.go, beacon-chain/powchain/deposit_test.go, beacon-chain/powchain/log_processing_test.go, beacon-chain/rpc/validator/assignments_test.go, beacon-chain/rpc/validator/exit_test.go, beacon-chain/rpc/validator/proposer_test.go, beacon-chain/sync/pending_attestations_queue_test.go, endtoend/BUILD.bazel, endtoend/minimal_e2e_test.go, endtoend/minimal_slashing_e2e_test.go, shared/testutil/deposits.go, shared/testutil/deposits_test.go
Reset test utility's deposit cache. The usage of `ResetCache()`, `DeterministicDepositsAndKeys()`, `DeterministicGenesisState()` and `DeterministicDepositsAndKeysSameValidator()` are fragmented.
We shouldn't rely on the test case implementer to know and manually reset the cache every time. Often, they will spend a long time figuring why setup doesn't work, this is not trivial to debug
=> Testutil: Reset deposit cache internally

slasher/db/kv/spanner_new.go
Fixes #8709 by adding a proper type assertion in the slasher codebase
=> Fix Small Type Assertion Bug in Slasher

beacon-chain/db/kv/backup.go
Bug Fix
through all the buckets in the db to rebuild the freelist. 
N.A
=> Disable No Freelist Sync In Backups

.buildkite-bazelrc
Other
Increases java memory for bazel from 1g to 2g.
Fixes issues with new spec tests in hf1 branch.
See: https://buildkite.com/prysmatic-labs/prysm/builds/51281 for a full run on top of hf1 with the new java opts set.
I did not find the root cause of the issue, but I suspect it has to do with an increased number of files loaded into the action cache / memory when running spec tests.
Example failure that this resolves: https://buildkite.com/prysmatic-labs/prysm/builds/51275#40198df3-e5c9-4d07-b7e7-7db587d89551
=> Double java heap size for buildkite

beacon-chain/operations/synccommittee/message.go, go.mod, go.sum, shared/queue/BUILD.bazel, shared/queue/priority_queue.go
The priority queue uses `copystructure.Copy` underneath when we push an item on to the queue. As seen from the flame, it's expensive due to reflect and many things. This PR removes the copy on push given the copy is done by the caller in `SaveSyncCommitteeMessage`
Also squeezed in a minor refactor for `SaveSyncCommitteeMessage` to avoid potential dead lock
=> Remove copy when push to priority queue

beacon-chain/core/altair/epoch_spec.go, beacon-chain/core/state/transition.go, beacon-chain/operations/synccommittee/BUILD.bazel, validator/client/runner.go
We haven't inserted update sync committee cache to run time code path. This PR does it.
Update sync committee cache when:
- Update sync committee at every `EPOCHS_PER_SYNC_COMMITTEE_PERIOD` interval
- Upgrade beacon state from phase 0 to Altair
=> Altair: Update sync committee cache

WORKSPACE, shared/params/loader_test.go
Other
I noticed we were using alpha.7 spectests but referencing alpha.6 spec. This PR adds a variable that all of the dependencies can reference. This would insure that all 4 deps are on the same version.
N/A
=> Use same version of spectests and spec in WORKSPACE

beacon-chain/db/slasherkv/BUILD.bazel, beacon-chain/db/slasherkv/kv.go, beacon-chain/db/slasherkv/pruning.go, beacon-chain/db/slasherkv/schema.go, beacon-chain/db/slasherkv/slasher.go, beacon-chain/db/slasherkv/slasher_test.go
Reverts prysmaticlabs/prysm#8927, as this PR led to attestation records taking around 1.2 Tb on Prater:
Napkin math:
```
100 attestations per block, 100 validators per attestation
key = epoch <> validator_index (8 bytes + 5 bytes) = 13 bytes
32 +  size_of(att) 
10,000 values per slot
keys total bytes = 4096 * 32 * (10000 * 13) = 17,039,360,000
values total bytes = 4096 * 32 * (10k * 950) = 1,245,184,000,000
```
=> Revert "Improve performance during CheckAttesterDoubleVotes"

beacon-chain/db/slasherkv/BUILD.bazel, beacon-chain/db/slasherkv/pruning.go, beacon-chain/db/slasherkv/slasher.go, beacon-chain/db/slasherkv/slasher_test.go
This PR is part of #8331. It also uses concurrency to improve double vote detection from #8927 but keeps a disk-space-efficient schema. The schema from 8927 ended up using up too much disk space in testnet trials.
=> Parallelized Double Vote Detection in Slasher With Disk-Space Efficient Schema

WORKSPACE, beacon-chain/rpc/apimiddleware/BUILD.bazel
Update spec tests to latest alpha8: https://github.com/ethereum/eth2.0-specs/releases/tag/v1.1.0-alpha.8
=> Update spec test to alpha8

shared/gateway/BUILD.bazel, shared/gateway/api_middleware_processing.go, shared/gateway/api_middleware_processing_test.go, shared/gateway/param_handling.go, shared/gateway/param_handling_test.go
Cleanup
Moves parameter handling related functions to a separate file. The `api_middleware_processing.go` file is quite big already and we will have some more param-related code coming soon.
=> Move API param handling to separate file

shared/bls/blst/public_key.go, shared/bls/blst/public_key_test.go
Bug fix
AggregatePublicKeys returns a true if pubkeys(its args) is nil or empty. A check was added. 
fixes  #9091 
=> No length check in AggregatePublicKeys

beacon-chain/node/node.go, beacon-chain/server/main.go, cmd/beacon-chain/flags/base.go, cmd/beacon-chain/main.go, cmd/beacon-chain/usage.go, endtoend/components/beacon_node.go
Other
`api-middleware-port` is the current name of the flag which specifies the port to serve HTTP JSON conforming to the official Eth2 APIs. API Middleware is an implementation detail and the flag name should rather describe the functionality. This PR renames it to `eth-api-port`. If we replace the API Middleware with something else in the future, the flag name will still be up-to-date.
=> Make Eth APIs flag name implementation agnostic

beacon-chain/cache/sync_committee.go, beacon-chain/core/altair/BUILD.bazel, beacon-chain/operations/synccommittee/BUILD.bazel, beacon-chain/rpc/prysm/v2/validator/BUILD.bazel, shared/p2putils/BUILD.bazel, shared/p2putils/fork.go, shared/params/minimal_config.go, spectest/mainnet/altair/epoch_processing/BUILD.bazel, spectest/mainnet/altair/finality/BUILD.bazel, spectest/mainnet/altair/fork_helper/BUILD.bazel, spectest/mainnet/altair/fork_transition/BUILD.bazel, spectest/mainnet/altair/operations/BUILD.bazel, spectest/mainnet/altair/rewards/BUILD.bazel, spectest/mainnet/altair/sanity/BUILD.bazel, spectest/mainnet/altair/ssz_static/BUILD.bazel, spectest/minimal/altair/epoch_processing/BUILD.bazel, spectest/minimal/altair/finality/BUILD.bazel, spectest/minimal/altair/fork/BUILD.bazel, spectest/minimal/altair/operations/BUILD.bazel, spectest/minimal/altair/rewards/BUILD.bazel, spectest/minimal/altair/sanity/BUILD.bazel, spectest/minimal/altair/ssz_static/BUILD.bazel
Fixed e2e tests for Altair to be green. 
```go
minimalConfig.ForkVersionSchedule = map[[4]byte]types.Epoch{
{0, 0, 0, 0}: 0, // Should have been {0, 0, 0, 1}
{1, 0, 0, 1}: math.MaxUint64,
}
```
Side changes, cleaned up `Fork()` implementation and ran gazelle which got changes from #9122
=> Green Altair e2e tests

tools/target_migration.bzl
Other
These messages are annoying when running `bazel build //...`
```
target '//beacon-chain:beacon-chain' is deprecated: This target has moved to //cmd/beacon-chain:beacon-chain
```
N/A - Cosmetic only
=> Bazel: set alias targets to manual only

validator/db/kv/attester_protection.go, validator/slashing-protection/cli_import_export_test.go, validator/slashing-protection/local/standard-protection-format/import_test.go, validator/slashing-protection/local/standard-protection-format/round_trip_test.go, validator/testing/protection_history.go
Bug fix
This bug led to an invalid assumption in PR #9120.
A user expects a fully populated AttestationRecord when calling AttestationHistoryForPubKey. 
The bug was that the public key was not populated in this method.
=> Return pubkey with AttestationHistoryForPubKey AttestationRecord response

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/log_test.go
This PR brings in `blockchain` pkg specific changes from `hf1` branch
- Added `ForkFetcher` to `ChainInfoFetcher` interface
- Updated `Test_logStateTransitionData` to use proper interface
=> Update log test and `ChainInfoFetcher` interface

beacon-chain/rpc/service.go
Use better alias names for importing in rpc `service.go`. I had a feeling the `XYZ2` was used due to auto import feature of goland
=> Better import alias names

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go, beacon-chain/sync/subscriber_sync_committee.go, beacon-chain/sync/subscriber_sync_contribution_proof.go, shared/bls/blst/public_key.go, validator/client/aggregate.go
No tracking issue. This PR resolves a few deep source warnings that make every branch targeting `hf1` red. This is due to unused code we have regarding eth1 data voting and a few other small deep source issues
=> Resolve Deep Source Warnings

beacon-chain/sync/validate_sync_committee_message.go, beacon-chain/sync/validate_sync_committee_test.go, beacon-chain/sync/validate_sync_contrbution_proof.go, beacon-chain/sync/validate_sync_contrbution_proof_test.go
This PR aligns sync committee (message/contribution) pipelines to alpha8. Change list:
- `hasSeenSyncMessageIndexSlot`'s key mixed with subcommittee index
-  removed has block and state requirement
- added more commentary of individual checks 
- added one more test case `is_syncing`, the general test coverages > 70%
=> Align sync committee pipelines to alpha8

beacon-chain/p2p/fork.go, beacon-chain/p2p/fork_test.go, shared/p2putils/fork.go, shared/p2putils/fork_test.go, shared/params/config.go, shared/params/mainnet_config.go
Cleanup
that we are using our fork schedule to determine the correct fork order, having this variables are a source on confusion. Therefore this PR removes them and fixes all usages to ultimately use our current fork schedule.
Fixes #
=> Remove Non Spec Config Variables

beacon-chain/blockchain/log.go, beacon-chain/operations/synccommittee/BUILD.bazel, beacon-chain/operations/synccommittee/contribution.go, beacon-chain/operations/synccommittee/message.go, beacon-chain/operations/synccommittee/metric.go, validator/client/sync_committee.go
Adding more metrics for saving sync committee message/contribution for the operation pool. This makes it easy to observe whether sync pipeline or sync validator duties are working as a whole
=> Add sync committee metrics for operation pool

beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/core/state/transition.go, beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go, beacon-chain/state/stategen/replay.go
This PR fixes a sync committee cache update bug. It now updates the cache at boundary slot - 1 and uses the block root at boundary slot - 1. Before it uses block root at boundary slot which introduces a subtle bug where the update cache and get cache have off by one
Note that I removed the update at fork boundary. This will be addressed in the next PR which we will implement fill on miss. This is absolutely needed due to restart
=> Update sync committee cache using block root at boundary slot - 1 

beacon-chain/core/helpers/BUILD.bazel, beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go
When using sync committee cache, and calling `IsCurrentEpochSyncCommittee` or `CurrentEpochSyncSubcommitteeIndices`, if there's a cache miss, we should fill the cache on the miss. This PR implements that functionality with a test.
Note: In test, I used a minor sleep (100ms) to ensure that go routine for the cache cache fill gets finished. Happy to hear whether there's a better solution for this
=> Sync committee cache: fill on miss

beacon-chain/core/helpers/rewards_penalties.go
This PR optimizes `TotalActiveBalance` by moving `SlotToEpoch(state.Slot()))` out side of the `ReadFromEveryValidator` loop. Every time `state.Slot()` is involved, it must obtain a beacon state read lock and that's obviously not efficient obtaining one instance of read lock for every validator (190k as of today)
=> Active balance: calculate epoch outside of loop

beacon-chain/core/altair/block.go, beacon-chain/rpc/prysm/v2/validator/BUILD.bazel, beacon-chain/rpc/prysm/v2/validator/proposer_test.go
This is an optimization PR over `runtime.assign`.   Whenever a node processes a block, it processes the `SyncAggregate` object. The node naively constructs a map that consists of every validator public key to every validator index in state. This is expensive and turns out to be unnecessary. The look up can be done individually via `state.ValidatorIndexByPubkey`. The saving here is removing 190k sized validator map and 190k lookups down to 512 lookups.
Before the fix:
After the fix:
=> Remove validator pubkey to index map

beacon-chain/operations/synccommittee/contribution.go, beacon-chain/operations/synccommittee/contribution_test.go, beacon-chain/operations/synccommittee/message.go, beacon-chain/operations/synccommittee/message_test.go, shared/queue/priority_queue.go, shared/queue/priority_queue_test.go
Sync committee object pool saves and retrieves objects using the priority queue. For retrieve, it uses the method `PopByKey`.  Using pop has an unintended consequence. By definition pop removes object on return and this does not fit our use case. In spec, there's multiple aggregators across multiple subcommittees. It means after aggregator at subcommittee 0 retrieve objects at slot N, it will empty the queue for slot N and leave aggregators at subcommittee 1,2,3 with nothing to aggregate.
To solve this we implement a new method `RetrieveByKey` for the priority queue. The method returns the object without removing the object from the queue.
Note: pool is still correctly getting pruned based on save. It gets trimmed after `syncCommitteeMaxQueueSize` is reached.
=> Sync committee pool can retrieve without pop

beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel, beacon-chain/rpc/prysm/v1alpha1/validator/aggregator_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/attester_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/exit_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/server.go, beacon-chain/rpc/prysm/v1alpha1/validator/server_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go, beacon-chain/rpc/service.go
Cleanup
v1alpha1 validator server's `BeaconDB` is not used anywhere outside tests, therefore it is safe to remove it.
=> Remove database field from v1alpha1 validator server

beacon-chain/core/altair/epoch_spec_test.go, beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go
`UpdateSyncCommitteeCache` returns error if latest block header's state root is zero hash. This implements an additional layer of defense to prevent callers corrupting the cache.
=> Disallow sync committee cache update if state root is 0s

shared/blockutil/BUILD.bazel, shared/blockutil/block_utils.go, shared/blockutil/block_utils_test.go
Add (signed) block header from block interface implementations. These are from `hf1` branch and I added the tests separately
=> Block util: block header from block interface

shared/testutil/assert/assertions.go, shared/testutil/assertions/BUILD.bazel, shared/testutil/assertions/assertions.go, shared/testutil/assertions/assertions_test.go, shared/testutil/require/requires.go
Other
Functionality to help us test copy methods and ensure that structs are not empty.
The idea behind this PR is that we may want some copy method that has hand written copy methods. If the underlying struct where ever extended to add new fields, the copy methods would no longer be a full copy. With these test assertions, we can write copy methods and assert that all fields are populate. In the event that new fields are added to some struct, tests will suddenly start failing as an indicator that the copy methods also need to be updated with the struct extensions.
=> testutil: Add NotEmpty method

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/pubsub.go, beacon-chain/p2p/pubsub_test.go, beacon-chain/p2p/service.go, beacon-chain/sync/BUILD.bazel, beacon-chain/sync/decode_pubsub.go, beacon-chain/sync/decode_pubsub_test.go, beacon-chain/sync/fork_watcher.go, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_test.go, beacon-chain/sync/subscription_topic_handler.go
Altair Hard Fork Work
the generated id. Due to this change some refactoring had to be carried out.
Part of #8638 
=> Fix Gossip Message ID Versioning

shared/copyutil/BUILD.bazel, shared/copyutil/cloners_test.go
Other
These copy methods had no tests!
The tests check that the copied object is equal to the original and that no fields are empty. Preventing empty fields is a future proofing method to alert developers that extending any struct requires changes to these cloner / copy methods.
=> shared/copyutil: Add tests for copy methods

validator/client/aggregate.go
Fix deep source complain of shadowing variable on `error error`
=> Fix deepsource: shadow of builtin detected

proto/prysm/v2/wrapper/beacon_block.go
Update Altair block wrapper's return to interfaces to sync with `hf1`
This change was introduced in #9173
=> Altair block wrapper: update return to interfaces

shared/testutil/BUILD.bazel, shared/testutil/block.go, shared/testutil/block_test.go
Adding functions to hydrate Altair versioned beacon blocks. These implementations are from the `hf1` branch
=> Hydrate altair block

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
Feature Flag Flip
reduce validator copies and therefore allocated heap usage.
N.A
=> Invert Optimized Balance Update Feature

beacon-chain/state/v2/BUILD.bazel, beacon-chain/state/v2/state_trie.go, beacon-chain/state/v2/state_trie_test.go
Adding v2's `InitializeFromProto` and `InitializeFromProtoUnsafe` from `hf1` to `develop`. I need these two functions to unblock the following:
- Move core processing deposits from `hf1` to `develop`
- Move testutil from` hf1` to `develop`. I can't do this until we have core processing deposits
=> State/v2: Add `InitializeFromProto` and `InitializeFromProtoUnsafe`

beacon-chain/core/blocks/attestation_regression_test.go, beacon-chain/core/blocks/attestation_test.go, beacon-chain/core/blocks/attester_slashing_test.go, beacon-chain/core/blocks/block_operations_fuzz_test.go, beacon-chain/core/blocks/deposit_test.go, beacon-chain/core/blocks/eth1_data_test.go, beacon-chain/core/blocks/exit_test.go, beacon-chain/core/blocks/proposer_slashing_regression_test.go, beacon-chain/core/blocks/proposer_slashing_test.go, beacon-chain/core/helpers/attestation_test.go, beacon-chain/core/helpers/block_test.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/core/helpers/randao_test.go, beacon-chain/core/helpers/rewards_penalties_test.go, beacon-chain/core/helpers/slot_epoch_test.go, beacon-chain/core/helpers/validators_test.go, beacon-chain/state/v1/BUILD.bazel, beacon-chain/state/v1/field_trie_test.go, beacon-chain/state/v1/getters_test.go, beacon-chain/state/v1/getters_validator.go, beacon-chain/state/v1/getters_validator_test.go, beacon-chain/state/v1/readonly_validator.go, beacon-chain/state/v1/readonly_validator_test.go, beacon-chain/state/v1/state_trie_test.go, beacon-chain/state/v1/types_test.go, beacon-chain/state/v1/validator_getters.go
Other
Required for Altair / hf1 branch. 
Key changes:
- v1.readOnlyValidator package private
- v1.NewValidator return the interface for ease of use
- v1.NewValidator returns an error when attempting to wrap a nil validator
- v1.(*BeaconState).ValidatorAtIndexReadOnly returns an error when trying to access a validator from a state with a nil slice for validators
GoImports punished me for some reason. :shrug:
=> beacon-chain/state/v1: ReadOnlyValidator wrapper constructor method

shared/params/mainnet_config.go
Update `hf1` branch to `beta.1` release, which updates target sync committee aggregators to 16 constant
Reference: https://github.com/ethereum/eth2.0-specs/releases/tag/v1.1.0-beta.1
=> Beta.1: update `TargetAggregatorsPerSyncSubcommittee` to 16

shared/featureconfig/config.go
Cleanup
Currently the same `Enabled feature flag` warning is displayed no matter if a flag is being enabled or disabled. The PR adds a new warning for disabling flags and introduces helper functions to avoid repeated code.
=> Log correct warning when disabling flags

beacon-chain/cache/sync_committee.go, beacon-chain/cache/sync_committee_disabled.go, beacon-chain/cache/sync_committee_test.go, beacon-chain/core/helpers/committee.go, beacon-chain/core/helpers/committee_test.go, beacon-chain/p2p/types/object_mapping.go, beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go, beacon-chain/rpc/prysm/v1alpha1/validator/assignments_test.go, beacon-chain/rpc/prysm/v2/validator/sync_committee.go
Fixed a bug when validator requests beacon node for duties at slot epoch boundary -1 (ie. every `N * SLOTS_PER_EPOCH-1`), beacon node incorrectly responds sync committee duties based on next period, instead of current period. The only time beacon node should respond based on next period is epochs per sync committee period multiply epoch boundary - 1 (ie. every `N * SLOTS_PER_EPOCH * EPOCHS_PER_SYNC_COMMITTEE_PERIOD-1`)
While fixing the bug, I also fixed much of the bad usage of terminology where `epoch` and `period` are mixed up
=> Fix next epoch sync duty calculation

endtoend/evaluators/validator.go, endtoend/minimal_e2e_test.go, validator/client/service.go
=> Enable Sync Evaluator For E2E

beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go, beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Bug fix
The `reqState` variable can be `nil` at certain times even if the underlying request didn't return an error which causes a runtime error. This PR fixes the issue by verifying that the value isn't `nil` 
Fixes #9161  
None.
=> v1alpha1 validators: catch possible reqState nil case

beacon-chain/blockchain/process_attestation_helpers.go
=> Use Only Checkpoint Cache for Processing Attestations

shared/featureconfig/flags.go
Cleanup
any user does run `--dev` there is no way to revert the changes from a bug in the new feature.
N.A
=> Remove Historical State Representation Flag From Dev

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go
Add head getters for validator index and public key. These are cheap and quick as it doesn't require a state copy for look up
This is used in altair and it is from #9123
=> Head: validator index getters

beacon-chain/node/node.go, beacon-chain/slasher/service.go, endtoend/BUILD.bazel, endtoend/components/beacon_node.go, endtoend/endtoend_test.go, endtoend/evaluators/finality.go, endtoend/evaluators/node.go, endtoend/evaluators/slashing.go, endtoend/evaluators/validator.go, endtoend/minimal_e2e_test.go, endtoend/slasher_e2e_test.go, endtoend/slasher_sync_e2e_test.go, endtoend/types/types.go
We believe there is a gap in slasher where if
(a) There are beacon nodes and validators running
(b) Some validator, `v`, produces an attestation before some epoch, `N`
(c) A beacon node with --slasher joins the network after epoch `N` and syncs the chain
(d) Validator `v` produces a slashable offense after epoch `N`
The slasher from part (c) did not join until after epoch `N`, therefore slasher did not have a record of validator `v` producing a slashable offense. This would mean slasher would **not** catch the offense from part (d). We believe this can be resolved by performing a backfilling routine from the epoch slasher syncs to minus `WEAK_SUBJECTIVITY_PERIOD` epochs to populate its history.
To prove this, we can start with an end-to-end test which demonstrates the scenario above. …
=> End-to-End Test Suite For Synced Slasher Node

.bazelrc, tools/ssz.bzl
Other
Since `--define=ssz=<value>` was changed in #9122, users may have been still using the old flag which has no effect or feedback.
=> Fail fast when using old define=ssz=<value>

beacon-chain/core/altair/BUILD.bazel, beacon-chain/core/altair/sync_committee.go, beacon-chain/core/altair/sync_committee_test.go, beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/broadcaster.go, beacon-chain/p2p/pubsub_filter.go, beacon-chain/p2p/sender.go, beacon-chain/p2p/service.go, beacon-chain/p2p/subnets.go, beacon-chain/sync/BUILD.bazel, beacon-chain/sync/fork_watcher.go, beacon-chain/sync/metrics.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/rpc_metadata_test.go, beacon-chain/sync/service.go, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_test.go, beacon-chain/sync/subscription_topic_handler.go, beacon-chain/sync/validate_beacon_blocks.go, beacon-chain/sync/validate_sync_committee_message.go, beacon-chain/sync/validate_sync_contrbution_proof_test.go, validator/client/sync_committee_test.go
Bug Fixes
As part of hardening prysm for the upcoming Altair hardfork, multiple short lived testnets were run with other clients. During the course of these testnets, some edge cases were revealed in prysm which would cause a lot of difficulties with regard to subscription/unsubscription at the fork boundary. This PR addresses the following issues.
Part of #8638 
=> General Interop Fixes

endtoend/evaluators/BUILD.bazel, endtoend/evaluators/metrics.go
Our current e2e test has some significant issues in the metrics evaluator, which checks for a difference between the head slot and the time-based slot. We had some flakiness as we were reading the time-based slot from a metrics file rather than computing it from the genesis time. This PR will hopefully reduce flakes in e2e.
=> More Precise Metrics E2E

beacon-chain/db/iface/interface.go, beacon-chain/db/slasherkv/BUILD.bazel, beacon-chain/db/slasherkv/pruning.go, beacon-chain/db/slasherkv/pruning_test.go, beacon-chain/db/slasherkv/slasher.go, beacon-chain/db/slasherkv/slasher_test.go
Part of #8331, this PR adds some latest key-value store methods, especially regarding pruning and fetching of slasher double votes, into the `develop` branch from current code in `feature/slasher`. This is part of an effort to reduce the final diff size of `feature/slasher` in preparation for Prysm v2.
These changes **DO NOT AFFECT** runtime, as the new slasher is not yet live.
The changes include:
- A much simpler way of pruning attestations and proposals now that the schema is simpler
- Efficient way of checking for proposer double votes using a better schema and concurrency
=> Add Latest Slasher KV Methods to DB Subpackage

beacon-chain/state/v1/state_trie.go
Optimisation
Assume `if fTrie.FieldReference().Refs() > 1` is true in `recomputeFieldTrie`.  If this is the case then `RecomputeTrie` is called on a different trie object (because of the reassignment `fTrie = newTrie`) and we can safely release the old trie object right after the reassignment. There is no need to wait for `recomputeFieldTrie` to complete.
Part of #8785
=> Reduce locking time in `recomputeFieldTrie`

beacon-chain/p2p/broadcaster.go, beacon-chain/p2p/broadcaster_test.go, beacon-chain/p2p/fork.go, beacon-chain/p2p/fork_test.go, beacon-chain/p2p/pubsub_filter.go, beacon-chain/p2p/pubsub_filter_test.go, beacon-chain/p2p/service.go, beacon-chain/rpc/eth/v1/beacon/BUILD.bazel, beacon-chain/rpc/eth/v1/beacon/config.go, beacon-chain/rpc/eth/v1/beacon/config_test.go, shared/p2putils/BUILD.bazel, shared/p2putils/fork.go, shared/p2putils/fork_test.go, shared/params/BUILD.bazel, shared/params/config.go, shared/params/loader.go, shared/params/loader_test.go, shared/params/mainnet_config.go, shared/params/minimal_config.go, shared/params/testnet_e2e_config.go
Altair Work
This updates the parameters to the latest ones introduced in the spec as of `v1.1.0-beta.2`. The biggest change is the change of
the target aggregators being increased to 16 from 4. This was introduced in `beta.1` .
For our changes in`p2putils`, the majority of the methods introduced are to help with fork versioning. These methods help determine the fork digest in a particular epoch, the fork digest in the next epoch, retrieving the fork data from a particular digest
and changes in our fork schedule structure to allow for a more accurate versioning scheme.
We also update our config with the merge and sharding specific parameters here to keep it in parity with how our current spec
configs are written. …
=> Update P2PUtils And Parameters From Altair

beacon-chain/p2p/service.go, beacon-chain/p2p/service_test.go
Other
Seeing an issue in altair-devnet-3 where the genesis time in p2p appears to be unset. This status error makes such a problem more obvious.
=> p2p: report status failure when no genesis time is set after start

shared/params/testnet_pyrmont_config.go
Add pyrmont fork version and epoch to config. Please cross check the values here:
https://github.com/eth2-clients/eth2-networks/pull/56/files
I left out values such as `INACTIVITY_SCORE_RECOVERY_RATE` and `CHURN_LIMIT_QUOTIENT`... because they are still the same as mainnet. The diff only reflected changes from config to preset based format
=> Add pyrmont hard fork config

beacon-chain/core/blocks/block_operations_fuzz_test.go, beacon-chain/state/v1/readonly_validator.go
Bug Fix
Previously in #7710, we had determined that declaring read only validators as pointers rather than the struct was a poor idea, as all these object end up on the heap and lead to more work being done by the gc. In our altair branch, we unfortunately 
reverted this change and it was merged into develop in #9221. This reverts the change back to our old format.
N.A
=> Change Back Read-Only Validator Declaration

beacon-chain/sync/initial-sync/round_robin.go
Other
Minor cosmetic fix. This prevents confusion about thinking the beacon node's head slot is the current slot.
N/A
=> Fix 'headSlot' log statement in init-sync

beacon-chain/rpc/apimiddleware/endpoint_factory.go
#9324 by mistake modified the struct type used for `/eth/v1/validator/beacon_committee_subscriptions` endpoint. This PR reverts the code back to the correct struct.
Fixes #9423
=> Fix struct type used when sending beacon committee subscriptions

WORKSPACE, beacon-chain/core/altair/epoch_precompute.go, beacon-chain/core/altair/epoch_precompute_test.go, spectest/mainnet/altair/random/BUILD.bazel, spectest/mainnet/altair/random/random_test.go, spectest/mainnet/altair/sanity/blocks_test.go, spectest/mainnet/phase0/random/BUILD.bazel, spectest/mainnet/phase0/random/random_test.go, spectest/mainnet/phase0/sanity/blocks_test.go, spectest/minimal/altair/random/BUILD.bazel, spectest/minimal/altair/random/random_test.go, spectest/minimal/altair/sanity/blocks_test.go, spectest/minimal/phase0/random/BUILD.bazel, spectest/minimal/phase0/random/random_test.go, spectest/minimal/phase0/sanity/blocks_test.go, spectest/shared/altair/sanity/BUILD.bazel, spectest/shared/altair/sanity/block_processing.go, spectest/shared/phase0/sanity/block_processing.go
This PR updates spec test to beta3 which included a new spec test format/folder `random`. While integrating the new spec test `random`, a bug was discovered where `ProcessEpochParticipation` processes flag indices for incorrectly marks **inactive** validators as true. In other words, for `get_unslashed_participating_indice`:
```python
active_validator_indices = get_active_validator_indices(state, epoch)
participating_indices = [i for i in active_validator_indices if has_flag(epoch_participation[i], flag_index)]
participating_indices = [i for i in state.validators if has_flag(epoch_participation[i], flag_index)]
```
Side note: `RunBlockProcessingTest` was refactored to use `folder_path` to it could be reused for `random` spec tests
Credit: Thanks @ralexstokes and team for the spec tests …
=> Update to spec test beta3

beacon-chain/core/altair/deposit_test.go, beacon-chain/core/blocks/deposit_test.go, beacon-chain/core/helpers/genesis.go, beacon-chain/powchain/deposit_test.go, beacon-chain/powchain/log_processing.go, beacon-chain/powchain/service.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/server_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go, shared/interop/generate_genesis_state.go, shared/interop/generate_genesis_state_test.go, shared/testutil/deposits.go, shared/testutil/deposits_test.go, shared/trieutil/sparse_merkle.go, shared/trieutil/sparse_merkle_test.go
=> Clean Up Sparse Merkle Trie

spectest/mainnet/altair/finality/BUILD.bazel, spectest/mainnet/altair/random/BUILD.bazel, spectest/mainnet/altair/sanity/BUILD.bazel, spectest/mainnet/phase0/finality/BUILD.bazel, spectest/mainnet/phase0/random/BUILD.bazel, spectest/mainnet/phase0/sanity/BUILD.bazel
In ci/cd, spectests are timing out 80% of the time. The 3 most common ones to timeout are `random`, `sanity` and `finality`
=> Spectest: increase sizes from small to medium

shared/gateway/api_middleware.go, shared/gateway/api_middleware_processing.go, shared/gateway/api_middleware_processing_test.go
Bug fix
grpc-gateway returns `{}` for successful POST responses with an `empty.Empty` return value. This has a length of 2 bytes, but we want to inform the client that the response length is `0` in such cases.
Fixes #9531
I also removed an unused param that Deepsource complained about.
=> Set `Content-Length` to zero for empty POST reponse

beacon-chain/node/node.go, beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel, beacon-chain/rpc/prysm/v1alpha1/validator/server.go, beacon-chain/sync/service_test.go
Misc changes from `hf1` to `devlop`. With this, there will be only `sync` and `endtoend` left from Altair
=> More misc altair changes

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
Adds a generic ProposeBeaconBlock function which can handle both Altair and phase 0 blocks using protobuf oneofs. This is important for hf1
=> Implement Generic ProposeBeaconBlock Function for RPC

beacon-chain/rpc/apimiddleware/BUILD.bazel, beacon-chain/rpc/apimiddleware/custom_hooks.go, beacon-chain/rpc/apimiddleware/custom_hooks_test.go, beacon-chain/rpc/apimiddleware/endpoint_factory.go, beacon-chain/rpc/apimiddleware/structs.go, shared/gateway/api_middleware.go
Feature
Adding the HTTP part of `GetBlockV2`: https://ethereum.github.io/beacon-APIs/#/Beacon/getBlockV2
Main thing to notice is that the example returns one of two version of the block in a way that is not in line with how gRPC returns `oneof` values. That's why a custom handler function was needed.
=> Align `GetBlockV2` to API HTTP spec

beacon-chain/rpc/apimiddleware/custom_hooks.go, beacon-chain/rpc/apimiddleware/custom_hooks_test.go, beacon-chain/rpc/apimiddleware/endpoint_factory.go, beacon-chain/rpc/apimiddleware/structs.go
Feature
Adding the HTTP part of `SubmitPoolSyncCommitteeSignatures`: https://ethereum.github.io/beacon-APIs/#/Beacon/submitPoolSyncCommitteeSignatures
Main thing to notice is that the example posted value is a top-level array, which is not supported by grpc-gateway. That's why a custom handler function was needed.
=> Align `SubmitPoolSyncCommitteeSignatures` to API HTTP spec

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
Feature
Flips feature for active balance cache to opt-out. 
This feature is required for testnet support and will be a requirement for v2.0.0.
=> Enable active balance cache

shared/featureconfig/config.go, shared/featureconfig/deprecated_flags.go, shared/featureconfig/flags.go
Flips feature to enable pruning of canonical attestation. This feature is required for testnet support and will be a requirement for v2.0.0.
=> Enable prune canonical attestation

beacon-chain/rpc/eth/validator/validator.go, beacon-chain/rpc/eth/validator/validator_test.go, proto/eth/v2/validator.proto
Other
After some discussion on Discord, it has been decided that `until_epoch` used in `PrepareSyncCommitteeSubnets` will be exclusive: https://github.com/ethereum/beacon-APIs/pull/165/files. This PR introduces the necessary changes.
Part of #7510
=> Make `until_epoch` exclusive in `PrepareSyncCommitteeSubnets`

beacon-chain/core/transition/transition_no_verify_sig.go, beacon-chain/core/transition/transition_no_verify_sig_test.go
`ProcessBlockNoVerifyAnySig` should fail early if beacon state and beacon block are on different version. Currently, it fails late until it processes attestations and ends up with a confusing error message such as `AppendCurrentEpochAttestations is not supported for hard fork 1 beacon state`... etc
=> Fail early if block and state are diff versions

.buildkite-bazelrc, hack/workspace_status_ci.sh
Other
Our continous integration uses a centralized cache server. However, many of the cache entries are missed when different agents have different STABLE stamp data.
This PR hardcodes these parameters such that the CI step can define `--config=nostamp` and have a much higher cache hit ratio.
N/A - should improve PR build times
=> CI: nostamp config for better cache hits

testing/endtoend/components/tracing_sink.go
Bug fix
When running the e2e test simultaneously (opposed to in parallel), the http server registers a global handler for "/" multiple times and leads to this panic.
```
panic: http: multiple registrations for /
goroutine 158739 [running]: 
net/http.(*ServeMux).Handle(0x1f86340, 0x16cc328, 0x1, 0x16eb840, 0xc000376550)
GOROOT/src/net/http/server.go:2464 +0x2c5
net/http.(*ServeMux).HandleFunc(...)
GOROOT/src/net/http/server.go:2501
net/http.HandleFunc(...)                                                       
GOROOT/src/net/http/server.go:2513
github.com/prysmaticlabs/prysm/testing/endtoend/components.(*TracingSink).initializeSink(0xc0001bc880)
testing/endtoend/components/tracing_sink.go:73 +0x36e
created by …
```
=> e2e: fix trace_sync http handler registration

testing/endtoend/minimal_e2e_test.go
Other
Previous release is still not Altair aware, so we can only run the long running e2e up to the 6th epoch. 
The environment variable for E2E_EPOCHS was overriding the hardcoded limitation for previous release and causing long running e2e to hang forever.
=> Fix long running e2e altair exception for previous release

cmd/beacon-chain/flags/base.go
Config Change
to target for a higher number of peers in a subnet.
N.A
=> Bump Up Peers In Subnet

beacon-chain/rpc/eth/beacon/blocks.go
Bug fix
Block v2 endpoints did not correctly handle errors when fetching a block. They always returned the `Internal` status code.
=> Fix error handing for block v2 endpoints

api/gateway/apimiddleware/api_middleware.go, beacon-chain/rpc/apimiddleware/custom_hooks.go, beacon-chain/rpc/apimiddleware/custom_hooks_test.go
Cleanup
- Adds a custom `RunDefault` type which is an alias for `bool`. This is done to improve readability.
- Unifies pre hooks, so that they can all specify whether to run the default logic. 
- Adds a missing unit test.
- Reorder `Endpoint` fields for better readability.
=> Small changes in API Middleware

beacon-chain/rpc/prysm/v1alpha1/validator/assignments.go
Other
The way we calculate the start epoch in `registerSyncSubnet` is semantically incorrect because we convert a period to an epoch, which doesn't make sense. It threw me off a little when doing some API work.
Related: https://discord.com/channels/476244492043812875/483017808658169866/882552736778973184
=> Correct the semantics of `startEpoch` calculation in `registerSyncSubnet`

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go
=> Check Head State For New Head Methods

beacon-chain/cache/committee.go
Cleanup
Removes an `fmt.Println` call from production code.
=> Remove `fmt.Println` from committee cache

WORKSPACE, config/params/loader_test.go, config/params/testnet_prater_config_test.go
Other
Updates spec test reference files to the latest release, [v1.1.0](https://github.com/ethereum/consensus-spec-tests/releases/tag/v1.1.0)
N/A
This also fixes params / config loader tests to test all of the spec values. Previously it was just checking the presets!
=> Update spectests to v1.1.0

beacon-chain/core/helpers/beacon_committee.go, beacon-chain/core/helpers/validators.go, beacon-chain/sync/validate_beacon_blocks.go
Cleanup
cache which is used everywhere across the repo.
N.A
=> Clean Up Proposer Cache

testing/endtoend/minimal_e2e_test.go
This PR allows tracing collection in end to end tests to function under test sharding done by bazel CI runners
=> Make Jaeger in E2E Sharding Aware

beacon-chain/db/slasherkv/slasher.go, beacon-chain/db/slasherkv/slasher_test.go
This PR prevents saving empty slasher chunks to disk, which would cause panic upon loading and decoding them later. It also adds a defensive err check when decoding.
=> Prevent Saving Empty Chunks to Disk

beacon-chain/slasher/service.go, beacon-chain/slasher/service_test.go
We noticed slasher goroutines share a single ticker for slots. The way channels work in Go is there will only be a single receiver that gets the tick from a single channel, so sometimes critical functionality of slasher may not be running on tick. This PR changes this so each goroutine has a unique slot ticker to always perform its responsibilities.
Evaluated using event feed subscriptions but it was overkill and could be fixed in fewer lines of code despite some more duplication.
=> Use Unique Slot Time Tickers for Slasher

WORKSPACE, tools/BUILD.bazel
Clean Up 
the images as we see fit instead of waiting for a it from upstream. 
Fixes #9674 
=> Pin Base Images 

beacon-chain/rpc/eth/beacon/validator.go, beacon-chain/rpc/eth/beacon/validator_test.go
Fixes #9721
Use balance instead of effective balance for `/eth/v1/beacon/states/{state_id}/validators` and `/eth/v1/beacon/states/{state_id}/validator_balances` end points
=> eth2 api: use balance instead of effective balance

api/gateway/gateway.go
V2.0.0 of Prysm migrated to using gorilla/mux instead of net/http for a default handler for our web UI and various aspects of our grpc gateway. Gorilla has a different way of handling wildcard paths compared to the stdlib. In gorilla, we need to do:
```
g.router.PathPrefix("/").HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
g.muxHandler(corsMux, w, r)
})
```
Instead of
```
g.router.HandlerFunc("/", func(w http.ResponseWriter, r *http.Request) {
g.muxHandler(corsMux, w, r)
})
```
This PR fixes the problem and allows the web ui to load
=> Web UI Fix for Prysm V2.0.0

crypto/bls/blst/signature.go
=> Bring Eth2FastAggregateVerify Inline With the Spec

validator/node/node.go
/v2/validator/health/version and all other health endpoints were gone in v2.0.0. During the grpc gateway refactor, the health endpoints were not registered in the validator client. This PR fixes the issue.
=> Health Endpoints Not Registered in Validator gRPC Gateway Fix

beacon-chain/state/fieldtrie/field_trie.go, beacon-chain/state/stateutil/trie_helpers.go, beacon-chain/state/stateutil/trie_helpers_test.go
Bug fix
There were two "MerkleizeTrieLeaves" that were nearly identical. 
The public method ensured that the hashlayer length was always a power of 2 while the private one did not. 
A follow up PR is to error check for chunkBuffer.Writer and verify that the static analysis for errcheck is working properly since these unhandled errors are not blocking/alerting users at build time.
N/A
This is a finding from Dr. Artem Vorobiev (artem@prysmaticlabs.com).
=> stateutil: Remove duplicated MerkleizeTrieLeaves method

WORKSPACE
This PR updates our prysm web UI checked-in assets to v1.0.1 https://github.com/prysmaticlabs/prysm-web-ui/releases/tag/v1.0.1. It is our first release in almost half a year thanks to the work from our new teammate, @james-prysm ! We are excited to bring an improved authentication experience and significant error fixes.
=> Update Prysm Web to Use v1.0.1

beacon-chain/cache/active_balance.go, beacon-chain/core/blocks/randao.go, beacon-chain/core/helpers/block.go, beacon-chain/core/helpers/randao.go, beacon-chain/state/phase0.go, beacon-chain/state/v1/getters_block.go, beacon-chain/state/v1/getters_randao.go, beacon-chain/state/v1/getters_state.go, beacon-chain/state/v2/getters_block.go, beacon-chain/state/v2/getters_randao.go, beacon-chain/state/v2/getters_state.go
Refactoring
As mentioned in https://github.com/prysmaticlabs/prysm/pull/9861#discussion_r743503630, `(...)AtIndex` functions should return `[32]byte` intead of `[]byte`. This PR updated these functions.
Part of #9820 
`go build ./...` is successful.
=> Return `[32]byte` from `(...)AtIndex` functions

beacon-chain/core/time/slot_epoch.go, beacon-chain/core/time/slot_epoch_test.go
This PR adds a helper to check if input slot is merge upgrade ready which satisfy the following condition:
`state.slot % SLOTS_PER_EPOCH == 0 and compute_epoch_at_slot(state.slot) == MERGE_FORK_EPOCH`
This helper is used will `ProcessSlots` as seen in Altair:
https://github.com/prysmaticlabs/prysm/blob/develop/beacon-chain/core/transition/transition.go#L262
=> time pkg: can upgrade to merge helper

WORKSPACE, config/params/loader_test.go
Non substantive. Just updating spec tests to v1.1.5 which consisted merge tests, there's nothing relevant for phase0 and altair but still good to bring in the diff into `develop` branch
=> Update spec tests to v1.1.5

proto/prysm/v1alpha1/validator-client/keymanager.proto
Removes unused import in `keymanager.proto`, gets rid of annoying warning every time when build:
`proto/prysm/v1alpha1/validator-client/keymanager.proto:9:1: warning: Import proto/prysm/v1alpha1/validator.proto is unused.`
=> Remove unused import

cmd/validator/slashing-protection/slashing-protection.go
Fixes #9905 by adding the --prater, --pyrmont, --mainnet flags to slashing protection exports. A user was mentioning that adding `--prater` to the slashing protection export command still logs "Running on Ethereum consensus mainnet" instead of prater. This is scary to a user.
=> Add Network Flags to Slashing Protection Export Command

cmd/validator/slashing-protection/export.go
Fixes #9897. The dappnode team was running into a curious issue where they were seeing an empty slashing protection history exported, as reported in #9897. They were running their validator with a command like this:
```
validator \
--prater \
--datadir=/root/.eth2 \
--wallet-dir=/root/.eth2validators \
--rpc-host 0.0.0.0 \
```
and then trying to export their slashing protection history with:
```
validator slashing-protection export --datadir=/root/.eth2validators
```
Note that they set their --datadir as `/root/.eth2` when running, which is different than what they are trying to export. They should have received some kind of warning if this was the case. This PR adds the necessary warning and explanation to users in case this situation happens.
**NOTE TO REVIEWERS**
Currently, if a …
=> Warn Users if Slashing Protection History is Empty

cmd/validator/slashing-protection/export.go
Resolves #9897, we finally confirmed and were able to reproduce the problem reported by the dappnode team where exporting their slashing protection history would result in an empty JSON history. This was because the wallet was created with an older version of Prysm that would place their `validator.db` in the top-level wallet directory. However, newer versions of Prysm create and use their `validator.db` in the wallet/direct or wallet/derived folder instead.
```
wallet/
validator.db # This is a faulty DB created in older versions of Prysm!
direct/
accounts/
all-accounts.keystore.json
validator.db # This is the correct DB
```
The problem and resolution was **confirmed** by the dappnode team today.
We issue a warning to users here and exit early instead:
```
No slashing protection data was …
```
=> Warn Users In Case Slashing Protection Exports are Empty

beacon-chain/monitor/process_attestation.go, beacon-chain/monitor/process_attestation_test.go
Testing on Prater at runtime move from 
`"Processed attestation aggregation" ValidatorIndex=2 prefix=monitor`
To
`""Processed attestation aggregation" BeaconBlockRoot=0x68656c6c6f2d Slot=1 SourceRoot:=0x68656c6c6f2d TargetRoot:=0x68656c6c6f2d ValidatorIndex=2 prefix=monitor`
=> Add verbosity to aggregation logs

beacon-chain/rpc/eth/beacon/sync_committee.go, beacon-chain/rpc/eth/beacon/sync_committee_test.go, beacon-chain/rpc/testutil/BUILD.bazel, beacon-chain/rpc/testutil/mock_genesis_timefetcher.go
=> Allow requests for next sync committee

validator/accounts/BUILD.bazel, validator/accounts/accounts_exit.go
Check if the beacon node is syncing before attempting to perform a voluntary exit as the current epoch will be wrong.
Fixes #9950
=> Check for syncstatus before performing a voluntary exit

validator/accounts/accounts_exit.go
In most cases, a simple error return string should not be capitalized.
https://programmerah.com/golang-warning-error-string-should-not-be-capitalized-or-end-with-punctuation-mark-29739/
=> Uncap error messages

beacon-chain/monitor/process_block.go, beacon-chain/monitor/process_block_test.go, beacon-chain/monitor/service_test.go
Adds an "aggregated since launch"  logging every 5 epochs. 
```
"Aggregated performance since launch" AttestationInclusion="80.00%" AverageInclusionDistance=1.2 BalanceChangePct="0.95%" CorrectlyVotedHeadPct="66.67%" CorrectlyVotedSourcePct="91.67%" CorrectlyVotedTargetPct="100.00%" StartBalance=31700000000 StartEpoch=0 TotalAggregations=0 TotalProposedBlocks=1 TotalRequested=15 TotalSyncContributions=0 ValidatorIndex=1 prefix=monitor
```
=> Monitor aggregated logs

beacon-chain/rpc/prysm/v1alpha1/validator/status.go, beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go
In the event all the keys provided to the rpc method have been recently observed, we choose to exit 
the method early. The reason this is done is because performing state regeneration is expensive 
and doing it for 2 states can take time. This allows validators to perform quicker restarts which is 
required when updating the validator client software. 
Additionally this PR also modifies a test case to check for this particular situation.
N.A
=> Faster Doppelganger Check

beacon-chain/rpc/service.go
Fix `gRPC client connected to beacon node` logging to exclude a typo `NewService`.
=> Fix grpc client connected... logging

validator/rpc/standard_api.go, validator/slashing-protection-history/export.go
As part of the validator keymanager API, in the `DeleteKeystores` endpoint: when we attempt to delete some keystores, say `a, b, c`, and a single keystore `b`, has an ERROR status when deleting, and `a, c` are deleted successfully, we only want to return slashing protection history for `a, c`. 
**NOTES**: The Prysm delete keystores underlying logic never returns an error, so it is not possible to add a unit test for this logic, unfortunately. Nevertheless, we should still implement the expected behavior.
=> Filter Errored Keys from Returned Slashing Protection History in Standard API

proto/eth/service/key_management.proto
Fixes the following warnings when Bazel build validators
```
proto/eth/service/key_management.proto:22:1: warning: Import proto/eth/v1/validator.proto is unused.
proto/eth/service/key_management.proto:23:1: warning: Import proto/eth/v2/validator.proto is unused.
```
=> Remove unused validator proto imports

beacon-chain/state/v1/field_roots.go, beacon-chain/state/v1/getters_state.go, beacon-chain/state/v2/field_roots.go, beacon-chain/state/v2/getters_state.go, beacon-chain/state/v3/field_roots.go, beacon-chain/state/v3/getters_state.go
Other
Adds a non-locking version of `ToProto` to avoid deadlocks when using the `stateRootHasher`.
Part of #9820
=> Create `toProtoNoLock` function

beacon-chain/rpc/prysm/v1alpha1/debug/p2p_test.go
Tests
`TestDebugServer_ListPeers` sometimes fails because the order of returned peers does not match test asserts. This change removes any assumptions about peer ordering.
=> Do not rely on peer order in `TestDebugServer_ListPeers`

math/math_helper.go, math/math_helper_test.go
Adds a safe math Sub64 method for uint64s in Prysm, brought up by @uncdr. We had safe add but no safe sub in Prysm to use generically
=> Add Safe Sub64 Method

.github/workflows/go.yml, crypto/bls/blst/signature.go, crypto/keystore/keystore.go, crypto/rand/rand.go, encoding/ssz/deep_equal.go, runtime/prereqs/prereq.go, testing/endtoend/components/beacon_node.go, testing/endtoend/components/boot_node.go, testing/endtoend/components/eth1.go, testing/endtoend/components/validator.go, testing/endtoend/helpers/helpers.go, tools/specs-checker/download.go, validator/accounts/wallet_recover.go
Gosec, one of our Github action workflows, changed a few hours ago with a release that had breaking changes. To resolve, we add justification to nosec rules defined in Prysm.
=> Add Justifications for Gosec Ignored

WORKSPACE
This PR Updates the web UI in Prysm to v1.0.2 released [here](https://github.com/prysmaticlabs/prysm-web-ui/releases/tag/v1.0.2)
=> Update Web UI Version to v1.0.2

beacon-chain/core/execution/upgrade.go
It's confusing that the import of `github.com/prysmaticlabs/prysm/beacon-chain/state/v3` has an alias to v2
=> Fix state alias v3

beacon-chain/rpc/eth/beacon/BUILD.bazel, beacon-chain/rpc/eth/beacon/sync_committee.go, beacon-chain/rpc/eth/beacon/sync_committee_test.go
In the back and forth to #9945 a bug was introduced in the logic to request future sync committees. This fixes that.
=> Fix sync commitee endpoint

beacon-chain/core/blocks/payload.go, beacon-chain/core/blocks/payload_test.go
`Transactions` and `ExtraData` are `List` when checking non-empty. Using nil is insufficient as they often come back as initialized and empty. This PR fixes it along with the unit tests
=> Update `Transactions` and `ExtraData` non empty check

api/gateway/apimiddleware/api_middleware.go
Bug fix
The `endpoint` variable is captured by the func returned from `WithMiddleware`, resulting in the same memory address being reused between API calls. This causes race conditions when multiple requests are issues simultaneously.
Fixes #10050
=> Do not reuse endpoint struct between API Middleware requests

testing/spectest/shared/altair/ssz_static/BUILD.bazel, testing/spectest/shared/altair/ssz_static/ssz_static.go, testing/spectest/shared/bellatrix/ssz_static/BUILD.bazel, testing/spectest/shared/bellatrix/ssz_static/ssz_static.go, testing/spectest/shared/common/ssz_static/BUILD.bazel, testing/spectest/shared/common/ssz_static/ssz_static.go, testing/spectest/shared/common/ssz_static/ssz_static_example_test.go, testing/spectest/shared/common/ssz_static/types.go, testing/spectest/shared/phase0/ssz_static/BUILD.bazel, testing/spectest/shared/phase0/ssz_static/ssz_static.go
Other
There was a ton of duplicated code across spectest for ssz static. This duplicated code is hard to maintain and will only get worse as more forks or phases are implemented.
This PR generalizes ssz static tests such that different phases or forks can reuse the same code to their advantage.
Part of investigation of #9402 and https://github.com/ferranbt/fastssz/issues/67
**Other notes for review**o
Test names for ssz_static now have a suffix to explain the type of code run, i.e. fastssz or custom HTR.
```
=== RUN   TestMainnet_Altair_SSZStatic/ssz_random/BeaconState/case_0
=== RUN   TestMainnet_Altair_SSZStatic/ssz_random/BeaconState/case_0/fastssz
=== RUN …
```
=> Spectests: Refactor ssz_static tests to deduplicate code and test custom HTR

beacon-chain/state/BUILD.bazel, beacon-chain/state/error.go, beacon-chain/state/state-native/v1/getters_validator.go, beacon-chain/state/state-native/v1/getters_validator_test.go, beacon-chain/state/state-native/v2/BUILD.bazel, beacon-chain/state/state-native/v2/getters_validator.go, beacon-chain/state/state-native/v2/getters_validator_test.go, beacon-chain/state/state-native/v3/BUILD.bazel, beacon-chain/state/state-native/v3/getters_validator.go, beacon-chain/state/state-native/v3/getters_validator_test.go, beacon-chain/state/v1/getters_validator.go, beacon-chain/state/v1/getters_validator_test.go, beacon-chain/state/v2/BUILD.bazel, beacon-chain/state/v2/getters_validator.go, beacon-chain/state/v2/getters_validator_test.go, beacon-chain/state/v3/BUILD.bazel, beacon-chain/state/v3/getters_validator.go, beacon-chain/state/v3/getters_validator_test.go
Refactor 
To increase DRY and enable DRY in tests and other users of the Beacon Chain state package,
an error that was duplicated unnecessarily in each version of the state is moved to the root
Beacon Chain state package.
Related and blocks #10047 
None
=> Move ErrNilValidatorsInState from one in each state version to a common one

beacon-chain/rpc/prysm/v1alpha1/beacon/server.go, beacon-chain/rpc/prysm/v1alpha1/validator/server.go, beacon-chain/rpc/prysm/v1alpha1/validator/server_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/status_test.go, beacon-chain/rpc/service.go
(cherry picked from commit 69a2ffd7c9f8ca1c67b4ea5aba71154ebc7713c2)
Cleanup
The `CanonicalStateChan` field is not used in any code path. It can be safely removed.
=> Remove `CanonicalStateChan`

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/head.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/rpc/prysm/v1alpha1/validator/sync_committee.go
Cleanup from #10020 
from the state and reduce the unnecessary copy. 
N.A
=> Use Better Head Info Fetcher

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/error.go, beacon-chain/blockchain/head.go, beacon-chain/blockchain/head_test.go, beacon-chain/blockchain/process_attestation_test.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/receive_attestation.go, beacon-chain/blockchain/receive_block.go, beacon-chain/blockchain/receive_block_test.go, beacon-chain/blockchain/service.go, beacon-chain/blockchain/service_test.go, beacon-chain/blockchain/store/BUILD.bazel, beacon-chain/blockchain/store/new.go, beacon-chain/blockchain/store/new_test.go, beacon-chain/blockchain/store/setter_getter.go, beacon-chain/blockchain/store/setter_getter_test.go, beacon-chain/blockchain/store/type.go, beacon-chain/blockchain/weak_subjectivity_checks_test.go
This PR replaces the newly implemented concurrent safe version of the blockchain store (#10118) in blockchain service. For the reviewers, please cross-check on there's no typo with the replacements (ie, justified, prev/best justified, finalized, and prev finalized)
=> Use store in blockchain service

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/new_slot.go, beacon-chain/blockchain/new_slot_test.go, beacon-chain/blockchain/receive_attestation.go
This PR implements the `on_tick` function in spec to reset the proposer boost and update the justified checkpoint. This is the last blocker before merging #10083
=> Add `on_tick` from spec

config/params/loader.go
=> Fix Checking of Minimal Preset

beacon-chain/blockchain/state_balance_cache.go, beacon-chain/blockchain/state_balance_cache_test.go
The state balance cache's `get` returns the cached balances when input root matches the cached root.  The cache is initialized with: 
```GO
balances []uint64
root     [32]byte
```
When someone inputs `[32]byte{}` the cache will return `[]uint64`. Such behavior is dangerous and could hide away edge cases. Instead, we should disallow returning a default value, and pass the default value to `update` to let it process or fail
=> State balance cache: handle input zeros

beacon-chain/node/node.go, beacon-chain/p2p/config.go, beacon-chain/p2p/connection_gater_test.go, beacon-chain/p2p/interfaces.go, beacon-chain/p2p/peers/scorers/block_providers.go, beacon-chain/p2p/peers/scorers/block_providers_test.go, beacon-chain/p2p/peers/scorers/service_test.go, beacon-chain/p2p/peers/status.go, beacon-chain/p2p/subnets.go, beacon-chain/p2p/testing/fuzz_p2p.go, beacon-chain/p2p/testing/mock_peermanager.go, beacon-chain/p2p/testing/p2p.go, beacon-chain/sync/initial-sync/blocks_fetcher_peers.go, beacon-chain/sync/initial-sync/blocks_fetcher_peers_test.go, beacon-chain/sync/initial-sync/blocks_fetcher_test.go, beacon-chain/sync/initial-sync/blocks_fetcher_utils_test.go, beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/initial-sync/service_test.go, beacon-chain/sync/rpc_beacon_blocks_by_range.go, beacon-chain/sync/rpc_beacon_blocks_by_range_test.go, beacon-chain/sync/subscriber.go, beacon-chain/sync/subscriber_test.go, cmd/beacon-chain/flags/base.go, cmd/beacon-chain/flags/config.go, cmd/flags.go
Bug Fix
This reverts commit 790bf031234f5bbd734fdb23f892e1041d293e4c.
urfave is unable to read `uint64` values from a yaml and is unlikely to ever support them anytime soon.
https://github.com/urfave/cli/issues/599
https://github.com/urfave/cli/issues/833
N.A
=> Revert "Replace a Few IntFlags with Uint64Flags (#9959)"

config/params/BUILD.bazel, config/params/loader.go, config/params/loader_test.go
Feature Helper
This is split off from #10020, @prestonvanloon mentioned earlier in https://github.com/prysmaticlabs/prysm/pull/10020#issuecomment-1024480859 that there was overlap between the yaml generation work in there and #10123 . This PR splits it out from the parent PR so that it can be reviewed separately and used. This PR allows a yaml file to be generated from a provided beacon config object. This is useful in e2e as we can provide other clients with a custom config.
N.A
=> Add Config To Yaml Function

beacon-chain/node/config.go, beacon-chain/node/config_test.go, beacon-chain/node/node.go, beacon-chain/rpc/eth/beacon/config_test.go, cmd/beacon-chain/flags/base.go, config/params/config.go
This PR adds a new beacon chain configuration flag `SafeSlotsToImportOptimistically`. It is user configurable via the beacon-chain CLI flag `safe-slots-to-import-optimistically`
=> Add SafeSlotsToImportOptimistically beacon configuration flag

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/receive_block.go, beacon-chain/powchain/execution_engine.go
This is a first take on enabling optimistically synced blocks. This PR modifies `onBlock` to continue even on failure from `ExecutePayload`. It also modifies the `onBlockBatch` to return a list of optimistic statuses on the block batch, and modifies the call site to save the synced tips accordingly
=> Sync optimistically candidate blocks

config/features/flags.go
Flag Addition
With #9717 being merged in, we can now add in our peer scorer to be part of our dev flags.
N.A
=> Add Peer Scorer to Dev Mode

cmd/validator/flags/flags.go, validator/node/node.go
Feature
I'd like to introduce a default list of ips to avoid cors issues for our validator to allow a default set of ports access to the validator's api. namely the use of port 4200 ( angular's default port) and port 3000 (react's default port)
=> default allowList for validator

validator/accounts/wallet_create_test.go, validator/keymanager/types.go
Bug fix
for the longest time, the wallet creation keymanager kind didn't match the type internally. introducing a fix to provide more flexibility while having backward compatibility for this keymanager kind check. users will be able to use the wallet creation more easily.
Fixes #10181
=> Keymanager-Kind: fix cli kind parsing and allow for backward compatability

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/testing/mock.go
This PR adds a variation fo already existing `IsOptimistic` method. The already present function check only if the head is optimistic, this can be used to check is other root,slot combination is optimistic also.
=> Adding a new method in HeaderFetcher

beacon-chain/powchain/BUILD.bazel, beacon-chain/powchain/engine-api-client/v1/client.go, beacon-chain/powchain/engine-api-client/v1/client_test.go, beacon-chain/powchain/options.go, beacon-chain/powchain/service.go, cmd/beacon-chain/flags/base.go, cmd/beacon-chain/main.go, cmd/beacon-chain/powchain/options.go, cmd/beacon-chain/powchain/options_test.go, cmd/beacon-chain/usage.go
This PR adds support for the engine API client via a flag `--execution-provider` in the beacon node. This exposes a getter called `EngineAPIClient()` in the powchain service. This client implement the `EngineCaller` interface defined as:
```go
type EngineCaller interface {
NewPayload(ctx context.Context, payload *pb.ExecutionPayload) (*pb.PayloadStatus, error)
ForkchoiceUpdated(
ctx context.Context, state *pb.ForkchoiceState, attrs *pb.PayloadAttributes,
) (*ForkchoiceUpdatedResponse, error)
GetPayload(ctx context.Context, payloadId [8]byte) (*pb.ExecutionPayload, error)
LatestExecutionBlock(ctx context.Context) (*pb.ExecutionBlock, error)
ExecutionBlockByHash(ctx context.Context, hash common.Hash) (*pb.ExecutionBlock, error)
}
```
=> Initialize the Engine API Client in the Beacon Chain's Powchain Service

beacon-chain/blockchain/optimistic_sync.go, beacon-chain/blockchain/service.go
In the event that there is an error reading synced tips from  DB  at launch or setting them in Fork Choice Store, do not stop the blockchain package from loading, just log the error and revert back to the last finalized state. Notice that most probably this error will surface somewhere else though. 
Credits to @rkapka for noticing that synced tips are not necessary for the node to function.
=> Do not stop on error loading synced tips

beacon-chain/forkchoice/protoarray/store.go, beacon-chain/forkchoice/protoarray/store_test.go
This PR fixes a bug in fork choice where we would consider canonical some orphaned blocks.
=> Fix updateCanonicalNodes

beacon-chain/powchain/engine-api-client/v1/client.go
`ForkchoiceUpdatedResponse` `Status` json tag should be `payloadStatus`, not `status` 
https://github.com/ethereum/execution-apis/blob/main/src/engine/specification.md#response-1
=> Fix `ForkchoiceUpdatedResponse` json tag

beacon-chain/powchain/engine-api-client/v1/client.go
This PR fixes a comment in our API client binding for engine_exchangeTransitionConfigurationV1 as specified in https://github.com/ethereum/execution-apis/pull/179
=> Small Comment Fix in Exchanging Transition Config

beacon-chain/blockchain/testing/mock.go
This PR adds an optimistic sync boolean to `IsOptimistic` for follow-up testing
Lint also made me reorder `ChainService` struct fields
=> Add opt sync bool to `IsOptimistic`

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go
The optimistic status will always be `false` until the merge happens. So we should just hard code return false for now with a `TODO`, and then we can merge PRs like #10274 into `develop.`
=> Update  `IsOptimistic ` to always false

beacon-chain/forkchoice/protoarray/optimistic_sync.go, beacon-chain/forkchoice/protoarray/optimistic_sync_test.go
We need to release the read lock before the return after reading `validatedTips`
=> Release lock before return `validatedTips`

validator/rpc/auth_token_test.go
Other
This test failed 30% of the time (30/100) due to the file change happening before the fs watcher go routine had a chance to monitor fs changes.
=> validator: Fix flaky test TestServer_RefreshJWTSecretOnFileChange

beacon-chain/state/stateutil/field_root_validator.go, config/features/flags.go
=> Disable Vectorized HTR from Our Dev Flag

testing/endtoend/components/beacon_node.go, testing/endtoend/mainnet_e2e_test.go, testing/endtoend/minimal_e2e_test.go, testing/endtoend/minimal_slashing_e2e_test.go, testing/endtoend/types/types.go
E2E Addition
Currently our E2E runs all our feature flags by default, however there are times when we do want our default path as a 'control' so that we can compare a beacon node running new features with our default one and make sure that both nodes can function side by side.
N.A
=> Allow E2E To Run Control Tests

async/multilock_test.go, beacon-chain/sync/service_test.go
Bug fix
The test is failing silently (while go test showing 'PASS') due to panic caused by feed type mismatch. As a result, intended testing logic is not exercised at all. There are a couuple fixes here:
1. fix the feed event type to be pointer
2. add seendCache to avoid nil pointer panic
3. fill block in beaconDB so validateBeaconBlockPubSub gets short cut
4. replace time.Sleep() with deterministic channel waiting
Fixes #
=> fix TestSyncHandlers_WaitTillSynced

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go
This PR fixes an old bug in prysm where we were applying proposer boost before inserting the block in fork-choice. This results in the proposer boost being ignored  if we update the weights between applying it and inserting the block. The new doubly linked tree approach loudly errors in this situation instead of ignoring the proposer boost. 
credits to @nisdas for raising the alarm and helping debugging this.
=> Boost proposer later

validator/client/validator_test.go
This test is flaky because it spawns a goroutine that may try to read from the db after it is closed. This change uses a channel to force the containing test method to wait until the goroutine finishes.
Bug fix
=> fix TestValidator_WaitForKeymanagerInitialization_Web race

validator/client/validator_test.go
Had an afterthought about #10343 - if one of the assert/requires in the goroutine fails, the channel might not get closed, which would make the test hang. This is safer.
Bug fix
=> this is safer if a goroutine require fails

beacon-chain/blockchain/optimistic_sync.go, beacon-chain/blockchain/optimistic_sync_test.go
There are two cases where we need to `validate_merge_block`:
1. When `is_merge_transition_block` returns true. This means beacon state contains an empty payload header and beacon block contains a non-empty payload
2. When beacon state is Altair version and beacon block contains a non-empty payload header
(2) is an extremely unlikely case but the protocol and the implementation should consider. This PR fixes (2) to make sure it actually validates instead of returning nil. I verified it successfully validates in local interop with Altair pre-state and non-empty payload block.
Reference: https://github.com/ethereum/consensus-specs/pull/2831
=> Handle pre state Altair with valid payload

beacon-chain/rpc/apimiddleware/custom_hooks.go, beacon-chain/rpc/apimiddleware/endpoint_factory.go, beacon-chain/rpc/apimiddleware/structs.go, beacon-chain/rpc/eth/validator/validator.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
This PR adds API middleware support for the fee recipient endpoint in Prysm for the standard API. This allows Prysm to support the API standard, which defines the endpoint using REST HTTP.
With this PR, one can now run:
```
curl -d '[{"fee_recipient": "0x9b984d5a03980d8dc0a24506c968465424c81dbe", "validator_index": 5}]' -X POST -H 'Content-Type: application/json' http://localhost:3500/eth/v1/validator/prepare_beacon_proposer
```
and it will update the fee recipients for execution payloads in Prysm
=> Add API Middleware Support for Fee Recipients Endpoint

beacon-chain/rpc/eth/debug/debug_test.go
Tests
There are no Bellatrix test cases for `GetBeaconStateV2` and `GetBeaconStateSSZV2`
=> Add missing tests to state retrieval

beacon-chain/blockchain/receive_attestation.go, beacon-chain/blockchain/receive_attestation_test.go
Notify the engine if head is changed after processing attestations mid slot. This ensures that optimistic status of the head slot is correct
=> Call FCU on update head after process attestation

beacon-chain/node/config.go, beacon-chain/node/config_test.go, cmd/beacon-chain/flags/BUILD.bazel, cmd/beacon-chain/flags/base.go, cmd/beacon-chain/main.go, cmd/beacon-chain/usage.go
Other
Part of #10292
renames fee-recipient flag to suggested-fee-recipient to match the validator client's name for the flag, also switches to use the burn address constant.
=> Fee recipient flag rename for beacon node

validator/client/validator_test.go, validator/node/node.go, validator/node/node_test.go
Bug fix
related to #10292
we wanted to rename prepare beacon proposer functions to fee recipient related to be clearer for internal use.
=> rename prepare beacon proposer to fee recipient 

validator/accounts/testing/mock.go, validator/client/service.go, validator/client/testutil/mock_validator.go, validator/client/validator.go, validator/client/validator_test.go, validator/client/wait_for_activation.go, validator/client/wait_for_activation_test.go, validator/node/node.go, validator/node/node_test.go
Bug fix
relates to #10404 
relates to #10292 
This pr improves the user experience of logs for fee recipients as well as prevents the validator client from sending anything to the beacon node if no flags are used from the validator client. The beacon node will continue to run with its own fee recipient values.
=> Fee Recipient : ux log fixes and prevent validator from calling beacon node if flags are not provided.

beacon-chain/rpc/eth/helpers/sync.go
Bug fix
Correct HTTP response when sync validation routine fails. Bug fix for #10420.
Fixes #10420
=> fix issue #10420

beacon-chain/rpc/service.go
Fixes the following panic
```
time="2022-03-24 20:05:16" level=error msg="gRPC panicked!" error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 903228 [running]:
runtime/debug.Stack()
GOROOT/src/runtime/debug/stack.go:24 +0x65
github.com/prysmaticlabs/prysm/monitoring/tracing.RecoveryHandlerFunc({0xb17a98, 0xc0101cec90}, {0x3b8200, 0x2bfe9a0})
monitoring/tracing/recovery_interceptor_option.go:29 +0x1f7
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0xb17a98, 0xc0101cec90}, {0x3b8200, 0x2bfe9a0}, 0xc005b8b3a8)
external/com_github_grpc_ecosystem_go_grpc_middleware/recovery/interceptors.go:61 +0x36
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1() …
```
=> Properly initialize replayer builder for rpc

beacon-chain/blockchain/service.go
Before the first finalized epoch, the finalized root may be zeros in some places. This ensures that we don't pass in zeros to get the finalized block in DB
=> Ensure finalized root can't be zeros

api/client/beacon/BUILD.bazel, api/client/beacon/checkpoint.go, api/client/beacon/checkpoint_test.go, api/client/beacon/client.go, api/client/beacon/client_test.go, api/client/beacon/doc.go, api/client/beacon/errors.go, beacon-chain/core/helpers/weak_subjectivity.go, beacon-chain/core/helpers/weak_subjectivity_test.go, beacon-chain/rpc/eth/beacon/blocks.go, cmd/prysmctl/BUILD.bazel, cmd/prysmctl/checkpoint/BUILD.bazel, cmd/prysmctl/checkpoint/checkpoint.go, cmd/prysmctl/checkpoint/latest.go, cmd/prysmctl/checkpoint/save.go, cmd/prysmctl/main.go, go.mod, network/forks/errors.go, network/forks/ordered.go, network/forks/ordered_test.go
Feature
This PR adds a client library for interacting with the beacon node api. This lib is still very incomplete and mostly only covers the methods needed to support checkpoint sync. Also included is a cli tool called `prysmctl`. This is intended as a kubectl style cli toolbox for interacting with the beacon node api, starting with methods for querying for a weak subjectivity checkpoint, or saving the state and block needed to perform a checkpoint sync.
=> Checkpoint Sync 3/5 - beacon node api client lib and prysmctl cli tool

crypto/bls/blst/BUILD.bazel, crypto/bls/blst/public_key.go
Cleanup
The ristretto Cache requires strings as keys, this requires an expensive byte to string conversion each time we want to retrieve the decompressed public key. This PR uses an LRU cache instead and uses the public key in its `[48]byte` form as the key. This has a few advantages, we don't have to allocate a public key string each time we want to access the decompressed public key. 
This is done by taking advantage of a new addition in go 1.17 which allows us to cast an array from a slice provided the slice is of the appropriate size. This is checked at the start of the function, where we make sure that the slice is of the correct size. Given that doing this is essentially zero-cost, this is more memory efficient …
=> Remove Ristretto Cache For Public Keys

validator/client/metrics.go
=> Add Balance Read Lock When Aggregating Validator Metrics

proto/engine/v1/json_marshal_unmarshal.go, proto/engine/v1/json_marshal_unmarshal_test.go
Execution block's base fee per gas marshal / unmarshal uses the incorrect endianness. This PR fixes it and improves upon the test
=> Fix execution block's base fee endianness marshal/unmarshal

testing/spectest/mainnet/altair/finality/BUILD.bazel, testing/spectest/mainnet/altair/fork_transition/BUILD.bazel, testing/spectest/mainnet/altair/forkchoice/BUILD.bazel, testing/spectest/mainnet/altair/random/BUILD.bazel, testing/spectest/mainnet/altair/sanity/BUILD.bazel, testing/spectest/mainnet/bellatrix/finality/BUILD.bazel, testing/spectest/mainnet/bellatrix/fork_transition/BUILD.bazel, testing/spectest/mainnet/bellatrix/forkchoice/BUILD.bazel, testing/spectest/mainnet/bellatrix/sanity/BUILD.bazel, testing/spectest/mainnet/phase0/finality/BUILD.bazel, testing/spectest/mainnet/phase0/forkchoice/BUILD.bazel, testing/spectest/mainnet/phase0/random/BUILD.bazel, testing/spectest/mainnet/phase0/sanity/BUILD.bazel, testing/spectest/minimal/altair/forkchoice/BUILD.bazel, testing/spectest/minimal/bellatrix/forkchoice/BUILD.bazel, testing/spectest/minimal/phase0/forkchoice/BUILD.bazel, testing/spectest/shared/common/ssz_static/BUILD.bazel
Other
Marking forkchoice tests as "enormous" so that bazel knows these tests need at least 800mb of RAM. This will allow bazel to better schedule jobs on the host machine. I.e. if the host only has 2Gb of RAM, but 8 cores CPU then it would only schedule at most 3 enormous jobs in parallel.
This may result in slightly longer CI runs but the overall flakes should be reduced.
=> Spectest: Improve test size and timeouts

beacon-chain/powchain/BUILD.bazel, beacon-chain/powchain/check_transition_config.go, beacon-chain/powchain/check_transition_config_test.go
Logs terminal total difficulty status on per `checkTransitionPollingInterval`. This is useful to find out how far we are away from reaching the terminal total difficulty 
```
[2022-03-30 09:06:10]  INFO powchain: Total terminal difficulty has not been reached yet latestTTD=6 transitionTTD=10
```
=> Log terminal total difficulty status

beacon-chain/rpc/apimiddleware/structs.go
Bug fix
Corrects field names in `executionPayloadJson` and `executionPayloadHeaderJson`. Current names are out of date.
Fixes #10460
=> Fix execution payload field names in API Middleware

beacon-chain/rpc/prysm/v1alpha1/beacon/validators.go, beacon-chain/rpc/prysm/v1alpha1/beacon/validators_test.go
Fixes #10411
Prysm RPC end points `GetValidatorPerformance` and `GetIndividualVotes` should consider Bellatrix state
=> RPC: GetValidatorPerformance for Bellatrix

beacon-chain/cache/depositcache/deposits_cache.go, beacon-chain/cache/depositcache/deposits_cache_test.go, beacon-chain/deterministic-genesis/service.go, beacon-chain/powchain/service_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_deposits.go
Fixes Potential Race Condition
In the event our finalized trie changes in between fetching it and fetching our non-finalized deposits we would retrieve the wrong set of non-finalized deposits. This PR fixes that by fetching the deposits via their canonical index.
N.A
=> Fetch Non Finalized Deposits Better

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
Bug Fix
Previously we were inserting deposits into our finalized trie via our deposit count(voted eth1data) instead of the eth1 deposit index in the state. The side effect of this is that when we do try to fetch non-finalized deposits for our trie we end up using the wrong merkle index, which leads to us fetching insufficient deposits in order to complete the whole trie in the event our deposit count(from voted eth1data) does not match up with the eth1 deposit index in the state. This can lead to proposers rebuilding the trie in periods where there are a lot of large amount of deposits being added in.
Fixes #10156 and Resolves #10120
=> Fix Nasty Finalization Bug

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/receive_attestation.go
Check if a node is canonical in forkchoice before calling dbase.
=> Use forkchoice first when checking canonical status

beacon-chain/cache/depositcache/deposits_cache.go, beacon-chain/cache/depositcache/deposits_cache_test.go
Bug Fix
Following on from #10511 , we harden our finalized deposit insertion method here. Some edge cases can be hit in the event the node is still waiting to fetch new deposit logs from its eth1 node and is processing blocks normally. This makes sure that we never revert the trie back to an older state, and only finalize as many deposits as there are stored in our deposit cache. 
Resolves #10156 and fixes #10120
=> Handle Finalized Deposit Insertion Better

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_attestations_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_utils_bench_test.go, config/features/config.go, config/features/deprecated_flags.go, config/features/flags.go
=> Remove Proposer Selection Feature

validator/client/validator.go, validator/client/validator_test.go
Bug fix
related to #10489
the suggested fee recipient flag was not working correctly and did not properly warn the user even though it was not working correctly. This PR aims to fix the usage of this flag. Also updated unit tests to better catch these in the future.
=> Suggested Fee Recipient : bug fix

beacon-chain/p2p/peers/scorers/peer_status.go
(cherry picked from commit e04e4795c81ea939cf8996c632c52598cd69d170)
Bug fix
`PeerStatusScorer.SetHeadSlot` is an exported function, but it does not lock the store.
Fixes #10530
=> Add lock to `PeerStatusScorer.SetHeadSlot`

testing/endtoend/components/eth1/miner.go, testing/endtoend/components/eth1/node.go, testing/endtoend/components/eth1/transactions.go
=> Fix Transaction Pool in E2E

beacon-chain/sync/validate_beacon_blocks.go
I think the proposer index and graffiti would be helpful to fields to have along side `Received block...` log to monitor where the late blocks were coming from. Other client implementation have these which made debugging useful as seen during interop event
=> Add proposer index and graffiti to received block log

beacon-chain/powchain/rpc_connection.go, beacon-chain/powchain/service.go
Bug Fix
#10498 introduced some changes in our `powchain` service in order to adapt it for the merge. However a poll routine was introduced which did not cleanup discarded connections correctly. This PR fixes it here along with any other places where there was improper cleanup.
Fixes #10573 
=> Cleanup Discarded Connections Correctly

consensus-types/primitives/BUILD.bazel, consensus-types/primitives/epoch.go, consensus-types/primitives/epoch_test.go
Brings the MaxEpoch helper function from eth2-types so we can rely less on the dependency and remove it in a follow-up PR
=> Max Epoch Helper from Eth2-Types

beacon-chain/sync/initial-sync/service.go, beacon-chain/sync/initial-sync/service_test.go
Bug fix
Reverts problematic PR #10523 and add a comment on why we spin up a goroutine in the service's constructor. 
Fixes #10602
=> Revert "Simplify Initial Sync (#10523)"

README.md
We are on: https://github.com/ethereum/consensus-specs/tree/v1.1.10
=> Update consensus spec version to v1.1.10

beacon-chain/powchain/engine_client.go
Thanks to SeaMonkey for this feedback. When engine API connection fails due to being unauthorized, users see this scary log:
```
got an unexpected error: 401 Unauthorized: Unauthorized: Error: Missing auth header
could not process block in batch
github.com/prysmaticlabs/prysm/beacon-chain/blockchain.(*Service).ReceiveBlockBatch
beacon-chain/blockchain/receive_block.go:84
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processBatchedBlocks
beacon-chain/sync/initial-sync/round_robin.go:283
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).processFetchedData
beacon-chain/sync/initial-sync/round_robin.go:133
github.com/prysmaticlabs/prysm/beacon-chain/sync/initial-sync.(*Service).syncToFinalizedEpoch …
```
=> More Useful Log When Auth Fails to Execution Client

testing/spectest/shared/common/forkchoice/BUILD.bazel, testing/spectest/shared/common/forkchoice/builder.go, testing/spectest/shared/common/forkchoice/builder_test.go, testing/spectest/shared/common/forkchoice/runner.go, testing/spectest/shared/common/forkchoice/service.go
Other
Refactored the forkchoice test parts to a "builder" that wasn't so specific to the yaml ingestion.
This reduces the cognitive score of the forkchoice runner and allows for different sources of information to be used.
The end goal is to use this builder for black box fuzzing.
=> Spectest: refactor forkchoice helper

beacon-chain/sync/initial-sync/round_robin.go
I missed one comment from #10592, here we can avoid one DB lookup in the event `s.cfg.Chain.HeadSlot() >= blk.Block().Slot()`
https://github.com/prysmaticlabs/prysm/pull/10592/files#r862913776
=> Fix `isProcessedBlock` order of operation

api/client/beacon/checkpoint.go, api/client/beacon/client.go, api/client/beacon/client_test.go, beacon-chain/db/kv/finalized_block_roots.go, beacon-chain/db/kv/wss_test.go
Bug fix
This fixes a couple bugs in the checkpoint sync implementation. 
- block file naming
- fix node version regex that only worked for prysm node versions
- fix checkpoint block finalization bug
Fixes #10617
Some of these fixes were split off from PR #10387 - that PR will be reduced in scope.
=> Checkpoint sync fixes

beacon-chain/blockchain/process_block.go, testing/endtoend/endtoend_test.go, testing/endtoend/minimal_e2e_test.go, testing/endtoend/types/types.go
Bug fix
This changes `handleEpochBoundary` so that it runs the equivalent of `process_slots` on the BeaconState before caching committee data. This fixes an issue where we cache incorrect shuffled and sorted validator indices for subsequent epochs, leading to a mismatch of the proposer index when running in E2E, due to the low value for MAX_SEED_LOOKAHED.
This PR runs process_slots on the BeaconState at the epoch boundary before calling `UpdateCommitteeCache`. This ensures that the validator registry has been updated so that the list of activation eligible validators matches what will be seen in the epochs to be cached. 
Fixes #10638
=> run process_slots before caching committee data

beacon-chain/db/kv/genesis_test.go, beacon-chain/db/kv/wss_test.go, beacon-chain/state/genesis/genesis.go, beacon-chain/state/genesis/genesis_test.go, config/params/BUILD.bazel, config/params/mainnet_config.go, config/params/minimal_config.go, config/params/registry.go, config/params/testnet_e2e_config.go, config/params/testnet_prater_config.go, config/params/values.go, encoding/ssz/detect/configfork_test.go, network/forks/ordered_test.go, validator/accounts/accounts_exit.go
Other
- cleanup
This is just a small tidy up PR, replacing ConfigName custom type with regular old strings to remove some convoluted reverse mapping operations and make things simpler.
=> simplify config names, use strings

beacon-chain/powchain/log_processing.go, beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
Some clients might take longer to respond with the request headers. The http client can time out before that time period, in order to allow different clients to run smoothly we dynamically adjust batch sizes depending so that we can come to an appropriate request size so that the connected eth1 client can respond in time.
N.A
=> Perform Request Size Limiting When Caching Eth1 Headers

testing/endtoend/evaluators/validator.go
E2E Improvement
During the bellatrix fork epoch at the merge block, the initial Execution engine calls can take a while. This might lead to validators not attesting the merge block in time, leading to lower participation. 
N.A
=> Fix Multiclient E2E Runs

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go
We want to update the head, we don't want to return nil in most cases. This PR added a regression test for log:
```go
require.LogsDoNotContain(t, logHook, "New head does not exist in DB. Do nothing")
```
=> Don't return nil with new head

beacon-chain/sync/BUILD.bazel, beacon-chain/sync/subscriber_beacon_blocks.go, beacon-chain/sync/subscriber_beacon_blocks_test.go
`error.Is` should be used as `func Is(err, target error)` but we had it `(target, err error)` This PR fixed it and added a unit test
=> Fix `error.Is` ordering

beacon-chain/sync/validate_beacon_blocks.go, beacon-chain/sync/validate_beacon_blocks_test.go
Bug fix
In the file `validate_beacon-locks-test.go` there were a number of test cases that were passing for the wrong reasons.
This branch fixes the tests that were passing despite an error in `decodePubsubMessage` and fixes the passing requirements by including the correct expected errors and validation decisions.
This ensures that the tests pass for the right reasons and in the future, if they break, that it is caught early.
Additionally a couple tests were renamed to better describe what they are testing.
Fixes #9791
I was unable to fully check whether the tests for valid blocks are passing for the right reasons.
=> Fix Tests in sync/validate_beacon_blocks.go to Pass for the Right Reasons

testing/endtoend/endtoend_test.go, testing/endtoend/minimal_e2e_test.go
Bug fix
Reverts a change to run for extra epochs in e2e tests.
Fixes #10716
=> run e2e for 12 epochs

beacon-chain/slasher/service.go
Slasher was panicking sometimes as we would close a channel used for chainstart notifications when another service would try to send over the channel. This fixes the issue as an unsubscribe from the feed is sufficient
=> Fix Slasher E2E Flakiness

testing/endtoend/evaluators/validator.go
=> Drop Down Expected Sync Participation During Fork

beacon-chain/core/validators/BUILD.bazel, beacon-chain/core/validators/validator.go, beacon-chain/core/validators/validator_test.go, testing/spectest/shared/altair/epoch_processing/registry_updates.go, testing/spectest/shared/bellatrix/epoch_processing/registry_updates.go, testing/spectest/shared/phase0/epoch_processing/registry_updates.go
Ensures withdrawal epoch doesn't overflow. Part of spec test updates to `v1.2.0-rc.1` 
Please merge this before #10665
=> Fix withdrawal epoch overflows

.buildkite-bazelrc
Other
This resolves the following error in CI.
```
java.io.IOException: Symlinks in action outputs are not yet supported by --experimental_remote_download_outputs=minimal
```
See https://github.com/bazelbuild/bazel/issues/13355
=> Update .buildkite-bazelrc: change CI to use toplevel remote caching.

beacon-chain/sync/validate_beacon_attestation.go
Per @nisdas 's comment on https://github.com/prysmaticlabs/prysm/pull/10674#discussion_r880105767
We should copy byte slices before setting them as cache keys in case protobuf unmarshalling creates unintended mutations
=> Sync: use copied bits for seen cache

validator/node/node.go
Bug fix
Using error templating ensures the flag name is not incorrect in the error message. 
It was incorrect prior to this change.
=> Fix error message with incorrect flag names

beacon-chain/blockchain/process_block.go, beacon-chain/powchain/engine_client.go
When testing out merge UX, came across a few error logs that pop up if an execution client goes offline while Prysm is operational. Many of these did not print anything useful, and would just pollute the screen with stack traces that do not help us. As these are RPC errors, fmt.Errorf is sufficient
=> Remove Unnecessary Stack Traces for Engine Errors

testing/endtoend/components/eth1/miner.go, testing/endtoend/components/eth1/node.go
Bug Fix
Currently we wrote both `stdout` and `stderr` logs to the same file, this introduced a race where it was possible for both these separate log processes to overwrite each other. This introduced possibilities where important logs went missing and led to E2E flakes.
Fixes #10718 
=> Write To Only One File For Geth Logs

beacon-chain/blockchain/error.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
The function `fillInForkChoiceMissingBlocks(ctx, blk, finalizedChkpt, justifiedChkpt)` obtains from DB all blocks starting from the parent of `blk` and goes up the parent chain. It inserts all blocks with slots higher than the last finalized checkpoint plus the parent of the last such slot.
This function does not check that this last parent is the finalized block, if it isn't then the function inserts a contending chain to the finalized block and it should be declared invalid.
In addition, this function has an off-by-one in which it passes also the finalized block to forkchoice, all tests for this functions were wrongfully counting nodes adding the extra finalized checkpoint that should not have been saved.
=> Do not fill in blocks that are not in the finalized branch

.github/workflows/go.yml, crypto/bls/blst/stub.go, fuzzbuzz.yaml
Bug Fix
In the event any of our fuzz targets use our blst library, they will panic and fail with this:
```
panic: blst is only supported on linux,darwin,windows
```
This PR fixes it by allowing fuzz targets to run with blst and adding test support for our fuzz targets in our github workflow.
N.A
=> Fix Fuzzing

beacon-chain/powchain/block_reader.go, beacon-chain/powchain/service.go, beacon-chain/powchain/service_test.go
=> Add Back Timestamp Related Deposit Processing

beacon-chain/blockchain/metrics.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/service.go
This fixes #10797
This PR implements a routine to check if there's a proposer at the next slot without payload ID cached. If there is, then we call fcu w/ payload attribute to cache the payload ID. 
I'll test this in kiln prod for a few days
=> Fill missing payload ID

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/service.go
Only prune on init sync if the new finalized epoch is higher than the one in forkchoice. 
This can happen when just launching a node with a finalized state at slot `32 N`, when processing the batch `32 N + 1 .. 32 (N+1)` the node will attempt to prune `32 (N-1)` which is not in forkchoice at startup.
=> Only prune in newer finalization

README.md
Update main readme labels to:
https://github.com/ethereum/execution-apis/tree/v1.0.0-alpha.9/src/engine
https://github.com/ethereum/consensus-specs/tree/v1.2.0-rc.1
=> Update spec labels

beacon-chain/core/helpers/rewards_penalties.go, beacon-chain/core/helpers/rewards_penalties_test.go
`get_total_balance` should return `EFFECTIVE_BALANCE_INCREMENT` as the minimum to avoid divisions by zero. This is outlined in the spec
=> Active balance: return `EFFECTIVE_BALANCE_INCREMENT` as min

beacon-chain/core/epoch/precompute/justification_finalization.go, beacon-chain/core/epoch/precompute/justification_finalization_test.go
Assume the following scenario:
`slot`: `95`
`current_target_balance`: `EFFECTIVE_BALANCE_INCREMENT`
`previous_target_balance`: `EFFECTIVE_BALANCE_INCREMENT`
`total_active_balance`: `100 * EFFECTIVE_BALANCE_INCREMENT`
`justification_bits`: `0011`
`state.current_justified_checkpoint.epoch`: `2` 
The above is an impossible scenario unless the client has a bug in manipulating `justification_bits` or `target_balance` calculations because they don't align. In an event of such, we should not allow the updating of the justified checkpoint epoch to a lower number. Prysm looks at `justification_bits` to update checkpoint whereas spec looks at `target_balance` to update checkpoint. They all work but prysm should add on an additional safety filter to disallow epoch to be updated lower than existing …
=> Disallow lower justified epoch to override higher epoch

api/gateway/gateway.go, monitoring/prometheus/service.go, monitoring/prometheus/simple_server.go, testing/endtoend/components/tracing_sink.go, testing/middleware/engine-api-proxy/proxy.go
In my other PR, I received a bunch of complaints: `G112 (CWE-400): Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server`
I set one-minute timeout in this PR for http.Server during init. I don't feel strongly about the value. I think one minute should be sufficient but please tell me otherwise 
Source: https://github.com/prysmaticlabs/prysm/runs/6869199767?check_suite_focus=true#step:4:1980
=> Fix gosec scan: G112 (CWE-400) Potential Slowloris Attack 

testing/assertions/assertions.go
Fix `ErrorIs` message. I don't think the message `not in chain` was suppose to be part of it
=> Fix message typo for `ErrorIs`

beacon-chain/blockchain/weak_subjectivity_checks.go
Bug fix
Re-words the info message that is displayed when prysm is started without a specified weak subjectivity checkpoint.
Fixes #10848
=> update info message about ws checkpoint

api/client/builder/types.go, api/client/builder/types_test.go
Pad `Uint256`'s `SSZBytes` to length 32 to make ssz happy. Thanks @kasey for the pointer
=> Pad `Uint256`'s `SSZBytes` to length 32

beacon-chain/blockchain/execution_engine_test.go, beacon-chain/blockchain/receive_block_test.go, time/slots/slottime.go
This PR changes a downcast from uint64 to int64 in `CurrentSlot` for the safer `int64 --> uint64`. The changed tests (which relied on the bad downcasting behavior) serve as regression tests.
=> Do not downcast time in currentslot

beacon-chain/blockchain/process_attestation_test.go, beacon-chain/blockchain/process_block.go, beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go, beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go, beacon-chain/forkchoice/doubly-linked-tree/store.go, beacon-chain/forkchoice/doubly-linked-tree/store_test.go, beacon-chain/forkchoice/doubly-linked-tree/vote_test.go, beacon-chain/forkchoice/interfaces.go, beacon-chain/forkchoice/protoarray/store.go, beacon-chain/forkchoice/protoarray/store_test.go, beacon-chain/forkchoice/protoarray/vote_test.go
Continue the cleanup of blockchain package: now that we track correct finalized and justified checkpoints on forkchoice, we can prune within it and remove the exported function. 
Part of #10734 
Note to reviewers: review only after #10840  has been merged. 
Fixes #10899
=> Prune within forkchoice

beacon-chain/powchain/log_processing.go, beacon-chain/sync/pending_attestations_queue.go, validator/client/metrics.go, validator/client/runner.go, validator/client/wait_for_activation.go
**What PR is this?**
As our repo grows overtime, keeping our code easy to follow becomes a challenge. Some of the challenges comes from complex code with less readability (easy to write, hard to read).
We use [cognitive complexity](https://github.com/uudashr/gocognit) to get the top 10 functions with the highest cognitive complexity. This PR reduced the cognitive complexity for 5 of them.
Ideally we should keep all function's gocognit complexity < 65.
| Function                                                                           | Original complexity | New complexity |
|------------------------------------------------------------------------------------|---------------------|----------------|
| client run validator/client/runner.go                                              | 96 …
=> Refactor: Reduce cognitive complexity for 5 out of top 10 functions in code base

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go
Do not query unnecessarily a block from DB to check if a root is a finalized slot descendant.
=> Use forkchoice to verify finalized descendant

.golangci.yml
After previous PRs to reduce functions with top cognitive complexity, we can lower the threshold now.
This will help guard our code base for future.
=> Change gocognit complextity threshold to 65

beacon-chain/builder/option.go, beacon-chain/builder/service.go, beacon-chain/node/node.go
Can register builder service through the `node.go`. I had to change `Status(ctx context.Context)` to `Status()` to satisfy service interface
=> Register builder service

testing/endtoend/minimal_e2e_test.go, testing/endtoend/minimal_scenario_e2e_test.go
Other - Sisyphean boulder size reduction
This merges the checkpoint sync e2e test into the base test to reduce the number of e2e tests to run. This should be ok since the checkpoint sync test is a superset of the main minimal e2e test.
Also moves the web3signer e2e test into the scenario test file, which only runs occasionally (as opposed to every e2e run).
It is needed to preserve everyone's sanity and remaining shreds of happiness.
This fixes all of our problems, everything will be fine from now on.
=> Stop ruining our lives with flaky e2e

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
This PR fills in submit validator registration endpoint for RPC. This will be used for builder service to register a validator to the remote relay endpoint
=> RPC: Add submit registration endpoint

beacon-chain/builder/service.go, beacon-chain/node/node.go, beacon-chain/rpc/BUILD.bazel, beacon-chain/rpc/service.go
Hook up builder service to RPC service so we can use it. I also added a nice `Builder has configured` log once the builder service is initialized with the HTTP client
=> RPC adds builder service

testing/endtoend/evaluators/fee_recipient.go
Bug fix
The fee Recipient E2E tests were missing the validator keys used for deposits in the check for fee recipient resulting in a mismatch in calculating the assumed fee recipient. this would result in E2E failing if one of those missed validator keys were chosen to propose the block.
=> Fee Recipient E2E misscounting deterministic keys leading to flakes

beacon-chain/sync/initial-sync/blocks_fetcher.go
Other
Currently in `blocksFetcher.fetchBlocksFromPeer` we ignore any error coming from `requestBlocks`. This PR logs out the error.
=> Log error in `fetchBlocksFromPeer`

beacon-chain/blockchain/log.go
We are overwriting the global variable `log` which results in bogus log messages from `blockchain` package. This reverts #10792 but adds back finalization information to the *Synced new block* message
=> do not overwrite log

cmd/client-stats/main.go
Bug fix
client-stats flags are not wrapped in `urfave/cli/v2/altsrc` flags and because of this they are not read from YAML. We have the same `init()` code for beacon-chain and validator.
Fixes #10494
=> Wrap client-stats flags

beacon-chain/sync/rpc_status.go
When we receive a finalized root from the peer for status exchange, and the finalized root is not in DB, it'd be really helpful to know what the root is
=> Log invalid finalized root

beacon-chain/blockchain/execution_engine.go, beacon-chain/blockchain/execution_engine_test.go
After pruning INVALID blocks from forkchoice, we update forkchoice's head but we do not save the new head information to store.  Thus, the RPC endpoint for head returns an error because it can't find head on DB, as it was just pruned. 
This was reported by Mario Vega from EF on hive testings
=> Save Head after pruning invalid nodes

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/sync/rpc_status.go, beacon-chain/sync/rpc_status_test.go, beacon-chain/sync/subscriber_test.go
This PR improves checking of finalized root for status exchange to beyond DB. It first checks for the last cached finalized checkpoint root in the fork choice store. Typically fork choice store gets updated first at t, and DB gets updated second at t+n. The caller of `IsFinalized` can get a more immediate and correct response on the given input root
=> Check finalized beyond DB

beacon-chain/blockchain/execution_engine_test.go, beacon-chain/forkchoice/protoarray/helpers.go, beacon-chain/forkchoice/protoarray/helpers_test.go, beacon-chain/forkchoice/protoarray/store.go
When pruning invalid nodes in the protoarray implementation, the number of nodes and the number of indices may not be equal. We compute deltas with the indices, but we check against the nodes length when applying weight changes. This PR fixes that discrepancy. The test `Test_NotifyForkchoiceUpdateRecursive_Protoarray` is the regression test. This test was being run only with doubly linked tree, which does not suffer from this bug
=> ensure there are as many deltas as nodes

consensus-types/wrapper/BUILD.bazel, consensus-types/wrapper/beacon_block.go, consensus-types/wrapper/beacon_block_test.go
> Feature
This PR adds two new functions to our `consensus-types/wrapper` package for helping us deal with Bellatrix beacon block formats.
```go
// BuildSignedBeaconBlockFromExecutionPayload takes a signed, blinded beacon block and converts into
// a full, signed beacon block by specifying an execution payload.
func BuildSignedBeaconBlockFromExecutionPayload(
blk interfaces.SignedBeaconBlock, payload *enginev1.ExecutionPayload,
) (interfaces.SignedBeaconBlock, error)
```
and:
```go
// WrapSignedBlindedBeaconBlock converts a signed beacon block into a blinded format.
func WrapSignedBlindedBeaconBlock(blk interfaces.SignedBeaconBlock) (interfaces.SignedBeaconBlock, error)
```
These two are pure functions that allow us …
=> Pure Functions to Convert Between Full and Blinded Bellatrix Beacon Blocks

cmd/validator/flags/flags.go, validator/client/validator.go
- String flag to bool flag. `--enable-validator-registration` is nicer than `--enable-validator-registration=true`
- Don't log `Submitted builder validator registration settings for custom builders` or call `SubmitValidatorRegistration` if `registerValidatorRequests` is 0
=> Minor UX improvement to validator registration

validator/client/validator_test.go, validator/client/wait_for_activation.go, validator/client/wait_for_activation_test.go
Other
related to #10593
This PR simplifies the calls we make to updating proposer settings such as fee recipient through APIs.
previously we call the prepare beacon proposer API and validator registration API when:
- Validator Client Starts
- Validator Key status changes
- Start of Epoch
This PR removes the calls when `Validator Key status changes` as it is consistently updated at the start of each epoch anyways. It is unlikely that the validator key will be chosen as a block proposer at the same time the proposer settings are updated, as it's rare for these settings to be updated after validator restart.
=> Simplify Push Proposer settings

api/client/builder/BUILD.bazel, api/client/builder/client.go, api/client/builder/client_test.go, api/client/builder/types.go, api/client/builder/types_test.go
Other
Sending large batches of requests can cause rpc timeouts when a backend is not capable of processing the work in a timely manner.
This PR sets a hard coded limit of 100 keys per request and completes the requests asynchronously.
Fixes #10949
=> Batch build API requests for RegisterValidator

api/client/builder/client.go
=> Check nil before logging "Failed to close response body..."

validator/client/validator.go, validator/client/validator_test.go
UX
and Bug Fix
This PR adds more logging for when a validator index is not assigned to the public key resulting in not calling the associated prepareBeaconProposer API. This will also fix a bug surrounding caching the index of public keys incorrectly as 0 when the key was not found. this results in using the wrong associated fee recipient for the key. This unit test also assists in making sure this feature is not broken in the future.
Fixes #10858
=> Push Proposer Settings: improve warn logs + bug fix

api/client/builder/BUILD.bazel, api/client/builder/client.go, api/client/builder/client_test.go
Bug fix
Validator registration batching is generally not needed. 
The original PR, #11002 was a workaround to an inefficient mev boost relay implementation. Said implementation has been improved significantly and therefore these changes are no longer needed.
Additionally, #11002 introduced some new race conditions (in tests) reported in issue #11020.
Fixes #11020
=> builder client: Revert key batching PR #11002

beacon-chain/blockchain/execution_engine.go
Adds a nilcheck for FCU, this crash was found by the Antithesis team.
=> add nilcheck for payload ID

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
Other
Per spec, the request should be limited to 1s. 
See https://github.com/ethereum/builder-specs/blob/e912fa8c6727fa456106cc85cb94fc4ab0f8d251/specs/validator.md#relation-to-local-block-building
=> Enforce a 1s timeout for block builder reply

validator/client/validator.go
Trivial grammatical fix to the fee recipient config warning message in the latest release.
>
Other
A grammatical fix to the warning message about fee recipient configs. Warning message reads easier.
N/A
Fixes #
=> Trivial fix to the warning message about fee recipient config

async/debounce_test.go, async/every_test.go
Bug fix
This PR updates the following `async/debounce` and `async/every` tests to prevent concurrent read and writes:
- `TestDebounce_SingleHandlerInvocation`
- `TestDebounce_MultipleHandlerInvocation`
- `TestTestEveryRuns`
It improves the project tests stability.
Atomic counters have also been added to the rest of the debounce tests to prevent potential data races later on.
The `timesHandled` counter used in these tests assertions are not protected against concurrent read and writes.
When reading their values for assertion, they can be incremented at the same time in the goroutine right above.
The same goes for the `i` counter in `TestTestEveryRuns`.
When running the tests with …
=> Fix counters data races in async tests

beacon-chain/powchain/engine_client.go
I'm not sure why we want to log the error data instead of the error string itself. The error data will probably be nil and it's not entirely useful. This PR changes it to logging error string instead of data.
```
time="2022-07-12 12:48:00" level=error msg="Could not check configuration values between execution and consensus client" error="<nil>: client error while processing request" prefix=powchain
```
=> Log error string instead of data

beacon-chain/builder/service.go, beacon-chain/builder/testing/mock.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
We were not using builder status correctly. We were using it before getting header and payload requests and that significantly eat up the block proposal time. Builder status was meant to call during start-up to validate that relay and builder are reachable. There's not much value calling it frequently besides slowing down block proposal
=> Remove builder status check for block proposal

validator/keymanager/remote-web3signer/internal/client.go, validator/keymanager/remote-web3signer/internal/client_test.go
Bug fix
PR fixes the case application/json parsing case when meta data is added.
example handling `Content-Type: application/json;  charset=UTF-8`
related to #11055
=> Web3signer: Support json content type with optional metadata

tools/pcli/main.go
Add a `blinded_block` option for `pcli pretty`
=> Allow pcli to pretty print blinded blocks

testing/endtoend/components/validator.go
Bug fix
fee-recipient-evaluator is enabled for current release but the flag was not being set, this PR adds the flag back in for testing the current release.
=> Enable Fee Recipient on Prysmsh: Bugfix

beacon-chain/sync/metrics.go
No issue, just need more granular metrics to understand the performance of the p2p blocks by range responses in beacon nodes
=> Use More Granular Metrics for P2P Blocks By Range Latency Histogram

config/features/config.go
This PR enables the --enable-only-blinded-beacon-blocks flag for prater and the goerli merge
=> Enable Only Saving Blinded Beacon Blocks for Prater

beacon-chain/sync/rpc.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_metadata.go, beacon-chain/sync/rpc_status.go, beacon-chain/sync/rpc_test.go
Networking Improvement
This resurrects #7926 , in this PR we directly penalize bad ssz payloads received via RPC and 
also incomplete rpc requests by other peers. With the peer scorer being the default this
makes prysm stricter with regards to bad behaviour by other peers. 
N.A , Part of #10322 
=> Penalize Bad Payloads Properly

beacon-chain/db/kv/checkpoint.go, beacon-chain/db/kv/validated_checkpoint.go
Show the missing root on `errMissingStateForCheckpoint`
=> Wrap missing state for checkpoint error

beacon-chain/db/kv/checkpoint.go, beacon-chain/db/kv/checkpoint_test.go, beacon-chain/db/kv/validated_checkpoint.go, beacon-chain/db/kv/validated_checkpoint_test.go
In the event, that a state summary is missing in the DB, a block may exist. We can try to recover to reconstruct then save the state summary in DB
=> Can recover from missing state summary in DB

validator/rpc/auth_token.go, validator/rpc/server.go
UX
The validator client uses a JWT token when enabling the web feature which is used for all RPC/REST API authentications.
The JWT is stored in a file `auth-token` within the wallet directory of the local computer where the validator client is running. This location is not always clear and this improved log can help debugging ` auth token needs to be used in the defined prysm wallet directory`
=> Validator Client: auth-token path log

beacon-chain/execution/check_transition_config.go
I made some improvements to `terminal difficulty has not been reached yet` log and added network field 
```
[2022-08-04 08:58:32]  INFO powchain: terminal difficulty has not been reached yet latestDifficulty=10721970 terminalDifficulty=10790000
```
👇🏼 
```
[2022-08-04 09:15:21]  INFO powchain: Ready for merge latestDifficulty=10735641 network=prater terminalDifficulty=10790000
```
=> Improve `terminal difficulty has not been reached yet logging`

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
This PR fixes signed bid validation to use the correct fork and genesis root. Source: https://github.com/ethereum/builder-specs/blob/main/specs/builder.md#signing
=> Use correct fork and genesis root to verify bid

beacon-chain/rpc/statefetcher/fetcher.go
Cleanup
Some methods incorrectly use the word `hex`. We never pass hex-encoded state to the fetcher.
=> Rename `statefetcher` methods

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
Fixes #11188
Validates builder header has the correct parent hash and the correct timestamp. If either fails, an error is returned to default to the local execution engine for block construction
=> Validate builder header

beacon-chain/cache/payload_id.go, beacon-chain/cache/payload_id_test.go
Bug fix
Comment in `ProposerPayloadIDsCache.SetProposerAndPayloadIDs` says:
> Ok to overwrite if the slot is already set but the payload ID is not set.
The mentioned payload ID refers to the cached ID, not the new one. The current comparison verifies the new ID.
=> Change proposer cache overwrite logic

beacon-chain/forkchoice/doubly-linked-tree/on_tick.go, beacon-chain/forkchoice/doubly-linked-tree/unrealized_justification.go, beacon-chain/forkchoice/protoarray/on_tick.go, beacon-chain/forkchoice/protoarray/unrealized_justification.go, beacon-chain/forkchoice/protoarray/unrealized_justification_test.go
There is a double lock race condition when NewSlot acquires the
checkpoints lock first and the nodes lock later, while calls to Head()
acquire the nodeslock first and the checkpoints lock later.
This PR releases the checkpoints lock in NewSlot, to reaquire it later
in updateUnrealizedCheckpoints after getting the nodes lock
=>     Release checkpoints lock on on_tick

beacon-chain/forkchoice/protoarray/store.go
Credit to @nisdas that found this recursive read locks between `store.head` and `viableForHead` acquiring the same checkpoints lock. This PR releases early from `head`. It can't be removed from `viableForHead` because it is called from several other paths.
=> release checkpoints lock from store.head

beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix_test.go
This PR ensures essential compliance that header and payload root match when outsourcing block construction using an external builder. If the root mismatch, it's an attributable fault on the relayer, we'll log an error to recommend user to disconnect with the relayer. I feel a lot better to fail earlier than to broadcast the faulty payload block out and get downgraded by peer scorers.
=> Builder: check payload and header HTR root match

beacon-chain/blockchain/service.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go, cmd/beacon-chain/main.go, cmd/beacon-chain/usage.go, config/params/mainnet_config.go
Fixes a few typos and bugs from #11109 
- The circuit breaker flags were not added to the group, so it was undefined
- Change defaults from 4, 6 to 3, 8 to be more prudent. 6 slots per epoch can easily be missed with a descent pool
- Fixed warning log to display the correct `diff` for `totalMissed`
- Updated a few variable names
=> Misc builder fixes

beacon-chain/node/BUILD.bazel, beacon-chain/node/node.go, beacon-chain/node/node_test.go, cmd/beacon-chain/main.go, cmd/beacon-chain/usage.go
This PR removes our backup webhook feature for the beacon node. The beacon node db being as large as it is right now, would cause a large spike in memory when backing it up. It would be better for users to manually copy it rather than copy it via memory using our webhook.
N.A
=> Remove Backup Webhook In the Beacon Node

beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go, beacon-chain/forkchoice/doubly-linked-tree/node.go, beacon-chain/forkchoice/doubly-linked-tree/on_tick.go, beacon-chain/forkchoice/doubly-linked-tree/store.go
The order of locks acquired in forkchoice is susceptible to deadlocks when two different functions are called which aquire locks in reversed order. In this PR we audit these locks. Credit goes to @nisdas that found all possible deadlocks and to @infosecual for a missing lock in `insert` that is added here. 
The order of all locks in every exposed function in doubly linked tree is as follows
Head: votes (defer)  --> nodes (defer) --> 
updateBalances: proposerBoost
applyProposerBoostScore: proposerBoost
head: checkpoints (defer)
CachedHeadRoot: nodes (defer)
Tips:
tips: nodes (defer)
IsOptimistic: nodes(defer)
AllTipsAreInvalid: nodes(defer)
InsertNode:
insert: nodes (defer) --> proposerBoost --> checkpoints
pullTips: nodes(defer) --> checkpoints (defer)
updateCheckpoints: checkpoints --> …
=> DoublyLinkedTree double locks

beacon-chain/forkchoice/protoarray/helpers.go, beacon-chain/forkchoice/protoarray/on_tick.go, beacon-chain/forkchoice/protoarray/store.go
This PR deals with the double locks in protoarray. The structure of the locks in protoarray is very similar to that in #11269, we record here the structure for future reference
Head: votes (defer)  --> nodes (defer) --> 
computeDeltas:
updateBalances: proposerBoost
applyProposerBoostScore: proposerBoost
updateBestChildAndDescendant: 
head: checkpoints
viableForHead: checkpoints (defer)
CachedHeadRoot:
Tips: nodes (defer)
IsOptimistic: nodes(defer)
AllTipsAreInvalid: nodes(defer)
InsertNode:
insert: nodes (defer) --> proposerBoost
pullTips: nodes(defer) --> checkpoints
updateCheckpoints: checkpoints --> 
AncestorRoot: nodes (defer)
prune: nodes(defer) --> checkpoints
InsertOptimisticChain: 
insert: nodes (defer) --> proposerBoost
updateCheckpoints: checkpoints --> 
AncestorRoot: nodes …
=> Protoarray deadlocks

cmd/beacon-chain/execution/BUILD.bazel, cmd/beacon-chain/execution/options.go, cmd/beacon-chain/flags/base.go, cmd/beacon-chain/main.go, cmd/beacon-chain/usage.go
Bug FIx
This brings back our `--http-web3provider` flag as an alias, so that users who are running solely via it will not have a failure when upgrading to v3.
N.A
=> Bring back old execution flag as an alias

beacon-chain/sync/service.go
Bug Fix
#11120 removed our resync routine, which is critical for the functioning of the node. If a user has their internet connection severed for a non-trivial amount of time, without this routine the beacon node will stall.
N.A
=> Add Back Resync Routine

beacon-chain/sync/rpc_beacon_blocks_by_range.go
Logging
In the event, we can't send a response successfully we will mark it as a debug log rather than an error. This is to prevent making our default logs as too noisy.
N.A
=> Bring Down Error To A Debug Log 

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_test.go
The most frequent feedback from v3 is the annoyance of duplicated logging for the INFO log `Updated fee recipient addresses for validator indices`. This gets logged every epoch regardless of changes to the fee recipient address. The beacon node server also updates DB regardless of changes to the fee recipient address. This doesn't make sense. The sensible thing to do would be to check if the fee recipient exists in DB and if the fee recipient is different from the previous set value then update DB if they are different. 
Corresponding benchmarks ensure the additional DB reads don't have performance impacts:
```
10000 validators:
BenchmarkServer_PrepareBeaconProposer-12    	      94	  11738194 ns/op
1000 validators:
BenchmarkServer_PrepareBeaconProposer-12    	    1008	   1007927 ns/op
```
=> Prysm API: skip updating fee recipient if it's the same

beacon-chain/rpc/eth/beacon/blocks.go, beacon-chain/rpc/eth/beacon/blocks_test.go
Bug Fix
This simplifies our list attestation rpc endpoint. The method has no need to know about the block version as 
attestations are supported by all block types.
Fixes #11291 
=> Simplify List Attestations RPC Method

beacon-chain/rpc/apimiddleware/structs.go
Bug fix
The Beacon API version of the register_validator has an encoding problem that is fixed in this PR. A pointer was the culprit that was creating decoding issues when external validators use prysm's beacon node. 
Fixes #11297
=> Beacon API: validator registration encoding bug

beacon-chain/blockchain/process_block_test.go, beacon-chain/forkchoice/doubly-linked-tree/node.go, beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync_test.go
In doubly linked tree we never mark the finalized node as valid.
=> Fix setNodeAndParentValidated

beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_aggregate_proof_test.go, beacon-chain/sync/validate_beacon_attestation.go, beacon-chain/sync/validate_beacon_attestation_test.go, beacon-chain/sync/validate_sync_committee_message_test.go, beacon-chain/sync/validate_sync_contribution_proof_test.go
It doesn't make sense why a node would stop accepting attestations over the wire under optimistic mode. The node should account for these attestations in fork choice. I understand that a node should not perform duties under optimistic mode but this is very different than performing duties
=> Accept attestations when node is optimistic

beacon-chain/execution/log_processing.go
Bug Fix
In the event the execution client returns a bad/invalid log, we handle the failure better by resetting our execution tracker to the last valid block.
N.A
=> Handle Execution Client Failures Better

beacon-chain/state/stategen/getter.go
Other
As title describes, wraps some errors to help identify unmarshal errors.
Part of the investigation of #11327
=> db: Wrap errors in db.fetchAncestor to better identify unmarshalling issues

validator/client/propose.go, validator/client/propose_test.go
Fixes a regression from #11159. All the blind block proposal currently fails on validator client due to: 
```
[2022-08-29 11:13:37] ERROR validator: Failed to get execution payload transactions error=unsupported getter pubKey=0xb104bed4f7cb
```
If the block is blind, we should skip logging txs count.
=> Fix can propose blind block

beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_bellatrix.go
This PR ensures that the correct header bid value gets logged. `bytesutil.BytesToUint64BigEndian(bid.Message.Value)` was incorrect.
=> Log corerct header value

beacon-chain/execution/check_transition_config.go, beacon-chain/execution/rpc_connection.go, beacon-chain/execution/service_test.go
This PR adds informative errors in case a user runs into the following scenarios:
1. Not authenticating their HTTP connection to their execution client with a JWT token, which will return 401 unauthorized errors upon checking the chain ID of the execution client via JSON-RPC
2. Not connecting to their execution client on the engine port, which will lead to "not found" errors when connecting via the usual JSON-RPC at 8545
Tested in interop mode and is a lot friendlier now than it was before.
=> Informative Errors on Execution Client Connection Issues

api/client/builder/client.go, api/client/builder/client_test.go
Bug fix
the code was trying to unmarshal responses bodies as error messages despite not all non-200 responses being error messages, resulting in bad unmarshalling.  This PR addresses all known code types and adds a unit test to catch this in the future. 
Fixes #11348
=> fixing json unmarshalling

beacon-chain/blockchain/execution_engine_test.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/receive_block_test.go
Do not save to DB a finalized checkpoint that it's older than the
current one.
Fixes #11351 
Fixes #11286
=> Only update finalized checkpoint in DB if it's newer

beacon-chain/blockchain/log.go
This makes `logStateTransitionData` more future proof. We only want to log `txCount` on the payload, not on the header. We can ignore unsupported error if it's header
=> Log tx count only on payload

beacon-chain/rpc/prysm/v1alpha1/validator/server.go, beacon-chain/rpc/prysm/v1alpha1/validator/server_test.go
Bug fix
if not connected validator index causes a panic instead of just not being found.
This is caused when the beacon node is not connected to the execution client/not synced causing the head to return as nil but not failing.
=> Improve Validator Index RPC Error Handling

validator/client/validator.go
Nitpick. Time to duty is always one second off. If you have to attest at slot 1, your time to duty should be 12s, not 11s. This is only cosmetic and used in log
=> Fix time to duty to round slot number

beacon-chain/rpc/prysm/v1alpha1/validator/BUILD.bazel, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_eth1data.go, config/features/config.go, config/features/flags.go
This PR adds a feature flag to disregard the staking contract when proposing blocks. This is useful for some devnets or private networks. The feature flag is `disable-staking-contract-check` 
cc @parithosh
=> Feature flag to disregard deposit contract

beacon-chain/builder/service.go
=> Don't hard shutdown if mev-boost / relay is not available

beacon-chain/sync/initial-sync/round_robin.go, beacon-chain/sync/initial-sync/round_robin_test.go
Improve warning around `Batch is not processed` and `no good blocks in batch`. The currently warning is not helpful and is a little bit scary
=> Better batch block processing warning

beacon-chain/blockchain/weak_subjectivity_checks.go
Documentation
Dials back the severity of the warning when no weak subjectivity checkpoint is provided.
Fixes #11361
=> less ominous --weak-subjectivity-checkpoint warning

consensus-types/blocks/factory.go, consensus-types/blocks/getters.go
Refactor
We can safely remove explicit block and body nilness checks from `BeaconBlockIsNil()` because these checks are already covered inside `b.IsNil()`. After removing this code, all test cases inside `Test_SignedBeaconBlock_IsNil` stil pass.
=> Simplify `BeaconBlockIsNil()`

beacon-chain/blockchain/process_block_helpers.go
Only check that the chain's parent is in forkchoice, rather than it
being the finalized checkpoint. Forkchoice anyway guarantees that the
chain will be a descendant of the finalized checkpoint.
=> Fix fillInMissingBlocks

beacon-chain/p2p/monitoring.go, beacon-chain/p2p/service.go
> Feature
This PR adds in avg gossip scores by client type and also adds in a gauge of connected peers by client type. Here's what this looks like on a mainnet setup.
```
connected_libp2p_peers{agent="lighthouse"} 9
connected_libp2p_peers{agent="nimbus"} 1
connected_libp2p_peers{agent="prysm"} 22
connected_libp2p_peers{agent="rust-libp2p"} 1
connected_libp2p_peers{agent="teku"} 3
connected_libp2p_peers_average_scores{agent="lighthouse"} 0.10133333333333333
connected_libp2p_peers_average_scores{agent="nimbus"} 0
connected_libp2p_peers_average_scores{agent="prysm"} 0.11212272727272726
connected_libp2p_peers_average_scores{agent="rust-libp2p"} 0
connected_libp2p_peers_average_scores{agent="teku"} 0.0398
```
**Which …
=> Add in P2P Metrics for Mainnet

beacon-chain/blockchain/metrics.go, beacon-chain/core/epoch/BUILD.bazel, beacon-chain/core/epoch/epoch_processing.go, beacon-chain/core/validators/BUILD.bazel, beacon-chain/core/validators/validator.go
The activation and exit queue metrics we added yesterday weren't correct because they would consider replay state.
As it turns out there are already validator state that account for pending, activation, slashing.. and more, we could just use this:
```go
validatorsCount = promauto.NewGaugeVec(prometheus.GaugeOpts{
Name: "validator_count",
Help: "The total number of validators",
}, []string{"state"})
```
=> Remove activation/exit queue metrics

beacon-chain/rpc/apimiddleware/structs.go
Thanks to @rkapka for finding out by the timestamp was not being returned on forkchoice dumps.
=> add forkchoice node timestamp to json response

beacon-chain/rpc/eth/validator/validator_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go
Logs if the returned payload from the engine does not have the fee
recipient set in the validator.
Also warn the user if he's proposing a block with the burner fee
recipient address.
=> Better log fee recipient mismatch

beacon-chain/execution/check_transition_config.go
As previously reproted, logging `ready for merge` and ttd for every 10s may be too aggressive. This PR changes it to logging every min
=> Log `ready for merge` every min

api/client/beacon/checkpoint.go, api/client/beacon/checkpoint_test.go
Extra assurance that downloaded state slot matches header slot. We don't want to compute construct block root using skipped slot root. cc @kasey
=> Validate downloaded state slot matches header slot

beacon-chain/execution/testing/mock_engine_client.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_execution_payload_test.go
Motivated from #11399
If the cached `getPayload` call to execution client times out, it may be wiser to give it a second try instead of failing block on the spot
=> Fall back to uncached getPaylod if first time outs

beacon-chain/blockchain/process_block_test.go, beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go, beacon-chain/forkchoice/doubly-linked-tree/node.go, beacon-chain/forkchoice/doubly-linked-tree/node_test.go, beacon-chain/forkchoice/doubly-linked-tree/on_tick.go, beacon-chain/forkchoice/doubly-linked-tree/store.go, beacon-chain/forkchoice/doubly-linked-tree/store_test.go, beacon-chain/forkchoice/doubly-linked-tree/types.go, beacon-chain/forkchoice/doubly-linked-tree/vote_test.go
Prune forkchoice after on_tick. 
Remove prune threshold to make sure we always prune after new finalization. 
Tested on production
=> Prune during on_tick

beacon-chain/execution/BUILD.bazel, testing/spectest/shared/common/forkchoice/BUILD.bazel, testing/spectest/shared/common/forkchoice/builder.go, testing/spectest/shared/common/forkchoice/runner.go, testing/spectest/shared/common/forkchoice/service.go, testing/spectest/shared/common/forkchoice/type.go, testing/spectest/utils/utils.go
Implement https://github.com/ethereum/consensus-specs/pull/2982
~~The semantics of the `valid` tests in forkchoice and sync is different this is why we fail currently, if that is changed the tests pass.~~
Passing spectests as of 09/11.
=> Implement optimistic sync spectests

beacon-chain/blockchain/receive_attestation.go
In the event of that `NewSlot` fails, we should log the error and continue updating head in case of a new head. This happens in e2e during checkpoint sync due to an unknown finalized root when pruning.
=> do not return on error during on_tick

beacon-chain/blockchain/receive_attestation.go
Code health improvement
Following up from #11463, it seems a little odd that we completely return from the spawn attestation routine for the new slot ticker even if a single update head fails. It seems to me the more sensible thing to do is just to log the error and cont. Update head every slot 
N/A
N/A
=> Don't return out of routine when update head errors out

network/auth.go
Bug Fix
It changes the default http client timeout to 30 seconds from 6 seconds. This is because if the default timeout is lower than the context provided with it, we will instead take the smaller deadline( 6 seconds). This causes issues with potentially time consuming engine calls. (NewPayload) . All our engine call timeouts are smaller than 30 seconds, so 30 is a sufficient value to use as a default here. 
N.A
=> Change Default Timeout To 30 Seconds

beacon-chain/blockchain/receive_attestation.go
> Better error logging UX
This has been bugging me for a while. When updating head files due to new attestations, the warning log `Resolving fork due to new attestation` doesn't convey the message. It is not resolving anything. I think it's better to be direct, like "Could not update head due to new attestation`. I also changed from `warn` to `error`. Feel free to disagree with that
Fixes #
=> Fix attestations update head error logging

validator/client/validator.go
Bug fix
If the validator is activated just after the duration of `timeTillDuty`, the log would display a negative number.
With this PR we add a simple check to ensure that the `timeTIllDuty` is only logged when it is above 0.
Fixes #11383
=> fix validator loggin timeTillDuty as a negative number

beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go, beacon-chain/forkchoice/doubly-linked-tree/types.go, beacon-chain/forkchoice/interfaces.go, beacon-chain/state/stategen/BUILD.bazel, beacon-chain/state/stategen/errors.go, beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/getter_test.go, beacon-chain/state/stategen/mock/mock.go, beacon-chain/state/stategen/service.go
This PR adds a handler to forkchoice to request justified balances only when the justified checkpoint has changed instead of receiving this information on every call to Head. At this moment this is a setter function that just sets this handler and an implementation in the stategen package.
=> Add a justified balance getter to forkchoice

validator/accounts/testing/BUILD.bazel, validator/accounts/testing/mock.go, validator/client/iface/BUILD.bazel, validator/client/iface/validator.go, validator/client/runner.go, validator/client/runner_test.go, validator/client/service.go, validator/client/testutil/BUILD.bazel, validator/client/testutil/mock_validator.go, validator/client/validator.go, validator/client/validator_test.go, validator/rpc/standard_api.go, validator/rpc/standard_api_test.go
Bug fix
This PR address 2 issues.
1. Fee Recipient API did not periodically call the beacon API with the correct data.#11539
2. Fee Recipient values did not persist correctly after validator restarts. The value will now persist after the start of each epoch if updated through the API. if the validator restarts directly after an update before the beacon API is called then the value will not persist on restart. The value set in the validator client will override values in the beacon node on restart, if one does not wish for the value to overwrite the beacon node's values they should not provide the validator client any on startup. 
Fixes #11322,#11539
=> Keymanager API: fix fee recipient API and add persistence

beacon-chain/execution/service.go
Bug fix
fixes this panic when the code tries to call the rpc client before it is initialized
```
[2022-09-26 07:03:54]  INFO initial-sync: Processing block batch of size 25 starting from  0xb89eddc1... 3960641/3972319 - estimated time remaining 2h35m42s blocksPerSecond=1.2 
peers=6                                                                                                                                                                          
panic: runtime error: invalid memory address or nil pointer dereference                                                                                                          
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x23abfa6] …
```
=> fix panic when the rpc client is not initialized

beacon-chain/rpc/apimiddleware/custom_handlers.go, beacon-chain/rpc/apimiddleware/custom_handlers_test.go, beacon-chain/rpc/apimiddleware/custom_hooks.go, beacon-chain/rpc/apimiddleware/custom_hooks_test.go, beacon-chain/rpc/apimiddleware/endpoint_factory.go, beacon-chain/rpc/apimiddleware/structs.go, validator/rpc/apimiddleware/endpoint_factory.go, validator/rpc/apimiddleware/structs.go, validator/rpc/apimiddleware/structs_test.go
Other
External projects/tools might want to deserialize API responses into custom structs. There is no need for these tools to define their own types because Prysm already has them.
Fixes #11504
=> Expose structs from API Middleware

cmd/validator/accounts/accounts.go
revert breaking change
Validator-Exit was moved to `prysmctl` in the following PR
https://github.com/prysmaticlabs/prysm/pull/11515/files#diff-f40562b5596adb94e7e60e9a0a25679a8887242252a1b0975d46452485972d21 
removed in`cmd/validator/accounts/accounts.go`
added in `cmd/prysmctl/signing/cmd.go`
this PR is to revert the removal of the command for the minor release in favor of fully deprecating it in a future major release.
=> revert moving validator-exit command

beacon-chain/node/BUILD.bazel, beacon-chain/node/node.go, beacon-chain/node/node_test.go, config/features/flags.go
If the chain-config-file flag is used concurrently with the network
flag then error and exit.
Related to #10822.
Bug fix
When passing a `chain-config-file` along with a network flag one will override the other making it unclear which network is being run.
This PR ensures that we send an error and stop the program when the two flags are set concurrently.
Fixes #10822.
=> Add error if chain-config-file used concurrently with network

.bazelrc
Other
`--stamp` made bazel link some buildtime information to every GoLink step of a go_binary. This meant that there was never a cache hit as the buildtime information includes info like the current timestamp.
This change should increase the number of build cache hits and makes binary release builds more reproducible
=> bazel: remove --stamp for builds

beacon-chain/p2p/fork_watcher.go, beacon-chain/p2p/gossip_topic_mappings.go, beacon-chain/p2p/gossip_topic_mappings_test.go, beacon-chain/p2p/message_id.go, beacon-chain/p2p/pubsub_filter.go, beacon-chain/p2p/types/object_mapping.go
This PR adds Capella p2p changes without BlsToExec object
=> Add Capella p2p changes

beacon-chain/core/transition/bellatrix_transition_no_verify_sig_test.go, beacon-chain/core/transition/transition_no_verify_sig.go, beacon-chain/core/transition/transition_no_verify_sig_test.go
Use the same block operations in Capella as in Bellatrix
=> Operations in Capella are as in Bellatrix

beacon-chain/p2p/utils.go, beacon-chain/p2p/utils_test.go, beacon-chain/rpc/eth/node/node_test.go
Bug Fix
During withdrawals testing, it was revealed that our API endpoints were outputting invalid ENRs. The reason it happened was because prysm was using the incorrect base64 encoding when serializing the record. This PR fixes it along with adding in a test for this.
N.A
=> Fix ENR Serialization

beacon-chain/core/epoch/precompute/attestation.go, beacon-chain/core/epoch/precompute/attestation_test.go
This was missed and caught during spec vector tests
=> Add capella to epoch balances calculation

beacon-chain/state/state-native/getters_withdrawal.go, beacon-chain/state/state-native/getters_withdrawal_test.go
This PR fixes a bug introduced in  #11656 which started the sweep in the wrong validator index. It also fixes a bug that was allowing for a balance 0 validator to fully withdraw.
=> Fix expected_withdrawals

prysm.sh
Bug fix
FIxes lines that prevents correct binaries from being downloaded via prysm.sh on Apple M1's.
originally opened by user https://github.com/baobaoy in https://github.com/prysmaticlabs/prysm/pull/11541 but pr went stale due to non-response.
Fixes #7950
=> correctly assign arm64 arch for Apple M1

validator/client/beacon-api/BUILD.bazel
Bug fix
This PR allows the validator's beacon REST API tests to be ran during CI by adding the `gotags = ["use_beacon_api"]` to the test target, therefore making the tests run even when `--config=beacon_api` is not set on the command line.
=> Onboard validator's beacon REST API tests to CI

beacon-chain/core/blocks/withdrawals.go, beacon-chain/core/blocks/withdrawals_test.go, beacon-chain/core/transition/transition_no_verify_sig.go
Credit to @terencechain for suggesting this. This PR moves signature aggregation of BLS_TO_EXECUTION_CHANGES with the rest of the signatures in the block.
=> Batch capella signatures with the rest of the block

beacon-chain/sync/validate_bls_to_execution_change.go, beacon-chain/sync/validate_bls_to_execution_change_test.go
Harden Gossip
In our gossip handler for BLS Execution Change Messages, we make sure our head state has 
transitioned to capella before we start verifying these messages. This also adds a test case
for it.
N.A
=> Add State Check For BLS Execution Change Messages

validator/client/beacon-api/beacon_api_validator_client.go, validator/client/beacon-api/index_test.go, validator/client/beacon-api/json_rest_handler_test.go
Bug fix
DeepSource was complaining about some variable shadowing and some functions returning the concrete type instead of the interface.
=> Fix DeepSource errors in the Validator's REST API

beacon-chain/core/blocks/withdrawals.go
* Other
Use "next" instead of "latest" in error message. This was changed in the specs a little while ago.
=> Update withdrawal error message to reflect new field name

testing/endtoend/endtoend_setup_test.go, testing/endtoend/mainnet_scenario_e2e_test.go, testing/endtoend/types/types.go
Bug fix
PR #11306 broke the post-submit E2E by unintentionally introducing an evaluator for normal runs. I am also removing some logic around running the test as I noticed the value can be provided through an environment variable.
=> Fix to Post Submit E2E

testing/endtoend/endtoend_setup_test.go, testing/endtoend/mainnet_scenario_e2e_test.go, testing/endtoend/types/types.go
E2E Fix
This re-enables our cross client e2e option along with allowing us to run the multiclient api evaluator. Previous test runs were failing because the evaluator was being applied to tests with no LH nodes. This makes sure the evaluator is only applied if LH nodes are running.
N.A
=> Add Back Cross Client Option

testing/endtoend/component_handler_test.go, testing/endtoend/components/beacon_node.go, testing/endtoend/components/eth1/depositor.go, testing/endtoend/components/eth1/node.go, testing/endtoend/components/lighthouse_validator.go, testing/endtoend/components/tracing_sink.go, testing/endtoend/components/validator.go, testing/endtoend/components/web3remotesigner.go, testing/endtoend/endtoend_test.go, testing/endtoend/types/types.go
Other
How to attach a debugger to an e2e subprocess. For example, it may be useful to debug and break the beacon chain process.
```
bazel test //testing/endtoend:go_default_test  --test_output=streamed --test_arg=-test.v --spawn_strategy=standalone -c dbg
```
When the test runs, you will see a log message like this: 
```
component_handler_test.go:238: This test PID: 272686 (parent=272671)
Beacon chain nodes: [274706 274705]
Validators: [274733 274734]
ETH1 nodes: [274691]
```
This log prints the process ID's spawned by this test. A remote debugger, dlv, can attach to process 274706 as such:
```
dlv --listen=:2345 --headless=true --api-version=2 attach 274706
```
And then a remote debugger can interact with dlv on …
=> e2e: Print process IDs for debugging.

beacon-chain/db/kv/blocks.go, beacon-chain/db/kv/checkpoint.go, beacon-chain/db/kv/state_summary.go, beacon-chain/db/kv/validated_checkpoint.go, beacon-chain/db/kv/validated_checkpoint_test.go
Other
As title describes, we should never attempt to secure a lock during a boltdb transaction as the transaction could be blocking other, unrelated, boltdb transactions.
This PR acknowledges a prior issue that was solved in https://github.com/prysmaticlabs/prysm/pull/9428 where opening a view transaction within an update transaction was problematic. We are revisiting that same problem where with a different solution that does not attempt to secure any cache lock within a bolt transaction.
=> beacondb: Remove cache look up and lock request from boltdb transaction for state summaries

beacon-chain/core/blocks/payload_test.go
As discussed with @prestonvanloon and @potuz few weeks back.  `Test_IsExecutionEnabledCapella` is bogus and we should just remove it anyway. There's no value testing Capella for execution enable
=> Remove `Test_IsExecutionEnabledCapella`

beacon-chain/rpc/apimiddleware/structs.go, validator/client/beacon-api/beacon_block_json_helpers.go, validator/client/beacon-api/beacon_block_json_helpers_test.go
Bug fix
Capella block includes a list of  `SignedBLSToExecutionChange` objects, but the middleware struct has a field of type `BLSToExecutionChangeJson`, which is unsigned.
=> fix validator client

beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/receive_block.go
We already remove attestations from the pool during on-block when the block is canonical. There is no need to remove again and also no need to remove when the block is not canonical .
=> Do not remove attestations twice

beacon-chain/state/stategen/replay.go
Feature
When looking at log messages, it is not easily possible to connect the start and end of the replayed state messaging. This PR shares the log fields between the two messages.
=> state: Improve replay state logs metadata

.bazelrc
Other
This is necessary otherwise build version will say unknown local build, built moments ago or something to that effect when using `--version`
=> Add --stamp to release builds

beacon-chain/blockchain/error.go
UX
Inspired by https://github.com/prysmaticlabs/prysm/issues/11774. Users are probably not aware what `ee` means in the error message and thus may not understand that there is an issue with the execution client.
=> More user-friendly message in `ErrUndefinedExecutionEngineError`

beacon-chain/rpc/eth/validator/validator.go, beacon-chain/rpc/eth/validator/validator_test.go
Tests
Bellatrix tests for `ProduceBlockV2` did not evaluate the returned payload.
=> Improve tests for `ProduceBlockV2`

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go, consensus-types/blocks/getters_test.go, consensus-types/blocks/setters.go, consensus-types/interfaces/beacon_block.go
`emptyBlockToSign` doesnt need to return both `beacon_block` and `signed_beacon_block` as two different objects. We can just use `signed_beacon_block` because it contains `beacon_block` anyway
=> Capella: clean up `emptyBlockToSign`

consensus-types/blocks/setters.go
Supercedes #11792
The only time when a validator writes to a block is during the block proposal phase. That's also the only time a block can get mutated. When constructing a block, there's no reason to copy the block field objects. Given that latency matters, calling these setters for block construction is a hot path. We should optimize based on that; hence this PR removes the unnecessary copy 
Note: these methods are not used today, they only are used in `capella` branch
=> Remove copy for block setters

beacon-chain/rpc/eth/validator/validator.go, beacon-chain/rpc/eth/validator/validator_test.go, beacon-chain/rpc/testutil/mock_state_fetcher.go
Bug fix
- #11723 introduced a regression bug, removing the ability to fetch attester duties for the next epoch.
- Fetching proposer epochs incorrectly allows to query for the next epoch.
=> Query duties - epoch changes

beacon-chain/rpc/eth/validator/BUILD.bazel, beacon-chain/rpc/eth/validator/validator.go, beacon-chain/rpc/eth/validator/validator_test.go
Mostly @rkapka's work. I just helped with clean up. Credit goes to him.
Built on top of #11817. This PR querying for proposer duties one epoch ahead of the current epoch
=> Allow proposer duties one epoch in advance part 2

testing/endtoend/helpers/helpers.go
Bug fix
Our E2E tests use presence of sentinel log messages in subprocesses as checks to ensure that components have started properly. Sometimes these checks fail, resulting in failed/flaky e2e tests. @nisdas has noticed that in these instances the logs appear corrupted, so it's likely that something is wrong with how we set up stderr redirection. I noticed that `WaitForTextInFile` calls Seek() on the file descriptor which is shared with component that call it. I think this is resulting in corruption of log files. 
I don't think an issue has been filed for this, but if we have one LMK and I'll attach it.
=> attempt to fix WaitForTextInFile log corruption

testing/endtoend/components/beacon_node.go, testing/endtoend/components/boot_node.go, testing/endtoend/components/lighthouse_beacon.go, testing/endtoend/components/lighthouse_validator.go, testing/endtoend/components/web3remotesigner.go
=> Use Single Log File in E2E

beacon-chain/blockchain/chain_info_test.go, beacon-chain/blockchain/head.go, beacon-chain/blockchain/head_test.go, beacon-chain/blockchain/receive_attestation_test.go
> Clean up
There's not much reason to be tracking head slot separately in the blockchain service's head struct. We shouldn't track it separately to prevent any disparity. The slot can cheaply be derived from the head block or head state. In this PR, we removed head slot tracking and used `block.slot`. You can use `state.slot` if people think that's better
=> Track head slot through head block

beacon-chain/execution/engine_client.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go
Code health error improvement
```
[2023-01-07 19:36:02] ERROR sync: Could not get reconstruct full bellatrix block from blinded body error=block hash field in execution header 0x21295832b07679e17f9c3e2ed8edafae28ac15deeac6cdcb8e0ddc68526c2b0d does not match execution block hash 0x0000000000000000000000000000000000000000000000000000000000000000 handler=beacon_blocks_by_root
```
👇🏼 
```
[2023-01-08 08:44:36]  WARN sync: Could not reconstruct block from header with syncing execution client. Waiting to complete syncing error=Block hash is empty 0x0000... handler=beacon_blocks_by_root
```
Fixes #
=> Better reconstruct error msg while EL client is syncing

beacon-chain/rpc/statefetcher/fetcher.go, beacon-chain/rpc/statefetcher/fetcher_test.go
Bug fix
The following error is observed in Lighthouse validator's logs during multi-client e2e:
```
Could not get state: requested slot number is higher than head slot number
```
This happens when there are skipped slots between head state slot and current slot. When fetching state by slot we should replay the state up to the current slot instead of returning an error.
=> Replay state to current slot in `StateBySlot`

beacon-chain/operations/blstoexec/pool.go, beacon-chain/operations/blstoexec/pool_test.go
See this discussion for context: 
https://discord.com/channels/595666850260713488/892088344438255616/1065818533403037806
TL;DR: this encourages users with uncompromized keys to not flood at the fork boundary
=> Use LIFO instead of FIFO when packing BLS changes

beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/blockchain/receive_block.go, beacon-chain/blockchain/receive_block_test.go, beacon-chain/operations/blstoexec/BUILD.bazel, beacon-chain/operations/blstoexec/mock/mock.go, beacon-chain/operations/blstoexec/pool.go, beacon-chain/operations/blstoexec/pool_test.go
Cleanup
- move `handleBlockBLSToExecChanges` to `handlePostBlockOperations`, next to exit handling
- small fixes to the pool itself
=> Refactor BLS change pool

beacon-chain/sync/validate_bls_to_execution_change.go, beacon-chain/sync/validate_bls_to_execution_change_test.go
Use only wall clock when gossiping BLS changes
=> Do not check headstate being Capella for BLS changes on gossip

beacon-chain/rpc/apimiddleware/endpoint_factory.go
Return correct JSON structure when erroring sending BLS changes. 
credit to @james-prysm for finding this one out.
=> Return error structures from bls changes endpoint

beacon-chain/blockchain/chain_info_norace_test.go, beacon-chain/blockchain/head_sync_committee_info_test.go, beacon-chain/state/stategen/getter.go, beacon-chain/state/stategen/service.go
Credit to @nisdas for finding this issue and to @kasey for solving it
Only lookup genesis root and then use the cache
=> save genesis state to hot cache and do not look it up from disk

beacon-chain/rpc/eth/validator/validator.go, beacon-chain/rpc/eth/validator/validator_test.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go
Bug fix
This PR fixes a bug in the PrepareBeaconProposer API which is duplicating validator indexes when not persisted in DB, it does not disrupt the feature for users and is only done at startup and dynamic changes to fee recipient. It however can double the size of the request as well as printing duplicates in log. A unit test was added to catch similar errors in the future.
=> PrepareBeaconProposer: bug fix

beacon-chain/sync/pending_blocks_queue_test.go, beacon-chain/sync/rpc_blobs_sidecars_by_range.go, beacon-chain/sync/rpc_blobs_sidecars_by_range_test.go
This fixes RPC client timeouts induced by the rate limiter by ensuring blobs are streamed once there exists a token available (typically 1 second).
cc: @terencechain
=> sync: Fix BlobsSidecarByRange rate limiting

beacon-chain/core/signing/signing_root.go, beacon-chain/core/signing/signing_root_test.go
Optimization
Computing the fork digest is a very hot path in gossip, we have to compute the digest for each message we 
receive in gossip. This PR caches the computation, so that we can easily received the result through a map. Also
a relevant unit test is added here.
N.A
=> Cache Fork Digest Computation

WORKSPACE, beacon-chain/core/signing/signing_root.go
Protects a digest map introduced into the signing package with a lock for thread-safe access.
This PR also updates the grail Bazel toolchain sha to 6889426c946f1b948a22468aaa73252d477c306cb550d5db09c330af9a810cee, as this changed due to a Github problem. See https://twitter.com/thesayynn/status/1620129657977987073 for information on what happened at the time of writing on Jan 30, 2023
=> Update Bazel Grail Toolchain SHA and Protect Digest Map with Lock

WORKSPACE
Build Fix
Github decided to revert their change which affected the sha256 computation of archives. 
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/ , This necessitates us changing it back again.
N.A
=> Revert Bazel Hash Change

beacon-chain/p2p/broadcaster.go, beacon-chain/p2p/broadcaster_test.go, beacon-chain/p2p/interfaces.go, beacon-chain/p2p/testing/fuzz_p2p.go, beacon-chain/p2p/testing/mock_broadcaster.go, beacon-chain/p2p/testing/p2p.go, beacon-chain/rpc/eth/beacon/pool.go, beacon-chain/rpc/eth/beacon/pool_test.go, beacon-chain/sync/broadcast_bls_changes.go, beacon-chain/sync/broadcast_bls_changes_test.go
This PR fixes a critical bug on develop where we would attempt broadcast nil objects at the fork boundary of Capella. 
It also fixes another bug in that some of the broadcast objects may be invalid at the time they are broadcast (since they could have been inserted in a different block between batches)
As discussed offline,  there is code duplication due to the fact that the verifier needs to have access to the head state, and the sync and rpc package do not have access to a shared package with this information. This is considered to be mild in that we can remove this PR entirely after the Capella fork has passed.
=> Rate limit broadcasting of BLS changes at the fork and at RPC endpoint

beacon-chain/blockchain/BUILD.bazel, beacon-chain/blockchain/error.go, beacon-chain/blockchain/mock_test.go, beacon-chain/blockchain/state_balance_cache.go, beacon-chain/blockchain/state_balance_cache_test.go
Avoid code duplication, this is useful in starting to get rid of the justified balance cache and move to tracking this on forkchoice.
=> reuse code from stategen in the justified balance cache

validator/client/beacon-api/beacon_api_validator_client.go, validator/client/beacon-api/duties.go, validator/client/beacon-api/sync_committee.go, validator/client/beacon-api/sync_committee_test.go
Feature
**Related issue**
#11580 
It adds REST API implementation for `GetSyncSubcommitteeIndex`.
=> add REST implementation for GetSyncSubcommitteeIndex

beacon-chain/blockchain/chain_info.go, beacon-chain/blockchain/process_block.go, beacon-chain/blockchain/process_block_helpers.go, beacon-chain/blockchain/process_block_test.go, beacon-chain/forkchoice/doubly-linked-tree/forkchoice.go, beacon-chain/forkchoice/doubly-linked-tree/forkchoice_test.go, beacon-chain/forkchoice/doubly-linked-tree/on_tick.go, beacon-chain/forkchoice/doubly-linked-tree/optimistic_sync.go, beacon-chain/forkchoice/doubly-linked-tree/proposer_boost.go, beacon-chain/forkchoice/doubly-linked-tree/store_test.go, beacon-chain/forkchoice/interfaces.go
This PR cleans up some methods that do not need to be exported from ForkChoice: 
- Removes AllTipsAreInvalid and embedds the only usage in `IsOptimistic`
- Renames InsertOptimisticChain to InsertChain
- Removes the Proposer Boost interface since the full logic is handled in Forkchoice
- Removes HasParent and simply use AncestorRoot from forkchoice. 
There are some more exported methods that can be removed (VotedFraction is removed in a serparate open PR) like the ones only used in tests, but those will not contribute to the reentrancy rework that we are initializing with this work.
=> Forkchoice interface cleanup

WORKSPACE
Other
Trying to build Prysm from a new machine with no caches and I am seeing that the sha value has changed. Perhaps the tar.gz was re-uploaded with different contents?
> ERROR: Analysis of target '//testing/spectest/general/phase0/bls:go_default_test' failed; build aborted: no such package '@consensus_spec_tests_general//': java.io.IOException: Error downloading [https://github.com/ethereum/consensus-spec-tests/releases/download/v1.3.0-rc.2-hotfix/general.tar.gz] to /home/preston/.cache/bazel/_bazel_preston/6e220e5720b8243fd605645eb29a29ba/external/consensus_spec_tests_general/temp17786787663920944455/general.tar.gz: Checksum was 11fed0121d7a79b6da3671ecbd8aa08bcd3fc2316450eeae2d0e065371910ef9 but wanted …
=> Update general spectest tar.gz SHA value

beacon-chain/operations/blstoexec/BUILD.bazel, beacon-chain/operations/blstoexec/pool.go, beacon-chain/operations/blstoexec/pool_test.go
When packing BLS changes, it is no longer needed to check their signature since we moved to using the genesis fork version.
=> Do not check signatures when packing BLS changes

WORKSPACE, config/params/loader_test.go
Update spec tests to `v1.3.0-rc.3` to align with https://github.com/ethereum/consensus-specs/releases/tag/v1.3.0-rc.3
=> Add `v1.3.0-rc.3` spec tests

beacon-chain/rpc/prysm/v1alpha1/validator/proposer_capella.go, beacon-chain/rpc/prysm/v1alpha1/validator/proposer_capella_test.go
We can better check the correctness of an unblinded block from mev-boost. The check is simple, we validate the header matches the payload by hash tree root each other. If they don't match, we should surface the error and don’t broadcast a bad block because we do not want to get penalized by our peers. Today we would broadcast a bad block which opens up to builder/relayer griefing attack
=> Check unblinded payload root before proposal

api/client/builder/client.go
Cleanup
Removes unused function. Capella blocks are handled in `SubmitBlindedBlock`.
=> Remove `SubmitBlindedBlockCapella`

api/client/builder/client.go, api/client/builder/client_test.go
Feature
Implements [ethereum/builder-specs@`e570404` (#60)](https://github.com/ethereum/builder-specs/pull/60/commits/e570404814e08d787bb9dd58f46f2714bd1f73f3)
=> Add `Eth-Consensus-Version` header to `SubmitBlindedBlock`

beacon-chain/blockchain/process_attestation_test.go, beacon-chain/blockchain/receive_attestation.go, beacon-chain/blockchain/testing/mock.go, beacon-chain/sync/pending_attestations_queue.go, beacon-chain/sync/validate_aggregate_proof.go, beacon-chain/sync/validate_beacon_attestation.go
Forkchoice enforces that all nodes are consistent with finalized checkpoint.
=> Use forkchoice HasNode to check if a block is consistent with finality

validator/client/beacon-api/beacon_api_validator_client.go, validator/client/grpc-api/grpc_validator_client.go, validator/client/iface/validator_client.go
Feature
It removes the `StreamDuties` endpoint from the beacon/grpc validator clients.
I didn't remove the `StreamDuties` endpoints from the protobuf files since it's already marked as deprecated and third parties may be depending on it.
=> Remove the StreamDuties endpoint

validator/client/beacon-api/beacon_api_validator_client.go, validator/client/validator-client-factory/validator_client_factory.go
Feature
It removes the gRPC fallback client from the validator REST API. Since all endpoints are now implemented, we don't need it anymore!
=> Remove the gRPC fallback client from the validator REST API

WORKSPACE, tools/BUILD.bazel
Other
Updates the base images to solve some HIGH and MEDIUM level CVE reports
```
gcr.io/prysmaticlabs/prysm/beacon-chain:latest (debian 11.5)
============================================================
Total: 21 (UNKNOWN: 0, LOW: 11, MEDIUM: 4, HIGH: 6, CRITICAL: 0)
┌───────────┬──────────────────┬──────────┬───────────────────┬──────────────────┬─────────────────────────────────────────────────────────────┐
│  Library  │  Vulnerability   │ Severity │ Installed Version │  Fixed Version   │                            Title                            │
├───────────┼──────────────────┼──────────┼───────────────────┼──────────────────┼─────────────────────────────────────────────────────────────┤
│ libc6     │ …
```
=> Update distroless base images

beacon-chain/blockchain/process_block.go
Add head locks and simplyfy routine
=> lock head on fillMissingBlockPayload

validator/client/propose.go
Other
Knowing the slot number aids debugging.
=> Add slot to proposal error logs

beacon-chain/node/node.go, beacon-chain/server/main.go, cmd/flags.go, testing/endtoend/component_handler_test.go
Bug fix
Some users may have hit gRPC max message sizes when running large number of validator keys. For example, requesting the epoch duties for thousands of validators by public key may result in a message larger than 4Mb.
Fixes #11983
=> Raise the max grpc message size to a very large value by default

WORKSPACE, config/params/testnet_prater_config.go
Reference: https://github.com/eth-clients/goerli/pull/160/
=> Add capella fork epoch for Goerli

beacon-chain/blockchain/process_block.go, beacon-chain/state/stategen/getter.go
When retrieving balances by Root for forkchoice, use the epoch boundary cache to retrieve the justified checkpoint balances
=> Use Epoch boundary cache to retrieve balances

api/client/beacon/checkpoint.go
These two log messages were appending a `d` to the hash. When compared to the other hash, they matched up until the `d`
>
Bug fix
> Feature
> Other
Fixes #
=> Fix log messages

encoding/bytesutil/BUILD.bazel, encoding/bytesutil/bytes_go120.go, encoding/bytesutil/bytes_legacy.go
Bug fix
We're hitting a quirk of go modules and go build tags whereby using a go 1.20 compiler when trying to use prysm as a dependency, or attempting to build prysm directly by specifying it's package path, will fail. Example:
```
$ go build -o bc github.com/prysmaticlabs/prysm/v3/cmd/beacon-chain
^[# github.com/prysmaticlabs/prysm/v3/encoding/bytesutil
encoding/bytesutil/bytes_go120.go:12:17: cannot convert PadTo(x, 4) (value of type []byte) to type [4]byte: conversion of slices to arrays requires go1.20 or later (-lang was set to go1.19; check go.mod)
encoding/bytesutil/bytes_go120.go:19:18: cannot convert PadTo(x, 20) (value of type []byte) to type [20]byte: conversion of slices to arrays requires go1.20 or later …
```
=> Disable conditional go 1.20 code until module is also at 1.20

WORKSPACE, tools/BUILD.bazel
Other
Bazel maintenance. The @bazel pkg_tar has been deprecated and will no longer work in bazel 6.x
See https://github.com/bazelbuild/bazel/issues/8857
=> Replace @bazel pkg_tar rule with canonical @rules_pkg pkg_tar

config/features/config.go, config/features/flags.go
Invert feature flag to reorg late blocks by default
=> Invert reorg of late blocks flag

testing/endtoend/evaluators/slashing.go, testing/endtoend/minimal_slashing_e2e_test.go
Bug Fix
The E2E run constantly fails on all PRs. This test has a high failure rate, so it is better to disable it before we
have it as a presubmit requirement in our CI . #12116 was recently merged in and it appears those evaluators that were re-enabled might not be working at all. 
N.A
=> Disable E2E Run For Slasher

beacon-chain/blockchain/process_block.go
> Bug fix
When we sent the missing slot event downstream, we sent it every 4s. Instead, we should send it when there's a missing slot, meaning the head slot is not at the current slot at the 4s mark.
=> Send missing slot event at the correct place

beacon-chain/db/iface/interface.go, beacon-chain/db/kv/BUILD.bazel, beacon-chain/db/kv/blob.go, beacon-chain/db/kv/blob_test.go, proto/prysm/v1alpha1/blobs.pb.go, proto/prysm/v1alpha1/blobs.proto
Add db methods to store blobs.
- New prysm-only container `BlobSidecars`. Easier than passing around and hashing individual `BlobSidecar`. We can assume everything stores in the DB is verified and complete
- New getters `BlobSidecarsByRoot` and  `BlobSidecarsBySlot`
- New getters `SaveBlobSidecar` and `DeleteBlobSidecar`
- `SaveBlobSidecar` rotates by converting slot using a modulo operator. In other words, we write over the old blob rather than delete the blob for free list. Kudos to @rauljordan for this idea
=> Add blob db methods

consensus-types/blocks/getters.go
Bug fix
The helper to get the blinded form copies the unblinded block field-by-field. It was missing the `BlobKzgCommitments` field, which resulted in deneb block db save -> read round trips to lose their `BlobKzgCommitments` value.
=> add missing field to proto copy helper

beacon-chain/p2p/BUILD.bazel, beacon-chain/p2p/monitoring.go, beacon-chain/p2p/pubsub.go, beacon-chain/p2p/pubsub_tracer.go
Feature
Adds in a new raw tracer whose main purpose is to record metrics from messages broadcasted and received by our gossipsub router. 
N.A
=> Add Pubsub Metrics Tracer

beacon-chain/rpc/prysm/v1alpha1/validator/proposer.go, beacon-chain/sync/blobs_test.go, beacon-chain/sync/rpc_beacon_blocks_by_root.go, beacon-chain/sync/rpc_blob_sidecars_by_range_test.go, beacon-chain/sync/rpc_blob_sidecars_by_root.go, beacon-chain/sync/rpc_blob_sidecars_by_root_test.go, beacon-chain/sync/rpc_chunked_response.go, beacon-chain/sync/rpc_send_request.go
This PR extracts the fixes from #12184 
We got blob by root end to end testing to work at the end with several fixes:
- Validator correctly saves blobs to the DB
- Using the correct encoding and decoding for blob chunk
- Properly closing the stream
=> Blob by root fixes
